etcd-io/etcd

CHANGELOG/CHANGELOG-3.5.md

Update 3.5 changelog to cover the two bug fixes related to leases revoke and checkpoint

---

contrib/raftexample/raftexample_test.go

Please see [https://github.com/etcd-io/etcd/runs/6772474782?check_suite_focus=true](https://github.com/etcd-io/etcd/runs/6772474782?check_suite_focus=true ) 
```
Write at 0x00c003019510 by goroutine 177:
runtime.closechan()
/opt/hostedtoolcache/go/1.17.8/x64/src/runtime/chan.go:355 +0x0
go.etcd.io/etcd/v3/contrib/raftexample.(*cluster).Close()
/home/runner/work/etcd/etcd/contrib/raftexample/raftexample_test.go:84 +0x317
go.etcd.io/etcd/v3/contrib/raftexample.(*cluster).closeNoErrors()
/home/runner/work/etcd/etcd/contrib/raftexample/raftexample_test.go:98 +0x6e
go.etcd.io/etcd/v3/contrib/raftexample.TestCloseProposerInflight·dwrap·19()
/home/runner/work/etcd/etcd/contrib/raftexample/raftexample_test.go:153 +0x47 …
```

Fix the DATA RACE issue of TestCloseProposerInflight

---

server/embed/config.go

Update link to tuning page

---

server/etcdserver/api/v3compactor/periodic.go
server/etcdserver/api/v3compactor/periodic_test.go

skip compact when rev not change at period compact mode

---

server/etcdserver/api/snap/snapshotter.go

Signed-off-by: L2ncE <llance_24@foxmail.com>

Fix a syntax error in a code comment

---

pkg/schedule/schedule.go
pkg/schedule/schedule_test.go
server/etcdserver/server.go
server/storage/mvcc/kvstore.go
server/storage/mvcc/kvstore_test.go

To make the fifo scheduler better debuggability.

schedule: Provide logs when the fifo job panic happens

---

client/v3/client_test.go

fix #14161 
Signed-off-by: chavacava <salvadorcavadini+github@gmail.com>

fix #14161

---

server/verify/verify.go

Make the code simple and clear.

verify: Get backend using simple api

---

server/proxy/grpcproxy/auth.go
server/proxy/grpcproxy/election.go
server/proxy/grpcproxy/lock.go
server/proxy/grpcproxy/maintenance.go

Avoid repeated creation of pb objects.

proxy: Put the pb object into the struct

---

tests/functional/runner/lease_renewer_command.go

Closes #14162 
Signed-off-by: chavacava <salvadorcavadini+github@gmail.com>

fix #14162

---

CHANGELOG/CHANGELOG-3.4.md

Update 3.4 change log to cover fixes for two issues

---

etcdctl/README.md

Fix a typo in etcdctl readme for the elect command

---

scripts/release.sh

Update scripts/release.sh to remove message related to travis.yml

---

CHANGELOG/CHANGELOG-3.4.md

update v3.4.19 release date

---

Documentation/contributor-guide/release.md

As proposed in https://github.com/etcd-io/etcd/issues/13912
cc @ahrtr

Make Benjamin an official v3.4 release manager

---

client/pkg/fileutil/fileutil.go

Fix syntax errors in comments
Signed-off-by: sky li (李少凯)-浪潮数据 <lishaokai1995@126.com>

Fix syntax errors in comments

---

contrib/mixin/mixin.libsonnet

This PR changes alert `etcdBackendQuotaLowSpace` to `etcdDatabaseQuotaLowSpace`
cc @ahrtr @spzala

etcd-mixin: fix etcdDatabaseQuotaLowSpace alert name

---

CHANGELOG/CHANGELOG-3.4.md

Update changelog for 3.4.20

---

clientv3/balancer/balancer_test.go

- ignore "transport is closing" error during connections warmup after stopping one peer.

[3.4] clientv3/balancer: fixed flaky TestRoundRobinBalancedResolvableFailoverFromServerFail

---

server/auth/simple_token.go
server/auth/store_test.go
server/embed/serve.go

fix: code cleanup

---

contrib/lock/README.md
contrib/lock/client/client.go
contrib/lock/storage/storage.go

fixing issue described in https://github.com/etcd-io/etcd/issues/14224

update contrib/lock example

---

CHANGELOG/CHANGELOG-3.4.md

Update the release date for 3.4.20

---

client/v3/client.go

more logging around auto sync

---

tests/functional/agent/handler.go
tests/functional/agent/server.go
tests/functional/agent/utils.go
tests/functional/cmd/etcd-tester/etcd_tester_test.go

Get duplicated code wraped in common functions, and simplify error handling.

Improve functional test code

---

CHANGELOG/CHANGELOG-3.5.md

Refer to https://github.com/etcd-io/etcd/pull/14366,
Also refer to https://github.com/etcd-io/etcd/pull/14356
cc @spzala @serathius

Update changelog-3.5 to cover the change for refactoring the keepAliveListener and keepAliveConn

---

tests/integration/clientv3/connectivity/network_partition_test.go

This fixes ci flakes where timeouts are expected to happen in network
partitions.
issue: https://github.com/etcd-io/etcd/issues/14333

Add ErrTimeoutDueToLeaderFail as expected error

---

README.md

Readme: Removed unnecessary comma.

---

tests/e2e/cluster_downgrade_test.go
tests/e2e/corrupt_test.go
tests/e2e/ctl_v3_auth_test.go
tests/e2e/ctl_v3_grpc_test.go
tests/e2e/ctl_v3_make_mirror_test.go
tests/e2e/ctl_v3_move_leader_test.go
tests/e2e/ctl_v3_snapshot_test.go
tests/e2e/ctl_v3_test.go
tests/e2e/discovery_test.go
tests/e2e/discovery_v3_test.go
tests/e2e/etcd_config_test.go
tests/e2e/etcd_release_upgrade_test.go
tests/e2e/gateway_test.go
tests/e2e/utl_migrate_test.go
tests/e2e/v2store_deprecation_test.go
tests/e2e/v3_curl_maxstream_test.go
tests/e2e/zap_logging_test.go
tests/framework/e2e.go
tests/framework/e2e/cluster.go
tests/framework/e2e/cluster_proxy.go
tests/framework/e2e/etcd_process.go
tests/framework/e2e/util.go
tests/framework/integration.go
tests/framework/interface.go

tests: Add context to e2e cluster start

---

.github/workflows/static-analysis.yaml
CONTRIBUTING.md

Signed-off-by: Cenk Alti <cenkalti@gmail.com>

Setup golangci-lint GitHub action

---

server/etcdmain/grpc_proxy.go
tests/e2e/etcd_grpcproxy_test.go

Backport of feature/bug fix from https://github.com/etcd-io/etcd/pull/14354 (as we discussed in https://github.com/etcd-io/etcd/pull/14354#issuecomment-1228258618).

Backport of pull/14354 to release-3.5

---

CHANGELOG/CHANGELOG-3.5.md
CHANGELOG/CHANGELOG-3.6.md

Document compact-hash-check flags in changelog

---

integration/v3_auth_test.go

[release-3.4] Fix the flaky test TestV3AuthRestartMember

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md
CHANGELOG/CHANGELOG-3.6.md

1. authentication data not loaded on member startup
2. etcdctl move-leader may fail for multiple endpoints

Updated changelog to cover the two issues

---

client/pkg/fileutil/fileutil.go
client/pkg/fileutil/fileutil_test.go
client/pkg/transport/listener.go
client/pkg/transport/listener_test.go

There is no response on https://github.com/etcd-io/etcd/pull/13947 for a long time, so fix it in this PR.
cc  @serathius @mitake @spzala

add verification on nil log

---

pkg/ioutil/pagewriter.go
pkg/ioutil/pagewriter_test.go

There is no response on https://github.com/etcd-io/etcd/pull/14022 for a long time, so finish it in this PR. 
cc  @serathius @mitake @spzala

add a verification on the pagebytes which must be > 0

---

tests/integration/v3_auth_test.go

cc @serathius @mitake @spzala 
Please also review https://github.com/etcd-io/etcd/pull/14453

[release-3.5] fix the flaky test TestV3AuthRestartMember

---

pkg/expect/expect.go
tests/e2e/ctl_v3_auth_test.go
tests/framework/e2e/cluster.go
tests/framework/e2e/cluster_proxy.go
tests/framework/e2e/etcd_process.go
tests/framework/e2e/etcd_spawn_cov.go

Just some cleanup of expect

---

tests/framework/integration/cluster.go
tests/integration/v3_auth_test.go

Integration_test: fix the flaky test TestV3AuthRestartMember

---

CONTRIBUTING.md
Makefile
README.md

Ref https://github.com/etcd-io/etcd/issues/14243
cc @ptabor @ahrtr @spzala

Improve contributor guidelines and simplify development commands

---

server/storage/mvcc/key_index.go
server/storage/mvcc/key_index_test.go
server/storage/mvcc/revision.go

Signed-off-by: Hongfei Huang <853885165@qq.com>

mvcc: Remove unused revisions and change comment rev to modified

---

.github/workflows/measure-test-flakiness.yaml

Fix measuring test flakiness

---

.github/workflows/measure-test-flakiness.yaml

really fix measure-test-flakiness

---

pkg/osutil/interrupt_unix.go
server/etcdmain/etcd.go

Signed-off-by: kkkkun <scuzk373x@gmail.com>
Clean up some redundant log messages

remove redundant log messsages

---

CHANGELOG/CHANGELOG-3.5.md

Update changelog for v3.5.5 release

---

.github/workflows/static-analysis.yaml
CONTRIBUTING.md
Makefile

makefile: Make static analysis commands easier to use

---

Makefile
scripts/test.sh

makefile: Split fmt into separate verify commands

---

Documentation/contributor-guide/features.md

Related https://github.com/etcd-io/etcd/pull/14428
Signed-off-by: Sahdev Zala <spzala@us.ibm.com>

Doc: Add feature graduation and deprecation policies

---

client/v2/README.md
client/v3/kv.go
client/v3/retry_interceptor_test.go
contrib/raftexample/raft_test.go
server/etcdserver/api/v3discovery/discovery.go
server/etcdserver/api/v3rpc/key_test.go
tests/integration/v3_failover_test.go

golang CodeReviewComments:
https://github.com/golang/go/wiki/CodeReviewComments#imports

etcd: format import order

---

.github/workflows/static-analysis.yaml
CONTRIBUTING.md
Makefile

Improve static analysis fixing scripts

---

server/etcdserver/api/membership/member.go
server/etcdserver/api/membership/member_test.go

PickPeerURL only used by unit test
Signed-off-by: Hongfei Huang <853885165@qq.com>

membership: Remove PickPeerURL Method

---

.golangci.yaml

golangci: add unconvert check

---

.golangci.yaml
tools/benchmark/cmd/util.go
tools/benchmark/cmd/watch_latency.go
tools/etcd-dump-db/backend.go
tools/etcd-dump-logs/etcd-dump-log_test.go
tools/etcd-dump-logs/main.go
tools/proto-annotations/cmd/etcd_version.go

golangci: add import order check

---

tests/e2e/ctl_v3_snapshot_test.go
tests/e2e/etcd_release_upgrade_test.go
tests/e2e/gateway_test.go
tests/framework/e2e/etcd_spawn_cov.go
tests/framework/e2e/etcd_spawn_nocov.go
tests/framework/e2e/etcdctl.go
tests/framework/e2e/flags.go
tests/functional/README.md
tests/manual/docker-dns-srv/certs-gateway/run.sh
tests/manual/docker-dns-srv/certs-wildcard/run.sh
tests/manual/docker-dns-srv/certs/run.sh
tests/manual/docker-dns/certs-common-name-auth/run.sh
tests/manual/docker-dns/certs-common-name-multi/run.sh
tests/manual/docker-dns/certs-gateway/run.sh
tests/manual/docker-dns/certs-san-dns/run.sh
tests/manual/docker-dns/certs-wildcard/run.sh
tests/manual/docker-dns/certs/run.sh
tests/manual/docker-dns/insecure/run.sh
tests/manual/docker-static-ip/certs-metrics-proxy/run.sh
tests/manual/docker-static-ip/certs/run.sh

Remove mention of ETCDCTL_API environment variable as it was removed from etcdctl

---

embed/etcd.go
pkg/fileutil/purge.go

Backport https://github.com/etcd-io/etcd/pull/14576 to 3.4.
cc @spzala @serathius @mitake

[3.4] etcdserver: added more debug log for the purgeFile goroutine

---

clientv3/integration/watch_test.go

Backport #14591 to 3.4.
Signed-off-by: 王霄霄 1141195807@qq.com

Backport #14591 to 3.4.

---

tests/framework/e2e/etcd_spawn_cov.go
tests/framework/e2e/flags.go
tests/framework/integration/cluster.go
tests/framework/integration/testing.go
tests/framework/testutils/path.go
tests/integration/clientv3/connectivity/dial_test.go
tests/integration/embed/embed_test.go
tests/integration/snapshot/v3_snapshot_test.go

tests: Move MustAbsPath function to testutils

---

tests/framework/e2e/etcdctl.go

Signed-off-by: Oleg Guba <oleg@dropbox.com>

[e2e] Fix bug in EtcdctlV3.HashKV() e2e implementation.

---

server/lease/lease_queue_test.go
server/lease/lessor.go

lessor: simplify expireExists to make it more clear

---

raft/raft.go

raft: remove duplicate letter in comment.
Signed-off-by: Wang Xiaoxiao 1141195807@qq.com

raft: remove duplicate letter in comment.

---

tools/etcd-dump-db/backend.go

Signed-off-by: qsyqian <qsyqian@gmail.com>

etcd-dump-db: enhance metaDecoder

---

client/v3/maintenance.go

fix: close conn

---

.github/workflows/build.yaml
.github/workflows/contrib.yaml
.github/workflows/coverage.yaml
.github/workflows/e2e.yaml
.github/workflows/functional.yaml
.github/workflows/fuzzing.yaml
.github/workflows/grpcproxy.yaml
.github/workflows/linearizability.yaml
.github/workflows/release.yaml
.github/workflows/static-analysis.yaml
.github/workflows/tests.yaml
tests/functional/Dockerfile
tests/manual/Makefile

- update .github workflows
- update tests

*: bump to go1.19.2 from 1.19.1

---

server/embed/config.go

update per the review comment https://github.com/etcd-io/etcd/pull/14613#discussion_r1007385630

chore: update the warn message on startup when the server name is default

---

MAINTAINERS

cc @ahrtr @spzala @lilic @wilsonwang371

remove inactive reviewers

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

update changelogs of 3.4 and 3.5 for backporting PR 14574 and 14647

---

tests/functional/tester/cluster_run.go

1. Terminate functional test on failure so as to keep the environment, including log and data.
2. cleanup some duplicated code/log.
This PR can also fix https://github.com/etcd-io/etcd/actions/runs/3315011414/jobs/5475040546
cc @spzala @serathius @ptabor @mitake

test: terminate functional test on failure and code cleanup

---

client/v3/maintenance.go

[3.5] fix: close maintenance conn

---

MAINTAINERS

As discussed with @serathius and @ptabor[^1].
[^1]: https://github.com/etcd-io/etcd/pull/14238#issuecomment-1268281624

(Re-) add @tbg as maintainer

---

tests/common/auth_util.go
tests/common/maintenance_auth_test.go

test: fix pipeline errors due to PRs conflict

---

tests/common/e2e_test.go
tests/common/integration_test.go
tests/common/kv_test.go
tests/common/lease_test.go
tests/common/main_test.go
tests/common/member_test.go
tests/common/role_test.go
tests/common/status_test.go
tests/common/txn_test.go
tests/common/unit_test.go
tests/common/user_test.go
tests/common/wait_leader_test.go
tests/common/watch_test.go
tests/e2e/cluster_downgrade_test.go
tests/e2e/ctl_v3_test.go
tests/e2e/discovery_test.go
tests/e2e/etcd_release_upgrade_test.go
tests/e2e/utl_migrate_test.go
tests/e2e/v2store_deprecation_test.go
tests/framework/config/cluster.go
tests/framework/e2e/cluster.go
tests/framework/e2e/config.go
tests/framework/e2e/e2e.go
tests/framework/integration/integration.go

test: support mix versions testing 

---

server/etcdserver/cluster_util.go

etcdserver: fix log typo when checking version compatiblity

---

tests/framework/e2e/cluster.go

The struct `EtcdProcessClusterConfig` has over 30 fields already. The act of initialising `EtcdProcessClusterConfig` causes mental burden.
This PR is opened to refactor `EtcdProcessClusterConfig` using ***Functional Options Pattern***.
To make it easier to review. The refactor is broken down into 3 steps:
1. add `DefaultConfig`, `NewConfig` and `EPClusterOption`
2. replace all initialisations with `DefaultConfig`, `NewConfig` and `EPClusterOption`
3. rename anti-pattern-naming fields(`DisableStrictReconfigCheck` and `NoCN`) and move them to `DefaultConfig`
This PR is the 1st step.

tests: refactor `EtcdProcessClusterConfig` using Functional Options Pattern

---

tests/e2e/cluster_downgrade_test.go

This fix avoids the assumption of knowing the current version of the binary. We can query the binary with the version flag to get the actual version of the given binary we upgrade and downgrade to. The respectively reported versions should match what is returned by the version endpoint.

Take binary version in Downgrade/Upgrade Test

---

client/v3/concurrency/mutex.go
tests/integration/clientv3/concurrency/mutex_test.go

Check the values of myKey and myRev first in Unlock method to prevent calling Unlock without Lock. Because this may cause the value of pfx to be deleted by mistake.
Signed-off-by: chenyahui <cyhone@qq.com>

etcdclient: check mutex state in Unlock method of concurrency.Mutex

---

raft/storage_test.go
raft/util_test.go

feat: use testify packages in tests

---

CHANGELOG/CHANGELOG-3.5.md

changelog: add item for 3.5 to cover the revision inconsistency issue

---

tests/linearizability/linearizability_test.go
tests/linearizability/model.go
tests/linearizability/traffic.go

tests: Make linearizability traffic extendable

---

client/pkg/fileutil/lock_windows.go
client/pkg/testutil/leak.go
client/pkg/transport/keepalive_listener.go
client/pkg/transport/listener.go
client/pkg/transport/sockopt_solaris.go
client/pkg/transport/sockopt_windows.go
client/pkg/transport/tls.go
client/v2/client.go
client/v2/client_test.go
client/v3/client.go
client/v3/client_test.go
client/v3/concurrency/key.go
client/v3/logger.go
client/v3/watch.go

Signed-off-by: Sasha Melentyev <sasha@melentyev.io>

client: Use func without format

---

server/etcdserver/api/v2store/store_ttl_test.go
tests/e2e/ctl_v3_auth_test.go

Signed-off-by: Sasha Melentyev <sasha@melentyev.io>

all: Change time unit

---

server/storage/backend/backend.go
server/storage/backend/batch_tx.go
tests/linearizability/failpoints.go

etcdserver: add failpoints for backend

---

scripts/build_lib.sh
server/storage/mvcc/kvstore.go
server/storage/mvcc/kvstore_compaction.go
tests/framework/e2e/cluster.go
tests/linearizability/failpoints.go
tests/linearizability/linearizability_test.go

Part of https://github.com/etcd-io/etcd/issues/14735
cc @ahrtr

Linearizability compact

---

contrib/lock/client/client.go
etcdctl/ctlv3/command/member_command.go
etcdctl/ctlv3/command/printer_fields.go
etcdctl/ctlv3/command/printer_simple.go
etcdctl/ctlv3/command/user_command.go
pkg/report/report.go
raft/tracker/progress.go
raft/tracker/tracker.go
raft/util.go
server/etcdserver/api/etcdhttp/debug.go
server/etcdserver/api/rafthttp/stream_test.go
server/main_test.go
tests/e2e/ctl_v3_move_leader_test.go
tests/e2e/metrics_test.go
tests/functional/tester/stresser_lease.go
tests/integration/embed/embed_test.go
tools/benchmark/cmd/util.go
tools/etcd-dump-logs/main.go

Signed-off-by: Sasha Melentyev <sasha@melentyev.io>

all: Change Printf and friends to Print if there is no formatting

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

changelog: add items to cover the issue of refreshing token on CommonName based authentication

---

tests/e2e/ctl_v3_elect_test.go
tests/e2e/ctl_v3_lock_test.go

waiting for a proper exit after a signal should ensure the goroutines don't leak.

Fix TestCtlV3Lock/Elect flakes

---

.github/workflows/govuln.yaml

.github: make govuln-check generic

---

pkg/expect/expect_test.go

fix TestSignal test

---

etcdctl/go.sum
etcdutl/go.sum

I forgot to execute ./script/fix.sh in previous PR. :(
cc @serathius

fix release pipeline failure

---

server/storage/wal/util.go
server/storage/wal/wal.go
server/storage/wal/wal_test.go

Add more debug info for debugging issue something like https://github.com/etcd-io/etcd/issues/14851 .
It's hard to tell where is the error coming from. So added more context in the error log.

add more debug info for opening WAL files failure

---

tests/e2e/etcd_mix_versions_test.go

Signed-off-by: WangXiaoxiao <1141195807@qq.com>

test: fix typo

---

CHANGELOG/CHANGELOG-3.6.md

cc @ptabor @serathius @spzala @tbg

changelog: added item for the decoupling raft from etcd in 3.6

---

tests/framework/e2e/cluster_proxy.go
tests/framework/e2e/etcd_process.go
tests/linearizability/failpoints.go

Allow failpoint requests to fail assuming that process exists within 1 second

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

changelog: add items for the nil pointer panic of readonly txn

---

server/etcdserver/server_access_control_test.go

tests(etcdserver): add `server_access_control_test.go`

---

tests/framework/e2e/cluster_proxy.go

We should call Wait for grpc-proxy process stop before start. Otherwise, the tcp port won't be released.
Fixes: #14926

e2e: deflake TestCtlV3AuthGracefulDisable

---

tests/integration/clientv3/maintenance_test.go

~~The gRPC stream sender calls the SnapshotResponse.Marshal to get the payload and the SnapshotResponse.Marshal always copies the Blob.There is no need to re-allocate buffer for each block.~~
~~REF: https://github.com/etcd-io/etcd/blob/dafc1ade48642a86f3e94cb8204c8a9793a23a95/api/etcdserverpb/rpc.pb.go#L9616-L9650~~
~~Revert: #12129~~
maintenance: add test to verify content of Snapshot

maintenance: add test to verify content of Snapshot

---

client/v3/concurrency/session.go
tests/integration/clientv3/concurrency/session_test.go

Signed-off-by: Ramil Mirhasanov <ramil600@yahoo.com>

clientv3/concurrency: add logger to session, add unit test

---

client/v3/client_test.go

test(client): add `TestIsUnavailableErr`

---

Dockerfile-release.amd64
Dockerfile-release.arm64
Dockerfile-release.ppc64le
Dockerfile-release.s390x
nsswitch.conf
scripts/build-docker.sh

remove the dependency on busybox

---

Dockerfile-release
Dockerfile-release.arm64
Dockerfile-release.ppc64le
nsswitch.conf
scripts/build-docker.sh

Backport https://github.com/etcd-io/etcd/pull/15036 to 3.4

3.4: remove the dependency on busybox

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

Changelog: update base image to static-debian11 and removd dependency on busybox

---

nsswitch.conf

Backport https://github.com/etcd-io/etcd/pull/15040 to 3.5.

[3.5] Update nsswitch.conf for 3.5

---

nsswitch.conf

Backport https://github.com/etcd-io/etcd/pull/15040 to 3.4.

[3.4] Update nsswitch.conf for 3.4

---

server/etcdserver/server.go

etcdserver: fix typo in comment

etcdserver: fix typo in comment

---

etcdctl/ctlv3/command/printer_simple.go
tests/e2e/ctl_v3_member_test.go
tests/framework/integration/cluster.go

Signed-off-by: wafuwafu13 <mariobaske@i.softbank.jp>

enhancement(ctlv3): display `as learner` when member add as learner

---

client/v3/options.go

Signed-off-by: WangXiaoxiao <1141195807@qq.com>

client/v3: fix comment typo

---

tests/framework/e2e/cluster_proxy.go
tests/framework/e2e/etcd_process.go
tests/linearizability/failpoints.go
tests/linearizability/linearizability_test.go

tests: Trigger only failpoints available in binary

---

tests/linearizability/traffic.go

Maybe due addition of leases, but I noticed increases number of request timeout even without any failure injections. 
cc @ahrtr @ptabor @geetasg

tests: Fix putWithLease traffic timeout/limit and double overall timeout to reduce number of failed requests

---

.github/workflows/codeql-analysis.yml
.github/workflows/scorecards.yml
client/v3/go.mod
client/v3/go.sum
etcdctl/go.mod
etcdctl/go.sum
etcdutl/go.mod
etcdutl/go.sum
go.mod
go.sum
pkg/go.mod
pkg/go.sum
server/go.mod
server/go.sum
tests/go.mod
tests/go.sum
tools/mod/go.mod
tools/mod/go.sum

dependabot automaticaly bumped the dependencies, but unfortunately it doesn't execute "./scripts/fix.sh", and it also created a PR for each module.

Bump some dependencies

---

tests/linearizability/client.go
tests/linearizability/identity/id.go
tests/linearizability/identity/lease_ids.go
tests/linearizability/linearizability_test.go
tests/linearizability/model/history.go
tests/linearizability/model/model.go
tests/linearizability/model/model_test.go
tests/linearizability/traffic.go
tests/linearizability/watch.go

tests: Move linearizability model and identity to dedicated packages

---

server/etcdserver/server.go

Backport https://github.com/etcd-io/etcd/pull/15095 to 3.5.

[3.5] etcdserver: return membership.ErrIDNotFound when the memberID not found

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

Linked to:
- https://github.com/etcd-io/etcd/pull/15096
- https://github.com/etcd-io/etcd/pull/15097
- https://github.com/etcd-io/etcd/pull/15095

changelog: add items to cover the issue of promoting a non-started learner member

---

CHANGELOG/CHANGELOG-3.4.md

CHANGELOG: add item about improvement for count-only range

---

tests/linearizability/linearizability_test.go

tests: Persist operation history

---

.github/ISSUE_TEMPLATE/bug-report.yml

Closes #15134 
blow -> below
Signed-off-by: Nirav_Prajapati <niravprajapati97120@gmail.com>

etcd: fix typo in bug.yaml

---

.github/workflows/linearizability-nightly.yaml
.github/workflows/linearizability-template.yaml
.github/workflows/linearizability.yaml

Temporary running nightly to verify the fix.

tests: Set artifact name based to avoid file override from different subruns

---

CHANGELOG/CHANGELOG-3.5.md

changelog: Set release date for v3.5.7

---

tests/linearizability/client.go
tests/linearizability/linearizability_test.go
tests/linearizability/model/history.go
tests/linearizability/model/model.go
tests/linearizability/model/model_test.go
tests/linearizability/traffic.go

tests: Separate request type from Txn operation type

---

tests/linearizability/linearizability_test.go

tests: Stop cluster after tests finish

---

.github/workflows/functional-arm64.yaml

Signed-off-by: Davanum Srinivas <davanum@gmail.com>

Add functional tests on arm64

---

CHANGELOG/CHANGELOG-3.4.md

CHANGELOG: add item about improvement for limit range

---

tests/linearizability/linearizability_test.go

tests: Deduplicate cluster test scenarios

---

server/etcdmain/config.go
server/etcdmain/etcd.go

Signed-off-by: Sasha Melentyev <sasha@melentyev.io>

Change verb and use switch stmt

---

tests/linearizability/model/model.go

test: reorder the import items in linearizability/model/model.go

---

CHANGELOG/CHANGELOG-3.4.md

CHANGELOG: add item about improvement for concurrent read

---

tests/linearizability/failpoints.go

Ref https://github.com/etcd-io/etcd/issues/15189

tests: Increase failpoint timeout and add more logs

---

.github/workflows/tests-arm64.yaml

Signed-off-by: Kevin Zhao <kevin.zhao@linaro.org>

Add integration test for Arm64

---

MAINTAINERS

Update @serathius email address just in case

---

tests/framework/e2e/cluster.go
tests/linearizability/linearizability_test.go
tests/linearizability/watch.go

tests: Enable progress notify in linearizability tests

---

tests/integration/v3_watch_test.go

test: enhance the test case TestV3WatchProgressOnMemberRestart

---

integration/v3_watch_test.go

Backport https://github.com/etcd-io/etcd/pull/15278 to 3.4

[3.4] test: enhance the test case TestV3WatchProgressOnMemberRestart

---

tests/linearizability/client.go
tests/linearizability/linearizability_test.go
tests/linearizability/model/history.go
tests/linearizability/model/model_test.go
tests/linearizability/traffic.go

tests: Implement multi operation Txn

---

tests/linearizability/watch.go

Kubernetes keeps progress on last revision it has seen so if broken, watches can be re-established from last seen revision. It uses:
* [event ModRevision for normal watch response](https://github.com/kubernetes/kubernetes/blob/bf7906674952a08f26e3a7cce7aaf35b1d56bd1e/staging/src/k8s.io/apiserver/pkg/storage/etcd3/event.go#L56)
* [response header Revision for progress notify](https://github.com/kubernetes/kubernetes/blob/bf7906674952a08f26e3a7cce7aaf35b1d56bd1e/staging/src/k8s.io/apiserver/pkg/storage/etcd3/watcher.go#L253)
For this bookmarking to work we need to guarantee that there are no events with revision prior. For ModRevision this is trivial as it's already assumed to be incremental. However for progress notify revision we need to add a specific validation. 

 Codify kubernetes using response header revision as bookmark

---

tests/linearizability/watch.go

tests: Detect duplicate watch event

---

client/v2/auth_role.go
client/v2/auth_user.go
client/v2/keys.go
client/v2/members.go
contrib/raftexample/raftexample_test.go
server/etcdserver/api/etcdhttp/version_test.go
server/etcdserver/api/rafthttp/http_test.go
server/etcdserver/api/rafthttp/stream.go
server/etcdserver/api/rafthttp/util.go
server/etcdserver/cluster_util.go
server/etcdserver/txn/util_test.go
server/lease/leasehttp/http.go
tests/linearizability/model/model.go

Use http constants to replace numbers as parameters

chore: Use http constants to replace numbers as parameters

---

etcdutl/go.mod
etcdutl/go.sum
go.mod
go.sum
server/go.mod
server/go.sum
tests/go.mod
tests/go.sum

dependency: bump github.com/golang-jwt/jwt/v4 to v4.5.0

---

CHANGELOG/CHANGELOG-3.6.md
client/v3/client_test.go
client/v3/cluster.go
client/v3/op.go
etcdctl/README.md
etcdctl/ctlv3/command/get_command.go
etcdctl/ctlv3/command/member_command.go
etcdctl/ctlv3/command/util.go
tests/common/member_test.go
tests/e2e/corrupt_test.go
tests/e2e/ctl_v3_auth_test.go
tests/e2e/ctl_v3_member_test.go
tests/e2e/ctl_v3_test.go
tests/e2e/v2store_deprecation_test.go
tests/framework/e2e/cluster.go
tests/framework/e2e/etcdctl.go
tests/framework/integration/integration.go
tests/framework/interfaces/interface.go

Fix https://github.com/etcd-io/etcd/issues/15243

clientv3: support serializable `MemberList` operation

---

tests/common/auth_test.go
tests/e2e/ctl_v3_auth_test.go

Related to the ask from https://github.com/etcd-io/etcd/pull/14041 to split tests into smaller pieces.
So code review will be reviewer friendly and easier to reason about.

migrate auth tests to common #6

---

tests/common/auth_test.go
tests/e2e/ctl_v3_auth_test.go

Related to the ask from https://github.com/etcd-io/etcd/pull/14041 to split tests into smaller pieces.
So code review will be reviewer friendly and easier to reason about.

migration auth tests to common #5

---

server/etcdserver/server.go
tests/integration/utl_wal_version_test.go

The cluster version will be initialized after the member becomes leader.
The update is handled asynchronously. It couldn't be updated if the member
has been closed and the go-runtime picks the `s.stopping` channel first.
```go
// https://github.com/etcd-io/etcd/blob/e2a5df534cf6b0a12859e61bfc2758d56a1e1971/server/etcdserver/server.go#L2170
func (s *EtcdServer) monitorClusterVersions() {
...
for {
select {
case <-s.firstCommitInTerm.Receive():
case <-time.After(monitorVersionInterval):
case <-s.stopping:
return
}
...
}
}
```
Or after the `s.stopping` has been closed, the [UpdateClusterVersion][1] won't
file GoAttach successfully. For the https://github.com/etcd-io/etcd/issues/15409, we can see the warn log
`server has stopped; skipping GoAttach` from GoAttach:
```plain …
```

tests/integration: deflake TestEtcdVersionFromWAL

---

CONTRIBUTING.md

Updates & simplifies "how to create Codespace's steps" in CONTRIBUTING.md

Update CONTRIBUTING.md reference for Codespaces

---

Makefile
scripts/test.sh

PR fixing this issue https://github.com/etcd-io/etcd/issues/15469

Add verify-goimport to verify all import items are well sorted

---

scripts/measure-test-flakiness.sh

document measure-test-flakiness.sh

---

server/mvcc/watchable_store.go
server/mvcc/watchable_store_test.go

Backport https://github.com/etcd-io/etcd/pull/15492

[v3.5] Fix issue15271

---

README.md

Point coverage to correct branch

---

Documentation/postmortems/v3.5-data-inconsistency.md

Separating postmortem update for easier review.

Update status of postmortem action items

---

CHANGELOG/CHANGELOG-3.4.md

Update changelog for https://github.com/etcd-io/etcd/pull/15542
cc @ahrtr @lavacat

changelog: added item to cover reverting 14548 in release-3.4

---

.github/workflows/tests.yaml
tests/e2e/etcd_config_test.go

Ensure that e2e with release tests are run.

Run e2e tests in CI

---

etcdserver/api/v3rpc/watch.go

[3.4] etcdserver: keep server side change of 14548

---

server/verify/verify.go

skip verification if db file does not exist

---

tests/robustness/failpoints.go
tests/robustness/linearizability_test.go

tests/robustness: Disable testing network blackhole until #15595 is fixed

---

.github/workflows/build.yaml
.github/workflows/e2e-arm64.yaml
.github/workflows/e2e.yaml
.github/workflows/grpcproxy.yaml
.github/workflows/tests-arm64.yaml
.github/workflows/tests.yaml
Makefile

Use makefile as entrypoint in CI

---

.github/workflows/release.yaml
scripts/test_images.sh

Cherry pick of #15505 on release-3.5.
#15505: scripts: Add testing of etcd in local image in release

[3.5] Add testing of etcd in local image in release workflow

---

CHANGELOG/CHANGELOG-3.5.md

CHANGELOG: add item into 3.5

---

tests/e2e/cluster_downgrade_test.go
tests/e2e/v2store_deprecation_test.go
tests/framework/config/cluster.go
tests/framework/e2e/cluster.go
tests/framework/e2e/etcd_process.go
tests/robustness/failpoints.go
tests/robustness/linearizability_test.go

tests/robustness: Support running snapshot tests on older versions

---

tests/e2e/cluster_downgrade_test.go
tests/e2e/corrupt_test.go
tests/e2e/ctl_v3_auth_cluster_test.go
tests/e2e/ctl_v3_auth_test.go
tests/e2e/ctl_v3_move_leader_test.go
tests/e2e/ctl_v3_snapshot_test.go
tests/e2e/ctl_v3_test.go
tests/e2e/discovery_test.go
tests/e2e/discovery_v3_test.go
tests/e2e/etcd_config_test.go
tests/e2e/gateway_test.go
tests/e2e/promote_experimental_flag_test.go
tests/e2e/utl_migrate_test.go
tests/e2e/v2store_deprecation_test.go
tests/e2e/watch_delay_test.go
tests/framework/e2e/cluster.go
tests/framework/e2e/cluster_proxy.go
tests/framework/e2e/e2e.go
tests/framework/e2e/etcd_process.go
tests/integration/clientv3/concurrency/main_test.go
tests/integration/clientv3/examples/main_test.go
tests/integration/lazy_cluster.go
tests/robustness/failpoints.go
tests/robustness/traffic.go
tests/robustness/watch.go

tests: Cleanup endpoints

---

.github/workflows/robustness-nightly.yaml
.github/workflows/robustness-template.yaml
.github/workflows/robustness.yaml
tests/robustness/makefile.mk

tests: Fix building incorrect etcd version and make switch strict

---

tests/framework/e2e/etcd_process.go
tests/robustness/linearizability_test.go

tests: Fix comparing etcd version

---

tests/robustness/failpoints.go
tests/robustness/linearizability_test.go
tests/robustness/watch.go

tests: Enfoce timeout on failpoints

---

tests/robustness/failpoints.go

tests/robustness: Detect trigger timeout and exit

---

tests/framework/e2e/etcd_spawn.go
tests/framework/e2e/flags.go
tests/framework/e2e/util.go

tests/framework: Cleanup alternative binaries in e2e tests

---

.github/workflows/release.yaml
.github/workflows/tests.yaml
Makefile
functional/scripts/docker-local-agent.sh
functional/scripts/docker-local-tester.sh

https://groups.google.com/g/golang-announce/c/Xdv6JL9ENs8/m/OV40vnafAwAJ
Linked to https://github.com/etcd-io/etcd/pull/15649

[3.4] Bump golang to 1.19.8 to fix CVEs

---

server/etcdserver/v3_server.go
tests/e2e/ctl_v3_auth_security_test.go
tests/e2e/ctl_v3_test.go

Backport https://github.com/etcd-io/etcd/pull/15648 to release-3.5.
cc @ahrtr @serathius @ptabor @spzala

[3.5] backport 15648

---

MAINTAINERS
README.md

Update maintainer list

---

etcdserver/v3_server.go
tests/e2e/cluster_test.go
tests/e2e/ctl_v3_auth_security_test.go
tests/e2e/ctl_v3_test.go

Backport https://github.com/etcd-io/etcd/pull/15648 to release-3.4.
cc @ahrtr @serathius @ptabor @spzala

[3.4] backport 15648

---

tests/e2e/ctl_v3_auth_cluster_test.go
tests/e2e/ctl_v3_auth_no_proxy_test.go
tests/e2e/etcd_mix_versions_test.go
tests/framework/e2e/cluster.go
tests/framework/e2e/cluster_proxy.go
tests/framework/e2e/etcd_process.go

tests: Make using etcdctl expicit in e2e tests

---

Documentation/contributor-guide/community-membership.md

After this PR is merge, I will enable enforcement on etcd org.
Fixes https://github.com/etcd-io/etcd/issues/15658
cc @ahrtr @ptabor @spzala

Require 2FA enabled for all members

---

tests/robustness/README.md
tests/robustness/linearizability_test.go
tests/robustness/makefile.mk
tests/robustness/watch.go

tests/robustness: Document analysing watch issue

---

pkg/expect/expect.go

https://github.com/google/goexpect has been archived on Feb 7, 2023.

chore: remove pkg/expect TODO comment

---

client/v3/txn_test.go

This pr is to fix issue #15666, using different errc for each testcase to avoid being confused when some of the testcases get a timeout.

fix: different errc to avoid confused when timeout

---

.github/workflows/release.yaml
scripts/test_images.sh

Cherry pick of #15505 on release-3.4.
#15505: scripts: Add testing of etcd in local image in release

[3.4] Add testing of etcd in local image in release workflow

---

etcdserver/api/v3rpc/watch.go
integration/v3_watch_test.go
mvcc/watchable_store.go
mvcc/watcher.go
mvcc/watcher_test.go

Backport https://github.com/etcd-io/etcd/pull/15237 to 3.4
Link to https://github.com/etcd-io/etcd/issues/15680

[3.4] etcdserver: guarantee order of requested progress notification

---

CHANGELOG/CHANGELOG-3.4.md

change v3.4.25's release date

---

server/etcdserver/txn/txn_test.go

Related issue: #15707
Increase test coverage.
This cover 100% the function txn.CheckTxnAuth

tests: cover txn.CheckTxnAuth logic with unit tests

---

server/auth/store_test.go

fixes https://github.com/etcd-io/etcd/issues/15746

tests: increases unit test coverage for etcd/server/auth isRangeOpPermitted

---

Documentation/contributor-guide/dependency_management.md

cc @mitake @ptabor @serathius @spzala @jmhbnz @chaochn47 @fuweid @tjungblu

Document: add guidance on dependency management

---

CHANGELOG/CHANGELOG-3.5.md

Provide release date for v3.5.8

---

server/etcdmain/util.go

lg always has a value
Signed-off-by: aimuz <mr.imuz@gmail.com>

refactor(util): remove duplicate lg check

---

scripts/test.sh

The current logic in [test.sh](https://github.com/etcd-io/etcd/blob/main/scripts/test.sh#L644:#L659) exits the run when there is first failure in the suite names passed to PASSES variable.
This is leading to incomplete results when the user intends to run multiple test suites.
This change continues with the for loop when there is failure in any suite and exits after the completion of all test suite runs.

keep going with other test suite runs when failure with one

---

tests/robustness/model/describe.go
tests/robustness/model/describe_test.go
tests/robustness/model/deterministic.go
tests/robustness/model/deterministic_test.go
tests/robustness/model/history.go
tests/robustness/model/non_deterministic_test.go

cc @ahrtr @ptabor 
Part of https://github.com/etcd-io/etcd/issues/15820

tests/robustness: Implement Range limit and count

---

server/storage/backend.go

log time when open backend db took too long

---

tests/robustness/linearizability_test.go
tests/robustness/traffic.go

tests/robustness: Make weighted pick random generic

---

server/etcdserver/v3_server.go
tests/e2e/ctl_v3_auth_test.go
tests/e2e/ctl_v3_lease_test.go
tests/integration/v3_auth_test.go

This PR backports #15656 to release-3.5
cc @serathius @ahrtr @spzala

Backport 15656 to release-3.5

---

server/etcdserver/server.go
tests/e2e/graceful_shutdown_test.go
tests/integration/v3_leadership_test.go

- tests/e2e: add graceful shutdown test
Fix https://github.com/etcd-io/etcd/issues/15702
cc @ahrtr @ptabor @serathius

tests/e2e: add graceful shutdown test 

---

tests/robustness/identity/id.go
tests/robustness/model/history.go
tests/robustness/traffic/client.go
tests/robustness/traffic/etcd.go
tests/robustness/traffic/kubernetes.go

cc @ahrtr @jmhbnz @chaochn47 
Another iteration to improve documentation of robustness tests.

tests/robustness: Separate stream id from client id and improve AppendableHistory doc

---

tests/robustness/model/describe.go
tests/robustness/model/deterministic.go
tests/robustness/model/history.go
tests/robustness/watch.go

tests/robustness: Improve naming of Txn fields

---

tests/robustness/linearizability_test.go
tests/robustness/report.go
tests/robustness/traffic/client.go
tests/robustness/traffic/kubernetes.go
tests/robustness/traffic/traffic.go
tests/robustness/watch.go

tests/robustness: Implement kubernetes list watch protocol

---

MAINTAINERS

cc @ptabor @ahrtr @spzala @mitake

Update maintainers emails

---

CHANGELOG/CHANGELOG-3.5.md

update changelog for https://github.com/etcd-io/etcd/pull/15907
cc @ahrtr 

update changelog for https://github.com/etcd-io/etcd/pull/15907

---

client/v3/snapshot/v3_snapshot.go

clientv3: refactor snapshot SaveWithVersion

---

Documentation/contributor-guide/community-membership.md

cc @serathius @ahrtr @spzala @ptabor 
I think it's good to update onboarding process for members and reviewers too.

Documentation: describe onboarding process

---

etcdctl/ctlv3/command/ep_command.go

etcdctl: update the description for flag '--rev'

---

Documentation/contributor-guide/dependency_management.md

Please feel free to suggest a better way to track this. I am OK as long as majority are happy.
cc @mitake @ptabor @serathius @jmhbnz @chaochn47 @fuweid @lavacat @pchan @ArkaSaha30 @sharathsivakumar

Add the rotation worksheet into the dependency management document

---

tests/e2e/cluster_downgrade_test.go
tests/e2e/corrupt_test.go
tests/e2e/etcd_config_test.go
tests/e2e/promote_experimental_flag_test.go
tests/e2e/v2store_deprecation_test.go

tests/e2e: Use epc.Etcdctl

---

scripts/test_lib.sh
tests/Dockerfile
tools/mod/install_all.sh

Fixes https://github.com/etcd-io/etcd/issues/16001
cherry-pick https://github.com/etcd-io/etcd/pull/13673  to release-3.5.
Already remove dependency on gobin
[https://github.com/etcd-io/etcd/pull/15018 remove ](https://github.com/etcd-io/etcd/pull/15018/commits/925c0611e007afe7a60f70761f3471a1431b105f).  we should remove all .

replace gobin with go install

---

tests/robustness/model/deterministic.go
tests/robustness/model/non_deterministic.go
tests/robustness/model/non_deterministic_test.go

tests/robustness: Assume starting from empty etcd instead of throwing out first failed request

---

tests/robustness/traffic/etcd.go

tests/robustness: Move get to list of randomized operations

---

tests/robustness/model/describe.go
tests/robustness/model/describe_test.go
tests/robustness/model/deterministic.go
tests/robustness/model/history.go
tests/robustness/model/non_deterministic.go
tests/robustness/traffic/client.go
tests/robustness/traffic/etcd.go
tests/robustness/validate/patch_history.go

cc @ahrtr @ptabor @jmhbnz @chaochn47 @lavacat

Robustness range request

---

tests/robustness/model/describe.go
tests/robustness/model/describe_test.go
tests/robustness/model/deterministic.go
tests/robustness/model/deterministic_test.go
tests/robustness/model/history.go
tests/robustness/model/non_deterministic.go
tests/robustness/model/non_deterministic_test.go
tests/robustness/validate/patch_history.go

Robustness Allow errors and partial responses from deterministic model

---

mvcc/kvstore.go
mvcc/kvstore_test.go

https://github.com/etcd-io/etcd/pull/14457

[3.4] etcdserver: fix corruption check when server has just been compacted

---

tests/robustness/model/deterministic.go
tests/robustness/model/deterministic_test.go
tests/robustness/model/non_deterministic.go
tests/robustness/model/non_deterministic_test.go
tests/robustness/model/replay.go
tests/robustness/report.go
tests/robustness/traffic/client.go
tests/robustness/validate/operations.go
tests/robustness/validate/validate.go
tests/robustness/validate/watch.go

Validate stale read

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

Let me know if that wording works for you.
for #15993

update change logs with lease put improvements

---

tests/robustness/traffic/etcd.go

cc @ahrtr @ptabor @jmhbnz @fuweid @chaochn47

tests/robustness: Add List and StaleList requests to etcd traffic

---

tests/robustness/traffic/etcd.go

tests/robustness: Fix multi txn key prefix

---

tests/robustness/model/describe.go
tests/robustness/model/history.go
tests/robustness/traffic/client.go
tests/robustness/traffic/etcd.go
tests/robustness/traffic/kubernetes.go

tests/robustness: Implement Kubernetes pagination

---

tests/robustness/validate/watch.go

cc @ahrtr @ptabor @jmhbnz @fuweid @chaochn47

tests/robustness: Combine watch histories

---

tests/robustness/validate/patch_history.go
tests/robustness/validate/patch_history_test.go
tests/robustness/validate/validate.go

Robustness fix patch txn onfailure

---

tests/robustness/linearizability_test.go
tests/robustness/report.go
tests/robustness/traffic/client.go
tests/robustness/traffic/traffic.go
tests/robustness/validate/patch_history.go
tests/robustness/validate/patch_history_test.go
tests/robustness/validate/watch.go
tests/robustness/watch.go

Want to keep watch requests to properly validate reliability of watch stream.
cc @ahrtr @ptabor @chaochn47 @jmhbnz @fuweid

tests/robustness: Store whole watch operations

---

.github/workflows/robustness-template-arm64.yaml
.github/workflows/robustness-template.yaml
.github/workflows/scorecards.yml

fix #16147
Also adds some missing comments.

fix action tag comment pattern to be consistent

---

server/etcdserver/api/membership/membership_test.go

Enable test to verify membership recovery from backend

---

tests/robustness/traffic/etcd.go
tests/robustness/traffic/kubernetes.go
tests/robustness/traffic/limiter.go
tests/robustness/traffic/limiter_test.go
tests/robustness/traffic/traffic.go

tests/robustness: Prevent to many concurrent non-unique writes which are causing linearization to timeout

---

CHANGELOG/CHANGELOG-3.5.md

update changelog for https://github.com/etcd-io/etcd/pull/15939
cc @ahrtr

update changelog for #15939

---

server/etcdserver/server_test.go

Adding test for updateClusterVersionV3
Related to task - "V2 snapshots are generated from V3 data" - https://github.com/etcd-io/etcd/issues/12913
Eventually TestUpdateVersion which tests updateClusterVersionV2 will be removed.

Adding test for updateClusterVersionV3

---

CHANGELOG/CHANGELOG-3.5.md

update changelog for #16188

---

etcdutl/snapshot/v3_snapshot.go

Backporting #16120 to release-3.5
cc @ahrtr

[Backport 3.5] etcdutl: fix db double closed

---

CHANGELOG/CHANGELOG-3.4.md

Changelog: update etcd 3.4.27's release date

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

Add changelog for backport 13577 to 3.4&3.5.

---

tests/integration/clientv3/naming/resolver_test.go

Fixes https://github.com/etcd-io/etcd/issues/16253
https://github.com/etcd-io/etcd/issues/16253#issuecomment-1638804693

Fix flaky integration/clientv3/naming TestEtcdGrpcResolverRoundRobin

---

Documentation/contributor-guide/triage_issues.md

refs https://github.com/etcd-io/etcd/pull/16192

Fix typo in triage_issues.md

---

server/etcdserver/raft.go

update typo in raft.go

---

etcdctl/go.mod
etcdctl/go.sum
etcdutl/go.mod
etcdutl/go.sum
go.mod
go.sum
tests/go.mod
tests/go.sum
tools/mod/go.mod
tools/mod/go.sum

Dependabot has raised the following updates:
- https://github.com/etcd-io/etcd/pull/16295
- https://github.com/etcd-io/etcd/pull/16293

Manual Dependency Bump

---

server/storage/backend/read_tx.go
server/storage/mvcc/kvstore.go
server/storage/schema/alarm.go
server/storage/schema/membership.go
server/storage/schema/schema.go
server/storage/schema/version.go

Follow up https://github.com/etcd-io/etcd/pull/16068#discussion_r1263664700

Replace unnecessary Lock()/Unlock()s with RLock()/RUnlock()s

---

tests/framework/e2e/cluster_proxy.go

tests: Make EtcdServerProcess substruct of proxyEtcdProcess to dummy methods when extending EtcdProcess interface

---

server/auth/range_perm_cache.go
server/auth/store.go
server/auth/store_mock_test.go
server/storage/backend/batch_tx.go
server/storage/backend/read_tx.go
server/storage/mvcc/hash.go
server/storage/mvcc/kvstore_txn.go
server/storage/mvcc/store.go
server/storage/schema/alarm.go
server/storage/schema/auth.go
server/storage/schema/auth_roles.go
server/storage/schema/auth_users.go
server/storage/schema/cindex.go
server/storage/schema/confstate.go
server/storage/schema/lease.go
server/storage/schema/schema.go
server/storage/schema/version.go

Remove RLock/RUnlock from BatchTx

---

api/version/version.go
client/v3/client.go
client/v3/client_test.go
client/v3/go.mod

checks the client supported versions based on the current version

---

client/v3/concurrency/session.go
tests/integration/clientv3/concurrency/session_test.go

It's not so convenient to build child context based on session's context now.
So add `Session.Ctx()` similar with `Client.Ctx()`.

clientv3: add Ctx() to return context of session

---

server/mvcc/kvstore.go
server/mvcc/util.go

Follow up https://github.com/etcd-io/etcd/pull/16068#discussion_r1263667496

[3.5] Add UnsafeReadScheduledCompact and UnsafeReadFinishedCompact

---

etcdctl/README.md

fix: throughput typo

---

pkg/adt/interval_tree_test.go
pkg/proxy/server.go
pkg/proxy/server_test.go
pkg/stringutil/rand.go
server/etcdserver/server.go
server/lease/lessor_bench_test.go
tests/integration/clientv3/snapshot/v3_snapshot_test.go

all: stop using math/rand.Seed

---

Documentation/contributor-guide/release.md
README.md
security/README.md

https://github.com/etcd-io/website/issues/479

Use new and better canonical link to Google Groups

---

tests/e2e/v2store_deprecation_test.go

Updating as per review feedback.
Related to https://github.com/etcd-io/etcd/pull/16441

Minor update to test code to remove a local var

---

pkg/ioutil/pagewriter.go
pkg/ioutil/pagewriter_test.go

backport #14452 on 3.5, have also created a discussion, see #16473 . At the same time, please confirm whether the PR is necessary.

[3.5] add a verification on the pagebytes which must be > 0

---

CHANGELOG/CHANGELOG-3.5.md

CHANGELOG: add #16490 item in CHANGELOG-3.5.md

---

tests/e2e/utils.go
tests/e2e/v3_curl_maintenance_test.go
tests/e2e/v3_curl_test.go

Linked to https://github.com/etcd-io/etcd/pull/16454

test: add v3 curl test to cover all maintenance REST API

---

server/etcdserver/txn/txn.go

server: Refactor checkTxn into single function handling all request types

---

tests/e2e/v3_curl_kv_test.go

All RESTful API in KV service are covered now.
part of https://github.com/etcd-io/etcd/issues/16507
also link to https://github.com/etcd-io/etcd/pull/16454

test: refactor the existing KV RESTful test cases and also add new cases

---

server/etcdserver/txn/txn_test.go
server/lease/lessor.go

cc @ahrtr @jmhbnz 
Tests for https://github.com/etcd-io/etcd/pull/16372

server: Test txn checking

---

.devcontainer/devcontainer.json
.github/workflows/e2e-arm64-template.yaml
.github/workflows/e2e.yaml
.github/workflows/grpcproxy.yaml
.github/workflows/robustness-template.yaml
.github/workflows/tests-arm64-template.yaml
.github/workflows/tests.yaml
Dockerfile
tests/e2e/cmux_test.go

signed-off-by: Sagar Rawat sagarrawat24291@gmail.com

update the debian12 and bookworm remove --v 1.0

---

server/etcdserver/txn/txn_test.go

Use test cases from TestCheckTxn to test Put and Range

---

tests/e2e/v3_curl_auth_test.go

Also link to https://github.com/etcd-io/etcd/pull/16454

test: add e2e test cases to cover all auth related RESTful APIs

---

tests/e2e/v3_curl_cluster_test.go

All cluster RESTful APIs are covered in this PR.
part of https://github.com/etcd-io/etcd/issues/16507
Also link to https://github.com/etcd-io/etcd/pull/16454

test: add test cases to cover cluster RESTful APIs

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

- https://github.com/etcd-io/etcd/pull/16555
- https://github.com/etcd-io/etcd/pull/16556

changelog: update changelog to cover the goalng bump

---

CHANGELOG/CHANGELOG-3.5.md

CHANGELOG: update 3.5 with #16565

---

server/storage/mvcc/hash.go

mvcc: minor cleanup of comment in HashStorage.Store

mvcc: cleanup comment in HashStorage.Store

---

MAINTAINERS
OWNERS

Add fuweid as reviewer

---

tests/e2e/corrupt_test.go

It's super easy to reproduce the issue https://github.com/etcd-io/etcd/issues/16666
```
ctl_v3_kv_test.go:102: 
Error Trace:	/Users/wachao/go/src/github.com/ahrtr/etcd/tests/e2e/ctl_v3_kv_test.go:102
/Users/wachao/software/go/src/runtime/asm_arm64.s:1197
Error:      	Not equal: 
expected: "bar2"
actual  : "bar"
Diff:
--- Expected
+++ Actual
@@ -1 +1 @@
-bar2
+bar
Test:       	TestCtlV3LinearizableRead
ctl_v3_kv_test.go:115: Checked the key/value 1 times
```
The issue can be resolved by either of the following approaches,
- rollback https://github.com/etcd-io/etcd/pull/13525
- Remove `e2e.WithWaitClusterReadyTimeout(1*time.Nanosecond)` in the test in this PR. [It's still possible to reproduce this issue by injecting extremely bigger time sleep]

test: add test cases to verify consistent reading right after writing

---

tests/framework/e2e/etcd_process.go
tests/robustness/failpoints.go

Part of https://github.com/etcd-io/etcd/issues/16673
This is enough to reproduce https://github.com/etcd-io/etcd/issues/16666

Inject sleep during etcd bootstrap to reproduce etcd-io#16666 

---

scripts/test.sh
tools/.golangci.yaml
tools/mod/go.mod
tools/mod/go.sum
tools/mod/tools.go

*: migrate nakedret_pass into golangci-lint

---

tests/framework/e2e/etcd_process.go
tests/robustness/failpoints.go

Fix parsing failpoint names when failpoint has set value

---

tests/robustness/linearizability_test.go

Fix providing profile to robustness tests

---

tests/framework/e2e/cluster_test.go

Test to prepare for https://github.com/etcd-io/etcd/pull/16707

Add tests to prepare to dynamic flag generation

---

tests/robustness/validate/validate.go

Fix linearization failure not causing test failure

---

tests/robustness/validate/patch_history.go

Use the minimal time event was observed on watch

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

Fix https://github.com/etcd-io/etcd/pull/16752#discussion_r1360342863

Update 3.4 & 3.5 changelog

---

tests/robustness/main_test.go
tests/robustness/scenarios.go

Make the main_test the entrypoint and move senario generation to separate file

---

tests/robustness/failpoint/cluster.go
tests/robustness/failpoint/failpoint.go

Add member replace failpoint to robustness tests

---

tests/integration/clientv3/naming/resolver_test.go

remove deprecated gRPC API usage

---

tests/robustness/failpoint/failpoint.go
tests/robustness/failpoint/network.go

Implement random packet dropping

---

.github/workflows/e2e-arm64-nightly.yaml
.github/workflows/robustness-nightly.yaml

Follow up to https://github.com/etcd-io/etcd/pull/16801#discussion_r1370567976

Schedule the arm64 related workflow nightly

---

etcdctl/go.mod
etcdctl/go.sum
etcdutl/go.mod
etcdutl/go.sum
go.mod
go.sum
server/go.mod
server/go.sum
tests/go.mod
tests/go.sum

[3.5] Bump bbolt to 1.3.8 for release-3.5

---

etcdutl/go.mod
etcdutl/go.sum
go.mod
go.sum
server/go.mod
server/go.sum
tests/go.mod
tests/go.sum

Bump bbolt to 1.3.8 for main branch

---

go.mod
go.sum

[3.4] Bump bbolt to 1.3.8 for release-3.4

---

CHANGELOG/CHANGELOG-3.5.md

Update date of v3.5.10 release

---

clientv3/client.go
clientv3/client_test.go

Backports #14368 in support of https://github.com/etcd-io/etcd/issues/16751.

[3.4] Backport clientv3: fix init client error

---

scripts/test.sh
scripts/updatebom.sh
tools/mod/go.mod
tools/mod/go.sum
tools/mod/tools.go

Fixes https://github.com/etcd-io/etcd/issues/15747.

update dependency in BOM check

---

client/v3/concurrency/main_test.go

Fix typo in concurrent examples

---

tests/framework/e2e/etcd_process.go

Increase client timeout for failpoint injection

---

tests/robustness/options/cluster_options_test.go

Refactor mocking rand

---

client/pkg/transport/sockopt_unix.go
client/pkg/transport/sockopt_wasm.go

Add for https://github.com/etcd-io/etcd/issues/16908.

client: add wasm for client transport

---

server/etcdserver/server_test.go

Split from https://github.com/etcd-io/etcd/pull/16989

Stop using v2 requests in server tests

---

etcdserver/api/rafthttp/http.go
etcdserver/api/rafthttp/stream.go
etcdserver/api/rafthttp/util.go
etcdserver/api/v3rpc/rpctypes/error.go
etcdserver/corrupt.go
etcdserver/corrupt_test.go
tests/e2e/cluster_test.go
tests/e2e/etcd_corrupt_test.go
tests/e2e/etcdctl.go

backport https://github.com/etcd-io/etcd/pull/15924 to 3.4

[3.4] etcdserver: add cluster id check for hashKVHandler

---

server/etcdserver/server_test.go

Split off https://github.com/etcd-io/etcd/pull/16989

Add tests for setting cluster version using v2 request

---

scripts/test_lib.sh

This is why the e2e job on prow is failing.

fix missing json flag when using VERBOSE=1

---

CHANGELOG/CHANGELOG-3.4.md

Update changelog for 3.4.28

---

server/etcdserver/api/membership/cluster.go
server/etcdserver/api/membership/storev2.go

Remove unused method and function

---

server/etcdserver/api/membership/cluster_test.go

https://github.com/etcd-io/etcd/pull/17017 followup as it was merged too early.

Test v3 storage configuration validation

---

server/etcdmain/etcd.go

Fix message in case of unsupported platform

---

tests/framework/e2e/cluster.go
tests/framework/e2e/etcd_process.go

Extracted from https://github.com/etcd-io/etcd/pull/16822, to make the review on that PR easier.
Once this PR is merged, I will rebase https://github.com/etcd-io/etcd/pull/16822.

Support setting http client timeout when enable/disable failpoint

---

tests/e2e/corrupt_test.go
tests/e2e/ctl_v3_member_no_proxy_test.go
tests/e2e/utils.go

Add member replace e2e test

---

README.md

Reference: https://docs.actuated.dev/faq/#is-there-a-sponsored-subscription-for-open-source-projects

Add actuated badge

---

server/etcdserver/bootstrap.go
server/etcdserver/server.go

Added some log messages for better diagnosis

---

client/v3/lease.go

etcdclient: Fix memory leak caused by for + time.After

---

CHANGELOG/CHANGELOG-3.4.md

Updates 3.4 changelog to include #17112.
Related to #16969.

changelog: update 3.4 changelog to include ssrf fix

---

tests/e2e/ctl_v3_member_no_proxy_test.go

Update test case TestMemberReplace to always connect to stable endpoints

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

changelog: update 3.4 3.5 changelogs to include livez/readyz changes.

---

tests/e2e/ctl_v3_snapshot_test.go

Add test e2e for etcd behavior when db file is older than snapshot.
Improve coverage for https://github.com/etcd-io/etcd/issues/17146

Test etcd fails to bootstrap with older db file

---

client/pkg/fileutil/purge.go
client/pkg/fileutil/purge_test.go
server/etcdserver/server.go

Backport https://github.com/etcd-io/etcd/pull/17199
cc @ahrtr

[release-3.5] Don't flock snapshot files

---

CHANGELOG/CHANGELOG-3.4.md

CHANGELOG: update changes for v3.4.29

---

Documentation/contributor-guide/dependency_management.md

Update rotation worksheet as mentioned [here](https://github.com/etcd-io/etcd/issues/17224)

docs: update rotation worksheet

---

server/go.mod
server/go.sum
server/mvcc/backend/batch_tx.go
server/mvcc/backend/batch_tx_test.go
tests/integration/clientv3/user_test.go

backport https://github.com/etcd-io/etcd/pull/17195 to 3.5

[3.5] Fix delete inconsistencies in read buffer

---

Makefile

Follow up task related to: https://github.com/etcd-io/etcd/pull/17200

Ensure bin/python directory is cleaned after install

---

server/storage/backend/backend.go

The task has already been tracked in roadmap by https://github.com/etcd-io/bbolt/issues/509

Specify logger for bbolt

---

CHANGELOG/CHANGELOG-3.6.md

refer to https://github.com/etcd-io/raft/pull/125

Migrate the raft changes to raft's changelog

---

server/storage/backend/batch_tx_test.go
server/storage/backend/tx_buffer.go

Revert https://github.com/etcd-io/etcd/pull/17228
https://github.com/etcd-io/etcd/issues/17247

Revert #17228

---

embed/etcd.go

Backporting https://github.com/etcd-io/etcd/pull/17314

[3.4] Print error log when creating peer listener failed

---

server/storage/backend/tx_buffer.go

Extracted from https://github.com/etcd-io/etcd/pull/17290.
It should can be reviewed & merged separately.

Add verification on keys: should be always mononically increasing

---

mvcc/kvstore_test.go

Backport https://github.com/etcd-io/etcd/pull/17313

[3.4] test: fix `TestHashKVWhenCompacting`: ensure all goroutine finished

---

server/etcdserver/server.go

Fix: https://github.com/kubernetes/kubeadm/issues/2997#issuecomment-1900069112

Added a error log when learner is not sync with etcd leader.

---

CHANGELOG/CHANGELOG-3.5.md

Add v3.5.12 changelog

---

CHANGELOG/CHANGELOG-3.4.md

Link to https://github.com/etcd-io/etcd/issues/17350

Update changelog for v3.4.30

---

OWNERS

cc  @fuweid @jmhbnz @mitake  @serathius @spzala  @wenjiaswe

Update ahrtr's email

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

For https://github.com/etcd-io/etcd/issues/17272
This PR adds changelog entries for:
https://github.com/etcd-io/etcd/pull/17363
https://github.com/etcd-io/etcd/pull/17369

Add backoff/retry config to changelog

---

OWNERS

Update OWNERS: retire mitake

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

Adding changelog entries for https://github.com/etcd-io/etcd/issues/17348

Add go1.21 update to changelog

---

README.md

Link to https://github.com/etcd-io/etcd/pull/17385

Add Hitoshi Mitake into the Emeritus Maintainers list

---

tests/framework/integration/cluster.go

Follow up to https://github.com/etcd-io/etcd/pull/17384#issuecomment-1932702710

Remove the unused AuthTokenTTL parameter from integration test

---

build.sh
scripts/install-marker.sh

- shellcheck violations fixed
- https://github.com/etcd-io/etcd/issues/17400

*: fix failing shellchecks

---

pkg/contention/contention.go

Misc cleanup of `pkg/contention/contention.go`:
- Improve docs
- change Observe param name from `which` to `id` to suggest event id

cleanup contention.go docs, Observe param name

---

CHANGELOG/CHANGELOG-3.5.md

update changelog for #15940
cc @ahrtr

update changelog for #15940

---

tests/robustness/traffic/kubernetes.go

Kubernetes uses WithRequireLeader to modify the context passed to the Watch() and RequestProgress() calls in order to ensure that a leader is present in the cluster before serving the request.
This commit mimics that behaviour in the Kubernetes traffic.
Towards: https://github.com/etcd-io/etcd/issues/15820
/assign @serathius

tests/robustness: use WithRequireLeader in Kubernetes traffic

---

.github/ISSUE_TEMPLATE/test-flake.yml

just a quick clarification because we can now also have flakes on prow jobs

Update flake issue template to include prow

---

CHANGELOG/CHANGELOG-3.5.md

update CHANGELOG-3.5.md for https://github.com/etcd-io/etcd/pull/17447

update CHANGELOG-3.5.md for #17447

---

etcdctl/go.mod
etcdctl/go.sum
etcdutl/go.mod
etcdutl/go.sum
go.mod
go.sum
server/go.mod
server/go.sum
tests/go.mod
tests/go.sum

[3.5] Bump bbolt to v1.3.9

---

go.mod
go.sum

[3.4] Bump bbolt to v1.3.9

---

Documentation/contributor-guide/dependency_management.md

cc @fuweid @jmhbnz @serathius @spzala

Clarify the core dependencies mappings: bbolt and raft

---

Makefile
functional/scripts/docker-local-agent.sh
functional/scripts/docker-local-tester.sh

continue https://github.com/etcd-io/etcd/pull/17538 , resolve https://github.com/etcd-io/etcd/pull/17538#pullrequestreview-1919249620
sorry about not clean.
Releated:
- https://github.com/etcd-io/etcd/issues/17533
/cc @jmhbnz @ahrtr

[3.4] Update go version to 1.21.8 for build.

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

Link to:
- https://github.com/etcd-io/etcd/pull/17567
- https://github.com/etcd-io/etcd/pull/17566
- https://github.com/etcd-io/etcd/pull/17557

Added changelog for the progress notification issue

---

Documentation/contributor-guide/release.md

Fix https://github.com/etcd-io/etcd/issues/17581
cc @jmhbnz @serathius @spzala @wenjiaswe 

Update release guide and setup a pool of release candidates

---

Documentation/contributor-guide/release.md

Update a format typo in https://github.com/etcd-io/etcd/pull/17589

Update format error for candidate links

---

README.md

Quick pr to add link for our meeting lead rotation worksheet.
Fixes #17577

Update community meeting docs to cover lead rotation

---

CHANGELOG/CHANGELOG-3.4.md

Release was completed yesterday while at KubeconEU.
cc @ahrtr

Update date of v3.4.31 release.

---

etcdctl/ctlv3/command/check.go
scripts/test.sh
scripts/test_images.sh
scripts/test_lib.sh
server/storage/backend/hooks_test.go
server/storage/schema/auth_roles_test.go
server/storage/schema/auth_users_test.go
server/storage/schema/confstate.go
server/storage/wal/wal.go
tests/common/lease_test.go
tests/integration/lazy_cluster.go
tests/robustness/validate/validate_test.go
tools/etcd-dump-logs/README.md

the same as https://github.com/etcd-io/etcd/pull/17540

fix some typos

---

CHANGELOG/CHANGELOG-3.4.md

Followup of https://github.com/etcd-io/etcd/pull/17330

add 3.4 changelog of adding downgrade support.

---

Makefile

add .PHONY: all、verify、fix、clean

Makefile: perfect .PHONY

---

clientv3/client.go

References:
- etcd-io#17001
- etcd-io#17018

Backport initialization of epMu in NewCtxClient to release-3.4

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

Update CHANGELOG 3.4 and 3.5 - initialization for epMu/mu in client context 

---

tests/framework/e2e/etcd_process.go

Caused https://github.com/etcd-io/etcd/actions/runs/8449504923/job/23143725180 flake
cc @ahrtr @jmhbnz @MadhavJivrajani

Increase timeout for deactivating failpoint

---

tests/robustness/failpoint/failpoint.go
tests/robustness/main_test.go

cc @ahrtr @siyuanfoundation @MadhavJivrajani

Make no failpoint error more readable

---

CHANGELOG/CHANGELOG-3.5.md

CHANGELOG:add wal write system call metrics observation

---

CONTRIBUTING.md
Documentation/contributor-guide/branch_management.md
Documentation/contributor-guide/community-membership.md
Documentation/contributor-guide/dependency_management.md
Documentation/contributor-guide/features.md
Documentation/contributor-guide/local_cluster.md
Documentation/contributor-guide/logging.md
Documentation/contributor-guide/modules.md
Documentation/contributor-guide/release.md
Documentation/contributor-guide/reporting_bugs.md
Documentation/contributor-guide/roadmap.md
Documentation/contributor-guide/triage_issues.md
Documentation/contributor-guide/triage_prs.md

As I was going through the documentation to learn more about the etcd project, I also improved it a bit on the go (leveraging Grammarly for typo and grammar checks, and rephrasing some small parts of them myself).

Improve documentation

---

tests/robustness/model/describe.go
tests/robustness/model/describe_test.go

cc @MadhavJivrajani @ahrtr @siyuanfoundation

Improve description for Kubernetes CAS operations

---

tests/robustness/traffic/kubernetes.go

Limit can cause multiple request due to pagination. For reads after a failed write we would like to return to normal write request as soon as possible.
cc @MadhavJivrajani @ahrtr @siyuanfoundation

Remove limit from read requests after a failed write

---

tests/common/kv_test.go
tests/integration/clientv3/ordering_kv_test.go
tests/integration/v3_watch_test.go

tests: fix some typos in comments

---

tests/robustness/validate/validate_test.go
tests/robustness/validate/watch.go

cc @ahrtr @siyuanfoundation @MadhavJivrajani

Add filter validation to ensure watch only includes events within selector

---

tests/robustness/validate/validate_test.go
tests/robustness/validate/watch.go

cc @ahrtr @siyuanfoundation @MadhavJivrajani

Resumable handles watch with revision zero

---

etcdserver/server.go
etcdserver/server_test.go

References:
- https://github.com/etcd-io/etcd/issues/17081
- https://github.com/etcd-io/etcd/pull/17078

[backport-3.4] server: ignore raft messages if member id mismatch 

---

tests/robustness/model/watch.go
tests/robustness/traffic/client.go
tests/robustness/validate/validate_test.go
tests/robustness/validate/watch.go

cc @siyuanfoundation @MadhavJivrajani @fuweid

Handle watch responses with error

---

server/etcdserver/api/capability.go
server/etcdserver/version/downgrade.go
server/etcdserver/version/downgrade_test.go
server/etcdserver/version/monitor.go

refactor the function based on the feedbacks of https://github.com/etcd-io/etcd/pull/17821

refactor IsValidVersionChange.

---

mvcc/kvstore.go

Backport https://github.com/etcd-io/etcd/pull/17792

[3.4] Update the compaction log when bootstrap and update compact's signature

---

CHANGELOG/CHANGELOG-3.4.md

Update 3.4 changelog for 2 new downgrade cases.

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

- Address [PRISMA-2023-0056](https://github.com/etcd-io/etcd/issues/17268#issuecomment-2050252647) changes.

Update CHANGELOG - 3.4, 3.5 - fix PRISMA-2023-0056

---

server/storage/mvcc/kvstore.go

server/storage/mvcc: should update currentRev in revMu

---

tests/robustness/report/report.go

Prerequisite for https://github.com/kubernetes/test-infra/pull/32481

robustness: Add option to not overwrite results dir.

---

CHANGELOG/CHANGELOG-3.4.md

Released on April 25, 2024
https://github.com/etcd-io/etcd/issues/17853

Update Changelog for v3.4.32

---

tests/robustness/model/replay.go
tests/robustness/report/wal.go
tests/robustness/validate/operations.go
tests/robustness/validate/validate.go
tests/robustness/validate/validate_test.go
tests/robustness/validate/watch.go

Robustness wal validate watch

---

tests/robustness/report/wal.go

Caused failure in https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/ci-etcd-robustness-release35-amd64/1784129279332716544

Add LeaseRevoke request to WAL parsing

---

CHANGELOG/CHANGELOG-3.6.md

Update changelog with quota to endpoint status response

---

etcdctl/go.mod
etcdctl/go.sum
etcdutl/go.mod
etcdutl/go.sum
go.mod
go.sum
server/go.mod
server/go.sum
tests/go.mod
tests/go.sum

Bump bbolt to 1.3.10 for 3.5

---

go.mod
go.sum

Bump bbolt to 1.3.10 for 3.4

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

Update changelog with bbolt bumps

---

tests/robustness/report/client.go

robustness: add 2 more log lines when persistClientReports

---

CHANGELOG/CHANGELOG-3.5.md
CHANGELOG/CHANGELOG-3.6.md

update changelog for experimental-stop-grpc-service-on-defrag

---

tests/robustness/README.md
tests/robustness/failpoint/network.go
tests/robustness/scenarios.go

cc @siyuanfoundation @MadhavJivrajani @fuweid

Update the robustness README and fix the #14370 reproduction case

---

tools/benchmark/cmd/put.go

tools/benchmark/cmd: eliminate custom max function

---

.github/workflows/robustness-template.yaml

github workflow: fix all apt-install  error return code

---

Makefile
scripts/fix.sh

Follow up from https://github.com/etcd-io/etcd/pull/17876#discussion_r1593507429
/assign @ahrtr @serathius

split out subroutine from fix.sh to makefile target

---

server/embed/config.go

ServerRegister -> ServiceRegister

embed: fix typo in comment

---

OWNERS

Add me to the reviewers' list.
Part of #18020.

Add ivanvc to reviewers

---

OWNERS

Part of https://github.com/etcd-io/etcd/issues/18020.

Add siyuanfoundation to reviewers.

---

tests/robustness/failpoint/gofail.go

This is required for compaction based failpoint, to allow the traffic send compaction request causing etcd to crash before failpoint executes the trigger.
cc @siyuanfoundation @fuweid @MadhavJivrajani

Allow gofail trigger to fail as long as the member stops running

---

scripts/release.sh

Minor improvement that was identified when releasing v3.5.14.
Related to https://github.com/etcd-io/etcd/issues/18013.
Backport of commit 4881e53677f6cb592aa1cf7ee15bfd51e6cf1ff9 / pull request #18095.

[3.5] scripts/release: shallow clone repository

---

scripts/release.sh

Minor improvement that was identified when releasing v3.5.14.
Related to https://github.com/etcd-io/etcd/issues/18013.
Backport of commit 4881e53677f6cb592aa1cf7ee15bfd51e6cf1ff9 / pull request #18095.

[3.4] scripts/release: shallow clone repository

---

etcdserver/server.go

Partially backport https://github.com/etcd-io/etcd/pull/17113

[3.4] print error log when validation on conf change failed

---

pkg/expect/expect.go
tests/framework/e2e/etcd_process.go
tests/robustness/failpoint/trigger.go

cc @fuweid @jmhbnz @MadhavJivrajani @siyuanfoundation

Improve e2e error reporting

---

server/storage/mvcc/key_index.go

Fix typo in mvcc comment

---

tests/robustness/model/replay.go
tests/robustness/validate/validate_test.go
tests/robustness/validate/watch.go

/cc @siyuanfoundation @MadhavJivrajani @fuweid @fykaa @henrybear327

Disable robustness test detection of #18089 to allow detecting other issues

---

tests/robustness/validate/patch_history_test.go
tests/robustness/validate/validate_test.go

Adding test for https://github.com/etcd-io/etcd/pull/18214 as promised.

Add tests for patching history to check output and return values

---

tests/robustness/main_test.go
tests/robustness/scenarios.go

/cc @siyuanfoundation @MadhavJivrajani @fuweid @fykaa @henrybear327

Add failpoint name to test name allowing us to track a per failpoint failures in testgrid

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

CHANGELOG: Update  to reflect go version 1.21.12 bump

---

client/v3/auth.go
client/v3/client.go
client/v3/cluster.go
client/v3/kubernetes/client.go
client/v3/kubernetes/interface.go
client/v3/kv.go
client/v3/lease.go
client/v3/maintenance.go
client/v3/txn.go
client/v3/watch.go

Backport https://github.com/etcd-io/etcd/pull/16333 to release-3.5
cc @ahrtr

Introduce Kubernetes KV interface to etcd client

---

OWNERS

https://github.com/etcd-io/etcd/issues/16367

Backport migration of OWNERS file.

---

tests/e2e/v3_lease_no_proxy_test.go

Link to https://github.com/etcd-io/etcd/pull/16822

test: extend leaseRevoke and leaseRenew test to support 5 members cluster

---

tests/e2e/v3_lease_no_proxy_test.go

Backport https://github.com/etcd-io/etcd/pull/18450 to 3.5

[3.5] test: extend leaseRevoke and leaseRenew test to support 5 members cluster

---

tests/e2e/hashkv_test.go

(cherry picked from commit 6f93af85d2aacbc85948f1db07e07f1a86698366)
Part of https://github.com/etcd-io/etcd/pull/18274

[3.5] tests/e2e: add test cases related to HashKV

---

server/mvcc/hash.go
server/mvcc/index_test.go
server/mvcc/key_index.go
server/mvcc/key_index_test.go
tests/e2e/watch_test.go

[3.5] *: keep tombstone if revision == compactAtRev

---

etcdctl/go.mod
etcdctl/go.sum
etcdutl/go.mod
etcdutl/go.sum
go.mod
go.sum
server/go.mod
server/go.sum
tests/go.mod
tests/go.sum

[3.5] Bump bbolt to 1.3.11

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

update changes for issue https://github.com/etcd-io/etcd/issues/18480

CHANGELOG: Add entries for bbolt dependency bump

---

server/storage/wal/repair.go
server/storage/wal/repair_test.go

Ensure consistent file permissions on broken WAL files

---

CHANGELOG/CHANGELOG-3.6.md

Update changelog-3.6 to cover the new flags for etcdctl

---

mvcc/backend/backend.go
tests/e2e/defrag_no_space_test.go
tests/e2e/etcdctl.go

Backport of https://github.com/etcd-io/etcd/pull/18822 to 3.4.

[3.4] fix(defrag): handle errors during defrag

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

docs(CHANGELOG): update 3.4/3.5 changelogs with defrag fixes

---

client/internal/v2/auth_role.go
client/internal/v2/auth_user.go
client/internal/v2/client_test.go
client/internal/v2/keys_test.go
client/internal/v2/members_test.go
client/pkg/transport/timeout_transport_test.go
server/embed/serve.go
server/etcdserver/api/etcdhttp/peer_test.go
server/etcdserver/api/rafthttp/http.go
server/etcdserver/apply_v2.go
server/lease/leasehttp/http.go
tests/e2e/http_health_check_test.go
tests/framework/e2e/etcd_process.go
tools/.golangci.yaml
tools/etcd-dump-logs/etcd-dump-log_test.go
tools/etcd-dump-logs/main.go

enables and fixes [usestdlibvars](https://golangci-lint.run/usage/linters/#usestdlibvars) linter issues

fix: enable usestdlibvars linter

---

server/storage/backend/backend.go

Fix for the govet error reported here: https://github.com/etcd-io/etcd/pull/18854#issuecomment-2464461492

build: fix govet shadow err

---

mvcc/backend/backend.go

See https://github.com/etcd-io/etcd/issues/18841 for details. Backport of https://github.com/etcd-io/etcd/pull/18851 to 3.4

[3.4] fix(defrag): close temp file in case of error

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

See https://github.com/etcd-io/etcd/issues/18841 for details.
- 3.4: https://github.com/etcd-io/etcd/pull/18855
- 3.5 https://github.com/etcd-io/etcd/pull/18854

docs(CHANGELOG): update 3.4/3.5 changelog with defrag close fix

---

scripts/release.sh

[3.4] release: properly change working dir if tmp location already exists

---

CHANGELOG/CHANGELOG-3.5.md

changelog: add GO-2024-3250 remediation entry

---

tests/robustness/main_test.go
tests/robustness/traffic/traffic.go

cc @ah8ad3 @ahrtr @MadhavJivrajani @henrybear327 @siyuanfoundation @jmhbnz

Add jitter to failpoint injection to cover periodily executed compaction

---

clientv3/integration/lease_test.go
clientv3/lease.go

Backport of https://github.com/etcd-io/etcd/pull/18893

[3.4] fix runtime error: comparing uncomparable type

---

tools/benchmark/cmd/watch_latency.go

Fix benchmark indexing

---

server/etcdserver/server.go

Fix gofump error due to merge race

---

tests/robustness/failpoint/cluster.go

cc @ahrtr @jmhbnz 
Fixes https://github.com/etcd-io/etcd/issues/18929

Handle non-linearized MemberList in v3.4 for robustness tests

---

etcdutl/go.mod
etcdutl/go.sum
go.mod
go.sum
server/go.mod
server/go.sum
tests/go.mod
tests/go.sum

This pull request completes this week's etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit#gid=1394774387) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).
- https://github.com/etcd-io/etcd/pull/18986
- https://github.com/etcd-io/etcd/pull/18990
- https://github.com/etcd-io/etcd/pull/18989
- https://github.com/etcd-io/etcd/pull/18988
- https://github.com/etcd-io/etcd/pull/18987
- https://github.com/etcd-io/etcd/pull/18985
- https://github.com/etcd-io/etcd/pull/18984

[2024-12-02] Manual Dependency Bump

---

CHANGELOG/CHANGELOG-3.5.md

Followup to https://github.com/etcd-io/etcd/pull/19028

Format the 3.5 changelog

---

server/storage/wal/wal.go

Add more debug info when running into ErrSliceOutOfRange when reading WAL. If the gap between offset and len(ents) is huge, then most likely the WAL record is somehow corrupted, otherwise if it's just +-1, then most likely it's a bug (i.e of the raft).

Add more debug info when running into ErrSliceOutOfRange when reading WAL

---

CHANGELOG/CHANGELOG-3.5.md

* add item: support custom content check offline in v2store
REF: https://github.com/etcd-io/etcd/pull/19113

CHANGELOG: update CHANGELOG-3.5.md

---

etcdutl/etcdutl/check_command.go

It's follow-up for https://github.com/etcd-io/etcd/pull/19113#discussion_r1910213211

[3.5] etcdutl/etcdutl: use datadir package to build wal/snapdir

---

server/embed/etcd.go
server/embed/serve.go
server/etcdserver/server.go
tests/integration/embed/embed_test.go

#19150: Backport https://github.com/etcd-io/etcd/pull/19139 to 3.5

[3.5] Avoid deadlock in etcd.Close when stopping during bootstrapping

---

etcdutl/etcdutl/common.go
etcdutl/etcdutl/migrate_command.go

This PR is extracted from https://github.com/etcd-io/etcd/pull/19168
cc @fuweid @serathius @ivanvc @jmhbnz @siyuanfoundation

Move getLatestWALSnap into etcdutl/common.go

---

tests/robustness/traffic/kubernetes.go

The expected sum of weights should be 100, not 1000.

tests: fix wrong number in comment.

---

client/pkg/logutil/zap_test.go

This patch adds a test before #19170.

client/pkg/logutil: add test for MergeOutputPaths

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

Update 3.4/3.5 changelog for PR #19166 and #19167

Update 3.4/3.5 CHANGELOG with fix for deadlock in etcd.Close

---

CHANGELOG/CHANGELOG-3.5.md

Link to https://github.com/etcd-io/etcd/pull/19258 and https://github.com/etcd-io/etcd/issues/19172

Update 3.5 changelog to cover the race condition fix

---

CHANGELOG/CHANGELOG-3.5.md

Issue https://github.com/etcd-io/etcd/issues/19119

docs(CHANGELOG): add release date of etcd v3.5.18

---

tests/robustness/traffic/kubernetes.go

Introduced by: https://github.com/etcd-io/etcd/pull/19137

tests/robustness: continue should ignore last key

---

CHANGELOG/CHANGELOG-3.5.md

Add changelog entry from https://github.com/etcd-io/etcd/pull/19275

changelog: add mixed rw performance evaluation backport

---

CHANGELOG/CHANGELOG-3.5.md

As reported in https://github.com/etcd-io/etcd/issues/19119#issuecomment-2615358030.

changelog: add entries regarding 3.5.18 dependency updates

---

tests/e2e/metrics_test.go

Followup of https://github.com/etcd-io/etcd/pull/19302

[test] Close the http response body

---

server/etcdserver/api/membership/cluster.go

[3.5] Add more info into log for learner member operations

---

server/etcdserver/api/membership/cluster.go

Add learner id into log when being promoted

---

CHANGELOG/CHANGELOG-3.5.md

Addressing comment from https://github.com/etcd-io/etcd/pull/19280#issuecomment-2619651371.

CHANGELOG(3.5): Add entry for #19280

---

tests/robustness/failpoint/network.go

Add more debug info into waitTillSnapshot

---

.github/workflows/release.yaml

[3.4]Fix(ci): upgrade artifact actions to v4 

---

tests/framework/e2e/cluster.go
tests/framework/e2e/cluster_test.go
tests/framework/e2e/etcd_process.go

https://github.com/etcd-io/etcd/pull/19352#discussion_r1951519034
cc @ajaysundark @fuweid @siyuanfoundation @serathius 
One this PR gets merges, @ajaysundark please rebase your PR, and uncomment the code at line 639 - 642

Minor refacotr on the e2e test framework

---

CHANGELOG/CHANGELOG-3.4.md

Follow up from: https://github.com/etcd-io/etcd/pull/19197#issuecomment-2595191749

CHANGELOG-3.4: Add entry from #19197

---

server/etcdserver/apply/apply.go

Rename `applierMembership` to `ApplierMembership` to fix the `unexported-return` lint error

---

tests/e2e/cluster_downgrade_test.go
tests/framework/e2e/cluster.go
tests/framework/e2e/downgrade.go
tests/robustness/failpoint/cluster.go

Fixes: 65159a2b9677673a6f (*: Update cases related to Downgrade)

deflake: TestDowngradeCancellationAfterDowngrading1InClusterOf3

---

Documentation/dev-guide/apispec/swagger/rpc.swagger.json
api/etcdserverpb/rpc.pb.go
api/etcdserverpb/rpc.proto

To highlight that it doesn't honour the limit and filters (Min or Max, Create or Modify, Revisions). This resolves etcd issue #18267
Signed-off-by: Ashik J M <ashikjm@gmail.com>

etcdserver: Update description for count field in the RangeResponse message

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md
CHANGELOG/CHANGELOG-3.6.md

Include notes from:
v3.4:
- #19529
v3.5:
- #19528
- #19530
v3.6:
- #19495
- #19527
- #19531
- #19522

Update CHANGELOGs with recent merged pull requests

---

CHANGELOG/CHANGELOG-3.5.md
CHANGELOG/CHANGELOG-3.6.md

Update changelog with v3.5.19 v3.6.0-rc.2 release dates

---

tests/robustness/validate/patch_history.go

Missed that during review of https://github.com/etcd-io/etcd/pull/19383
cc @joshuazh-x @ahrtr @henrybear327 @fuweid @siyuanfoundation

Use clientPutCount instead of persistedPutCount as not all client requests are persisted

---

server/etcdserver/api/membership/cluster.go
server/etcdserver/api/v3rpc/watch.go
server/etcdserver/raft.go
server/etcdserver/server.go
server/mvcc/backend/backend.go
server/mvcc/backend/batch_tx.go
server/mvcc/kvstore.go
server/mvcc/kvstore_compaction.go

partial fix https://github.com/etcd-io/etcd/issues/17817

[release-3.5] back port gofail comments

---

server/etcdserver/server_test.go

extracted from https://github.com/etcd-io/etcd/pull/19563
cc @serathius

[release-3.5/test] Update server unit test cases to set a backend

---

pkg/expect/expect_test.go
pkg/netutil/netutil_test.go
pkg/proxy/server_test.go
pkg/traceutil/trace_test.go

Follow up on: https://github.com/etcd-io/etcd/pull/19440#issuecomment-2691945198
Replace Contexts with the one provided by the test package.
Part of #19581

pkg: address Go 1.24 usetesting issues

---

client/internal/v2/client_test.go
client/internal/v2/keys_test.go
client/internal/v2/members_test.go
client/v3/client_test.go
client/v3/credentials/credentials_test.go
client/v3/ctx_test.go
client/v3/ordering/kv_test.go
client/v3/txn_test.go
client/v3/watch_test.go

Apply `usetesting --fix ./...` on client packages

client: address Go 1.24 usetesting issues

---

server/auth/jwt_test.go
server/auth/simple_token_test.go
server/auth/store_test.go
server/embed/auth_test.go
server/etcdserver/api/rafthttp/stream_test.go
server/etcdserver/api/v3rpc/validationfuzz_test.go
server/etcdserver/server_test.go
server/etcdserver/txn/txn_test.go
server/etcdserver/version/version_test.go
server/lease/leasehttp/http_test.go
server/storage/backend/hooks_test.go
server/storage/mvcc/hash_test.go
server/storage/mvcc/kv_test.go
server/storage/mvcc/kvstore_bench_test.go
server/storage/mvcc/kvstore_compaction_test.go
server/storage/mvcc/kvstore_test.go

Apply `usetesting --fix ./...` on server packages

server: address Go 1.24 usetesting issues

---

etcdctl/ctlv3/command/printer.go
tests/e2e/ctl_v3_member_test.go
tests/e2e/etcd_mix_versions_test.go
tests/framework/e2e/cluster.go
tests/framework/e2e/etcdctl.go

cc @fuweid @ivanvc @jmhbnz @serathius @siyuanfoundation 
Note main & release-3.6 do not have this issue.

[release-3.5] Fix the issue that learner promotion command doesn't support json output

---

etcdutl/snapshot/v3_snapshot_test.go

Apply `usetesting --fix ./...` on etcdutl packages

etcdutl: address Go 1.24 usetesting issues

---

tests/robustness/README.md

- wordsmithing
- fix broken links

Update the robustness test README

---

tests/robustness/report/client.go

Fix wrong error message in `loadKeyValueOperations`

---

Documentation/contributor-guide/features.md

Update the feature development process to reflect the changes brought by feature gates.

doc: update feature development guide.

---

tests/framework/e2e/config.go

Returns the string representation of the `ClusterVersion`

---

tests/e2e/etcd_release_upgrade_test.go

Backport: [#19634](https://github.com/etcd-io/etcd/pull/19634))

[3.6] e2e: add upgrade test for clusters set up by promoted members

---

tests/robustness/model/history.go
tests/robustness/model/history_test.go

Reference:
- https://github.com/etcd-io/etcd/pull/19651#discussion_r2011549432

[Robustness test] Improve append history checks

---

CHANGELOG/CHANGELOG-3.5.md
CHANGELOG/CHANGELOG-3.6.md

Add missing entries from:
- #19686
- #19560
- #19561
- #19687

CHANGELOG: Add missing entries in v3.6.0-rc.3 and v3.5.21

---

tests/robustness/client/kvhash.go
tests/robustness/main_test.go

Reference:
- https://github.com/etcd-io/etcd/pull/19680

[Robustness] Improve HashKV check comments

---

Documentation/contributor-guide/bump_etcd_version_k8s.md

Clarified according to https://github.com/etcd-io/etcd/pull/19717#issuecomment-2789183940

K8s bump etcd version guide

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.6.md

CHANGELOG: update items with release date

---

tests/antithesis/Dockerfile.config

Reference: https://github.com/etcd-io/etcd/issues/19299

[Robustness Test] Fix Dockerfile.config

---

tests/antithesis/test-template/go-delete-keys/go.mod
tests/antithesis/test-template/go-delete-keys/go.sum
tests/antithesis/test-template/go-delete-keys/serial_driver_delete_keys.go

This PR complements [this](https://github.com/etcd-io/etcd/pull/19765) PR which added a Go client for robustness tests. With this PR we have introduced the Antithesis library.

Add Antithesis package imports

---

.github/workflows/antithesis-test.yml

[Robustness test] Merge Antithesis Github workflows

---

server/etcdserver/txn/txn.go

/cc @ahrtr @fuweid @siyuanfoundation

Extract ensureTrace function

---

client/v3/naming/endpoints/endpoints.go

chore(client/v3/naming): deprecate Metadata field in Endpoint struct

---

Makefile
scripts/test.sh

Address reviews in #19815
/cc @ivanvc @jmhbnz

fix: test-release checks

---

tests/integration/clientv3/maintenance_test.go

Fixes: #19832 
Not sure it's related to https://github.com/etcd-io/etcd/pull/19780
ping @ahrtr
cc @dfawley

tests/integration: deflaky TestMaintenanceSnapshotTimeout

---

Documentation/contributor-guide/dependency_management.md

Update dependency management guide

---

scripts/release_notes.tpl.txt
scripts/test.sh

fix: https://github.com/etcd-io/etcd/issues/17278

release: Fix the tar unzip command,  avoid permissions issues

---

tests/antithesis/test-template/robustness/main.go
tests/robustness/main_test.go
tests/robustness/report/report.go
tests/robustness/validate/operations.go
tests/robustness/validate/patch_history_test.go
tests/robustness/validate/validate.go
tests/robustness/validate/validate_test.go

This PR addresses https://github.com/etcd-io/etcd/issues/19840 and is supposed to run validation on the history collected by the recording client.

[Antithesis] Validate history collected by recording client

---

tests/antithesis/test-template/Dockerfile

Fix antithesis driver command type

---

Documentation/contributor-guide/release.md

doc: add example PR of kubernetes/org for release.

---

tests/antithesis/README.md

[Antithesis] Document running validation

---

CHANGELOG/CHANGELOG-3.6.md

/cc @jmhbnz @ivanvc @siyuanfoundation

Update v3.6.0-rc.5 release date

---

tests/antithesis/test-template/robustness/main.go

antithesis: replaced Reachable/Unreachable assertion with Always

---

tests/antithesis/Makefile
tests/antithesis/README.md
tests/antithesis/docker-compose.yml
tests/antithesis/test-template/robustness/main.go

Fix #19882 
This will likely have a conflict with #19887.  Once that is merged, I can rebase this PR and resolve the conflict.

[Antithesis] Get access to etcd data directory

---

tests/robustness/validate/validate.go

With Antithesis tests we no longer have guarantee of any requests passing.

Disable validation of assumption for persisted requests

---

client/v3/client.go
client/v3/client_test.go

Fixes  https://github.com/etcd-io/etcd/issues/19830

feat(client/v3): export username/password error

---

tests/robustness/validate/operations_test.go

Add benchmark for linearization

---

tests/robustness/model/deterministic.go

```
│  new.bench  │             new2.bench              │
│   sec/op    │   sec/op     vs base                │
ValidateLinearizableOperations/Successes-14             3.610m ± 3%   3.612m ± 3%        ~ (p=0.796 n=10)
ValidateLinearizableOperations/AllFailures-14           1.541m ± 3%   1.534m ± 4%        ~ (p=0.143 n=10)
ValidateLinearizableOperations/PutFailuresWithRead-14   1.360m ± 1%   1.058m ± 2%  -22.24% (p=0.000 n=10)
geomean                                                 1.963m        1.803m        -8.17%
```

Avoid copying state for read requests

---

tests/antithesis/docker-compose.yml
tests/antithesis/test-template/robustness/main.go
tests/robustness/main_test.go
tests/robustness/report/client.go
tests/robustness/report/client_test.go
tests/robustness/report/report.go

[Antithesis] dump result to robustness report

---

CHANGELOG/CHANGELOG-3.6.md

:partying_face: 
/cc @ahrtr @jmhbnz 

Update for release v3.6.0

---

tests/integration/member_test.go

This is a cherry-pick of #19947 
cc: @ahrtr

[release-3.5][Integration Test]: Add test for panic-free removal of non-existent members

---

.github/workflows/antithesis-test.yml
tests/antithesis/Makefile
tests/antithesis/README.md
tests/antithesis/docker-compose.yml

Build dedicated etcd image for antithesis

---

tests/antithesis/test-template/robustness/main.go
tests/robustness/client/watch.go
tests/robustness/main_test.go
tests/robustness/report/client.go

[Antithesis] Add support for watch requests

---

.github/workflows/antithesis-test.yml

Fix building antithesis etcd image

---

tests/antithesis/test-template/robustness/main.go
tests/robustness/client/watch.go

Fix missing KV reports in antithesis

---

tests/antithesis/Makefile
tests/robustness/client/watch.go

Prevent exiting before watch closes

---

tests/robustness/traffic/etcd.go

Add StaleGet traffic for antithesis

---

tests/robustness/model/describe.go
tests/robustness/model/non_deterministic.go

Improve visualization to have a more summarized description of states
ref: https://github.com/etcd-io/etcd/issues/19901

Make visualization more compact

---

tests/robustness/report/wal.go
tests/robustness/report/wal_test.go

Observed in https://linuxfoundation.antithesis.com/report/-W0W_c-65bqGb25mnjA4-j-E/7Dza3vy0KQL9i2M8cFq1ZDnOXCtG15MEqRAgCm1CuW4.html?auth=v2.public.eyJuYmYiOiIyMDI1LTA1LTE3VDE1OjQ5OjAzLjA3ODc4NjQ1MVoiLCJzY29wZSI6eyJSZXBvcnRTY29wZVYxIjp7ImFzc2V0IjoiN0R6YTN2eTBLUUw5aTJNOGNGcTFaRG5PWEN0RzE1TUVxUkFnQ20xQ3VXNC5odG1sIiwicmVwb3J0X2lkIjoiLVcwV19jLTY1YnFHYjI1bW5qQTQtai1FIn19fUYm9OyOli6grMnUGlCpul9yPSbQreCQLH6K-RLyCY4t82Ln2855-wZQF_fWDKDik7ubVRcU0kdkyyUykU4feAQ

Allow case where only one member observed all requests

---

tests/robustness/traffic/etcd.go

Add Stale List traffic for antithesis

---

tests/robustness/traffic/etcd.go

As part of fixing #19941 
This will make it ready when you need it @serathius

Add delete traffic for antithesis

---

tests/antithesis/test-template/robustness/traffic/main.go
tests/robustness/traffic/traffic.go

Measure traffic during test

---

tests/robustness/traffic/etcd.go

Part of the series to fix #19941

Add PutWithLease traffic

---

CHANGELOG/CHANGELOG-3.6.md

Please see https://github.com/etcd-io/etcd/pull/20043

Add changelog for deprecated/removed otelgrpc API

---

LICENSE
api/LICENSE
bill-of-materials.json
client/internal/v2/LICENSE
client/pkg/LICENSE
client/v3/LICENSE
etcdctl/LICENSE
etcdutl/LICENSE
pkg/LICENSE
server/LICENSE
tests/LICENSE

Provide date based on file creation date
/cc @ahrtr @ivanvc @jmhbnz @fuweid

Fix LICENSE file

---

cache/LICENSE
cache/OWNERS
cache/README.md
cache/cache.go
cache/go.mod
scripts/test.sh
scripts/test_lib.sh

Needed for https://github.com/etcd-io/etcd/issues/19371
/cc @ahrtr @fuweid @siyuanfoundation @jmhbnz @ivanvc

Setup directory for cache

---

tests/integration/clientv3/concurrency/election_test.go
tests/integration/clientv3/concurrency/mutex_test.go
tests/integration/clientv3/concurrency/session_test.go

chore(test): address Go usetesting for `concurrency`

---

tests/integration/clientv3/connectivity/black_hole_test.go
tests/integration/clientv3/connectivity/dial_test.go
tests/integration/clientv3/connectivity/network_partition_test.go
tests/integration/clientv3/connectivity/server_shutdown_test.go

chore(test): address Go usetesting for `connectivity`

---

tests/integration/clientv3/lease/lease_test.go

chore(test): address usetesting issues in `lease_test.go`

---

tests/integration/clientv3/watch_test.go

chore(test): address Go usetesting for `watch_test`

---

CHANGELOG/CHANGELOG-3.6.md

Link to 
- https://github.com/etcd-io/etcd/pull/20051
- https://github.com/etcd-io/etcd/pull/20071
- https://github.com/etcd-io/etcd/issues/20047
- https://github.com/etcd-io/etcd/issues/20009
cc @ivanvc @jmhbnz

Update changelog-3.6 to cover to fixes for 3.6.1

---

.github/workflows/antithesis-test.yml

/cc @fuweid @ahrtr @siyuanfoundation @jmhbnz @ivanvc @henrybear327 @nwnt

Fix antithesis makefile target

---

tests/integration/v3_auth_test.go

chore(test): address Go usetesting for `v3_auth_test`

---

tests/integration/v3_grpc_test.go

chore(test): address Go usetesting for `v3_grpc_test`

---

tests/integration/v3_lease_test.go

chore(test): address Go usetesting for `v3_lease_test`

---

tests/integration/clientv3/cluster_test.go
tests/integration/clientv3/kv_test.go
tests/integration/clientv3/maintenance_test.go
tests/integration/clientv3/metrics_test.go
tests/integration/clientv3/mirror_auth_test.go
tests/integration/clientv3/mirror_test.go
tests/integration/clientv3/namespace_test.go
tests/integration/clientv3/naming/endpoints_test.go
tests/integration/clientv3/naming/resolver_test.go
tests/integration/clientv3/ordering_kv_test.go
tests/integration/clientv3/ordering_util_test.go
tests/integration/clientv3/snapshot/v3_snapshot_test.go
tests/integration/clientv3/txn_test.go
tests/integration/clientv3/user_test.go
tests/integration/clientv3/util.go
tests/integration/clientv3/watch_fragment_test.go

chore(test): address Go usetesting for `clientV3`

---

tests/robustness/traffic/etcd.go

ref: https://github.com/etcd-io/etcd/issues/19941

Add List requests to Antithesis traffic

---

client/v3/client_test.go

chore(clientV3): address Go usetesting for clientV3

---

tools/.golangci.yaml

chore(test): Re-enable usetesting linter

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md
CHANGELOG/CHANGELOG-3.6.md

Adds each fix PR for previous release branches.

CHANGELOG: add backport fix notes for #19577

---

server/embed/config.go
server/embed/config_test.go

Backport https://github.com/etcd-io/etcd/pull/20111 to 3.6.
cc @fuweid @ivanvc @jmhbnz @serathius 

[release-3.6] Add validation to ensure that there is NO empty discovery endpoint

---

CHANGELOG/CHANGELOG-3.6.md
CHANGELOG/CHANGELOG-3.7.md

Link to 
- https://github.com/etcd-io/etcd/pull/20109
- https://github.com/etcd-io/etcd/pull/20113
- https://github.com/etcd-io/etcd/pull/20117

Update changelog to cover v2discovery and client/v2 removals

---

CHANGELOG/CHANGELOG-3.6.md

Add CHANGELOG for #20128.
Part of #20126.

CHANGELOG(3.6): Add Go 1.23.10 note

---

CHANGELOG/CHANGELOG-3.6.md

CHANGELOG(3.6): Set v3.6.1 release date

---

tests/antithesis/test-template/robustness/traffic/main.go

Add defragment support

---

tests/antithesis/test-template/robustness/finally/main.go
tests/antithesis/test-template/robustness/traffic/main.go

Add Kubernetes Traffic Type

---

tests/robustness/model/deterministic.go
tests/robustness/model/history.go

/cc @joshjms @nwnt @fuweid @siyuanfoundation 
Fixes https://github.com/etcd-io/etcd/issues/20098

Treat future revision as client error

---

.github/workflows/antithesis-test.yml

Ref: https://github.com/etcd-io/etcd/issues/20112

Add single node cluster config to Antithesis tests in Github Actions

---

.github/workflows/antithesis-test.yml

Ref: https://github.com/etcd-io/etcd/pull/20216 https://github.com/etcd-io/etcd/issues/20112

[Antithesis] Fix building the client image

---

server/etcdserver/api/v3rpc/watch.go
server/storage/mvcc/watchable_store.go
server/storage/mvcc/watcher_test.go

Ref https://github.com/etcd-io/etcd/issues/20221
/cc @ahrtr @fuweid @siyuanfoundation

Skip sending progress notification for watch with starting revision in the future

---

server/storage/mvcc/watchable_store.go

Link to https://github.com/etcd-io/etcd/issues/20221
cc @fuweid @serathius

Add verification to verify the watch response have a bigger revision than minRev

---

server/etcdserver/api/v3rpc/watch.go
server/storage/mvcc/watchable_store.go
server/storage/mvcc/watcher_test.go

Backport https://github.com/etcd-io/etcd/pull/20229 to release-3.6
/cc @ahrtr @fuweid

[release-3.6] Skip sending progress notification for watch with starting revision in the future

---

tools/etcd-dump-db/main.go
tools/etcd-dump-db/utils.go

Part of https://github.com/etcd-io/etcd/issues/20265 
cc @ahrtr @jmhbnz @ivanvc 

 chore(client): remove existFileOrDir funce

---

cache/demux.go
cache/predicate.go
cache/ringbuffer.go
cache/ringbuffer_test.go

cache: remove AfterRev entry predicate

---

mvcc/watchable_store.go
mvcc/watchable_store_test.go

Manual backport https://github.com/etcd-io/etcd/pull/20281
Ref https://github.com/etcd-io/etcd/issues/20221
/cc @ahrtr @fuweid

[release-3.4] Avoid lowering revision of watchers in the future after restore

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md
CHANGELOG/CHANGELOG-3.6.md
tests/robustness/README.md

Document #20221 in robustness track record

---

CHANGELOG/CHANGELOG-3.4.md
CHANGELOG/CHANGELOG-3.5.md

Part of: https://github.com/etcd-io/etcd/issues/20313

CHANGELOG(3.4,3.5): Add Go 1.23.11 note

---

server/etcdserver/raft.go
server/etcdserver/server.go
tests/e2e/force_new_cluster_test.go
tests/framework/e2e/cluster.go
tests/framework/e2e/etcd_process.go

Backport https://github.com/etcd-io/etcd/pull/20055 to 3.5.
Link to https://github.com/etcd-io/etcd/issues/20009

[release-3.5] Fix the issue that --force-new-cluster can't remove all other members in a corner case

---

CHANGELOG/CHANGELOG-3.5.md

Link to
- https://github.com/etcd-io/etcd/pull/20339
- https://github.com/etcd-io/etcd/issues/20009

Update 3.5 changelog to cover the --force-new-cluster issue

---

scripts/build-binary.sh
scripts/build-docker.sh
scripts/build-release.sh
scripts/build.sh
scripts/build_lib.sh
scripts/build_tools.sh
scripts/codecov_upload.sh
scripts/fix.sh
scripts/fuzzing.sh
scripts/genproto.sh
scripts/markdown_diff_lint.sh
scripts/measure-testgrid-flakiness.sh
scripts/release.sh
scripts/release_mod.sh
scripts/sync_go_toolchain_directive.sh
scripts/test.sh
scripts/test_images.sh
scripts/test_lib.sh
scripts/test_utils.sh
scripts/update_dep.sh
scripts/update_proto_annotations.sh
scripts/updatebom.sh
scripts/verify_genproto.sh
scripts/verify_go_versions.sh
scripts/verify_golangci-lint_version.sh
scripts/verify_proto_annotations.sh

changed the shebang command to match other scripts

Tooling: Added licence header

---

cache/cache.go
tests/integration/cache_test.go

cache: enable Watch on arbitrary start_revision

---

tests/e2e/v2store_deprecation_test.go

Followup to https://github.com/etcd-io/etcd/pull/20357

[release-3.5] Fix flaky TestCtlV2CustomContentWithAuthData

---

server/etcdserver/api/membership/storev2.go
server/etcdserver/api/membership/storev2_test.go

Fix https://github.com/etcd-io/etcd/issues/20351
Link to https://github.com/etcd-io/etcd/pull/20357

Fix v2store check returning wrong result even there isn't any auth data

---

CHANGELOG/CHANGELOG-3.6.md

Link to 
- https://github.com/etcd-io/etcd/pull/20370
- https://github.com/etcd-io/etcd/issues/20351
cc @fuweid @ivanvc @jmhbnz

Update 3.6 changelog to cover the v2store check returning wrong result

---

etcd.conf.yml.sample
server/etcdmain/config.go
server/etcdmain/help.go

Backport PR of #20328 for `release-3.5`
Issue: #20224

[release-3.5] Updated help for --quota-backend-bytes

---

client/v3/watch.go

Sorry, I forgot to update the comment in the last PR, so I'm opening this to fix that.
@serathius @fuweid

modify the comment for the now public CancelReason

---

etcdctl/ctlv3/command/printer_json_test.go

This PR includes refactoring changes only. No new functionality is introduced.
- Updated printer_json.go to follow consistent import naming conventions.
- Reduced code duplication in printer_json_test.go by extracting common setup logic into helper functions.
These changes improve code readability and maintainability without altering behavior.

etcdctl: refactor `printer_json` files

---

cache/cache.go
tests/integration/cache_test.go

cache: rename ErrUnsupportedWatch, add ErrKeyRangeInvalid

---

server/etcdserver/api/membership/cluster.go
tests/e2e/member_no_proxy_test.go

Fix https://github.com/etcd-io/etcd/issues/20340
Refer to https://github.com/etcd-io/etcd/issues/20340#issuecomment-3105037914

Check promotion against v2store when updating v2store

---

client/v3/op.go

expose IsSortSet so that cache can validate unsupported get flags

---

tests/robustness/README.md

robustness: update README.md

---

tests/antithesis/server/Dockerfile

Fix Antithesis makefile if statement

---

tests/antithesis/config/docker-compose-1-node.yml
tests/antithesis/config/docker-compose-3-node.yml

Turn ETCD_VERIFY on for antithesis tests

---

tests/robustness/Makefile
tests/robustness/README.md

- Add robustness test for issue 15220
- Close #18926
``` shell
make test-robustness-issue15220
```
<details>
<summary>detail log</summary>
``` shell
tail -n 100 out.log
logger.go:146: 2025-07-31T23:32:51.873+0900	ERROR	Broke watch guarantee	{"guarantee": "bookmarkable", "client": 2, "revision": 462}
logger.go:146: 2025-07-31T23:32:51.873+0900	ERROR	Broke watch guarantee	{"guarantee": "bookmarkable", "client": 2, "revision": 462}
logger.go:146: 2025-07-31T23:32:51.873+0900	ERROR	Broke watch guarantee	{"guarantee": "bookmarkable", "client": 2, "revision": 462}
logger.go:146: 2025-07-31T23:32:51.873+0900	ERROR	Broke watch guarantee	{"guarantee": "bookmarkable", "client": 2, "revision": 462}
logger.go:146: 2025-07-31T23:32:51.873+0900	ERROR	Broke watch guarantee	{"guarantee": "bookmarkable", …
```

tests: add robustness test for issue 15220

---

tests/robustness/README.md

- Update incorrect example
- Format README
- To help developers read the README

Update robustness README

---

.github/workflows/antithesis-verify.yml

https://github.com/etcd-io/etcd/issues/19793

Test Antithesis makefile targets in a CI run

---

cache/cache.go
cache/cache_test.go
cache/config.go
cache/store.go
tests/integration/cache_test.go

cache: implement storage for last‐observed state

---

tests/integration/cache_test.go

cache: refactor TestCacheWithoutPrefixGet for different initialization scenarios and added shared applyEvents helper

---

tests/robustness/report/wal.go
tests/robustness/report/wal_test.go

/cc @fuweid @siyuanfoundation @nwnt @henrybear327 @joshjms
Implements merging incomplete histories needed for https://github.com/etcd-io/etcd/pull/20239

Use raft index to merge WAL files allowing to merge incomplete histories

---

CHANGELOG/CHANGELOG-3.7.md

Add a change log item for #20420 per https://github.com/etcd-io/etcd/pull/20420#issuecomment-3154219833

Update grpc-middleware migration in CHANGELOG-3.7

---

tests/e2e/reproduce_18667_test.go

add e2e to reproduce issue 18667

---

CHANGELOG/CHANGELOG-3.7.md

Part of: #17777 #20162
cc @ahrtr @ivanvc @siyuanfoundation

CHANGELOG: update 3.7 changelog, add organize etcdctl commads related

---

CHANGELOG/CHANGELOG-3.6.md

Link to
- https://github.com/etcd-io/etcd/pull/20496
- https://github.com/etcd-io/etcd/pull/20494
- https://github.com/etcd-io/etcd/issues/20495
cc. @fuweid @ivanvc @jmhbnz @serathius

Update 3.6 changelog to cover the confState not populated issue

---

etcdutl/go.mod
etcdutl/go.sum
go.mod
go.sum
server/go.mod
server/go.sum
tests/go.mod
tests/go.sum

Bump bbolt to v1.4.3

---

go.mod
go.sum

[release-3.4] Bump bbolt to v1.3.12

---

etcdutl/go.mod
etcdutl/go.sum
go.mod
go.sum
server/go.mod
server/go.sum
tests/go.mod
tests/go.sum

[release-3.6] Bump bbolt to v1.4.3

---

etcdctl/go.mod
etcdctl/go.sum
etcdutl/go.mod
etcdutl/go.sum
go.mod
go.sum
server/go.mod
server/go.sum
tests/go.mod
tests/go.sum

[release-3.5] Bump bbolt to v1.3.12

---

cache/cache.go
cache/demux_test.go
cache/watcher.go

cache: change watcher.eventQueue to respCh (clientv3.WatchResponse)

---

tests/robustness/coverage/coverage_test.go

It prints the table of mapping "key pattern" to average "uses" (number of `Txn` that referenced the lease) and TTL (set in the call).

Expand Lease test case in trace analysis

---

cache/cache.go
cache/snapshot.go
cache/store.go
cache/store_test.go
tests/integration/cache_test.go

cache: implement snapshots & enable cache.Get(rev>0)

---

tests/integration/cache_test.go

cache: assert ErrFutureRev in testGet

---

tests/robustness/client/watch.go

Fix minor linter warning in robustness tests

---

CHANGELOG/CHANGELOG-3.5.md
CHANGELOG/CHANGELOG-3.6.md

CHANGELOG: Set release 3.5.23 and 3.6.5 dates

---

tests/robustness/validate/watch.go

Reduced watch reliable runtime from 50s to 5s.
cc @henrybear327

Use reflect.DeepEqual to speed up comparison

---

tests/integration/clientv3/watch/v3_watch_restore_test.go
tests/integration/clientv3/watch/v3_watch_test.go
tests/integration/clientv3/watch/watch_fragment_test.go
tests/integration/clientv3/watch/watch_test.go

Refactor watch tests

---

client/pkg/testutil/leak.go
client/v3/client_test.go
client/v3/watch.go
pkg/expect/expect.go
pkg/grpctesting/stub_server.go
server/etcdserver/api/v3discovery/discovery_test.go
server/proxy/grpcproxy/watch_broadcasts.go
server/storage/mvcc/watchable_store_test.go

chore: fix some typos in comment
