Documentation/dev-guide/apispec/swagger/rpc.swagger.json, Documentation/dev-guide/apispec/swagger/v3election.swagger.json, Documentation/dev-guide/apispec/swagger/v3lock.swagger.json, api/etcdserverpb/gw/rpc.pb.gw.go, server/etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go, server/etcdserver/api/v3lock/v3lockpb/gw/v3lock.pb.gw.go
TODO: ensure the generated code is up-to-date in the CI.
Signed-off-by: spacewander <spacewanderlzx@gmail.com>
=> chore: commit the change generated by scripts/genproto.sh

tests/common/e2e_test.go, tests/common/integration_test.go, tests/framework/config/client.go
This PR is on top of https://github.com/etcd-io/etcd/pull/14615
We defines two common `WithAuth` functions for e2e and integration test respectively. They are calling `integration.WithAuth` and `e2e.WithAuth` respectively.
cc @serathius @spzala @mitake @ptabor @chaochn47 @veshij
=> test: add common function "WithAuth"

.github/workflows/linearizability.yaml, Makefile, scripts/build_lib.sh, tests/framework/e2e/cluster.go, tests/framework/e2e/etcd_process.go, tests/linearizability/failpoints.go, tests/linearizability/linearizability_test.go, tools/mod/go.mod, tools/mod/go.sum, tools/mod/tools.go
=> tests: Add linearizability tests scenario for #14370

tests/common/main_test.go, tests/common/unit_test.go, tests/framework/framework.go, tests/framework/interface.go
```
// When a build tag (e.g. e2e or integration) isn't configured in IDE,
// then IDE may complain "Unresolved reference 'WithAuth'". So we need
// to define a default WithAuth to resolve such case.
```
cc @chaochn47 @serathius @spzala @ptabor
=> test: define a default WithAuth to resolve Unresolved reference error

tests/common/alarm_test.go, tests/common/compact_test.go, tests/common/defrag_test.go, tests/common/endpoint_test.go, tests/common/kv_test.go, tests/common/lease_test.go, tests/common/main_test.go, tests/common/member_test.go, tests/common/role_test.go, tests/common/wait_leader_test.go, tests/framework/config/cluster.go, tests/framework/e2e.go, tests/framework/integration.go
This PR tries to fix the anti-pattern naming problem(see [#14389](https://github.com/etcd-io/etcd/pull/14389#discussion_r955668262)), such as `DisableStrictReconfigCheck`(written by me🤣).
As far as I see, at least 4 structs have this problem:
1. [ctlCtx](https://github.com/etcd-io/etcd/blob/8ce81a1624e47f173d195bc335145b9923ee35e6/tests/e2e/ctl_v3_test.go#L124)
2. [config.ClusterConfig](https://github.com/etcd-io/etcd/blob/main/tests/framework/config/cluster.go)
3. [e2e.EtcdProcessClusterConfig](https://github.com/etcd-io/etcd/blob/8ce81a1624e47f173d195bc335145b9923ee35e6/tests/framework/e2e/cluster.go#L138)
4. [integration.ClusterConfig](https://github.com/etcd-io/etcd/blob/8ce81a1624e47f173d195bc335145b9923ee35e6/tests/framework/integration/cluster.go#L135)
This PR only tries to fix …
=> test: fix anti-pattern naming problem in config.ClusterConfig

tests/e2e/cluster_downgrade_test.go, tests/e2e/corrupt_test.go, tests/e2e/ctl_v3_grpc_test.go, tests/e2e/etcd_grpcproxy_test.go, tests/e2e/v2store_deprecation_test.go, tests/framework/e2e.go, tests/framework/e2e/cluster.go, tests/framework/e2e/etcdctl.go, tests/framework/integration.go, tests/framework/integration/cluster.go, tests/framework/interface.go
1. set up a default `withAuth` option in common test entry point
2. `NewEtcdctl` accepts a client option that could have invalid user name and password, it should fail client creation. I am happy to add more comments to reduce the confusion.
3. `AuthEnable` and `AuthDisable` does not need response in the function signature.
@ahrtr @serathius
=> common test: update auth test interface

server/embed/config.go, server/etcdmain/etcd.go
=> fix: add a warning message on startup if the server name is default

tests/framework/e2e/etcdctl.go
Flag is already set in https://github.com/etcd-io/etcd/blob/9bc4a63a419cd316f6920e37ec551b87d1c7c3a7/tests/framework/e2e/etcdctl.go#L317.
Duplicate flag leads to duplicate entries in hashkv output.
=> [e2e] don't pass --endpoints flag in test HashKV implementation

tests/common/alarm_test.go, tests/common/compact_test.go, tests/common/defrag_test.go, tests/common/endpoint_test.go, tests/common/kv_test.go, tests/common/main_test.go, tests/common/role_test.go, tests/common/wait_leader_test.go, tests/framework/config/cluster.go
As mentioned in [#14629](https://github.com/etcd-io/etcd/pull/14629#discussion_r1005582285), the code could be more concise with these changes.
From my understanding, `3` was used as the default value of `clusterSize`.
@ahrtr please have a look, thanks!
=> tests: add a ClusterOption interface for ClusterSize in config.Cluster

server/auth/range_perm_cache.go, server/auth/store.go, tests/e2e/ctl_v3_auth_cluster_test.go, tests/framework/e2e/cluster.go, tests/framework/e2e/etcdctl.go
When new node joins the cluster and applies snapshot - auth cache is not updated.
On auth-enabled cluster it leads to all requests with "user doesn't exist".
It also leads to data inconsistencies in the cluster since updates can't be applied from raft log.
See discussion in https://github.com/etcd-io/etcd/issues/14571.
Fixes: https://github.com/etcd-io/etcd/issues/14571
=> etcdserver: call refreshRangePermCache on Recover() in AuthStore.

.github/workflows/govuln.yaml
- add job for govuln job
- allow to continue on failure, until all issues are addressed
- address: https://github.com/etcd-io/etcd/issues/14449
=> .github: add govuln check

.github/workflows/scorecards.yml
Closes #14636 
I've upgraded the version of Scorecard Github Action from 2.0.3 to 2.0.6.
Here is a test I've made. The [older action](https://github.com/joycebrum/etcd/actions/runs/3305719746) was with the same error. The [latest action](https://github.com/joycebrum/etcd/actions/runs/3348212136) ran with Scorecard Github Action 2.0.6 and with success.
=> Fix error on Scorecard run by upgrading the action version

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
Since I'm backporting #14308 from 3.6 to 3.5, I need to move the changelog line to 3.5
=> Update 3.4, 3.5, and 3.6 changelogs for adding configurable cipher list to gRPC proxy

server/auth/store_test.go
This is a corrective action for https://github.com/etcd-io/etcd/issues/14571 Since introducing the change of https://github.com/etcd-io/etcd/pull/13954 `authStore.rangePermCache` needs to be updated immediately after changing auth configuration or recovery from Raft logs or snapshot (prior to the change, `rangePermCache` just needs to be updated during data access). However, the unit test cases don't cover the behavior for `authStore.Recover()`. Although below test cases cover similar scenario, it wasn't enough for testing the new behavior:
- [TestReocver()](https://github.com/etcd-io/etcd/blob/main/server/auth/store_test.go#L167): it tests `authStore.Recover()` but just focusing on …
=> server: add a unit test case for authStore.Reocver() with empty rangePermCache

auth/store.go, auth/store_test.go
This PR backports https://github.com/etcd-io/etcd/pull/14647 to release-3.4
cc @ahrtr
=> [3.4] server: add a unit test case for authStore.Reocver() with empty rangePermCache

server/auth/store.go, server/auth/store_test.go
This PR backports https://github.com/etcd-io/etcd/pull/14647 to `release-3.5`
cc @ahrtr 
=> [3.5] server: refresh auth info when etcd recovers from a snapshot

tests/e2e/ctl_v3_auth_test.go, tests/e2e/ctl_v3_test.go
=> test: added e2e test case for issue 14571: etcd doesn't load auth info when recovering from a snapshot

client/v3/experimental/recipes/double_barrier.go, tests/integration/clientv3/experimental/recipes/v3_double_barrier_test.go
Fix https://github.com/etcd-io/etcd/issues/14603
Check the waiter count before creating the ephemeral key, do not create the key if there are already too many clients. Check the count after creating the key again, if the total kvs is bigger than the expected count, then check the rev of the current key, and take action accordingly based on its rev. If its rev is in the first ${count}, then it's valid client, otherwise, it should fail.
=> clientv3: fix the implementation of double barrier

tests/common/alarm_test.go, tests/common/compact_test.go, tests/common/defrag_test.go, tests/common/endpoint_test.go, tests/common/kv_test.go, tests/common/lease_test.go, tests/common/member_test.go, tests/common/role_test.go, tests/common/status_test.go, tests/common/txn_test.go, tests/common/user_test.go, tests/common/wait_leader_test.go, tests/common/watch_test.go, tests/framework/config/cluster.go, tests/framework/e2e.go, tests/framework/integration.go, tests/framework/interface.go, tests/framework/unit.go
As mentioned in https://github.com/etcd-io/etcd/pull/14632#pullrequestreview-1158400017 @serathius, `TestRunner.NewCluster` method now accepts options.
This implementation avoids adding a new method to `TestRunner` interface. The downside is that
```
clus := testRunner.NewCluster(ctx, t, tc.config)
```
becomes more verbose as shown below:
```
clus := testRunner.NewCluster(ctx, t, config.WithClusterConfig(tc.config))
```
=> tests: TestRunner.NewCluster accepts options

server/storage/mvcc/kvstore_txn.go
Adding more context to the panic log message for https://github.com/etcd-io/etcd/issues/14211 .
Our goal is to capture enough information that will allow us to reproduce the issue when it happens again.
=> server: add more context to panic message

.github/workflows/build.yaml, .github/workflows/contrib.yaml, .github/workflows/coverage.yaml, .github/workflows/e2e.yaml, .github/workflows/functional.yaml, .github/workflows/fuzzing.yaml, .github/workflows/govuln.yaml, .github/workflows/grpcproxy.yaml, .github/workflows/linearizability.yaml, .github/workflows/release.yaml, .github/workflows/static-analysis.yaml, .github/workflows/tests.yaml, tests/functional/Dockerfile, tests/manual/Makefile
```
govulncheck is an experimental tool. Share feedback at https://go.dev/s/govulncheck-feedback.
Scanning for dependencies with known vulnerabilities...
Found 1 known vulnerability.
Vulnerability #1: GO-2022-1095
Due to unsanitized NUL values, attackers may be able to
maliciously set environment variables on Windows. In
syscall.StartProcess and os/exec.Cmd, invalid environment
variable values containing NUL values are not properly checked
for. A malicious environment variable value can exploit this
behavior to set a value for a different environment variable.
For example, the environment variable string "A=B\x00C=D" sets
the variables "A=B" and "C=D".
Call stacks in your code:
tools/etcd-dump-logs/main.go:340:18: go.etcd.io/etcd/v3/tools/etcd-dump-logs.listEntriesType calls …
```
=> bump go version to 1.19.3 to address security fixes

client/v3/experimental/recipes/double_barrier.go, tests/integration/clientv3/experimental/recipes/v3_double_barrier_test.go
Cherry-pick https://github.com/etcd-io/etcd/pull/14604 to 3.5
cc @mitake @ptabor @spzala @serathius
=> [3.5] clientv3: fix the implementation of double barrier

tests/e2e/cluster_downgrade_test.go, tests/framework/e2e/util.go
In the TestDowngradeUpgradeCluster case, the brand-new cluster is using simple-config-changer, which means that entries has been committed before leader election and these entries will be applied when etcdserver starts to receive apply-requests. The simple-config-changer will mark the `confState` dirty and the storage backend precommit hook will update the `confState`.
For the new cluster, the storage version is nil at the beginning. And it will be v3.5 if the `confState` record has been committed. And it will be >v3.5 if the `storageVersion` record has been committed.
When the new cluster is ready, the leader will set init cluster version with v3.6.x. And then it will trigger the `monitorStorageVersion` to update the `storageVersion` to v3.6.x. If the `confState` record has been updated …
=> test: deflake TestDowngradeUpgradeClusterOf3 timeout

tests/framework/e2e/util.go
Should really clean up e2e test logs and make tests much more repeatable.
cc @ahrtr @spzala
=> tests: Pass only etcd related environment variables during e2e tests

etcdctl/ctlv3/command/del_command.go
Fixes https://github.com/etcd-io/etcd/issues/13705
Base PR: https://github.com/etcd-io/etcd/pull/13729 
Change commit branch from main to release-3.5
=> add warning message when delete to release-3.5

client/v3/maintenance.go, etcdctl/ctlv3/command/defrag_command.go, etcdctl/ctlv3/command/ep_command.go, server/etcdserver/api/v3rpc/auth.go, server/etcdserver/api/v3rpc/maintenance.go, tests/common/auth_util.go, tests/common/maintenance_auth_test.go
When auth is enabled, etcd doesn't check permission for some important operations, such as downgrade, move-leader... at all.  The existing behavior isn't consistent, we check admin permission for some operations (e.g. HashKV, snapshot, defragment), but not for others. I think only admin (users with `root` role) can perform such operations. 
I think the following operations require admin permission,
1. all maintenance operations;
2. all lease operations;
The only exception is `memberList` operation, there is no check on this API at all. Should we require admin permission to perform `MemberList` operation? 
cc @mitake @ptabor  @spzala @serathius 
=> auth: check permission when performing maintainenence operations if auth is enabled

CHANGELOG/CHANGELOG-3.6.md
Related PR: https://github.com/etcd-io/etcd/pull/14663
cc @mitake
=> changelog: add item to cover the fix on adding protection on maintenance requests when auth is enabled

client/v3/client.go, client/v3/client_test.go
fix clientv3 init client error
close #14323
Signed-off-by: happlins [happlins@foxmail.com](mailto:happlins@foxmail.com)
=> clientv3: fix init client error

CHANGELOG/CHANGELOG-3.5.md
cc @mitake @ptabor @spzala @serathius
=> changelog: add item to cover the fix for double barrier running into stack overflow

raft/raft.go, raft/raftpb/confchange.go
This commit simplifies the logic added in 37c7e4d to auto-leave joint configurations. It does so by making the following adjustments to the code:
- remove the `oldApplied <= r.pendingConfIndex` condition. This does not seem necessary. When a node first attempts to auto-leave a joint config, it will bump `r.pendingConfIndex` when proposing. In cases where `oldApplied >= r.pendingConfIndex`, the proposal must have already been applied. Reviewers should double check this.
- use raft.Step instead of custom proposal code. This code was already present in stepLeader, so there was no reason to duplicate it. This would have avoided bugs like the one we fixed in #14538.
- use `confChangeToMsg` to generate message, to centralize the creation of all `MsgProp{EntryConfChange}` messages.
cc. @tbg …
=> raft: simplify auto-leave joint config on entry application logic

raft/raft.go
=> raft: change the log from debug to warning when uncommitted size exceeds threshold

tests/linearizability/failpoints.go, tests/linearizability/linearizability_test.go
=> tests: Add triggering random go failpoints to linearizability tests

raft/raft.go, raft/raft_flow_control_test.go, raft/raft_snap_test.go, raft/raft_test.go, raft/rafttest/interaction_env.go, raft/rafttest/interaction_env_handler_add_nodes.go, raft/testdata/replicate_pause.txt, raft/tracker/inflights.go, raft/tracker/inflights_test.go, raft/tracker/progress.go, raft/tracker/progress_test.go
When Inflights to a particular node is full, i.e. MaxInflightMsgs for the append messages flow is saturated, it is still necessary to continue sending MsgApp to ensure progress. Currently this is achieved by "forgetting" the first in-flight message in the window, which frees up quota for one new MsgApp.
This new message is constructed in such a way that it potentially has multiple entries, or a large entry. The effect of this is that the in-flight limitations can be exceeded arbitrarily, for as long as the flow to this node continues being saturated. In particular, if a follower is stuck, the leader will keep sending entries to it.
This commit makes the MsgApp empty when Inflights is saturated, and prevents the described leakage of Entries to slow followers.
Signed-off-by: Pavel …
=> raft: send empty appends when replication is paused

tests/e2e/ctl_v3_auth_cluster_test.go, tests/e2e/etcd_grpcproxy_test.go, tests/e2e/etcd_mix_versions_test.go, tests/framework/e2e/cluster.go
cc  @mitake @ptabor @serathius @spzala
=> test: support mix versions sending snapshot test

raft/go.mod, raft/go.sum, raft/tracker/inflights_test.go, raft/tracker/progress_test.go
This commit removes the verbose comparisons in tests, in favor of using assert/require helpers from the testify packages.
Part of #14709
Signed-off-by: Pavel Kalinnikov <pavel@cockroachlabs.com>
=> raft/tracker: use testify packages in tests

tests/linearizability/linearizability_test.go
=> tests: Preserve data dir from failed linearizability tests

tests/e2e/utl_migrate_test.go, tests/e2e/v2store_deprecation_test.go, tests/framework/e2e/cluster.go
When e2e test cases specify the DataDirPath, we need to create a subdirectory for each member, otherwise all members share the same directory and accordingly lead to conflict.
=> test: Create a subdirectory for each member when DataDirPath is specified

raft/log_unstable.go
No change in behavior, but clarify interaction with unstable snapshot.
Extracted from https://github.com/etcd-io/etcd/pull/14627. cc. @tbg
=> raft: clarify conditions in unstable.stableTo

raft/node.go, raft/node_test.go, raft/rawnode.go
The function was unused beyond its own unit test. Delete it.
Extracted from https://github.com/etcd-io/etcd/pull/14627. cc. @tbg
=> raft: delete unused Ready.containsUpdates method

raft/log.go, raft/log_test.go, raft/node.go, raft/node_test.go, raft/raft_paper_test.go, raft/rawnode.go, raft/rawnode_test.go
Also rename `hasNextEnts` to `hasNextCommittedEnts`.
Also rename `maxNextEntsSize` to `maxNextCommittedEntsSize`.
Extracted from #14627. cc. @tbg 
Pure refactor.
=> raft: rename raftLog.nextEnts to raftLog.nextCommittedEnts

tests/e2e/cluster_downgrade_test.go, tests/e2e/corrupt_test.go, tests/e2e/ctl_v3_auth_cluster_test.go, tests/e2e/ctl_v3_kv_test.go, tests/e2e/ctl_v3_snapshot_test.go, tests/e2e/utl_migrate_test.go, tests/framework/e2e/cluster.go
Context #14711
This PR focuses on 2nd step: replaces 1/3(the rest is on the way) initialisations with `DefaultConfig`, `NewConfig` and `EPClusterOption`.
=> tests: refactor `EtcdProcessClusterConfig` using Functional Options Pattern

README.md
Tobias Grieger is actively working on etcd/raft (thanks @tbg ), and has already been added back as a raft maintainer, so no reason to keep him in the Emeritus Maintainers list.
cc @tbg
=> README: remove Tobias Grieger from the Emeritus Maintainers list

server/storage/backend/batch_tx.go
Fix the issue discovered in https://github.com/etcd-io/etcd/pull/14685
`unsafeCommit` is called by both `(*batchTxBuffered) commit` and `(*backend) defrag`. When users perform the defragmentation operation, etcd doesn't update the consistent index, because `unsafeCommit` doesn't call the `OnPreCommitUnsafe`. If etcd crashes(e.g. panicking) in the process for whatever reason, when etcd starts again it replays the WAL entries starting from the latest snapshot, accordingly it may re-apply entries which might have already been applied, eventually the revision isn't consistent with other members.
Refer to discussion in [pull/14685](https://github.com/etcd-io/etcd/pull/14685), especially the comment https://github.com/etcd-io/etcd/pull/14685#issuecomment-1310999115.
Signed-off-by: Benjamin Wang …
=> etcdserver: call the OnPreCommitUnsafe in unsafeCommit

.github/workflows/e2e.yaml
Local test result:
```
'build' completed at Sun Nov 13 05:22:08 PM HKT 2022
'release' started at Sun Nov 13 05:22:08 PM HKT 2022
Downloading etcd-v3.5.5-linux-amd64.tar.gz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 18.5M  100 18.5M    0     0  5453k      0  0:00:03  0:00:03 --:--:-- 9325k
etcd-v3.5.5-linux-amd64/etcdutl
etcd-v3.5.5-linux-amd64/Documentation/
etcd-v3.5.5-linux-amd64/Documentation/dev-guide/
etcd-v3.5.5-linux-amd64/Documentation/dev-guide/apispec/ …
```
=> e2e: test DowngradeVersion with latest point release

server/mvcc/backend/batch_tx.go
Backport https://github.com/etcd-io/etcd/pull/14730 to 3.5.
`unsafeCommit` is called by both `(*batchTxBuffered) commit` and `(*backend) defrag`. When users perform the defragmentation operation, etcd doesn't update the consistent index. If etcd crashes(e.g. panicking) in the process for whatever reason, then etcd replays the WAL entries starting from the latest snapshot, accordingly it may re-apply entries which might have already been applied, eventually the revision isn't consistent with other members.
Refer to discussion in https://github.com/etcd-io/etcd/pull/14685
=> [3.5] etcdserver: call the OnPreCommitUnsafe in unsafeCommit

CHANGELOG/CHANGELOG-3.6.md, raft/confchange/confchange.go, raft/confchange/datadriven_test.go, raft/confchange/quick_test.go, raft/confchange/restore_test.go, raft/raft.go, raft/raft_test.go, raft/tracker/inflights.go, raft/tracker/inflights_test.go, raft/tracker/progress.go, raft/tracker/progress_test.go, raft/tracker/tracker.go
Raft flow control limits the message size and the number of inflight messages. However, a single large entry that exceeds the size limit can still be sent. In combination with the max messages count limit, many large messages can be sent in a row and overflow the receiver. In effect, the "max" size value acts as "target" which can be missed.
This PR adds an additional soft limit on the total size of inflight messages, which catches such situations and prevents the receiver overflow.
=> raft: add MaxInflightBytes limit to the outgoing messages flow

pkg/expect/expect.go, pkg/expect/expect_test.go, tests/common/txn_test.go, tests/e2e/ctl_v3_auth_test.go, tests/e2e/ctl_v3_elect_test.go, tests/e2e/ctl_v3_kv_test.go, tests/e2e/ctl_v3_lock_test.go, tests/e2e/ctl_v3_move_leader_test.go, tests/e2e/ctl_v3_snapshot_test.go, tests/e2e/ctl_v3_test.go, tests/e2e/ctl_v3_txn_test.go, tests/e2e/etcd_config_test.go, tests/e2e/gateway_test.go, tests/e2e/no_quorum_ready_test.go, tests/e2e/utl_migrate_test.go, tests/e2e/v3_cipher_suite_test.go, tests/e2e/v3_curl_maxstream_test.go, tests/e2e/v3_curl_test.go, tests/framework/e2e/cluster.go, tests/framework/e2e/curl.go, tests/framework/e2e/etcd_process.go, tests/framework/e2e/util.go, tests/linearizability/failpoints.go
ExpectProcess and ExpectFunc now take the exit code of the process into account, not just the matching of the tty output.
I'm still fixing some of the tests that are now failing due to this.
=> Expect exit code enhancement

tests/e2e/ctl_v3_completion_test.go
The etcdctl and etcdutl built with `-tags cov` mode will show go-test result
after each execution, like
```
...
PASS
coverage: 0.0% of statements in ./...
```
Since the PASS is not real command, the `source completion` command will
fail with command-not-found error. And there is no easy way to disable
the (*testing.M).Run's output. Therefore, this patch uses build tag !cov
to disable cases when enable coverage.
Fixes: #14694
=> tests/e2e: disable testShellCompletion if enable cov flag

tests/linearizability/client.go, tests/linearizability/model.go, tests/linearizability/model_test.go
=> Revision inconsistency caused by panic during defrag

raft/raftpb/raft.proto, raft/util.go, raft/util_test.go
Use array indexing to clean up the code and make it constant time.
Also, add a test for `IsResponseMsg`.
cc. @tbg 
=> raft: clean up IsLocalMsg and IsResponseMsg logic

raft/log.go, raft/log_test.go
This commit removes the ability to apply log entries at the same time as applying a snapshot. Doing so it possible, but it leads to complex code and raises questions about what should be applied first. It also raises additional complexity when we start allowing concurrent, asynchronous log appends and log application. It's easiest to just disallow this.
Extracted from https://github.com/etcd-io/etcd/pull/14627.
cc. @tbg
=> raft: don't apply entries when applying snapshot

raft/log_test.go
=> feat: raft/log_test se testify packages in tests

client/v3/client.go
Deprecated: use WithTransportCredentials and insecure.NewCredentials() instead. Will be supported throughout 1.x.
Signed-off-by: Ramil Mirhasanov <ramil600@yahoo.com>
=> client/v3: replace deprecated grpc.WithInsecure()  issue #14732

tests/e2e/cluster_downgrade_test.go, tests/e2e/corrupt_test.go, tests/e2e/ctl_v3_auth_cluster_test.go, tests/e2e/ctl_v3_grpc_test.go, tests/e2e/ctl_v3_make_mirror_test.go, tests/e2e/ctl_v3_move_leader_test.go, tests/e2e/ctl_v3_snapshot_test.go, tests/e2e/ctl_v3_test.go, tests/e2e/discovery_test.go, tests/e2e/discovery_v3_test.go, tests/e2e/etcd_grpcproxy_test.go, tests/e2e/etcd_mix_versions_test.go, tests/e2e/etcd_release_upgrade_test.go, tests/e2e/gateway_test.go, tests/e2e/utl_migrate_test.go, tests/e2e/v2store_deprecation_test.go, tests/e2e/v3_curl_maxstream_test.go, tests/e2e/zap_logging_test.go, tests/framework/e2e/cluster.go, tests/framework/e2e/e2e.go, tests/linearizability/linearizability_test.go
Context https://github.com/etcd-io/etcd/pull/14711
This PR finished 2nd step: replaces all initialisations of `EtcdProcessClusterConfig` with DefaultConfig, NewConfig and EPClusterOption.
=> tests: refactor EtcdProcessClusterConfig using Functional Options Pattern

CHANGELOG/CHANGELOG-3.4.md, client/v3/config.go
The correct param forMaxCallRecvMsgSize is '--max-recv-bytes' instead of '--max-request-bytes', so I fixed the documentation and description.
=> docs: fix max recv msg size description

tests/e2e/cluster_downgrade_test.go, tests/e2e/corrupt_test.go, tests/e2e/ctl_v3_auth_no_proxy_test.go, tests/e2e/ctl_v3_grpc_test.go, tests/e2e/ctl_v3_kv_test.go, tests/e2e/ctl_v3_move_leader_test.go, tests/e2e/ctl_v3_test.go, tests/e2e/discovery_v3_test.go, tests/e2e/etcd_grpcproxy_test.go, tests/e2e/v2store_deprecation_test.go, tests/e2e/v3_curl_test.go, tests/framework/e2e/cluster.go, tests/framework/e2e/cluster_proxy.go, tests/framework/e2e/curl.go, tests/framework/e2e/e2e.go, tests/framework/e2e/etcd_process.go, tests/framework/e2e/etcdctl.go, tests/linearizability/failpoints.go, tests/linearizability/linearizability_test.go
Part of https://github.com/etcd-io/etcd/issues/14726
cc @ahrtr
=> Linearizability raft before leader send

tools/mod/go.mod, tools/mod/go.sum
=> tool: bump gofail version

scripts/build-binary.sh, scripts/build_lib.sh, tests/functional/build.sh
This changes the builds to always add -trimpath which removes specific build time paths from the binary (like current directories etc).
Improves build reproducability to make the final binary independent from the specific build path.
Lastly, when stripping debug symbols, also add -w to strip DWARF symbols as well which aren't needed in that case either.
Found this when doing #13545 and thought that maybe these additional changes would also be welcome.
=> release: build with consistent paths

build.sh, scripts/build-binary, tests/functional/build
Trimming GOPATH etcd binary for next release.
Backports https://github.com/etcd-io/etcd/pull/13552
=> [3.5] trim build path

raft/log_unstable_test.go
=> feat: raft/log_unstable_test use testify packages in tests

CHANGELOG/CHANGELOG-3.5.md
=> Update changelog for v3.5.6 release

client/v3/concurrency/key.go
I am not totally sure if I am correct but I think [here](https://github.com/etcd-io/etcd/blob/main/client/v3/concurrency/key.go#L48-L49), we should mention:
> waitDeletes efficiently waits until all keys matching the prefix and no greater than the create revision **_are deleted_**
Instead of just:
> waitDeletes efficiently waits until all keys matching the prefix and no greater than the create revision.
I tried to verify this with [the PR](https://github.com/etcd-io/etcd/pull/7444/files) related to the above change (found using git blame)
=> client: update comment for clarity

tests/integration/corrupt_test.go
If the corrupted member has been elected as leader, the memberID in alert response won't be the corrupted one. It will be a smaller follower ID since the raftCluster.Members always sorts by ID. We should check the leader ID and decide to use which memberID.
Fixes: #14823
=> tests/integration: deflake Corruption cases

tests/e2e/ctl_v3_test.go, tests/framework/e2e/cluster.go, tests/framework/e2e/curl.go, tests/framework/e2e/e2e.go
Context #14711 
Rename anti-pattern-naming fields(DisableStrictReconfigCheck and NoCN) and move them to DefaultConfig.
=> tests: fix anti-pattern name in `NewEtcdProcessCluster`

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
Related issue: https://github.com/etcd-io/etcd/issues/14849
PRs:
- 3.5: https://github.com/etcd-io/etcd/pull/14852
- 3.4: https://github.com/etcd-io/etcd/pull/14853
=> changelog: add items for both 3.4 and 3.5 changelog to cover the case of removing memberid from corrupt alarm

scripts/test_lib.sh, server/etcdserver/corrupt.go, server/etcdserver/corrupt_test.go, tests/e2e/corrupt_test.go, tests/integration/corrupt_test.go
Fix https://github.com/etcd-io/etcd/issues/14849
=> [3.5] etcdserver: intentionally set the memberID as 0 in corruption alarm

client/pkg/transport/timeout_dialer_test.go, client/pkg/transport/timeout_listener_test.go
There is data race on `stop` channel. After verify write-timeout successfully, the case won't wait for `blocker` to receive close signal from `stop` channel. If the new `blocker`, which is to read-timeout verifier, get dial's result immediately, the new `blocker` might fetch the message from `stop` channel before old one and then close the connection, which causes that the `conn.Read` returns `EOF` when it reads data.
How to reproduce this in linux devbox?
Use `taskset` to limit the test process in one-cpu.
```bash
cd ./client/pkg/transport
go test -c -o /tmp/test --race=true ./
taskset -c 0 /tmp/test -test.run TestWriteReadTimeoutListener -test.v -test.cpu 4 -test.count=10000 -test.failfast
```
To fix this, suggest to use seperate `stop` channel to prevent from data race.
Signed-off-by: …
=> Deflake transport timeout case

client/pkg/types/id.go, server/etcdserver/corrupt.go, server/etcdserver/corrupt_test.go, tests/integration/corrupt_test.go
Currently when the compact hash checker detects hash mismatch, it assumes that the corrupted member is always one of the followers. This isn't correct, because it's also possible that it's the leader's data corrupted. It's also possible that there are multiple members corrupted, for example 2 members out of a 5 member cluster.
The solution is to depend on quorum to identify the corrupted member. For example, for a 3 member cluster, if 2 members have the same compactRevision and hash, then the left one member is the corrupted one. For a 5 member cluster, if at least 3 members have the same CompactRevision and hash, then the left members are the corrupted ones.
If there isn't a quorum, then the least minority are regarded as the corrupted member. For example, for a 5 member cluster, m1 and …
=> Identify corrupted member depending on quorum

server/etcdserver/corrupt_test.go
When two members in a 5 member cluster are corrupted, and they have different hashes, etcd will raise alarm for both members, but the order isn't guaranteed. But if the two corrupted members have the same hash, then the order is guaranteed. The leader always raise alarm in the same order as the member list.
Refer to: https://github.com/etcd-io/etcd/actions/runs/3569072873/jobs/5998638380 
=> test: fix unit test Instability

CONTRIBUTING.md, Makefile
[Issue][1] #14396
1. `make build` will read `GO_BUILD_FLAGS` from env and prepend to go build flags.
2. ~~New make target `verify-go-build-flags-from-env` to runs tests from [build-test.sh][3].~~
3. ~~A test case `default-arch-build-flags-from-env` in [github actions][4] to runs tests from [build-test.sh][3] in pipeline.~~
1. ~~New flag `upload-artifact` and condition to enable/disable upload of result JUnit XML selectively.~~
2. ~~Syntax change of env export as per [this guide][5].~~
~~export JUNIT_REPORT_DIR=$(realpath ${TARGET})~~
~~# Changed to~~
~~echo "JUNIT_REPORT_DIR=$(realpath ${TARGET})" >> $GITHUB_ENV~~
4. A note about the change is added in [CONTRIBUTING.md][7].
`make build` to read build flags from env `GO_BUILD_FLAGS` and prepend to those in [Makefile][2] for building …
=> Read Go Build Flags from env `GO_BUILD_FLAGS` (#14396)

.github/workflows/linearizability.yaml, tests/linearizability/linearizability_test.go
This testing short history makes validating linearizability faster and reduces chances of going into exponential complexity. 
Downside it that repeated runs will override same report files. To avoid that I changed tests to run with failfast so report from last fail is preserved.
Re-run test 5 times confirming that this doesn't increase flakiness.
=> Linearizability recreate cluster

server/etcdserver/quota.go, tests/integration/v3_alarm_test.go
This is a backport of https://github.com/etcd-io/etcd/pull/13435.
The original change had a second commit that modifies a changelog file.
The 3.5 branch does not include any changelog file, so that part was not
cherry-picked.
make build
make test 
both succeeded
=> [3.5] Backport: non mutating requests pass through quotaKVServer when NOSPACE 

CHANGELOG/CHANGELOG-3.5.md
added non mutating requests pass through quotaKVServer when NOSPACE in 3.7
3.5 Backport PR
https://github.com/etcd-io/etcd/pull/14884
=> changelog: added non mutating requests pass through quotaKVServer when NOSPACE in 3.7

tests/linearizability/client.go, tests/linearizability/model.go, tests/linearizability/model_test.go, tests/linearizability/traffic.go
=> linearizability tests - Add support for delete api

server/etcdserver/txn/util.go, server/etcdserver/txn/util_test.go
Fix https://github.com/etcd-io/etcd/issues/14891 
Please see https://github.com/etcd-io/etcd/issues/14891#issuecomment-1337191993
I need to add unit test to verify it.
cc @ptabor @serathius
=> etcdserver: fix nil pointer panic for readonly txn

tests/linearizability/client.go, tests/linearizability/history.go, tests/linearizability/id.go, tests/linearizability/linearizability_test.go, tests/linearizability/model.go, tests/linearizability/model_test.go, tests/linearizability/traffic.go
Based on recommendations in porcupine issues, failed requests should be marked as they failed at the end of test. This allows to stop aggregating errors within model making it:
* Much simpler to implement. Handling all the edge cases turned out to be very hard as we added new methods like delete.
* Much more accurate. Now we can validate revision being continuous as failed request cannot just pop up.
Only downside is history visualization is much less readable.
=> Improve support for failed requests in linearizability tests

etcdserver/util.go, etcdserver/util_test.go
Backporting https://github.com/etcd-io/etcd/pull/14895
Linked to https://github.com/etcd-io/etcd/issues/14891
=> [3.4] etcdserver: fix nil pointer panic for readonly txn

server/etcdserver/util.go, server/etcdserver/util_test.go
Backporting https://github.com/etcd-io/etcd/pull/14895
cc @serathius @ptabor @spzala
=> [3.5] etcdserver: fix nil pointer panic for readonly txn

server/etcdserver/txn/util.go, server/etcdserver/txn/util_test.go
The pb provides an accessor method to get field and it will not panic if
the owner is nil. And add non-empty RangeRespone into the test case.
ping @ahrtr
=> chore: use Getter in WarnOfExpensiveReadOnlyTxnRequest 

.github/workflows/build.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/contrib.yaml, .github/workflows/coverage.yaml, .github/workflows/e2e.yaml, .github/workflows/functional.yaml, .github/workflows/fuzzing.yaml, .github/workflows/govuln.yaml, .github/workflows/grpcproxy.yaml, .github/workflows/linearizability.yaml, .github/workflows/measure-test-flakiness.yaml, .github/workflows/release.yaml, .github/workflows/static-analysis.yaml, .github/workflows/tests.yaml
Closes #14878 
I've configured and tested all workflows using default permissions as read-only, only the release.yaml and converage.yaml I wasn't able to test. I've assumed, looking to the scripts, that the release.yaml would need a write permission on it's job, the coverage.yaml didn't seem to need any write permission.
Let me know if I've misjudged it.
Thanks!
=> Set Github workflows default permissions to read-only

.github/workflows/linearizability-nightly.yaml
Start with a simple job against main that runs for 3h by repeating it more often than the PR job.
---
fix for #14045 
I didn't find a much better way to make it run for longer, I basically just incremented the --count by two orders of manitude. Let me know if there's a nicer way, happy to implement that.
The caveat with the schedule is that this is only for the main branch, we have to maybe split the jobs up to checkout the respective release branches in parallel and run the tests.
=> Create a nightly job for linearizability tests

security/security-release-process.md
Many of the existing PSC members are now emeritus maintainers. Considering the current state of the project, we may want to keep PSC with the current maintainers. We will list volunteers as we add them.
Signed-off-by: Sahdev Zala <spzala@us.ibm.com>
=> Update PSC members

tests/linearizability/client.go, tests/linearizability/history.go, tests/linearizability/model.go, tests/linearizability/model_test.go, tests/linearizability/traffic.go
cc @ahrtr @ptabor @geetasg @tjungblu
=> tests: Add Txn operation to linearizability tests

.github/workflows/build.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/contrib.yaml, .github/workflows/coverage.yaml, .github/workflows/e2e.yaml, .github/workflows/functional.yaml, .github/workflows/fuzzing.yaml, .github/workflows/govuln.yaml, .github/workflows/grpcproxy.yaml, .github/workflows/linearizability-nightly.yaml, .github/workflows/linearizability.yaml, .github/workflows/measure-test-flakiness.yaml, .github/workflows/release.yaml, .github/workflows/static-analysis.yaml, .github/workflows/tests.yaml
There are lots of Vulnerability alerts in the code scanning result in https://github.com/etcd-io/etcd/security/code-scanning .
Enhanced the existing workflow using [app.stepsecurity.io](https://app.stepsecurity.io/secureworkflow/etcd-io/etcd/tests.yaml/main?enable=pin). 
1. Copy the existing yaml file and paste into the textbox,
2. Click "SECURE WORKFLOW"
3. Copy the manifest from the textbox and paste into etcd repo.
=> Secure the github workflows

.github/workflows/release.yaml, scripts/build-binary.sh, scripts/release.sh, scripts/test_lib.sh
=> Trigger release in current branch for github workflow case

client/v3/watch.go, client/v3/watch_test.go
Resolve the comment https://github.com/kubernetes/kubernetes/pull/114403#discussion_r1045906333 
cc @mitake @spzala
=> client: enhance the function shouldRetryWatch and added unit test

client/v3/naming/resolver/resolver.go
`grpc.resolver.Target.Endpoint` and some other fields are deprecated, URL field is suggested to use instead.
`URL.Path` is required to be stripped of "/" prefix for naming/resolver to work properly
Signed-off-by: Ramil Mirhasanov <ramil600@yahoo.com>
=> resolver: cleanup of deprecated grpc resolver target.Endpoint field

.github/dependabot.yml
FYI. https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#scheduleinterval
cc @ptabor  @serathius @spzala
=> dependabot: change schedule interval to weekly

.github/workflows/trivy-nightly-scan.yaml
This PR will add `trivy-nightly-scan` for etcd images with versions `3.4.22` and `3.5.6` to scan for vulnerabilities everyday at 2AM UTC.
Fixes: #14908
Signed-off-by: ArkaSaha30 <arkasaha30@gmail.com>
=> etcd: add `trivy-nightly-scan` for etcd images

client/v3/watch.go, tests/integration/v3_auth_test.go
In order to fix https://github.com/etcd-io/etcd/issues/12385, PR https://github.com/etcd-io/etcd/pull/14322 introduced a change in which the client side may retry based on the error message returned from server side.
This is not good, as it's too fragile and it's also changed the protocol between client and server. Please see the discussion in https://github.com/kubernetes/kubernetes/pull/114403
Note: The issue https://github.com/etcd-io/etcd/issues/12385 only happens when auth is enabled, and client side reuse the same client to watch.
So we decided to rollback the change on 3.5, reasons: 
1. K8s doesn't enable auth at all. It has no any impact on K8s. 
2. It's very easy for client application to workaround the issue.
The client just needs to create a new client each time before …
=> clientv3: revert the client side change in 14547

CHANGELOG/CHANGELOG-3.5.md
Related PR: https://github.com/etcd-io/etcd/pull/14995
=> changelog: added item to cover the rollback to fix 'auth invalid token and old revision errors in watch'

Documentation/README.md
document: fix doc with syntax error
Change etcdd.io -> etcd.io
Signed-off-by: ZhengSheng0524 <j13tw@yahoo.com.tw>
=> fix doc etcdd.io -> etcd.io

.github/workflows/trivy-nightly-scan.yaml
This PR will add trivy nightly scan for `release-3.5` to scan the latest release version `v3.5.6`.
Fixes: #15003
Signed-off-by: ArkaSaha30 <arkasaha30@gmail.com>
=> Add trivy nightly scan for `release-3.5`

.github/workflows/trivy-nightly-scan.yaml
This PR will add trivy nightly scan for `release-3.4` to scan the latest release version` v3.4.22`.
Fixes: #15003
Signed-off-by: ArkaSaha30 <arkasaha30@gmail.com>
=> Add trivy nightly scan for `release-3.4`

tests/common/auth_test.go, tests/common/auth_util.go, tests/e2e/ctl_v3_auth_test.go
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow. 
Related to https://github.com/etcd-io/etcd/pull/14041
=> tests/common: migrate auth tests #1

.github/workflows/trivy-nightly-scan.yaml
Fixes #15009
Specified the correct branch name for "Trivy Nightly Scan" of the release-3.4 in the workflows.
=> fix: specify the branch name of release-3.4 in the workflow

Dockerfile-release.amd64, Dockerfile-release.arm64, Dockerfile-release.ppc64le, Dockerfile-release.s390x
Command:
```
trivy image --severity CRITICAL gcr.io/etcd-development/etcd:v3.5.6 
```
See report:
=> [3.5] Security: use distroless base image to address critical Vulnerabilities

Dockerfile-release, Dockerfile-release.arm64, Dockerfile-release.ppc64le
Command:
```
trivy image --severity CRITICAL gcr.io/etcd-development/etcd:v3.4.22 
```
Report:
=> [3.4] Security: use distroless base image to address critical Vulnerabilities

server/lease/lessor_test.go
This PR fixes a potential goroutine leak in `TestLessorRenew` and `TestLessorRenewWithCheckpointer`.
In the unlikely event that the test lease expires before `Renew` is called, the call to `Renew` enters the select statement at [server/lease/lessor.go#L412-L424](https://github.com/etcd-io/etcd/blob/main/server/lease/lessor.go#L412-L424) and remains blocked indefinitely. This is reproducible by inserting an appropriate call to `time.Sleep` before the call to `Renew`.
The fix is to move the potentially blocking call to a separate goroutine. If waiting for the call times out, the test fails and the deferred `(*lessor).Stop` method is called which will unblock the call to `Renew`.
=> lease: fix potential goroutine leak in lessor_test.go

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
=> changelog: update items to address the critical and high Vulnerabilities

client/v3/credentials/credentials_test.go
Signed-off-by: wafuwafu13 <mariobaske@i.softbank.jp>
=> test(client): add `credentials_test.go`

client/v3/maintenance.go, client/v3/snapshot/v3_snapshot.go
Unfortunately, golang doesn't have Ternary operator.
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x86443bd]
goroutine 1 [running]:
go.etcd.io/etcd/client/v3.(*maintenance).SnapshotWithVersion(0xa5cd9e0, {0x88d46a0, 0xa467860})
go.etcd.io/etcd/client/v3@v3.6.0-alpha.0/maintenance.go:264 +0x49d
go.etcd.io/etcd/client/v3/snapshot.SaveWithVersion({0x88d46a0, 0xa467860}, 0xa69aa80, {{0xa66dd30, 0x1, 0x1}, 0x0, 0x1a13b8600, 0x77359400, 0x165a0bc00, ...}, ...)
go.etcd.io/etcd/client/v3@v3.6.0-alpha.0/snapshot/v3_snapshot.go:69 +0x42b
go.etcd.io/etcd/etcdctl/v3/ctlv3/command.snapshotSaveCommandFunc(0xa69e000, {0xa5cd340, 0x1, 0x4})
go.etcd.io/etcd/etcdctl/v3/ctlv3/command/snapshot_command.go:66 +0x1ec …
```
=> clientv3: add protection code to prevent SnapshotWithVersion from panicking

Dockerfile-release.amd64, Dockerfile-release.arm64, Dockerfile-release.ppc64le, Dockerfile-release.s390x, nsswitch.conf, scripts/build-docker
Backport https://github.com/etcd-io/etcd/pull/15036 to 3.5
=> 3.5: remove the dependency on busybox

nsswitch.conf
I was thinking the /etc/nsswitch.conf is empty, but actually it isn't empty in `gcr.io/distroless/static-debian11`.
=> Update nsswitch.conf file

.github/workflows/static-analysis.yaml
We are constantly getting this error recently,
```
Run arduino/setup-protoc@64c0c85d18e984422218383b81c52f8b077404d3
with:
version: 3.14.0
include-pre-releases: false
Error: API rate limit exceeded for 40.84.170.113. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)
```
See https://github.com/etcd-io/etcd/actions/runs/3783950658/jobs/6432877430 
=> Added 'secrets.GITHUB_TOKEN' for the static-analysis workflow

tests/linearizability/model.go
=> tests: Refactor etcd model

tests/linearizability/model.go, tests/linearizability/model_test.go, tests/linearizability/traffic.go
=> tests: Support multiple keys in linearizability tests

go.mod, tools/etcd-dump-logs/etcd-dump-log_test.go, tools/etcd-dump-logs/expectedoutput/decoder_correctoutputformat.output, tools/etcd-dump-logs/expectedoutput/decoder_wrongoutputformat.output, tools/etcd-dump-logs/expectedoutput/listAll.output, tools/etcd-dump-logs/expectedoutput/listConfigChange.output, tools/etcd-dump-logs/expectedoutput/listConfigChangeIRRCompaction.output, tools/etcd-dump-logs/expectedoutput/listIRRCompaction.output, tools/etcd-dump-logs/expectedoutput/listIRRDeleteRange.output, tools/etcd-dump-logs/expectedoutput/listIRRLeaseGrant.output, tools/etcd-dump-logs/expectedoutput/listIRRLeaseRevoke.output, tools/etcd-dump-logs/expectedoutput/listIRRPut.output, tools/etcd-dump-logs/expectedoutput/listIRRRange.output, tools/etcd-dump-logs/expectedoutput/listIRRTxn.output, tools/etcd-dump-logs/expectedoutput/listInternalRaftRequest.output, tools/etcd-dump-logs/expectedoutput/listNormal.output, tools/etcd-dump-logs/expectedoutput/listRequest.output
The tests are subtle as they skip if the binary is not generated in the local directory.
$ go build . && go test
PASS
ok      go.etcd.io/etcd/v3/tools/etcd-dump-logs 0.769s
Signed-off-by: Piotr Tabor <ptab@google.com>
=> etcd-dump-logs: Make the tests work again.

.gitignore, server/storage/wal/decoder.go, server/storage/wal/record_test.go, server/storage/wal/repair.go, server/storage/wal/repair_test.go, server/storage/wal/wal.go, server/storage/wal/wal_test.go, server/storage/wal/walpb/record.go, tools/etcd-dump-logs/etcd-dump-log_test.go, tools/etcd-dump-logs/main.go, tools/etcd-dump-logs/raw.go, tools/etcd-dump-logs/raw_test.go
Before this PR diagnosing etcd not running due to crc wal log corruption landed with: 
```
$ go build ./tools/etcd-dump-logs/... && ./etcd-dump-logs ../../Downloads/data
{"level":"warn","msg":"found unexpected non-snap file; skipping","path":"gke-c10ed2ca2a3e4fb8a45f-ffba-8587271_status.txt"}
{"level":"warn","msg":"found unexpected non-snap file; skipping","path":"gke-c10ed2ca2a3e4fb8a45f-ffba-7612155_status.txt"}
Snapshot:
term=32 index=38873895 nodes=[b71f75320dc06a6c] confstate={"voters":[13195394291058371180],"auto_leave":false}
Start dumping log entries from snapshot.
2022/12/23 16:25:28 Failed reading WAL: walpb: crc mismatch
```
So we just now CRC got corrupted ... somewhere... 
With the PR:
```
$ go build ./tools/etcd-dump-logs/... && ./etcd-dump-logs --raw ../../Downloads/data > …
```
=> etcd-dump-logs: Expand to allow diagnosing CRC corrupted problems in WAL log

tests/common/auth_test.go, tests/e2e/ctl_v3_auth_test.go
Signed-off-by: Chao Chen <chaochn@amazon.com>
Related to https://github.com/etcd-io/etcd/pull/14041
=> tests/common: migrate auth tests #2

CHANGELOG/CHANGELOG-3.6.md, server/config/config.go, server/embed/config.go, server/etcdmain/config.go, server/etcdmain/config_test.go, server/etcdmain/help.go, tests/e2e/etcd_config_test.go, tests/framework/e2e/cluster.go
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow. 
Motivation
1. It can benefit one-node cluster with limited resource (e.g memory) without any performance impact. 
2. For multi-node cluster, setting a small value for DefaultSnapshotCatchUpEntries can reduce the memory usage while less tolerant of network events that will cause snapshot transfer (reduced availability).
3. It can benefit the E2E test cases to speed up test time and improve development velocity.
Questions
1. open to discussion if we want to mark this flag as `experimental`.
2. should we set a lower bound limit on the snapshot catchup entries count? 
Related https://github.com/etcd-io/etcd/pull/14819 and https://github.com/etcd-io/etcd/pull/15013#discussion_r1051683699
=> externalize snapshot catchup entries to etcd flag

tests/e2e/ctl_v3_snapshot_test.go, tests/e2e/etcd_grpcproxy_test.go, tests/framework/e2e/cluster.go, tests/framework/e2e/cluster_proxy.go, tests/framework/e2e/curl.go, tests/framework/e2e/etcd_process.go, tests/linearizability/failpoints.go, tests/linearizability/linearizability_test.go
=> tests: Implement network delay and blackholing in linearizability tests

tests/linearizability/linearizability_test.go, tests/linearizability/watch.go
=> Watch events during linearizability test and compare history

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
Linked to https://github.com/etcd-io/etcd/pull/15069
=> changelog: add 3.5 item to cover the fix for last partically synced WAL record

.github/workflows/build.yaml, .github/workflows/contrib.yaml, .github/workflows/coverage.yaml, .github/workflows/e2e.yaml, .github/workflows/functional.yaml, .github/workflows/fuzzing.yaml, .github/workflows/govuln.yaml, .github/workflows/grpcproxy.yaml, .github/workflows/linearizability-nightly.yaml, .github/workflows/linearizability.yaml, .github/workflows/release.yaml, .github/workflows/static-analysis.yaml, .github/workflows/tests.yaml, tests/functional/Dockerfile, tests/manual/Makefile
Signed-off-by: yanggang <gang.yang@daocloud.io>
[release go1.19.5](https://golang.google.cn/doc/devel/release#go1.19)
```
go1.19.5 (released 2023-01-10) includes fixes to the compiler, the linker, and the crypto/x509, net/http, sync/atomic, and syscall packages. See the [Go 1.19.5 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.19.5+label%3ACherryPickApproved) on our issue tracker for details.
```
=> Bump go to 1.19.5

tests/linearizability/client.go, tests/linearizability/history.go, tests/linearizability/lease_ids.go, tests/linearizability/linearizability_test.go, tests/linearizability/model.go, tests/linearizability/model_test.go, tests/linearizability/traffic.go
Signed-off-by: Geeta Gharpure <geetagh@amazon.com>
=> Add support for lease api to linearizability tests

tests/linearizability/history.go, tests/linearizability/linearizability_test.go, tests/linearizability/model.go, tests/linearizability/model_test.go, tests/linearizability/watch.go
=> tests: Use watch events to patch history to speed up linearization

go.mod, go.sum, tests/e2e/v3_curl_test.go
The issue is caused by hand-crafted protobuf message. The runtime.errorBody defines two protobuf fields with same number. We need to upgrade the version to fix it. Otherwise, the client side won't receive any errors from server side because of panic.
```
mismatching field: runtime.errorBody.error, want runtime.errorBody.message
```
It can fix the cases
PASSES="build grpcproxy" CPU=4 RACE=true ./test -run TestV3CurlLeaseRevokeNoTLS
The original error is like:
```
v3_curl_lease_test.go:109: testV3CurlLeaseRevoke: prefix (/v3) endpoint (/kv/lease/revoke): error (read /dev/ptmx: input/output error (expected "etcdserver: requested lease not found", got ["curl: (52) Empty reply from server\r\n"])), wanted etcdserver: requested lease not found
v3_curl_lease_test.go:109: testV3CurlLeaseRevoke: …
```
=> [3.4] grpc-gateway: update version to v1.11.0

CHANGELOG/CHANGELOG-3.4.md
It is used to fix grpc-gateway error handler issue.
=> CHANGELOG: add dep update item to 3.4

tests/linearizability/model.go
Lease support for linearizability tests :  address review feedback
Signed-off-by: Geeta Gharpure <geetagh@amazon.com>
=> Lease support for linearizability tests :  address review feedback

tests/linearizability/history.go, tests/linearizability/linearizability_test.go
Watch event time can be much delayed compared to requests. This created rare issues where last failed request was incorrectly discarded.
=> tests: Fix history patch window

.github/workflows/linearizability-nightly.yaml
Single run takes up to 30s. Let's reduce number of runs to reduce chance of timeout.
cc @ahrtr @tjungblu @ptabor
=> tests: Reduce number of runs in nightly action

client/v3/retry_interceptor.go
Signed-off-by: wafuwafu13 <mariobaske@i.softbank.jp>
recreate https://github.com/etcd-io/etcd/pull/15032.
I'm sorry to have caused you trouble.
=> clientv3: refactor getToken automatically

.github/workflows/linearizability-nightly.yaml, .github/workflows/linearizability-template.yaml, .github/workflows/linearizability.yaml, Makefile
=> Add linearizability nightlies for release 3.4/3.5

server/etcdserver/server.go
This PR should fix the failure in https://github.com/etcd-io/etcd/actions/runs/3908224614/jobs/6678181444 
```
cluster_test.go:259: expecting promote not ready learner to fail, got no error
```
The existing test cases `TestMemberPromote*` in [cluster_test.go](https://github.com/etcd-io/etcd/blob/main/tests/integration/clientv3/cluster_test.go) already covers the code path updated in this PR.
=> etcdserver: return `membership.ErrIDNotFound` when the memberID not found

etcdserver/server.go
Backport https://github.com/etcd-io/etcd/pull/15095 to 3.4.
=> [3.4] etcdserver: return membership.ErrIDNotFound when the memberID not found

etcdctl/ctlv3/command/get_command.go, mvcc/index.go, mvcc/index_test.go, mvcc/kvstore_test.go, mvcc/kvstore_txn.go, tests/e2e/ctl_v3_kv_test.go
Backports
* https://github.com/etcd-io/etcd/pull/11771 (Only including the code change and test)
* https://github.com/etcd-io/etcd/pull/11743
The #11771 's test case needs #11743 change. So I backport two prs in one pr.
-----
Related to https://github.com/etcd-io/etcd/pull/15072
=> [3.4] mvcc: reduce count-only range overhead

.github/workflows/linearizability-nightly.yaml, .github/workflows/linearizability-template.yaml, .github/workflows/linearizability.yaml, tests/linearizability/linearizability_test.go
Decided to use the original approach of reproduction of the issue. I was not able to reliable reproduction via SIGKILL on lower QPS or clients. This approach has downside that validating linerizability for so many clients is too costly.  Memory usage for pourcupine just exploded and would definitely not fit in github action worker. 
Decided to use the initial data inconsistency validation for reproduction.
=> Reproduce issue 13766 in linearizability tests

server/etcdserver/server.go, server/lease/lessor.go, server/storage/mvcc/watchable_store.go
Using time.After will create a new Timer in each cycle, In these cases, it is better to use time.Ticker.
Signed-off-by: Zhao Guo <guozhao-coder@foxmail.com>
=> etcdserver: use time.Ticker instead of time.After

integration/v3_grpc_test.go, mvcc/index.go, mvcc/index_test.go, mvcc/kv_test.go, mvcc/kvstore_test.go, mvcc/kvstore_txn.go
Backports:
* #11990 
* #13060
* And update the UT from #14124
----
Related to #15072
=> [3.4] mvcc: push down RangeOptions.limit argv into index tree to reduce memory overhead

server/storage/mvcc/kvstore_compaction.go, server/storage/mvcc/kvstore_test.go
After setting the ComparionSleepInterval, we can use time.Ticker instead of time.After to optimize the scheduleComparison(), otherwise it will fail in the 'TestStoreCompact(t)' test.
Signed-off-by: guozhao <guozhao@360.cn>
=> test: add CompactionSleepInterval in FakeStore's config

tests/linearizability/client.go, tests/linearizability/linearizability_test.go, tests/linearizability/model/history.go, tests/linearizability/model/model.go, tests/linearizability/model/model_test.go, tests/linearizability/traffic.go
=> tests: Add defragment request to linearizability tests

tests/linearizability/linearizability_test.go, tests/linearizability/model/history.go, tests/linearizability/model/model.go, tests/linearizability/model/model_test.go, tests/linearizability/traffic.go, tests/linearizability/watch.go
Part of https://github.com/etcd-io/etcd/issues/15102
=> tests: Implement LargePut requests

pkg/netutil/netutil.go, pkg/netutil/netutil_test.go
This is a backport of #15153
This formats ipv6 addresses to ensure they can be compared safely
Signed-off-by: kidsan <8798449+Kidsan@users.noreply.github.com>
=> [3.4] Backport: netutil: consistently format ipv6 addresses

server/etcdserver/raft.go
Hi there,
I am trying to learn the source code of etcd. I figure out there is a typo in the comments, and am trying to fix it. I hope this easy commit can be a start of my open source contribution. I understand this might be too easy. I will keep an eye on the good first issues and try to fix them first.
The old name(raftDone) of the channel(notifyc) which indicates the apply has been completed is left unchanged in the comments, resulting in confusion when reading the source code.
Signed-off-by: Jiaming Cao <alan.c.19971111@gmail.com>
=> etcdserver: correct the old name of notifyc in comments

mvcc/backend/backend.go, mvcc/backend/tx_buffer.go
(cherry picked from commit 9c82e8c72b96eec1e7667a0e139a07b944c33b75)
----
Related to #15072
=> [3.4] server: set multiple concurrentReadTx instances share one txReadBuffer.

client/v3/retry_interceptor.go
Signed-off-by: upuplouis <45809347+upuplouis@users.noreply.github.com>
getToken automatically. Otherwise, auth token may be invalid when the token has expired
(see https://github.com/etcd-io/etcd/issues/11954 for more).
=> fix(client):getToken automatically when the token has expired

Makefile, tools/rw-heatmaps/rw-benchmark.sh
The minor change is extracted from https://github.com/etcd-io/etcd/pull/15060. It should can be reviewed and merged separately.
=> tools: fix the CSV format error and add build target 'tools' in Makefile

pkg/netutil/netutil.go, pkg/netutil/netutil_test.go
This formats ipv6 addresses to ensure they can be compared safely
Fixes #15127
=> netutil: consistently format ipv6 addresses

etcdutl/go.mod, etcdutl/go.sum, go.mod, go.sum, server/go.mod, server/go.sum, tests/go.mod, tests/go.sum
=> Bump bbolt to v1.3.7

tests/linearizability/failpoints.go, tests/linearizability/linearizability_test.go, tests/linearizability/watch.go
Main benefit is consistent log header that includes date making it easier to derive when event happend and how long it took.
=> tests: Propagage logger through linearizability tests

client/pkg/tlsutil/versions.go, client/pkg/tlsutil/versions_test.go, client/pkg/transport/listener.go, server/embed/config.go, server/embed/config_test.go, server/embed/etcd.go, server/etcdmain/config.go, server/etcdmain/help.go, tests/e2e/etcd_config_test.go, tests/integration/v3_tls_test.go
This PR adds optional TLS min/max protocol versions fields to `TLSInfo` struct, which is used in both server and client configs. Instead of hardcoding max version to TLSv1.2 it lets Go select the max version. This effectively enables TLSv1.3 support for etcd. The min/max values are also exposed via optional server flags and config file fields so that users can explicitly set the minimum and/or maximum TLS versions, if they want.
It seems that TLSv1.3 was previously supported (prior etcd 3.5) but it got disabled as a workaround to fix a test suite failure which appeared when Go 1.13 release enabled TLSv1.3 by default, see discussion https://github.com/etcd-io/etcd/pull/11110#issuecomment-528617457. In this PR, the failing test case is changed to set the max version to TLSv1.2. This …
=> Add TLSv1.3 support.

tests/linearizability/linearizability_test.go
Skip the peer traffic failpoint.
=> tests/linearizability: remove PeerProxy for ClusterSize=1

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
Linked to https://github.com/etcd-io/etcd/pull/15221
=> changelog: add items to cover the bumping of bbolt to v1.3.7

.github/workflows/e2e-arm64.yaml
Signed-off-by: Kevin Zhao <kevin.zhao@linaro.org>
=> Add E2E tests on arm64

pkg/netutil/netutil.go, pkg/netutil/netutil_test.go
This is a backport of #15153
This formats ipv6 addresses to ensure they can be compared safely
Signed-off-by: kidsan <8798449+Kidsan@users.noreply.github.com>
=> [3.5] Backport: netutil: consistently format ipv6 addresses

tests/framework/e2e/cluster.go, tests/linearizability/linearizability_test.go
When the linearizability test cases run with three members, it might take
7-8s to stop three members, especially stopping the leader. The leader
will transfer the leadership and it might take more time to stop peer
listener.
<details>
<summary>Click to check the log!</summary>
```plain
2023-02-02T08:19:15.2472384Z     logger.go:130: 2023-02-02T08:19:15.245Z	INFO	stopping server...	{"name": "TestLinearizabilityClusterOfSize3LowTraffic-test-2"}
2023-02-02T08:19:15.2473286Z /home/runner/work/etcd/etcd/bin/etcd (TestLinearizabilityClusterOfSize3LowTraffic-test-2) (12503): {"level":"info","ts":"2023-02-02T08:19:15.245Z","caller":"osutil/interrupt_unix.go:65","msg":"received signal; shutting down","signal":"terminated"}
2023-02-02T08:19:15.2474776Z /home/runner/work/etcd/etcd/bin/etcd …
```
=> tests/linearizability: force stop cluster with signal kill

tests/linearizability/failpoints.go, tests/linearizability/linearizability_test.go
fixes https://github.com/etcd-io/etcd/issues/14726, except `raftBeforeFollowerSend`
Signed-off-by: Bogdan Kanivets <bkanivets@apple.com>
=> tests linearizability: trigger snapshot related failpoints

Makefile, server/storage/wal/wal.go
It can be used to reproduce https://github.com/etcd-io/etcd/issues/15247
=> etcdserver: add failpoints walBeforeSync and walAfterSync

build.sh, server/wal/wal.go
Backport https://github.com/etcd-io/etcd/pull/15252 to 3.5
=> [3.5] etcdserver: add failpoints walBeforeSync and walAfterSync

build, wal/wal.go
Backport https://github.com/etcd-io/etcd/pull/15252 to 3.4.
=> [3.4] etctserver: add failpoints walBeforeSync and walAfterSync

tests/linearizability/failpoints.go, tests/linearizability/linearizability_test.go
raftBeforeFollowerSend can only be triggered on Follower and won't work on 1 node cluster. Had to split RandomFailpoint into RandomOneNodeClusterFailpoint and RandomMultiNodeClusterFailpoint
Signed-off-by: Bogdan Kanivets <bkanivets@apple.com>
=> tests: trigger raftBeforeFollowerSend failpoint in linearizability test

client/pkg/logutil/zap.go, tests/e2e/zap_logging_test.go
Historic capnslog timestamps are in microsecond resolution. We need to match that when we migrate to the zap logger.
The standard zap time encoder options are listed here: https://github.com/uber-go/zap/blob/077b03eb1c5f4ed0703209766e4c897bb88ae6fb/zapcore/encoder.go#L171 
Unfortunately none of these completely matched both the precision and format of the historic capnslog format so I've added a custom encoder function that matches exactly.  
Here is a comparison:
| Format | Example |
| ------------- | ------------- |
| Old capnslog  | 2023-02-02 13:50:27.813478 |
| Zap RFC3339NanoTimeEncoder  | 2023-02-03T20:08:58.299954658+13:00  |
| Zap RFC3339TimeEncoder  | 2023-02-03T20:09:52+13:00  |
| Zap EpochMillisTimeEncoder  | 1675408253432.4639  |
| Zap EpochNanosTimeEncoder  | …
=> Adjust time resolution to microseconds

client/pkg/logutil/zap.go, tests/e2e/zap_logging_test.go
This is a backport of https://github.com/etcd-io/etcd/pull/15239.
Historic capnslog timestamps are in microsecond resolution. We need to match that when we migrate to the zap logger.
=> [3.5] Backport adjusting time resolution to microseconds

pkg/logutil/zap.go
This is a backport of https://github.com/etcd-io/etcd/pull/15239.
Historic capnslog timestamps are in microsecond resolution. We need to match that when we migrate to the zap logger.
=> [3.4] Backport adjusting time resolution to microseconds

client/v3/watch.go, tests/integration/v3_watch_test.go
The manual ProgressRequest has issue, it may send inconsistent rev back to client. We should guard the `watchRequest.rev` from decreasing, otherwise, the client may receive duplicate events.
Confirmed that this PR can fix the duplicated event issue.
=> clientv3: correct `nextRev` on receiving progress notification response

client/v3/watch.go, tests/integration/v3_watch_test.go
Backport https://github.com/etcd-io/etcd/pull/15248 to 3.5
=> [3.5] clientv3: correct the nextRev on receving progress notification response

clientv3/watch.go, integration/v3_watch_test.go
Backport https://github.com/etcd-io/etcd/pull/15248 to 3.4
=> [3.4] clientv3: correct the nextRev on receving progress notification response

tests/linearizability/linearizability_test.go, tests/linearizability/watch.go
Fix https://github.com/etcd-io/etcd/issues/15271
Note that there are two revisions:
1. The revision in the response header;
2. The ModRevision in each event.
Note that in each watchResponse, the highest event.ModRevision may be less than the header.Revision. 
Let's work with an example. Assuming the latest header.Revision and (highest) event.ModRevision are both 1000, but the etcdserver is somehow partitioned status, and when it comes back to normal, it syncs the latest logs (e.g. sync a snapshot) from the leader, and it's latest revision may jump to 4000 directly. But the client side still need to receive events starting from 1001. In this case, what the client will receive in the first watchResponse will be something like below,
- watchResponse.Header.Revision: 4000
- First …
=> test: correct the logic of comparing revision in linearizablity/watch.go

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
Linked to https://github.com/etcd-io/etcd/pull/15248
=> changelog: add items for the duplicated events issue

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
Historic capnslog timestamps are in microsecond resolution. We need to match that when we migrate to the zap logger.
3.6:  https://github.com/etcd-io/etcd/pull/15239 (Note one further change incoming for 3.6 zap logging timestamps to migrate to `RFC3339NanoTimeEncoder`)
3.5 Backport: https://github.com/etcd-io/etcd/pull/15240
3.4 Backport: https://github.com/etcd-io/etcd/pull/15241
=> CHANGELOG: Add entries for timestamp resolution fixes.

.github/workflows/e2e-arm64.yaml, .github/workflows/tests-arm64.yaml
Using the tip from [1]. 
[1] https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution#example-only-run-job-for-specific-repository
Signed-off-by: Davanum Srinivas <davanum@gmail.com>
=> Do not run arm64 jobs on forks

tests/linearizability/client.go, tests/linearizability/linearizability_test.go, tests/linearizability/model/history.go
Problem: time.Now() uses wall clock reading. See https://github.com/golang/go/blob/master/src/time/time.go#L17 "later time-telling operations use the wall clock reading, but later time-measuring operations, specifically comparisons and subtractions, use the monotonic clock reading." This can cause 'Return' to be before 'Call' and wrong order of operations from different clients.
Solution: use same base time for all clients and only use 'time-measuring' operations to record timestamps for history.
=> tests: use monotonic clock for linearizability test history

.github/workflows/build.yaml, .github/workflows/contrib.yaml, .github/workflows/coverage.yaml, .github/workflows/e2e-arm64.yaml, .github/workflows/e2e.yaml, .github/workflows/fuzzing.yaml, .github/workflows/govuln.yaml, .github/workflows/grpcproxy.yaml, .github/workflows/linearizability-template.yaml, .github/workflows/release.yaml, .github/workflows/static-analysis.yaml, .github/workflows/tests-arm64.yaml, .github/workflows/tests.yaml, tests/manual/Makefile
Go 1.19.6 (released 2023-02-14) includes important security and bug fixes.
Refer: https://go.dev/doc/devel/release#go1.19 
Fixes: #15327
=> Bump to go 1.19.6

tests/e2e/etcd_mix_versions_test.go, tests/framework/e2e/cluster.go
fix issue #14807
Signed-off-by: WangXiaoxiao <1141195807@qq.com>
=> tests: add mix version for snapshot e2e case

tests/common/auth_test.go, tests/e2e/ctl_v3_auth_test.go
Related to the ask from https://github.com/etcd-io/etcd/pull/14041 to split tests into smaller pieces.
So code review will be reviewer friendly and easier to reason about.
=> migrate auth test to common #4

.github/dependabot.yml
cc @ahrtr @ptabor @spzala 
Current configuration generates a PR per each package, even though all dependencies are also available in root go.mod.
By having dependabot only update root go.mod we will avoid a lot of spam and still be able to get all relevant dependency upgrade suggestions.
=> workflows: Remove non-root gomod dependabot rules

server/etcdserver/api/rafthttp/pipeline.go, server/etcdserver/api/rafthttp/transport.go
The isMsgApp function implements the judgment of the MsgApp message, use the isMsgApp function instead.
=> rafthttp: replace inline code with existing function

tests/integration/clientv3/lease/leasing_test.go
Fixes #15352.
Depending on the goroutine scheduling, the expected count of 8 might not have been reached yet. This ensures the routine won't stop earlier than that.
=> Fixing flaky TestLeasingDeleteRangeContendTxn

.devcontainer/devcontainer.json
When the devcontainer starts it will run `make build` to ensure compiled etcd binaries are immediately available for use.
I've confirmed `make test` is also successfully running unit and integration tests within the container.
Standard etcd ports are forwarded in-case the user wants to interact with the etcd components from outside the container.
This is just an initial proposal and creates a foundation that other contributors can add to moving forward.
Fixes #15377
=> Add initial .devcontainer for go 1.19

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
We recently backported moving to go 1.19.6 to 3.4 and 3.5. This pull request adds `CHANGELOG` entries for these for the next release of both versions.
Relates to issue #15332
Refer backport prs:
- 3.4 #15333 
- 3.5 #15337
=> CHANGELOG: Add entries for 3.4 and 3.5 go version 1.19.

CHANGELOG/CHANGELOG-3.6.md, server/etcdmain/help.go, server/etcdserver/server.go, tests/framework/e2e/cluster.go
The 100k value was justified when storev2 was being dumped completely with every snapshot.  
With storev2 being decommissioned we should consider checkpointing more frequently for faster recovery and to avoid issues with purging wal files.
This pull request aims to generate discussion and hopefully consensus if now is the right time to return to the previous 10,000 snapshot count.
Note: If this pr is accepted I will raise the corresponding one for 3.6 documentation update.
Fixes #15360 
/area performance
=> Return default snapshot count to 10,000

tests/integration/clientv3/lease/leasing_test.go
The TestLeasingDeleteRangeContendTxn is trying to test for RangeDelete when the target resources are being updated.  When the `txnLeasing` wants a server-side transaction, it needs to ensure all the keys mod revision should be leass than what it saw. If the compare fails, it will repeat to apply the server-side transaction until it is sucessful. I believe the test-case is trying to verify how the `txnLeasing` handles the race issue.
Before the patch #15401, the resource-updating goroutine keeps updating until the RangeDelete finishes. The testcase is flaky because two goroutines are sharing one `ctx` and grpc-go client won't wait for the response if `ctx` has been canceled.
For example,
| DelLease Goroutine   | PutLease Goroutine         | ETCD Server                    | Key/0 Status |
| …
=> tests/integration: Update TestLeasingDeleteRangeContendTxn

pkg/schedule/schedule_test.go
Compare the `Finished` with expected value after executing `WaitFinish`. 
Signed-off-by: dbadoy4874 <dbadoy4874@gmail.com>
=> pkg/schedule: correct comparison for FIFO schedule test

.github/workflows/build.yaml, .github/workflows/contrib.yaml, .github/workflows/coverage.yaml, .github/workflows/e2e-arm64.yaml, .github/workflows/e2e.yaml, .github/workflows/fuzzing.yaml, .github/workflows/govuln.yaml, .github/workflows/grpcproxy.yaml, .github/workflows/release.yaml, .github/workflows/robustness-template.yaml, .github/workflows/static-analysis.yaml, .github/workflows/tests-arm64.yaml, .github/workflows/tests.yaml, tests/manual/Makefile
Mitigates CVE-2023-24532, refer: https://groups.google.com/g/golang-dev/c/3wmx8i5WvNY/m/AEOlccrGAwAJ?utm_medium=email&utm_source=footer 
Relates to #15426 
/area security
=> Updated go to latest 1.19.7 release

.github/workflows/e2e.yaml, .github/workflows/functional.yaml, .github/workflows/grpcproxy.yaml, .github/workflows/release.yaml, .github/workflows/tests.yaml, Makefile, api/go.mod, client/pkg/go.mod, client/v2/go.mod, client/v3/go.mod, pkg/go.mod, raft/go.mod, tools/mod/go.mod
Mitigates CVE-2023-24532, refer: https://groups.google.com/g/golang-dev/c/3wmx8i5WvNY/m/AEOlccrGAwAJ?utm_medium=email&utm_source=footer
Relates to https://github.com/etcd-io/etcd/issues/15426
/area security
Note: I somehow missed some nested `go.mod` updates from `1.17` to `1.19` when I previously backported `1.19.6` update so I am tidying up those in this pull request also.
=> [3.5] Backport update to latest go 1.19.7 release

.github/workflows/release.yaml, .github/workflows/tests.yaml, Makefile, functional/scripts/docker-local-agent.sh, functional/scripts/docker-local-tester.sh
Mitigates CVE-2023-24532, refer: https://groups.google.com/g/golang-dev/c/3wmx8i5WvNY/m/AEOlccrGAwAJ?utm_medium=email&utm_source=footer
Relates to https://github.com/etcd-io/etcd/issues/15426
/area security
=>  [3.4] Backport update to latest go 1.19.7 release

CONTRIBUTING.md, README.md
In #15383  we added support for a devcontainer to help new contributors get a development environment running very easily. This pull request proposes adding a small section to our `CONTRIBUTING.md` to explain how to use it.
Relates to #15377
=> Update contributing guide with new codespaces developement option

pkg/stringutil/rand.go, server/embed/serve.go, tests/e2e/watch_delay_test.go
Address step 1 from https://github.com/etcd-io/etcd/issues/15402#issuecomment-1460061395
=> Watch random scheduler

server/embed/serve.go
Dummy fix. Implement wsproxy.Logger with zap.Logger. Use sctx.lg as logger.
=> FIX #13389

tests/e2e/watch_delay_test.go
Fix a format error introduced in https://github.com/etcd-io/etcd/pull/15431. I am curious why we did not see it in the recent couple of PRs.
=> test: fix format error

server/etcdmain/config_test.go
Quick follow on from #15453 to refactor two further references to the old variable names.
cc @ahrtr
=> Refactor: Use proper variable names for urls

embed/serve.go, go.mod, go.sum, pkg/stringutil/rand.go, tests/e2e/cluster_test.go, tests/e2e/watch_delay_test.go
Backporting https://github.com/etcd-io/etcd/pull/15431 to release-3.4
cc @ahrtr @ptabor 
Phase 1 of https://github.com/etcd-io/etcd/issues/15402#issuecomment-1460061395
=> Watch random scheduler 3.4

server/auth/store.go, server/auth/store_test.go
When the etcd cluster is migrated from the old version before 3.5 to the version 3.5+, if user changes the password will trigger a panic bug.
Old etcd version user's option is nil.  I checked the code and found that user.Options.NoPassword is always false. It seems that there is no need to check here, and it is not allowed to set an empty password.
=> server/auth: fix auth panic bug when user changes password

client/pkg/tlsutil/versions.go, client/pkg/tlsutil/versions_test.go, client/pkg/transport/listener.go, server/embed/config.go, server/embed/config_test.go, server/embed/etcd.go, server/etcdmain/config.go, server/etcdmain/help.go, tests/e2e/etcd_config_test.go, tests/integration/v3_tls_test.go
TLS 1.3 support was (re-)added to the main branch in #15156
Organizations running etcd 3.5 are starting to require TLS 1.3 for security compliance.
Fixes #15436
=> [3.5] Backport tls 1.3 support

bill-of-materials.json, tests/e2e/cluster_downgrade_test.go, tests/e2e/cmux_test.go, tests/e2e/metrics_test.go, tests/e2e/utils.go, tests/e2e/v3_cipher_suite_test.go, tests/e2e/v3_curl_maxstream_test.go, tests/e2e/v3_curl_test.go, tests/e2e/watch_delay_test.go, tests/framework/e2e/curl.go, tests/go.mod
Regression testing for https://github.com/etcd-io/etcd/issues/15402
Ensures that all etcd endpoints listed in https://github.com/etcd-io/etcd/issues/15402 are available in every combination of TLS and http version.
=> Test connection multiplexing.

tests/integration/tracing_test.go
`TestTracing` has been failing 4 times in the past 2 months in `test` and `test-arm` branch. 
default randomized election timeout is 1 to 2s, single node will fast-forward 900ms
change the timeout from 1 to 5 seconds to ensure de-flaking this test
cc @fuweid @ahrtr @serathius 
```
logger.go:130: 2023-03-16T02:01:05.478Z	INFO	default.raft	8e9e05c52164694d is starting a new election at term 1
logger.go:130: 2023-03-16T02:01:05.478Z	INFO	default.raft	8e9e05c52164694d became pre-candidate at term 1
logger.go:130: 2023-03-16T02:01:05.478Z	INFO	default.raft	8e9e05c52164694d received MsgPreVoteResp from 8e9e05c52164694d at term 1
logger.go:130: 2023-03-16T02:01:05.478Z	INFO	default.raft	8e9e05c52164694d became candidate at term 2
logger.go:130: 2023-03-16T02:01:05.478Z	INFO	default.raft …
```
=> deflake TestTracing

tests/common/member_test.go, tests/framework/integration/cluster.go
```
logger.go:130: 2023-03-17T21:25:24.870Z	INFO	m2.raft	found conflict at index 5 [existing term: 3, conflicting term: 7]	{"member": "m2"}
logger.go:130: 2023-03-17T21:25:24.871Z	INFO	m2.raft	replace the unstable entries from index 5	{"member": "m2"}
logger.go:130: 2023-03-17T21:25:24.871Z	INFO	m2.raft	raft.node: c9f72a2ce27a2277 elected leader 89e201e60fa5e8e5 at term 7	{"member": "m2"}
logger.go:130: 2023-03-17T21:25:24.871Z	INFO	m0.raft	raft.node: 5bd65997f89ffd02 elected leader 89e201e60fa5e8e5 at term 7	{"member": "m0"}
member_test.go:54: member is not started, memberId:14553147093137629815, memberName:m2
```
Member attributes: `clientURL` is not published due to raft election disruption. 
Enable `PreVote` to `true` will help deflake the integration test and reduce the run time. …
=> deflake member_test: enable pre-vote by default and add retry

bill-of-materials.json, pkg/expect/expect.go, tests/e2e/cluster_test.go, tests/e2e/cmux_test.go, tests/e2e/corrupt_test.go, tests/e2e/etcdctl.go, tests/e2e/util.go, tests/e2e/utils.go, tests/e2e/v2_curl_test.go, tests/e2e/v3_curl_test.go, tests/e2e/watch_delay_test.go, tests/go.mod, tests/integration/cluster.go, tests/integration/cluster_test.go, tests/integration/grpc_test.go, tests/integration/v3_grpc_test.go, tests/integration/v3_tls_test.go
Regression testing for https://github.com/etcd-io/etcd/issues/15402
Ensures that all etcd endpoints listed in https://github.com/etcd-io/etcd/issues/15402 are available in every combination of TLS and http version.
=> Connection multiplexing regression tests for v3.5 

etcdctl/ctlv3/command/txn_command.go
`etcdctl txn --help` is currently not sufficient to be able to use the command without referring to other sources.
We can add a `Long:` description to at least explain what the stdin payload should contain and provide an example of interactive use.
Here is a preview of the proposed help output:
```bash
james  ~  Documents  etcd   txn_help_docs                                                                                                                   11:32:18 
➜ ./bin/etcdctl txn --help
NAME:
txn - Txn processes all the requests in one transaction
USAGE:
etcdctl txn [options] [flags]
DESCRIPTION:
TXN reads multiple etcd requests from standard input and applies them as a single atomic transaction.
A transaction consists of:
1) a list of conditions,
2) a list of requests to …
```
=> Add detailed long description for etcdctl txn

server/embed/serve.go, tests/e2e/cmux_test.go
There are two goroutines accessing the `gs` grpc server var. Before insecure `gs` server start, the `gs` can be changed to secure server and then the client will fail to connect to etcd with insecure request. It is data-race. We should use argument for reference in the new goroutine.
fix: #15495
=> server/embed: fix data race when start insecure grpc

server/storage/mvcc/hash_test.go, server/storage/mvcc/kv_test.go, server/storage/mvcc/kvstore_bench_test.go, server/storage/mvcc/kvstore_compaction_test.go, server/storage/mvcc/kvstore_test.go, server/storage/mvcc/watchable_store_bench_test.go, server/storage/mvcc/watchable_store_test.go, server/storage/mvcc/watcher_bench_test.go, server/storage/mvcc/watcher_test.go
* test: should not leak goroutines after test finished
The original flaky test shows in CI pipeline https://github.com/etcd-io/etcd/actions/runs/4312405975/jobs/7522924734, but gotestsum run into a golang issue https://github.com/gotestyourself/gotestsum/issues/310. The error message is not clear from summary, like
```
{"Time":"2023-03-02T09:19:38.754394861Z","Action":"output","Package":"go.etcd.io/etcd/server/v3/storage/mvcc","Test":"TestHashByRevValue","Output":"      /opt/hostedtoolcache/go/1.19.6/x64/src/testing/testing.go:1433 +0x7e4\n"}
{"Time":"2023-03-02T09:19:38.754414561Z","Action":"output","Package":"go.etcd.io/etcd/server/v3/storage/mvcc","Test":"TestHashByRevValue","Output":"      /opt/hostedtoolcache/go/1.19.6/x64/src/runtime/panic.go:476 +0x32\n"} …
```
=> deflake: mvcc storage ut

server/embed/serve.go, tests/e2e/cmux_test.go
There are two goroutines accessing the `gs` grpc server var. Before insecure `gs` server start, the `gs` can be changed to secure server and then the client will fail to connect to etcd with insecure request. It is data-race. We should use argument for reference in the new goroutine.
fix: #15495
(cherry picked from commit a9988e2625eede1af81d189b5f2ecf7d4af3edf1)
cherry-pick: #15509
=> [3.5] server/embed: fix data race when start insecure grpc

mvcc/watchable_store.go, mvcc/watchable_store_test.go
Backport https://github.com/etcd-io/etcd/pull/15492
=> [v3.4] Fix issue15271

clientv3/watch.go, etcdserver/api/v3rpc/watch.go, integration/cluster.go, integration/v3_auth_test.go
https://github.com/etcd-io/etcd/pull/14322 was backported to release-3.4 in https://github.com/etcd-io/etcd/pull/14548, but it should be reverted too.
cc @ahrtr @serathius
=> [3.4] Revert 14548

embed/serve.go
There are two goroutines accessing the `gs` grpc server var. Before insecure `gs` server start, the `gs` can be changed to secure server and then the client will fail to connect to etcd with insecure request. It is data-race. We should use argument for reference in the new goroutine.
fix: #15495
(cherry picked from commit a9988e2625eede1af81d189b5f2ecf7d4af3edf1)
cherry-pick: #15509
=> [3.4] server/embed: fix data race when start insecure grpc

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
Add item **server/embed: fix data race when starting both secure & insecure gRPC servers on the same address** to 3.4/3.5 changelog.
REF: #15509
=> CHANGELOG: add 'server/embed: fix data race when starting both secure & insecure gRPC servers on the same address' into 3.4/3.5

contrib/mixin/mixin.libsonnet, contrib/mixin/test.yaml
Prometheus rule `etcdDatabaseHighFragmentationRatio` is excessively trigger happy in its current form when the etcd database is small. I think it would be better if the metrics are ignored unless total database size is 100MB+ (or something similar). When the size is small the percentage is large and there isn't a real problem with etcd so this is just creates noise.
Signed-off-by: Göran Gustafsson <gustafsson.g@gmail.com>
=> etcd-mixin: Limit etcdDatabaseHighFragmentationRatio to 100MB+

embed/config.go, embed/config_test.go, embed/etcd.go, etcdmain/config.go, etcdmain/help.go, integration/v3_tls_test.go, pkg/tlsutil/versions.go, pkg/tlsutil/versions_test.go, pkg/transport/listener.go, tests/e2e/etcd_config_test.go
TLS 1.3 support was (re-)added to the main branch in https://github.com/etcd-io/etcd/pull/15156
Organizations running etcd 3.4 are starting to require TLS 1.3 for security compliance.
Fixes https://github.com/etcd-io/etcd/issues/15437
=> [3.4] Backport tls 1.3 support

.github/workflows/release.yaml, scripts/test_images.sh
Please see the previous PR #15350 for details.
Fixes: https://github.com/etcd-io/etcd/issues/15139
@ahrtr @chaochn47
=> scripts: Add testing of etcd in local image in release workflow.

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md, CHANGELOG/CHANGELOG-3.6.md
Update `CHANGELOG-3.4.md` and `CHANGELOG-3.5.md` to reflect recent backports.
Fixes #15436
Fixes #15437
Note:  It appears we didn't have a CHANGELOG entry added for 3.6 for the original feature addition so I have updated that also.
=> CHANGELOG: Add new tls configuration options 

test
Changes invocation from `go test -timeout 30m -v -cpu 1,2,4 '' -v --count 1 go.etcd.io/etcd/tests/e2e` to `go test -timeout 30m -v -cpu 1,2,4 -v --count 1 go.etcd.io/etcd/tests/e2e` (removes ''). Those braces caused tests run in root package instead of e2e.
Logs from a failed run https://github.com/etcd-io/etcd/actions/runs/4533349980/jobs/7986037591:
```
=== RUN   TestMain
main_test.go:32: skip launching etcd server when invoked via go test
--- SKIP: TestMain (0.00s)
=== RUN   TestMain
main_test.go:32: skip launching etcd server when invoked via go test
--- SKIP: TestMain (0.00s)
=== RUN   TestMain
main_test.go:32: skip launching etcd server when invoked via go test
--- SKIP: TestMain (0.00s)
PASS
ok  	go.etcd.io/etcd	0.020s
Error: Process completed with exit code 143.
```
cc @ahrtr …
=> [3.4] tests: Avoid testing package root tests in e2e 

bill-of-materials.json, tests/common/auth_test.go, tests/common/auth_util.go, tests/e2e/ctl_v3_auth_test.go
Related to the ask from https://github.com/etcd-io/etcd/pull/14041 to split tests into smaller pieces.
So code review will be reviewer friendly and easier to reason about.
=> migrate auth tests to common #7

.github/workflows/measure-test-flakiness.yaml, Makefile
The PR is to address the ask from https://github.com/etcd-io/etcd/issues/13167#issuecomment-1474791002. @serathius
The workflow stays running every Sunday midnight. 
Measure-test-flakiness workflow output will additionally show the top contributor of the failed Tests name in Test/Test-arm workflow (only covers integration tests right now) in the past 1 week.
Example output https://github.com/chaochn47/etcd/actions/runs/4546435089/jobs/8015061879
---
Running against E2E workflows does not produce meaningful output, need to investigate more in the tool
```
dev-dsk-chaochn-2c-a26acd76 % bin/etcd-test-analyzer run -token $GITHUB_TOKEN -max-age=168h -workflow E2E -branch main
Fetching workflow runs from GitHub
Analyzing workflow "E2E"
[E2E]: Finding workflow runs
[E2E]: Downloading artifacts …
```
=> add etcd test analyzer build and integrate into measure-test-flakiness workflow

etcd.conf.yml.sample
This pull request proposes to update our `etcd.conf.yml` with an example for setting `cipher-suites`.
This topic has come up in discussions and issues and it appears there has been some confusion about how it should be done, so let's provide a concrete example.
Relates to:
- https://github.com/etcd-io/etcd/discussions/15547
- https://github.com/etcd-io/etcd/discussions/15476
- https://github.com/etcd-io/etcd/issues/12461
- https://github.com/etcd-io/etcd/issues/11587
=> Document defining ciphers in example etcd config file

server/embed/etcd.go
=> server: Fix defer function closure escape

tests/e2e/cluster_test.go, tests/e2e/cmux_test.go, tests/e2e/etcd_spawn_nocov.go, tests/e2e/etcdctl.go, tests/e2e/utils.go, tests/e2e/v2_curl_test.go, tests/e2e/v3_curl_test.go, tests/e2e/watch_delay_test.go
Regression testing for https://github.com/etcd-io/etcd/issues/15402
Ensures that all etcd endpoints listed in https://github.com/etcd-io/etcd/issues/15402 are available in every combination of TLS and http version.
Unfortunately needed to backport a lot of features from e2e test framework.
=> [3.4] Test cmux

scripts/build-docker.sh, scripts/test_images.sh
Fixes: https://github.com/etcd-io/etcd/issues/15266
Signed-off-by: zhangguanzhang <zhangguanzhang@qq.com>
=> Fixes: #15266 All docker images of Architecture show amd64

contrib/raftexample/README.md
Raft library has been moved to https://github.com/etcd-io/raft, raftexample's `raft_library` link is 404, we must change it to the new url.
Changes:
- contrib/raftexample README.
=> contrib/raftexample: fix raftexample README's raft library link.

scripts/build-docker, scripts/test_images.sh
Cherry pick of https://github.com/etcd-io/etcd/pull/15270 on release-3.5.
https://github.com/etcd-io/etcd/pull/15270: Fixes: #15266 All docker images of Architecture show amd64
=> [3.5] Backport fixes all docker images of Architecture show amd64

.github/workflows/e2e.yaml, .github/workflows/functional.yaml, .github/workflows/grpcproxy.yaml, .github/workflows/tests.yaml, build, build.sh, scripts/build-binary, scripts/build-docker, scripts/build-release.sh, scripts/test_lib.sh, test, test.sh, tests/functional/build
cc @serathius @ahrtr 
REF: #15514
=> [3.5] chore: enable strict mode for test CI

tests/framework/e2e/cluster.go, tests/robustness/failpoints.go, tests/robustness/linearizability_test.go
=> Robustness fix blackhole

server/auth/range_perm_cache.go, server/auth/range_perm_cache_test.go, server/auth/store.go, server/auth/store_test.go, tests/integration/v3_auth_test.go
Current `RoleGrantPermission` allows to create permission for ranges like (a, a) or (b, a). These are treated as empty ranges so not harmful. But they are quite confusing and etcd should disallow it.
cc @ahrtr @serathius @spzala @ptabor
=> server/auth: disallow creating empty permission ranges

server/etcdserver/server.go, tests/common/auth_test.go, tests/common/e2e_test.go, tests/common/integration_test.go, tests/common/member_test.go, tests/common/unit_test.go, tests/framework/integration/cluster.go
Before the fix, 
```
taskset -c 1 go test -v -failfast -count 100 -run TestAuthMemberRemove --tags integration
```
can reproduce the error. 
It was reported in the [Mesure Test Flakiness workflow](https://github.com/etcd-io/etcd/actions/runs/4585850341/jobs/8098223054)
=> fix flaking auth member remove test

tests/e2e/watch_delay_test.go
value is selected empirically after spot checking some logs of flaky workflows
fixes: https://github.com/etcd-io/etcd/issues/15634
=> tests: increase maxWatchDelay to prevent flaky TestWatchDelay*

clientv3/snapshot/member_test.go, clientv3/snapshot/v3_snapshot_test.go, embed/config.go, embed/config_test.go, embed/etcd.go, embed/serve.go, etcdmain/config.go, etcdmain/config_test.go, etcdmain/etcd.go, etcdmain/help.go, integration/embed_test.go, tests/e2e/cluster_proxy_test.go, tests/e2e/cluster_test.go, tests/e2e/cmux_test.go, tests/e2e/etcd_process.go, tests/e2e/etcdctl.go, tests/e2e/utils.go, tests/e2e/watch_delay_test.go, tools/etcd-dump-metrics/etcd.go
Backport https://github.com/etcd-io/etcd/pull/15446 and https://github.com/etcd-io/etcd/pull/15588
=> [3.4] Separate grpc server

tests/robustness/linearizability_test.go, tests/robustness/traffic.go
Should help with https://github.com/etcd-io/etcd/issues/15330
=> tests: Ensure that operation history finishes with successful request

auth/range_perm_cache.go, auth/range_perm_cache_test.go, auth/store.go, auth/store_test.go, etcdserver/api/v3rpc/rpctypes/error.go, etcdserver/api/v3rpc/util.go, integration/v3_auth_test.go
This PR backports https://github.com/etcd-io/etcd/pull/15294 to release-3.4. It also backports https://github.com/etcd-io/etcd/pull/13086 which is needed by 15294 and its fix is valuable for 3.4.
cc @ahrtr @serathius @spzala
=> [3.4] backport 15294

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
This PR updates changelog for https://github.com/etcd-io/etcd/pull/15621 and https://github.com/etcd-io/etcd/pull/15619
cc @ahrtr @serathius @spzala
=> changelog: add items to cover 15294

CONTRIBUTING.md, Documentation/contributor-guide/community-membership.md, GOVERNANCE.md
Based on https://github.com/kubernetes/community/blob/master/community-membership.md
Changes:
* Extracted contributor membership to separate file
* Provide more detailed requirements for each role. Base maintainers on kubernetes subproject owners.
* Introduction of member role
cc @ahrtr @ptabor @spzala @mitake
=> Move to community membership model closer to kubernetes one

server/etcdserver/api/v3rpc/watch.go, server/storage/mvcc/watchable_store.go, server/storage/mvcc/watcher.go, server/storage/mvcc/watcher_test.go, tests/integration/v3_watch_test.go, tests/robustness/linearizability_test.go, tests/robustness/traffic.go, tests/robustness/watch.go
Progress notifications requested using `ProgressRequest` were sent directly using the `ctrlStream`, which means that they could race against watch responses in the `watchStream`.
This would especially happen when the stream was not synced - e.g. if you requested a progress notification on a freshly created unsynced watcher, the notification would typically arrive indicating a revision for which not all watch responses had been sent.
This changes the behaviour so that v3rpc always goes through the watch stream, using a new RequestProgressAll function that closely matches the behaviour of the v3rpc code - i.e.
1. Generate a message with WatchId -1, indicating the revision for *all* watchers in the stream
2. Guarantee that a response is (eventually) sent
The latter might require us to defer …
=> etcdserver: Send requested progress notifications through watchStream (fix #15220)

.github/workflows/build.yaml, .github/workflows/contrib.yaml, .github/workflows/coverage.yaml, .github/workflows/e2e-arm64.yaml, .github/workflows/e2e.yaml, .github/workflows/fuzzing.yaml, .github/workflows/govuln.yaml, .github/workflows/grpcproxy.yaml, .github/workflows/release.yaml, .github/workflows/robustness-template.yaml, .github/workflows/static-analysis.yaml, .github/workflows/tests-arm64.yaml, .github/workflows/tests.yaml, tests/manual/Makefile
See https://groups.google.com/g/golang-announce/c/Xdv6JL9ENs8/m/OV40vnafAwAJ
=> security: bump golang to 1.19.8 to fix four CVEs

.github/workflows/e2e.yaml, .github/workflows/functional.yaml, .github/workflows/grpcproxy.yaml, .github/workflows/release.yaml, .github/workflows/tests.yaml, Makefile
Linked to https://github.com/etcd-io/etcd/pull/15649
fix CVE https://groups.google.com/g/golang-announce/c/Xdv6JL9ENs8/m/OV40vnafAwAJ
=> [3.5] bump golang to 1.19.8 to fix four CVEs

server/etcdserver/v3_server.go, tests/e2e/cmux_test.go, tests/e2e/ctl_v3_auth_security_test.go, tests/e2e/ctl_v3_test.go, tests/e2e/utils.go
Fix https://nvd.nist.gov/vuln/detail/CVE-2021-28235
cc @mitake @ptabor @serathius @spzala 
The issue can only happen when all the following conditions are true:
1. The auth is enabled;
2. The log level is set to "`debug`";
3. Clients send authentication request to etcdserver with username & password. Note that clients send authentication request automatically when reading or writing data.
=> security: clear password after authenticating the user

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
=> changelog: Refactor changelog and add changes for v3.5.8

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
1. Bumped golang to 1.19.8;
2. etcdserver: set zap logging to wsproxy;
3. Fix https://nvd.nist.gov/vuln/detail/CVE-2021-28235.
=> changelog: update items to cover the some new changes in 3.5 and 3.4

embed/serve.go
Backport https://github.com/etcd-io/etcd/pull/15447 to 3.4
=> [3.4] etcdserver: set zap logging to wsproxy

server/embed/serve.go
Backport https://github.com/etcd-io/etcd/pull/15447 to 3.5
=> [3.5] etcdserver: set zap logging to wsproxy

server/auth/range_perm_cache.go, server/auth/range_perm_cache_test.go, server/auth/store.go, server/auth/store_test.go, tests/integration/v3_auth_test.go
This PR backports https://github.com/etcd-io/etcd/pull/15294 to release-3.5.
cc @serathius @ahrtr @spzala
=> [3.5] backport 15294

scripts/build-docker.sh, scripts/test_images.sh
Backport fix for docker image arch to 3.4 for inclusion in `v3.4.25`, refer #15680.
Relates to: #15266
=> [3.4] Backport fix for all docker images showing amd64 architecture

client/pkg/fileutil/preallocate.go
`fileutil.Preallocate` function is supported on Darwin yet it is not documented. This fix the issue by updating the docstring.
=> Show darwin as supported in fileutil.Preallocate docstring

client/pkg/fileutil/preallocate.go
The recent pull request https://github.com/etcd-io/etcd/pull/15281 updated a comment for a function but caused a format error due to trailing spaces. 
This is a quick fix to address after running `./scripts/fix.sh`.
Fixes #15692
=> Fix gofmt for client/pkg/fileutil/preallocate.go

README.md
Signed-off-by: guiyong.ou [guiyong.ou@daocloud.io](mailto:guiyong.ou@daocloud.io)
fixed #15671 
=> Fix link for maintainers role and responsibilities in README.md

server/etcdserver/api/v3rpc/watch.go, server/mvcc/watchable_store.go, server/mvcc/watcher.go, server/mvcc/watcher_test.go, tests/integration/v3_watch_test.go
Backport https://github.com/etcd-io/etcd/pull/15237 to 3.5
Link to https://github.com/etcd-io/etcd/issues/15585
=> [3.5] etcdserver: guarantee order of requested progress notifications

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
=> changelog: add items to cover some fixes for 3.5.8 and 3.4.25

server/auth/jwt.go, server/auth/jwt_test.go
This PR is to fix panic on identical JWT token generation and authentication as well as add test cases for the same.
Extension of #15002
Fixes: https://github.com/etcd-io/etcd/issues/14931
=> server/auth: fix panic a malformed jwt generation and add test-cases

server/auth/jwt.go, server/auth/jwt_test.go
Fix https://github.com/etcd-io/etcd/issues/14931.
Linked to https://github.com/etcd-io/etcd/pull/15639
=> [3.5] etcdserver: verify field 'username' and 'revision' present when decoding a JWT token

auth/jwt.go, auth/jwt_test.go
Fix https://github.com/etcd-io/etcd/issues/14931.
Linked to https://github.com/etcd-io/etcd/pull/15639
=> [3.4] etcdserver: verify field 'username' and 'revision' present when decoding a JWT token

tests/framework/e2e/cluster.go, tests/robustness/linearizability_test.go
Fix: https://github.com/etcd-io/etcd/issues/15497
Before:
It is 28.9mins which is close to 30mins timeout
```
% (cd tests && 'env' 'ETCD_VERIFY=all' 'go' 'test' 'go.etcd.io/etcd/tests/v3/common' '--tags=e2e' '-timeout=30m')
ok  	go.etcd.io/etcd/tests/v3/common	1735.430s
```
https://github.com/etcd-io/etcd/actions/runs/4602707842/jobs/8131973032?pr=15580
After:
15mins
```
% (cd tests && 'env' 'ETCD_VERIFY=all' 'go' 'test' 'go.etcd.io/etcd/tests/v3/common' '--tags=e2e' '-timeout=30m')
ok  	go.etcd.io/etcd/tests/v3/common	902.535s
```
~~**Note: this change is meant to optimize 'go.etcd.io/etcd/tests/v3/common' test latency not for all the e2e tests**~~
~~After force stop on 3 node cluster created in `PeerTLS / PeerAutoTLS`~~
~~It is reduced to 19.9mins. ~~
```
% (cd tests && 'env' …
```
=> tests/framwork/e2e/cluster.go: revert back to sequential cluster stop to reduce e2e test run time

scripts/build-binary.sh, scripts/release.sh
The `git_assert_branch_in_sync` doesn't exist in 3.4, so let's just remove it.
The issue was introduced in https://github.com/etcd-io/etcd/commit/49d05f88c31c71a48368bf20927cd8ba61a3bf1a. In our workflow, it always run in `in-place` mode, so it never triggers the branch.
=> [3.4] fix release.sh: git_assert_branch_in_sync not exist in 3.4

.github/ISSUE_TEMPLATE/membership-request.yml, Documentation/contributor-guide/community-membership.md
This pull request proposes adding a new github issue template for nominating new etcd org members. Currently I have only set this up to cater for the base "Member" role as this would be the one happening on the most frequent basis versus adding reviewers or maintainers.
The issue template is partially inspired by the kubernetes github organisation membership template but adjusted to be from the angle of a reviewer or maintainer raising the nomination instead of the member.
The intent of the template is to save a small amount of the creators time and ensure issues automatically have the right labels and follow a consistent approach.
Please let me know what you think of the suggested layout, happy to tweak it!
=> Add issue template for new membership nominations.

tests/framework/integration/cluster.go, tests/framework/testutils/log_observer.go, tests/framework/testutils/log_observer_test.go, tests/integration/v3_watch_restore_test.go
It's followup of #15667 (tests: deflake TestV3WatchRestoreSnapshotUnsync).
This patch is to use zaptest/observer as base to provide a similar
function to pkg/expect.Expect.
The test env
```bash
11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
mkdir /sys/fs/cgroup/etcd-followup-15667
echo 0-2 | tee /sys/fs/cgroup/etcd-followup-15667/cpuset.cpus # three cores
```
Before change:
* memory.peak: ~ 681 MiB
* Elapsed (wall clock) time (h:mm:ss or m:ss): 6:14.04
After change:
* memory.peak: ~ 671 MiB
* Elapsed (wall clock) time (h:mm:ss or m:ss): 6:13.07
Based on the test result, I think it's safe to be enabled by default.
=> tests: make log monitor as common helper (followup #15667

.github/workflows/build.yaml, .github/workflows/contrib.yaml, .github/workflows/coverage.yaml, .github/workflows/e2e-arm64.yaml, .github/workflows/e2e.yaml, .github/workflows/fuzzing.yaml, .github/workflows/go-version.yaml, .github/workflows/govuln.yaml, .github/workflows/grpcproxy.yaml, .github/workflows/release.yaml, .github/workflows/robustness-template.yaml, .github/workflows/static-analysis.yaml, .github/workflows/tests-arm64.yaml, .github/workflows/tests.yaml, scripts/release.sh
Adds a reusable workflow to setup the GoVersion. 
The output of this workflow will be used in the other workflows to reduce maintenance burden for the project  and also increase speed of adoption for new patch releases.
Related to https://github.com/etcd-io/etcd/issues/15674
=> Adds a reusable workflow to setup the GoVersion

server/etcdmain/config.go, server/etcdmain/help.go
Improves the description for --initial-clsuter-state provided in the help. Details of the issue can be found [here](https://github.com/etcd-io/etcd/issues/15743)
=> fixes for "improve description of --initial-cluster-state flag" #15743 

CHANGELOG/README.md
Please read https://groups.google.com/g/etcd-dev/c/8S7u6NqW6C4
=> Change the minimum recommended etcd versions to run in production to 3.4.22+ and 3.5.6+

server/etcdserver/api/v3rpc/maintenance.go
It's to deflake TestAuthMemberRemove.
When the client has multiple endpoints, the client might send a request with valid token to the follower member which hasn't received token replicated log yet. The member will reject the request.
For instance, the maintenance.Status API will return "auth: invalid auth token". But the client doesn't identify the error. The client won't retry to refresh auth token. The maintenance.Status should togRPCError before return so that the client can reflesh token. It's align with existing API.
Since the maintenance client always creates one connection to target member, the member will have the token after refresh auth.
Maybe we can introduce a sync to wait for member is ready with token, instead of refreshing.
Fixes: #15758
Please read …
=> server/etcdserver: togRPCError for maintenance API

pkg/grpc_testing/stub_server.go, tests/integration/clientv3/naming/resolver_test.go
The [default grpc-go load balancing strategy is pick first](https://github.com/grpc/grpc-go/issues/5009) which may not be expected, particularly for production scenarios. We should consider adding a test for round robin as an alternative.
Refer: https://github.com/etcd-io/website/pull/633
=> tests: Add new test for round robin resolver

etcdmain/config.go, etcdmain/help.go
This pull request addresses https://github.com/etcd-io/etcd/issues/15743. This is a backport for version 3.4..
@lavacat @ahrtr @jmhbnz
=> [3.4] server: backport 15743, improved description of --initial-cluster-state

server/proxy/grpcproxy/register.go
In func `NewSession`
https://github.com/etcd-io/etcd/blob/e04120042e0c05143816679804cab46e84bc96c3/client/v3/concurrency/session.go#L67-L72
It create a new goroutine to eat messages until keep alive channel closes.
However, the `s.Close` is missed some branch of   `registerSession` (L72 and L75)
https://github.com/etcd-io/etcd/blob/e04120042e0c05143816679804cab46e84bc96c3/client/v3/concurrency/session.go#L92-L105
https://github.com/etcd-io/etcd/blob/e04120042e0c05143816679804cab46e84bc96c3/server/proxy/grpcproxy/register.go#L64-L85
As `registerSession` will return nil instead of the created session, it seems we cannot close it from its callee, with will cause some leak routines. For example,
```
[Goroutine 16 in state chan send, with …
```
=> close the session to avoid leak goroutine

tests/robustness/linearizability_test.go, tests/robustness/report.go
// t.Failed() returns false during panicking. We need to forcibly
// save data on panicking.
// Refer to: https://github.com/golang/go/issues/49929
=> test: forcibly save data on panicking

scripts/test_lib.sh
Though there is mention of mode `fail_fast`, at https://github.com/etcd-io/etcd/blob/main/scripts/test_lib.sh#L252, and usages, there is no actual pass of `-failfast` flag.
_Usages locations:_
https://github.com/etcd-io/etcd/blob/main/scripts/test.sh#L163
https://github.com/etcd-io/etcd/blob/main/scripts/test.sh#L168
=> Add -failfast flag when the mode is fail_fast

tests/robustness/client.go, tests/robustness/failpoints.go, tests/robustness/watch.go
In a [scheduled test][1], the error shows
```
2023-04-19T11:16:15.8166316Z     traffic.go:96: rpc error: code = Unavailable desc = keepalive ping failed to receive ACK within timeout
```
According to [grpc-keepalive@v1.51.0][2], each frame from server will fresh the `lastRead` and it won't file `Ping` frame to server. But the client used by [`tombstone` request][3] might hit the race. Since we use 5ms as timeout, the client might not receive the result of `Ping` from server in time. The keepalive will mark it timeout and close the connection.
I didn't reproduce it in my local. If we add the sleep before update `lastRead`, it can reproduce it sometimes. Still investigating this part.
```diff
diff --git a/internal/transport/http2_client.go b/internal/transport/http2_client.go
index …
```
=> tests/robustness: tune timeout policy

tests/integration/clientv3/naming/resolver_test.go
The flake is as a result of the new test case I introduced in #15577. The test case was sending 100 requests using a round robin resolver against two endpoints and expecting roughly half to go to each server, with a 10% total tolerance (so 5% either side of 50).
In the identified flake 61 requests went to first server and 39 to the second so more than the 5% either side threshold.
To try and address that I am going to increase number of requests  to 1,000 which should reduce run to run variability by increasing sample size. Additionally I will increase allowed tolerance to 15%.
These two changes in combination are expected to reduce the chance this flake can happen.
Fixes: #15794
=> tests: Deflake TestEtcdGrpcResolverRoundRobin

server/etcdserver/v3_server.go, tests/e2e/ctl_v3_auth_test.go, tests/e2e/ctl_v3_lease_test.go, tests/integration/v3_auth_test.go
Currently, `LeaseTimeToLive()` API or `etcdctl lease timetolive` command don't require RBAC permission. However, their responses can have key names attached to the target lease. Value of the keys cannot be accessed through the API, but protecting the key name is better. So this PR let the API require read permission of keys attached to a lease (if a lease isn't attached to specific keys, behavior won't be changed).
cc @ahrtr @serathius @spzala @ptabor
=> protect LeaseTimeToLive with RBAC

Documentation/contributor-guide/dependency_management.md
XREF: https://github.com/etcd-io/etcd/pull/15810
=> dependency_management.md: document go.opentelemetry.io/otel version update is blocked

.github/workflows/go-version.yaml
Go 1.19.9 was released 2023-05-02, we should consider updating.
https://go.dev/doc/devel/release#go1.19.minor
> The update includes three security fixes to the html/template package, as well as bug fixes to the compiler, the runtime, and the crypto/tls and syscall packages. See the [Go 1.19.9 milestone](https://github.com/golang/go/issues?q=milestone%3AGo1.19.9+label%3ACherryPickApproved) on our issue tracker for details.
=> Updated go to latest patch release 1.19.9

tests/robustness/client.go, tests/robustness/linearizability_test.go, tests/robustness/model/history.go, tests/robustness/model/model.go, tests/robustness/model/model_test.go, tests/robustness/traffic.go
https://docs.google.com/document/d/1NUZDiJeiIH5vo_FMaTWf0JtrQKCx0kpEaIIuPoj9P6A/edit?usp=sharing
* Use mod revision for optimistic concurrency.
* Introduce range requests as more general then get
* Add kubernetes specific traffic generation, for now using pull, but expected to evolve to use watch.
* Introduce kubernetes specific test scenario
=> tests/robustness: Implement first step in validating the Kubernetes-etcd contract

.github/workflows/e2e-arm64.yaml, .github/workflows/tests-arm64.yaml
```
Warning: Unexpected input(s) 'ref', valid inputs are ['go-version', 'go-version-file', 'check-latest', 'token', 'cache', 'cache-dependency-path', 'architecture']
```
xref: https://github.com/etcd-io/etcd/issues/15647#issuecomment-1530058382
=> remove invalid arm64 workflow config

.github/workflows/e2e.yaml, .github/workflows/functional.yaml, .github/workflows/go-version.yaml, .github/workflows/grpcproxy.yaml, .github/workflows/release.yaml, .github/workflows/tests.yaml, Makefile, scripts/release
Backport the following to `release-3.5`:
- https://github.com/etcd-io/etcd/pull/15748
- https://github.com/etcd-io/etcd/pull/15821
=> [3.5] Backport updating go to latest patch release 1.19.9 

.github/workflows/go-version.yaml, .github/workflows/release.yaml, .github/workflows/tests.yaml, Makefile, functional/scripts/docker-local-agent.sh, functional/scripts/docker-local-tester.sh, scripts/release.sh
Backport the following to `release-3.4`:
- https://github.com/etcd-io/etcd/pull/15748
- https://github.com/etcd-io/etcd/pull/15821
=> [3.4] Backport updating go to latest patch release 1.19.9

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
We recently backported:
- https://github.com/etcd-io/etcd/pull/15823
- https://github.com/etcd-io/etcd/pull/15822
Let's prep the changelog to show which go release binaries would compile with.
There could be more go patch releases between now and the next releases but we can always tweak it later to take those into account.
=> Update 3.4 and 3.5 changelogs for compile with 1.19.9.

server/etcdserver/v3_server.go
This is a follow up commit for https://github.com/etcd-io/etcd/pull/15656
The format check in release-3.5 branch (https://github.com/etcd-io/etcd/actions/runs/4867999645/jobs/8681084238?pr=15815) found that the order of return types of `checkLeaseTimeToLive()` is invalid. It wasn't detected in main and release-3.4. This PR fixes that.
The backport PRs (https://github.com/etcd-io/etcd/pull/15815 and https://github.com/etcd-io/etcd/pull/15814) have same style fix.
cc @ahrtr @spzala @serathius
=> server/etcdserver: swap order of return types

scripts/test.sh, scripts/test_lib.sh
The existing logic in the function run_for_modules exits the loop through modules when there is a failure.
- This change adds an environment variable  KEEP_GOING_MODULE to have the option to continue running tests in other modules even on failure with one of them.
- Also including comments in `test.sh` to describe KEEP_GOING_MODULE and KEEP_GOING_SUITE
- Changing variable PASSES_CONTINUE to KEEP_GOING_SUITE
Instead of https://github.com/etcd-io/etcd/pull/15824
=> Add an option to keep_going with run for modules on failure

etcdserver/v3_server.go, integration/v3_auth_test.go, tests/e2e/ctl_v3_auth_test.go, tests/e2e/ctl_v3_lease_test.go
This PR backports #15656 to release-3.4
cc @ahrtr @spzala @serathius
=> Backport 15656 to release-3.4

tests/robustness/model/history.go, tests/robustness/traffic/client.go, tests/robustness/traffic/traffic.go
=> tests/robustness: Add safeguards to client and history

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
https://github.com/etcd-io/etcd/releases/tag/v3.4.26 was just released, and also 3.5.9 was released.
=> Changelog: update the release date of 3.4.26 and 3.5.9

Documentation/contributor-guide/triage_issues.md
This pull request proposes a significant re-write of our existing etcd issue triage guidelines.
The purpose of the re-write is to make the guidelines into a more step by step process with clearer descriptions of the actual actions expected to be taken. 
Additionally these new guidelines align closer to the style of [kubernetes issue triage guidelines](https://www.kubernetes.dev/docs/guide/issue-triage) and now take into account our new etcd [community membership model](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/community-membership.md).
The expected outcome is that these new guidelines will be easier for contributors to follow and will hopefully empower our new @etcd-io/members to be active with triage, which should reduce burden on maintainers and help …
=> Initial re-write for contributor issue triage guide

.github/workflows/go-version.yaml, .github/workflows/tests-arm64.yaml
Grant readonly permission to workflows. We already did this, but missing for two workflows.
=> workflow: grant only read permission to all workflows

.github/workflows/e2e-arm64.yaml, .github/workflows/robustness-nightly.yaml, .github/workflows/robustness-template.yaml, .github/workflows/robustness.yaml, .github/workflows/tests-arm64.yaml
In order to progress tier one support for `arm64` we need to get nightly on per pull request actions workflows running our robustness test suite on the `arm64` platform.
This pull request completes the work started in https://github.com/etcd-io/etcd/pull/15310:
- Robustness template updated to support dynamic `runs-on`.
- New `main-arm64` jobs added to robustness nightly workflow.
Additionally this pull request adds the [recommended `self-hosted` label](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#choosing-self-hosted-runners) to existing `arm64` tests and e2e workflows.
Relates to https://github.com/etcd-io/etcd/issues/14748
cc @serathius, @ahrtr, @chaochn47
=> Run robustness tests on arm64

server/proxy/grpcproxy/cluster.go, tests/integration/proxy/grpcproxy/cluster_test.go
If start grpc proxy with --resolver-prefix, memberlist will return all alive proxy nodes, when one grpc proxy node is down, it is expected to not return the down node, but it is still return
=> grpcproxy: fix memberlist results not update when proxy node down

tests/robustness/linearizability_test.go, tests/robustness/traffic/client.go, tests/robustness/traffic/traffic.go, tests/robustness/watch.go
see: https://github.com/etcd-io/etcd/pull/15323
For consistency watch events should also use only time-measurement operations.
fixes: https://github.com/etcd-io/etcd/issues/15328
=> tests/robustness: use monotonic clock for watch events

tests/robustness/README.md, tests/robustness/identity/id.go, tests/robustness/linearizability_test.go, tests/robustness/model/history.go, tests/robustness/report.go, tests/robustness/traffic/client.go, tests/robustness/traffic/etcd.go, tests/robustness/traffic/kubernetes.go, tests/robustness/traffic/traffic.go, tests/robustness/watch.go
=> tests/robustness: Validate all etcd watches opened to etcd

server/storage/schema/bucket.go
Benchmarks show `bytes.Equal` is much faster than `bytes.Compare`[1] for equality comparisons and preferred per the example in docs[2].
[1] https://www.sobyte.net/post/2022-01/go-bytes-compare-equal/
[2] https://pkg.go.dev/bytes#Compare
=> server/storage/schema: prefer equal to compare for equality comparisons

server/proxy/grpcproxy/cluster.go, tests/integration/proxy/grpcproxy/cluster_test.go
Backport of https://github.com/etcd-io/etcd/pull/15835
cc @lavacat @ahrtr
=> [release-3.5]grpcproxy: fix memberlist results not update when proxy node down

.github/workflows/e2e.yaml, tests/common/kv_test.go
For the sub test TestKVDelete/ClientAutoTLS, the timeout might be caused by IO or task scheduled. It's really hard to reproduce this case. And we don't add `VERBOSE=1` for e2e test, the pipeline doesn't show the `EXPECT_DEBUG` log in time. It's also hard to debug when flaky case show. ~~So, this patch adds `readAt` timestamp to `EXPECT_DEBUG` log.~~ So, this patch will enable `VERBOSE=1` to get timestamp in time.
And the one operation `del a c -w json` will be performed after two seconds delay, we can increase the timeout from 15s to 30s just in case that the put or del operations take more time in unstable env.
```
Warning: Keys between "a" and "c" will be deleted. Please interrupt the
command within next 2 seconds to cancel.
```
Close: #14762
Please read …
=> tests: deflake TestKVDelete/ClientAutoTLS

etcd.conf.yml.sample
In discussion https://github.com/etcd-io/etcd/discussions/15837 an etcd user wasn't clear about how to specify `initial-cluster` in the configuration file which led to their cluster not starting, and unfortunately our [sample configuration file](https://github.com/etcd-io/etcd/blob/main/etcd.conf.yml.sample) currently doesn't provide any real guidance on this.
Let's help our users get it right the first time by adding a quick example format to the config file.
Longer term we should also investigate better handling of spaces in these strings so a more expressive dictionary style could be freely used as well.
=> Add example format for initial-cluster in configuration file

server/etcdserver/corrupt.go, server/storage/mvcc/hash.go
Update minor code comments to improve code readability when reviewing PR https://github.com/etcd-io/etcd/pull/15924
=> update code comments

tools/benchmark/cmd/range.go
With limit flag, we can verify the performance for the pagination.
=> tools/benchmark: support limit flag for range

client/pkg/types/id.go, contrib/raftexample/kvstore.go, etcdctl/ctlv3/command/printer_json.go, pkg/cobrautl/help.go, pkg/report/timeseries.go, pkg/traceutil/trace.go, server/etcdserver/api/membership/cluster.go, tools/etcd-dump-logs/main.go, tools/proto-annotations/cmd/etcd_version.go
strings.Builder uses *(*string)(unsafe.Pointer(&b.buf)) to save the application memory operation when converting to a string
Updates https://github.com/etcd-io/etcd/issues/15910
=> *: use strings.Builder instead of bytes.Buffer

client/v3/naming/endpoints/endpoints_impl.go, tests/integration/clientv3/naming/resolver_test.go
Backport of #15021 to release-3.5
fixes bug with multiple endpoints with same prefix
=> [release-3.5]naming/endpoints: backport of #15021, fix endpoints prefix bug

tests/robustness/traffic/client.go, tests/robustness/traffic/kubernetes.go, tests/robustness/watch.go
=> tests/robustness: Use traffic.RecordingClient in watch

tools/mod/go.mod, tools/mod/go.sum
=> [20230530] Bump dependencies identified by dependabot

MAINTAINERS
We have moved the roles description from Governance file.
=> Update roles reference

Documentation/contributor-guide/triage_issues.md
One task as part of our planned [issue triage refresh](https://github.com/etcd-io/etcd/issues/15773) is:
> Update [triage_issues.md](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/triage_issues.md) to add a clearer support policy statement to the aim to shift away from providing 1:1 support and instead addressing broader themes and concerns in a way that helps all etcd users.
This pull request proposes stronger wording and clear instructions we can follow to ensure our github discussion forums are the place where our support issues are managed.
The proposal to use the "Convert to discussion" github feature would remove some support clutter from our issues section, leaving that focused on our open development work like bugs and features, while our support …
=> Strengthen etcd support policy in issue triage docs

.github/ISSUE_TEMPLATE/bug-report.yml, README.md
This pull request completes the following subtask of our [refresh for etcd issue triage](https://github.com/etcd-io/etcd/issues/15773):
> Raise the profile of our [frequently asked questions](https://etcd.io/docs/v3.5/faq) page by adding it to key areas like issue templates and readme.
Additionally I have:
- Fixed a number of minor lint errors reported by `markdownlint` in the `README.md`.
- Refactored our bug report template to add an interactive checklist to help guide users to the right channels before opening issues, take a look at a preview below or interactive here: https://github.com/jmhbnz/etcd/issues/new?assignees=&labels=type%2Fbug&projects=&template=bug-report.yml
=> Promote etcd frequently asked questions in our bug report template and readme

server/etcdserver/corrupt.go, server/storage/mvcc/kvstore.go, server/storage/mvcc/kvstore_test.go, tests/e2e/corrupt_test.go, tests/framework/e2e/cluster.go
Fix #15919 
Commit 1: add an e2e test to reproduce the problem. This test won't pass without the fix.
Commit 2: check ScheduledCompactKeyName and FinishedCompactKeyName
before writing hash to hashstore. If they do not match, then it means this compaction has once been interrupted and its hash value is invalid. In such cases, we won't write the hash values to the hashstore, and avoids the incorrect corruption alarm.
=> Check ScheduledCompactKeyName and FinishedCompactKeyName before writing hash

tests/robustness/linearizability_test.go
=> tests/robustness: Put traffic type on second place before cluster size in test name

server/embed/etcd.go, tests/e2e/ctl_v3_grpc_test.go, tests/e2e/ctl_v3_test.go, tests/e2e/etcd_release_upgrade_test.go, tests/e2e/utils.go, tests/framework/e2e/cluster.go, tests/framework/e2e/util.go, tests/framework/integration/cluster.go
1. Add test coverage of unix domain socket address as `--listen-client-urls`
2. Address the potential blocker based on https://github.com/etcd-io/etcd/pull/15940#pullrequestreview-1466036536
cc @serathius @ahrtr @jmhbnz
=> add uds test cases into e2e TestAuthority

server/etcdmain/help.go
add experimental-compact-hash-check-enabled and experimental-compact-hash-check-time to help.
cherry-pick https://github.com/etcd-io/etcd/pull/16031 to release-3.5.
=> cherry-pick #16031 to release-3.5 

server/etcdmain/help.go
add `experimental-compact-hash-check-enabled` and `experimental-compact-hash-check-time` to help.
=> add experimental-compact-hash-check-enabled to help

tests/robustness/linearizability_test.go, tests/robustness/model/history.go, tests/robustness/validate/operations.go, tests/robustness/validate/patch_history.go, tests/robustness/validate/validate.go, tests/robustness/validate/watch.go, tests/robustness/watch.go
=> tests/robustness: Extract validation to separate package

server/etcdserver/apply/apply_auth.go, server/etcdserver/apply/apply_auth_test.go, server/lease/lease.go, server/lease/lessor.go
Mitigates etcd-io#15993 by not checking each key individually for permission when auth is entirely disabled or admin user is calling the method.
=> Early exit auth check on lease puts

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
update https://github.com/etcd-io/etcd/pull/16047 and https://github.com/etcd-io/etcd/pull/16048 to Changelog
=> update 3.4 and 3.5 changelogs

Makefile, scripts/fix-goimports.sh, scripts/fix.sh
Sub task of https://github.com/etcd-io/etcd/issues/13896.
This pull request proposes a new `Makefile` target `fix-goimports` to ensure this can be run individually. As a side effect `scripts/fix.sh` becomes less monolithic which if I understand correctly is part of the intent of https://github.com/etcd-io/etcd/issues/13896.
Additionally I noticed a couple of `Makefile` `PHONY` target names did not match their child target names so I have aligned these under a second commit.
=> Ensure goimports can be fixed individually

tests/robustness/failpoints.go, tests/robustness/linearizability_test.go
Part of https://github.com/etcd-io/etcd/issues/15913
=> tests/robustness: Disable blackhole until snapshot for v3.5 and v3.4

tests/robustness/model/deterministic.go, tests/robustness/model/deterministic_test.go, tests/robustness/model/non_deterministic.go, tests/robustness/model/non_deterministic_test.go
It is just to complicated to support starting from non-empty etcd. Existing implementation was very naive to assume that we can build full state from just one request. We might consider implementing validation of non-empty history in future, but for now settting this limit should clean up the code and speed up development.
=> tests/robustness: Limit model to start only from fresh state

tests/robustness/failpoints.go, tests/robustness/linearizability_test.go
=> Robustness retry failpoint

server/mvcc/kvstore.go, server/mvcc/kvstore_test.go
cherry-pick https://github.com/etcd-io/etcd/pull/14457
=> [3.5] etcdserver: fix corruption check when server has just been compacted

tests/robustness/model/describe.go, tests/robustness/model/describe_test.go, tests/robustness/model/deterministic.go, tests/robustness/model/deterministic_test.go, tests/robustness/model/history.go, tests/robustness/traffic/client.go, tests/robustness/traffic/etcd.go, tests/robustness/traffic/kubernetes.go, tests/robustness/traffic/traffic.go, tests/robustness/validate/validate.go
For now we just validate stale read revision, but not response content. Reason is that etcd model only stores latest version of keys, and no history like real etcd.
Validating stale read contents needs to be done outside of model as storing whole history is just to costly for linearization validation.
=> tests/robustness: Implement stale reads without validation

Documentation/infra-guide/arm64-infra.md
This is a quick pull request to close out https://github.com/etcd-io/etcd/issues/15953.  The intent is to document what we need to do if we need to provision new or additional `arm64` compute for the project.
We have plans to adopt automation for provisioning new `c3.large.arm` machines, however there is a lot of external interest in etcd moving `arm64` to tier 1 status and my view is that the automation is not required for this to proceed so I am going to move that future improvement to a separate issue and suggest we merge this basic documentation as a first step so tier1 can happen sooner.
Fixes https://github.com/etcd-io/etcd/issues/15953
=> Document new arm64 infra process

tests/robustness/linearizability_test.go
=> tests/robustness: Separate traffic name from cluster setup in test name

tests/robustness/traffic/kubernetes.go
Having too many delete requests is bad as they are not unique requests, so linearization is more prone to timeout on them.
Going from 30% to 10%.
cc @ahrtr @ptabor @fuweid @jmhbnz @chaochn47
=> tests/robustness: Tune Kubernetes tests to reduce number of delete requests

server/etcdserver/apply_auth.go, server/etcdserver/apply_auth_test.go, server/lease/lessor.go
Mitigates #15993 by not checking each key individually for permission when auth is entirely disabled or admin user is calling the method.
Backport of #16005
=> [3.5] Early exit auth check on lease puts

etcdserver/apply_auth.go, etcdserver/apply_auth_test.go, lease/lessor.go
Mitigates #15993 by not checking each key individually for permission when auth is entirely disabled or admin user is calling the method.
Backport of #16005
=> [3.4] Early exit auth check on lease puts

server/etcdserver/server.go, server/etcdserver/server_test.go
=> Verify consistent index is latest at the time of snapshot

tests/robustness/model/describe.go, tests/robustness/model/describe_test.go, tests/robustness/model/deterministic.go, tests/robustness/model/deterministic_test.go, tests/robustness/model/history.go, tests/robustness/model/non_deterministic_test.go, tests/robustness/model/replay.go, tests/robustness/traffic/client.go, tests/robustness/validate/patch_history.go, tests/robustness/validate/validate.go, tests/robustness/validate/watch.go
Change `key` in range requests to `start`, `end`
=> tests/robustness: Implement proper range requests

Documentation/infra-guide/arm64-infra.md
This pull request introduces basic step by step instructions for turning a brand new Equinix Metal `arm64` bare metal machine into a github actions runner for etcd project self hosted `arm64` workflows.
Where possible I am relying on existing github documentation.
In future I intend to automate this process further via something like terraform but this basic documentation gives us enough to mark the initial issue as closed and be one step closer to `arm64` T1.
Fixes https://github.com/etcd-io/etcd/issues/15954
=> Document steps for setting up new arm64 self hosted actions runner

.github/workflows/tests-arm64.yaml, .github/workflows/tests.yaml, bill-of-materials.json, go.mod, go.sum, server/etcdserver/raft.go, tests/framework/integration/testing.go, tests/go.mod, tests/go.sum, tests/integration/clientv3/cluster_test.go
Enable failpoint in integration test. Part of https://github.com/etcd-io/etcd/pull/15708 to address the original issue. 
=> Enable failpoint in integration test

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
We recently backported:
- https://github.com/etcd-io/etcd/pull/16038
- https://github.com/etcd-io/etcd/pull/16033
=> Update 3.4 and 3.5 changelogs for compile with 1.19.10

pkg/expect/expect.go, pkg/expect/expect_test.go, tests/framework/e2e/etcd_process.go
For the pkg/expect package, if the process has been stopped but there is no `Close()` call, the `ExitCode()` won't return exit code correctly. The `ExitCode()` should check `exitErr` and return exit code if cmd isn't nil.
And introduces `exitCode` to return correct exit code based on the process is signaled or exited.
-----
Context: https://github.com/etcd-io/etcd/pull/16094#discussion_r1233134482
cc @serathius @tjungblu 
fixes: #16134
=> *: should return exitCode even if cmd isn't nil

server/etcdserver/apply/apply_auth_test.go
Achieved 100% test coverage for apply_auth.go.
The test cases focus on the authorization itself, can verifies operations can only be performed by proper users and roles. The correctness of the applying result is not checked by these tests.
=> etcdserver: add tests for apply_auth.go

tests/e2e/ctl_v3_auth_cluster_test.go, tests/e2e/etcd_grpcproxy_test.go, tests/e2e/etcd_mix_versions_test.go, tests/e2e/runtime_reconfiguration_test.go, tests/framework/e2e/cluster.go, tests/framework/e2e/etcdctl.go
Followed
1. https://etcd.io/docs/next/op-guide/runtime-configuration
2. https://etcd.io/docs/next/op-guide/runtime-reconf-design 
To address https://github.com/etcd-io/etcd/pull/15708#issuecomment-1506553979
> This PR not only changes MemberPromote, but introduces a big change for all membership changes. We should double check that all configuration changes are properly tested. If not we should add a large set of e2e tests that:
Grow cluster from 1 to 3 members (without learners)
Grow cluster from 1 to 3 members (with learners) in both 1 at the time and two at one time scenario
Reduce cluster from 3 to 1 member
etc
=> add runtime reconfiguration tests

server/etcdserver/raft.go, server/etcdserver/raft_test.go, server/etcdserver/server.go, server/etcdserver/server_test.go, tests/integration/clientv3/cluster_test.go
Fix #15528
The PR is built on top of https://github.com/etcd-io/etcd/pull/15703
PTAL @ahrtr @serathius, thanks!
=> raft node notifies configure when confChanged

etcdutl/etcdutl/snapshot_command.go, etcdutl/snapshot/util.go, etcdutl/snapshot/v3_snapshot.go, tests/e2e/ctl_v3_snapshot_test.go, tests/framework/e2e/etcdctl.go
This PR adds the flags `--bump-revision` and `--mark-compacted` to etcdutl snapshot restore for #16028.
I chose to handle this after the database is loaded from the snapshot, so as to not modify the snapshot, I didn't want to risk corrupting the snapshot as a part of this optional step. If for some reason the bump fails, a user would still be able to restore the snapshot again without the bump and restart the watchers manually.
=> Adding optional revision bump to snapshot restore

etcdutl/etcdutl/snapshot_command.go
It's really weird to have circular description between `--bump-revision` and `--mark-compacted`,
- description `required if --mark-compacted` for flag `--bump-revision`
- description `required if --bump-revision > 0` for flag `--mark-compacted`
Actually `--mark-compacted` is determined entirely by `--bump-revision`,
- It (--mark-compacted) isn't allowed if users do not bump revision
- It (--mark-compacted) must be specified if users bump the revision
So we only need to add the description(restrictions) to flag `--mark-compacted`. See also https://github.com/etcd-io/etcd/pull/16029#issuecomment-1612703238
=> etcdutl: update description for `--mark-compacted and` and `--bump-revision` flags in snapshot restore command

api/v3rpc/rpctypes/error.go, server/etcdserver/api/rafthttp/http.go, server/etcdserver/api/rafthttp/stream.go, server/etcdserver/api/rafthttp/util.go, server/etcdserver/corrupt.go, server/etcdserver/corrupt_test.go, tests/e2e/corrupt_test.go, tests/framework/e2e/cluster.go, tests/integration/hashkv_test.go
See https://github.com/etcd-io/etcd/issues/15548
This PR only adds cluster id check for hashKVHandler. Cluster id checks for other handlers(member, promote, version, etc.) will be in separate PRs.
=> Add cluster id check for hash kv handler

client/v3/experimental/recipes/barrier.go, tests/integration/clientv3/experimental/recipes/v3_barrier_test.go
fix the unexpected blocking when using Barrier.Wait(), e.g. NewBarrier(client, "a").Wait() will block if key "a" is not existed but "a0" is existed, but it should return immediately.
=> clientv3: remove v3.WithFirstKey() in Barrier.Wait()

client/v3/experimental/recipes/barrier.go, tests/integration/clientv3/experimental/recipes/v3_barrier_test.go
=> [3.5] clientv3: remove v3.WithFirstKey() in Barrier.Wait()

server/etcdserver/apply/uber_applier_test.go
#16036 
Add tests for uber applier.
Test cases involve building correct applier chains when alarms are on and off.
=> add tests for uber applier

etcdutl/snapshot/v3_snapshot.go
#11838 fix `db` may not be closed，but  in `768da4` missing line: `dbClosed = true`（`git bisect` is very useful ）
if `copyAndVerifyDB` return nil, `db` is closed twice.
=> etcdutl: fix db double closed

tests/e2e/runtime_reconfiguration_test.go
Noticed a few test flakes of the newly added test. Usually etcd client will pick the first server address. 
Fix is to exclude learner endpoint from `MemberPromote`. 
```
2023-07-06T08:49:21.8398626Z     runtime_reconfiguration_test.go:181: 
2023-07-06T08:49:21.8400055Z         	Error Trace:	/home/runner/work/etcd/etcd/tests/e2e/runtime_reconfiguration_test.go:181
2023-07-06T08:49:21.8401843Z         	            				/home/runner/work/etcd/etcd/tests/e2e/runtime_reconfiguration_test.go:78
2023-07-06T08:49:21.8404818Z         	Error:      	Received unexpected error:
2023-07-06T08:49:21.8411142Z         	            	[/home/runner/work/etcd/etcd/bin/etcdctl --endpoints=http://localhost:20005 endpoint health] match not found.  Set EXPECT_DEBUG for more info Errs: [unexpected exit code [1] …
```
=> tests: exclude learner endpoint from MemberPromote

clientv3/snapshot/util.go, clientv3/snapshot/v3_snapshot.go, etcdctl/ctlv3/command/snapshot_command.go, mvcc/util.go, tests/e2e/ctl_v3_snapshot_test.go
3.4 backport of https://github.com/etcd-io/etcd/pull/16029 for https://github.com/etcd-io/etcd/issues/16028
=> [3.4] Adding optional revision bump and mark compacted to snapshot restore

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md, CHANGELOG/CHANGELOG-3.6.md
=> Update CHANGELOG for #16029 #16165 #16193

MAINTAINERS, README.md
I am sending this PR to ask for approval to regain maintainer status.
Recent activities:
- https://github.com/etcd-io/etcd/pull/16193 merged
- https://github.com/etcd-io/etcd/pull/16194 merged
Plan forward:
- Currently working on design doc for https://github.com/etcd-io/etcd/issues/16007
- Regular issue triage, feature development
- Help with [community meetings](https://github.com/etcd-io/etcd/pull/16189#discussion_r1255308042), [KubeCon](https://github.com/etcd-io/etcd/discussions/16186)
- And anything else
Reference:
- Started being etcd maintainer in January 2021: https://github.com/etcd-io/etcd/pull/12624
- Retired in September 2022: https://github.com/etcd-io/etcd/pull/14373
I have not been active in OSS etcd community for a while but I have been working on kubernetes and etcd the …
=> Asking for approval to regain maintainer status

embed/etcd.go, tests/e2e/cluster_test.go, tests/e2e/cmux_test.go
Since v3.4.25, ETCD server introduces http-only urls flag to expose gRPC-only endpoints. When user enables this feature, the stopServer will panic during terminating. If the server is leader, it won't have chance to transfer the leadership.
```
Jul 07 14:43:04  etcd[11502]: received terminated signal, shutting down...
Jul 07 14:43:04  etcd[11502]: WARNING: 2023/07/07 14:43:04 grpc: addrConn.createTransport failed to connect to {0.0.0.0:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial tcp 0.0.0.0:2379: connect: connection refused". Reconnecting...Jul 07 14:43:04  etcd[11502]: WARNING: 2023/07/07 14:43:04 grpc: addrConn.createTransport failed to connect to {0.0.0.0:2379  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing …
```
=> [3.4] embed: fix nil pointer dereference when stopServer

CHANGELOG/CHANGELOG-3.4.md
- [embed: fix nil pointer dereference when stopServer](https://github.com/etcd-io/etcd/pull/16195)
=> CHANGELOG: add item for 3.4.27

README.md
As discussed at our recent community meeting we have run a brief survey to get consensus on how often the community would like to meet.
The [survey results](https://github.com/etcd-io/website/issues/703) are now in and the community would prefer to move to fortnightly meetings.
=> Update community meeting frequency to fortnightly

.github/workflows/e2e-arm64-nightly.yaml, .github/workflows/e2e-arm64-template.yaml, .github/workflows/tests-arm64-nightly.yaml, .github/workflows/tests-arm64-template.yaml
Follow-on from https://github.com/etcd-io/etcd/pull/16151 to setup scheduled workflows for `arm64` nightly integration and e2e suites against the `release-3.5` branch.
Arm64 integration and e2e suites now adopt a shared re-usable workflow template which is slightly customised for `main` or `release-3.5`.
Fixes https://github.com/etcd-io/etcd/issues/15832
=> Templated arm64 integration and e2e workflows for main and release-3.5

client/v3/concurrency/stm.go, client/v3/concurrency/stm_test.go
Related issue: https://github.com/etcd-io/etcd/issues/13400
Also add some tests for this specific case!
=> Clientv3 prevent nil pointer

tools/benchmark/cmd/range.go
=> tools/benchmark: support --count-only for range

pkg/expect/expect.go, pkg/expect/expect_test.go
Let's say there is command which outputs one line and exit with error.
There are three goroutines to acquire the lock:
1. ep.read()
2. ep.waitSaveExitErr()
3. ep.Expect()
When ep.read goroutine reads the log but it doesn't acquire the lock in time, the ep.waitSaveExitErr acquires the lock and updates the `exitErr`. And then ep.Expect acquires lock but it doesn't see any log yet and then returns err.
It's hard to reproduce it in local. Add the extra sleep can reproduce it.
```diff
diff --git a/pkg/expect/expect.go b/pkg/expect/expect.go
index a512a3ce4..602bea73f 100644
--- a/pkg/expect/expect.go
+++ b/pkg/expect/expect.go
@@ -128,6 +128,7 @@ func (ep *ExpectProcess) tryReadNextLine(r *bufio.Reader) error {
printDebugLines := os.Getenv("EXPECT_DEBUG") != ""
l, err := r.ReadString('\n')
+ …
```
=> pkg/expect: fix data race

Documentation/infra-guide/arm64-infra.md, MAINTAINERS
This pr updates `MAINTAINERS` to add myself as reviewer following recent nomination https://github.com/etcd-io/etcd/issues/16233.
Note: Also fixed a tiny format issue for github handle reference for @ahrtr.
=> Add jmhbnz as etcd reviewer

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
Link to https://github.com/etcd-io/etcd/pull/16226
=> Changelog: add items to cover the fix of bumping go to 1.19.11

.github/workflows/robustness-nightly.yaml
In https://github.com/etcd-io/etcd/pull/15886 we introduced an `arm64` nightly job for robustness running against `main` branch.
This pr extends that to include a job for `release-3.5`, in support of announcing tier 1 support for arm64 for 3.5+.
=> Add new job for nightly release35 arm64 robustness

client/v3/client.go, server/auth/store.go, tests/e2e/ctl_v3_auth_test.go
Backport #13577
Disable auth gracefully without impacting existing watchers.
Related:
- #16235
TODO: changelog for 3.5 after this pr is merged.
=> [3.5] Backport #13577 to 3.5

client/v3/op.go, client/v3/op_test.go
=> expose op.isOptsWithFromKey and op.isOptsWithPrefix

pkg/expect/expect.go
ExpectProcess's Stop method uses 'strings.Contains' to check the returned err, however, this can be avoided. os.ErrProcessDone's error message is the same as the hardcoded string. So I think this explicit error is what this method wants to compare.
=> pkg/expect: avoid hardcoding when checking ErrProcessDone

etcdctl/ctlv3/command/check.go, etcdctl/ctlv3/command/util.go
The current printing code is complicated.
This PR simplifies the code and reduces the function calls.
Please take a look.
=> etcdctl/ctlv3/command: simplify code using fmt.Printf with '\n'

.github/workflows/e2e-arm64-nightly.yaml, scripts/test.sh
Recently in https://github.com/etcd-io/etcd/pull/16152 we extended our `arm64` nightly test coverage to include `release-3.5` as  a requirement for being able to announce tier1 support for `arm64`.
When these were merged the `PASSES` for the test command was `PASSES='build e2e'`.   To truly have alignment between what we run for `arm64` vs `amd64` we need to update that to `PASSES='build release e2e'`.
Now that the first iteration of the tests have been merged and are passing successfully overnight I would now like to fix the alignment so both architectures run the exact same command.
This is a pre step before I can start work on https://github.com/etcd-io/etcd/issues/16176.
=> Ensure release is run for arm64 e2e nightly tests

pkg/ioutil/pagewriter_test.go
The PageWriter has cache buffer so that it doesn't call the Writer until the cache is almost full. Since the data's length is random, the pending bytes should be always less than cache buffer size, instead of page size.
Fix: #16255
=> pkg/ioutil: deflake TestPageWriterRandom

client/v3/client.go, client/v3/client_test.go
=> Backport #14368 to v3.5

tests/framework/integration/cluster.go
Please review this simple patch on [tests/framework/integration/cluster.go].
It looks unnecessary to assign the value returned by `net.SplitHostPort` to variable `host`.
[tests/framework/integration/cluster.go]:
<https://github.com/etcd-io/etcd/blob/main/tests/framework/integration/cluster.go>
=> tests: cleanup unnecessary assignment in cluster.go

.github/workflows/e2e.yaml, test.sh
Currently `release-3.5` e2e tests for `amd64` are relying on a hardcoded version, currently `v.3.4.7`. Refer: https://github.com/etcd-io/etcd/actions/runs/5603021362/job/15178839191#step:6:932 
```bash
'release' started at Wed Jul 19 19:00:50 UTC 2023
Downloading etcd-v3.4.7-linux-amd64.tar.gz
```
I believe this hard coded version was put in place because by default the github `checkout` action does a shallow clone, meaning our reliance on checking for local repository tags fails.
Recently we fixed this for `main` in  https://github.com/etcd-io/etcd/pull/16230 by instead updating `test.sh` to check the list of remote repository tags.
This looks to be working well after merge so I would like to suggest we backport it to `release-3.5`.
=> Backport fix to e2e release version identifcation

Documentation/contributor-guide/roadmap.md, README.md
Add a roadmap so that all contributors and users know the priorities of each major or minor release. Note that etcd community will continue to focus on technical debt over the next few major or minor releases.
=> Documentation: add roadmap

server/embed/config_tracing.go
This is the latest semconv package used in etcd's dependencies. Switching to that version reduces the overall package dependencies of the project (and helps downstream projects which track this, e.g. Kubernetes).
=> server: switch to semconv v1.17.0

tests/robustness/failpoints.go
If the cluster serves requests slowly, the database has few revision number and then Compact won't trigger BatchCommit. Add a loop to check the last revision is big enough to trigger panic.
REF: https://github.com/etcd-io/etcd/pull/14691#issuecomment-1649473554
=> tests/robustness: enhance compact failpoint

pkg/flags/unique_urls.go, pkg/flags/unique_urls_test.go
From the name of func 'UniqueURLsFromFlag', we can tell that UniqueURLs'uss should not have duplicates. The current implemention of UniqueURLs'Set has a bug to make it unique. This PR fixes it.
Please take a look.
=> pkg/flags: fix UniqueURLs'Set to remove duplicates in UniqueURLs'uss

pkg/flags/unique_urls.go, pkg/flags/unique_urls_test.go
Backport: https://github.com/etcd-io/etcd/pull/16272
Fix UniqueURLs'Set to remove duplicates in UniqueURLs'uss.
Fixes: https://github.com/etcd-io/etcd/issues/16307
TODO: changelog for 3.5 after this pr is merged.
=> [3.5] Backport #16272 to 3.5

pkg/flags/unique_urls.go, pkg/flags/urls_test.go
Backport: https://github.com/etcd-io/etcd/pull/16272
Fix UniqueURLs'Set to remove duplicates in UniqueURLs'uss.
Fixes: https://github.com/etcd-io/etcd/issues/16307
TODO: changelog for 3.4 after this pr is merged.
=> [3.4] Backport #16272 to 3.4

server/storage/backend/batch_tx.go, server/storage/backend/read_tx.go, server/storage/schema/confstate_test.go
Simple is better. Why have `Lock` on read transaction, why have `Rlock` on write transaction. It's bad Go practice to share interface between objects that interpret it differently.  `ReadTxn` and `BatchTxn` serve different purpose with different side effect, they should not share the same interface.
=> server: Remove Lock/Unlock from ReadTx 

.github/ISSUE_TEMPLATE/test-flake.yml
Automate the `area/testing` triage label for flake issues.  We had a few recently and currently it's added manually.
=> Automate adding area/testing label to flake issues

.github/workflows/e2e-arm64-template.yaml, .github/workflows/e2e.yaml, .github/workflows/grpcproxy.yaml, .github/workflows/tests-arm64-nightly.yaml, .github/workflows/tests-arm64-template.yaml, .github/workflows/tests.yaml, scripts/test.sh
Use [data race detection](https://go.dev/doc/articles/race_detector) by default for all `amd64` and `arm64` tests.  This is already happening for `amd64` although may have been unexpected.  This pull request aligns both `arm64` so both platforms are treated the same.
Also removes now extraneous parameters in github workflows to centralise the control for race to the defaults defined in `scripts/test.sh`.
Fixes #16315
=> Simplify go data race detection controls

etcdutl/snapshot/v3_snapshot.go, server/auth/store.go, server/etcdserver/cindex/cindex.go, server/storage/backend/batch_tx.go, server/storage/backend/hooks.go, server/storage/backend/hooks_test.go, server/storage/hooks.go, server/storage/mvcc/store.go, server/storage/schema/actions.go, server/storage/schema/actions_test.go, server/storage/schema/alarm.go, server/storage/schema/auth_roles.go, server/storage/schema/auth_roles_test.go, server/storage/schema/auth_users_test.go, server/storage/schema/cindex.go, server/storage/schema/confstate.go, server/storage/schema/lease.go, server/storage/schema/lease_test.go, server/storage/schema/migration.go, server/storage/schema/migration_test.go, server/storage/schema/schema.go, server/storage/schema/schema_test.go, server/storage/schema/version.go
Followup on https://github.com/etcd-io/etcd/pull/16320 (will remove the first commit when merged)
Splitting the interfaces to ensure unsafe functions do get lock if they don't need to.
=> Separate Writer interface from BatchTx interfaces

client/v3/experimental/recipes/barrier.go, tests/integration/clientv3/experimental/recipes/v3_barrier_test.go
The unexpected blocking after release() can be reproduced with the following codes:
```
func TestBarrier2(t *testing.T) {
var cli *v3.Client
var err error
if cli, err = v3.New(v3.Config{Endpoints: []string{"10.117.190.125:2379"}, DialTimeout: 5 * time.Second}); err != nil {
t.Fatal(err)
}
defer cli.Close()
b := recipe.NewBarrier(cli, "test-barrier")
if err := b.Hold(); err != nil {
t.Fatalf("could not hold barrier (%v)", err)
}
if err := b.Hold(); err == nil {
t.Fatalf("able to double-hold barrier")
}
// this is the key step to reproduce the problem, put a random key to move the revision forward
if _, err := cli.Put(cli.Ctx(), "x", ""); err != nil {
t.Errorf("could not put x, err:%v", err)
}
donec := make(chan struct{})
stopc := make(chan struct{})
defer close(stopc)
for i := 0; i < 5; …
```
=> clientv3: fix barrier.Wait() still block after barrier.Release()

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
issue #16343 : Update golang patch version to latest 1.19.12 release
backport prs:  #16352 #16353
=> Changelog: modify dependencies bumping go to 1.19.12

.github/workflows/e2e.yaml, .github/workflows/tests.yaml, Makefile
This pull request is a minimal backport to ensure the three Makefile recipes (`test-unit`, `test-integration` and `test-e2e-release`) required for our scheduled nightly `arm64` workflows are present in the `release-3.5` branch.
This is a requirement to be able to progress https://github.com/etcd-io/etcd/issues/16176 and will allow us to simplify these workflow templates as both `release-3.5` and `main` will be able to execute the same test commands.
Once this pull request is merged a follow-up pull request can be raised for `main` to simplify how test commands are specified in the following workflows:
- e2e-release - https://github.com/etcd-io/etcd/blob/main/.github/workflows/e2e-arm64-nightly.yaml#L19
- integration - https://github.com/etcd-io/etcd/blob/main/.github/workflows/tests-arm64- …
=> [3.5] Backport Makefile recipes for common test commands

.github/workflows/e2e-arm64-nightly.yaml, .github/workflows/e2e-arm64-template.yaml, .github/workflows/tests-arm64-nightly.yaml, .github/workflows/tests-arm64-template.yaml
Now that a minimal backport of command test command makefile recipes has been backported to `release-3.5` in https://github.com/etcd-io/etcd/pull/16340 we can go ahead with simplifying how test commands are managed in `main`.
We can further simplify some of the template files once all etcd test workflows adopt containers in https://github.com/etcd-io/etcd/issues/15956.
Progress towards https://github.com/etcd-io/etcd/issues/16176.
=> Streamline test commands between branches

etcdutl/etcdutl/backup_command.go, server/etcdserver/api/membership/cluster.go, server/etcdserver/api/membership/cluster_test.go, server/etcdserver/api/membership/storev2.go, server/etcdserver/cluster_util.go
Introducing method to create the snapshot in v2 format using v3 state. This is used by the backup command in this PR. Main snapshot path will be updated in subsequent PRs.
=> Add a method to export membership info to v2 store from RaftCluster

client/v3/client.go, client/v3/credentials/credentials.go, client/v3/credentials/credentials_test.go, client/v3/retry_interceptor_test.go, server/embed/etcd.go, server/etcdserver/api/v3rpc/grpc.go
Link to https://github.com/etcd-io/etcd/issues/15145
The [credentials.Bundle](https://github.com/grpc/grpc-go/blob/8f496b2a9544fdceadb26b0d45392b1022d232d9/credentials/credentials.go#L180) is an experimental API. We should try to remove the dependency on such experimental gRPC API. 
Actually transport credential and per GRPC credentials are two different things, no need to get them bind together.
=> clientv3: remove the experimental gRPC API grpccredentials.Bundle

server/etcdserver/apply/apply.go, server/etcdserver/apply/apply_auth.go, server/etcdserver/apply/apply_auth_test.go, server/etcdserver/apply/corrupt.go, server/etcdserver/apply/uber_applier.go, server/etcdserver/txn/txn.go, server/etcdserver/v3_server.go
cc @ahrtr @fuweid @jmhbnz @wenjiaswe 
Functions `Range`, `Put`, `DeleteRange` and `Txn` are public function that can be called by both applier and recursively by `Txn`. The top call is responsible for opening/closing a transaction and trace. This complicated code as depending type of call it needed to manage transaction or not. This PR simplifies the code by separating the recursive vs external call, thus creating a begining point for traces and transactions.
=> server: Separate internal txn functions for recursion and have public function create transaction and trace

.github/workflows/tests.yaml, Makefile
This pull request is a minimal backport to ensure the Makefile recipes (mainly `test-unit`, `test-integration` and `test-e2e-release`) used heavily in later release branches are also present in `release-3.4` branch.
This pull request completes our streamline test commands issue.  After this is merged all three active branches will be using the same Makefile recipes for our common test commands. This gives us a common way of abstracting away any minor differences in actual command executed between branches.
Fixes #16176
=>  [3.4] Backport Makefile recipes for common test commands

server/etcdserver/txn/txn.go
=> server: Separate txnRead from txnWrite

tests/robustness/linearizability_test.go, tests/robustness/traffic/traffic.go
Fixes https://github.com/etcd-io/etcd/issues/16370
Minimal QPS observed was 88.
=> tests/robustness: Reduce minimal QPS to eliminate flakes

etcdutl/snapshot/v3_snapshot.go, tests/e2e/cluster_downgrade_test.go, tests/e2e/ctl_v3_snapshot_test.go
=> Update etcdutl restore to create v2 snapshot from v3

etcd.conf.yml.sample
As discussed recently in #13506  it would be good if an example of the TLS protocol configuration was included in the sample etcd conf file
=> Add example config for TLS protocol version

tests/e2e/ctl_v3_auth_no_proxy_test.go
Recently the e2e test is flaky. I double checked two workflow failures, and both of them were pointing to the test case `TestCtlV3AuthCertCNWithWithConcurrentOperation`.  The [creating & deleting users goroutine](https://github.com/etcd-io/etcd/blob/e3a1d7fb3c713371a6f535346d7cb695d21f9f2f/tests/e2e/ctl_v3_auth_no_proxy_test.go#L88-L104) somehow couldn't finish its task in 30 seconds, but it's very close to success (already finished about 94 out of the 100 users).  
=> test: increase the timeout for the flaky test `TestCtlV3AuthCertCNWithWithConcurrentOperation`

Documentation/contributor-guide/dependency_management.md
The gRPC has already been bumped to v1.57.0, so the previous known issue is resolved.
=> Update dependency management guide

client/pkg/transport/sockopt.go, server/embed/config.go, server/embed/config_test.go
Currently in `main` it's possible to specify `--socket-reuse-port` and `--socket-reuse-address` in the config file. However, the same cannot be done for `release-3.5`.
An added complication is that the format for specifying these in the config file differs slightly from the command line parameter. Example below:
```yaml 
socket-options:
reuse-port: true
```
This backport addresses the immediate bug of configuration via file for these options not being possible in `release-3.5`.
In future, we should also consider aligning  the way the option name should be used in both the configuration file and the command flags.
Relates to #16399.
=> [3.5] Backport expose socket options

tests/e2e/cmux_test.go, tests/framework/e2e/curl.go
Redirect metrics data into file to reduce output.
Fix: #16422
=> tests/*: redirect metrics into file

contrib/raftexample/raft.go
When I adjust the value of `defaultSnapshotCount` to be smaller than `snapshotCatchUpEntriesN` in raftexample, because the `compactIndex` cannot be updated, a panic will occur when the snapshot is triggered for the second time, and the error is "panic: requested index is unavailable due to compaction".
This PR adds ErrCompacted error handling for Compact  (keep consistent with etcd server).
=> Handle ErrCompacted errors for Compact in raftexample

pkg/expect/expect_test.go, scripts/test.sh
Fixes for:
- Some bash versions can't take empty list variables and fail today with error like this:
```
PASSES="e2e" ./scripts/test.sh 
Running with --race=true --cpu=4
Starting at: Thu Aug 17 20:18:19 UTC 2023
'e2e' started at Thu Aug 17 20:18:19 UTC 2023
./scripts/test.sh: line 130: RUN_ARG[@]: unbound variable
make: *** [test-e2e] Error 1
```
- Unit tests which hardcode `tail` path fail with errors like this when it's present at different path:
```
--- FAIL: TestExpectFuncTimeout (0.51s)
expect_test.go:75: 
Error Trace:	/home/$USER/workspace/go/src/github.com/shyamjvs/etcd/pkg/expect/expect_test.go:75
Error:      	Error "unexpected exit code [143] after running [/bin/tail -f /dev/null]" does not contain "unexpected exit code [143] after running [/usr/bin/tail -f /dev/null]"
Test: …
```
=> Fix unit tests and make targets to not fail in some environments

pkg/ioutil/pagewriter_test.go, tests/e2e/watch_delay_test.go
Our nightly `arm64` integration tests have been flaking recently, on the `release-3.5` branch refer: https://github.com/etcd-io/etcd/actions/workflows/tests-arm64-nightly.yaml
One of these flakes relate to `TestPageWriterRandom` https://github.com/etcd-io/etcd/actions/runs/5908988147/job/16029062404. This test was improved recently in `main` under https://github.com/etcd-io/etcd/pull/16268.
Another flake is happening on `release-3.5` for `TestWatchDelay`. This was also fixed in `main` under https://github.com/etcd-io/etcd/pull/15636.
We should consider backporting these fixes to `release-3.5`.
=> [3.5] tests: Backport recent test flake fixes

tests/e2e/v2store_deprecation_test.go
Related to - https://github.com/etcd-io/etcd/issues/12913
Related to - https://github.com/etcd-io/etcd/pull/16418
=> Update test for v2 deprecation to verify membership match

.github/workflows/robustness-nightly.yaml, .github/workflows/robustness.yaml, tests/robustness/linearizability_test.go, tests/robustness/traffic/traffic.go
Use ubuntu-latest-8-cores to run lazyfs for robustness CI, since the lazyfs uses more CPU resources.
REF: https://github.com/etcd-io/etcd/issues/16370
=> *: enable ubuntu-latest-8-cores runner for amd64 robustness workflow

.github/workflows/e2e.yaml, .github/workflows/grpcproxy.yaml, .github/workflows/tests.yaml
Recent pull request https://github.com/etcd-io/etcd/pull/15927 introduced running our `arm64` ci jobs in containers to prevent leaking test processes causing issues on our self hosted runners.
The github runners we use for non arm64 ci jobs do not have the cleanup issue as our self hosted runners do, so it isn't absolutely necessary to migrate all workflows into containers. However we should consider doing it on the basis that we have one unified way to run etcd testing workflows.
Fixes: https://github.com/etcd-io/etcd/issues/15956
=> Run integration, e2e & grpcproxy tests in container.

server/etcdserver/server.go, server/etcdserver/server_test.go, server/etcdserver/snapshot_merge.go
e2e test is TestDowngradeUpgradeClusterOf3WithSnapshot
=> Update to generate v2 snapshot from v3 state

tests/e2e/cluster_downgrade_test.go
Otherwise the following snap.Data may run into nil pointer panic.
=> test: verify snap.Load() is sucessful

tests/e2e/cluster_downgrade_test.go
=> Add membership changes to downgrade tests

server/storage/wal/wal_test.go
We recently updated to golang 1.20.  This golang release deprecated `math/rand.Seed` (which in most cases can now be removed) and `math/rand.Read` in favor of `crypto/rand.Read`, refer: https://go.dev/doc/go1.20
In #16447 we removed instances of `math/rand.Seed`.
After scanning through the codebase this pull request updates the one instance I could find of us using `math/rand.Read` and replaces it with `crypto/rand.Read`.
=> Use crypto/rand.Read instead of deprecated math/rand.Read

server/etcdserver/server.go
Related to https://github.com/etcd-io/etcd/pull/16418
=> Preserve the order of steps done for snapshot

Documentation/contributor-guide/dependency_management.md
Recently in https://github.com/etcd-io/etcd/issues/16393 we updated etcd to a new Go minor version and also briefly discussed some guidelines for how the etcd project should aim to stay up to date moving forward.
This pull request summarizes the discussion in the issue into a basic and very brief initial policy we can use to guide future decisions.
<br />
Note: Also addressed some `markdownlint` warnings for the doc so just review the policy commit for the meaningful piece.
=> Document project golang version policy

pkg/expect/expect.go, pkg/expect/expect_test.go, tests/e2e/corrupt_test.go, tests/e2e/ctl_v3_auth_test.go, tests/e2e/ctl_v3_defrag_test.go, tests/e2e/ctl_v3_grpc_test.go, tests/e2e/ctl_v3_kv_test.go, tests/e2e/ctl_v3_lease_test.go, tests/e2e/ctl_v3_lock_test.go, tests/e2e/ctl_v3_member_test.go, tests/e2e/ctl_v3_move_leader_test.go, tests/e2e/ctl_v3_role_test.go, tests/e2e/ctl_v3_snapshot_test.go, tests/e2e/ctl_v3_test.go, tests/e2e/discovery_test.go, tests/e2e/discovery_v3_test.go, tests/e2e/etcd_config_test.go, tests/e2e/etcd_release_upgrade_test.go, tests/e2e/gateway_test.go, tests/e2e/metrics_test.go, tests/e2e/utl_migrate_test.go, tests/e2e/v2store_deprecation_test.go, tests/e2e/v3_cipher_suite_test.go, tests/e2e/v3_curl_maxstream_test.go, tests/e2e/v3_curl_test.go, tests/framework/e2e/curl.go, tests/framework/e2e/etcd_process.go, tests/framework/e2e/etcdctl.go, tests/framework/e2e/lazyfs.go, tests/framework/e2e/util.go
Currently we only support exact string match on the response (e.g. curl response, and process output). But in some cases, the response may not be a fixed string. One example is discussed in https://github.com/etcd-io/etcd/pull/16454, there may be random spaces in the grpc-gateway v2 response.
So we need to support match the response based on a regular expression.
=> test: support regular expression matching on the response

tests/e2e/v3_curl_kv_test.go, tests/e2e/v3_curl_test.go
I will refactor & add new test cases in a following PR. This PR just moves all KV related test cases into a separate file.
Also linked to https://github.com/etcd-io/etcd/pull/16454
=> test: move all KV related RESTful APIs into a separate test file

tests/e2e/v3_curl_auth_test.go, tests/e2e/v3_curl_test.go
This PR moves the auth related curl test into a separate file. I will add more auth related test cases in a following PR.
Link to https://github.com/etcd-io/etcd/pull/16454
=> test: move all auth related test cases into a separate test file

tests/e2e/v3_cipher_suite_test.go, tests/e2e/v3_curl_auth_test.go, tests/e2e/v3_curl_kv_test.go, tests/e2e/v3_curl_lease_test.go, tests/e2e/v3_curl_maintenance_test.go, tests/e2e/v3_curl_maxstream_test.go, tests/e2e/v3_curl_test.go
As discussed in https://github.com/etcd-io/etcd/pull/16511#issuecomment-1702499475 we proposed a new naming standard for our v3 RESTful tests.
This is a quick maintenance pr to apply that new standard to the rest of the test cases so we don't have any inconsistency.
```bash
james  ~  D  etcd   maintain-testc.. 
➜ grep -Riol  TestV3Curl | xargs sed -i 's/TestV3Curl/TestCurlV3/g'
james  ~  D  etcd   maintain-testc.. 
➜ grep -Riol  testV3Curl | xargs sed -i 's/testV3Curl/testCurlV3/g'
james  ~  D  etcd   maintain-testc.. 
➜ grep -Riol  TestV3Curl | wc -l
0
```
=> Maintain a consistent naming standard for curlv3 tests

tests/e2e/ctl_v3_test.go, tests/e2e/v3_curl_lease_test.go, tests/e2e/v3_curl_maintenance_test.go, tests/e2e/v3_curl_test.go
v2 API has already been deprecated. It doesn't make sense to maintain an apiPrefix in the test cases. So cleanup the apiPrefix.
Link to https://github.com/etcd-io/etcd/issues/16507
=> test: remove apiPrefix and withApiPrefix

tests/integration/v3_watch_test.go
Fix https://github.com/etcd-io/etcd/issues/16416
The case may be blocked on sending progress notification, so may not be able to exit the goroutine.
=> test: de-flake test case TestV3WatchProgressOnMemberRestart

tests/common/member_test.go
Get memberlist immediately before each time checking the members, otherwise it always checks the member on a static list of members.
```
member_test.go:53: 
Error Trace:	/__w/etcd/etcd/tests/common/member_test.go:53
/__w/etcd/etcd/tests/framework/testutils/execute.go:38
/__t/go/1.20.7/x64/src/runtime/asm_amd64.s:1598
Error:      	Condition never satisfied
Test:       	TestMemberList/PeerTLS
```
See https://github.com/etcd-io/etcd/actions/runs/6093660649/job/16533696393
=> test: fix the flaky test case `TestMemberList`

server/storage/mvcc/kvstore_test.go
The HashByRev-goroutines exit since receive `donec` notification. The Check-computed-hashes goroutine could not have chance to get the hash result and be stuck forever. We should add case for donec when we wait for hash result.
Closes: #16266
=> server/storage/mvcc: deflake TestHashKVWhenCompacting

tests/e2e/cmux_test.go, tests/e2e/v2_curl_test.go
Our `arm64` e2e nightly tests have failed for six days in a row for the `release-3.5` branch, so I am looking into that, refer: https://github.com/etcd-io/etcd/actions/workflows/e2e-arm64-nightly.yaml  
While investigating I noticed we haven't backported the great work @fuweid did in https://github.com/etcd-io/etcd/pull/16439 so in 3.5 the logs are still full of spam and have to be downloaded to see issues.
Let's backport the metrics redirection to make life easier.
=> [3.5] Backport redirecting cmux test metrics data into file to reduce output

pkg/ioutil/pagewriter_test.go
The PageWriter has cache buffer so that it doesn't call the Writer until the cache is almost full. Since the data's length is random, the pending bytes should be always less than cache buffer size, instead of page size.
Fix: #16255
(cherry picked from commit fddd1add52b33649a99d7f756404924138344a10 #16268 )
=> [3.4] pkg/ioutil: deflake TestPageWriterRandom

server/storage/backend/tx_buffer.go, server/storage/backend/tx_buffer_test.go
=> server: optimizing memory overhead of copy operation in ConcurrentReadTxn

tests/e2e/v3_curl_lock_test.go
Also link to https://github.com/etcd-io/etcd/pull/16454
=> test: add test case to cover lock restful APIs

tests/e2e/cmux_test.go
Our nightly `arm64` e2e tests have been failing this week ever since we adopted Debian 12 in https://github.com/etcd-io/etcd/pull/16516.
As mentioned in https://github.com/etcd-io/etcd/pull/16513#issuecomment-1702385175 http 1.0 is no longer supported in Debian 12.  We've removed this version from `TestConnectionMultiplexing` already in `main`.
This pull request backports the change to `release-3.5` so our nightly `arm64` e2e tests that run in a Debian 12 container on our self hosted runners will return to green.
=> [3.5] Backport removing obsolete http 1.0 version for cmux tests

tests/e2e/v3_curl_election_test.go, tests/e2e/v3_curl_watch_test.go
also link to https://github.com/etcd-io/etcd/pull/16454
=> test: split watch and election tests to separate files

client/pkg/transport/tls.go, client/pkg/transport/tls_test.go
Backport: #13824
Closes: #13810
> NOTE: There are too many commits in the original pull request. I can't just use cherry-pick -xs to carry it.
=> [3.5] Fix panic in etcd validate secure endpoints

Makefile
Ensure that we can update the Golang patch version for release-3.5 by only updating a single file.
#16560
=> fix:Ensure that go version is only defined in one file for release-3.5

tests/e2e/v3_curl_election_test.go
also link to https://github.com/etcd-io/etcd/pull/16454
=> test: add test case to cover all election REST APIs

tests/e2e/v3_curl_auth_test.go, tests/e2e/v3_curl_election_test.go, tests/e2e/v3_curl_kv_test.go
Link to https://github.com/etcd-io/etcd/pull/16454
Random spaces may be inserted between fields in a marshalled json response in grpc-gateway v2, so simply the expected output to make it work for both v1 and v2.
=> test: simply the expected output for some curl test cases

OWNERS
This pull request proposes a layout for the `OWNERS` file we need to add to each non archived subproject under the `etcd-io` github organisation as part of the creation of sig-etcd.
Refer to OWNERS documentation: https://www.kubernetes.dev/docs/guide/owners
Note: Once the sig comes online fully and we shift to managing org membership through the kubernetes org bot then we need to consider a follow-up pull request to prune out the old `MAINTAINERS` file approach.
=> Add OWNERS file for etcd

client/pkg/transport/keepalive_listener.go, client/pkg/transport/listener.go, etcdctl/main_test.go, etcdutl/main_test.go, scripts/test.sh, server/etcdserver/bootstrap_test.go, server/main_test.go, server/storage/wal/wal.go, tests/robustness/validate/operations.go
=> *: fix nakedret lint

CHANGELOG/CHANGELOG-3.6.md
Link to https://github.com/etcd-io/etcd/pull/16595 and https://github.com/etcd-io/etcd/pull/16594
=> Update 3.6 changelog to include the grpc-gateway upgrading from v1 to v2 and golang upgrading to 1.21

Makefile, scripts/test.sh, server/lease/lessor_bench_test.go, tests/common/compact_test.go, tests/e2e/corrupt_test.go, tests/e2e/ctl_v3_member_test.go, tests/e2e/v3_curl_cluster_test.go, tests/framework/e2e/cluster.go, tests/integration/v3_auth_test.go
Part of #15549
```bash
PASSES="ineffassign" ./scripts/test.sh
Running with --race
Starting at: Mon Sep 18 12:40:24 HKT 2023
'ineffassign' started at Mon Sep 18 12:40:24 HKT 2023
% (cd tools/mod && 'go' 'install' 'github.com/gordonklaus/ineffassign')
% (cd api && '/home/fuwei/go/bin/ineffassign' './...')
% (cd tools/mod && 'go' 'install' 'github.com/gordonklaus/ineffassign')
% (cd pkg && '/home/fuwei/go/bin/ineffassign' './...')
% (cd tools/mod && 'go' 'install' 'github.com/gordonklaus/ineffassign')
% (cd client/pkg && '/home/fuwei/go/bin/ineffassign' './...')
% (cd tools/mod && 'go' 'install' 'github.com/gordonklaus/ineffassign')
% (cd client/internal/v2 && '/home/fuwei/go/bin/ineffassign' './...')
% (cd tools/mod && 'go' 'install' 'github.com/gordonklaus/ineffassign')
% (cd client/v3 && …
```
=> *: fix ineffassign lint

Makefile, api/v3rpc/rpctypes/metadatafields.go, client/v3/experimental/recipes/double_barrier.go, client/v3/lease.go, client/v3/maintenance.go, pkg/traceutil/trace.go, pkg/traceutil/trace_test.go, scripts/test.sh, server/auth/store_test.go, server/etcdserver/txn/txn.go, server/etcdserver/v3_server.go, server/proxy/grpcproxy/util.go, tests/framework/e2e/etcd_process.go, tests/integration/clientv3/lease/leasing_test.go, tests/integration/lazy_cluster.go, tests/robustness/report/client.go, tools/.golangci.yaml, tools/mod/go.mod, tools/mod/go.sum, tools/mod/tools.go
Changed TraceKey/StartTimeKey/TokenFieldNameGRPCKey to struct{} to follow the correct usage of context. Similar patch to #8901.
~~And this patch also copies the tools/.golangci.yaml and run the linters for which we have already fixed. 
The temp .golangci.yaml will be removed when we fixes all the linters' issues.~~
Added `lint_pass` in scripts/test.sh to run the golangci linters for each modules. And disable no working linters in the global golangci.yaml and enable them by #16610.
Part of #16610
=> *: fix staticcheck lint

pkg/stringutil/rand_test.go
From the algorithm below, 'ss' should be sorted.
Also removes 'fmt.Println', because the idiomatic tests would not print.
=> pkg/stringutil: sort 'ss' in TestUniqueStrings

.github/workflows/e2e.yaml, server/etcdserver/api/membership/cluster.go, server/etcdserver/api/membership/cluster_test.go, server/etcdserver/server.go, server/etcdserver/server_test.go, tests/e2e/ctl_v3_member_test.go, tests/framework/e2e/cluster.go
The first commit added a test case, basically which always fails,
```
2023-09-27T16:26:55.3567789Z     ctl_v3_member_test.go:128: 
2023-09-27T16:26:55.3568428Z         	Error Trace:	/__w/etcd/etcd/tests/e2e/ctl_v3_member_test.go:128
2023-09-27T16:26:56.3453793Z         	            				/__t/go/1.21.1/x64/src/runtime/asm_amd64.s:1650
2023-09-27T16:26:56.3455109Z         	Error:      	Not equal: 
2023-09-27T16:26:56.3456321Z         	            	expected: 1
2023-09-27T16:26:56.3457394Z         	            	actual  : 2
```
After applying the patch in the second commit, then the issue is resolved.
The third commit is fixing the broken unit test in server_test.go, and is coming from @geetasg 's PR …
=> Fix memberList may return incorrect intermediate results right after bootstrap

CHANGELOG/CHANGELOG-3.6.md
Updated CHANGELOG to reflect removal of `etcdutl backup`  from PR: https://github.com/etcd-io/etcd/pull/16662
=> Documented removal of etcdutl backup in CHANGELOG-3.6

.github/workflows/static-analysis.yaml, tools/.golangci.yaml
The yamllint is different from yamlfmt. We disable the yamlint on comment.
This patch is to check the diff after make-fix. Maybe we can consider to use `yamlfmt -lint` instead of yamllint
REF: https://github.com/etcd-io/etcd/pull/16269#discussion_r1341239430
=> .github: ensure there is no change after make-fix

tests/e2e/ctl_v3_member_test.go
FIx https://github.com/etcd-io/etcd/pull/16658#discussion_r1341959776
=> test: fix the TestCtlV3ConsistentMemberList: set the wait-cluster-ready-timeout as 1ns

tests/e2e/corrupt_test.go, tests/e2e/ctl_v3_test.go, tests/e2e/etcd_mix_versions_test.go, tests/e2e/v3_cipher_suite_test.go, tests/e2e/v3_curl_maxstream_test.go, tests/e2e/watch_delay_test.go, tests/framework/e2e/cluster.go, tests/robustness/failpoints.go, tests/robustness/linearizability_test.go
Refactor in preparation for randomizing configuration in robustness tests for https://github.com/etcd-io/etcd/issues/16673
=> Reuse embed.Config in e2e cluster config

tests/e2e/ctl_v3_kv_test.go
=> Avoid timing out and provide a proper error in TestCtlV3GetFormat test

tests/robustness/validate/validate_test.go, tests/robustness/validate/watch.go
cc @ahrtr 
Part of https://github.com/etcd-io/etcd/issues/16693
=> Fix watch validation assuming that client requesting older watch revision

Documentation/infra-guide/arm64-infra.md
As noticed in https://github.com/cncf/cluster/issues/242 we have a typo for a github handle in our infra admins table which caused some confusion so let's fix that.
=> Fix typo in ci infra admins table

scripts/test.sh
Part of #15549 
The markdown_you_pass was introduced by https://github.com/etcd-io/etcd/pull/7416
But in the etcd-io org, I don't see any documents relative to [eschew-you](https://github.com/coreos/docs/blob/master/STYLE.md#eschew-you). 
The comment like `Get your pull request reviewed` seems reasonable.
This pr is to clean up the `markdown_you_pass`.
=> scripts: remove the markdown_you_pass

Makefile, functional/scripts/docker-local-agent.sh, functional/scripts/docker-local-tester.sh
Following up on #16729.
Could be a good idea to fetch the go version from .go-version like it is done in the main branch to simplify go version bumps on 3.4 in the future.
=> [3.4] etcd: upgrade go version to 1.20.9 in Makefile & scripts

server/embed/serve.go, tests/e2e/watch_delay_test.go
Introduction of round robin https://github.com/golang/net/commit/120fc906b30bade8c220769da77801566d7f4ec8 Added in v0.10.0 https://github.com/golang/net/compare/v0.10.0...v0.11.0
Fixes https://github.com/etcd-io/etcd/issues/15402 on main branch
=> Return to default write scheduler since golang.org/x/net@v0.11.0 started using round robin

.github/workflows/e2e-arm64-template.yaml, .github/workflows/e2e.yaml, .github/workflows/grpcproxy.yaml
E2e tests has been flaky, with failfast and 2 scenarios tests are twice as fragile. Any early failure of one of the scenarios cases second to be canceled. Retryign always require running both scenarios.
Intead let's just wait as in other tests allowing us to retry just the scenario that failed
=> Continue on e2e failure

server/embed/serve.go, tests/e2e/watch_delay_test.go
Introduction of round robin https://github.com/golang/net/commit/120fc906b30bade8c220769da77801566d7f4ec8 Added in v0.10.0 https://github.com/golang/net/compare/v0.10.0...v0.11.0
=> [v3.5] Return to default write scheduler since golang.org/x/net@v0.11.0 started using round robin

tests/e2e/cmux_test.go, tests/e2e/watch_delay_test.go, tests/framework/e2e/cluster.go, tests/framework/e2e/cluster_test.go
Part of https://github.com/etcd-io/etcd/issues/16673 to randomize etcd configuration we need to expand coverage of flags that can be provided in e2e tests. Instead of manually transforming embed.Config struct fields, we can use flagset to automatically generate flags.
=> Dynamically generate flags passed to etcd binary

server/etcdserver/api/etcdhttp/health.go, server/etcdserver/api/etcdhttp/health_test.go, server/proxy/grpcproxy/health.go
Part of #16007 
Discovered by reviewing https://github.com/etcd-io/etcd/pull/16651
@siyuanfoundation @serathius
=> http health check bug fixes

tests/e2e/etcd_config_test.go
The proc.Stop just sends the SIGTERM to etcd server. The etcd server needs time to teardown. If we don't wait for it, the etcd server will hold the port and then next test case, like TestGrpcProxyAutoSync, will fail to listen on the port 20000.
```bash
file_/__w/etcd/etcd/tests/fixtures/server.crt_--peer-key-file_/__w/etcd/etcd/tests/fixtures/server.key.insecure_--cert-file_/__w/etcd/etcd/tests/fixtures/server2.crt_--key-file_/__w/etcd/etcd/tests/fixtures/server2.key.insecure_--tls-min-version_TLS1.2_--tls-max-version_TLS1.3) (32856): {"level":"info","ts":"2023-10-13T06:12:32.718845Z","caller":"embed/etcd.go:394","msg":"closing etcd server","name":"e1","data-dir":"/tmp/TestEtcdTLSVersion284993522/001","advertise-peer-urls":["https://127.0.0.1:20000"],"advertise-client-urls":["https://0.0.0 …
```
=> tests: deflake TestEtcdTLSVersion

.github/workflows/static-analysis.yaml, Documentation/contributor-guide/branch_management.md, Documentation/contributor-guide/community-membership.md, Makefile, scripts/test.sh, security/README.md
Part of #15549 
It's trying to re-enable the markdown_marker checker in the repo because we have the old issue https://github.com/etcd-io/etcd/issues/7123. 
However, the marker tool doesn't support the github-like relative path render. 
The `/absolute-path` is useful and easier to be maintained in the github repo than `../../`.
```markdown
This is [MAINTAINER](/MAINTAINER) file.
```
Filed to https://github.com/crawford/marker/pull/23 and hope @crawford can give some inputs.
CI Result: https://github.com/etcd-io/etcd/actions/runs/6446242086/job/17501156794?pr=16708#step:9:459
```
'markdown_marker' started at Sun Oct  8 07:23:06 UTC 2023
% 'marker' '--skip-http' '--root' './Documentation'
'markdown_marker' PASSED and completed at Sun Oct  8 07:23:06 UTC 2023
SUCCESS
```
Please read …
=> *: enable markdown_marker checker

server/etcdserver/api/etcdhttp/health.go
From the Go specification (https://go.dev/ref/spec#For_range):
> "1. For a nil slice, the number of iterations is 0."
`len` returns 0 if the slice or map is `nil` (https://pkg.go.dev/builtin#len). Therefore, checking `len(v) > 0` around a loop is unnecessary.
=> etcdserver: remove redundant `len` check in health check

tests/robustness/validate/operations.go, tests/robustness/validate/validate.go, tests/robustness/validate/validate_test.go, tests/robustness/validate/watch.go
It doesn't make sense to report watch failure if key value operations are not linearizable.
cc @ahrtr
=> Refactor and reorder validation to avoid reporting multiple correlated failures

api/go.mod, api/go.sum, client/v3/go.mod, client/v3/go.sum, etcdctl/go.mod, etcdctl/go.sum, etcdutl/go.mod, etcdutl/go.sum, go.mod, go.sum, pkg/go.mod, pkg/go.sum, raft/go.mod, raft/go.sum, server/embed/etcd.go, server/go.mod, server/go.sum, tests/go.mod, tests/go.sum
Split gRPC-go dependency update in release-3.5 into multiple PRs based on https://github.com/etcd-io/etcd/pull/16591#issuecomment-1724059411. 
Backport #14125
=> [3.5] Bump grpc-go to1.47 (and fix the connection-string format)

server/etcdserver/api/etcdhttp/health.go, server/etcdserver/api/etcdhttp/health_test.go, server/proxy/grpcproxy/health.go
https://github.com/etcd-io/etcd/issues/16007
This is a prototype for adding livez/readyz support to etcd ([design doc](https://docs.google.com/document/d/1SkzmO4RT_GI9YhT0dw4a6nEwKVCciwrwbCDxK0D7ASM/edit?usp=sharing)). 
This pr is setting up the general structure for livez/ready checks, with only 2 simple checks implemented.
=> Add livez and readyz for etcd

etcdutl/snapshot/v3_snapshot.go
```
./bin/etcdutl snapshot restore a.snap --data-dir=./a-cluster
2023-06-13T16:09:36+08:00       info    snapshot/v3_snapshot.go:248     restoring snapshot      {"path": "a.snap", "wal-dir": "a-cluster/member/wal", "data-dir": "./a-cluster", "snap-dir": "a-cluster/member/snap", "stack": "go.etcd.io/etcd/etcdutl/v3/snapshot.(*v3Manager).Restore\n\tgo.etcd.io/etcd/etcdutl/v3/snapshot/v3_snapshot.go:254\ngo.etcd.io/etcd/etcdutl/v3/etcdutl.SnapshotRestoreCommandFunc\n\tgo.etcd.io/etcd/etcdutl/v3/etcdutl/snapshot_command.go:147\ngo.etcd.io/etcd/etcdutl/v3/etcdutl.snapshotRestoreCommandFunc\n\tgo.etcd.io/etcd/etcdutl/v3/etcdutl/snapshot_command.go:117\ngithub.com/spf13/cobra.(*Command).execute\n\tgithub.com/spf13/cobra@v1.1.3/command.go:856\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tgithub.c …
```
=> remove stack log when restore snapshot

contrib/mixin/dashboards/variables.libsonnet
Fix mixin cluster parameter otherwise generated mixins looks like this:
```json
{"type":"prometheus","uid":"${datasource}"},"label":"cluster","name":"job","query":"label_values(etcd_server_has_leader{job=~\".*etcd.*\"}, job)","refresh":2,"type":"query"}]},"time":{"from":"now-15m","to":"now"},"timezone": "`}}{{ .Values.grafana.defaultDashboardsTimezone }}{{`","title":"etcd","uid":"c2f4e12cdf69feb95caa41a5a1b423d9"}`}}
```
where name is job when the variable name used in dashboard queries is cluster.
Issue came up here: https://github.com/prometheus-community/helm-charts/pull/3880#issuecomment-1765190231
=> Fix cluster variable in mixins

embed/serve.go, tests/e2e/watch_delay_test.go
Introduction of round robin https://github.com/golang/net/commit/120fc906b30bade8c220769da77801566d7f4ec8 Added in v0.10.0 https://github.com/golang/net/compare/v0.10.0...v0.11.0
Closes https://github.com/etcd-io/etcd/issues/15402
=> [3.4] Return to default write scheduler since golang.org/x/net@v0.11.0 started using round robin

api/v3rpc/rpctypes/error.go, server/etcdserver/api/rafthttp/http.go, server/etcdserver/api/rafthttp/stream.go, server/etcdserver/api/rafthttp/util.go, server/etcdserver/corrupt.go, server/etcdserver/corrupt_test.go, tests/e2e/cluster_test.go, tests/e2e/corrupt_test.go, tests/integration/hashkv_test.go
Backport of https://github.com/etcd-io/etcd/pull/15924 to release-3.5
=> [release-3.5] etcdserver: add cluster id check for hashKVHandler

server/etcdserver/server.go, tests/e2e/corrupt_test.go, tests/e2e/discovery_v3_test.go, tests/e2e/http_health_check_test.go, tests/framework/config/client.go, tests/framework/e2e/cluster.go, tests/framework/e2e/etcd_process.go, tests/framework/e2e/etcdctl.go, tests/framework/integration/integration.go
=> add existing http health check handler e2e test

CHANGELOG/CHANGELOG-3.5.md
Ref: https://github.com/etcd-io/etcd/pull/16790
=> CHANGELOG-3.5.md: Upgrade gRPC to 1.58.3

Documentation/dev-guide/grpc_naming.md, clientv3/integration/naming/endpoints_test.go, clientv3/integration/naming/resolver_test.go, clientv3/naming/doc.go, clientv3/naming/endpoints/endpoints.go, clientv3/naming/endpoints/endpoints_impl.go, clientv3/naming/endpoints/internal/update.go, clientv3/naming/resolver/resolver.go, etcdserver/api/rafthttp/transport.go, go.mod, go.sum, test
Part of https://github.com/etcd-io/etcd/issues/16740
Backport https://github.com/etcd-io/etcd/pull/12397 and https://github.com/etcd-io/etcd/pull/12614 as the first step..
Note: https://etcd.io/docs/v3.4/dev-guide/grpc_naming/ doc needs to be reflected before https://github.com/etcd-io/etcd/issues/16751 is cut. 
This will upgrade gRPC to v1.29.1 and naming API change. 
=> [3.4]  Upgrade grpc-go to 1.29.1 and Backport "Introduce grpc-1.30+ compatible client/v3/naming API."

.github/workflows/e2e-arm64-nightly.yaml, .github/workflows/e2e-arm64-template.yaml, .github/workflows/robustness-nightly.yaml, .github/workflows/tests-arm64-template.yaml, Documentation/infra-guide/arm64-infra.md
Switch over to managed Arm64 hosts
The service is provided by actuated.dev, and **sponsored by both Ampere and the CNCF**.
This change switches over from 2x self-managed runners where side effects are possible between builds, to a pool of servers where each build runs in an isolated VM.
Benefits to the etcd maintainers and community:
* Securely isolated, immutable environments for every build
* No more server maintenance, reduced documentation and process
* Support from an externally contracted team, much more efficient use of CNCF credits.
* Potential to enable builds for each PR instead of just nightly
@dims and other etcd maintainers have been briefed on the discussion / plans via Slack.
Please feel free to ask questions here too.
=> Switch over to managed Arm64 hosts

.github/workflows/robustness-nightly.yaml
Until we can resolve issues with fuse for new actuated runner.
Refer: https://github.com/etcd-io/etcd/pull/16824
=> Revert runner change for main robustness nightly

CHANGELOG/CHANGELOG-3.6.md, server/config/config.go, server/embed/config.go, server/embed/etcd.go, server/etcdmain/help.go, server/etcdserver/api/v3client/v3client.go, server/etcdserver/api/v3rpc/grpc.go, server/etcdserver/api/v3rpc/health.go, server/etcdserver/api/v3rpc/maintenance.go, tests/e2e/failover_test.go, tests/framework/e2e/cluster.go, tests/framework/integration/cluster.go
Trying to fix https://github.com/kubernetes/kubernetes/issues/93280 on etcd side since etcd is part of the kubernetes sigs. 
Before failure rate is around 33%
```
v3_failover_test.go:101: etcd client failed to fail over, error (context deadline exceeded)
v3_failover_test.go:103: request failure rate is 33.59%, traffic volume success 172 requests, total 259 requests
```
After failure rate is 0%
```
v3_failover_test.go:103: request failure rate is 0.00%, traffic volume success 2116 requests, total 2116 requests
```
```
2023-07-20T22:18:20.243Z [[core] [Channel #19 SubChannel #20] Subchannel picks a new address "unix:localhost:m0" to connect]
2023-07-20T22:18:20.243Z [[balancer] base.baseBalancer: handle SubConn state change: 0xc0006aad68, CONNECTING]
2023-07-20T22:18:20.243Z [[core] …
```
=> gRPC health server sets serving status to NOT_SERVING on defrag

clientv3/auth.go, clientv3/client.go, clientv3/credentials/credentials.go, clientv3/maintenance.go, etcdserver/v3_server.go
Part of https://github.com/etcd-io/etcd/issues/16740
Backport https://github.com/etcd-io/etcd/pull/12165 to release-3.4 as the first step to remove etcd dependence on gRPC old balancer API. 
https://github.com/etcd-io/etcd/pull/16800 should be merged first and this PR will be rebased on top of that. 
=> [3.4] Backport clientv3:get AuthToken gracefully without dialing gRPC with balancer API to get extra connection

clientv3/balancer/resolver/endpoint/endpoint.go, clientv3/client.go, clientv3/credentials/credentials.go
Break down of https://github.com/etcd-io/etcd/pull/16827
=> Backport [3.4] clientV3: simplify grpc dialer usage. Remove workaround #11184 after bumping grpc to 1.26.0.

contrib/recipes/barrier.go, integration/v3_barrier_test.go
Backports https://github.com/etcd-io/etcd/pull/16156 to fix the unexpected blocking when using Barrier.Wait(), e.g. NewBarrier(client, a).Wait() will block if key a is not existed but a0 is existed, but it should return immediately.
=> [3.4] Backport clientv3: remove v3.WithFirstKey() in Barrier.Wait()

server/etcdserver/api/v3rpc/grpc.go, server/etcdserver/api/v3rpc/health.go, server/etcdserver/api/v3rpc/maintenance.go, tests/e2e/failover_test.go
Follow up of https://github.com/etcd-io/etcd/pull/16278
=> v3rpc: online defrag toggles gRPC health server serving status

tests/e2e/http_health_check_test.go
Replace https://github.com/etcd-io/etcd/pull/16784 since its CI test failed.
Based on https://github.com/etcd-io/etcd/pull/16792#issuecomment-1771466727, this test should be merged first and #16792 will be rebased on top of it. 
@siyuanfoundation on the second commit. 
/cc @serathius
=> add livez readyz e2e tests

clientv3/client.go, clientv3/client_test.go
Breakdown of https://github.com/etcd-io/etcd/pull/16827 for https://github.com/etcd-io/etcd/issues/16740
Backports
- https://github.com/etcd-io/etcd/pull/13203
=> [3.4] backport client: call .Endpoints() in dial() in client/v3/client.go instead of accessing cfg.Endpoints directly

tests/framework/e2e/etcd_process.go, tests/robustness/failpoint/failpoint.go, tests/robustness/failpoint/gofail.go
Introduces a new failpoint to simulate an IO stall in the Raft loop during robustness tests. Extensible to check whether the stalled raft loop handled properly once https://github.com/etcd-io/etcd/issues/15247#issuecomment-1439508257 or similar fix merged.
=> Add robustness failpoint for IO stall in raft loop

pkg/osutil/osutil.go, pkg/osutil/osutil_test.go
The osutil.Unsetenv function is not used. Today, os.Unsetenv exists in the standard library, and is already used elsewhere in etcd. Removing this function could break things that may be importing this package. According to pkg.go.dev, it seems like the only thing is etcd forks, so it may be worth getting rid of this code. See:
https://pkg.go.dev/github.com/coreos/etcd/pkg/osutil?tab=importedby
Signed-off-by: Evan Jones <ej@evanjones.ca>
=> osutil: remove unused Unsetenv function

etcdutl/README.md
Contribfest issue: [16160](https://github.com/etcd-io/etcd/issues/16160)
the 'bump-revision' and 'mark-compated' flags were added to `snapshot restore` and required documentation.
Signed off by Stephen Pawulski spawulski@gmail.com
=> README.md: Add documentation for new snapshot restore flags

.github/workflows/robustness.yaml
Trial running a small robustness workflow for arm64 on every pull request KubeconNA 2023 Contribfest issue #16863
=> etcd-io tests: trial arm64 on every pr with a small robustness workflow

README.md
While working on https://github.com/etcd-io/website/issues/745 I noticed that the README in this repo should also be updated.
I'm not sure if this is the public wording we want to use, but I tried to base it off of the recent `Triage meeting thursday` email in etcd-dev.
=> Update README to callout the issue triage meeting

scripts/test.sh, server/etcdserver/api/v3discovery/discovery_test.go
Fixes typo in `test.sh` script and `golangci-lint` failure.
=> fix test script and lint

CONTRIBUTING.md
#16904 
fix spelling of word maintainer
add link to install protoc 3.20.3
add link to install yamllint
=> doc fix: add instruction to installling protoc and yamllint in contributing.md

tests/robustness/failpoint/gofail.go
When a sleep failpoint is injected into a single-node scenario, the cluster becomes unable to function during the execution of the sleep failpoint. This will lead to a decrease in qps, which may even fall below the minimum requirement if the sleep time is set to a long duration.
=> Exclude sleep failpoint from 1 node scenario

tests/robustness/options/cluster_options.go, tests/robustness/options/cluster_options_test.go, tests/robustness/options/server_config_options.go, tests/robustness/scenarios.go
Compared with With functions in e2e like e2e.WithSnapshotCount, the new With functions takes a list of possible field values, and randomly pick one when running the test. This would make the test cluster dynamic from a set of exploration space.
Added a script to auto generate the with functions for server config fields.
=> robustness test: add with functions of randomizable config params in robustness test

server/etcdserver/api/etcdhttp/health.go, server/etcdserver/api/etcdhttp/health_test.go
part of the work for https://github.com/etcd-io/etcd/issues/16007
label field consistent with [K8s health metrics](https://github.com/kubernetes/kubernetes/blob/02b0b79eda5a3d41a07a6f2965ee97d492e8b6b2/staging/src/k8s.io/component-base/metrics/prometheus/slis/metrics.go#L35)
=> etcdserver: add metric counters for livez/readyz health checks.

CHANGELOG/CHANGELOG-3.5.md
Update 3.5 changelog for fixes backported to 3.5 in [PR](https://github.com/etcd-io/etcd/pull/16946)
=> changelog: Update fix for CVE-2023-47108

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
[Fix #16891(Comment)](https://github.com/etcd-io/etcd/issues/16891)
=> Update 3.4 & 3.5 changelog.

.github/workflows/gh-workflow-approve.yaml
Allow to run GitHub workflows for Pull Requests that have the ok-to-test label.
Fixes #16956 
=> github workflow: enable workflow approval

README.md, security/security-release-process.md
This pr fixes the slack link for sig-etcd in readme.md. More details here: https://github.com/kubernetes/community/issues/7616
=> readme: fix slack link for sig-etcd

server/etcdserver/cluster_util.go
It's possible that etcd server may run into a server side request forgery situation when adding a new member. If users provide a malicious peer URL, the existing etcd members may be redirected to other unexpected internal URL when getting the new member's version.
One component of #16969
=> Disable following redirects when checking peer urls

server/etcdserver/api/etcdhttp/health.go, server/etcdserver/api/etcdhttp/health_test.go, tests/e2e/http_health_check_test.go
Follow up of https://github.com/etcd-io/etcd/pull/16792:
Because `ReadIndex check` requires non-trivial changes, it would be difficult to backport. 
To unblock livez/readyz, a fallback to the old `linearizable_read` check would meet the MVP, the new `livez/readyz` checks would be no worse than the old `/heath` checks, and minimize the risk for backporting.
=> etcdserver: add linearizable_read check to readyz.

clientv3/client.go, tests/e2e/cluster_proxy_test.go, tests/e2e/cluster_test.go, tests/e2e/ctl_v3_grpc_test.go, tests/e2e/etcd_process.go, tests/e2e/etcd_spawn_nocov.go
Breakdown of https://github.com/etcd-io/etcd/pull/16827
Backport https://github.com/etcd-io/etcd/pull/13359 (only e2e test is implemented, corresponding integration test is not deserved to be back-ported given its risk caused by large number of test code changes)
=> [3.4] backport #13359 Fix http2 authority header in single endpoint scenario

tests/e2e/v2store_deprecation_test.go
Split from https://github.com/etcd-io/etcd/pull/16989
=> Refactor v2 deprecation tests to allow different cluster config

clientv3/integration/naming/resolver_test.go, clientv3/naming/resolver/resolver.go, go.mod, go.sum, pkg/grpc_testing/stub_server.go
Last PR of https://github.com/etcd-io/etcd/issues/16740 to resolve the CVE by upgrading gRPC version. 
Backported https://github.com/etcd-io/etcd/pull/16790
=> [3.4] Upgrade grpc 1.58.3

etcdserver/api/v3rpc/interceptor.go
etcd v3.5.0 supports saving snapshot from leaner, may I backport this to v3.4?
backport #12890 
=> [3.4] backport #12890 learner support snapshot RPC

server/etcdserver/apply_v2.go, server/etcdserver/server.go, server/etcdserver/server_test.go
Applier is no longer needed as we just handle a cluster changes.
=> Remove v2 applier

client/v3/ordering/util.go, tests/integration/clientv3/ordering_util_test.go
Add tests for `clientv3test.TestUnresolvableOrderViolation` and `clientv3test.TestEndpointSwitchResolvesViolation`
Improve `TestEndpointSwitchResolvesViolation` with a partition resolved return no error case
Addresses https://github.com/etcd-io/etcd/issues/16865
=> clientv3test: add comments for clientv3test

tests/e2e/ctl_v3_member_test.go
This simple test shows that approach presented in https://github.com/etcd-io/etcd/pull/16084  to just switch validation to just use v3 store is incorrect 
If run on top of the PR it results in panic
```
panic: failed to delete member from store [recovered]
panic: execute job failed
goroutine 209 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0x4?, {0x0?, 0x0?, 0xc00051c9e0?})
go.uber.org/zap@v1.26.0/zapcore/entry.go:196 +0x54
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0006300d0, {0xc00064c400, 0x2, 0x2})
go.uber.org/zap@v1.26.0/zapcore/entry.go:262 +0x3ec
go.uber.org/zap.(*Logger).Panic(0x1056348?, {0x1064328?, 0xe82200?}, {0xc00064c400, 0x2, 0x2})
go.uber.org/zap@v1.26.0/logger.go:284 +0x51
go.etcd.io/etcd/pkg/v3/schedule.(*fifo).executeJob.func1() …
```
=> Add a simple test ensuring membership is properly bootstrapped

client/v3/client.go
=> add initialization for epMu in contetx client

server/embed/config.go, server/embed/config_tracing.go, server/embed/config_tracing_test.go, server/embed/etcd.go, server/etcdmain/config.go, server/etcdmain/help.go, tests/go.mod, tests/integration/tracing_test.go
`ExperimentalDistributedTracingSamplingRatePerMillion` is the number of samples to collect per million spans.
Defaults to 0.
Without this flag tracing is effectively broken / unusable in `release-3.5` as the default sample rate was changed to `0` in 3.5.5 via https://github.com/etcd-io/etcd/commit/4c013c91e90a5f2f8b226ba81476707c47c42f5d.
Backports:
- https://github.com/etcd-io/etcd/pull/13248
- https://github.com/etcd-io/etcd/pull/14348
Fixes #16935
=> [3.5] Backport add sampling rate to fix distributed tracing

CHANGELOG/CHANGELOG-3.5.md
Update CHANGELOG to cover https://github.com/etcd-io/etcd/pull/16951.
=> CHANGELOG: Add 3.5.11 note for --experimental-distributed-tracing-sampling-rate

server/etcdserver/api/membership/cluster.go, server/etcdserver/api/membership/cluster_test.go, server/etcdserver/server.go
This PR is not very useful, but let's merge it to clarify how validation should look like as long as we bootstrap from v2 store 
Alternatives proposed before:
* https://github.com/etcd-io/etcd/pull/16084
* https://github.com/etcd-io/etcd/pull/17019
=> Switch to validating v3 when v2 and v3 are synchronized

server/etcdserver/server_test.go
This test was written to show issue with https://github.com/etcd-io/etcd/pull/17019.
We cannot disable validation on entries before v3 state because we are still using them to update confState, which is still loaded from snapshot and not v3.
=> Test ApplyConfState after restart

server/etcdserver/apply/apply.go, server/etcdserver/apply/apply_auth.go, server/etcdserver/apply/apply_auth_test.go, server/etcdserver/apply/uber_applier.go, server/etcdserver/apply/uber_applier_test.go, server/etcdserver/server.go, server/etcdserver/server_test.go
Cluster membership changes can be done via both `EntryNormal` (setting attribute on member) and `EntryConfChange` (adding member). This made it natural to keep them in separate code paths, but it resulted that changes to membership.Cluster can go through totally separate paths
* applyEntryNormal -> uberApplier -> corruptApplier -> authApplier ->  backendApplier -> membership.Cluster
* applyConfChange -> membership.Cluster
This has lead to very weird `shouldApplyV3` logic required to handle v2 and v3 synchronization.
My proposal would be to move the membershipChanges from `applyEntryNormal` and keep them next to `applyConfChange`. The long term goal would be to change `membership.Cluster` into a `membership.Applier`, that would be a single state machine handling all changes to cluster …
=> Extract membership applier

CHANGELOG/CHANGELOG-3.5.md
Updates changelog for 3.5 to include https://github.com/etcd-io/etcd/pull/16986
=> changelog: Update changelog for 3.5.11 to include url redirect fix

server/etcdserver/cluster_util.go
It's possible that etcd server may run into SSRF situation when adding a new member. If users provide a malicious peer URL, the existing etcd members may be redirected to other unexpected internal URL when getting the new member's version.
Backports:
- https://github.com/etcd-io/etcd/pull/16986
=> [3.5] Backport disable following redirects when checking peer urls

tests/robustness/failpoint/failpoint.go, tests/robustness/main_test.go
If one of nodes is unhealthy the test would never finish as watchers would never reach max revision.
cc @ahrtr 
We should also consider setting timeout on watch collection.
=> Abort if failpoint injecton failed

server/etcdserver/cluster_util.go, server/etcdserver/corrupt.go, server/lease/leasehttp/http.go
Disable following redirects from peer HTTP communication on the client's side. Etcd server may run into SSRF (Server-side request forgery) when adding a new member. If users provide a malicious peer URL, the existing etcd members may be redirected to another unexpected internal URL when getting the new member's version.
Fixes #16969.
=> server: disable redirects in peer communication

server/lease/lessor.go
Rollback https://github.com/etcd-io/etcd/pull/14080
Please read https://github.com/etcd-io/etcd/pull/16035#discussion_r1413820384
=> Rollback the pull/14080: which fixed the potential deadlock

server/etcdserver/cluster_util.go, server/etcdserver/corrupt.go, server/lease/leasehttp/http.go
This PR backports SSRF from #17066 to the `release-3.5` branch.
Disable following redirects from peer HTTP communication on the client's side. Etcd server may run into SSRF (Server-side request forgery) when adding a new member. If users provide a malicious peer URL, the existing etcd members may be redirected to another unexpected internal URL when getting the new member's version.
Related to #16969 
=> Backport disable redirects in peer communication to release-3.5

server/etcdserver/api/etcdhttp/health.go, server/etcdserver/api/etcdhttp/health_test.go, server/proxy/grpcproxy/health.go
Part of https://github.com/etcd-io/etcd/issues/16007
Follow up of https://github.com/etcd-io/etcd/pull/17000
Original PRs:
https://github.com/etcd-io/etcd/pull/16697
https://github.com/etcd-io/etcd/pull/16651
https://github.com/etcd-io/etcd/pull/16797
https://github.com/etcd-io/etcd/pull/16984
=> [3.5] Backport livez/readyz

server/etcdserver/server.go, server/etcdserver/server_test.go
Ignore Raft messages when the `To` field mismatches the local member ID. In cases where incorrect Raft messages are dispatched, potentially due to a malfunctioning switch, this proactive check prevents panics, such as "tocommit is out of range".
Fix #16220
Fix #17081
=> server: ignore raft messages if member id mismatch

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
https://github.com/etcd-io/etcd/issues/17049
https://github.com/etcd-io/etcd/pull/17076#issuecomment-1843614913
=> Update release-3.4 and 3.5 Changelog for go bump to 1.20.12

scripts/genproto.sh
@jmhbnz and I are working on refining the test-infra prow workflow to harmonise with the legacy GitHub Actions workflow.
We noticed the [test-infra/config/jobs/etcd/etcd-presubmits.yaml](https://github.com/kubernetes/test-infra/blob/551ef90f7a3efa1560b593bf0c6eea7290bee516/config/jobs/etcd/etcd-presubmits.yaml#L69) is using `make verify-lint` whilst the [etcd/.github/workflows/static-anaylsis.yaml](https://github.com/etcd-io/etcd/blob/db4e95cb1f8d3a8eebfb89c880d5fbd8d6165292/.github/workflows/static-analysis.yaml#L37) is using `make verify`
We want to make a change from `make verify-lint` to `make verify` within the test-infra repo 
When testing the `make verify` command in the test-infra image: `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231122-5f461e0995-master` there was an error …
=> Adding automated install of Protoc if not found on the system

Documentation/contributor-guide/roadmap.md
Remembered a discussion at KubeCon NA we wanted to add a status for the current release priorities.
This gives us a quick view overall where the major items for the release are at.
=> Add status column for current release priorities

tests/robustness/makefile.mk
If the arguments have version suffixes (like @latest or @v1.0.0), "go install" builds packages in module-aware mode, ignoring the go.mod file in the current directory or any parent directory, if there is one.
So there is no need to execute "`cd tools/mod`"
=> Install gofail in module-aware mode and ignore go.mod file

.github/workflows/e2e-arm64.yaml, .github/workflows/robustness-nightly.yaml, .github/workflows/robustness.yaml, .github/workflows/tests-template.yaml, .github/workflows/tests.yaml
part of https://github.com/etcd-io/etcd/issues/17045
This PR updates the RAM requirements for several workflows based on the recent triage meeting discussions and analysis:
**E2E Tests:**
* Increased the RAM allocation for the actuated runner to 8GB.
**Reusable Tests Workflow:**
* Due to the workflow utilizing the `runs-on` input provided by the calling workflow, direct modification was not possible.
* Implemented a conditional statement to dynamically adjust the `runs-on` parameter based on the `arch` input variable:
* For `arm64` architecture, the workflow now runs on `actuated-arm64-8cpu-8gb` with 8GB RAM.
* Other architectures continue to use the RAM allocation specified by the calling workflow.
**Reusable Robustness Workflow:**
* The `runs-on` parameter is parsed at runtime using the …
=> Adjusted RAM Requirements for arm64 Workflows

.github/workflows/e2e.yaml, Makefile, build.sh, pkg/expect/expect.go, server/etcdserver/server.go, server/mvcc/backend/batch_tx.go, tests/e2e/etcdctl.go, tests/e2e/http_health_check_test.go, tests/framework/e2e/cluster.go, tests/framework/e2e/cluster_proxy.go, tests/framework/e2e/etcd_process.go, tests/framework/e2e/util.go, tools/mod/go.mod, tools/mod/tools.go
Part of https://github.com/etcd-io/etcd/issues/16007
Followup PR of https://github.com/etcd-io/etcd/pull/17039
Original PR https://github.com/etcd-io/etcd/pull/16698
=> [3.5] Backport e2e tests for livez/readyz.

tools/mod/go.mod, tools/mod/go.sum
This pull request completes this weeks etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1DDWzbcOx1p32MhyelaPZ_SfYtAD6xRsrtGRZ9QXPOyQ/edit#gid=0) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).
Summary of actions:
=> [2023-12-13] Bump dependencies identified by dependabot 

contrib/README.md
Add missing lock and mixin contrib example descriptions to contrib README.
=> contrib: add missing lock and mixin readme descriptions

etcdserver/cluster_util.go, etcdserver/corrupt.go, lease/leasehttp/http.go
Disable following redirects from peer HTTP communication on the client's side. Etcd server may run into SSRF (Server-side request forgery) when adding a new member. If users provide a malicious peer URL, the existing etcd members may be redirected to another unexpected internal URL when getting the new member's version.
Related to #16969 
=> [3.4] Backport disable redirects in peer communication

server/etcdserver/server.go, server/etcdserver/v3_server.go, server/lease/lessor.go, server/lease/lessor_test.go, tests/e2e/v3_lease_no_proxy_test.go, tests/integration/v3_lease_test.go
Fix https://github.com/etcd-io/etcd/issues/15247.
- The first commit prevents an old leader from revoking any leases, similar to https://github.com/etcd-io/etcd/pull/12531.
- The second commit prevents the clients from getting stuck on an unhealthy member (i.e. an old leader)
Also refer to https://docs.google.com/document/d/1peLDjwebnSuNR69ombuUiJ5fkSw7Rd3Slv_mUpOLsmg/edit#heading=h.jbaw5ynuj9i7
=> Ignore old leader's leases revoking request

etcdserver/api/etcdhttp/health.go, etcdserver/api/etcdhttp/health_test.go, proxy/grpcproxy/health.go
Similar to https://github.com/etcd-io/etcd/pull/17039
=> [3.4] Backport livez/readyz

.github/workflows/e2e-arm64.yaml, .github/workflows/robustness-template.yaml, .github/workflows/tests-template.yaml
Recently in https://github.com/etcd-io/etcd/issues/17045 we introduced a new github action to etcd testing workflows that run on `arm64` so that we could tune the memory requests of those workflows in an evidence based way.
We have now completed that tuning, with workflows being reduced from `32GB` ram to `8GB` ram which also includes plenty of headroom based on current utilisation where workflows generally all sit below `5GB`:
With the tuning complete I propose we turn off collecting the detailed performance telemetry for every workflow as it creates quite noisy summaries and some error annotations on our workflows, for example: https://github.com/etcd-io/etcd/actions/runs/7231109865.   
We can always turn it back on sometime in future if performance profiling is required again.
=> Remove workflow telemetry github action

tests/robustness/traffic/kubernetes.go
Correct typo from 'Kuberntes' to 'Kubernetes'.
=> Correct typo from 'Kuberntes' to 'Kubernetes'

.github/dependabot.yml, Dockerfile
This should not change the current behavior, but will cause dependabot to update the digest of the latest base image weekly. 
Related: https://github.com/etcd-io/etcd/issues/16987
Signed-off-by: Wes Panther <wpanther@google.com>
=> Add digest for base image and configure dependabot

etcdserver/server.go
Backporting one of the commits from https://github.com/etcd-io/etcd/pull/17151
Checking `be` variable is nil is done to avoid panic from  https://github.com/etcd-io/etcd/issues/17146
```
DEFAULT 2023-12-16T11:46:09.619866958Z panic: runtime error: invalid memory address or nil pointer dereference [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0xc1a07e] goroutine 1 [running]: go.etcd.io/etcd/etcdserver.NewServer.func2(0xc000452de0, 0xc000451ca0) go.etcd.io/etcd/etcdserver/server.go:345 +0x3e panic(0xed6ba0, 0xc0003261f0) /usr/local/go/src/runtime/panic.go:971 +0x499 go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc00029e630, 0xc007e7c000, 0x1, 0x1) /workspace/louhi_ws/go/pkg/mod/go.uber.org/zap@v1.10.0/zapcore/entry.go:229 +0x565 go.uber.org/zap.(*Logger).Panic(0xc000114c60, …
```
=> [release-3.4] Check if be is nil to avoid panic when be is overriden with nil

.github/workflows/fuzzing.yaml, .github/workflows/robustness-template.yaml, .github/workflows/scorecards.yml, .github/workflows/tests-template.yaml
Recently dependabot opened https://github.com/etcd-io/etcd/pull/17140 to propose bumping for v4.0 of artifact-upload github action.
There are breaking changes in v4.0, refer:
- Description: https://github.com/actions/upload-artifact#breaking-changes
- Discussion: https://github.com/actions/upload-artifact/issues/472
For etcd the impact appears to be isolated to `.github/workflows/tests-template.yaml` where we just need to explicitly declare a unique `name: ` for each matrix job artifact (like we already do in `.github/workflows/robustness-template.yaml` for example).
=> Fix artifact upload github action for compatibility with v4.0

client/pkg/transport/listener.go, client/pkg/transport/listener_test.go, client/pkg/transport/listener_tls.go
Continues the work from #16860. Implements the unit tests to verify the revocation list functionality. 
Fixes #16861.
=> Replace the deprecated `x509.ParseCRL` with `x509.ParseRevocationList`

.github/workflows/gh-workflow-approve.yaml
Earlier today I `/ok-to-test` approved https://github.com/etcd-io/etcd/pull/17190 and https://github.com/etcd-io/etcd/pull/17189.
These are both backport prs to our stable release branches.
After adding the comment k8s ci bot happily added the correct `ok-to-test` label, however our github workflows didn't actually approve and run, meaning they are still waiting on a maintainer.
Investigating it looks like we are just missing `release-3.4` and `release-3.5` branches in the `gh-workflow-approve.yaml` workflow to fix this so org members can help take the load off maintainers when managing backports.
=> Enable org members to approve workflows for backports

etcdmain/help.go
I was working on this issue: https://github.com/etcd-io/etcd/issues/17132 when I found that  flag `--experimental-enable-lease-checkpoint-persist` is missing from `etcd --help` in etcd version `3.4.x` 
Please check this:  https://github.com/etcd-io/etcd/issues/17132#issuecomment-1868512541
=> [3.4] Add missing `experimental-enable-lease-checkpoint-persist` flag in etcd help

server/etcdmain/help.go
I was working on this issue: https://github.com/etcd-io/etcd/issues/17132 when I found that  flag `--experimental-enable-lease-checkpoint-persist` is missing from `etcd --help` in etcd version `3.5.x` 
Please check this:  https://github.com/etcd-io/etcd/issues/17132#issuecomment-1868512541
=> [3.5] Add missing `experimental-enable-lease-checkpoint-persist` flag in etcd help

tests/framework/testutils/execute.go
As part of https://github.com/etcd-io/etcd/issues/15247, backporting https://github.com/etcd-io/etcd/pull/16822 to 3.5 branch will be done in 2 steps-
1. backport testutils.ExecuteUntil to 3.5 branch since tests/e2e/v3_lease_no_proxy_test.go makes use of testutils.ExecuteUntil
2. backport changes in #16822 to 3.5 branch
This PR addresses Step 1 above.
=> Backport testutils.ExecuteUntil to 3.5 branch

etcdmain/config_test.go, etcdmain/help.go
Fixes : https://github.com/etcd-io/etcd/issues/16034 for `etcd v3.5`
Backport: https://github.com/etcd-io/etcd/pull/16465
=> [3.4]Add a unit tests and missing flags in etcd help.

server/etcdserver/bootstrap.go, server/etcdserver/server.go, server/storage/backend.go, tests/e2e/leader_snapshot_no_proxy_test.go, tests/robustness/failpoint/failpoint.go, tests/robustness/failpoint/gofail.go, tests/robustness/failpoint/network.go
Did some digging and found that we never added any tests for this behavior.
Improves logs and add explicit tests and endpoint around recovering snapshot backend for https://github.com/etcd-io/etcd/issues/17146
cc @ahrtr
=> Improve logs around recovering snapshot backend and add an e2e test 

Documentation/infra-guide/arm64-infra.md
We updated our resource requirement for actuated instances. 
We should update the doc here as well.
=> Update arm64 infra guide standard `arm64` runner definition

Makefile, scripts/genproto.sh
@jmhbnz and I are working on refining the test-infra prow workflow to harmonise with the legacy GitHub Actions workflow.
We noticed the [test-infra/config/jobs/etcd/etcd-presubmits.yaml](https://github.com/kubernetes/test-infra/blob/551ef90f7a3efa1560b593bf0c6eea7290bee516/config/jobs/etcd/etcd-presubmits.yaml#L69) is using `make verify-lint` whilst the [etcd/.github/workflows/static-anaylsis.yaml](https://github.com/etcd-io/etcd/blob/db4e95cb1f8d3a8eebfb89c880d5fbd8d6165292/.github/workflows/static-analysis.yaml#L37) is using `make verify`
We want to make a change from `make verify-lint` to `make verify` within the test-infra repo
When testing the `make verify` command in the test-infra image: `gcr.io/k8s-staging-test-infra/kubekins-e2e:v20231208-8b9fd88e88-master` there was an error …
=> Automate installation of yamllint

client/pkg/fileutil/purge.go, client/pkg/fileutil/purge_test.go, server/etcdserver/server.go
Ref https://github.com/etcd-io/etcd/issues/17194
Flocking to snapshot files was added unintentionally in https://github.com/etcd-io/etcd/pull/1927.
Even at this time `PurgeFile` function was used for both wal and snapshot files https://github.com/etcd-io/etcd/blob/502396edd53140cd2a099fb5d7a9f59ec79f4475/etcdserver/server.go#L323-L339
Did minimal changes to avoid flocking files. Don't want to refactor it now to allow easy backport to older versions.
cc @ahrtr
=> Don't flock snapshot files

etcdserver/server.go, pkg/fileutil/purge.go, pkg/fileutil/purge_test.go
Backport https://github.com/etcd-io/etcd/pull/17199
cc @ahrtr
=> [release-3.4] Don't flock snapshot files

Dockerfile-release.amd64, Dockerfile-release.arm64, Dockerfile-release.ppc64le, Dockerfile-release.s390x
This pull request proposes backporting https://github.com/etcd-io/etcd/pull/17122 to `release-3.5`.
Currently etcd official release image builds are not reproducible as we currently use the mutable `latest` tag for our distroless base image. With this backport they would become reproducible through a switch to immutable digests.
It needs to be called out there is a tradeoff that before each release we would ideally consider updating to the latest upstream image sha to ensure our reproducible builds are using the most current base image.  For `main` we have dependabot keeping on top of this.  For release branches I don't believe dependabot can be configured to analyse non default branch so we would need to do it manually.
Relates to https://github.com/etcd-io/etcd/issues/16987.
=> [3.5] Backport adding digest for etcd base image

server/embed/config.go, server/embed/config_logging.go
Struct Config has methods on both value and pointer receivers. Such usage is not recommended by the Go Documentation. 
In general, all methods on a given type should have either value or pointer receivers, but not a mixture of both.
https://go.dev/tour/methods/8
=> Fix Struct Config has methods on both value and pointer receivers. Such usage is not recommended by the Go Documentation. 

Documentation/contributor-guide/roadmap.md, Documentation/contributor-guide/triage_issues.md
One of the last remaining steps of https://github.com/etcd-io/etcd/issues/15773 and https://github.com/etcd-io/etcd/issues/13611 is refreshing how we prioritize issues for etcd.
Currently the only issue label we have is `priority/important` which means we have no way of distinguishing issue criticality or equally importantly which issues are truly backlog and should not be worked on right now. We have attempted to create priorities in our roadmap however they are bespoke, lack description and don't exist as project issue labels.
This pull request:
1. Proposes we adopt the Kubernetes project issue priorities defined here: https://www.kubernetes.dev/docs/guide/issue-triage/#step-three-define-priority
2. Updates our `roadmap.md` to use the new priorities.
I think it makes sense for etcd to …
=> Adopt kubernetes issue priorities

server/go.mod, server/storage/backend/batch_tx.go, server/storage/backend/batch_tx_test.go, tests/framework/integration/cluster.go, tests/integration/clientv3/user_test.go, tests/integration/member_test.go
The PR includes fix for 
- UnsafeDelete https://github.com/etcd-io/etcd/issues/17158
=> Fix delete inconsistencies in read buffer

tests/e2e/corrupt_test.go, tests/e2e/ctl_v3_member_no_proxy_test.go, tests/e2e/etcdctl.go, tests/e2e/utils.go
Follow up: https://github.com/etcd-io/etcd/pull/17079#issuecomment-1856089798
=> [3.5] member replace e2e test

tests/e2e/ctl_v3_member_no_proxy_test.go, tests/e2e/etcdctl.go, tests/e2e/utils.go
Follow up: https://github.com/etcd-io/etcd/pull/17079#issuecomment-1856089798
=> [3.4] member replace e2e test

server/storage/backend/batch_tx_test.go, server/storage/backend/tx_buffer.go
related to https://github.com/etcd-io/etcd/issues/17158
=> Fix tx buffer inconsistency if there are duplicate keys in one tx.

tests/integration/clientv3/maintenance_test.go
Unlike SnapshotWithVersion, the client.Snapshot doesn't wait for first response. The server could open db after we close connection or shutdown the server. We can read few bytes to ensure server opens boltdb.
Closes #17223 
=> integration: deflake TestMaintenanceSnapshotCancel

clientv3/integration/user_test.go, go.mod, go.sum, mvcc/backend/batch_tx.go, mvcc/backend/batch_tx_test.go
backport https://github.com/etcd-io/etcd/pull/17195 to 3.4
part of https://github.com/etcd-io/etcd/issues/17158
=> [3.4] Fix delete inconsistencies in read buffer

Dockerfile-release, Dockerfile-release.arm64, Dockerfile-release.ppc64le
This pull request proposes backporting https://github.com/etcd-io/etcd/pull/17122 to `release-3.4`.
Currently etcd official release image builds are not reproducible as we currently use the mutable `latest` tag for our distroless base image. With this backport they would become reproducible through a switch to immutable digests.
It needs to be called out there is a tradeoff that before each release we would ideally consider updating to the latest upstream image sha to ensure our reproducible builds are using the most current base image. For `main` we have dependabot keeping on top of this. For release branches I don't believe dependabot can be configured to analyse non default branch so we would need to do it manually.
Fixes https://github.com/etcd-io/etcd/issues/16987
=> [3.4] Backport adding digest for etcd base image

server/storage/mvcc/kvstore_compaction.go
To improve traceability of backend database usage, Added below parameter related to backend database usage metrics inside scheduledCompaction function.
current-db-size-bytes
current-db-size
current-db-size-in-use-bytes
current-db-size-in-use
Signed-off-by: Rahul More <rahulbapumore@gmail.com>
=> mvcc: Printing etcd backend database related metrics inside scheduleCompaction function

server/storage/backend/batch_tx.go
Fix https://github.com/etcd-io/etcd/issues/17245
etcd creates the meta bucket twice on startup, 
- https://github.com/etcd-io/etcd/blob/4bc55e520861f6998d3e8b8b919c1b3abaeb487f/server/etcdserver/bootstrap.go#L212
- https://github.com/etcd-io/etcd/blob/4bc55e520861f6998d3e8b8b919c1b3abaeb487f/server/storage/mvcc/kvstore.go#L118
Overall, it isn't a big problem. But let's replace `CreateBucket` with `CreateBucketIfNotExists` to remove the error message, to avoid any confusion.
=> Replace `CreateBucket` with `CreateBucketIfNotExists`

CHANGELOG/CHANGELOG-3.4.md
Link to https://github.com/etcd-io/etcd/pull/17270
=> Add changelog for 3.4.30 to cover the nil pointer log panicking issue

.devcontainer/devcontainer.json
Working with @jmhbnz to debug issues with etcd `make verify` prow job, we noticed required tools for working with prow locally are not available in the codespace `devcontainer.json`
=> Added container tools to devcontainer for debugging prow jobs

server/storage/mvcc/kvstore_compaction_test.go
It always reuse the same memory space. Each next iteration will always overwrite previous data.
It took me about 2 hours to identify the root cause why there are duplicated keys in the buffer.
=> Fix test issue in TestScheduleCompaction

client/internal/v2/client_test.go, client/internal/v2/keys_test.go, client/internal/v2/members_test.go, tools/.golangci.yaml
I was looking at the disabled linter rules and addressed the `error-strings` warnings. The only offending files are in the deprecated v2 client test code.
After speaking with @jmhbnz, he told me that @fuweid was working recently with the linter rules. So, it would be great if you could take a look at this.
=> Fix golangci revive error-strings issues

server/mvcc/kvstore_compaction.go
Backporting commit 21bbc82 in etcd 3.5
To improve traceability of backend database usage, Added below parameter related to backend database usage metrics inside scheduledCompaction function.
current-db-size-bytes
current-db-size
current-db-size-in-use-bytes
current-db-size-in-use
=> [3.5] mvcc: Printing etcd backend database related metrics inside scheduleCompaction function

server/embed/etcd.go
Backport https://github.com/etcd-io/etcd/pull/17314
=> [3.5] Print error log when creating peer listener failed

client/v3/client.go, client/v3/client_test.go, client/v3/config.go
Address https://github.com/etcd-io/etcd/issues/17272.
=> Add backoff & retries to client config

tests/robustness/validate/validate.go, tests/robustness/validate/watch.go
Creation of event history requires each client to return consistent events. If clients observed inconsistent view of some revision, merging will fail and return diff between two clients. This however doesn't provide hint on what kind of issue happend.
This PR helps cases where there is an error with single watch stream (like event duplication) by running normal watch validation even without full event history.
Before:
```
logger.go:130: 2024-01-16T15:53:49.847+0100 INFO    Validating watch
validate.go:43: Failed merging watch history to create event history, skipping further validation, err: events between clients 11 and 8 don't match, revision: 872, diff:   []model.WatchEvent{
+       {
+  …
```
=> Validate watch even if event history cannot be created

server/storage/mvcc/kvstore_test.go
Fix https://github.com/etcd-io/etcd/issues/17232
- We should ensure all goroutines finished before exiting the test case
- Compaction 100 times may take longer than 10s, so reduce the count from 100 to 50;
=> test: fix `TestHashKVWhenCompacting`: ensure all goroutine finished

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
Updates 3.4 and 3.5 CHANGELOGs to add a line that the binaries are compiled with go version 1.20.13.
Related to #17269
=> changelog: add 3.4 and 3.5 note about go 1.20.13

tests/robustness/model/replay.go
Encountered this while addressing comments in https://github.com/etcd-io/etcd/pull/17352
Panic encountered:
```
--- FAIL: TestRobustnessExploratory (5.57s)
--- FAIL: TestRobustnessExploratory/Kubernetes/LowTraffic/ClusterOfSize1 (5.55s)
panic: runtime error: index out of range [184] with length 184 [recovered]
panic: runtime error: index out of range [184] with length 184
goroutine 162 [running]:
testing.tRunner.func1.2({0x1a829c0, 0xc0001b5320})
/usr/local/go/src/testing/testing.go:1545 +0x238
testing.tRunner.func1()
/usr/local/go/src/testing/testing.go:1548 +0x397
panic({0x1a829c0?, 0xc0001b5320?})
/usr/local/go/src/runtime/panic.go:914 +0x21f
go.etcd.io/etcd/tests/v3/robustness/model.(*EtcdReplay).next(0xc0000c4d30)
/Users/mjivrajani/gocode/src/github.com/MadhavJivrajani/etcd/tests/robu …
```
=> tests/robustness: fix out of index panic in model replay

server/etcdserver/bootstrap_test.go, server/etcdserver/corrupt_test.go, server/etcdserver/raft_test.go, server/etcdserver/server_test.go
If pending changes aren't committed before test completed, it might cause data race when we don't drain all the background goroutines.
```bash
$ cd server
$ go test -race -v -run TestApplyRepeat ./etcdserver
...
panic: Log in goroutine after TestApplyRepeat has completed: 2024-02-03T17:06:13.262+0800       DEBUG   bbolt   Committing transaction 2
goroutine 81 [running]:
testing.(*common).logDepth(0xc000502820, {0xc0001b0460, 0x41}, 0x3)
/usr/local/go/src/testing/testing.go:1022 +0x6d4
testing.(*common).log(...)
/usr/local/go/src/testing/testing.go:1004
testing.(*common).Logf(0xc000502820, {0x1421ad7, 0x2}, {0xc000603520, 0x1, 0x1})
/usr/local/go/src/testing/testing.go:1055 +0xa5
go.uber.org/zap/zaptest.testingWriter.Write({{0x15f1f90?, 0xc000502820?}, 0xda?}, {0xc000119800, 0x42, 0x400}) …
```
=> etcdserver: drain leaky goroutines before test completed

client/v3/client.go, client/v3/client_test.go, client/v3/config.go
Backporting https://github.com/etcd-io/etcd/pull/17307 to 3.5 to allow kubernetes to consume these new options as they are on etcd release-3.5.
Addresses https://github.com/etcd-io/etcd/issues/17272.
=> [3.5] backport backoff/retry config

clientv3/client.go, clientv3/client_test.go, clientv3/config.go
Backporting https://github.com/etcd-io/etcd/pull/17307 to 3.4.
Addresses https://github.com/etcd-io/etcd/issues/17272.
=> [3.4] add backoff to client config

client/pkg/transport/keepalive_listener.go, client/pkg/transport/keepalive_listener_openbsd.go, client/pkg/transport/keepalive_listener_unix.go
Modified code to allow for operation on OpenBSD, which does not support SetKeepAlivePeriod(). SetKeepAlivePeriod() is now ignored on the affected platform.
This PR fixes #15811.
=> etcd: ignore SetKeepAlivePeriod errors on OpenBSD

server/etcdserver/apply_auth_test.go, server/etcdserver/corrupt_test.go, server/etcdserver/raft_test.go, server/etcdserver/server_test.go
=> [3.5] etcdserver: drain leaky goroutines before test completed

etcdserver/apply_auth_test.go, etcdserver/corrupt_test.go, etcdserver/raft_test.go, etcdserver/server_test.go
Part of https://github.com/etcd-io/etcd/issues/17317
=> [3.4] etcdserver: drain leaky goroutines before test completed

client/pkg/transport/keepalive_listener.go, client/pkg/transport/keepalive_listener_openbsd.go, client/pkg/transport/keepalive_listener_unix.go
This is a backport of https://github.com/etcd-io/etcd/pull/15812
cc @ahrtr
=> [3.5] Backport ignore SetKeepAlivePeriod errors on OpenBSD

CHANGELOG/CHANGELOG-3.5.md
Add backport https://github.com/etcd-io/etcd/pull/15812 to 3.4, 3.5 changelog
=> add OpenBSD support to changelog 3.5

client/v3/watch.go, client/v3/watch_test.go, tests/integration/v3_auth_test.go
If we cannot finish https://github.com/etcd-io/etcd/pull/15253 before 3.6, it's better to drop the string dependent error handling from the main branch.
cc @ahrtr
=> Remove string dependent error handling in watch and auth

tests/e2e/cluster_test.go, tests/e2e/etcd_process.go, tests/e2e/etcdctl.go
Similar to #17381, backports e2e `WaitLeader` into 3.4.
Relates to #16822, #15247
=> [3.4] tests/e2e: backport WaitLeader

scripts/build_lib.sh
This PR will make `CGO_ENABLED` configurable via environment variable. If nothing is set or declared the value of `CGO_ENABLED` will default to `0`.
=> Make CGO_ENABLED configurable

build
This PR will make CGO_ENABLED configurable via environment variable. If nothing is set or declared the value of CGO_ENABLED will default to 0.
Issue: https://github.com/etcd-io/etcd/issues/17419
=> [3.4] Make CGO_ENABLED configurable

build.sh
This PR will make CGO_ENABLED configurable via environment variable. If nothing is set or declared the value of CGO_ENABLED will default to 0.
Issue: https://github.com/etcd-io/etcd/issues/17419
=> [3.5] Make CGO_ENABLED configurable 

etcdutl/etcdutl/snapshot_command.go, etcdutl/snapshot/v3_snapshot.go, server/storage/backend/backend.go
When running the snapshot command, allow receiving an initial memory map allocation for the database, avoiding future memory allocation issues.
As discussed in the fortnightly etc triage meeting, I'm continuing the work from #16055 by squashing the commits and rebasing @fatihusta's original branch with main.
Fixes #16052.
=> etcdutl: Fix snapshot restore memory alloc issue

tests/e2e/logging_test.go
Fix: #17329
- Add the e2e test to validate error logs in an etcd cluster when performing basic operations.
**Note:** It is important to note that while performing the basic operations, we're receiving the error logs which itself is a different issue. Hence, In order to Pass the test-case whenever we've an error log, we're using allowlist here. Later on, once we implement a solution to avoid having excess error logs, we can remove the allowlist from this piece of code.
=> feat: add `TestNoErrorLogsDuringNormalOperations` e2e test to validate error logs during etcd bootstrap

tests/framework/e2e/cluster.go, tests/framework/e2e/etcd_process.go
This PR backports EtcdProcess's GoFailClientTimeout, as requested in #17425.
Required to backport #16822.
=> [3.5] Implement etcd process go fail client timeout

server/etcdserver/api/etcdhttp/health.go
- goword checks fail if function name mismatches with comment
- https://github.com/etcd-io/etcd/issues/17400
=> server: fix comment to match function name

mvcc/kvstore_compaction.go
Backporting commit https://github.com/etcd-io/etcd/commit/21bbc82710a39db30f1bf7d89ea4fa073ad26bcd to `release-3.4`.
Final task to close out https://github.com/etcd-io/etcd/issues/17179.
=> [3.4] mvcc: Printing etcd backend database related metrics inside scheduleCompaction function

tests/e2e/cluster_test.go, tests/e2e/etcd_process.go
This PR backports e2e `EtcdProcess`' `GoFailClientTimeout`. Which is required to backport #16822.
=> [3.4] backport EtcdProcess GoFailClientTimeout

server/verify/verify.go
validateConsistentIndex function might return err but defer might still log it's successful.
Using `retErr` return value is to shadow local error so that `retErr` is always correct.
=> server/verify: use retErr to shadow local err

go.mod, go.sum, server/go.mod, server/go.sum, tests/go.mod, tests/go.sum
- update logrus to address PRISMA-2023-0056
- https://github.com/etcd-io/etcd/issues/17268
```bash
$ go version -m ./bin/etcd | grep logrus
dep	github.com/sirupsen/logrus	v1.9.3	h1:dueUQJ1C2q9oE3F7wvmSGAaVtTmUizReu6fjN8uqzbQ=
```
=> *: update logrus to v1.9.3

.github/workflows/tests-template.yaml, .github/workflows/tests.yaml, Makefile
- add test-smoke to the tests.yaml pipeline
- add bom and dep to the test-smoke definition
- https://github.com/etcd-io/etcd/issues/17400
- https://github.com/etcd-io/etcd/issues/17401
- wait for https://github.com/etcd-io/etcd/pull/17433 to merge
- wait for https://github.com/etcd-io/etcd/pull/17434 to merge
=> *: add test-smoke to the pipeline and update test-smoke

server/etcdserver/server.go, server/etcdserver/v3_server.go, server/lease/lessor.go, server/lease/lessor_test.go, tests/e2e/v3_lease_no_proxy_test.go, tests/framework/e2e/cluster.go, tests/integration/v3_lease_test.go
Backport of PR #16822.
This PR has two commits:
~1. Backport e2e `EtcdProecess`' `GoFailClientTimeout`.~ Addressed in https://github.com/etcd-io/etcd/pull/17427
2. Backport of the actual implementation of ignoring old leader leases revoking requests.
=> [3.5] backport ignore old leaders leases revoking requests

tests/robustness/main_test.go, tests/robustness/validate/validate.go, tests/robustness/validate/watch.go
Follow up from https://github.com/etcd-io/etcd/pull/17352#issuecomment-1941122809
We can check for the condition that Kubernetes checks for, i.e. prevKV can be nil iff the event is not a create a event, only if we know whether compaction has occured or not. If compaction has occured, prevKV can be nil and that is completely valid.
This commit checks if compaction took place during the test run by querying the `/metrics` endpoint. Based on if compaction occured, we now check the Kubernetes condition in the prevKV robustness test.
/assign @serathius
=> tests/robustness: check for compaction before prevKV validation

server/etcdmain/grpc_proxy.go
[…m arguments to the grpc-proxy
](https://github.com/etcd-io/etcd/pull/17366#issue-2117590456)
=> [3.5] Added client keepalive arguments to the grpc-proxy

client/pkg/types/urls.go, pkg/flags/urls_test.go, server/embed/etcd.go, tests/e2e/ctl_v3_grpc_test.go, tests/e2e/ctl_v3_test.go, tests/e2e/etcd_release_upgrade_test.go, tests/framework/e2e/cluster.go, tests/framework/e2e/util.go, tests/integration/cluster.go
backport of #12469 to release 3.5, which enables using unix socket setup an embed server
=> [release-3.5]pkg/types: Support Unix sockets in NewURLS

etcdctl/README.md
I noticed there was a typo in `etcdctl/README.md`
This MR fixes that.
=> Fix typo in  etcdctl/README.md

tests/robustness/main_test.go, tests/robustness/validate/validate.go, tests/robustness/validate/watch.go
This reverts commit 5d7f58d14be1da5135d158dad6fc43391cbf6283.
https://github.com/etcd-io/etcd/pull/17450 increased runtime of robustness tests by over 30% (from 19m to 31m on presubmits) and caused latest nightly tests to timeout. Reverting.
=> Revert "tests/robustness: check for compaction before prevKV validation"

etcdserver/server.go, etcdserver/v3_server.go, integration/v3_lease_test.go, lease/lessor.go, lease/lessor_test.go, tests/e2e/cluster_test.go, tests/e2e/etcdctl.go, tests/e2e/v3_lease_no_proxy_test.go
Backport of PR #16822. Related to #15247.
This PR has three commits:
1. Fixes the incorrect backport of `WaitLeader` (PR: #17398), as 3.4's `spawnJsonCmd` receives an expected output string as an argument, which wasn't provided in the first backport implementation.
2. Completes backporting the remaining e2e cluster setup functions (`EndpointsGRPC`, `EndpointsHTTP`) from the original backport from PR: #15620.
3. Backport of the actual implementation of ignoring old leader leases revoking requests.
=> [3.4] backport ignore old leader leases revoking requests

etcdutl/go.mod, server/etcdserver/server.go, server/storage/backend/verify.go, server/storage/schema/bucket.go
Followup test verification for https://github.com/etcd-io/etcd/issues/17158
Should help us find all places impacted by readbuf inconsistency.
Similar to https://github.com/etcd-io/etcd/pull/17127
=> Add VerifyTxConsistency to backend.

server/storage/mvcc/kvstore_test.go
Fixes : #16963
In test case ```TestHashKVWhenCompacting```, compactions are not finished in 10 secs so increased timeout to 20 secs to accomodate same.
=> Increased timeout to fix TestHashKVWhenCompacting test

go.mod, go.sum, server/go.mod, server/go.sum, tests/go.mod, tests/go.sum, tools/mod/go.mod, tools/mod/go.sum
- addressing https://github.com/etcd-io/etcd/issues/17268#issuecomment-1956266197 for `release-3.5`
=> [3.5] dependency: bump github.com/sirupsen/logrus to v1.9.3

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
=> Update changelogs to cover the bumping bbolt to v1.3.9 for both 3.4.31 and 3.5.13

ADOPTERS.md
Add Cyberfusion to adopters.
I added the URL to an article detailing our use of etcd. Of the available fields, the 'Backups' one seems most appropriate. If it should be (re)moved, please let me know.
=> Add Cyberfusion to adopters

CONTRIBUTING.md
Related to https://github.com/etcd-io/etcd/issues/13167.
=> Add a test status section to display testgrid status.

server/etcdserver/raft.go
=> etcdserver: skip when detect a removed peer

Documentation/contributor-guide/dependency_management.md
Our recent golang update pr's got me thinking about our version policy once again.
Re-reading our current agreed policy I noticed the wording made it possible for us to have periods of time when our stable release branches could potentially be promoting an unsupported version of go.
This pull requests proposes updating our policy so that rather than waiting to upgrade until the current version is no longer supported, we should instead get started on the update a bit sooner.
---
We currently promote golang version `1.21` as the minimum version to build our stable releases. The next upgrade for these branches will be to golang `1.22`. 
| Old policy         | New policy |
|--------------|:-----:|
| Wait until golang `1.23` is released before upgrading. Meaning we could have a period of time …
=> Tweak golang version policy to avoid unsupported minor versions

api/go.mod, api/go.sum, client/v3/go.mod, client/v3/go.sum, etcdctl/go.mod, etcdctl/go.sum, etcdutl/go.mod, etcdutl/go.sum, go.mod, go.sum, pkg/go.mod, pkg/go.sum, raft/go.mod, raft/go.sum, server/go.mod, server/go.sum, tests/go.mod, tests/go.sum, tools/mod/go.mod
Addresses CVE-2024-24786 in the release-3.5 branch by bumping google.golang.org/protobuf from miscellaneous versions to v1.33.0.
Part of #17551
=> [3.5] dependency: bump google protobuf to 1.33.0

go.mod, go.sum
Addresses CVE-2024-24786 in the release-3.4 branch by bumping google.golang.org/protobuf from v1.31.0 to v1.33.0.
Part of #17551
=> [3.4] dependency: bump google protobuf to 1.33.0

.github/workflows/govuln.yaml
Enables `govuln` in the release-3.5 branch.
Part of #17549.
=> [3.5] Add govuln GitHub workflow

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
* Add a line in 3.4 and 3.5 changelogs regarding updating google.golang.org/protobuf to v1.33.0 to address CVE-2024-24786. 
* Remove a duplicated line from compiling binaries with Go 1.21.6 (the most recent compilation is with 1.21.8).
Fixes: #17551 
=> [3.4][3.5] Changelog: Add CVE-2024-24786 remediation

scripts/codecov_upload.sh
Go v1.22 has an error generating the coverage output. Disable it temporarily so GitHub workflows can run in the meantime.
Related to #17560
=> tests: temporary disable coverage redisign Go experiment

server/etcdserver/api/v3rpc/watch.go, tests/integration/v3_watch_test.go
When implementing the fix for progress notifications (https://github.com/etcd-io/etcd/pull/15237) we made a incorrect assumption that that unsynched watches will always get at least one event.
Unsynched watches include not only slow watchers, but also newly created watches that requested old revision. In case that non of the events match watch filter, those newly created watches might become synched without any event going through.
Fixes https://github.com/etcd-io/etcd/issues/17507
/cc @scpmw @ahrtr
=> Fix progress notification for watch that doesn't get any events

server/etcdserver/api/v3rpc/watch.go, tests/integration/v3_watch_test.go
When implementing the fix for progress notifications (https://github.com/etcd-io/etcd/pull/15237) we made a incorrect assumption that that unsynched watches will always get at least one event.
Unsynched watches include not only slow watchers, but also newly created watches that requested current or older revision. In case that non of the events match watch filter, those newly created watches might become synched without any event going through.
Backport https://github.com/etcd-io/etcd/pull/17557
=> [release-3.5] Fix progress notification for watch that doesn't get any events

etcdserver/api/v3rpc/watch.go, integration/v3_watch_test.go
When implementing the fix for progress notifications (https://github.com/etcd-io/etcd/pull/15237) we made a incorrect assumption that that unsynched watches will always get at least one event.
Unsynched watches include not only slow watchers, but also newly created watches that requested current or older revision. In case that non of the events match watch filter, those newly created watches might become synched without any event going through.
Backport https://github.com/etcd-io/etcd/pull/17557
=> [release-3.4] Fix progress notification for watch that doesn't get any events

go.mod, go.sum
- https://github.com/etcd-io/etcd/issues/17268
=> [3.4] dependency: bump github.com/sirupsen/logrus to v1.9.3

client/pkg/logutil/log_format.go, client/pkg/logutil/log_format_test.go, client/pkg/tlsutil/cipher_suites_test.go, client/pkg/verify/verify.go, client/v3/client.go, client/v3/internal/endpoint/endpoint.go, client/v3/internal/endpoint/endpoint_test.go, client/v3/mock/mockserver/mockserver.go, client/v3/retry_interceptor.go, client/v3/watch.go, tests/integration/clientv3/concurrency/example_election_test.go, tests/integration/clientv3/concurrency/example_mutex_test.go, tests/integration/clientv3/concurrency/example_stm_test.go
If we need to deprecate rather than rename an exported variable, we can add an ignore to the linter for that line.
Renamed exported variable:
* `logutil.JsonLogFormat` -> `logutil.JSONLogFormat`
Renamed exported variables from internal packages:
* `endpoint.CREDS_REQUIRE` -> `endpoint.CredsRequire`
* `endpoint.CREDS_DROP` -> `endpoint.CredsDrop`
* `endpoint.CREDS_OPTIONAL` -> `endpoint.CredsOptional`
Exported renamed variables to unexported as they weren't being used anywhere outside their package:
* `verify.ENV_VERIFY` -> `verify.envVerify`
* `verify.ENV_VERIFY_VALUE_ALL` -> `verify.envVerifyValueAll`
* `verify.ENV_VERIFY_VALUE_ASSERT` -> `verify.envVerifyValueAssert`
After addressing these, the var-naming rule passes in the `client` directory.
Relates to #17578
Please read …
=> client: address golangci var-naming issues

server/etcdserver/api/v3rpc/watch.go, server/storage/mvcc/watchable_store.go, server/storage/mvcc/watchable_store_test.go, tests/integration/v3_watch_test.go, tests/robustness/makefile.mk
Fix https://github.com/etcd-io/etcd/issues/17529
@fuweid @serathius @ahrtr 
=> Fix watch event loss

api/v3rpc/rpctypes/error.go, server/etcdserver/corrupt.go, server/etcdserver/corrupt_test.go
Addresses the `var-naming` linter issues in `api`.
Renames the exported variables:
* `rpctypes.ErrGRPCClusterIdMismatch` -> `rpctypes.ErrGRPCClusterIDMismatch`
* `rpctypes.ErrClusterIdMismatch` -> `rpctypes.ErrClusterIDMismatch`
Should we need to deprecate rather than rename, I can add a linter exception.
=> api: address golangci var-naming issues

.github/ISSUE_TEMPLATE/bug-report.yml, security/README.md, security/email-templates.md, security/security-release-process.md
Temporary move to using etcd maintainers mailing list from security@etcd.io.
Related,
https://github.com/kubernetes/community/issues/7739 and https://github.com/kubernetes/k8s.io/pull/6542
A placeholder PR if needed @ahrtr @serathius @wenjiaswe @jmhbnz
=> Use etcd maintainers ML for security related discussion

server/mvcc/watchable_store.go, server/mvcc/watchable_store_test.go
xref. https://github.com/etcd-io/etcd/issues/17529
=> [release-3.5] backport fix watch event loss after compaction

mvcc/watchable_store.go, mvcc/watchable_store_test.go
There seems no go failpoint enabled integration tests. Is it okay just backporting the fix and unit test? Adding an e2e test with go failpoint should be feasible. Let me know if this is the requirement of backporting the fix. 
xref. #17529
=> [release-3.4] backport fix watch event loss after compaction #17555

CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md
=> update 3.4 and 3.5 CHANGELOG of watch event loss after compaction fix

.github/dependabot.yml
Now we will automatically upgrade the docker image in the main branch, let's treat release-3.4 and release-3.5 similarly
Releated: 
- https://github.com/etcd-io/etcd/issues/17609
=> Let dapendabot to auto-update docker for release 3.4&3.5.

server/embed/etcd.go, server/embed/serve.go, server/mock/mockstore/store_recorder.go, server/storage/backend/verify.go, server/storage/backend/verify_test.go, server/storage/schema/lease.go, server/storage/schema/membership.go, server/storage/wal/util.go, server/verify/verify.go
This PR addresses minor var-naming violations from the server directory.
=> server: address golangci var-naming issues

tests/common/auth_test.go, tests/common/member_test.go, tests/integration/clientv3/concurrency/session_test.go, tests/integration/clientv3/naming/resolver_test.go, tests/integration/embed/embed_test.go, tests/integration/v3_leadership_test.go, tests/integration/v3_lease_test.go, tests/integration/v3_watch_test.go
Addresses the `var-naming` issues in `tests/common` and `tests/integration`.
All of these changes were just in local variable names or unexported functions.
Part of #17578
=> tests/common, tests/integration: Address tests var-naming lint rule

.github/workflows/robustness-nightly.yaml, .github/workflows/robustness-template.yaml, .github/workflows/robustness.yaml
In October last year we switched from self managed arm64 CI infrastructure from Equinix Metal to managed arm64 runners provided via the CNCF and actuated.dev.
Since then we have completed some right sizing for memory requirements for all our `arm64` workflows, however we are still hitting some teething issues with CPU performance. Notably for robustness testing.
Performance issues were tracked in:
- https://github.com/etcd-io/etcd/issues/17246
- https://github.com/etcd-io/etcd/issues/17593
One mitigation to improve CPU performance was to disable lazyfs for `arm64` which was completed in https://github.com/etcd-io/etcd/pull/17323. 
Even with lazyfs disabled we are still seeing failures, recent examples are:
1. https://github.com/etcd-io/etcd/actions/runs/8324216324/job/22775349104
```bash …
```
=> Investigate arm64 robustness performance

tests/framework/e2e/cluster.go
Increasing the `ttl` to 5 second to fix flaky issue related to https://github.com/etcd-io/etcd/issues/17556.
Flaking test: `TestCtlV3AuthAndWatchJWT`.
=> flaky: fix jwt test with increasing ttl

pkg/expect/expect.go, pkg/grpctesting/recorder.go, pkg/grpctesting/stub_server.go, tests/framework/integration/cluster.go, tests/integration/clientv3/naming/resolver_test.go
Addresses the `var-naming` issues in `pkg`.
* Renames the `grpc_testing` module to `grpctesting`
* Renames the exported `GrpcRecorder` struct to `GRPCRecorder`
Part of #17578
=> pkg: address golangci var-naming issues

tools/benchmark/cmd/watch_latency.go
* Support prevKV
* Support multiple watchers per stream
* Allow continious puts without waiting for event
cc @ahrtr @jmhbnz @chaochn47
=> Improve watch latency benchmark

contrib/lock/client/client.go, server/etcdserver/api/etcdhttp/peer_test.go
As the doc of http.Response.Body says:
// The http Client and Transport guarantee that Body is always
// non-nil, even on responses without a body or responses with
// a zero-length body. It is the caller's responsibility to
// close Body.
=> all: call Close() after reading http.Response.Body

tests/e2e/cmux_test.go, tests/e2e/watch_delay_test.go, tests/framework/e2e/cluster.go, tests/framework/e2e/cluster_proxy.go, tests/framework/e2e/curl.go, tests/framework/e2e/etcd_process.go, tests/framework/e2e/etcdctl.go, tests/framework/integration/cluster.go, tests/framework/integration/cluster_direct.go, tests/framework/integration/cluster_proxy.go, tests/framework/integration/testing.go, tests/integration/grpc_test.go
Addresses the `var-naming` issues in `tests/framework`.
There are some exported variables that were renamed, but as they're in the tests directory, I didn't think they would need to be deprecated rather than just renamed.
=> tests/framework: address golangci var-naming issues

tests/robustness/failpoint/cluster.go, tests/robustness/identity/id.go, tests/robustness/identity/lease_ids.go, tests/robustness/main_test.go, tests/robustness/model/deterministic.go, tests/robustness/model/history.go, tests/robustness/report/client.go, tests/robustness/report/client_test.go, tests/robustness/traffic/client.go, tests/robustness/traffic/etcd.go, tests/robustness/traffic/kubernetes.go, tests/robustness/traffic/traffic.go, tests/robustness/validate/patch_history_test.go, tests/robustness/validate/validate.go, tests/robustness/validate/watch.go
Addresses the `var-naming` lint issues in `tests/robustness`.
In this case, too, there are some exported variables that were renamed, but as they're in the tests directory, I didn't think they would need to be deprecated rather than just renamed.
=> tests/robustness: address golangci var-naming issues

tests/framework/integration/cluster.go, tests/integration/clientv3/connectivity/black_hole_test.go, tests/integration/clientv3/connectivity/dial_test.go, tests/integration/clientv3/connectivity/network_partition_test.go, tests/integration/clientv3/connectivity/server_shutdown_test.go, tests/integration/clientv3/kv_test.go, tests/integration/clientv3/maintenance_test.go, tests/integration/clientv3/metrics_test.go, tests/integration/clientv3/ordering_kv_test.go, tests/integration/clientv3/ordering_util_test.go, tests/integration/hashkv_test.go, tests/integration/proxy/grpcproxy/cluster_test.go, tests/integration/proxy/grpcproxy/kv_test.go, tests/integration/proxy/grpcproxy/register_test.go, tests/integration/v3_grpc_test.go, tests/integration/v3_tls_test.go
Currently, (`test/framework/`'s) `integration.Member` exports `GrpcURL` already as a struct variable. However, when addressing the `var-naming` linting issues, renaming it from `GrpcURL` to `GRPCURL` clashes with the `GRPCURL()` function.
Given that it's already an exported variable, defining a getter function is unnecessary. This variable's use is also mixed, with calls to both the exported variable (`GrpcURL`) and the function (`GRPCURL()`).
If we prefer to keep the getter function `GRPCURL()`. Then, it would be better to unexport `GrpcURL` (`grpcURL`). But all of the other `GRPC*` variables are exported already. Therefore, it would make sense to unexport all of them, but would increase the rewrite effort.
Please read …
=> tests/framework: address golangci var-naming issues [remove (*Member) GRPCURL()]

tools/mod/go.mod, tools/mod/go.sum, tools/mod/tools.go
`yq` was a tool initially used to get the project's Go version when it was running on Travis CI. This was removed at the commit 577c898feea768e20b9f3c26357abc15b22a3ff3, and the project currently uses `.go-version` to specify the Go version. Therefore, we can safely delete this dependency.
Fixes #17658.
=> tools/mod: remove reference to github.com/mikefarah/yq/v4

server/storage/backend/batch_tx_test.go, server/storage/backend/tx_buffer.go, server/storage/backend/tx_buffer_test.go
Recommit https://github.com/etcd-io/etcd/pull/17228 with buf fix. 
https://github.com/etcd-io/etcd/issues/17247 was fixed by reverting https://github.com/etcd-io/etcd/pull/17228. But the underlying problem with the buffer should still be fixed. 
No failure locally with 
```
EXPECT_DEBUG=true GO_TEST_FLAGS='-run=TestRobustness/Kubernetes/HighTraffic/ClusterOfSize3 --timeout=3000m --count=100 --failfast -v' RESULTS_DIR=./tmp/results make test-robustness
```
and just the `[RaftAfterSaveSnapPanic, MemberReplace]` Failpoints.
=> Fix tx buffer inconsistency if there are unordered key writes in one tx.

etcdutl/etcdutl/migrate_command.go, etcdutl/etcdutl/snapshot_command.go, server/config/config.go, server/etcdserver/bootstrap.go, server/etcdserver/bootstrap_test.go, server/etcdserver/raft_test.go, server/storage/datadir/datadir.go, server/storage/datadir/datadir_test.go, server/storage/util.go, server/verify/verify.go
Addresses the `var-naming` lint issues in `server/storage`.
The use of `Wal` and `WAL` across the project is inconsistent. This was a good opportunity to standardize it.
I deprecated two functions:
* `datadir.ToWalDir` -> `datadir.ToWALDir`
* `serverstorage.GetEffectiveNodeIDsFromWalEntries` -> `serverstorage.GetEffectiveNodeIDsFromWALEntries`
=> server/storage: address golangci var-naming issues

etcdmain/help.go, etcdserver/cluster_util.go, etcdserver/server.go
Part of https://github.com/etcd-io/etcd/issues/15878#issuecomment-1910886682.
https://github.com/etcd-io/etcd/pull/17330 allows existing server to be downgraded to 3.4, with `haveWAL=true`. 
This PR would allow a brand new 3.4 server to join an existing 3.5 cluster. 
This would enable the downgrade method of stopping a 3.5 server and starting a new 3.4 server one by one.
Tested with `TestMixVersionsSnapshotByAddingMember` e2e test in https://github.com/etcd-io/etcd/pull/17531
=> [3.4] Allow new server to join higher cluster version if NextClusterVersionCompatible is true

CHANGELOG/CHANGELOG-3.5.md
Release was completed today, refer https://github.com/etcd-io/etcd/releases/tag/v3.5.13.
=> Update release date for v3.5.13.

server/storage/wal/encoder.go, server/storage/wal/metrics.go
xref. #17615 
add new metrics: _**wal_write_duration_seconds**_
**_wal_write_duration_seconds_** represent total delay of: 
> syscall.write(padding_info + record_data_with_padding)
- delay of fsync is not included in _**wal_write_duration_seconds**_
- data: the raft log to write to the WAL on disk at one single raftNode loop
=> feat: add wal write system call metrics observation (main)

client/pkg/testutil/leak.go
interestingGoroutines uses so many strings.Contains checks to determine
whether to continue, I think it can be avoided.
This patch introduces shouldSkip func to do the checks in a loop
to make the logic clearer.
=> client/pkg/testutil: add shouldSkip func for interestingGoroutines
