etcd-io/etcd

- CHANGELOG/CHANGELOG-3.5.md
feature [livez/readyz HTTP endpoints](https://github.com/etcd-io/etcd/pull/17039) is added in  v3.5.11
please see: https://github.com/etcd-io/etcd/commits/release-3.5/?before=3b252db4f6e68c3ae3ecaa87ab1b502f46d39d6e+35
> changelog: change livez/readyz HTTP endpoints to v3.5.11

- server/etcdmain/help.go
Just a small nit that my editor automatically fixed:
Trailing whitespace in server/etcdmain/help.go
> nit: Fix trailing whitespace in etcdmain/help.go

- client/pkg/testutil/assert.go
AssertTrue and AssertFalse use copyToInterface to copy msg.
This is unnecessary, cause we know the msgAndArgs param of assert.Equal is variadic:
func Equal(t TestingT, expected, actual interface{}, msgAndArgs ...interface{}) bool
This patch removes copyToInterface function, and use msg directly.
> client/pkg/testutil: eliminate copyToInterface function

- tests/e2e/discovery_test.go
Ignore `e2e/discovery_test.go` when `cluster_proxy` tag is set.
Fixes #16098.
> tests/e2e: ignore discovery tests when cluster_proxy tag is set

- server/etcdserver/v3_server.go
- server/lease/lease.go
- server/lease/leasehttp/http.go
- tests/integration/v3_lease_test.go
- tests/robustness/makefile.mk
The old leader demotes lessor and all the leases' expire time will be updated. Instead of returning incorrect remaining TTL, we should return errors to force client retry.
Fixes: #17506
> *: LeaseTimeToLive returns error if leader changed

- Documentation/contributor-guide/release.md
- scripts/release.sh
We recently released etcd `v3.5.13`. This pull request captures lessons from the release to ensure future releases can be smoother.
1. Versions specified on the release script must not be prefixed.
2. Git remote should be ssh format since pushing to github with https requires tokens now.
3. Network timeouts can occur pushing images, but it is safe to re-run the script.
4. Release script requires signing tags with gpg keys, ssh signing is not supported yet.
> Fix release git url & document lessons learned

- tools/.golangci.yaml
Address the warning "The configuration option `run.skip-files` is deprecated, please use `issues.exclude-files`.", as seen in this [CI run log](https://github.com/etcd-io/etcd/actions/runs/8517852373/job/23329049363#step:6:29)
> Replace run.skip-files with issues.exclude-files in golangci config

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
changelog update for PRs https://github.com/etcd-io/etcd/pull/17641 and https://github.com/etcd-io/etcd/pull/17692.
> changelog: add requests retry when receiving ErrGPRCNotSupportedForLearner

- server/storage/backend/batch_tx.go
- bbolt v.1.4.0-alpha has deprecated error in errors.go and introduce new error package
- This PR will change from using deprecated error to new error package
> server/storage: change deprecated bolt error to new error package

- client/v3/client.go
Tested against the demo code provided in PR #17001
References:
- #17001
- #17018
> Backport initialization of mu in NewCtxClient to release-3.5

- client/v3/retry_interceptor.go
Backport of PR https://github.com/etcd-io/etcd/pull/12985
> [3.5] backport for fix retry requests when receiving ErrGPRCNotSupportedForLearner

- clientv3/retry_interceptor.go
Backport of PR https://github.com/etcd-io/etcd/pull/12985
> [3.4] backport for fix retry requests when receiving ErrGPRCNotSupportedForLearner

- .github/workflows/tests-template.yaml
- Makefile
- build.sh
- go.sum
- server/etcdserver/v3_server.go
- server/lease/leasehttp/http.go
- server/lease/lessor.go
- test.sh
- tests/go.mod
- tests/go.sum
- tests/integration/v3_lease_test.go
* Enable failpoints for integration
* Cherry-pick: #17642
> [3.5] *: LeaseTimeToLive returns error if leader changed

- .github/workflows/tests.yaml
- Makefile
- build
- etcdserver/v3_server.go
- go.mod
- go.sum
- integration/v3_lease_test.go
- lease/leasehttp/http.go
- lease/lessor.go
- test
* Enable failpoints for integration
* Cherry-pick: https://github.com/etcd-io/etcd/pull/17642
> [3.4] *: LeaseTimeToLive returns error if leader changed

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
> CHANGELOG: update for LeaseTimeToLive returns error if leader changed

- tools/benchmark/cmd/put.go
hashKV checks nilness of 'eh' and 'es', but doesn't use them. Instead
it panics with 'err' which is definitely nil.
This should be avoided, See:
https://pkg.go.dev/golang.org/x/tools/go/analysis/passes/nilness#nilpanic
This patch renames 'eh' and 'es' to 'err' in order to correct the real
errors to panic.
> tools/benchmark/cmd: don't panic with nil values in hashKV function

- scripts/codecov_upload.sh
With the update to Go 1.22.2, this workaround is no longer needed.
This reverts commit da7ab15f80c06373e03267e11497da71a028a3aa.
Fixes #17560.
> Revert "tests: temporary disable coverage redesign Go experiment"

- tests/robustness/main_test.go
- tests/robustness/validate/operations.go
- tests/robustness/validate/validate.go
- tests/robustness/validate/validate_test.go
As part of https://github.com/etcd-io/etcd/issues/15598 I was working on re-implementing the history patching to avoid too much space explosion. One thing I noticed that it's not easy to reproduce linearization timeout if patching is totally disabled.
To ensure that patching is working and helping reduce the runtime, I have generated and added a case to `TestValidation` that is expected to run over 5 minutes without any patching
> Limit a timeout in testing robustness validation

- .github/workflows/gh-workflow-approve.yaml
Releated: https://github.com/etcd-io/etcd/pull/17616#pullrequestreview-1948121446
Actually, this config is not work for `release3.5` and `release3.4`, we need let this workflow  file exist at `release-3.5`.
https://github.com/etcd-io/etcd/blob/6f55dfa26e1a359e47e1fb15af79951e97dbac39/.github/workflows/gh-workflow-approve.yaml#L9-L12
Once this PR is merged, we can verify on https://github.com/etcd-io/etcd/pull/17616
> [3.5] Add approvals gh workflows.

- server/wal/encoder.go
- server/wal/metrics.go
xref. #17615 
add new metrics: _**wal_write_duration_seconds**_
**_wal_write_duration_seconds_** represent total delay of: 
> syscall.write(padding_info + record_data_with_padding)
- delay of fsync is not included in _**wal_write_duration_seconds**_
- data: the raft log to write to the WAL on disk at one single raftNode loop
> [3.5] feat: add wal write system call metrics observation

- .github/workflows/release.yaml
Supercedes #17744 and #17743. The two dependencies must be updated simultaneously as they're not backward compatible.
> dependency(gh_action): bump upload and download artifact from 3 to 4

- tests/e2e/ctl_v3_test.go
- tests/e2e/etcd_mix_versions_test.go
- tests/e2e/etcd_release_upgrade_test.go
- tests/framework/e2e/cluster.go
- tests/framework/e2e/config.go
- tests/framework/e2e/etcd_process.go
- tests/framework/e2e/etcdctl.go
- tests/framework/e2e/flags.go
Part of https://github.com/etcd-io/etcd/issues/15878#issuecomment-1910886682
Original PR: https://github.com/etcd-io/etcd/pull/14707 and https://github.com/etcd-io/etcd/pull/15013
Slightly different from the tests in main in that we cannot verify a snapshot is sent because there is no `snapshot-catchup-entries` flag in 3.5.
> [3.5] backport mix version e2e test.

- tests/robustness/makefile.mk
cc @ahrtr @jmhbnz @MadhavJivrajani @siyuanfoundation
> Don't cache test-robustness-reports

- tools/benchmark/cmd/mvcc-put.go
> fix: close profile in the mvccPutFunc func

- tests/e2e/etcd_mix_versions_test.go
follow up https://github.com/etcd-io/etcd/pull/17531 to make code more consistent between 3.5 and main.
> test: refactor mix_version_test.

- tests/robustness/model/deterministic.go
- tests/robustness/model/history.go
- tests/robustness/report/client.go
- tests/robustness/report/client_test.go
- tests/robustness/traffic/client.go
- tests/robustness/traffic/traffic.go
- tests/robustness/validate/patch_history.go
- tests/robustness/validate/patch_history_test.go
cc @ahrtr @jmhbnz @MadhavJivrajani @siyuanfoundation 
Hope this will help debugging of arm64 failures. I expect the reason behind low QPS on arm is request timeout, currently set to 40ms. It's possible a lot of read request timeout due to lower single core performance. This PR will calculate a request success rate so we can confirm that.
> [Robustness] Collect failed read operations to calculate request success rate

- tests/robustness/traffic/traffic.go
- tests/robustness/validate/validate.go
cc @MadhavJivrajani @ahrtr @siyuanfoundation
Started using https://github.com/etcd-io/etcd/pull/17733 and imminently make a mistake of copying one report over another. This results in strange errors and linearization visualization. It took me more time than I want to admit to identify the problem.
Adding validation of assumptions that should always be true if report comes directly from robustness test run. This should re-evaluation of reports more user friendly by providing clear errors.
> Add explicit checks for assumptions in robustness test validation

- server/embed/config.go
- server/etcdmain/help.go
> etcdserver: updated pre-vote flag description

- scripts/measure-testgrid-flakiness.sh
- tools/testgrid-analysis/cmd/data.go
- tools/testgrid-analysis/cmd/flaky.go
https://github.com/etcd-io/etcd/issues/17773
> testgrid: print out all failed tests for visibility.

- tools/etcd-dump-db/backend.go
Previous output:
```
$ ./etcd-dump-db iterate-bucket /tmp/db key --decode
rev={main:431 sub:0}, value=[key "/registry/pods/default/cGyPD" | val "295" | created 52 | mod 431 | ver 3]
rev={main:430 sub:0}, value=[key "/registry/pods/default/4JCLw" | val "294" | created 42 | mod 430 | ver 4]
rev={main:429 sub:0}, value=[key "/registry/pods/default/b4liI" | val "" | created 0 | mod 0 | ver 0]
```
New output (added `tombstone`):
```
$ ./etcd-dump-db iterate-bucket /tmp/db key --decode
rev={Revision:{Main:431 Sub:0} tombstone:false}, value=[key "/registry/pods/default/cGyPD" | val "295" | created 52 | mod 431 | ver 3]
rev={Revision:{Main:430 Sub:0} tombstone:false}, value=[key "/registry/pods/default/4JCLw" | val "294" | created 42 | mod 430 | ver 4]
rev={Revision:{Main:429 Sub:0} …
```
> Enhance the etcd-dump-db: reuse revision in package mvcc

- tests/robustness/main_test.go
- tests/robustness/report/wal.go
- tests/robustness/validate/patch_history.go
- tests/robustness/validate/patch_history_test.go
- tests/robustness/validate/validate.go
- tests/robustness/validate/validate_test.go
Ref https://github.com/etcd-io/etcd/issues/15598
> Robustness wal

- tests/robustness/validate/validate_test.go
- tests/robustness/validate/watch.go
cc @MadhavJivrajani @ahrtr @siyuanfoundation
Noticed that watch validation allows just an empty streams. The current validation is:
* `validateReliable` checks `if there are events ordered in time as a < b < c, then if the watch receives events a and c, it is guaranteed to receive b`.
* `validateResumable` checks watch request that should start from specified revision, this allows us to check that first event in the watch stream. The `a` in `a < b < c`.
As watch is eventually consistent it means that watch streams can just finish early and be empty. To make all the pieces we need something to guarantee the `c` in `a < b < c`.
Here is where `validateBookmarkable` could help. It's the only way to be sure that we got events up to some revision. Bookmarkable should guarantee that all events …
> Validate bookmarkable checks the last event before progress notify

- server/etcdmain/grpc_proxy.go
As the doc is saying:
Deprecated: NameToCertificate only allows associating a single certificate
with a given name. Leave that field nil to let the library select the first
compatible chain from Certificates.
> server/etcdmain: eliminate deprecated tlsConfig.BuildNameToCertificate()

- server/embed/config.go
- server/embed/util.go
- server/etcdmain/config_test.go
Addresses issues with `config.{TLSMinVersion,TLSMaxVersion,WALDir,MaxWALFiles}`.
This is part 1 of 2 from `server/embed`, as it's the package with the most changes.
> server/embed: address golangci var-naming issues

- server/etcdserver/server.go
- server/etcdserver/server_test.go
References: 
- https://github.com/etcd-io/etcd/issues/17081
- https://github.com/etcd-io/etcd/pull/17078
> [backport-3.5] server: ignore raft messages if member id mismatch

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
Fix https://github.com/etcd-io/etcd/pull/17813#pullrequestreview-2008260907 raised by @ahrtr 
Reference:
- https://github.com/etcd-io/etcd/pull/17814
- https://github.com/etcd-io/etcd/pull/17813
> Update CHANGELOG 3.4 and 3.5 - ignore raft messages if member id mismatch

- server/embed/config.go
- server/etcdmain/config.go
- server/etcdmain/config_test.go
- tests/e2e/etcd_mix_versions_test.go
- tests/framework/e2e/cluster.go
https://github.com/etcd-io/etcd/issues/17752
This is import prerequisite to verify that in a mixed version cluster, the follower receives a snapshot that has the correct schema for that version. 
Did not add the flag to help file so that it is a hidden flag that only is used for testing.
> [3.5] add experimental-snapshot-catchup-entries flag

- server/auth/range_perm_cache.go
Not a big deal, but to make this function clearer.
> server/auth: simplify code for isValidPermissionRange

- server/storage/mvcc/kvstore.go
Two changes:
- Print the "`resume scheduled compaction`" only when the `compactLockfree` is successful.
- Actually the compact() never return an error, so remove the second return parameter.
Link to https://github.com/etcd-io/etcd/issues/17780#issuecomment-2056558562
> Update the compaction log when bootstrap and update compact's signature

- tests/robustness/validate/validate_test.go
- tests/robustness/validate/watch.go
Validate delivery of events between progress notifies. https://github.com/etcd-io/etcd/pull/17771 prevented empty streams for revision ranges between watch requiring revision and progress notify. This missed one more case, ranges between two progress notifies. This PR extends reliable validation to validate whole ranges. 
Simplifying bookmarkable to just validate revision order between events
and progress notifies.
Use reliable to validate if events are missing, but still report
broken resumable if first event after revision is missing. It's easier
to have one place that validates event slices.
> Validate revisions between progress notify

- server/storage/mvcc/kvstore.go
Link to https://github.com/etcd-io/etcd/issues/17780#issuecomment-2056558562
It could be one of the possible reason for the "mvcc: required revision is a future revision" error.
> Add verification that the revision shouldn't decrease on bootstrap

- tests/robustness/failpoint/failpoint.go
- tests/robustness/main_test.go
- tests/robustness/report/client.go
- tests/robustness/traffic/traffic.go
Fixes https://github.com/etcd-io/etcd/issues/17775
cc @ahrtr @siyuanfoundation @fuweid @MadhavJivrajani
> Don't require minimal for failpoint injection period

- server/storage/mvcc/kvstore.go
- tests/e2e/reproduce_17780_test.go
> [RFC] fix revision loss issue caused by compaction - 17780

- server/mvcc/kvstore.go
Backport https://github.com/etcd-io/etcd/pull/17792
> [3.5] Update the compaction log when bootstrap and update compact's signature

- etcdserver/api/membership/cluster.go
- etcdserver/api/membership/cluster_test.go
- etcdserver/server.go
https://github.com/etcd-io/etcd/issues/17818
Tested with 1 server cluster downgrade
```bash
bin/etcd
curl http://127.0.0.1:2379/version
>> {"etcdserver":"3.5.13","etcdcluster":"3.5.0"}
../etcd-3.4/bin/etcd --next-cluster-version-compatible
>> ...
>> mvcc: downgrade meta bucket: remove keys [confState, term]
>> ...
>> etcdserver/membership: updated the cluster version from 3.5 to 3.4
curl http://127.0.0.1:2379/version
>> {"etcdserver":"3.4.31","etcdcluster":"3.4.0"}
```
> [3.4] Allow updateClusterVersion when downgrading from 3.5.

- server/config/v2_deprecation.go
- server/config/v2_deprecation_test.go
- server/embed/config.go
- server/etcdmain/config.go
- server/etcdmain/help.go
- server/storage/util.go
Addresses issues in V2 Deprecation constant names. The current constants are in upper snake_case; use Go's camelCase and deprecate their old names.
> server/config: address golangci var-naming issues

- tests/robustness/main_test.go
- tests/robustness/report/report.go
- tests/robustness/report/wal.go
Discovered turning off LazyFS before creating the report might result in empty server directory. This PR moves cluster shutdown to defer executed after we generate report and copies the data from lazyfs directory.
cc @MadhavJivrajani @siyuanfoundation @fuweid
> Persist member data with lazyfs enabled

- server/mvcc/kvstore.go
- server/mvcc/kvstore_compaction.go
- tests/e2e/reproduce_17780_test.go
Backport:
* https://github.com/etcd-io/etcd/pull/17815
* https://github.com/etcd-io/etcd/pull/17862
> [3.5] fix revision loss issue caused by compaction - 17780

- etcdutl/etcdutl/snapshot_command.go
- tests/common/status_test.go
- tools/etcd-dump-logs/etcd-dump-log_test.go
- tools/etcd-dump-logs/raw_test.go
This is the last PR from #17578, before enabling the linter. Addresses miscellaneous violations in `etcdutl`, `tools/etcd-dump-logs`, and `tests/common`.
> Address remaining var naming linter warnings

- server/etcdserver/api/capability.go
`v` is the version the code want to change the `curVersion` so it should be the `verTo` when calling `IsValidClusterVersionChange`.
This should be a no-op change because Capability does not really change in 3.x. 
> fix version order when calling IsValidClusterVersionChange in UpdateCapability

- server/proxy/tcpproxy/userspace.go
- server/proxy/tcpproxy/userspace_test.go
formatAddr is just like net.JoinHostPort, I think we can use net.JoinHostPort
directly, it's simpler and clearer.
> server/proxy/tcpproxy: use net.JoinHostPort rather than formatAddr

- mvcc/kvstore.go
- mvcc/kvstore_compaction.go
- tests/e2e/cluster_test.go
- tests/e2e/reproduce_17780_test.go
Backport:
* https://github.com/etcd-io/etcd/pull/17815
* https://github.com/etcd-io/etcd/pull/17862
NOTE: 
I didn't see the log in main branch. It seems that etcd replays the WAL after restart.
Run the command `EXPECT_DEBUG=true CPU=4 FAILPOINTS='true' make test-e2e GO_TEST_FLAGS="-run TestReproduce17780 -count=1 -v"` and will see that following log.
```plain
// restored compaction 
../../bin/etcd-413597: 2024-04-24 11:27:46.450662 I | mvcc: resume scheduled compaction at 11
// replay WAL
../../bin/etcd-413597: 2024-04-24 11:27:46.500414 W | etcdserver: failed to apply request "compaction:<revision:11 physical:true > header:<ID:5939560774486836239 > " with response "" took (11.026µs) to execute, err …
```
> [3.4] fix revision loss issue caused by compaction - 17780 

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
Fix: Revision decreasing after panic during compaction - #17780
> CHANGELOG: update 3.4 and 3.5 with fix

- client/pkg/transport/timeout_transport_test.go
- etcdctl/ctlv3/command/printer_simple.go
- etcdutl/snapshot/v3_snapshot.go
- server/etcdserver/api/etcdhttp/peer_test.go
- server/etcdserver/cluster_util.go
- server/etcdserver/corrupt.go
- server/etcdserver/corrupt_test.go
- server/lease/leasehttp/http.go
- server/storage/backend/backend.go
- server/storage/backend/batch_tx_test.go
- tests/integration/clientv3/naming/resolver_test.go
- tests/integration/snapshot/member_test.go
- tests/integration/snapshot/v3_snapshot_test.go
- tests/integration/v3_failover_test.go
This is unnecessary, as the documentation for 'go doc fmt' says:
%s the uninterpreted bytes of the string or slice
> all: don't convert byte slice to string when using verb %s

- tests/framework/e2e/etcd_process.go
This PR introduces showing the error message returned by gofail HTTP endpoints, making debugging easier.
Also apply simplified `Enabled()` logic, as suggested by the linter
> gofail: show error messages returned by gofail HTTP endpoints

- scripts/test_lib.sh
- tools/testgrid-analysis/cmd/data.go
- tools/testgrid-analysis/cmd/github.go
> Test: add tools/rw-heatmaps & tools/testgrid-analysis to module_dirs

- .github/workflows/robustness-template.yaml
Robustness tests require a larger instance size, which user forks cannot access. It also tries to trigger an ARM64 build that runs on actuated infrastructure. By not running them on user forks, contributors won't be notified that their builds are failing due to timeouts trying to run the job, while the tests will still run on etcd-io/etcd pull requests and commits.
Part of #17912 
> github/workflows: skip robustness tests in forks

- tests/e2e/etcd_mix_versions_test.go
- tests/framework/e2e/cluster.go
Uncomment the test now that 3.4.32 is released.
> [3.5] add mix version test of adding last ver to current ver.

- server/etcdserver/api/etcdhttp/health.go
- server/storage/datadir/datadir.go
- server/storage/util.go
The deprecation tag/comment must be followed by an empty line, as prompted in https://github.com/etcd-io/etcd/pull/17674#discussion_r1554831812.
> Fix deprecation comments from addressing var-naming work

- server/etcdserver/server.go
- server/etcdserver/util.go
- tests/common/member_test.go
Fixes #17653
Why the test failed?
The [quorum](https://github.com/etcd-io/etcd/blob/a7f5d4b4e4569bd316277ebf1347785e0467c64d/server/etcdserver/server.go#L1597) was not reached because one member was "down".
Why was one node "down"?
It wasn't, actually. The node connected outside `HealthInterval`:
`2024-03-25T17:44:33.8754342Z {"Time":"2024-03-25T17:44:33.830596472Z","Action":"output","Package":"go.etcd.io/etcd/tests/v3/common","Test":"TestMemberRemove/StrictReconfigCheck/WaitForQuorum/PeerAutoTLS","Output":"/home/runner/work/etcd/etcd/bin/etcd (TestMemberRemoveStrictReconfigCheckWaitForQuorumPeerAutoTLS-test-0) (58753): {\"level\":\"info\",\"ts\":\"2024-03-25T17:44:33.825435Z\",\"caller\":\"rafthttp/peer_status.go:53\",\"msg\":\"peer became …
> Fix remove member failed.

- proxy/grpcproxy/cluster.go
- proxy/grpcproxy/cluster_test.go
If grpc starts with `--resolver-prefix`, its memberlist will return all alive proxy nodes. When one GRPC proxy node goes down, it shouldn't return that node. However, it's returned.
Backport of PR #15907 / commit ecfed91e5050431385961573e5c09658a66a59d5.
Part to #17887.
> [3.4] fix grpc proxy member list not updated with node deletion

- CHANGELOG/CHANGELOG-3.4.md
> changelog/3.4: add fix for member list not updated when node goes down

- server/etcdmain/grpc_proxy.go
- server/etcdserver/api/v3rpc/grpc.go
Follow up from #17892. Use gRPC chain interceptor functions from grpc package instead of github.com/grpc-ecosystem/go-grpc-middleware (server interceptor chain helpers deprecated in [v1.4.0](https://github.com/grpc-ecosystem/go-grpc-middleware/releases/tag/v1.4.0))
Ref #17883
> Chore: Use chain interceptors from grpc package

- OWNERS
This pull request updates our `OWNERS` file to reflect https://github.com/kubernetes/org/pull/4838.
> Update jmhbnz project role in owners

- Documentation/contributor-guide/release.md
Installation of `gsutil` asks about picking a cloud proejct from a list of projects that one has access to along with an option to create a new project. Clarifying the name here would be helpful.
> Add etcd cloud project name

- server/etcdserver/bootstrap.go
Corrected to `bootstrappedCluster`.
> Fix typo bootstrapedCluster

- Makefile
Define a Python virtual environment to install `yamllint`, if not installed locally, in a temporary directory and delete it after the run of the `verify-yamllint` command. This avoids the issue of building the build of materials that doesn't follow symlinks in the virtual environment directory.
Fixes #17936.
Related to:
* kubernetes/test-infra#32563
* #17637 
* #17929
> make: fix running fix target after verify

- .github/workflows/static-analysis.yaml
The golangci-lint-action step runs only on the repository's top-level directory. Then, `make verify` reruns it on the same directory, which is redundant.
However, to keep `make verify` target working, `golangci-lint` needs to be installed locally.
Fixes #17929
> github/workflows: remove golangci-lint-action step from static-analysis

- server/config/config.go
- server/embed/config.go
- server/embed/etcd.go
- server/etcdmain/config.go
- server/etcdmain/help.go
- server/etcdserver/api/v3client/v3client.go
- server/etcdserver/api/v3rpc/grpc.go
- server/etcdserver/api/v3rpc/health.go
- server/etcdserver/api/v3rpc/maintenance.go
- tests/e2e/failover_test.go
- tests/framework/e2e/cluster.go
- tests/framework/e2e/etcdctl.go
gRPC health server sets serving status to NOT_SERVING on defrag.
Backported from 3.6 in #16278
---
would be awesome to have this available in 3.5 already, we ran into this recently with a performance test when running etcd with 38 gigs.
> [3.5] gRPC health server sets serving status to NOT_SERVING on defrag

- etcd.conf.yml.sample
- server/embed/config.go
- server/embed/config_test.go
Allow setting AllowedCN and AllowedHostname tls fields through the config file for peer transport security.
Closes: #17867
> config: support AllowedCN and AllowedHostname through config file

- pkg/report/timeseries.go
This patch eliminates the minDuration and maxDuration functions, simplifies the code.
> pkg/report: make use of builtin min/max function

- Makefile
- api/go.mod
- client/internal/v2/go.mod
- client/pkg/go.mod
- client/v3/go.mod
- etcdctl/go.mod
- etcdutl/go.mod
- pkg/go.mod
- scripts/fix.sh
- scripts/sync_go_toolchain_directive.sh
- scripts/test_lib.sh
- scripts/verify_go_versions.sh
- server/go.mod
- tests/go.mod
- tools/rw-heatmaps/go.mod
- tools/testgrid-analysis/go.mod
This PR does the following:
Additionally, provide ability to opt-out of the .go-version and use a
custom one via env vars: FORCE_HOST_GO and GO_VERSION.
This commit adds a script to sync the version present in .go-version
across all go.mod files as the toolchain directive. As part of that,
this commit also modifies go.mod files that did not have synced toolchain
directives.
Additionally, this also adds a script to verify all toolchain and go
directives against the version present in .go-version as follows:
(1) The go directive <= version in .go-version
(2) The toolchain directive == version in .go-version
The make target for this script is run as part of `make verify` which will automatically be run as a presubmit.
/assign @ahrtr @jmhbnz @serathius
> [RFC] Setup a way to consistently manage go versions across scripts and go.mods

- tests/robustness/client/client.go
- tests/robustness/failpoint/cluster.go
- tests/robustness/failpoint/failpoint.go
- tests/robustness/failpoint/gofail.go
- tests/robustness/failpoint/kill.go
- tests/robustness/failpoint/network.go
- tests/robustness/failpoint/trigger.go
- tests/robustness/main_test.go
- tests/robustness/traffic/etcd.go
- tests/robustness/traffic/kubernetes.go
- tests/robustness/traffic/traffic.go
- tests/robustness/validate/patch_history.go
- tests/robustness/watch.go
cc @fuweid @siyuanfoundation @MadhavJivrajani
> Robustness operations failpoints

- tests/robustness/validate/operations.go
- tests/robustness/validate/operations_test.go
- tests/robustness/validate/patch_history.go
- tests/robustness/validate/patch_history_test.go
- tests/robustness/validate/validate.go
- tests/robustness/validate/validate_test.go
- tests/robustness/validate/watch.go
cc @fuweid @siyuanfoundation @MadhavJivrajani
> Add tests to serializable operations validation

- tests/robustness/validate/validate.go
This assumption is not true during durability issues like #14370. In reality we want to avoid situations where WAL is was truncated, for that it's enough that we ensure that first and last operations are present.
Found it when running `make test-robustness-issue14370` and instead of getting `Model is not linearizable` I got that assumptions were broken, which is harder to understand.
cc @siyuanfoundation @MadhavJivrajani @fuweid
> Relax assumptions about all client request persisted in WAL to only require first and last request to be persisted

- etcdctl/ctlv3/command/snapshot_command.go
- etcdutl/etcdutl/snapshot_command.go
- etcdutl/snapshot/v3_snapshot.go
- server/mvcc/backend/backend.go
This PR backports #17277
Part of #16052.
> [3.5] backport etcdutl memory allocation issue

- CHANGELOG/CHANGELOG-3.5.md
Add 3.5 release note from #17977, backporting #17277.
Fixes #16052.
> changelog: add note from #17977 backport

- .github/workflows/OWNERS
- Documentation/OWNERS
- client/v3/OWNERS
- contrib/OWNERS
- contrib/mixin/OWNERS
- etcdctl/OWNERS
- etcdutl/OWNERS
- security/OWNERS
- tests/OWNERS
- tests/robustness/OWNERS
- tools/OWNERS
- tools/benchmark/OWNERS
- tools/etcd-dump-db/OWNERS
- tools/etcd-dump-logs/OWNERS
- tools/etcd-dump-metrics/OWNERS
- tools/local-tester/OWNERS
- tools/rw-heatmaps/OWNERS
- tools/testgrid-analysis/OWNERS
This pull request proposes adding an initial set of nested `OWNERS` files with `labels:` populated in order to automate labeling for pull requests now that we have enabled the `owners-label` prow plugin in https://github.com/kubernetes/test-infra/pull/32589.
I've structured the `OWNERS` files with the assumption that inheritance works, we need to test/verify this.  For example, a pull request for `tools/rw-heatmaps` should in theory be allocated both the `area/tooling` and `area/performance` labels based on the inheritance.
Moving forward we can also use the nested `OWNERS` files to further delegate approvers and reviewers for specific directories of `etcd-io/etcd` code.
Fixes: https://github.com/etcd-io/etcd/issues/17970
> Add nested owners files to automate labeling pull requests

- tests/robustness/failpoint/network.go
- tests/robustness/main_test.go
- tests/robustness/scenarios.go
Overdid it in https://github.com/etcd-io/etcd/pull/17967
cc @MadhavJivrajani  for fast review.
> Prevent picking a failpoint that waiting till snapshot that doesn't support lower snapshot catchup entries but allow reproducing issue #15271

- .github/workflows/codeql-analysis.yml
- .github/workflows/release.yaml
- .github/workflows/scorecards.yml
Pull Request #17679 added the trivy scan workflow. The `code-action/upload-serif` action pointed to the right commit but had a different version in the comment. This PR points it to the right version and the dependency update from 3.25.3 to 3.25.5.
It supersedes #18001.
> dependency(gh_actions): Manually bump codeql action from 3.25.3 to 3.25.5

- tests/robustness/validate/operations.go
- tests/robustness/validate/operations_test.go
This is a follow-up PR regarding the previous conversation. -> https://github.com/etcd-io/etcd/pull/17918#discussion_r1588334682
> add error constants in validate pkg

- .github/workflows/static-analysis.yaml
- Makefile
- go.mod
- scripts/sync_go_toolchain_directive.sh
- scripts/verify_go_versions.sh
- tools/mod/go.mod
Replicating https://github.com/etcd-io/etcd/pull/17876 
This commit adds a script to sync the version present in .go-version across all go.mod files as the toolchain directive. As part of that, this commit also modifies go.mod files that did not have synced toolchain directives.
Additionally, this also adds a script to verify all toolchain and go directives against the version present in .go-version as follows: (1) The go directive <= version in .go-version
(2) The toolchain directive == version in .go-version
This script runs as part of the `make verify` target, making it run as a presbumit by default.
/assign @ahrtr
> [release-3.4]  Setup a way to consistently manage go versions across scripts and go.mods

- .github/workflows/static-analysis.yaml
- Makefile
- api/go.mod
- client/pkg/go.mod
- client/v2/go.mod
- client/v3/go.mod
- etcdctl/go.mod
- etcdutl/go.mod
- go.mod
- pkg/go.mod
- raft/go.mod
- scripts/sync_go_toolchain_directive.sh
- scripts/test_lib.sh
- scripts/verify_go_versions.sh
- server/go.mod
- tests/go.mod
- tools/mod/go.mod
Replicates https://github.com/etcd-io/etcd/pull/17876
This PR does the following:
scripts: default to using .go-version's version for tests and builds
Additionally, provide ability to opt-out of the .go-version and use a
custom one via env vars: FORCE_HOST_GO and GO_VERSION.
.*: sync go toolchain version and add ability to verify versions
This commit adds a script to sync the version present in .go-version
across all go.mod files as the toolchain directive. As part of that,
this commit also modifies go.mod files that did not have synced toolchain
directives.
Additionally, this also adds a script to verify all toolchain and go
directives against the version present in .go-version as follows:
(1) The go directive <= version in .go-version
(2) The toolchain directive == version in …
> [release-3.5] Setup a way to consistently manage go versions across scripts and go.mods

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
Updates 3.4 and 3.5 CHANGELOGs to add a line that the binaries are compiled with go version 1.21.10
Related to #17964 
> changelog:  add 3.4 and 3.5 note about go 1.21.10

- CHANGELOG/CHANGELOG-3.6.md
- server/etcdserver/txn/metrics.go
- server/etcdserver/txn/metrics_test.go
- server/etcdserver/txn/txn.go
- tests/integration/metrics_test.go
This PR is intended to address this issue:
https://github.com/etcd-io/etcd/issues/16866
> etcdserver: add server range duration metrics

- etcdctl/ctlv3/command/printer.go
based on OMC's output for etcdctl endpoint health reporting, add output that includes how much storage is used/not in use and a percentage for better visualization of data within the database. Help with analysis for defrag rates and visual output.
https://github.com/gmeghnag/omc/blob/e97cc10586cefbf0c626ef43b61597730f2b82cf/cmd/etcd/etcdctl.go#L35-L50\
> Update printer.go for used/not-used ETCD storage percentage

- .github/workflows/robustness-template.yaml
- tests/robustness/makefile.mk
To include the mix version scenarios from https://github.com/etcd-io/etcd/pull/17923
https://github.com/etcd-io/etcd/issues/17097
> workflow: change the target of make test-robustness to test-robustness-main

- etcd.conf.yml.sample
- server/embed/config.go
- server/embed/config_test.go
Backport of https://github.com/etcd-io/etcd/pull/17861, resolves https://github.com/etcd-io/etcd/issues/17867.
Blocks v3.5.14 release: https://github.com/etcd-io/etcd/issues/18013
This backport allows setting AllowedCN and AllowedHostname tls fields through config file for peer transport security.
> [3.5] config: support AllowedCN and AllowedHostname through config file

- CHANGELOG/CHANGELOG-3.5.md
This PR will update the CHANGELOG-3.5.md with the inclusion of backport PR https://github.com/etcd-io/etcd/pull/18063 for  v3.5.14 release 
> CHANGELOG: add support AllowedCN and AllowedHostname

- CHANGELOG/CHANGELOG-3.5.md
Part of #18013. Set the v3.5.14 release date to today.
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#contribution-flow
> Update release date for v3.5.14

- scripts/release.sh
Minor improvement that was identified when releasing v3.5.14.
Related to #18013.
> scripts/release: shallow clone repository

- server/embed/config.go
- server/go.mod
This still allows the errors to be unwrapped, and drops the direct dependency on multierr.
> Use Go 1.20 error joining instead of multierr

- etcdutl/README.md
- etcdutl/ctl.go
- etcdutl/etcdutl/hashkv_command.go
- etcdutl/etcdutl/printer.go
- etcdutl/etcdutl/printer_fields.go
- etcdutl/etcdutl/printer_json.go
- etcdutl/etcdutl/printer_simple.go
- etcdutl/etcdutl/printer_table.go
- server/storage/mvcc/hash.go
- server/storage/mvcc/hash_test.go
- server/storage/mvcc/kvstore.go
- server/storage/mvcc/kvstore_test.go
Fixes #15061
```json
% bin/etcdctl endpoint hashkv -w json | jq
[
{
"Endpoint": "127.0.0.1:2379",
"HashKV": {
"header": {
"cluster_id": 14841639068965180000,
"member_id": 10276657743932975000,
"revision": 214,
"raft_term": 17
},
"hash": 902327963,
"compact_revision": 150,
"hash_revision": 214
}
}
]
% bin/etcdutl snapshot hashkv default.etcd/member/snap/db -w json | jq
{
"hash": 902327963,
"hashRevision": 214,
"compactRevision": 150
}
```
> cli: Add etcdutl snapshot hashkv command

- client/v3/go.mod
- client/v3/go.sum
- etcdctl/go.sum
- etcdutl/go.mod
- etcdutl/go.sum
- go.mod
- go.sum
- server/go.mod
- server/go.sum
- tests/go.mod
- tests/go.sum
- tools/mod/go.mod
- tools/mod/go.sum
This pull request completes this week's etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit#gid=1394774387) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md). 
Summary of actions
- Bumped
- bump github.com/prometheus/common from 0.53.0 to 0.54.0
- https://github.com/etcd-io/etcd/pull/18118
- https://github.com/etcd-io/etcd/pull/18111
- Closed (fully indirect)
- bump github.com/go-logr/logr from 1.4.1 to 1.4.2
- https://github.com/etcd-io/etcd/pull/18119
- bump github.com/prometheus/procfs from 0.12.0 to 0.15.1
- …
> [2024-06-03] Bump dependency updates identified by dependabot

- tests/e2e/etcd_mix_versions_test.go
- tests/framework/e2e/cluster_test.go
- tests/framework/e2e/etcd_process.go
> test: update CouldSetSnapshotCatchupEntries to use 3.5.14.

- client/pkg/transport/listener.go
- server/embed/config.go
- server/embed/config_test.go
- server/etcdmain/config.go
- server/etcdmain/help.go
- tests/e2e/etcd_config_test.go
From https://github.com/etcd-io/etcd/pull/13460 
We also need the similiar features, and hope etcd can support multiple values for allowed client. Ref https://github.com/tikv/pd/issues/5134
Fixes https://github.com/etcd-io/etcd/issues/11728
> Support multiple values for allowed client and peer TLS identities

- client/pkg/logutil/zap.go
- client/pkg/logutil/zap_test.go
`2024-06-02T01:49:05.536Z` should be `2024-06-02T01:49:05.536000Z`, so precision won't be dropped and it's easier to use string compare when sorting the timestamp. For example `2024-06-02T01:49:05.536Z` should be bigger than `2024-06-02T01:49:05.535123Z` but the former appears first when sorting the strings. 
> The RFC3339Nano format removes trailing zeros from the seconds field and thus may not sort correctly once formatted. 
> A comma or decimal point followed by one or more zeros represents a fractional second, printed to the given number of decimal places. A comma or decimal point followed by one or more nines represents a fractional second, printed to the given number of decimal places, with …
> fix ts with no trailing zeros

- tests/robustness/main_test.go
- tests/robustness/model/deterministic.go
- tests/robustness/model/replay.go
- tests/robustness/report/wal.go
- tests/robustness/traffic/etcd.go
- tests/robustness/traffic/kubernetes.go
- tests/robustness/validate/patch_history.go
We should return token to that bucket if `nonUniqueWriteLimiter.Take()` return true. After unlock Delete/LeaseRevoke ops, the model should be updated for replay function. There are two updates for `toWatchEvents`.
1. When leaveRevokes op has deleted few keys, we should generate `delete-operation` events based on alphabetical order of deleted keys.
2. When putWithLease op hits non-exist lease, we should ignore that update event.
> tests/robustness: unlock Delete/LeaseRevoke ops

- CHANGELOG/CHANGELOG-3.6.md
Add changelog of #18015 for 3.6
> CHANGELOG: support multiple values for allowed client and peer TLS identities

- .github/workflows/coverage.yaml
- codecov.yml
- scripts/test.sh
- add missing directory fixing go.etcd.io/etcd/etcdutl/v3/::etcdutl/
- update codecov config to support commenting in PR
Reference: 
- https://github.com/etcd-io/etcd/issues/18131
- https://docs.codecov.com/docs/unexpected-coverage-changes#reasons-for-indirect-changes
> Update codecov config to support commenting in PR

- .github/workflows/govuln.yaml
This commit fixed the Go Vulnerability Checker CI job, which isn't scanning for all go.mod files within the project.
Reference:
- https://github.com/etcd-io/etcd/discussions/18168
> Fix govulncheck CI check on main branch

- server/storage/wal/metrics.go
bugfix: https://github.com/etcd-io/etcd/pull/17618.
`walWriteSec` should be registered in prometheus.
/cc @Akiqqqqqqq
> bugfix: register of walWriteSec

- CHANGELOG/CHANGELOG-3.5.md
Fully address CVE-2023-45288 and fix govulncheck CI check
Reference: 
- https://github.com/etcd-io/etcd/pull/18170
> Update release-3.5 changelog

- tests/robustness/scenarios.go
https://github.com/etcd-io/etcd/issues/18144
> robustness: Separate compaction and LazyFS test scenario for cluster size 1

- Makefile
- scripts/test.sh
Add a `Makefile` target to run govuln across the submodules. This will allow it to be imported into a prow job and remove the logic from the GitHub workflow file.
Part of #18173.
> Add run-govulncheck Makefile target

- tests/robustness/failpoint/cluster.go
- tests/robustness/failpoint/failpoint.go
- tests/robustness/failpoint/gofail.go
- tests/robustness/failpoint/kill.go
- tests/robustness/failpoint/network.go
- tests/robustness/failpoint/trigger.go
- tests/robustness/main_test.go
- tests/robustness/report/failpoint.go
- tests/robustness/scenarios.go
- tests/robustness/traffic/etcd.go
- tests/robustness/traffic/kubernetes.go
- tests/robustness/traffic/traffic.go
For https://github.com/etcd-io/etcd/issues/18144
cc @siyuanfoundation
> Avoid sending Compact request when LazyFS is enabled

- server/embed/etcd.go
- server/embed/etcd_test.go
- server/etcdmain/help.go
- tests/e2e/etcd_config_test.go
Otherwise, it will fail with
> cannot listen on TLS for 127.0.0.1:8080: KeyFile and CertFile are not presented
We should instead explicitly fail fast, with a clear error message.
Also, adding some documentation how to configure TLS for metrics URLs.
c.f., https://github.com/etcd-io/etcd/issues/8060
> fix(server): enforce listen-metrics-urls client TLS info when its scheme is https/unixs

- server/embed/etcd.go
Follow up https://github.com/etcd-io/etcd/pull/18186#discussion_r1644423850
> Update the error message when client certificate isn't provided for secure metrics url

- tests/robustness/makefile.mk
Recursive `make` commands should always use the variable `MAKE`, as the value of this variable is the file name with which make was invoked
References:
- https://www.gnu.org/software/make/manual/html_node/MAKE-Variable.html
- https://github.com/etcd-io/gofail/pull/69#discussion_r1644163380
> Use $(MAKE) instead of make

- server/embed/config.go
- server/embed/etcd.go
- tests/framework/integration/cluster.go
- tests/integration/clientv3/kv_test.go
- tests/integration/v3_grpc_test.go
This PR introduces GRPCAdditionalServerOptions which allow changing the internal gRPC settings. Sometimes, we may register our own gRPC service into `etcd` and change the `max-request-bytes` might affect the internal etcd logic.
> embed: add `GRPCAdditionalServerOptions` config

- client/pkg/transport/listener.go
- server/embed/config.go
- server/embed/config_test.go
- server/etcdmain/config.go
- server/etcdmain/help.go
- tests/e2e/etcd_config_test.go
cherry pick https://github.com/etcd-io/etcd/pull/18015 to release-3.5
> [3.5] Support multiple values for allowed client and peer TLS identities

- server/storage/mvcc/store.go
Fix typo in mvcc module store.go file
> mvcc: fix typo

- CHANGELOG/CHANGELOG-3.5.md
change log for bugfix https://github.com/etcd-io/etcd/pull/18164.
/cc @ahrtr @ivanvc
> add changelog for bugfix 18164 prometheus metric register of walWriteSec

- client/v3/client.go
It should be helpful to detect issue like https://github.com/etcd-io/etcd/issues/18090
> Add verification on `client.Sync` to ensure the returned endpoints never empty

- scripts/test.sh
Just noticed we're using a release of `shellcheck` from 2021: https://github.com/koalaman/shellcheck/releases
This pull request bumps us to latest `0.10.0` release which came out in March 2024, looks ok:
```bash
james  ~  D  etcd   main                                                                       last: 0m 0s  11:27:26 
➜ make verify-shellcheck
PASSES="shellcheck" ./scripts/test.sh
Running with --race
Starting at: Mon 24 Jun 2024 11:27:33 NZST
'shellcheck' started at Mon 24 Jun 2024 11:27:33 NZST
Tool: 'shellcheck' not found on PATH. https://github.com/koalaman/shellcheck#installing
Installing shellcheck v0.10.0
shellcheck-v0.10.0/LICENSE.txt
shellcheck-v0.10.0/README.txt
shellcheck-v0.10.0/shellcheck
% './bin/shellcheck' '-fgcc' 'scripts/build-binary.sh' …
```
> Bump shellcheck to latest v0.10.0 release

- CHANGELOG/CHANGELOG-3.6.md
> Update release-3.6 changelog

- tests/robustness/model/describe.go
- tests/robustness/model/deterministic.go
- tests/robustness/model/history.go
- tests/robustness/model/non_deterministic.go
- tests/robustness/model/non_deterministic_test.go
- tests/robustness/validate/operations.go
- tests/robustness/validate/patch_history.go
- tests/robustness/validate/patch_history_test.go
/cc @siyuanfoundation @MadhavJivrajani @fuweid @fykaa @henrybear327
> Separate persisted responses without knowing their revision to prevent duplicating state during linearization

- tests/e2e/watch_test.go
e2e for https://github.com/etcd-io/etcd/issues/18089 
The goal is to reproduce a DELETE event being dropped in a watch after a compaction occurs on the revision where the deletion took place. In order to reproduce this, we perform the following sequence (steps for reproduction thanks to @ahrtr):
- PUT k v2 (assume returned revision = r2)
- PUT k v3 (assume returned revision = r3)
- PUT k v4 (assume returned revision = r4)
- DELETE k (assume returned revision = r5)
- PUT k v6 (assume returned revision = r6)
- COMPACT r5
- WATCH rev=r5
We should get the DELETE event (r5) followed by the PUT event (r6). However, currently we only get the PUT event with returned revision of r6 (key=k, val=v6).
/assign @ahrtr @serathius @siyuanfoundation
> tests/e2e: add e2e test to reproduce issue 18089

- Makefile
- test.sh
Backporting shellcheck installation method to 3.5 as described here: https://github.com/etcd-io/etcd/pull/18216#pullrequestreview-2134426526
Related issue: https://github.com/etcd-io/etcd/issues/17472
> etcd 3.5: Install shellcheck if not exists.

- client/pkg/transport/listener.go
Clean up unnecessary nil Logger for listener.go as pointed out in issue [#18084](https://github.com/etcd-io/etcd/issues/18084)
> etcd-client: Clean up unnecessary nil Logger check

- CHANGELOG/CHANGELOG-3.4.md
The 3.4.33 release date was not set after the tag was pushed. Set it to 2024-06-13.
Part of #18014.
> changelog/3.4: set 3.4.33 release date

- Makefile
- scripts/install-marker.sh
- test
Backporting shellcheck installation method to 3.4 as described here: https://github.com/etcd-io/etcd/pull/18216#pullrequestreview-2134426526
This is based on commit 4f23883 and pull request etcd-io#14872.
Related issue: https://github.com/etcd-io/etcd/issues/17472
Fixed outstanding shellcheck errors [SC2086] by adding double quotes to variables where needed.
> [3.4] Install shellcheck if it is not present

- tests/integration/cluster.go
This PR backports #16523 
Close #16475 
> [3.5] backport deflake TestV3AuthWithLeaseRevokeWithRootJWT

- .github/workflows/govuln.yaml
By running `find -exec`, an error exit code doesn't properly return the error if there's a failure in a command executed. Use `xargs` to force an exit with an error when a command fails to run.
Refer to https://github.com/ivanvc/etcd/actions/runs/9727114371/job/26846300969 for an example of a run that should have failed but didn't.
After updating the workflow to use `xargs`, this is a build with a failure: https://github.com/ivanvc/etcd/actions/runs/9727235294/job/26846574320
Fixes #18173
Related to Slack thread: https://kubernetes.slack.com/archives/C3HD8ARJ5/p1719591918822359
> [3.5] github/govuln: don't swallow govulncheck errors

- server/auth/simple_token.go
Right now the basic auth tokens that are deleted after `--auth-token-ttl` cause info-level logs to be emitted. Change this to debug. This helps with the issue at #18244 where calling `/readyz` frequently pollutes the etcd server logs with this log message.
Fixes #18244.
> Suppress noisy basic auth token deletion log

- etcdctl/README.md
- etcdctl/ctlv3/command/get_command.go
- tests/e2e/ctl_v3_kv_test.go
etcdctl is missing options to modify get opts for WithMinCreateRev, WithMaxCreateRev, WithMinModRev, WithMaxModRev.
> etcdctl: add support for filtering by {min,max} x {create,mod} x {revision}

- tools/mod/go.mod
- tools/mod/go.sum
This PR bumps github.com/prometheus/common from 0.54.0 to 0.55.0 in tools/mod missed in https://github.com/etcd-io/etcd/pull/18266
Dependabot raised raised the following PR:
- https://github.com/etcd-io/etcd/pull/18261
> Follow up manual Dependency Bump

- scripts/test.sh
- tools/mod/go.mod
- tools/mod/go.sum
As tools/mod is not part of the test library's modules, the check to verify consistent dependency versions ignored it. Explicitly get the dependencies from this module when running verify-dep.
Part of #18180 .
> make: Include tools/mod when checking dependency versions

- scripts/release.sh
As outlined in https://github.com/etcd-io/etcd/issues/18013#issuecomment-2140934998 and https://github.com/etcd-io/etcd/issues/18013#issuecomment-2197759674 we have verified our `etcd-development/etcd` bucket in use for `gcr.io` is already fully public and manually verified that new objects pushed to the bucket automatically become public without needing `gsutil acl ...` command run.
This pull request will dramatically reduce output spam from this script when publishing a release which can make it frustrating to scrollback and review output.
We should merge and backport this before `v3.5.15` is released.
Fixes #18013
> Remove gsutil acl command for bucket permissions from release.sh

- CHANGELOG/CHANGELOG-3.5.md
Mention the 0a960a2 backported to 3.5 release in the changelog.
/assign @ivanvc
> Update CHANGELOG-3.5 with backported commit

- Makefile
- clientv3/internal/endpoint/doc.go
- clientv3/internal/resolver/doc.go
- clientv3/naming/endpoints/doc.go
- clientv3/naming/endpoints/internal/doc.go
- clientv3/naming/resolver/doc.go
- etcdserver/cluster_util.go
- etcdserver/etcdserverpb/doc.go
- functional/rpcpb/doc.go
- pkg/grpc_testing/doc.go
- raft/confchange/doc.go
- raft/quorum/doc.go
- raft/raftpb/doc.go
- raft/tracker/doc.go
- test
- wal/walpb/doc.go
This is meant to address the failing revive checks mentioned in this issue: https://github.com/etcd-io/etcd/issues/17472
Screenshot of Revive linter errors:
Output with code changes:
> [3.4] installed revive on CI and added doc.go to fix revive linter errors

- tests/robustness/watch.go
https://github.com/etcd-io/etcd/issues/18276
The head rev match might be to restrictive causing validation flakiness. 
> robustness: remove head rev match in validateGotAtLeastOneProgressNotify

- client/pkg/testutil/leak.go
The Go runtime uses runtime Finalizer to delete cert [[1]]. The interestingGoroutines is able to collect stack like,
```plain
leak.go:103: Found leaked goroutined BEFORE test appears to have leaked :
sync.(*Map).LoadAndDelete(0xc00031e180, {0xe07320, 0xc00009fde0})
/usr/local/go/src/sync/map.go:272 +0x192
sync.(*Map).Delete(...)
/usr/local/go/src/sync/map.go:297
crypto/tls.(*certCache).evict(...)
/usr/local/go/src/crypto/tls/cache.go:73
crypto/tls.(*certCache).active.func1(0x0?)
/usr/local/go/src/crypto/tls/cache.go:65 +0x67
```
It's caused by GC instead of leaky goroutine. interestingGoroutines should skip it.
[1]: https://github.com/golang/go/blob/8e1fdea8316d840fd07e9d6e026048e53290948b/src/crypto/tls/cache.go#L63
Please read https://github.com/etcd-io/etcd/blob/main/CONTRIBUTING.md#con …
> client/pkg/testutil: update interestingGoroutines

- client/v3/watch.go
- client/v3/watch_test.go
> client/v3/watch.go: use `fmt` go pkg for metadata map printing

- client/v3/watch.go
- client/v3/watch_test.go
This PR backports the changes from #18308 PR to the release-3.5 branch.
Addresses Issue #18303 in the backport release-3.5.
> [3.5] client/v3/watch.go: use fmt go pkg for gRPC metadata map printing

- clientv3/watch.go
- clientv3/watch_test.go
This PR backports the changes from #18308 to the release-3.4 branch.
Addresses Issue #18303 in the backport release-3.4.
> [3.4] client/v3/watch.go: use fmt go pkg for gRPC metadata map printing

- .github/workflows/tests.yaml
The pull-etcd-unit-test-amd64, pull-etcd-unit-test-386, pull-etcd-integration-1-cpu-amd64, pull-etcd-integration-2-cpu-amd64, and pull-etcd-integration-8-cpu-amd64 jobs are already running on the prow infrastructure. It is safe to remove these duplicated workloads from GitHub actions.
Fixes #18065
Part of kubernetes/k8s.io#6102
> github: remove amd64 test actions

- server/embed/config_logging.go
- tests/e2e/zap_logging_test.go
etcdserver generates the same warning message "`rejected connection`" when it rejects a connection from the client and from the peer. It isn't good for debugging some connection issue. This PR is trying to generate a different warning message to differentiate client connections and peer connections.
> Differentiate the warning message for rejected client and peer connections

- server/embed/config_logging.go
- tests/e2e/zap_logging_test.go
Backport https://github.com/etcd-io/etcd/pull/18313 to 3.5
> [3.5] Differentiate the warning message for rejected client and peer connections

- CHANGELOG/CHANGELOG-3.5.md
Related to https://github.com/etcd-io/etcd/pull/18319
> CHANGELOG Differentiate the warning message for rejected client and peer connections for release-3.5

- CHANGELOG/CHANGELOG-3.5.md
In this commit, we update the changelog for gRPC metadata printing in release 3.5 which is mainly a backport from PR #18312.
> CHANGELOG/CHANGELOG-3.5.md: update changelog for gRPC metadata printing

- CHANGELOG/CHANGELOG-3.4.md
In this commit, we update the changelog for gRPC metadata printing in release 3.4 which is mainly a backport from PR #18311.
> CHANGELOG/CHANGELOG-3.4.md: update changelog for gRPC metadata printing

- client/pkg/fileutil/purge.go
PR for issue https://github.com/etcd-io/etcd/issues/17565
Proposed improvement to syntax for control flow of `purgeFile` function in `client/pkg/fileutil/purge.go`. 
- go routine accesses single slice `fnamesWithSufix` that remains unmodified.
- `nPurged` variable introduced for for loop in go routine, and for counting writes to `purgeC` channel.
- Remove explicit sorting after suffix filtering, as the provided `ReadDir` method reads directory filenames in sorted order, and sorted order is preserved after suffix filtering.
> fileutil: improve control flow readability of purgeFile function

- scripts/test.sh
The markdown linter, marker, now publishes a released version with the tool. Given that this project is written in Rust, running this check can now be done by using the statically compiled binary without having the Rust local environment.
Part of #18059.
> marker(markdown linter): use released binary when running markdown lint

- server/embed/etcd.go
- server/embed/etcd_test.go
- server/etcdmain/help.go
- tests/e2e/etcd_config_test.go
- tests/e2e/utils.go
This was not a straightforward backport so needs a closer review than normal.
Backports a657f069a1d3be9f04d037789b6b9394d4292306, 22f20a827bc3af96e1deda21792f736bd1c38feb, 497f1a45a3f3730fa94a8af4efa3d4a0e7fa7403 and 3e86af6843568931c281600b962f5ae05ebfc42f from https://github.com/etcd-io/etcd/pull/18186.
Also backports required `tests/e2e/utils.go` elements of 4c77726914401640f03b1371cf011bdf554c20f5 from https://github.com/etcd-io/etcd/pull/17661.
cc @serathius, @ahrtr, @ivanvc
> [3.5] Backport fix(server/embed) enforce non-empty client TLS if scheme is https/unixs

- server/storage/mvcc/key_index_test.go
In commit [[1]], the newTestKeyIndex function creates one key with two Revision{Main: 14} revisions. However, starting from version [[2]], etcd server does not allow duplicate keys in a single transaction. This update to newTestKeyIndex is to avoid confusion and ensure consistency with the latest etcd server behavior.
REF:
[1]: https://github.com/etcd-io/etcd/pull/3558/commits/be80d11948a97450e6769912640099fad63acb1c
[2]: https://github.com/etcd-io/etcd/pull/4376
> mvcc/*_test.go: should not use duplicate revision.Main for one key

- scripts/release.sh
With verification completed during release `v3.5.15` we are certain this improvement is safe so we should now also backport https://github.com/etcd-io/etcd/pull/18250/commits/f0246a9f84f7839825d68511ac65eb52eb24e81d to `release-3.4`.
> The bucket is already fully public so new releases don't need to run this command.
> 
> This will prevent significant terminal spam during the release process as there are thousands of objects in the bucket.
>  [3.4] Remove gsutil acl command for bucket permissions

- pkg/featuregate/feature_gate.go
- pkg/featuregate/feature_gate_test.go
- server/embed/config.go
- server/embed/etcd.go
- server/etcdmain/config_test.go
- server/etcdmain/help.go
- server/features/etcd_features.go
part of https://github.com/etcd-io/etcd/issues/18023
> Add "server-feature-gates" flag.

- client/v3/auth.go
- client/v3/client.go
- client/v3/cluster.go
- client/v3/kubernetes/client.go
- client/v3/kubernetes/interface.go
- client/v3/kv.go
- client/v3/lease.go
- client/v3/maintenance.go
- client/v3/txn.go
- client/v3/watch.go
Matching ticket on Kubernetes side https://github.com/kubernetes/kubernetes/pull/125258
cc @ahrtr @logicalhan
Design: https://docs.google.com/document/d/1-nIpoW87qqQ9FxINOzXPkhu7CD_FWW1piYqHZDr39nU/edit?usp=sharing
Part of https://github.com/etcd-io/etcd/issues/15820
> Introduce Kubernetes interface to etcd client

- server/etcdserver/server.go
@serathius @ahrtr 
Per the suggestion in (https://github.com/etcd-io/etcd/pull/18235#issuecomment-2209038945), I have changed the snapshot and compact operations to a synchronous process for simplification.
As a first step, I just removed `s.GoAttach(func() {})`. 
I will add benchmark results once all tests pass.
> etcdserver: change the snapshot + compact into sync operation

- .github/workflows/robustness-template.yaml
As discovered by the OpenSSF Scorecard, the robustness actions didn't pin dependencies. This pull request fixes that issue.
Part of #18362.
> github/workflows: pin robutness tests dependencies

- server/embed/config.go
- server/embed/config_test.go
part 2 of breaking up https://github.com/etcd-io/etcd/pull/18234 into smaller PRs.
https://github.com/etcd-io/etcd/issues/18023
> Add config file field for feature-gates flag.

- .github/workflows/gh-workflow-approve.yaml
As discovered by the OpenSSF Scorecard, the `gh-workflow-approve.yaml` action didn't specify default permissions. This pull request fixes that issue.
Part of https://github.com/etcd-io/etcd/issues/18362.
> github/workflows: set read-only default permissions to approve workflow

- pkg/wait/wait_time.go
- pkg/wait/wait_time_test.go
Wait time implementation in fact supports a trigger deadline that is greater than or equal to wait deadlines, rather than greater than wait deadlines. Updates docs and a couple tests accordingly.
> Fix wait time docs, tests to indicate trigger deadline geq to wait deadline.

- tests/e2e/hashkv_test.go
Related to https://github.com/etcd-io/etcd/pull/18274
> tests/e2e: add test cases related to HashKV

- tests/robustness/traffic/traffic.go
The `TestRobustnessExploratoryKubernetesHighTrafficClusterOfSize1` has been flaking due to linearization validation timing out.
As per the discussion in https://github.com/etcd-io/etcd/issues/18208 this PR tries to address the linearization timeout issues observed during CI runs by reducing the number of concurrent clients from 12 to 10 in the HighTrafficProfile for robustness tests.
cc: @MadhavJivrajani @serathius @siyuanfoundation
> Reduce client concurrency for high traffic robustness tests

- tests/e2e/hashkv_test.go
Follow-up: https://github.com/etcd-io/etcd/pull/18369#discussion_r1698144827
ping @ahrtr
> tests/e2e: check compactOnRev > tombstoneRevs[0]

- Documentation/contributor-guide/release.md
Update release.md based on 3.5.15 release: https://github.com/etcd-io/etcd/issues/18247#issuecomment-2240080965
> Update release.md to reflect notes taken during 3.5.15 release

- tests/robustness/main_test.go
cc @ahrtr @siyuanfoundation @fuweid @MadhavJivrajani
> Remove flake caused failpoint in watch disrupting progress notifies

- client/pkg/go.mod
- client/pkg/go.sum
- client/v2/go.sum
- client/v3/go.sum
- etcdctl/go.sum
- etcdutl/go.sum
- go.sum
- pkg/go.mod
- pkg/go.sum
- server/go.mod
- server/go.sum
- tests/go.mod
- tests/go.sum
- tools/mod/go.mod
- tools/mod/go.sum
cc @ah8ad3 @ahrtr @siyuanfoundation @fuweid @MadhavJivrajani 
Should remove flakes in robustness test that inject a sleep failpoint into older release that doesn't run new gofail.
> Upgrade gofail to v0.2.0

- bill-of-materials.json
- tests/functional/cmd/etcd-tester/main.go
- tests/go.mod
- tests/go.sum
Cleanup `github.com/etcd-io/gofail`, we should only use the new module `go.etcd.io/gofail`
> [3.5] Cleanup github.com/etcd-io/gofail

- tests/robustness/makefile.mk
Addition of  tools/mod package into older branches moved the source of truth for gofail version, so the existing makefile code stopped overriding changes. This resulted in robustness tests flaking with release of gofail@v0.2.0 that allowed new type of failpoint. 
This PR should help us ensure that gofail version is set properly on older branches.
Before we see `downgraded go.etcd.io/gofail v0.2.0 => v0.1.0` line in the following build logs
```
$ make /tmp/etcd-release-3.5-failpoints/bin 
rm -rf /tmp/etcd-release-3.5-failpoints/
mkdir -p /tmp/etcd-release-3.5-failpoints/
cd /tmp/etcd-release-3.5-failpoints/; \
git clone --depth 1 --branch release-3.5 https://github.com/etcd-io/etcd.git .; \
go get go.etcd.io/gofail@v0.2.0; \
(cd server; go get go.etcd.io/gofail@v0.2.0); \
(cd etcdctl; go …
```
> Ensure proper gofail package version in robustness tests

- etcdctl/ctlv3/command/snapshot_command.go
- etcdctl/util/normalizer.go
- pkg/cobrautl/help.go
Part of https://github.com/etcd-io/etcd/issues/17777.
Add example section into `etcdctl` by first adding it to helper function of cobra.
Create a `util` module into `etcdctl` move helper there.
Add a normalizer function for exmaples.
Change indent of `etcdctl` from `"\t`" to `"  "`.
I tried to keep this PR simple and add only functionality of examples to helper and add examples of snapshot so it can be easy to review. 
/cc @ivanvc @jmhbnz
> Add examples to `etcdctl snapshot` command's help

- pkg/flags/flag.go
- server/config/config.go
- server/embed/config.go
- server/embed/config_test.go
- server/embed/etcd.go
- server/etcdmain/config.go
- server/etcdmain/config_test.go
- server/etcdmain/help.go
- server/etcdserver/api/v3rpc/health.go
- server/features/etcd_features.go
- tests/e2e/failover_test.go
- tests/framework/e2e/cluster.go
- tests/framework/integration/cluster.go
part of https://github.com/etcd-io/etcd/issues/18023, an example of basic wiring from an existing experimental feature flag to the new feature gate.
final step of of breaking up https://github.com/etcd-io/etcd/pull/18234/ into smaller PRs.
> migrate experimental-stop-grpc-service-on-defrag flag to feature gate.

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
Reference: https://github.com/etcd-io/etcd/issues/18419
> Update release-3.4 and release-3.5 CHANGELOG with go version bump

- Documentation/contributor-guide/release.md
This pull request updates our release process to reflect tweaking branch protection settings before and after performing a release.
I also fixed some `markdownlint` errors and tidied a few other areas in the doc.
> Keep release process documentation up to date

- .github/workflows/gh-workflow-approve.yaml
Backports commit: 5a02298ad5a947214ba02655b0a93ac01d4c178a from https://github.com/etcd-io/etcd/pull/18368 to `release-3.5`.
Finishes off one aspect of https://github.com/etcd-io/etcd/issues/18362.
>  [3.5] Backport github/workflows: set read-only default permissions to approve workflow 

- Documentation/contributor-guide/dependency_management.md
This PR will add the troubleshooting step in case of `genproto` errors while manual dependency bumps of `grpc-*` pacakges.
Sample error:
```
[0;31mFAIL: 'genproto' FAILED at Wed Jul 31 07:09:08 UTC 2024
make: *** [Makefile:134: verify-genproto] Error 255
```
Ref: https://github.com/etcd-io/etcd/pull/18384#issuecomment-2260113697
> Add `genproto` error troubleshoot step for manual bumps

- server/etcdserver/raft.go
- server/etcdserver/server.go
- server/etcdserver/server_test.go
Resolve https://github.com/etcd-io/etcd/issues/18069
Will post benchmark result later.
> Skip leadership check if the etcd instance is active processing heartbeats

- server/etcdserver/raft.go
- server/etcdserver/server.go
- server/etcdserver/server_test.go
Backport https://github.com/etcd-io/etcd/pull/18428 to 3.5.
Resolve https://github.com/etcd-io/etcd/issues/18069 in 3.5.
> [3.5] Skip leadership check if the etcd instance is active processing heartbeats

- etcdserver/raft.go
- etcdserver/server.go
- etcdserver/server_test.go
Backport https://github.com/etcd-io/etcd/pull/18428 to 3.4.
Resolve https://github.com/etcd-io/etcd/issues/18069 in 3.4.
> [3.4] Skip leadership check if the etcd instance is active processing heartbeats

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
Linked to,
- https://github.com/etcd-io/etcd/pull/18428
- https://github.com/etcd-io/etcd/pull/18439
- https://github.com/etcd-io/etcd/pull/18440
- https://github.com/etcd-io/etcd/issues/18069
> Update changelog for the performance regression caused by ensureLeadership in leaseRenew

- tests/robustness/traffic/etcd.go
- tests/robustness/traffic/kubernetes.go
- tests/robustness/traffic/traffic.go
Not hitting minimal QPS is expected to be caused by introduction of
compation. Let's avoid it for high throughput test cases.
Reducing number of clients to avoid linearization timeouts.
cc @ah8ad3 @fuweid @MadhavJivrajani @siyuanfoundation
> Reduce number of concurrent clients to 8 and compactions to avoid flakes

- server/storage/mvcc/hash.go
- server/storage/mvcc/index_test.go
- server/storage/mvcc/key_index.go
- server/storage/mvcc/key_index_test.go
- tests/e2e/watch_test.go
Before this patch, the tombstone can be deleted if its revision is equal compacted revision. It causes that the watch subscriber won't get this DELETE event. Based on Compact API [[1]], we should keep tombstone revision if it's not less than the compaction revision.
> CompactionRequest compacts the key-value store up to a given revision.
> All superseded keys with a revision less than the compaction revision
> will be removed.
[1]: https://etcd.io/docs/latest/dev-guide/api_reference_v3/
------------
To Reviewers:
During writing tests, I found that the compact doesn't always remove smaller revision data.
For example,
```
➜  bin/etcdctl put hello world -w json …
```
> *: keep tombstone if revision == compactAtRev

- tests/e2e/v3_lease_no_proxy_test.go
Backport https://github.com/etcd-io/etcd/pull/18450 to 3.4
> [3.4] test: extend leaseRevoke and leaseRenew test to support 5 members cluster

- client/pkg/testutil/leak.go
The Go runtime uses runtime Finalizer to delete cert [[1]]. The interestingGoroutines is able to collect stack like,
```plain
leak.go:103: Found leaked goroutined BEFORE test appears to have leaked :
sync.(*Map).LoadAndDelete(0xc00031e180, {0xe07320, 0xc00009fde0})
/usr/local/go/src/sync/map.go:272 +0x192
sync.(*Map).Delete(...)
/usr/local/go/src/sync/map.go:297
crypto/tls.(*certCache).evict(...)
/usr/local/go/src/crypto/tls/cache.go:73
crypto/tls.(*certCache).active.func1(0x0?)
/usr/local/go/src/crypto/tls/cache.go:65 +0x67
```
It's caused by GC instead of leaky goroutine. interestingGoroutines should skip it.
Backport of #18287
[1]: https://github.com/golang/go/blob/8e1fdea8316d840fd07e9d6e026048e53290948b/src/crypto/tls/cache.go#L63
Please read …
> [3.5] client/pkg/testutil: update interestingGoroutines

- tests/e2e/watch_test.go
The goal is to reproduce a DELETE event being dropped in a watch after a compaction occurs on the revision where the deletion took place. In order to reproduce this, we perform the following sequence (steps for reproduction thanks to @ahrtr):
- PUT k v2 (assume returned revision = r2)
- PUT k v3 (assume returned revision = r3)
- PUT k v4 (assume returned revision = r4)
- DELETE k (assume returned revision = r5)
- PUT k v6 (assume returned revision = r6)
- COMPACT r5
- WATCH rev=r5
We should get the DELETE event (r5) followed by the PUT event (r6). However, currently we only get the PUT event with returned revision of r6 (key=k, val=v6).
(cherry picked from commit ebf2cac6bda38892121585d2467982da54e60ef1)
Part of https://github.com/etcd-io/etcd/pull/18274
Please read …
> [3.5] tests/e2e: add e2e test to reproduce issue 18089

- CHANGELOG/CHANGELOG-3.6.md
Issue : https://github.com/etcd-io/etcd/issues/15061
> CHANGELOG: Add entry for etcdutl hashkv command.

- server/mvcc/key_index_test.go
Backport of #18321
Part of https://github.com/etcd-io/etcd/pull/18274
> [3.5] mvcc/*_test.go: should not use duplicate revision.Main for one key

- mvcc/key_index_test.go
Backport of #18321
Part of https://github.com/etcd-io/etcd/pull/18274
> [3.4] mvcc/*_test.go: should not use duplicate revision.Main for one key

- tests/e2e/watch_test.go
The goal is to reproduce a DELETE event being dropped in a watch after a compaction occurs on the revision where the deletion took place. In order to reproduce this, we perform the following sequence (steps for reproduction thanks to @ahrtr):
- PUT k v2 (assume returned revision = r2)
- PUT k v3 (assume returned revision = r3)
- PUT k v4 (assume returned revision = r4)
- DELETE k (assume returned revision = r5)
- PUT k v6 (assume returned revision = r6)
- COMPACT r5
- WATCH rev=r5
We should get the DELETE event (r5) followed by the PUT event (r6). However, currently we only get the PUT event with returned revision of r6 (key=k, val=v6).
(cherry picked from commit ebf2cac6bda38892121585d2467982da54e60ef1) #18201
Part of #18274 
Please read …
> [3.4] tests/e2e: add e2e test to reproduce issue 18089

- mvcc/index_test.go
- mvcc/key_index.go
- mvcc/key_index_test.go
- mvcc/kvstore.go
- tests/e2e/watch_test.go
Backport of https://github.com/etcd-io/etcd/pull/18274
----
NOTE: release-3.4 doesn't compute hash value for compaction.
> [3.4] *: keep tombstone if revision == compactAtRev 

- tests/robustness/model/replay.go
- tests/robustness/validate/validate_test.go
- tests/robustness/validate/watch.go
This reverts commit 4fe227c46c6159546df568f769a47763944e30ce.
REF: https://github.com/etcd-io/etcd/pull/18274#issuecomment-2269494421
> Revert "Disable robustness test detection of #18089 to allow detecting other issues

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
> CHANGELOG: update changes for issue 18089

- server/embed/config_test.go
- server/embed/etcd.go
- server/etcdmain/help.go
- server/features/etcd_features.go
migrating experimental-initial-corrupt-check flag to feature gate.
part of https://github.com/etcd-io/etcd/issues/18023
> KEP-4578: migrate experimental-initial-corrupt-check flag to feature gate.

- go.mod
- go.sum
> [3.4] Bump bbolt to 1.3.11

- server/storage/mvcc/kvstore.go
- server/storage/mvcc/kvstore_test.go
fix comment in PR https://github.com/etcd-io/etcd/pull/13018#discussion_r1730275709
> etcdserver: rename defaultCompactionSleepInterval var

- client/v3/kubernetes/client.go
Totally slipped past me, only found this because K8s has integration tests that expect client side grpc error for size of request. I didn't catch it as they are not located in `apiserver` package, but in `controlplane`. When iterating I assumed that all relevant tests are in apiserver package.
cc @ahrtr
> Fix passing default grpc call options in Kubernetes client

- client/v3/kubernetes/client.go
Backport https://github.com/etcd-io/etcd/pull/18360#pullrequestreview-2272337341
> [release-3.5] Fix passing default grpc call options in Kubernetes client

- server/config/config.go
- server/embed/config.go
- server/embed/etcd.go
- server/etcdmain/config.go
- server/etcdmain/help.go
- server/etcdserver/server.go
- server/mvcc/kvstore.go
- server/mvcc/kvstore_compaction.go
- server/mvcc/kvstore_test.go
Backport according to https://github.com/etcd-io/etcd/issues/18485#issuecomment-2306061035.
This is a cherry-pick of:
- https://github.com/etcd-io/etcd/commit/184b0e5d4964f1115590acec50fa5e584a2f7770:  add sleep interval
- https://github.com/etcd-io/etcd/commit/fab8474ef8370a089fe0174e28c197b5b93898df: add CompactionSleepInterval in FakeStore's config
- https://github.com/etcd-io/etcd/commit/2c53be7c5d91e9b618342d63d2d06c3b265abee4 : rename defaultCompactionSleepInterval var 
Just for run testing, and I'll squash it later if passed :)
> [3.5] Introduce the CompactionSleepInterval flag

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
Update 3.4 and 3.5 CHANGELOG to add a note regarding the Go update to 1.22.7.
Part of #18548.
To be merged after https://github.com/etcd-io/etcd/pull/18549, https://github.com/etcd-io/etcd/pull/18550.
> CHANGELOG: add note regarding updating to go 1.22.7

- tools/benchmark/cmd/root.go
When reproducing #18509 , i found that benchmark doesn't support InsecureSkipVerify, so add it.
> benchmark: support InsecureSkipVerify

- tools/etcd-dump-db/README.md
- tools/etcd-dump-db/main.go
- tools/etcd-dump-db/meta.go
- tools/etcd-dump-db/page.go
- tools/etcd-dump-db/scan.go
- tools/etcd-dump-db/utils.go
The `etcd-dump-db scan-keys ...` is useful to analyze issue something like https://github.com/etcd-io/bbolt/issues/778.  It supports scanning the key space even the db is corrupted.
> Support scan-keys command to scan the key space starting a specific revision

- server/lease/lessor.go
- server/lease/lessor_test.go
Fixes #18538
Refactors `lessor` functions and `TestLessorRenewExtendPileup` to not operate on the global variable `leaseRevokeRate`.  Passes `leaseRevokeRate` as a `LessorConfig` option to fix the race conditions described in #18538.
Multiple goroutines were concurrently modifying the global variable resulting in the race conditions.
> Fix races in TestLessorRenewExtendPileup

- server/lease/lessor.go
- server/lease/lessor_test.go
> Backport TestLessorRenewExtendPileup race condition fix for release-3.5

- lease/lessor.go
- lease/lessor_test.go
> [3.4] Backport TestLessorRenewExtendPileup race condition fix

- CHANGELOG/CHANGELOG-3.5.md
Update the CHANGELOG regarding introducing the `etcd --experimental-compaction-sleep-interval` flag (https://github.com/etcd-io/etcd/pull/18514)
> CHANGELOG: add note for the CompactionSleepInterval flag(PR 18514)

- CHANGELOG/CHANGELOG-3.5.md
Updated 3.5 CHANGELOG to reflect today's release.
Part of #18485.
> CHANGELOG: Update release date for v3.5.16

- Documentation/contributor-guide/release.md
This commit will improve the release documentation guide by incorporating the following points:
```
1. Step 5 can be simplified to do a single-branch checkout
2. Step 6 should clarify that the release directory is in /tmp/etcd-release-${VERSION}/etcd/release/
3. Step 8 mention to add the "Release" label to the announcement message
```
Reference: https://github.com/etcd-io/etcd/issues/18485#issuecomment-2341751693
> Improve release documentation

- CHANGELOG/CHANGELOG-3.4.md
Set the v3.4.34 release date to today.
Part of #18486.
> CHANGELOG: set release 3.4.34 date

- client/v3/README.md
See description in https://github.com/etcd-io/etcd/issues/18410
> docs: remove warning that etcd 3.5.0 was not yet released

- scripts/release.sh
Address https://github.com/etcd-io/etcd/issues/18581 in `main`.
We need to also backport it to `release-3.5`.
> Ensure commits are signed in `scripts/release.sh`

- scripts/release.sh
As found in https://github.com/etcd-io/etcd/issues/18486#issuecomment-2347374985, running release-3.4's release script created the tag but didn't push it. This pull request addresses that issue.
I verified this by running the script with my fork and pointing the `REPOSITORY` environment variable to it:
1. `version/version.go` bump commit: https://github.com/ivanvc/etcd/commit/d2e6638c13addb522c12f2f47ab7a7a10bf57802
2. tag: https://github.com/ivanvc/etcd/releases/tag/v3.4.102
Part of https://github.com/etcd-io/etcd/issues/18486
> [3.4] release: push tag after creating it

- scripts/test.sh
- scripts/test_lib.sh
- scripts/updatebom.sh
> Rename modules_exp to modules_for_bom to improve code and clarity

- scripts/test_lib.sh
- tools/mod/doc.go
- tools/mod/tools.go
As `tools/mod` also contains the `go.mod` file, we should look into adding it to the `module_dirs` variable, so that when executing `./scripts/fix.sh`, the proper checks and fixes can be applied.
To address the issue of broken unit tests and code coverage due to `tools/mod` directory's lack of Go code, we've introduced a new `doc.go` file. This file acts as a placeholder, enabling tools like `golangci-lint` and `go test` to function correctly.
Discovered when working on https://github.com/etcd-io/etcd/pull/18575, where running `./scripts/fix.sh` missed fixing the go mod file in `tools/mod`, causing the CI pipeline to fail.
> Add tools/mod to module_dirs

- client/pkg/fileutil/lock_flock.go
- pkg/proxy/server.go
- server/etcdserver/api/v3compactor/periodic.go
- server/etcdserver/api/v3discovery/discovery.go
- server/etcdserver/server.go
- server/etcdserver/v3_server.go
- tests/framework/e2e/etcd_process.go
- tests/integration/clientv3/kv_test.go
- tests/integration/clientv3/lease/lease_test.go
- tests/integration/clientv3/metrics_test.go
- tests/integration/clientv3/util.go
- tests/integration/v3_failover_test.go
Update `err == *` expressions to `errors.Is(err, *)`, as a preferred means of error equality checks that can handle wrapping (https://pkg.go.dev/errors#pkg-overview).
This PR updates all cases to be fixed in a number of files, but not all files. The rest of the cases should be addressed in a separate PR.
> Use errors.Is for error equality checks

- Documentation/contributor-guide/release.md
This pull request has the improvements noted while doing #18486.
> docs: update release.md with improvements from v3.4.34 release

- client/pkg/testutil/recorder.go
- server/etcdserver/api/v3compactor/periodic_test.go
> Fixed periodic compaction tests

- etcdctl/ctlv3/command/ep_command.go
Follow up on https://github.com/etcd-io/etcd/pull/18615#issuecomment-2367198258 for using errors.Is in `etcdctl` module, as part of https://github.com/etcd-io/etcd/issues/18576.
Use errors.Is for error equality check in `ep_command.go`.
> command: Use errors.Is for error equality check in ep_command.go

- etcdctl/ctlv3/command/completion_command.go
- etcdutl/etcdutl/completion_commmand.go
`cobra.ExactValidArgs` method is deprecated I update `cobra.ExactValidArgs` method to `cobra.MatchAll` method
> update: `cobra.ExactValidArgs` method is deprecated

- server/storage/wal/file_pipeline.go
- server/storage/wal/repair.go
- server/storage/wal/wal.go
- server/storage/wal/wal_test.go
Relates to https://github.com/etcd-io/etcd/pull/18574#discussion_r1758781591
This PR adds a new function to consolidate WAL file creation into a single function to help reduce errors and make the process more consistent.
> Add function to create WAL files

- client/internal/v2/README.md
- client/pkg/fileutil/preallocate_darwin.go
- client/v3/client.go
- client/v3/retry_interceptor.go
PR for rest of errors.Is conversions for the client modules, as part of https://github.com/etcd-io/etcd/issues/18576
> client: remaining errors.Is conversions

- tests/e2e/v2store_deprecation_test.go
This should fix https://github.com/etcd-io/etcd/issues/18412.
After the test case is done Go's testing pkg tries to cleanup the temporary directories that were created by calls to `TempDir()`. This cleanup sometimes failed with errors like:
```
testing.go:1231: TempDir RemoveAll cleanup: unlinkat /tmp/TestV2DeprecationWriteOnlySnapshot1900751190/002/member-0/member/snap: directory not empty
```
I belive the cleanup sometimes happened before the etcd process was stopped which lead to the above error. Adding the defer statement to make sure the process is done before the test case returns seems to fix the error for me.
Before my changes I was able to reliably reproduce the issue with
```
go test -v -count 1000 -run "^TestV2DeprecationWriteOnlySnapshot$"
```
and with the changes from this PR …
> fix(tests/e2e): ensure spawned cmds are closed

- CONTRIBUTING.md
Fixes https://github.com/etcd-io/etcd/issues/18650. I think this is all what was missing for me, should also be enough for others to help fix flaky tests.
> docs(contributing): document how to install stress tool

- tests/common/auth_test.go
A simple fix for https://github.com/etcd-io/etcd/issues/18585.
Apparently under some load it can happen that the auth token expires before it was used/renewed which leads to this test (maybe other tests are affected by this as well?) being flaky (from what I saw, roughly ~0.3% of test runs). See also my comment https://github.com/etcd-io/etcd/issues/18585#issuecomment-2383054323. I figured out that simply increasing the TTL of the token to 3s seems to solve the test flakyness. In order to verify I made the following changes in `tests/framework/e2e/e2e.go` to be able to run the test using `stress`:
```patch
@@ -16,7 +16,9 @@ package e2e
import (
"context"
+       "net"
"os"
+       "strconv"
"testing"
"go.etcd.io/etcd/client/pkg/v3/testutil"
@@ -44,6 +46,21 @@ func (e e2eRunner) …
```
> fix(tests/common): increase token ttl to fix flaky TestAuthLeaseTimeToLive test

- server/etcdserver/api/v3compactor/periodic_test.go
This should fix https://github.com/etcd-io/etcd/issues/17487, see also comments in issue. 
@ahrtr and I were both not sure if this is a change of the test logic (I think it is not) and how the 10ms timeout was initially chosen. Maybe someone else knows more in that regard? Anyway this change makes the test reliable for me.
> fix(v3compactor): flaky TestPeriodicSkipRevNotChange test by increasing timeout

- api/etcdserverpb/raft_internal_stringer.go
This is the first pull request aiming to enable the `unexported-return` revive lint rule from golangci-lint.
The aim is to ensure that the structs returned from exported functions are exported, too.
In this pull request, the following structs are now exported:
* `etcdserverpb.TxnRequestStringer`, previously `txnRequestStringer`, as it is returned by the exported function `NewLoggableTxnRequest()`.
* `etcdserverpb.LoggablePutRequest`, previously `loggablePutRequest`, as it is returned by the exported function `NewLoggablePutRequest()`.
Part of #18370.
> api: address revive unexported-return issues

- server/etcdserver/api/membership/cluster.go
- server/etcdserver/server.go
- tests/integration/cluster_test.go
- tests/robustness/makefile.mk
Previously, calling s.IsLearner() when the local node is no longer a member panics. There was an attempt to fix this by first checking IsMemberExist(), but this is not a correct fix because the member could be removed between the two calls. Instead of panicking when the member was removed, IsLearner() should return false. A node which is not a member is also not a learner.
There was a similar concurrency bug when accessing the IsLearner property of a member, which will panic with a nil pointer access error if the member is removed between the IsMemberExist() and Member() calls.
I did not add a unit test because it's basically impossible to test for such concurrency bugs.
> etcdserver: fix panic when checking IsLearner of removed member

- server/etcdserver/apply/apply.go
- server/etcdserver/apply/apply_auth.go
- server/etcdserver/apply/apply_auth_test.go
- server/etcdserver/apply/uber_applier.go
cc @ahrtr 
https://github.com/etcd-io/etcd/issues/18667#issuecomment-2393130782
> Remove context from top level apply

- server/etcdserver/apply/apply.go
- server/etcdserver/apply/apply_auth_test.go
- server/etcdserver/apply/uber_applier.go
cc @ahrtr 
https://github.com/etcd-io/etcd/issues/18667#issuecomment-2393130782
> Remove context from dispatch

- .github/workflows/release.yaml
GitHub Container Registry is returning a TOOMANYREQUESTS error. Switch to AWS ECR mirror, as suggested in https://github.com/aquasecurity/trivy-action/issues/389.
Part of #18671.
> github/workflows: use ECR mirror for Trivy's DB

- Documentation/contributor-guide/release.md
Resolve https://github.com/etcd-io/etcd/issues/18611
cc @ivanvc @jmhbnz
> Update release steps on how to share quay.io password

- client/internal/v2/client_test.go
- client/internal/v2/go.mod
- client/internal/v2/members_test.go
- client/pkg/fileutil/fileutil_test.go
- client/pkg/fileutil/lock_test.go
- client/pkg/fileutil/preallocate_test.go
- client/pkg/fileutil/purge_test.go
- client/pkg/fileutil/read_dir_test.go
- client/pkg/transport/keepalive_listener_test.go
- client/pkg/transport/listener_test.go
- client/pkg/transport/timeout_dialer_test.go
- client/pkg/transport/timeout_listener_test.go
- client/pkg/transport/timeout_transport_test.go
- client/pkg/transport/tls_test.go
- client/pkg/transport/transport_test.go
- client/pkg/types/id_test.go
- client/pkg/types/urlsmap_test.go
- client/v3/client_test.go
- client/v3/config_test.go
- client/v3/yaml/config_test.go
There is no linter for this.
This uses testify instead of testing for
With 
```go
require.NoError(t, err)
require.Error(t, err)
```
instead of
```go
if err != nil {
t.Fatal(err)
}
if err == nil {
t.Fatal(err)
}
```
> fix: use require.NoError instead of t.Fatal(err) in client package

- client/pkg/logutil/zap_test.go
- server/etcdserver/api/v2store/store_ttl_test.go
- server/storage/backend/tx_buffer_test.go
- server/storage/mvcc/key_index_test.go
- tests/common/auth_util.go
- tests/common/endpoint_test.go
- tests/e2e/ctl_v3_auth_cluster_test.go
- tests/e2e/ctl_v3_member_test.go
- tests/e2e/v3_curl_auth_test.go
- tests/e2e/v3_curl_cluster_test.go
- tests/e2e/v3_curl_kv_test.go
- tests/e2e/v3_lease_no_proxy_test.go
- tests/framework/testutils/log_observer_test.go
- tests/integration/clientv3/experimental/recipes/v3_double_barrier_test.go
- tests/integration/clientv3/lease/leasing_test.go
- tests/integration/clientv3/maintenance_test.go
- tests/integration/clientv3/naming/resolver_test.go
- tools/.golangci.yaml
This fixes [empty](https://github.com/Antonboom/testifylint?tab=readme-ov-file#empty) and [len](https://github.com/Antonboom/testifylint?tab=readme-ov-file#len) rules from [testifylint](https://github.com/Antonboom/testifylint).
> fix: enable empty and len rules from testifylint

- pkg/ioutil/pagewriter_test.go
- server/etcdserver/api/v2store/store_ttl_test.go
- tests/e2e/v3_curl_auth_test.go
- tests/integration/clientv3/lease/leasing_test.go
- tests/integration/v2store/store_tag_test.go
- tests/integration/v2store/store_test.go
- tests/integration/v3_auth_test.go
- tests/integration/v3_stm_test.go
- tools/.golangci.yaml
This fixes [nil-compare](https://github.com/Antonboom/testifylint?tab=readme-ov-file#nil-compare) rule from [testifylint](https://github.com/Antonboom/testifylint).
It also replaces `testutil.AssertNil` and `testutil.AssertNotNil` by `assert.Nil` and `require.NotNil`
The require package is used for NotNil replacement because of the Fatal method being used in testutil version of the method.
> fix: enable nil-compare rule from testifylint

- tests/e2e/corrupt_test.go
- tests/e2e/ctl_v3_member_test.go
- tests/e2e/ctl_v3_snapshot_test.go
- tests/e2e/hashkv_test.go
- tests/e2e/reproduce_17780_test.go
- tests/e2e/v3_curl_cluster_test.go
- tests/integration/v3_auth_test.go
- tools/.golangci.yaml
This fixes [compares](https://github.com/Antonboom/testifylint?tab=readme-ov-file#compares) and [negative-positive](https://github.com/Antonboom/testifylint?tab=readme-ov-file#negative-positive) rules from [testifylint](https://github.com/Antonboom/testifylint).
> fix: enable compares and negative-positive rules from testifylint

- client/internal/v2/client.go
- client/internal/v2/client_test.go
- client/internal/v2/keys.go
- client/internal/v2/keys_test.go
- client/internal/v2/util.go
This enable errorlint in module `go.etcd.io/etcd/client/v2`
> fix: enable errorlint in module `go.etcd.io/etcd/client/v2`

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
Add an entry regarding using Go 1.22.8 for releases 3.4 and 3.5.
Part of: #18665
> CHANGELOG: add go 1.22.8 entry for 3.4 and 3.5

- pkg/expect/expect.go
- pkg/expect/expect_test.go
- tests/framework/testutils/log_observer_test.go
- tools/.golangci.yaml
This PR enables the `error-is-as` testifylint rule as part of https://github.com/etcd-io/etcd/issues/18719
> fix: enable error-is-as rule from testifylint

- server/etcdserver/api/v2store/store_ttl_test.go
- server/etcdserver/apply/uber_applier_test.go
- tests/e2e/ctl_v3_move_leader_test.go
- tests/e2e/v3_curl_auth_test.go
- tests/integration/clientv3/lease/leasing_test.go
- tests/integration/v2store/store_tag_test.go
- tests/integration/v2store/store_test.go
- tests/integration/v3_auth_test.go
- tests/integration/v3_stm_test.go
- tools/.golangci.yaml
This fixes [error-nil](https://github.com/Antonboom/testifylint?tab=readme-ov-file#error-nil) rule from [testifylint](https://github.com/Antonboom/testifylint).
> fix: enable error-nil rule from testifylint

- client/v3/config.go
- etcdctl/ctlv3/command/global.go
- etcdctl/ctlv3/command/make_mirror_command.go
- etcdctl/ctlv3/ctl.go
Add `--max-send-bytes` and `--max-recv-bytes` options for `etcdctl` to configure `MaxCallSendMsgSize` and `MaxCallRecvMsgSize`.
This was mentioned in #13054 and #12576, but it wasn't fixed.
We ran into this issue when trying to sync large kv using `make-mirror` and adding this option solves the issue.
> feat(etcdctl): add --max-send-bytes and --max-recv-bytes options

- client/v3/credentials/credentials_test.go
- pkg/flags/uint32_test.go
- server/etcdserver/api/v2store/node_extern_test.go
- server/etcdserver/api/v2store/store_ttl_test.go
- server/etcdserver/server_test.go
- tests/e2e/graceful_shutdown_test.go
- tests/e2e/hashkv_test.go
- tests/e2e/reproduce_17780_test.go
- tests/integration/v2store/store_tag_test.go
- tests/integration/v2store/store_test.go
- tools/.golangci.yaml
This fixes [expected-actual](https://github.com/Antonboom/testifylint?tab=readme-ov-file#expected-actual) rule from [testifylint](https://github.com/Antonboom/testifylint).
Related to #18719
> fix: enable expected-actual rule from testifylint

- server/embed/etcd.go
When I was separating GRPC and HTTP ports, the following error occurred, causing ETCD to not start properly and causing confusion for me.
error log:
```text
cannot bind both --client-listen-urls and --client-listen-http-urls on the same url https://192.168.31.23:2379
```
key config:
```text
...
--listen-client-urls=https://127.0.0.1:2379,https://192.168.31.23:2379 \
--listen-client-http-urls=https://192.168.31.23:2379 \
...
```
It should be a spelling error in the error log output, client-listen-* will be listen-client-*. I hope it can help others.
> embed: fix typo client-listen-x to listen-client-x

- contrib/raftexample/kvstore_test.go
- contrib/raftexample/raftexample_test.go
- tools/etcd-dump-logs/etcd-dump-log_test.go
There is no linter for this.
This uses testify instead of testing for
With 
```go
require.NoError(t, err)
require.Error(t, err)
```
instead of
```go
if err != nil {
t.Fatal(err)
}
if err == nil {
t.Fatal(err)
}
```
> fix: use require.NoError instead of t.Fatal(err) in contrib and tools packages

- api/v3rpc/rpctypes/error_test.go
- client/pkg/fileutil/lock_linux.go
- client/pkg/fileutil/preallocate_unix.go
- client/pkg/srv/srv.go
- client/pkg/transport/timeout_dialer_test.go
- client/pkg/transport/timeout_listener_test.go
- client/v3/client.go
- client/v3/client_test.go
- client/v3/experimental/recipes/key.go
- client/v3/lease.go
- client/v3/leasing/kv.go
- client/v3/maintenance.go
- client/v3/mock/mockserver/mockserver.go
- client/v3/retry.go
- client/v3/retry_interceptor.go
- client/v3/snapshot/v3_snapshot.go
- client/v3/watch.go
- pkg/featuregate/feature_gate.go
- pkg/flags/flag.go
- pkg/grpctesting/stub_server.go
- pkg/ioutil/readcloser_test.go
- pkg/netutil/netutil.go
This enable errorlint in packages api, client and pkg
> fix: enable errorlint in api, client and pkg

- tools/.golangci.yaml
Followup to https://github.com/etcd-io/etcd/pull/18741
Refer to https://github.com/etcd-io/etcd/pull/18741#issuecomment-2422395914
> Add comment to clarify non-f-functions on golang standard lib

- client/internal/v2/keys_bench_test.go
- client/pkg/fileutil/preallocate_test.go
- client/pkg/fileutil/read_dir_test.go
- client/pkg/testutil/before.go
- client/pkg/testutil/testutil.go
- client/pkg/tlsutil/cipher_suites_test.go
- client/pkg/transport/listener_test.go
- client/pkg/transport/timeout_dialer_test.go
- client/pkg/types/set_test.go
- client/v3/client_test.go
enables and fixes [thelper](https://golangci-lint.run/usage/linters/#thelper) linter issues in client directory
> fix: enable thelper linter in client directory

- tests/robustness/README.md
cc @ahrtr @fuweid @henrybear327 @siyuanfoundation @MadhavJivrajani @jmhbnz
> Improve documentation of robustness test adding key concepts used in the test

- tests/robustness/failpoint/gofail.go
Brackets are not usually used in test name nor file path that we generate report in. This makes it easier to copy path for report.
cc @ah8ad3 @ahrtr @MadhavJivrajani @henrybear327
> Remove brackets from failpoint name

- tests/e2e/ctl_v3_member_test.go
- tests/e2e/ctl_v3_snapshot_test.go
- tests/integration/clientv3/concurrency/example_mutex_test.go
- tests/integration/clientv3/connectivity/black_hole_test.go
- tests/integration/clientv3/connectivity/network_partition_test.go
- tests/integration/clientv3/connectivity/server_shutdown_test.go
- tests/integration/clientv3/experimental/recipes/v3_double_barrier_test.go
- tests/integration/clientv3/experimental/recipes/v3_lock_test.go
- tests/integration/clientv3/lease/leasing_test.go
- tests/integration/clientv3/maintenance_test.go
- tests/integration/clientv3/ordering_kv_test.go
- tests/integration/clientv3/ordering_util_test.go
- tests/integration/clientv3/txn_test.go
- tests/integration/clientv3/user_test.go
- tests/integration/clientv3/watch_test.go
- tests/integration/v3_grpc_test.go
- tests/integration/v3_lease_test.go
- tests/integration/v3_tls_test.go
tests directory errors.Is conversions, as part of https://github.com/etcd-io/etcd/issues/18576
> tests: remaining errors.Is conversions

- pkg/flags/flag_test.go
- tools/.golangci.yaml
Tenv is an analyzer that detects using os.Setenv instead of t.Setenv since Go1.17.
enables and fixes [tenv](https://golangci-lint.run/usage/linters/#tenv) linter issues
> fix: enable tenv linter

- client/v3/client_test.go
- tools/.golangci.yaml
This fixes [float-compare](https://github.com/Antonboom/testifylint?tab=readme-ov-file#float-compare) rule from [testifylint](https://github.com/Antonboom/testifylint).
Related to #18719
> fix: enable float-compare rule from testifylint

- server/etcdserver/api/v3rpc/watch.go
Under some conditions serverWatchStream.close() leaves recvLoop goroutine blocked on sending data to ctrlStream channel:
```
goroutine profile: total 177241
43832 @ 0x43fe6e 0x40a6a5 0x40a2f7 0xd9bb8d 0xd9af66 0x473181
#	0xd9bb8c	go.etcd.io/etcd/server/v3/etcdserver/api/v3rpc.(*serverWatchStream).recvLoop+0x70c	external/io_etcd_go_etcd_server_v3/etcdserver/api/v3rpc/watch.go:348
#	0xd9af65	go.etcd.io/etcd/server/v3/etcdserver/api/v3rpc.(*watchServer).Watch.func2+0x45		external/io_etcd_go_etcd_server_v3/etcdserver/api/v3rpc/watch.go:191
```
corresponding code:
https://github.com/etcd-io/etcd/blob/40b4715ca371c950c1965cd79519f5f0f9a57921/server/etcdserver/api/v3rpc/watch.go#L349-L360
Reading from the `ctrlStream` channel is implemented in sendLoop, which is terminated on `closec` closure: …
> etcdserver: terminate recvLoop on serverWatchStream.close()

- tests/common/alarm_test.go
- tests/common/auth_test.go
- tests/common/member_test.go
- tests/e2e/cluster_downgrade_test.go
- tests/e2e/corrupt_test.go
- tests/e2e/ctl_v3_auth_test.go
- tests/e2e/ctl_v3_snapshot_test.go
- tests/e2e/etcd_config_test.go
- tests/integration/clientv3/lease/lease_test.go
- tests/integration/clientv3/lease/leasing_test.go
- tests/integration/clientv3/maintenance_test.go
- tests/integration/clientv3/naming/endpoints_test.go
- tests/integration/clientv3/snapshot/v3_snapshot_test.go
- tests/integration/clientv3/watch_test.go
- tests/integration/cluster_test.go
- tests/integration/embed/embed_test.go
- tests/integration/metrics_test.go
- tests/integration/proxy/grpcproxy/cluster_test.go
- tests/integration/proxy/grpcproxy/kv_test.go
- tests/integration/snapshot/member_test.go
- tests/integration/snapshot/v3_snapshot_test.go
- tests/integration/v3_auth_test.go
- tests/integration/v3_grpc_test.go
- tests/integration/v3_lease_test.go
- tests/integration/v3_watch_test.go
- tests/integration/v3election_grpc_test.go
- tests/robustness/main_test.go
- tests/robustness/model/deterministic_test.go
- tests/robustness/model/non_deterministic_test.go
- tests/robustness/validate/validate_test.go
There is no linter for this.
This uses testify instead of testing for
With 
```go
require.NoError(t, err)
require.Error(t, err)
```
instead of
```go
if err != nil {
t.Fatal(err)
}
if err == nil {
t.Fatal(err)
}
```
> fix: use require.NoError instead of t.Fatal(err) in tests package (part 1)

- tests/robustness/random/random.go
- tests/robustness/traffic/etcd.go
- tests/robustness/traffic/kubernetes.go
- tests/robustness/traffic/traffic.go
Should reduce number of flakes due to etcd being overloaded by too many compaction at once
> Ensure compaction is executed at even intervals to avoid overload

- .github/workflows/release.yaml
- Documentation/contributor-guide/release.md
- scripts/release.sh
- scripts/release_notes.tpl.txt
Implements #18604.
While we verify that this works as expected, it will create the release as a draft. Then, we can verify that it looks correct and manually publish them.
I tested this feature in my fork. Refer to the latest [release](https://github.com/ivanvc/etcd/releases/tag/untagged-2fbc011075d562e8f480) (and its assets).
I introduced a `scripts/release_notes.tpl.txt`. Because I don't have access to edit a previous release and copy the Markdown, I manually crafted the Markdown based on what I saw and improved how we reference the version for the Docker instructions. But, because it was manual, I may have an error.
While working on importing the release notes, I realized that we had been copy-pasting the release text with a broken link.
> For installation guides, please check out …
> release: use GitHub's gh to create GitHub release

- client/internal/v2/auth_user.go
- client/internal/v2/client_test.go
- client/internal/v2/curl.go
- client/internal/v2/keys.go
- client/pkg/fileutil/dir_unix.go
- client/pkg/fileutil/fileutil.go
- client/pkg/fileutil/fileutil_test.go
- client/pkg/fileutil/lock.go
- client/pkg/testutil/leak.go
- client/pkg/transport/limit_listen.go
- client/pkg/transport/listener.go
- client/pkg/transport/listener_test.go
- client/v3/client.go
- client/v3/client_test.go
- client/v3/compare.go
- client/v3/concurrency/mutex.go
- client/v3/kv.go
- client/v3/mirror/syncer.go
- client/v3/retry.go
- client/v3/retry_interceptor.go
- client/v3/sort.go
- client/v3/watch.go
enables and fixes [gofumpt](https://golangci-lint.run/usage/linters/#gofumpt) linter issues in client directory
> fix: enable gofumpt instead of gofmt linter in client

- etcdserver/api/v3rpc/watch.go
backport of https://github.com/etcd-io/etcd/pull/18739 to 3.4
> [serverWatchStream] terminate recvLoop on sws.close()

- client/v3/go.mod
- client/v3/go.sum
- etcdctl/go.sum
- etcdutl/go.mod
- etcdutl/go.sum
- go.mod
- go.sum
- server/go.mod
- server/go.sum
- tests/go.mod
- tests/go.sum
- tools/mod/go.mod
- tools/mod/go.sum
This pull request completes this week's etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit#gid=1394774387) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).
- https://github.com/etcd-io/etcd/pull/18758
- https://github.com/etcd-io/etcd/pull/18764
- https://github.com/etcd-io/etcd/pull/18763
- https://github.com/etcd-io/etcd/pull/18762
- https://github.com/etcd-io/etcd/pull/18761
- https://github.com/etcd-io/etcd/pull/18759
- https://github.com/etcd-io/etcd/pull/18765
Please read …
> [2024-10-20] Bump dependency updates identified by dependabot #18755

- .github/workflows/tests.yaml
These jobs have now been migrated to prow in:
- https://github.com/kubernetes/test-infra/pull/33733
- https://github.com/kubernetes/test-infra/pull/33734
> Remove defunct release-3.5 arm64 github actions workflows

- server/etcdserver/api/v3rpc/watch.go
Backport of https://github.com/etcd-io/etcd/pull/18739 to 3.5
> [3.5] [serverWatchStream] terminate recvLoop on sws.close()

- server/etcdserver/apply.go
- server/etcdserver/apply_test.go
Manually backported https://github.com/etcd-io/etcd/pull/18749 given conflicting changes.
/assign @ahrtr
> [3.5] manual: Fix risk of a partial write txn being applied

- CHANGELOG/CHANGELOG-3.5.md
Update changelog to cover the following two fixes:
- https://github.com/etcd-io/etcd/pull/18784
- https://github.com/etcd-io/etcd/pull/18799
> Update 3.5 changelog to cover two major fixes

- tests/e2e/logging_test.go
See also https://github.com/etcd-io/etcd/issues/17329
This is how I would extend the logging test to include both a single node and a three node cluster. If it is ok like that I'd submit PRs for backporting as written in the linked issue
> chore(e2e): extend logging test to 3 node cluster

- server/etcdserver/server.go
Since nobody proceeds with the proposal, so create a followup PR to https://github.com/etcd-io/etcd/pull/18635/files#r1778755879
cc @clement2026 @serathius
> Refactor Etcdserver.snapshot to extract compaction into a separate method

- server/config/config.go
- server/embed/config.go
- server/embed/config_logging.go
- server/embed/config_logging_journal_unix.go
- server/embed/etcd.go
- server/etcdmain/config.go
- server/etcdmain/etcd.go
- server/etcdserver/api/etcdhttp/peer.go
- server/etcdserver/api/etcdhttp/utils.go
- server/etcdserver/api/membership/cluster.go
- server/etcdserver/api/membership/errors.go
- server/etcdserver/api/membership/storev2.go
- server/etcdserver/api/rafthttp/http.go
- server/etcdserver/api/rafthttp/stream.go
- server/etcdserver/api/snap/snapshotter.go
- server/etcdserver/api/v2discovery/discovery.go
- server/etcdserver/api/v2store/store.go
- server/etcdserver/api/v2store/store_ttl_test.go
- server/etcdserver/api/v3rpc/watch.go
- server/etcdserver/bootstrap.go
- server/etcdserver/corrupt.go
- server/etcdserver/server.go
- server/lease/leasehttp/http.go
- server/proxy/grpcproxy/kv.go
- server/storage/backend.go
- server/storage/mvcc/kvstore_test.go
- server/storage/schema/membership.go
- server/storage/schema/schema.go
- server/storage/wal/version.go
- server/storage/wal/wal.go
This enable errorlint in packages server 
> fix: enable errorlint in server directory

- tests/robustness/client/watch.go
- tests/robustness/failpoint/cluster.go
- tests/robustness/report/client.go
- tests/robustness/report/report.go
- tests/robustness/scenarios/scenarios.go
- tests/robustness/traffic/traffic.go
- tests/robustness/validate/validate.go
There is no linter for this.
This uses testify instead of testing for t.Fatal calls
> fix: use require instead of t.Fatal(err) in tests/robustness package

- tests/e2e/logging_test.go
Backport of https://github.com/etcd-io/etcd/pull/18806 to `release-3.5` branch.
> [3.5] chore(e2e): backport TestNoErrorLogsDuringNormalOperations test

- pkg/expect/expect.go
- tests/e2e/etcd_process.go
- tests/e2e/logging_test.go
Backport of https://github.com/etcd-io/etcd/pull/18806 to release-3.4 branch.
> [3.4] chore(e2e): backport TestNoErrorLogsDuringNormalOperations test

- etcdctl/ctlv3/command/auth_command.go
- etcdctl/ctlv3/command/ep_command.go
- etcdctl/ctlv3/command/lease_command.go
- etcdctl/ctlv3/command/lock_command.go
- etcdctl/ctlv3/command/member_command.go
- etcdctl/ctlv3/command/put_command.go
- etcdctl/ctlv3/command/txn_command.go
- etcdctl/ctlv3/command/user_command.go
- etcdctl/ctlv3/command/watch_command.go
- etcdctl/ctlv3/command/watch_command_test.go
- etcdutl/etcdutl/defrag_command.go
- etcdutl/etcdutl/migrate_command.go
This enable errorlint in  etcdctl and etcdutl directories
> fix: enable errorlint in etcdctl and etcdutl directories

- client/v3/go.mod
- client/v3/go.sum
- etcdctl/go.sum
- etcdutl/go.mod
- etcdutl/go.sum
- go.mod
- go.sum
- server/go.mod
- server/go.sum
- tests/go.mod
- tests/go.sum
- tools/mod/go.mod
- tools/mod/go.sum
This pull request completes this week's etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit#gid=1394774387) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).
- https://github.com/etcd-io/etcd/pull/18796
- https://github.com/etcd-io/etcd/pull/18797
- https://github.com/etcd-io/etcd/pull/18792
- https://github.com/etcd-io/etcd/pull/18791
- https://github.com/etcd-io/etcd/pull/18790
- https://github.com/etcd-io/etcd/pull/18789
- https://github.com/etcd-io/etcd/pull/18788
Please read …
> [2024-10-31] Bump dependency updates identified by dependabot

- tests/e2e/logging_test.go
See https://github.com/etcd-io/etcd/issues/17329#issuecomment-2449367451 for details. This PR adds three additional test cases, each with different TLS settings.
> chore(e2e): extend TestNoErrorLogsDuringNormalOperations with different TLS configs

- CHANGELOG/CHANGELOG-3.4.md
Previous PR forgot to update 3.4 changelog.
> Update 3.4 changelog to cover the goroutine leakage issue

- contrib/raftexample/kvstore.go
- contrib/raftexample/raft.go
- tests/e2e/ctl_v3_auth_test.go
- tests/e2e/utils.go
- tests/e2e/v3_curl_election_test.go
- tests/e2e/v3_curl_maxstream_test.go
- tests/framework/e2e/cluster.go
- tests/framework/e2e/etcdctl.go
- tests/framework/e2e/util.go
- tests/framework/integration/cluster.go
- tests/framework/integration/integration.go
- tests/integration/clientv3/kv_test.go
- tests/integration/clientv3/lease/lease_test.go
- tests/integration/clientv3/user_test.go
- tests/integration/clientv3/watch_test.go
- tests/integration/v2store/store_test.go
- tests/integration/v3_grpc_test.go
- tests/integration/v3_lease_test.go
- tests/robustness/failpoint/failpoint.go
- tests/robustness/failpoint/gofail.go
- tests/robustness/report/wal.go
- tests/robustness/validate/operations.go
- tools/.golangci.yaml
- tools/etcd-dump-db/backend.go
- tools/etcd-dump-logs/main.go
This enable errorlint in golangci-lint config file
> fix: enable errorlint linter

- tests/common/alarm_test.go
- tests/common/compact_test.go
- tests/common/kv_test.go
- tests/common/maintenance_auth_test.go
- tests/common/member_test.go
- tests/common/role_test.go
- tests/common/status_test.go
- tests/common/txn_test.go
- tests/common/user_test.go
- tests/common/watch_test.go
This uses testify instead of testing for t.Fatal calls
> fix: use require instead of t.Fatal(err) in tests/common package

- tests/common/auth_test.go
- tests/e2e/corrupt_test.go
- tests/e2e/ctl_v3_member_test.go
- tests/e2e/v3_lease_no_proxy_test.go
- tests/e2e/watch_test.go
- tests/e2e/zap_logging_test.go
- tests/framework/testutils/log_observer_test.go
- tools/.golangci.yaml
This fixes [go-require](https://github.com/Antonboom/testifylint?tab=readme-ov-file#go-require) rule from [testifylint](https://github.com/Antonboom/testifylint)
Closes #18719
> fix: enable go-require rule from testifylint

- scripts/release.sh
I identified this issue while working on #18649. Currently, if we follow the practice of testing the release script in the first step when doing a release with `DRY=true` and then rerun the script, the script won't change directories into the freshly cloned repository. Instead, it will use the current directory, which may be prone to unwanted changes accidentally being pushed as part of the release.
With this approach, running it after a DRY run will yield the error:
```
In workspace '/tmp/etcd-release-3.5.124/etcd' the branch: release-3.5 diverges from the origin.
Consider cleaning up / renaming this directory or (cd /tmp/etcd-release-3.5.124/etcd && git reset --hard origin/release-3.5)
```
However, I feel the best experience would be to replace:
```
run git checkout "${BRANCH}" || exit …
```
> release: properly change working dir if tmp location already exists

- server/storage/backend/backend.go
- tests/e2e/defrag_no_space_test.go
PR contains an e2e test, gofailpoint and a fix for the issue described in https://github.com/etcd-io/etcd/issues/18810. 
Without the fix the test triggers a nil ptr panic in etcd as described in the linked issue:
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
panic: execute job failed
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x787ad8]
goroutine 136 [running]:
go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x80?, 0x2?, {0xf?, 0x0?, 0x0?})
go.uber.org/zap@v1.27.0/zapcore/entry.go:196 +0x78
go.uber.org/zap/zapcore.(*CheckedEntry).Write(0x40005d81a0, {0x400058a780, 0x2, 0x2})
go.uber.org/zap@v1.27.0/zapcore/entry.go:262 +0x1c4
go.uber.org/zap.(*Logger).Panic(0xcd8746?, {0xce7440?, 0xb54f60?}, {0x400058a780, 0x2, 0x2}) …
```
> fix(defrag): handle no space left error

- server/mvcc/backend/backend.go
- tests/e2e/defrag_no_space_test.go
Backport of https://github.com/etcd-io/etcd/pull/18822 to 3.5.
> [3.5] fix(defrag): handle errors during defrag

- server/storage/backend/backend.go
See issue https://github.com/etcd-io/etcd/issues/18841 and the discussion https://github.com/etcd-io/etcd/pull/18822#discussion_r1830692111 for details.
As written in the issue the temp file is closed if the defragmentation works as expected. The only case where it is left open is when the `bolt.Open` call fails. I think it is enough to simply include the close there, in my opinion there is no need to complicate this more.
> fix(defrag): close temp file in case of error

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
Part of #18847.
Add a note in 3.4.35 and 3.5.17 about compiling with Go 1.22.9.
> changelog: update go version for 3.4.35 and 3.5.17

- server/mvcc/backend/backend.go
See https://github.com/etcd-io/etcd/issues/18841 for details. Backport of https://github.com/etcd-io/etcd/pull/18851 to 3.5
> [3.5] fix(defrag): close temp file in case of error

- contrib/raftexample/raft.go
- etcdctl/ctlv3/command/check.go
- etcdctl/ctlv3/command/elect_command.go
- etcdctl/ctlv3/command/ep_command.go
- etcdctl/ctlv3/command/lease_command.go
- etcdctl/ctlv3/command/printer.go
- etcdctl/ctlv3/command/printer_fields.go
- etcdctl/ctlv3/command/printer_simple.go
- etcdctl/ctlv3/command/printer_table.go
- etcdctl/ctlv3/command/snapshot_command.go
- etcdctl/ctlv3/command/user_command.go
- etcdctl/ctlv3/ctl.go
- etcdutl/ctl.go
- etcdutl/etcdutl/defrag_command.go
- etcdutl/etcdutl/hashkv_command.go
- etcdutl/etcdutl/printer.go
- etcdutl/etcdutl/printer_simple.go
- etcdutl/etcdutl/snapshot_command.go
- etcdutl/snapshot/v3_snapshot.go
- etcdutl/snapshot/v3_snapshot_test.go
enables and fixes [gofumpt](https://golangci-lint.run/usage/linters/#gofumpt) linter issues in contrib, etcdctl and etcdutl directories
> fix: enable gofumpt instead of gofmt linter in contrib, etcdctl and etcdutl

- tools/benchmark/cmd/lease.go
- tools/etcd-dump-db/backend.go
- tools/etcd-dump-db/main.go
- tools/etcd-dump-db/page.go
- tools/etcd-dump-logs/etcd-dump-log_test.go
- tools/etcd-dump-logs/main.go
- tools/local-tester/bridge/bridge.go
- tools/proto-annotations/cmd/etcd_version.go
enables and fixes [gofumpt](https://golangci-lint.run/usage/linters/#gofumpt) linter issues in tools directory
> fix: enable gofumpt instead of gofmt linter in tools

- README.md
We have migrated jobs off the actuated infrastructure.
> Remove actuated badge from README.md

- .github/workflows/release.yaml
- scripts/release.sh
- scripts/release_notes.tpl.txt
> [3.4] release: use GitHub's gh to create GitHub release

- scripts/release.sh
Backport of https://github.com/etcd-io/etcd/pull/18812 to 3.5 according to the release plan of 3.5.17 (https://github.com/etcd-io/etcd/issues/18846)
> [3.5] release: properly change working dir if tmp location already exists

- CHANGELOG/CHANGELOG-3.4.md
Set the v3.4.35 release date to today.
Part of https://github.com/etcd-io/etcd/issues/18845.
> CHANGELOG: Add release date of etcd v3.4.35

- tests/robustness/failpoint/gofail.go
- tests/robustness/makefile.mk
- tests/robustness/patches/compactBeforeSetFinishedCompact/kvstore_compaction.patch
- tests/robustness/scenarios/scenarios.go
> tests: add robustness test for issue 17780

- scripts/release.sh
Backports commit: b82f882c3d9011bab9da05a6159f701e979b4348 to `release-3.4`.
We encountered the issue of needing to amend this script manually with this commit diff during release today in order to carry out the release. We originally discussed not backporting this change to `release-3.4` because we were not confident how well the script was performing (https://github.com/etcd-io/etcd/pull/17677#discussion_r1545789197). We have now performed several releases with the script carrying out the full release process including pushing tags etc, so I think we should now complete the backport.
cc @ahrtr, @ivanvc
> [3.4] Backport updating release script to use ssh

- Documentation/contributor-guide/release.md
As noted in 2024-11-12 releases:
1. Add instructions on how to verify that GitHub authentication works.
2. Detail the steps on how to release the GitHub release.
Link to #18846.
> docs(release): update GitHub release related instructions

- server/etcdmain/grpc_proxy.go
- tests/e2e/etcd_grpcproxy_test.go
This adds the min and max TLS version support from #13506 and #15156 to the grpc proxy.
Fixes #13506
> add tls min/max version to grpc proxy

- .github/OWNERS
- scripts/OWNERS
Let's recognize the fantastic work @ivanvc has been doing recently. 
Of particular note was the recent rework of `scripts/release.sh` to [use `gh` cli to automate creating GitHub releases](https://github.com/etcd-io/etcd/pull/18649). This saved us significant toil last release cycle earlier this week.
Given the excellent work Ivan has been doing in the areas of ci / tooling and his earlier efforts to rewrite `tools/rw-heatmaps` in golang I think it makes perfect sense for him to be an `approver` for these areas.
cc @etcd-io/maintainers-etcd
> Add ivanvc as approver for .github, scripts and tools/rw-heatmaps

- etcdctl/go.mod
- etcdctl/go.sum
- etcdutl/go.mod
- etcdutl/go.sum
- go.mod
- go.sum
- server/go.mod
- server/go.sum
- tests/go.mod
- tests/go.sum
> [3.5] Bump golang-jwt/jwt to 4.5.1 to address GO-2024-3250

- tests/robustness/README.md
cc @ahrtr @jmhbnz @fuweid @siyuanfoundation @MadhavJivrajani
> Add robustness track record section to make tracking easier

- README.md
This PR fixes displaying the etcd logo in README.md on a GitHub dark theme.
<details><summary>Before/after screenshots</summary>
<p>
Before (dark):
After (dark):
Before (light):
After (light):
</p>
</details> 
See [this doc](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to) for implementation details.
> Fix displaying etcd logo in README on a dark theme

- tests/robustness/validate/patch_history.go
First stage for https://github.com/etcd-io/etcd/pull/18772
We clean up the patchOperations functions to be simpler and use switch allowing support for other commands.
cc @ah8ad3 @ahrtr @MadhavJivrajani @henrybear327 @siyuanfoundation @jmhbnz
> Robustness refactor patch operations

- tests/robustness/validate/operations_test.go
- tests/robustness/validate/patch_history.go
- tests/robustness/validate/patch_history_test.go
Spitted from https://github.com/etcd-io/etcd/pull/18772
cc @ah8ad3 @ahrtr @MadhavJivrajani @henrybear327 @siyuanfoundation @jmhbnz
> Robustness duplicated puts 2

- server/etcdmain/grpc_proxy.go
- tests/e2e/etcd_grpcproxy_test.go
This adds the min and max TLS version support from #13506 and #15156 to the grpc proxy.
Fixes #13506
Backport of #18816
> [3.5] add tls min/max version to grpc proxy

- tests/robustness/validate/patch_history_test.go
cc @ah8ad3 @ahrtr @MadhavJivrajani @henrybear327 @siyuanfoundation @jmhbnz
> Multiply return time by 100 in tests to detect off by one differences

- tests/robustness/validate/patch_history.go
- tests/robustness/validate/patch_history_test.go
- tests/robustness/validate/validate.go
> Robustness duplicated puts 3

- tests/robustness/traffic/traffic.go
In last robustness meeting Nov 20 https://docs.google.com/document/d/1idZ_7tV6F18v223LyQ0WVUn9gXLSKyeLwYTdAgbjxpw/edit?usp=sharing, we identified that reducing QPS would reduce number of flakes from 10->2
We need a better way to monitor and track qps accross tests
> Reduce QPS requirement to 100

- client/v3/lease.go
- tests/integration/clientv3/lease/lease_test.go
Fixes a runtime panic that occurs when KeepAlive is called with a Context implemented by an uncomparable type, which is later canceled. The panic message is:
```
panic: runtime error: comparing uncomparable type lease_test.uncomparableCtx
goroutine 380 [running]:
go.etcd.io/etcd/client/v3.(*lessor).keepAliveCtxCloser(0xc000327720, {0x13416c8, 0xc00011b9b0}, 0x14c4932ade455905, 0xc002291420)
/home/kevin/IdeaProjects/etcd/client/v3/lease.go:351 +0x1d6
created by go.etcd.io/etcd/client/v3.(*lessor).KeepAlive in goroutine 156
/home/kevin/IdeaProjects/etcd/client/v3/lease.go:299 +0x554
```
To reproduce the issue, the existing test has been updated to include a custom uncomparable Context implementation. Previously, this test consistently caused a panic due to the uncomparable Context type. The …
> fix runtime error: comparing uncomparable type

- client/v3/lease.go
- tests/integration/clientv3/lease/lease_test.go
Backport of https://github.com/etcd-io/etcd/pull/18893
> [3.5] fix runtime error: comparing uncomparable type

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
https://github.com/etcd-io/etcd/pull/18893
> CHANGELOG: Fix runtime panic that occurs when KeepAlive is called with a Context implemented by an uncomparable type #18893

- server/etcdserver/api/membership/cluster.go
- server/etcdserver/server.go
- server/etcdserver/server_test.go
- tests/integration/v3_watch_restore_test.go
Part of https://github.com/etcd-io/etcd/issues/17098
Alternative to https://github.com/etcd-io/etcd/pull/18635
Goal: Reduce number of raft entries stored in memory
Context:
* Etcd maintains 2 different independently updates storages. V2 - stored as snapshots every X entries (100`000 by default), V3 - memory mapped bbolt storage, flushed every 5 seconds to disk
* Etcd maintains guarantee for the data stored on disk. V3 storage needs to be always fresher than V2 snapshot. Meaning V3 consistent index is >= index of last snapshot.
* This guarantee requires that before writing any V2 snapshots etcd needs to flush V3 storage which is costly.
* In etcd v3.6 no longer uses v2 storage as source of truth, however it maintains periodic snapshot generation for backward compatibility.
* Raft in memory …
> Run a separate in memory snapshot to reduce number of entries stored in raft memory storage

- pkg/expect/expect.go
- pkg/featuregate/feature_gate_test.go
- pkg/netutil/netutil_test.go
- pkg/netutil/routes_linux.go
- pkg/osutil/osutil.go
- pkg/traceutil/trace.go
- tools/.golangci.yaml
enables and fixes [gofumpt](https://golangci-lint.run/usage/linters/#gofumpt) linter issues globally
Closes #18955
> fix: enable gofumpt instead of gofmt linter globally

- codecov.yml
Now that we have enabled proper codecov integration in https://github.com/kubernetes/org/issues/5231 we have noticed pr's being failed for coverage reductions that are trivial, i.e. < .1%.
Let's try and introduce some configuration to make codecov only fail when a meaningful reduction in coverage has occurred.
cc @serathius
> Add a threshold for codecov failure

- server/storage/mvcc/watchable_store.go
- server/storage/mvcc/watchable_store_test.go
- server/storage/mvcc/watcher_test.go
Part of https://github.com/etcd-io/etcd/issues/16839
Improve etcd behavior during watch congestion by reducing the memory needed. 
Congestion causes watch requests to backup and resync loop to allocate tons of memory. This patch has shown to reduce memory needed 5-10 times.
| Reuse events | object size [KB] | etcd memory[MB] | latency 50%ile | latency 90%ile | latency 99%ile |
| ------------ | ---------------- | --------------- | -------------- | -------------- | -------------- |
| FALSE        | 5                | 111.72          | 0.1005         | 0.1543         | 0.1856         |
| TRUE         | 5                | 109.096         | 0.1012         | 0.1556         | 0.1874         |
| FALSE        | 10               | 1103.924        | 2.7177         | 7.3661         | 11.9127        | …
> Reuse events used for syncing watchers

- server/storage/mvcc/watchable_store.go
- server/storage/mvcc/watchable_store_test.go
> Extract rangeEvents function

- server/config/config.go
- server/etcdserver/api/v3rpc/grpc.go
- server/etcdserver/api/v3rpc/watch.go
- server/etcdserver/api/v3rpc/watch_test.go
> Reuse grpcOverheadBytes calculation by creating a function for that

- server/embed/config.go
- server/etcdmain/config.go
- server/etcdmain/help.go
- tests/e2e/etcd_config_test.go
Resolve https://github.com/etcd-io/etcd/issues/18995
cc @fuweid @serathius
> Mark --snapshot-count as deprecated in v3.6 and will be decommissioned in 3.7

- server/etcdmain/config.go
- server/etcdmain/help.go
- tests/e2e/etcd_config_test.go
Part of https://github.com/etcd-io/etcd/issues/12913
> [3.5] Print warning message for deprecated v2 flags if set

- api/etcdserverpb/raft_internal_stringer_test.go
- api/v3rpc/rpctypes/error_test.go
This uses testify instead of testing for t.Fatal or t.Error calls in api package
> fix: use testify instead of t.Fatal or t.Error in api package

- CHANGELOG/CHANGELOG-3.5.md
Link to https://github.com/etcd-io/etcd/pull/18999
> Update 3.5 changelog to cover the warning message for the deprecated v2 flags if set

- tools/.golangci.yaml
Golangci-lint config file is not well formatted. This fixes it
> fix: golangci-lint yamllint

- .github/dependabot.yml
Concerning tools update it seems more appropriate to update only direct dependencies.
They can also be grouped in one PR update.
> chore: group tools/mod updates and update only direct dependencies

- scripts/release.sh
This pull requests:
1. Allows to specify the release version with either the "v" prefix or not (i.e., `v3.6.0` or `3.6.0`)
~2. Sets the `BRANCH` to main if the minor version is `3.6`.~
~Technically, this is not needed if we pass the environment variable `BRANCH` set to `main` with every pre-release. So, another "fix" would be to document this in the release guide. I'm open to reverting and doing the documentation this way.~
Part of #19010.
> release: Allow "v" prefix when specifying release version

- Documentation/contributor-guide/release.md
Spawned from https://github.com/etcd-io/etcd/pull/19011#pullrequestreview-2481614802. Update the release documentation to specify how to do a pre-release from the main branch.
Fixes #19010.
> docs: Add note on releasing a pre-release

- server/config/v2_deprecation.go
- server/embed/config.go
- server/embed/etcd.go
- server/etcdmain/config.go
- server/etcdmain/help.go
- tests/e2e/etcd_config_test.go
Resolve https://github.com/etcd-io/etcd/issues/18994
> Deprecate `--v2-deprecation` and schedule to remove it in 3.8

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
Updated Versions in the changelog file .
Part of https://github.com/etcd-io/etcd/issues/19000
> Update Changelog of 3.5 and 3.4

- contrib/raftexample/kvstore_test.go
- contrib/raftexample/raft_test.go
- contrib/raftexample/raftexample_test.go
This uses testify instead of testing for t.Fatal or t.Error calls in contrib package
> fix: use testify instead of t.Fatal or t.Error in contrib package

- Documentation/contributor-guide/dependency_management.md
> Documentation: consistent way to manage go version

- scripts/test.sh
The original go mod tidy pass implementation was done before the `--diff` go mod option existed. This simplifies the implementation, as temporary files are no longer needed.
> scripts: simplify mod tidy pass

- codecov.yml
Basically we depend on maintainers to decide whether we should add test to improve the coverage for each PR, although we set a 1% threshold for now.
> Set a 80% threshold for the codecov status.patch

- server/embed/serve.go
Extracted from https://github.com/etcd-io/etcd/pull/19040, so as to be reviewed & merged separately.
When server is stopping for whatever reason, the member may fail to publish itself.  In that case, it won't close the ready notify channel, accordingly the etcdserver will get blocked on the ready notification (see below). 
https://github.com/etcd-io/etcd/blob/3cf550d3a47ecee743eaadec1ebd183a0fa88383/server/embed/serve.go#L103
> Do not wait for ready notify if the server is stopping

- server/embed/serve.go
Follow up to https://github.com/etcd-io/etcd/pull/19041
It was a mistake that I made when debugging the `codecov/patch` failure in https://github.com/etcd-io/etcd/pull/19041.  Sorry. Also refer to https://github.com/etcd-io/etcd/pull/19046#issuecomment-2539373718
> Remove duplicated <-s.ReadyNotify()

- scripts/test.sh
The repository scripts now always have the 'sh' extension. Therefore, the find over '*.sh' matches all scripts without the need to append `./scripts/build-binary.sh`, `./scripts/build-docker.sh`, and `./scripts/release.sh`.
> scripts: fix shellws pass

- tests/e2e/logging_test.go
- tests/e2e/zap_logging_test.go
Should fix https://github.com/etcd-io/etcd/issues/18978 as suggested by @ahrtr
> fix(e2e): ignore error log about failed storage update

- etcdctl/ctlv3/command/watch_command_test.go
- etcdctl/go.mod
- etcdctl/go.sum
This uses testify instead of testing for t.Fatal or t.Error calls in client package
> fix: use testify instead of t.Fatal or t.Error in etcdctl packages

- server/etcdserver/version/monitor.go
Don't think those errors are useful or understandable. Function `UpdateStorageVersionIfNeeded` was supposed to wait until cluster version is set, however it missed case that cluster version is set to "3.0.0" temporarily before all members join.
```
{"level":"warn","ts":"2024-12-16T13:21:15.690381+0100","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_SNAPSHOT","remote-peer-id":"fd422379fda50e48","rtt":"0s","error":"dial tcp 127.0.0.1:32380: connect: connection refused"}
{"level":"warn","ts":"2024-12-16T13:21:15.690398+0100","caller":"rafthttp/probing_status.go:68","msg":"prober detected unhealthy status","round-tripper-name":"ROUND_TRIPPER_RAFT_MESSAGE","remote-peer-id":"fd422379fda50e48","rtt":"0s","error":"dial tcp …
```
> Wait for cluster version to non-default value to remove errors when cluster is bootstrapping.

- tests/e2e/logging_test.go
Revert https://github.com/etcd-io/etcd/pull/19060.
After https://github.com/etcd-io/etcd/pull/19068 is merged, we shouldn't see the following error anymore,
```
Messages:   	error level log message found: {"level":"error","ts":"2024-11-16T20:58:00.500222Z","caller":"version/monitor.go:120","msg":"failed to update storage version","cluster-version":"3.6.0","error":"cannot detect storage schema version: missing confstate information","stacktrace":"go.etcd.io/etcd/server/v3/etcdserver/version.(*Monitor).UpdateStorageVersionIfNeeded\n\tgo.etcd.io/etcd/server/v3/etcdserver/version/monitor.go:120\ngo.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).monitorStorageVersion\n\tgo.etcd.io/etcd/server/v3/etcdserver/server.go:2286\ngo.etcd.io/etcd/server/v3/etcdserver.(*EtcdServer).GoAttach.func1\n\tgo. …
```
> Update the allowedErrors in TestNoErrorLogsDuringNormalOperations

- scripts/fix.sh
The BOM fix is called from the `fix-bom` target, which is also a prerequisite for the `fix` target:
https://github.com/etcd-io/etcd/blob/b5c620a75d70380d8117979995e1915d6f16d620/Makefile#L73
Therefore, running `make fix` runs the BOM fix twice.
This is the clipped output from running `make fix`:
```
generating bill-of-materials.json                                                                                                                                                  
% (cd tools/mod && 'go' 'install' 'github.com/appscodelabs/license-bill-of-materials')                                                                                             
% '/home/ivan/.local/share/asdf/installs/golang/1.22.9/packages/bin/license-bill-of-materials' '--override-file' …
```
> scripts: remove duplicate bom fix in fix make target

- pkg/adt/interval_tree_test.go
- pkg/crc/crc_test.go
- pkg/expect/expect_test.go
- pkg/flags/flag_test.go
- pkg/flags/strings_test.go
- pkg/flags/uint32_test.go
- pkg/flags/unique_strings_test.go
- pkg/flags/urls_test.go
- pkg/ioutil/pagewriter_test.go
- pkg/ioutil/readcloser_test.go
- pkg/report/report_test.go
- pkg/report/timeseries_test.go
- pkg/schedule/schedule_test.go
- pkg/stringutil/rand_test.go
- pkg/traceutil/trace_test.go
This uses testify instead of testing for t.Fatal or t.Error calls in pkg package
> fix: use testify instead of t.Fatal or t.Error in pkg package (part 1)

- tools/etcd-dump-logs/main.go
Currently if users explicitly set --start-index=0, it will be ignored. It isn't expected, we should respect it as long as users explicitly set it.
> [tools/etcd-dump-logs] Fix the usage of --start-index in etcd-dump-logs

- Makefile
- scripts/test.sh
This check is duplicated as the project uses revive's `receiver-naming`:
https://github.com/etcd-io/etcd/blob/b53107151a4b0404ef5edebaf11337fb3a80da66/tools/.golangci.yaml#L82-L84
Which is more robust, as the current check may have false positives.
Because `golangci-lint` runs before `verify-receiver-name` it captures the error first (refer to the [prow job](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/etcd-io_etcd/19084/pull-etcd-verify/1869632803721711616) from the test pull request #19084), so this check is unnecessary. Moreover, the current implementation has false positives, as it doesn't detect the issue in that pull request because of a very lax regular expression:
```
make verify-receiver-name
PASSES="receiver_name" ./scripts/test.sh
Running with --race
Starting at: …
```
> scripts: remove receiver name check

- server/storage/backend/backend.go
To remove the ugly nil checks by instantiating the logger with a no-op logger if it is nil.
Fixes #19015
> backend: Remove logger nil checks

- server/storage/schema/schema.go
- server/storage/schema/schema_test.go
Add more info in the error message. 
Also read https://github.com/etcd-io/etcd/pull/13405#discussion_r1890378185
> Add more info in the error message in downgrade detection

- client/internal/v2/client_test.go
- client/internal/v2/keys_bench_test.go
- client/internal/v2/members_test.go
- client/pkg/fileutil/dir_windows.go
- client/pkg/fileutil/fileutil_test.go
- client/pkg/fileutil/read_dir_test.go
- client/pkg/srv/srv_test.go
- client/pkg/tlsutil/cipher_suites_test.go
- client/pkg/transport/keepalive_listener_test.go
- client/pkg/transport/listener_test.go
- client/pkg/transport/timeout_transport_test.go
- client/pkg/types/set_test.go
- client/pkg/types/urlsmap_test.go
- client/v3/client_test.go
- client/v3/compact_op_test.go
- client/v3/ctx_test.go
This uses testify instead of testing for t.Fatal or t.Error calls in client package
> fix: use testify instead of t.Fatal or t.Error in client package (part 1)

- CONTRIBUTING.md
* Fix a couple of broken links related to code styling and linting
* Add `jq` and `xz` to the list of build tools (needed when running `make verify`)
* Add links to the website of all the listed build tools
Fixes #19110
> docs(contributing): fix links and build tool list

- tests/framework/e2e/curl.go
- tests/robustness/failpoint/cluster.go
- tests/robustness/failpoint/failpoint.go
- tests/robustness/report/wal.go
https://github.com/etcd-io/etcd/issues/17118
> Add MemberDowngrade failpoint

- tests/framework/integration/cluster.go
- tests/integration/clientv3/cluster_test.go
```
logger.go:146: 2025-01-07T10:48:59.222Z	WARN	m1	failed to reach the peer URL	{"member": "m1", "address": "http://127.0.0.1:1234/version", "remote-member-id": "8453db59c251d047", "error": "Get \"http://127.0.0.1:1234/version\": dial tcp 127.0.0.1:1234: connect: connection refused"}
logger.go:146: 2025-01-07T10:51:09.907Z	INFO	m1	sending database snapshot	{"member": "m1", "snapshot-index": 10, "remote-peer-id": "2c0c6ac2c3d63c1e", "bytes": 108356, "size": "108 kB", "URLs": "unix://127.0.0.1:2100542460"}
logger.go:146: 2025-01-07T10:51:09.907Z	WARN	m1	failed to send database snapshot	{"member": "m1", "snapshot-index": 10, "remote-peer-id": "2c0c6ac2c3d63c1e", "bytes": 108356, "size": "108 kB", "error": "dial tcp 127.0.0.1:1234: connect: connection refused"}
```
In test case …
> Fix the inconsistent between listen peerURL and advertise peerURL

- server/etcdserver/server.go
- tests/e2e/etcd_mix_versions_test.go
Backport https://github.com/etcd-io/etcd/pull/19140 to 3.5
cc @serathius
> [3.5] Fix mixVersion test case: ensure a snapshot to be sent out

- tests/robustness/client/client.go
- tests/robustness/failpoint/trigger.go
- tests/robustness/traffic/etcd.go
- tests/robustness/traffic/kubernetes.go
Robustness tests now use `kubernetes.Interface` (where possible) replacing use of `kubernetesClient` (deleted)
> Use new interface in robustness tests

- server/embed/etcd.go
- server/embed/serve.go
- server/etcdserver/server.go
- tests/integration/embed/embed_test.go
Fix issue described in #19058. Also refer to #10600. 
**Root cause**
`etcd.Close()` will read remaining items in channel `sctx.serversC` which was supposed to be closed when exiting `serveCtx.serve`. Stopping during bootstrapping may skip closing `sctx.serversC` hence cause `etcd.Close()` stuck.
Skip closing `sctx.serversC`
https://github.com/etcd-io/etcd/blob/aac7ef6bcc78c6aa3b558fdb2d330f3c782652da/server/embed/serve.go#L105-L109
https://github.com/etcd-io/etcd/blob/aac7ef6bcc78c6aa3b558fdb2d330f3c782652da/server/embed/serve.go#L124-L125
`etcd.Close()` reads closed channel
https://github.com/etcd-io/etcd/blob/aac7ef6bcc78c6aa3b558fdb2d330f3c782652da/server/embed/serve.go#L124-L125
> Avoid deadlock in etcd.Close when stopping during bootstrapping

- etcdutl/etcdutl/migrate_command.go
- etcdutl/etcdutl/migrate_command_test.go
- tests/e2e/utl_migrate_test.go
Resolve https://github.com/etcd-io/etcd/issues/17227
cc @serathius @ivanvc @jmhbnz @fuweid @siyuanfoundation 
> Update etcdutl migrate command: load wal records from the latest snapshot

- etcdutl/ctl.go
- etcdutl/etcdutl/check_command.go
- tests/e2e/v2store_deprecation_test.go
> [3.5] support custom content check offline in v2store

- scripts/release_notes.tpl.txt
This PR supersedes #19122.
Add space between `${ETCD_VER}` and the path for docker commands.
> Fix release_notes.tpl.txt by adding a space between Docker image name and version

- scripts/release_notes.tpl.txt
Add space between ${ETCD_VER} and Path
Chery-pick commit 519a2e3a272903d888138e8518ea48333364edf5 / pull request #19153.
> [3.5] Fix release_notes.tpl.txt by adding a space between Docker image name and version

- scripts/release_notes.tpl.txt
Add space between ${ETCD_VER} and Path
Chery-pick commit 519a2e3a272903d888138e8518ea48333364edf5 / pull request #19153.
> [3.4] Fix release_notes.tpl.txt by adding a space between Docker image name and version

- api/go.mod
- api/go.sum
- client/v3/go.mod
- client/v3/go.sum
- etcdctl/go.mod
- etcdctl/go.sum
- etcdutl/go.mod
- etcdutl/go.sum
- go.mod
- go.sum
- pkg/go.mod
- pkg/go.sum
- server/go.mod
- server/go.sum
- tests/go.mod
- tests/go.sum
- tools/mod/go.mod
- tools/mod/go.sum
Remediation for CVE-2024-45338.
> [3.5] bump golang.org/x/net from 0.25.0 to 0.34.0

- tests/robustness/failpoint/cluster.go
- tests/robustness/scenarios/scenarios.go
This should prevent snapshot from being sent in the test.
Tested locally for 100 times, did not see any flakiness.
https://github.com/etcd-io/etcd/issues/19147 
> robustness: only run MemberDowngrade test for high SnapshotCatchUpEntries

- server/etcdserver/api/rafthttp/http.go
Update typo in the warn message
> rafthttp: Improve warn message in checkClusterCompatibilityFromHeader

- embed/etcd.go
- embed/serve.go
- etcdserver/server.go
- integration/embed_test.go
#19150: Backport https://github.com/etcd-io/etcd/pull/19139 to 3.4
> [3.4] Avoid deadlock in etcd.Close when stopping during bootstrapping

- tests/robustness/traffic/traffic.go
Use the highest MaximalQPS of all traffic profiles as burst otherwise actual traffic may be accidentally limited. For example, if burst is set to 200 it is unlikely traffic can achieve higher than 200.
> tests: use high burst value in limiter.

- tests/e2e/utl_migrate_test.go
This PR is extracted from https://github.com/etcd-io/etcd/pull/19168
cc @fuweid @serathius @ivanvc @jmhbnz @siyuanfoundation
> Enhance test case TestEtctlutlMigrate to support multiple member cluster

- server/etcdmain/config.go
- server/etcdmain/config_test.go
fix for #19066 Print warnings when deprecated options are configured in config file
Issue Details
Add warnings when deprecated options are configured
Problem: Currently, etcd doesn't warn users when they configure deprecated options
Goal: Improve user experience by warning about deprecated configurations before they're removed
Solution Overview
Implementation Location: server/config/config.go
> fix for #19066 Print warnings when deprecated options are configured in config file

- server/embed/config.go
- server/embed/etcd.go
- server/etcdmain/config.go
- server/etcdmain/config_test.go
- server/etcdmain/help.go
- tests/e2e/corrupt_test.go
- tests/framework/e2e/cluster.go
Fixes: https://github.com/etcd-io/etcd/issues/19141
Move flag experimental-corrupt-check-time
> migrate flag experimental-corrupt-check-time to use corrupt-check-time

- client/pkg/logutil/zap.go
> client/pkg/logutil: simplify MergeOutputPaths function

- tests/e2e/cluster_downgrade_test.go
- tests/framework/e2e/curl.go
- tests/framework/e2e/downgrade.go
- tests/robustness/failpoint/cluster.go
- tests/robustness/failpoint/failpoint.go
https://github.com/etcd-io/etcd/issues/17118
The MemberDowngradeUpgrade failpoint first downgrades all members, and upgrades some members. This is to test no robustness issue during the whole downgrade-upgrade process, which can be stopped at any point.
Tested locally with 
```
go test -run TestRobustnessExploratory -v --count 100 --failfast --timeout 5h
```
There is a little flakiness due to reasons unrelated to what the test wants to do, like a server fails to start. But that's mainly because we are stopping and restarting the servers many times. I think <5% is probably acceptable.
> add MemberDowngradeUpgrade failpoint

- server/embed/config.go
- server/storage/wal/wal_test.go
- tools/.golangci.yaml
enable [use-any](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#use-any) rule from revive
Also sort revive rules alphabetically
> chore: enable use-any rule from revive

- server/etcdserver/api/membership/cluster.go
Extracted from https://github.com/etcd-io/etcd/pull/19168
> Minor refactor on RaftCluster.Recover()

- tests/robustness/README.md
- tests/robustness/main_test.go
- tests/robustness/makefile.mk
- tests/robustness/scenarios/scenarios.go
- tests/robustness/traffic/etcd.go
- tests/robustness/traffic/traffic.go
This is just an idea about how to reproduce issue 18089 using robustness tests.
With a few tweaks I was able to reproduce the issue by 
* issuing more Delete requests
* running frequent compact
* simulating a slow watch
In my local environment it usually takes 2 to 10 runs (< 1min) to reproduce the issue.
```
make test-robustness-issue18089
...
logger.go:146: 2025-01-11T00:36:07.292Z     ERROR   Broke watch guarantee   {"guarantee": "resumable", "client": 9, "request": {"Key":"/registry/pods/","Revision":539,"WithPrefix":true,"WithProgressNotify":true,"WithPrevKV":true}, "got-event": {"Type":"put-operation","Key":"/registry/pods/default/jzIW7","Value":{"Value":"563","Hash":0},"Revision":540,"IsCreate": …
```
> Add Robustness test to reproduce issue 18089

- server/embed/config.go
- server/embed/etcd.go
- server/etcdmain/config.go
- server/etcdmain/config_test.go
- server/etcdmain/help.go
- tests/e2e/corrupt_test.go
- tests/framework/e2e/cluster.go
- tests/robustness/failpoint/trigger.go
- tests/robustness/options/server_config_options.go
Fixes one flag described in: https://github.com/etcd-io/etcd/issues/19141
> migrate flag experimental-compaction-batch-limit to use compaction-batch-limit

- client/v3/snapshot/v3_snapshot.go
cc @ahrtr @fuweid @ivanvc 
Found case where a leaked file descriptor prevents data being deleted from disk and filling up the disk.
Would like to backport it to all v3.5 and v3.4
> Prevent leaking file descriptor during snapshotting and provide better logging of errors

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
Update 3.4.36 and 3.5.18 Go entries to reflect the 1.22.11 update.
Part of #19210.
> changelog: update Go entry to reflect 1.22.11 update

- tests/framework/e2e/downgrade.go
To fix https://github.com/etcd-io/etcd/issues/19215
> robustness: do not panic when parsing unknown versions.

- server/proxy/tcpproxy/userspace.go
"addr" is the result of net.JoinHostPort which supports IPv6 address.
Rather than ranging "tp.Endpoints" again, it's better to reuse "addr" in the first loop to collect "eps".
See #7942 and #7943 for context.
> server/proxy/tcpproxy: reuse addr in TCPProxy.Run

- pkg/flags/selective_string.go
- pkg/flags/unique_strings.go
This PR introduces tiny optimizations by specifying `len` in `make(map...)` statements
> flags: optimise memory allocation

- contrib/lock/client/client.go
- etcdctl/ctlv3/command/check.go
- etcdctl/ctlv3/ctl.go
- pkg/flags/selective_string.go
- server/etcdserver/api/v2store/store.go
- server/etcdserver/cluster_util.go
- server/proxy/grpcproxy/watcher.go
- server/storage/mvcc/watchable_store.go
- tests/framework/e2e/cluster.go
- tests/integration/clientv3/metrics_test.go
- tests/integration/v3_alarm_test.go
- tests/integration/v3_failover_test.go
- tests/robustness/validate/patch_history.go
- tools/.golangci.yaml
- tools/etcd-dump-logs/raw.go
[early-return](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#early-return): In Go it is idiomatic to minimize nesting statements, a typical example is to avoid if-then-else constructions.
[superfluous-else](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#superfluous-else): To improve the readability of code, it is recommended to reduce the indentation as much as possible. This rule highlights redundant else-blocks that can be eliminated from the code.
> chore: enable early-return and superfluous-else from revive

- tests/common/auth_test.go
Fix https://github.com/etcd-io/etcd/issues/19223
> wait for the member to get started

- server/storage/mvcc/key_index.go
- server/storage/mvcc/key_index_test.go
- server/storage/mvcc/kv_test.go
- server/storage/mvcc/kvstore.go
- tests/e2e/watch_test.go
The tombstone could be the only one available revision in database. It happens when all historical revisions have been deleted in previous compactions. Since tombstone revision is still in database, we should restore it as valid key index. Otherwise, we lost that deletion event if we try to compact on that revision.
REF: #19179 
> mvcc: restore tombstone index if it's first revision

- tests/robustness/failpoint/trigger.go
- tests/robustness/options/server_config_options.go
- tests/robustness/scenarios/scenarios.go
PR https://github.com/etcd-io/etcd/pull/19196 broke robustness test periodics.
/cc @ahrtr @siyuanfoundation @gangli113
>  Fix passing compaction-batch-limit to etcd v3.4 and v3.5

- tests/robustness/traffic/etcd.go
- tests/robustness/traffic/kubernetes.go
- tests/robustness/traffic/traffic.go
Previously proposed in https://github.com/etcd-io/etcd/pull/18773
> Add compaction to kubernetes robustness tests

- tests/common/member_test.go
- tests/framework/integration/bridge.go
- tests/framework/integration/cluster.go
Introducing a new `Bridge` interface to resolve bridge unexported return issue
Part of #18370.
> tests: address bridge unexported return issue

- server/embed/config_test.go
cc @ahrtr @fuweid @AwesomePatrol @siyuanfoundation
> Add tests for NewConfig matching AddFlags defaults

- server/etcdserver/api/etcdhttp/health.go
- server/etcdserver/api/etcdhttp/health_test.go
> etcdserver: add learner check to readyz

- server/mvcc/key_index.go
- server/mvcc/key_index_test.go
- server/mvcc/kv_test.go
- server/mvcc/kvstore.go
- tests/e2e/watch_test.go
The tombstone could be the only one available revision in database. It happens when all historical revisions have been deleted in previous compactions. Since tombstone revision is still in database, we should restore it as valid key index. Otherwise, we lost that event.
(cherry picked from commit d8b41925749ec85b0320839968a2218c4f9dc73f) [#19188](https://github.com/etcd-io/etcd/pull/19188)
> [3.5] mvcc: restore tombstone index if it's first revision

- mvcc/key_index.go
- mvcc/key_index_test.go
- mvcc/kv_test.go
- mvcc/kvstore.go
- tests/e2e/watch_test.go
The tombstone could be the only one available revision in database. It happens when all historical revisions have been deleted in previous compactions. Since tombstone revision is still in database, we should restore it as valid key index. Otherwise, we lost that event.
(cherry picked from commit d8b41925749ec85b0320839968a2218c4f9dc73f) [#19188](https://github.com/etcd-io/etcd/pull/19188)
> [3.4] mvcc: restore tombstone index if it's first revision

- server/embed/etcd.go
- server/embed/serve.go
Fix https://github.com/etcd-io/etcd/issues/19172
Please review this PR commit by commit.
Two high level thoughts,
- There are multiple levels of goroutines. The grandparent ( [StartEtcd](https://github.com/etcd-io/etcd/blob/5d47d7fc2e6bed14c6d3cf71ed3e6a939dd76bd5/server/embed/etcd.go#L99) ) creates multiple child goroutines ( [client listeners](https://github.com/etcd-io/etcd/blob/5d47d7fc2e6bed14c6d3cf71ed3e6a939dd76bd5/server/embed/etcd.go#L776-L780), peer listeners and metrics listeners). The [client listeners](https://github.com/etcd-io/etcd/blob/5d47d7fc2e6bed14c6d3cf71ed3e6a939dd76bd5/server/embed/etcd.go#L776-L780) creates some grandson goroutines (see the first commit).  Each one should only manage their immediate children.
- For `sync.WaitGroup`, we should always call `wg.Add` …
> Fix race condition (also a regression of the PR 19139)

- tests/framework/e2e/cluster.go
- tests/framework/e2e/cluster_test.go
cc @ahrtr @siyuanfoundation @fuweid
> Add tests for hardcoded flags in TestEtcdServerProcessConfig

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
> CHANGELOG: update backport info for #19179

- server/embed/etcd.go
- server/embed/serve.go
Fix https://github.com/etcd-io/etcd/issues/19172
Original solution: https://github.com/etcd-io/etcd/pull/19221
cc @serathius @fuweid
> Refactoring the error handlers concurrent control implementation

- bill-of-materials.json
- etcdutl/go.mod
- etcdutl/go.sum
- go.mod
- go.sum
- server/auth/jwt.go
- server/auth/jwt_test.go
- server/auth/options.go
- server/go.mod
- server/go.sum
- tests/go.mod
- tests/go.sum
github.com/golang-jwt/jwt has a v5 that can be used instead of v4 
See https://github.com/golang-jwt/jwt/blob/main/MIGRATION_GUIDE.md#migration-guide-v500
> build(deps): bump github.com/golang-jwt/jwt from v4 to v5

- server/embed/config.go
- server/embed/etcd.go
- server/etcdmain/config.go
- server/etcdmain/config_test.go
- server/etcdmain/help.go
- tests/e2e/watch_test.go
- tests/framework/e2e/cluster.go
- tests/robustness/scenarios/scenarios.go
Fixes one flag described in: https://github.com/etcd-io/etcd/issues/19141
> migrate flag experimental-watch-progress-notify-interval to use watch-progress-notify-interval

- tests/robustness/main_test.go
Starting with Go 1.20 calling rand.Seed explicitly is no longer needed. 
I'm guessing the deprecated functionality is not needed particularly for robustness testing.
There was an earlier etcd issue https://github.com/etcd-io/etcd/issues/16428 and PR for this in August 2023 https://github.com/etcd-io/etcd/pull/16447.
> Remove explicit random seed in robustness tests

- server/storage/schema/schema_test.go
- server/storage/wal/version.go
- server/storage/wal/version_test.go
- tests/integration/utl_wal_version_test.go
Link to https://github.com/etcd-io/etcd/pull/19168
> Remove the code of checking ClusterVersionSet in MinimalEtcdVersion

- server/embed/config.go
- server/embed/etcd.go
- server/etcdmain/config.go
- server/etcdmain/config_test.go
- server/etcdmain/help.go
Migrate flag warning-apply-duration described in: https://github.com/etcd-io/etcd/issues/19141
> migrate to use warning-apply-duration flag

- server/config/config.go
- server/embed/config.go
- server/embed/etcd.go
- server/etcdmain/config.go
- server/etcdmain/config_test.go
- server/etcdmain/help.go
- server/etcdserver/bootstrap.go
Migrate flag bootstrap-defrag-threshold-megabytes described in: https://github.com/etcd-io/etcd/issues/19141
> migrate to use bootstrap-defrag-threshold-megabytes flag

- tests/e2e/runtime_reconfiguration_test.go
To handle the case of learner not being ready when being promoted, add retry with some delay to improve the stability of e2e tests.
This is for https://github.com/etcd-io/etcd/issues/19216
> tests: Add retry if promote member fails.

- client/v3/kubernetes/interface.go
It wrongly asked the API user to use the last key of previous response when they should append "\x00" to exclude the last key from the contents of the next requested page.
> Fix documentation of List method of Kubernetes interface

- etcdctl/README.md
- tests/e2e/cluster_downgrade_test.go
- tests/framework/e2e/downgrade.go
- tests/framework/e2e/etcdctl.go
Part 1 of the e2e test - downgrade cancellation is called before any of the node is actually downgraded
A README fix was also associated with this PR, as downgrade command doesn't seem to take version as a parameter. 
Reference: https://github.com/etcd-io/etcd/issues/17976
> Add downgrade cancellation e2e tests

- server/etcdserver/api/etcdhttp/health.go
- server/etcdserver/api/etcdhttp/health_test.go
> add learner check to readyz

- server/config/config.go
- server/embed/config.go
- server/embed/etcd.go
- server/etcdmain/config.go
- server/etcdmain/config_test.go
- server/etcdmain/help.go
- server/etcdserver/bootstrap.go
- server/etcdserver/bootstrap_test.go
- tests/framework/integration/cluster.go
- tests/integration/clientv3/cluster_test.go
Migrate flag experimental-max-learners described in: https://github.com/etcd-io/etcd/issues/19141
The experimental flags are marked as deprecated and will be decommissioned in v3.7
> migrate to use max-learners flag

- tests/integration/embed/embed_proxy_test.go
For some reason, the goword check has passed while the file `tests/integration/embed/embed_proxy_test.go` has an error in the godoc. Update it so it doesn't show the error anymore.
Running `goword` against this file returns:
```bash
$ goword ./tests/integration/embed/embed_proxy_test.go
./tests/integration/embed/embed_proxy_test.go.17: // The purpose of this (empty) package is too keep following test working: (godoc-export: The -> // Package embed_test?)
```
I found this while working on another related task.
> Fix goword errors

- tools/local-tester/README.md
- tools/local-tester/bridge.sh
- tools/local-tester/bridge/bridge.go
- tools/local-tester/bridge/dispatch.go
While looking at something else in our `tools/` directory the other day I stumbled into the `local-tester` directory and taking a brief look it seemed to me like it was something we no longer used as we have the massively more comprehensive robustness testing suite now.  The last meaningful update to the tool looked to be about eight years ago.
I propose we mark this old utility as deprecated and remove it in future so we don't confuse anyone with what tool they should be using to validate etcd behaviour under failure conditions.
cc @serathius, @ahrtr
> Mark etcd-local-tester as deprecated so we can remove it in future

- scripts/test_images.sh
While importing the release tests into the Prow infrastructure, after some exploration, I found that the current script didn't work correctly because it allows an input environment variable "IMAGE," which in the Prow infra points to the image from the container. This made the `scripts/test_images.sh` script fail. So, I took an opportunity to rewrite the script in a more modular way while fixing this issue.
* Wrap script in functions, add a main function, and call them from it.
* Make environment variables local inside the function scope to avoid unexpected behaviors by the running environment-supplied variables.
* Fix the typo in the "REPOSITORY" environment variable.
* Rename the input "IMAGE" to "TEST_IMAGE" to avoid clashing with the environment variable from the Prow infrastructure. …
> scripts/test_images.sh: refactor to import job into the prow infrastructure

- server/etcdserver/api/v3compactor/periodic.go
As a new contributor getting familiar with the codebase for the first time, I noticed some inconsistencies in the comments describing the compaction period timing.
>  Correct compaction period comments

- etcdutl/snapshot/v3_snapshot_test.go
The backend commits pending changes into boltdb per 100 ms by default. When brand-new member starts, that member will save member into backend by `MustSaveMemberToBackend`. However, it doesn't force change into boltdb. It depends on backend's auto-commit per 100ms.
If auto-commit happens after `UpdateStorageVersion`, the `UpdateStorageVersion`
will fail on `missing confstate information`. The confstate information is handled by commit-prehook. Once `UpdateStorageVersion` fails, `TestSnapshotStatus` won't have another chance to do that because that
server has been closed. So without storage version information, hash of boltdb data is not expected.
```diff
diff --git a/etcdutl/snapshot/v3_snapshot_test.go b/etcdutl/snapshot/v3_snapshot_test.go
index c2b3d5202..cd88ff995 100644
--- …
```
> deflaky: TestSnapshotStatus

- client/v3/op.go
- tests/robustness/client/client.go
Since #19137, kubernetes traffic profile is unable to send List request with page size, because limit in option is not accessable. To fix it, this fix is to introduce Limit() interface.
Fixes: #19292
> *: introduce (*Op) Limit() interface for robustness

- tests/framework/e2e/downgrade.go
- tests/robustness/failpoint/cluster.go
Part of https://github.com/etcd-io/etcd/issues/19306.
This would reduce the time to run DowngradeUpgradeMembers. But it still would not complete in 1min (still needs about 90s with this change for downgrading and upgrading all 3 members).
@gangli113 is working on changing the failpoint timeout for the `MemberDowngradeUpgrade` failpoint. 
> Remove some HealthInterval to reduce the time to run DowngradeUpgradeMembers

- server/config/config.go
- server/embed/config.go
- server/embed/etcd.go
- server/etcdmain/config.go
- server/etcdmain/config_test.go
- server/etcdmain/help.go
- server/storage/backend.go
This fixes https://github.com/etcd-io/etcd/issues/19061
> migrate experimental-memory-mlock flag to memory-mlock

- scripts/test.sh
When testing on mac os, the script downloads incorrect binary, `ELF 64-bit LSB executable, x86-64, version 1 (SYSV)`, which is not executable on MAC OS. 
With this change, the script downloads executable binary, `Mach-O 64-bit executable x86_64`
> fix test.sh to download correct binary for mac os

- client/pkg/fileutil/fileutil.go
Looks to my eyes that the `continue` statement in `RemoveMatchFile` is redundant? I see no logic below it in the enclosing for loop.
> fileutil: removes redundant continue statement in RemoveMatchFile

- server/embed/config.go
- server/embed/config_test.go
cc @ahrtr @fuweid @AwesomePatrol @siyuanfoundation
> Align NewConfig with AddFlags defaults

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
Update 3.4.36 and 3.5.18 to reflect the go 1.22.12 Update
Subtask of https://github.com/etcd-io/etcd/issues/19333
> changelog: update GO entry to reflect 1.22.12 update

- tests/robustness/failpoint/cluster.go
- tests/robustness/failpoint/failpoint.go
fix https://github.com/etcd-io/etcd/issues/19306
After increasing timeout of DowngradeUpgrade context, test passed
```
--- PASS: TestRobustnessExploratory (247.49s)
--- PASS: TestRobustnessExploratory/EtcdHighTraffic/ClusterOfSize3 (111.99s)
--- PASS: TestRobustnessExploratory/EtcdHighTraffic/ClusterOfSize3/MemberDowngradeUpgrade (109.36s)
--- PASS: TestRobustnessExploratory/EtcdTrafficDeleteLeases/ClusterOfSize3 (61.07s)
--- PASS: TestRobustnessExploratory/EtcdTrafficDeleteLeases/ClusterOfSize3/MemberDowngradeUpgrade (58.64s)
--- PASS: TestRobustnessExploratory/KubernetesHighTraffic/ClusterOfSize3 (71.66s)
--- PASS: TestRobustnessExploratory/KubernetesHighTraffic/ClusterOfSize3/MemberDowngradeUpgrade (69.18s)
--- PASS: TestRobustnessExploratory/KubernetesLowTraffic/ClusterOfSize3 (2.75s) …
```
> increase timeout for MemberDowngradeUpgrade test

- server/embed/config.go
- server/embed/etcd.go
- server/etcdmain/config.go
- server/etcdmain/config_test.go
- server/etcdmain/help.go
Migrate flag `experimental-downgrade-check-time` to `downgrade-check-time`.
Sub task from https://github.com/etcd-io/etcd/issues/19141
> migrate experimental-downgrade-checktime to downgrade-checktime

- tests/robustness/README.md
- tests/robustness/makefile.mk
- tests/robustness/scenarios/scenarios.go
- tests/robustness/traffic/kubernetes.go
- tests/robustness/traffic/traffic.go
NOTE: It's still hard to reproduce it. It may take 5 minutes or few hours.
Closes: #19304 
cc @ahrtr @serathius @siyuanfoundation
> test: update robustness doc and new case to reproduce 19179

- server/embed/config.go
- server/embed/etcd.go
- server/etcdmain/config.go
- server/etcdmain/config_test.go
- server/etcdmain/help.go
Migrate `experimental-compaction-sleep-interval` flag to `compaction-sleep-interval`
Sub task from https://github.com/etcd-io/etcd/issues/19141
> migrate experimental-compaction-sleep-interval flag to compaction-sleep interval

- server/auth/store.go
- server/auth/store_test.go
- server/etcdserver/adapters.go
- server/storage/mvcc/kvstore.go
- server/storage/mvcc/watchable_store.go
- server/storage/mvcc/watchable_store_test.go
- server/storage/schema/auth.go
PR to fix `unexported-return` lint issues under the `server` folder as mentioned in [Issue 18370](https://github.com/etcd-io/etcd/issues/18370). 
This PR:
- uses existing interfaces to fix
> server: fix unexported-return lint issue

- server/config/config.go
- server/embed/config.go
- server/embed/config_test.go
- server/embed/etcd.go
- server/etcdmain/help.go
- server/etcdserver/server.go
- server/features/etcd_features.go
- tests/framework/integration/cluster.go
migrate experimental-enable-lease-checkpoint and experimental-enable-lease-checkpoint-persist flag to feature gate.
to replace https://github.com/etcd-io/etcd/pull/18479
subtask of https://github.com/etcd-io/etcd/issues/18023
> migrate experimental-enable-lease-checkpoint and experimental-enable-lease-checkpoint-persist flag to feature gate.

- etcdutl/snapshot/v3_snapshot.go
- etcdutl/snapshot/v3_snapshot_test.go
- server/storage/mvcc/revision.go
- tests/e2e/ctl_v3_auth_test.go
- tests/e2e/ctl_v3_snapshot_test.go
The new implementation:
- Uses map to track unique keys for accurate counting
- Excludes internal built-in keys from total count
- Improves code maintainability
Although this approach uses additional memory for the map, the trade-off is acceptable since:
- Status() is not in hot path
- Correctness takes priority over performance optimization
- Simpler code is easier to maintain
Fixes #19253
> etcdutl: use map to count unique user keys in snapshot status

- CHANGELOG/CHANGELOG-3.6.md
Link to https://github.com/etcd-io/etcd/pull/19344
> Update 3.6 changelog to cover the etcdutl status command change

- server/embed/config.go
- server/etcdmain/config.go
- server/etcdmain/config_test.go
- server/etcdmain/help.go
To replace https://github.com/etcd-io/etcd/pull/19225
closes https://github.com/etcd-io/etcd/issues/19062
> migrate experimental-peer-skip-client-san-verification flag to peer-skip-client-san-verification

- tests/e2e/cluster_downgrade_test.go
- tests/framework/e2e/downgrade.go
The log message was of the following format before fixing
```
cluster_downgrade_test.go:163: Elect members for operations
%!(EXTRA zapcore.Field={members 1 0  [2 1]})
```
After
```
cluster_downgrade_test.go:163: Elect members for operations zapcore.Field{Key:"members", Type:0x1, Integer:0, String:"", Interface:zap.ints{1}}
```
> Fix a log formatting bug in the e2e downgrade tests

- etcdutl/etcdutl/migrate_command.go
- server/storage/schema/schema.go
- server/storage/wal/version.go
This fixes WALVersion for [issue](https://github.com/etcd-io/etcd/issues/18370)
> Migrate WALVersion to fix unexported-return of walVersion

- server/embed/config.go
- server/etcdmain/config.go
- server/etcdmain/config_test.go
- server/etcdmain/help.go
- tests/framework/e2e/cluster.go
- tests/framework/e2e/cluster_test.go
- tests/framework/e2e/etcd_process.go
Migrate `experimental-snapshot-catchup-entries` flag to `snapshot-catchup-entries`
Sub task from https://github.com/etcd-io/etcd/issues/19141
__Note:__
1. This PR also handles a fix to an unintended bug from [this feature PR](https://github.com/etcd-io/etcd/pull/15033), where the field-name was set as `experimental-snapshot-catch-up-entries` when cmd-line flag `experimental-snapshot-catchup-entries` was used.
2. YAML field `experimental-snapshot-catch-up-entries` will set flag `experimental-snapshot-catchup-entries` correctly at `FlagsExplicitlySet`. This is required to mark / identify the field if used from 'config-file' as a deprecated flag usage.
3. `experimental-snapshot-catch-up-entries` YAML field usage is maintained the same field-name for backward compability.
> migrate experimental-snapshot-catchup-entries flag to snapshot-catchup-entries

- tests/framework/e2e/downgrade.go
Fix https://github.com/etcd-io/etcd/issues/19391
There are two issues in the existing downgrade e2e test cases:
- as long as it's downgrade is enabled, then we should expect a lower cluster version.
- after we upgrade all member to its original version, we should expect a higher cluster version.
Thanks @fuweid for the analysis.
cc @siyuanfoundation @serathius @henrybear327
> [test] Correct the expected version in downgrade test case

- server/embed/config_logging.go
This pull request removes the deprecated `NewZapCoreLoggerBuilder` function.
> server: Remove deprecated NewZapCoreLoggerBuilder

- CHANGELOG/CHANGELOG-3.6.md
Add a deprecation note from #19404.
> CHANGELOG-3.6: Add note from #19404

- server/storage/mvcc/kvstore_compaction.go
Fix https://github.com/etcd-io/etcd/issues/19406
cc @fuweid @serathius @chaochn47 @miancheng7
> Fix a performance regression due to uncertain compaction sleep interval

- server/mvcc/kvstore_compaction.go
The compaction behavior [here](https://github.com/etcd-io/etcd/blob/v3.5.16/server/mvcc/kvstore_compaction.go#L93) is changed in commit
[02635](https://github.com/etcd-io/etcd/commit/0263597ba84f65047948141696be926e53aa2429) and introduces a latency issue. To be more speicific, the `ticker.C`  acts as a fixed timer that triggers every 10ms, regardless of how long each batch of compaction takes. This means that if a previous compaction batch takes longer than 10ms, the next batch starts immediately, making compaction a blocking operation for etcd.
To fix the issue, this commit revert the compaction to the previous behavior which ensures a 10ms delay between each batch of compaction, allowing other read and write operations to proceed smoothly.
issue …
> [release-3.5] Fix a performance regression due to uncertain compaction sleep interval

- scripts/release.sh
Follow up on https://github.com/etcd-io/etcd/issues/19334:
* Properly get the minor version from prereleases (i.e., `v3.6.0-rc.0` → `v3.6`, not `v3.6.0-rc`). I tested it on my fork, and the linked pages are as expected (note that we still have a broken link in the upgrade guide): https://github.com/ivanvc/etcd/releases/tag/v3.6.0-rc.0
* Fix a typo in "flag". It said "flat".
> Fix release script prerelease GitHub template release

- server/lease/lease.go
Use RLock in Demoted method to improve read-only access to expiry with better concurrency.
> perf: use RLock in Demoted method for read-only access to expiry

- server/etcdserver/api/v3alarm/alarms.go
- server/storage/schema/alarm.go
> Move interface `AlarmBackend` from `server/etcdserver/api/v3alarm` to `server/storage/schema` to fix the `unexported-return` lint error

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
Updated the **dependencies** section in `CHANGELOG-3.4.md` under **v3.4.36** and `CHANGELOG-3.5.md` under **v3.5.19** to compile binaries using go 1.23.6.
Subtask of #19417
> Update CHANGELOG for version bump to go 1.23.6

- Documentation/contributor-guide/release.md
As discussed in last two release meetings this pull request simplifies our release permissions process by moving away from manual changes to branch restrictions and instead making the permissions based on membership of the release GitHub team.
Historically for every release we would:
1) Raise a `k/org` pr in advance to give release team elevated permissions by changing the permission levels for groups.
2) Once merged, manually edit our branch restrictions in GitHub so that the release team member running the release script could push the release commit directly to the stable release branch without a pull request.
3) After release raise a `k/org` pr to revoke release team elevated permissions by changing the permission levels for groups.
In future we will instead:
1) Raise a `k/org` pr in …
> Simplify release permissions process

- server/mock/mockstorage/storage_recorder.go
> Rename `storageRecorder` to `StorageRecorder` to fix `unexported-return` lint error

- Documentation/contributor-guide/release.md
Thanks to @jmhbnz and @ivanvc 's long time leadership in the release team, adding them as official leads.
Also adding @siyuanfoundation and @fuweid as additional team members. 
Thanks everyone for your contribution!
> Add release team leads and additional release team members

- CHANGELOG/CHANGELOG-3.6.md
> CHANGELOG: update 3.6 changelog with DowngradeInfo

- tests/integration/clientv3/examples/example_cluster_test.go
- tests/integration/clientv3/examples/example_kv_test.go
- tests/integration/clientv3/examples/example_lease_test.go
- tests/integration/clientv3/examples/example_maintenance_test.go
- tests/integration/clientv3/examples/example_metrics_test.go
- tests/integration/clientv3/examples/example_test.go
- tests/integration/clientv3/examples/example_watch_test.go
Resolving CI issues in https://github.com/etcd-io/etcd/pull/19466 (See [this CI run](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/etcd-io_etcd/19466/pull-etcd-verify/1894134919769100288) for more detail)
> Address issues reported by golangci-lint after bumping the version to v1.64.5

- tests/common/lease_test.go
The following change can reproduce the issue #17504 by `TESTCASE=TestLeaseGrantTimeToLiveExpired/PeerAutoTLS make test-e2e`. We can retry it to reduce flakey possibility, if there is leader change.
```diff
diff --git a/tests/common/lease_test.go b/tests/common/lease_test.go
index afb27c330..dea8459dc 100644
--- a/tests/common/lease_test.go
+++ b/tests/common/lease_test.go
@@ -16,6 +16,7 @@ package common
import (
"context"
+       "sync"
"testing"
"time"
@@ -139,6 +140,18 @@ func TestLeaseGrantTimeToLiveExpired(t *testing.T) {
require.NoError(t, err)
require.Equal(t, int64(1), getResp.Count)
+                               var wg sync.WaitGroup
+                               defer wg.Wait()
+
+                               wg.Add(1)
+                               go func() {
+ …
```
> tests: deflakey TestLeaseGrantTimeToLiveExpired

- tests/common/lease_test.go
Backport https://github.com/etcd-io/etcd/pull/19476 to 3.6
> [3.6] Fix TestLeaseGrantTimeToLiveExpired flaky due to leader change

- tests/integration/clientv3/lease/lease_test.go
Refer to https://github.com/etcd-io/etcd/actions/runs/13499481627/job/37714129702?pr=19426
```
cluster.go:242:  - m0 -> 2f0c1931b70c09a2 (unix://localhost:m0)
lease_test.go:211: chan is closed, want not closed
lease_test.go:211: chan is closed, want not closed
```
> Fix flaky `TestLeaseKeepAliveOneSecond`

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.6.md
Both releases were published successfully during today's release meeting.
cc @ivanvc, @ahrtr
> Add release date for `v3.4.36` and `v3.6.0-rc.1`

- client/v3/retry_interceptor.go
- tests/integration/v3_lease_test.go
With Go v1.24.0 being more strict on the errors usage, it raises some issues in the current codebase.
```bash
% (cd client/v3 && 'go' 'vet' './...')
stderr: # go.etcd.io/etcd/client/v3
stderr: # [go.etcd.io/etcd/client/v3]
stderr: ./retry_interceptor.go:354:48: non-constant format string in call to google.golang.org/grpc/status.Errorf
stderr: ./retry_interceptor.go:356:40: non-constant format string in call to google.golang.org/grpc/status.Errorf
stderr: ./retry_interceptor.go:358:39: non-constant format string in call to google.golang.org/grpc/status.Errorf
% (cd tests && 'go' 'vet' './...')
stderr: # go.etcd.io/etcd/tests/v3/integration
stderr: # [go.etcd.io/etcd/tests/v3/integration]
stderr: integration/v3_lease_test.go:1034:24: non-constant format string in call to fmt.Errorf
FAIL: …
```
> Address Go 1.24 govet errors

- pkg/featuregate/feature_gate.go
- server/etcdserver/metrics.go
- server/etcdserver/server.go
- server/etcdserver/server_test.go
Fix https://github.com/etcd-io/etcd/issues/19324
Add a prometheus metric `etcd_server_feature_enabled`
> Add prometheus metric for server feature gate

- etcdctl/ctlv3/ctl.go
- etcdctl/util/help.go
This PR moves cobra helper of `etcdctl` from main pkg to `etcdctl` pkg. This will remove cobra dependency from main pkg which wasn't necessary.
This PR was created after suggestion in this comment https://github.com/etcd-io/etcd/pull/18183#discussion_r1687171454
Part of https://github.com/etcd-io/etcd/issues/17777
> etcdctl: move cobra helper of etcdctl from main pkg to etcdctl pkg

- client/v3/kv.go
- server/auth/jwt.go
use a more straightforward return value
> refactor: use a more straightforward return value

- CHANGELOG/CHANGELOG-3.7.md
Follow up on pull request https://github.com/etcd-io/etcd/pull/18356
Added changelog file for version 3.7.
Added `UsageFunc` to deprecations section of changelog version 3.6.
/cc @ahrtr @ivanvc
> Add change log 3.7

- tests/common/lease_test.go
Following change deflakes the test here #19500 which can be reproduced by `TESTCASE=TestLeaseGrantKeepAliveOnce make test-e2e`. This change just increases the timeout and checks if the leader has changed.
> tests: deflakey TestLeaseGrantKeepAliveOnce

- .github/workflows/verify-released-assets.yaml
This pull request may seem counter-intuitive, as we're trying to move away from GitHub actions. However, there's no current way of running a CI check like this in Prow. It doesn't support running when the repository has a new tag.
This change:
* Verifies that the `SHA256SUMS` file exists and has the same number of lines as uploaded assets.
* Verifies that the uploaded files match the checksum from the `SHA256SUMS` file
For both GitHub and Google Cloud assets.
I tested this in my fork:
* Successful run: https://github.com/ivanvc/etcd/actions/runs/13648835540
* Failure run: https://github.com/ivanvc/etcd/actions/runs/13648892616
If the workflow fails, the release lead will get an email from GitHub with the failure.
With this check, we should have more confidence when we enable the automatic …
> Add verify release assets GitHub workflow

- api/go.mod
- api/go.sum
- client/pkg/go.mod
- client/v2/go.mod
- client/v3/go.mod
- client/v3/go.sum
- etcdctl/go.mod
- etcdctl/go.sum
- etcdutl/go.mod
- etcdutl/go.sum
- go.mod
- go.sum
- pkg/go.mod
- pkg/go.sum
- raft/go.mod
- server/go.mod
- server/go.sum
- tests/go.mod
- tests/go.sum
- tools/mod/go.mod
- tools/mod/go.sum
Part of https://github.com/etcd-io/etcd/issues/19526.
> [3.5] dependency: bump golang.org/x/net from v0.34.0 to v0.36.0

- go.mod
- go.sum
> [3.4] dependency: bump golang.org/x/net from v0.34.0 to v0.36.0

- scripts/release_mod.sh
Replace `go list -m` with `go mod edit -json`, as the latter can return the same information. This will be helpful when the project migrates to using a Go workspace, as it will return the current module defined in go.mod rather than all the modules from the current directory (using a workspace, the top-level go.mod will return all the child modules from the repository).
Spun off from #19423.
Part of #18409.
> scripts/release: Use `go mod` instead of `go list`

- server/embed/config.go
- server/etcdmain/config.go
- server/etcdmain/config_test.go
- server/etcdmain/help.go
ExperimentalMaxLearners was introduced in v3.6, so there's no need to worry about deprecating, it can be migrated straight into a FeatureGate.
Follow up on https://github.com/kubernetes/kubernetes/pull/130583#issuecomment-2707218268.
> server: remove ExperimentalMaxLearners

- server/proxy/grpcproxy/cluster.go
Fixes: #19553
When a watch channel gets closed, the monitor() function gets stuck in an endless loop, locking and unlocking mutexes and heavily impacting CPU usage
CPU profile data captured during an instance of this issue:
```
File: etcd
Type: cpu
Time: 2025-03-07 10:01:07 GMT
Duration: 10.15s, Total samples = 9.94s (97.90%)
Entering interactive mode (type "help" for commands, "o" for options)
(pprof) web
(pprof) top
Showing nodes accounting for 8560ms, 86.12% of 9940ms total
Dropped 78 nodes (cum <= 49.70ms)
Showing top 10 nodes out of 31
flat  flat%   sum%        cum   cum%
2490ms 25.05% 25.05%     7210ms 72.54%  runtime.selectgo
1390ms 13.98% 39.03%     1630ms 16.40%  runtime.unlock2
1200ms 12.07% 51.11%     1200ms 12.07%  runtime.lock2
810ms  8.15% 59.26%      820ms  8.25% …
```
> fix: grpcproxy can get stuck in and endless loop causing high cpu usage

- server/etcdserver/api/membership/cluster.go
- server/etcdserver/api/membership/cluster_test.go
- server/etcdserver/api/membership/store.go
- server/etcdserver/server.go
- server/etcdserver/server_test.go
- server/verify/verify.go
- tests/e2e/ctl_v2_test.go
Link to https://github.com/etcd-io/etcd/issues/19557
Also added a generic verification on ensure the membership data in v3store is always in sync with v2store.
> [release-3.5] Fix the learner promotion changes not being persisted into v3store (bbolt)

- Makefile
- scripts/markdown_diff_lint.sh
- tools/.markdownlint.jsonc
With this pull request, we add a bash script to run linting check on modified or newly added markdown files. We then add a makefile target to run the script using make. 
Partially resolves #18059
> Tooling for markdown linting

- client/pkg/testutil/before.go
Follow up on: https://github.com/etcd-io/etcd/pull/19440#issuecomment-2691945198
Use the test package's provided Chdir function. Therefore, it's not required to evaluate an error (it doesn't return one) or change directories at the end.
References:
* https://pkg.go.dev/testing#T.Chdir
* https://pkg.go.dev/testing#T.TempDir
Part of #19581
> client/pkg: address Go 1.24 usetesting issues

- server/lease/lessor.go
> [3.5]: use RLock in Demoted method for read-only access to expiry

- OWNERS
Fu Wei (@fuweid) has been actively contributing to etcd for the past 2–3 years. He (and also @ivanvc ) maintains a strong and effective collaboration with the community and tech leads. He not only has a deep understanding of etcd but has also played a key role in the development of v3.6.0.  His contributions have been essential to a smooth release. I propose promoting him to etcd maintainer/approver.
All Fu Wei's PR: https://github.com/etcd-io/etcd/issues?q=state%3Aclosed%20is%3Apr%20author%3Afuweid 
Proof of his expertise in etcd:
1. Resolved the missing delete event on watch: https://github.com/etcd-io/etcd/issues/19179
2. Figured out the root cause of the flaky downgrade e2e test: https://github.com/etcd-io/etcd/issues/19391#issuecomment-2652285100
3. Figured out the root cause why …
> Nominate @fuweid as a new approver

- tests/common/alarm_test.go
- tests/common/auth_test.go
- tests/common/compact_test.go
- tests/common/defrag_test.go
- tests/common/endpoint_test.go
- tests/common/kv_test.go
- tests/common/lease_test.go
- tests/common/maintenance_auth_test.go
- tests/common/member_test.go
- tests/common/role_test.go
- tests/common/status_test.go
- tests/common/txn_test.go
- tests/common/user_test.go
- tests/common/wait_leader_test.go
- tests/common/watch_test.go
Apply `usetesting --fix ./...` on tests/common packages
> tests/common:  address Go 1.24 usetesting issues

- tests/framework/e2e/cluster.go
- tests/framework/e2e/downgrade.go
- tests/framework/e2e/etcd_process.go
- tests/framework/integration/cluster.go
- tests/framework/testutils/execute.go
- tests/framework/testutils/log_observer_test.go
Apply `usetesting --fix ./...` on tests/framework packages
> tests/framework: address Go 1.24 usetesting issues

- .devcontainer/devcontainer.json
I think this is the last missing piece in https://github.com/etcd-io/etcd/pull/19440 :)
Reference:
- https://github.com/etcd-io/etcd/issues/19524
> Bump devcontainer version to 1.24

- Makefile
- tests/robustness/Makefile
This idea came from a robustness meeting where @serathius explained how the robustness tests `Makefile` was structured. Renaming the file to `Makefile` allows users to execute `make` commands from the `tests/robustness` directory. However, to also be able to import it from the top-level `Makefile`, we need to ensure that we are not using relative directories. This is simple to achieve by introducing variables to the repository's top-level, and executing the top-level `make`/`Makefile` from the robustness by using make's `--directory` argument.
/cc @serathius
> test/robustness: rename makefile.mk to Makefile

- tests/framework/e2e/config.go
backport https://github.com/etcd-io/etcd/pull/19640 to 3.6
cc @fuweid
> [release-3.6] Returns the string representation of the `ClusterVersion`

- scripts/markdown_diff_lint.sh
- scripts/test_lib.sh
- scripts/test_utils.sh
From #19604 , the `markdown_diff_lint.sh` fails because of:
```bash
if [[ "$(go list)" != "${ROOT_MODULE}/v3" ]]; then
echo "must be run from '${ROOT_MODULE}/v3' module directory"
exit 255
fi
```
While the `markdown_diff_lint.sh` does not require `go`. The idea is to break `test_lib.sh` into another file that only contains basic functionalities like logging and getting relative path (i.e. `test_utils.sh`). Both `test_lib.sh` and `markdown_diff_lint.sh` will `source` from `test_utils.sh`. 
Solves #18059 
> Split `scripts/test_lib.sh`

- CHANGELOG/CHANGELOG-3.5.md
Add entries from pull requests that were released.
> CHANGELOG-3.5: Set v3.5.20 release date

- server/etcdserver/api/membership/cluster.go
- server/etcdserver/api/membership/cluster_test.go
- server/etcdserver/api/membership/membership_test.go
- server/etcdserver/api/membership/store.go
- server/etcdserver/bootstrap.go
- server/storage/backend/verify.go
- server/storage/schema/membership.go
- tests/e2e/ctl_v3_member_test.go
- tests/go.mod
release-3.6 isn't able to automatically fix the issues which have already been affected by https://github.com/etcd-io/etcd/issues/19557.
Also adding the validation has flaws as mentioned in https://github.com/etcd-io/etcd/issues/19557#issuecomment-2741425899
Eventually I tried to add similar auto sync in 3.6 as what we did for 3.5 in https://github.com/etcd-io/etcd/pull/19606 
This is the only way to avoid all confusion and reduce of user experience.
cc @fuweid @serathius @siyuanfoundation
> [release-3.6] Auto sync members in v3store is IsLearner differs between v2 and v3 store

- CHANGELOG/CHANGELOG-3.6.md
Link to
- https://github.com/etcd-io/etcd/pull/19636
- https://github.com/etcd-io/etcd/issues/19557
cc @serathius @ivanvc @fuweid 
@ivanvc once the PR https://github.com/etcd-io/etcd/pull/19636 gets merged, then we should release v3.6.0-rc.3, thx
> Update 3.6 changelog for the fix to auto sync member in v3store

- tests/e2e/etcd_release_upgrade_test.go
REF: #19557
cc @ahrtr @serathius @siyuanfoundation 
---
Please wait for v3.5.20 release. This case can be pass with latest of release/3.5.
> e2e: add upgrade test for clusters set up by promoted members

- etcdutl/go.mod
- etcdutl/go.sum
- go.mod
- go.sum
- server/go.mod
- server/go.sum
- tests/go.mod
- tests/go.sum
> [release-3.6] dependency: bump github.com/golang-jwt/jwt/v5 from 5.2.1 to 5.2.2

- etcdctl/go.mod
- etcdctl/go.sum
- etcdutl/go.mod
- etcdutl/go.sum
- go.mod
- go.sum
- server/go.mod
- server/go.sum
- tests/go.mod
- tests/go.sum
> [release-3.5] dependency: bump github.com/golang-jwt/jwt/v4 from 4.5.1 to 4.5.2

- scripts/test.sh
Hi folks 👋
I am a newbie and I was excited about contributing to etcd. Currently local development workflow suggests running 'make verify' to verify all checks pass before committing. However, currently this check fails in the main branch. 
Two errors have been faced and fixed. 
- Firstly, updated check for "github.com/prometheus/procfs" in "bill-of-materials.json" to be skipped in OSX.
- Secondly, updated "scripts/test.sh" to download tools "crawford/marker" and "koalaman/shellcheck" for the host OS and architecture. Previously ARM MacOS devices were having errors while running make verify because downloaded version of shellcheck was for linux x86_64 architecture.
For reference, here are the errors faced during local setup.
1. Error before updating `bill-if-materials.json`,
``` …
```
> development: fix 'make verify' errors in OSX

- tests/robustness/model/history.go
- tests/robustness/validate/patch_history.go
- tests/robustness/validate/patch_history_test.go
Reference:
- https://github.com/etcd-io/etcd/issues/19579
> Patch the return time with MaxInt64 in robustness test

- CHANGELOG/CHANGELOG-3.6.md
Link to 
- https://github.com/etcd-io/etcd/pull/19671
- https://github.com/etcd-io/etcd/issues/19670
- https://github.com/etcd-io/etcd/pull/19673
cc @fuweid @ivanvc @serathius @liggitt
> Update 3.6 changelog to cover the revert client/v2 change

- scripts/codecov_upload.sh
This is required to upload a Codecov report in a Prow post submit job.
Reference: 
* Prow documentation: https://docs.prow.k8s.io/docs/jobs/
* Codecov bash script:
```
-C sha       Specify the commit sha
```
> codecov: set commit sha for merges

- tests/robustness/validate/patch_history_test.go
Since we use MaxInt64 to represent infinite for failed transactions, there is no need to provide some infinite ourselves. We can just pass returnTime observed by client and expect it will be set to infinite during preparation step.
/assign @henrybear327
> Pass a non-infinite returnTime in history patching tests

- tests/robustness/model/history.go
- tests/robustness/validate/operations.go
- tests/robustness/validate/patch_history.go
- tests/robustness/validate/patch_history_test.go
- tests/robustness/validate/validate.go
In the current implementation, we patch the return time of failed requests to infinite and save it in the report, so we lose the original return time. 
With the change in this PR, we would now save the return time as-is, and during validation, we patch it to infinite. 
Reference:
- https://github.com/etcd-io/etcd/issues/19579
- https://github.com/etcd-io/etcd/pull/19651#discussion_r2011549432
Closes https://github.com/etcd-io/etcd/issues/19579
> [Robustness test] Preserve return time for failed requests

- client/pkg/types/urls.go
- server/etcdmain/etcd.go
- server/storage/wal/repair.go
- tools/.golangci.yaml
[unnecessary-stmt](https://github.com/mgechev/revive/blob/master/RULES_DESCRIPTIONS.md#unnecessary-stmt): This rule suggests to remove redundant statements like a break at the end of a case block, for improving the code's readability.
> chore: enable unnecessary-stmt rule from revive

- tests/robustness/client/kvhash.go
- tests/robustness/main_test.go
This PR adds only the end-of-test check only.
Test plan:
- `make gofail-enable && make build && make gofail-disable && cd tests/robustness/ && go test -v --count 100 --timeout 10h; cd -`
- `make test-robustness-issue18089`
Reference:
- https://github.com/etcd-io/etcd/issues/18386
> [Robustness Test] Add HashKV check to robustness test

- CHANGELOG/CHANGELOG-3.6.md
Link to https://github.com/etcd-io/etcd/pull/19703 , which is backport of https://github.com/etcd-io/etcd/pull/19694
I will also add the verification in release-3.6 as mentioned in https://github.com/etcd-io/etcd/pull/19694#issuecomment-2768913482 
After that, we should be ready to release `v3.6.0-rc.4`. 
cc @ivanvc @jmhbnz @serathius
> Update 3.6 changelog to cover the membership validation update

- scripts/markdown_diff_lint.sh
- tools/.markdownlint.jsonc
Add `ETCD_ROOT_DIR="$(git rev-parse --show-toplevel)"` in `markdown_diff_lint.sh`. 
Solves #18059 
> markdown lint job: set ETCD_ROOT_DIR to root directory of git repository

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
- CHANGELOG/CHANGELOG-3.6.md
- CHANGELOG/CHANGELOG-3.7.md
Reference:
- https://github.com/etcd-io/etcd/issues/19713
> Update release note for bumping Go to 1.23.8/1.24.2

- tests/robustness/validate/patch_history_test.go
- tests/robustness/validate/validate.go
> Merge operation categorization into one function

- tools/.markdownlint.jsonc
Since our markdown files can be quite varying, we can remove the enforced headings rule. 
Should allow PRs such as https://github.com/etcd-io/etcd/pull/19717 to pass `pull-etcd-markdown-lint` test. Refer to [this](https://prow.k8s.io/view/gs/kubernetes-ci-logs/pr-logs/pull/etcd-io_etcd/19717/pull-etcd-markdown-lint/1910163428895363072) message in prow. 
> Remove required headings rule in markdown checker

- tests/antithesis/Dockerfile.config
- tests/antithesis/README.md
- tests/antithesis/docker-compose.yaml
- tests/antithesis/test-template/Dockerfile.client
- tests/antithesis/test-template/entrypoint/entrypoint.py
This PR moves parts of the [demo](https://github.com/antithesishq/etcd-test-composer/) to the etcd repo. I've also run the tests locally and setup a demo cluster using docker-compose. 
cc @serathius
> Antithesis Integration: Move Antithesis demo to etcd repo

- CHANGELOG/CHANGELOG-3.6.md
`etcdutl snapshot save` never made it to v3.5, so there's no need to list it as a deprecation/removal.
> CHAGELOG-3.6: Remove `etcdutl snapshot save` removal note

- server/storage/mvcc/kvstore_compaction.go
Previously, the compaction pause duration metric was skipped if the number of keys was smaller than `batchNum`, leading to gaps in monitoring data. This change ensures the metric is emitted for every batch, regardless of key count.
> emit compaction pause duration metric in every compaction batch

- server/etcdserver/api/v2store/store_ttl_test.go
- tests/e2e/v2store_deprecation_test.go
- tools/etcd-dump-logs/etcd-dump-log_test.go
Fixes testifylint new issues after this [comment](https://github.com/etcd-io/etcd/pull/19692/commits/3e2d80b150f9770c1dcd984f75fa9719d8a13ac9#r2047457575)
Signed-off-by: Matthieu MOREL <matthieu.morel35@gmail.com>
> chore: fix testifylint new issues

- tools/rw-heatmaps/cmd/root.go
- tools/rw-heatmaps/pkg/chart/line_chart.go
I've been working on this on and off, and I wanted to get it moving before the end of this year.
It implements line charts for the "rw-heatmaps." I want to get some feedback on the resulting charts. We should also rename `tools/rw-heatmaps` to something that suits both heatmaps and line charts.
I'll squash commits as we get closer to merging this.
Supersedes #15060.
/cc @ahrtr @jmhbnz
> Add rw benchmark line chart

- tests/robustness/report/wal.go
Updates the test logic to catch `wal.ErrSliceOutOfRange`. 
ref https://github.com/etcd-io/etcd/issues/19674
> Catch ErrSliceOutOfRange error

- server/etcdserver/api/membership/cluster_test.go
- server/etcdserver/server_test.go
- server/lease/lessor_bench_test.go
- server/storage/backend/batch_tx_test.go
- server/storage/backend/hooks_test.go
- server/storage/backend/testing/betesting.go
- server/storage/wal/testing/waltesting.go
- tests/e2e/utils.go
- tests/e2e/v2store_deprecation_test.go
- tests/framework/e2e/cluster.go
- tests/framework/e2e/cluster_direct.go
- tests/framework/e2e/e2e.go
- tests/framework/e2e/etcd_process.go
- tests/framework/e2e/testing.go
- tests/framework/e2e/util.go
- tests/framework/integration/cluster.go
- tests/framework/integration/integration.go
- tests/framework/integration/testing.go
- tests/framework/unit/unit.go
- tests/integration/v3_leadership_test.go
- tools/.golangci.yaml
enables and fixes [thelper](https://golangci-lint.run/usage/linters/#thelper) linter issues.
Notice that only naming rules are activated here.
> chore: enable thelper linter

- CHANGELOG/CHANGELOG-2.3.md
- CHANGELOG/CHANGELOG-3.0.md
- CHANGELOG/CHANGELOG-3.1.md
- CHANGELOG/CHANGELOG-3.2.md
- CHANGELOG/CHANGELOG-3.3.md
- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
- CHANGELOG/CHANGELOG-3.6.md
- CHANGELOG/CHANGELOG-3.7.md
- CHANGELOG/CHANGELOG-4.0.md
- tools/.markdownlint.jsonc
* Changed all occurrences of `<hr>` to --- in *.md files.
* Disable MD041 - First line in a file should be a top-level heading (https://github.com/DavidAnson/markdownlint/blob/main/doc/md041.md) 
cc @ivanvc @ahrtr @jmhbnz
> Change <hr> occurrences to `---` in Markdown files

- server/storage/mvcc/kvstore_compaction.go
- tests/e2e/metrics_test.go
- tests/e2e/reproduce_19406_test.go
- tests/framework/e2e/metrics.go
This is a follow-up to issue [#19406](https://github.com/etcd-io/etcd/issues/19406).  
The fix in [#19405](https://github.com/etcd-io/etcd/pull/19405) has been merged, and this PR introduces an **e2e test** to reproduce the issue. The goal is to ensure that the test will catch the problem if it resurfaces in the future.  
I have tested this locally and confirmed that the test:  
✅ **Passes consistently** with the fix applied.  
❌ **Fails reliably** if the fix in [#19405](https://github.com/etcd-io/etcd/pull/19405) is rolled back.  
```
% go test -v -run TestReproduce19406
=== RUN   TestReproduce19406
testing.go:25: Changing working directory to: /tmp/TestReproduce194063444741838/001
logger.go:146: 2025-03-14T23:56:18.083Z	INFO	starting server...	{"name": "TestReproduce19406-test-0"} …
```
> Add e2e test to reproduce issue #19406

- Makefile
- test
Add `run-govulncheck` Makefile target for release-3.4 Prow job.
<details>
<summary> Results </summary>
<pre>
➜  etcd git:(makefile-govulncheck) ✗ make run-govulncheck
PASSES="govuln" ./test
Running with TEST_CPUS: 1,2,4
Starting 'govuln' pass at Sun Apr 27 12:13:44 AM +08 2025
Fetching vulnerabilities from the database...
Checking the code against the vulnerabilities...
The package pattern matched the following 131 root packages:
go.etcd.io/etcd/auth/authpb
go.etcd.io/etcd/etcdserver/api/v3rpc/rpctypes
go.etcd.io/etcd/clientv3/credentials
go.etcd.io/etcd/clientv3/internal/endpoint
go.etcd.io/etcd/clientv3/internal/resolver
go.etcd.io/etcd/mvcc/mvccpb
go.etcd.io/etcd/etcdserver/etcdserverpb …
> [release-3.4] Add run-govulncheck Makefile target

- pkg/featuregate/feature_gate.go
- pkg/featuregate/feature_gate_test.go
Avoid returning an unexported struct in the exported New function. Instead, return the MutableFeatureGate interface.
I found this issue in the recently introduced `featuregate` package while reviewing the staleness of #18370. Since this package was introduced in v3.6, it makes sense to merge and backport to `release-3.6`.
/cc @ahrtr @siyuanfoundation 
> pkg/featuregate: Return MutableFeatureGate interface in New function

- pkg/adt/interval_tree_test.go
Adds tests for `IntervalTree.Find()`, following up on https://github.com/etcd-io/etcd/pull/19768#discussion_r2053855066 as part of https://github.com/etcd-io/etcd/issues/19769.
cc @serathius
> adt: add tests for IntervalTree.Find()

- server/etcdserver/api/v3compactor/periodic_test.go
This commit fixes the flaky TestPeriodicHourly test (issue #19499) and similar test cases by introducing an exponential backoff retry mechanism for waiting on actions rather than relying on a fixed timeout.
The root cause of the flakiness was timing inconsistencies in CI environments, where actions sometimes take slightly longer than the expected 10ms timeout set when creating a compactable object.
The new waitWithRetry function attempts to get the expected actions multiple times with exponentially increasing wait periods (10ms, 20ms, 40ms, etc.) before ultimately failing.
The solution was verified by reproducing the issue with an artificial delay and stress-testing the fix with 1000 consecutive runs.
The following test functions were updated to use the new retry mechanism:
- …
> fix(server/etcdserver/api/v3compactor): fix flaky TestPeriodicHourly and others with Retry Mechanism

- tests/antithesis/Makefile
- tests/antithesis/README.md
- tests/antithesis/test-template/Dockerfile
As antithesis requires CGO we cannot compile binary staticly.
/cc @jmhbnz @ivanvc @nwnt
> Fix antithesis docker file removing distroless layer.

- server/etcdserver/txn/txn.go
/cc @ahrtr @fuweid @siyuanfoundation
> Refactor checking put request

- server/etcdserver/apply/apply.go
- server/etcdserver/apply/apply_auth.go
- server/etcdserver/apply/apply_auth_test.go
- server/etcdserver/apply/uber_applier.go
- server/etcdserver/apply/uber_applier_test.go
- server/etcdserver/server.go
- server/etcdserver/server_test.go
/cc @ahrtr @fuweid @siyuanfoundation
> Simplify apply by handling membership apply through the same applyV3 stack

- tests/antithesis/test-template/go-delete-keys/serial_driver_delete_keys.go
This PR addresses [this](https://github.com/etcd-io/etcd/issues/19788) issue. We wish to use the `RecordingClient` existing in the robustness test client library. 
cc @serathius
> Antithesis: Use RecordingClient from robustness tests

- CHANGELOG/CHANGELOG-3.5.md
- CHANGELOG/CHANGELOG-3.6.md
> Update changelog to include fix for compaction pause duration metric

- Makefile
In the case of workflow failures (e.g., flaky tests), we should still upload a partial coverage report to avoid lagging reports on the stable branches.
This is a second take on https://github.com/kubernetes/test-infra/pull/34381.
Fixes #19835.
> make: upload partial coverage reports

- Makefile
- scripts/test.sh
Moving scripts from Prow job (https://github.com/kubernetes/test-infra/blob/master/config/jobs/etcd/etcd-presubmits.yaml) to `test.sh`. 
This is for ease of migrating `release-3.4` and `release-3.5` Github Actions workflows to Prow.
ref: https://github.com/kubernetes/test-infra/issues/32754
/cc @ivanvc
> Add test-release-tests Makefile target

- server/embed/config_test.go
- server/etcdmain/config_test.go
- server/features/etcd_features.go
Because the feature is not feature gated.
See https://github.com/etcd-io/etcd/issues/19050#issuecomment-2553103000 for context 
> remove DistributedTracing from feature gate list.

- Documentation/contributor-guide/bump_etcd_version_k8s.md
Add clearer description to update GOLANG_VERSION when building new etcd image.
> Add instruction to change golang version when building image

- tests/antithesis/test-template/robustness/main.go
- tests/robustness/traffic/etcd.go
Fix #19839 
This currently includes exporting etcdTraffic so it can be reused by the antithesis robustness tests.
> Use robustness traffic generation

- client/v3/naming/endpoints/endpoints.go
This PR cherry-picks commit `28d10d35c07d4fe9faf84e4bf63aa79385c1a821` from `main` into the `release-3.5` branch.
cc: @ahrtr 
> [release 3.5] Backport Deprecated Metadata field in Endpoint struct

- CHANGELOG/CHANGELOG-3.5.md
- CHANGELOG/CHANGELOG-3.6.md
This PR updates the v3.5 and v3.6 changelog entries to include a deprecation notice for the `Metadata` field in the `Endpoint` struct from the `client/v3/naming/endpoints` package.
cc: @ahrtr @ivanvc 
> chore(CHANGELOG): update v3.5 and v3.6 changelog to reflect Endpoint.Metadata deprecation

- Makefile
- scripts/test_images.sh
- scripts/test_lib.sh
- test
Add test-release Makefile target for release-3.4 Prow job.
ref: https://github.com/kubernetes/test-infra/issues/32754
/cc @ivanvc @jmhbnz
> [release-3.4] add test release makefile target

- CHANGELOG/CHANGELOG-3.6.md
3.6 entry for the Go 1.23.9 update.
Part of #19866.
> CHANGELOG(3.6): add Go 1.23.9 entry

- tests/antithesis/README.md
- tests/antithesis/test-template/Dockerfile
- tests/antithesis/test-template/robustness/main.go
- tests/robustness/main_test.go
- tests/robustness/traffic/traffic.go
- tests/robustness/validate/validate.go
- tests/robustness/validate/validate_test.go
In Antithesis we don't have control of failure injection. So we don't have guarantee that the first request will pass.
Changing first request to read fixes the issue of first request not being retryable. Changing the test name prefix to "singleton_driver_" enables antithesis fault injection.
/cc @siyuanfoundation @fuweid @nwnt @henrybear327
> Allow retryable check of database empty and enable failure injection in Antithesis

- scripts/release_notes.tpl.txt
- test
fix: https://github.com/etcd-io/etcd/issues/17278
A part of https://github.com/etcd-io/etcd/pull/19862
Because auto cherry-pick to release-3.4 branch failed, manually backport commit.
/cc @ivanvc @ahrtr
> [release-3.4] release: Fix the tar unzip command, avoid permissions issues

- .github/workflows/antithesis-test.yml
- tests/antithesis/docker-compose.yml
Fixing bug from https://github.com/etcd-io/etcd/pull/19889
> Add ubuntu image to antithesis configuration

- tests/robustness/model/deterministic.go
- tests/robustness/model/non_deterministic.go
```
│  old.bench   │              new.bench              │
│    sec/op    │   sec/op     vs base                │
ValidateLinearizableOperations/Successes-14             13.493m ± 4%   3.658m ± 3%  -72.89% (p=0.000 n=10)
ValidateLinearizableOperations/AllFailures-14           10.663m ± 1%   1.539m ± 6%  -85.57% (p=0.000 n=10)
ValidateLinearizableOperations/PutFailuresWithRead-14    9.742m ± 2%   1.365m ± 1%  -85.99% (p=0.000 n=10)
geomean                                                  11.19m        1.973m       -82.37%
```
/cc @siyuanfoundation @fuweid @nwnt @henrybear327
> Avoid encoding to Json to reduce overhead

- tests/robustness/traffic/etcd.go
This should help recovery from failed Put requests. LIST will read all keys allowing us identify if requests previous write succeeded, thus making linearization cheaper.
/cc @henrybear327 @nwnt
> After failed request fallback to LIST

- CHANGELOG/CHANGELOG-3.5.md
3.5 entry for the Go 1.23.9 update.
Part of https://github.com/etcd-io/etcd/issues/19866.
> CHANGELOG(3.5): add Go 1.23.9 entry

- CHANGELOG/CHANGELOG-3.6.md
listed the removed flags under the v3.6.0-rc.4 (2025-04-15) release
Fixes #19492
> listed removed flags in v3.6.0-rc.3

- CHANGELOG/CHANGELOG-3.4.md
3.4 entry for the Go 1.23.9 update.
Part of https://github.com/etcd-io/etcd/issues/19866.
cc @ivanvc
> CHANGELOG(3.4): add Go 1.23.9 entry

- tests/robustness/model/deterministic.go
- tests/robustness/model/non_deterministic.go
- tests/robustness/model/replay.go
- tests/robustness/model/watch.go
- tests/robustness/report/client.go
Improved visualization for robustness test reports.
* Added `omitempty` to omit empty JSON fields
* Added indentation for report files (e.g. watch.json and operations.json)
Ref: https://github.com/etcd-io/etcd/issues/19901
> robustness: improved visualization for EtcdState and WatchOperation

- server/storage/mvcc/watchable_store.go
- server/storage/mvcc/watchable_store_test.go
This occurs specifically when the watch is for a compacted revision, as there's a possible interleaving of cancel/close that invokes the `cancelWatch` function twice.
It's fairly difficult to provoke the race condition but it is possible to observe on `main` the racing test can fail with a negative gauge:
```
$ go test ./...  -run TestNewWatcherCountGauge/compacted_watch,_close/cancel_race
--- FAIL: TestNewWatcherCountGauge (0.34s)
watchable_store_test.go:86:  # HELP etcd_debugging_mvcc_watcher_total Total number of watchers.
-etcd_debugging_mvcc_watcher_total -1
+etcd_debugging_mvcc_watcher_total 0
FAIL
FAIL    go.etcd.io/etcd/server/v3/storage/mvcc  0.830s
?       go.etcd.io/etcd/server/v3/storage/mvcc/testutil [no test files]
FAIL
```
It seems as though it is partially expected for the …
> mvcc: avoid double decrement of watcher gauge on close/cancel race

- tests/robustness/Makefile
Add `test-robustness-release-3.6` Makefile target
```
make gofail-enable
make build
make gofail-disable
make test-robustness-release-3.6
```
Ref: https://github.com/etcd-io/etcd/issues/19942
/cc @ivanvc @serathius
> Add test-robustness-release-3.6 Makefile target

- tests/integration/member_test.go
This test verifies that etcd no longer panics when restarting after removing a member that was already removed from the cluster.
addresses: issue #13715
cc: @ahrtr
> [Integration Test]: Add test for panic-free removal of non-existent members

- tests/antithesis/test-template/robustness/main.go
- tests/robustness/main_test.go
- tests/robustness/report/wal.go
- tests/robustness/validate/operations.go
- tests/robustness/validate/validate.go
- tests/robustness/validate/validate_test.go
Validation works without persisted requests, it will just take longer.
> Don't panic if could not read the persisted requests

- scripts/release.sh
When we release etcd v3.6.0, we ran into an issue. The command `git tag --list | grep -c "${RELEASE_VERSION}")" -gt 0` returned 64, so it thought the tag v3.6.0 already existed, but actually not. 
So updating the script to exactly match the target tag.
Normally we fix in main, and backport to stable releases, given the tight schedule, so we fix it release-3.6 for now, and backport and forward port to other branches.
> [release-3.6] Update release script to exactly match the target tag

- server/etcdserver/api/membership/cluster.go
- server/etcdserver/api/membership/cluster_test.go
- server/etcdserver/api/membership/storev2.go
- server/etcdserver/apply/uber_applier_test.go
- tests/e2e/v2store_deprecation_test.go
V3 version of https://github.com/etcd-io/etcd/pull/19695
> Assume v3 store is always not nil

- .github/workflows/stale.yaml
As @ivanvc and @jmhbnz  suggested, exempt `help wanted` label for stale action.
Ref: https://github.com/etcd-io/etcd/pull/19932#issuecomment-2892286858
> stale action: exempt help wanted label for stale action

- pkg/adt/interval_tree.go
Splits interval trees by right endpoint on matched left endpoints, to improve exact interval matching performance. 
This addresses the issue: https://github.com/etcd-io/etcd/issues/19769
Additionally I've attached below code snippets and outputs for non-rigorous (Go benchmarks on before/after performance of `Find()` and `Insert()` on randomly built interval trees with multiple occurrences of given left/right endpoint values, which is the regime where I think a performance difference may appear. Run on my laptop, there appears to be no change to the `Insert()` op performance, but a roughly 88% at p-value of 0 (according to benchstat output below) performance increase in `Find()`, on such interval trees.
```
// Benchmark of the Insert op on random interval trees of up to 128 nodes with …
```
> adt: split interval tree by right endpoint on matched left endpoints

- server/etcdserver/raft_test.go
- server/etcdserver/server.go
- server/etcdserver/server_test.go
- tests/framework/integration/cluster.go
It seems [`SyncTicker`](https://github.com/etcd-io/etcd/blob/c849507a3895a93742d83845635e17a069a8ee2e/server/etcdserver/server.go#L269) in `EtcdServer` is no longer used. Should we remove this field?  @serathius
> remove deprecated SyncTicker in EtcdServer

- tests/framework/e2e/cluster.go
- tests/framework/e2e/config.go
- tests/framework/e2e/downgrade.go
followup to https://github.com/etcd-io/etcd/pull/19959#issuecomment-2897914417
cc @fuweid @serathius @ivanvc @jmhbnz 
> Converts between experimental and non-experimental flags in downgrade & upgrade robustness & e2e test

- server/etcdserver/api/membership/cluster.go
- server/etcdserver/api/membership/cluster_test.go
- server/etcdserver/api/membership/membership_test.go
- server/etcdserver/server_test.go
I didn't find know any case where during server lifecycle v2store would be nil. I have a sad suspicion that this condition was introduced just for testing.
Would like to introduce hard assumption to v2 not being nil to ensure that it is properly tested and we are 100% sure that when we move to v3 storage the v2 is not used.
> Assume v2 store is always not nil

- tests/framework/e2e/config.go
Otherwise, we will get flags something like below when converting experimental flag to non-experimental flag,
- `---compaction-batch-limit=10`
- `---watch-progress-notify-interval=100ms`
See errors below,
```
main_test.go:144: failed triggering failpoint, err: failed to find etcd ready lines ["ready to serve client requests"], err: match not found.  Set EXPECT_DEBUG for more info Errs: [unexpected exit code [2] after running [/tmp/etcd-release-3.6-failpoints/bin/etcd --name=TestRobustnessExploratoryKubernetesLowTrafficClusterOfSize1-test-0 --listen-client-urls=http://localhost:20000 --advertise-client-urls=http://localhost:20000 --listen-peer-urls=http://localhost:20001 --initial-advertise-peer-urls=http://localhost:20001 --initial-cluster-token=new …
```
> Remove prefix `--experimental-` instead of `--experimental` from flag

- tests/antithesis/test-template/robustness/traffic/main.go
- tests/robustness/traffic/etcd.go
- tests/robustness/traffic/key_store.go
- tests/robustness/traffic/kubernetes.go
- tests/robustness/traffic/traffic.go
Adds the `keyStore` into `etcdTraffic` which maintains a consistent pool of keys (size 10) such that used keys will be swapped out and replaced with a new key. 
```bash
PERSIST_RESULTS=true EXPECT_DEBUG=true GO_TEST_FLAGS='-v' make test-robustness
```
The porcupine results shows that the uniqueness of keys in early stages for EtcdTrafficDeleteLeases:
and in the later stages:
ref: https://github.com/etcd-io/etcd/issues/19984
/cc @serathius
> Add key window to achieve unique keys for delete operations

- Makefile
- build
- test
Adds `verify-mod-tidy` to `make verify`. 
Ref: https://github.com/kubernetes/test-infra/issues/32754
/cc @ivanvc @abdurrehman107
> [release-3.4] Add verify-mod-tidy Makefile target

- CHANGELOG/CHANGELOG-3.7.md
Changelog for https://github.com/etcd-io/etcd/pull/20017
> Add changelog for otelgrpc to v0.61.0

- server/etcdserver/api/membership/cluster.go
- server/etcdserver/api/membership/cluster_test.go
- tests/e2e/force_new_cluster_test.go
Fix the second issue mentioned in https://github.com/etcd-io/etcd/issues/20009#issuecomment-2910091109
> Add protection on `PromoteMember` and `UpdateRaftAttributes`

- server/etcdserver/api/membership/cluster.go
- server/etcdserver/api/membership/cluster_test.go
- tests/e2e/force_new_cluster_test.go
Backport https://github.com/etcd-io/etcd/pull/20026 to release-3.6.
FYI. also reproduced the panicking issue with only the first commit on release-3.6,
```
{"level":"panic","ts":"2025-05-29T08:44:44.090830+0100","caller":"schedule/schedule.go:202","msg":"execute job failed","job":"server_applyAll","panic":"runtime error: invalid memory address or nil pointer dereference","stacktrace":"go.etcd.io/etcd/pkg/v3/schedule.(*fifo).executeJob.func1\n\tgo.etcd.io/etcd/pkg/v3@v3.6.0/schedule/schedule.go:202\nruntime.gopanic\n\truntime/panic.go:791\nruntime.panicmem\n\truntime/panic.go:262\nruntime.sigpanic\n\truntime/signal_unix.go:917\ngo.etcd.io/etcd/server/v3/etcdserver/api/membership.(*RaftCluster).PromoteMe …
```
> [release-3.6] Add protection on `PromoteMember` and `UpdateRaftAttributes`

- tests/e2e/etcd_release_upgrade_test.go
- tests/e2e/reproduce_19406_test.go
Address usetesting linter issues in `tests/e2e`.
Part of #19581.
> tests/e2e: address usetesting issues

- server/storage/mvcc/watchable_store.go
- server/storage/mvcc/watchable_store_test.go
This occurs specifically when the watch is for a compacted revision, as there's a possible interleaving of cancel/close that invokes the `cancelWatch` function twice.
It's fairly difficult to provoke the race condition but it is possible to observe on `main` the racing test can fail with a negative gauge:
```
$ go test ./...  -run TestNewWatcherCountGauge/compacted_watch,_close/cancel_race
--- FAIL: TestNewWatcherCountGauge (0.34s)
watchable_store_test.go:86:  # HELP etcd_debugging_mvcc_watcher_total Total number of watchers.
-etcd_debugging_mvcc_watcher_total -1
+etcd_debugging_mvcc_watcher_total 0
FAIL
FAIL    go.etcd.io/etcd/server/v3/storage/mvcc  0.830s
?       go.etcd.io/etcd/server/v3/storage/mvcc/testutil [no test files]
FAIL
```
It seems as though it is partially expected for the …
> [release-3.6] mvcc: avoid double decrement of watcher gauge on close/cancel race (3.6 backport)

- server/mvcc/watchable_store.go
- server/mvcc/watchable_store_test.go
This occurs specifically when the watch is for a compacted revision, as there's a possible interleaving of cancel/close that invokes the `cancelWatch` function twice.
It's fairly difficult to provoke the race condition but it is possible to observe on `main` the racing test can fail with a negative gauge:
```
$ go test ./...  -run TestNewWatcherCountGauge/compacted_watch,_close/cancel_race
--- FAIL: TestNewWatcherCountGauge (0.34s)
watchable_store_test.go:86:  # HELP etcd_debugging_mvcc_watcher_total Total number of watchers.
-etcd_debugging_mvcc_watcher_total -1
+etcd_debugging_mvcc_watcher_total 0
FAIL
FAIL    go.etcd.io/etcd/server/v3/storage/mvcc  0.830s
?       go.etcd.io/etcd/server/v3/storage/mvcc/testutil [no test files]
FAIL
```
It seems as though it is partially expected for the …
> [release-3.5] mvcc: avoid double decrement of watcher gauge on close/cancel race (3.5 backport)

- mvcc/watchable_store.go
- mvcc/watchable_store_test.go
This occurs specifically when the watch is for a compacted revision, as there's a possible interleaving of cancel/close that invokes the `cancelWatch` function twice.
It's fairly difficult to provoke the race condition but it is possible to observe on `main` the racing test can fail with a negative gauge:
```
$ go test ./...  -run TestNewWatcherCountGauge/compacted_watch,_close/cancel_race
--- FAIL: TestNewWatcherCountGauge (0.34s)
watchable_store_test.go:86:  # HELP etcd_debugging_mvcc_watcher_total Total number of watchers.
-etcd_debugging_mvcc_watcher_total -1
+etcd_debugging_mvcc_watcher_total 0
FAIL
FAIL    go.etcd.io/etcd/server/v3/storage/mvcc  0.830s
?       go.etcd.io/etcd/server/v3/storage/mvcc/testutil [no test files]
FAIL
```
It seems as though it is partially expected for the …
> [release-3.4] mvcc: avoid double decrement of watcher gauge on close/cancel race (3.4 backport)

- tests/common/auth_test.go
Address usetesting linter issues in `tests/common`.
Part of #19581
> tests/common: address Go 1.24 usetesting issues

- server/etcdserver/bootstrap.go
- tests/e2e/force_new_cluster_test.go
- tests/framework/e2e/cluster.go
- tests/go.mod
See discussion in https://github.com/etcd-io/raft/pull/300. 
`--force-new-cluster` will automatically remove all other members on bootstrap, but it won't work in a corner case (HardState isn't synched to disk, and then etcd crashes). Reproduced the issue in the first commit, and fixed it in the second commit,
```
force_new_cluster_test.go:98: Online checking the member count
force_new_cluster_test.go:101: 
Error Trace:	/Users/wachao/go/src/github.com/ahrtr/etcd/tests/e2e/force_new_cluster_test.go:101
Error:      	"[ID:4075498731181859066 name:"TestForceNewCluster_MemberCount-test-1" peerURLs:"http://localhost:20006" clientURLs:"http://localhost:20005"  ID:14578408409545168728 name:"TestForceNewCluster_MemberCount-test-0" peerURLs:"http://localhost:20001" …
```
> Fix the issue that `--force-new-cluster` can't remove all other members in a corner case

- server/etcdserver/bootstrap.go
- tests/e2e/force_new_cluster_test.go
- tests/framework/e2e/cluster.go
Backport https://github.com/etcd-io/etcd/pull/20055 to 3.6
> [release-3.6] Fix the issue that `--force-new-cluster` can't remove all other members in a corner case

- tests/robustness/traffic/etcd.go
- tests/robustness/traffic/key_store.go
Syncs keys to prevent leaked keys when receiving ListResponse.
Ref: https://github.com/etcd-io/etcd/issues/20034
> Sync keys in keystore on list request response

- tests/integration/cluster_test.go
- tests/integration/corrupt_test.go
- tests/integration/embed/embed_test.go
- tests/integration/grpc_test.go
- tests/integration/hashkv_test.go
- tests/integration/member_test.go
- tests/integration/metrics_test.go
- tests/integration/proxy/grpcproxy/cluster_test.go
- tests/integration/proxy/grpcproxy/kv_test.go
- tests/integration/revision_test.go
- tests/integration/snapshot/member_test.go
- tests/integration/snapshot/v3_snapshot_test.go
- tests/integration/tracing_test.go
- tests/integration/utl_wal_version_test.go
- tests/integration/v3_alarm_test.go
- tests/integration/v3_election_test.go
- tests/integration/v3_failover_test.go
- tests/integration/v3_grpc_inflight_test.go
- tests/integration/v3_kv_test.go
- tests/integration/v3_leadership_test.go
- tests/integration/v3_stm_test.go
- tests/integration/v3_watch_restore_test.go
- tests/integration/v3_watch_test.go
- tests/integration/v3election_grpc_test.go
- tests/integration/v3lock_grpc_test.go
Address usetesting linter issues in `tests/integration`. This is the last part before re-enabling the `usetesting` linter.
Part of #19581.
> tests/integration: address usetesting issues

- Makefile
- test
Separates the grpcproxy tests and adds the Makefile target for integration and e2e grpcproxy tests.
Ref: https://github.com/kubernetes/test-infra/issues/32754
/cc @ivanvc @abdurrehman107 
> [release-3.4] Add grpcproxy Makefile targets

- server/etcdmain/config_test.go
Prepare to remove v2discovery in main.
> Update `--discovery` related test cases to use v3discovery flags

- server/embed/config.go
- server/embed/config_test.go
Extracted from https://github.com/etcd-io/etcd/pull/20109.
Verify that the discovery endpoint isn't empty, and we should backport this minor fix to 3.6.
cc @serathius 
> Verify that the discovery endpoint isn't empty

- etcdctl/ctlv3/command/ep_command.go
Fix https://github.com/etcd-io/etcd/issues/20118
Note both `etcdctl endpoint health`  and `etcdctl endpoint health --cluster` have this issue.
`flags.SetPflagsFromEnv` should only be called once.  It has already been called in `clientConfigFromCmd`, so there is no need to call it again in `epHealthCommandFunc`.
Also reverted https://github.com/etcd-io/etcd/pull/18742 to fix the `etcdctl endpoint health --cluster` issue
> Update 'endpoint health' command to avoid calling `flags.SetPflagsFromEnv` multiple times

- tests/antithesis/test-template/robustness/finally/main.go
- tests/robustness/validate/operations.go
- tests/robustness/validate/operations_test.go
- tests/robustness/validate/result.go
- tests/robustness/validate/validate.go
- tests/robustness/validate/validate_test.go
- tests/robustness/validate/watch.go
Fixes https://github.com/etcd-io/etcd/issues/19971
This allows to properly pass error message to antithesis assertion, and allows to avoid marking assertion success if the validation didn't run.
This helps with debugging cases like there where error is serialized to json as `{}` 
From https://linuxfoundation.antithesis.com/report/619OBPxquzXWE8b5L9-nNH6t/tpWvKQeJd1lxZ5sgXF_V2MXxeFzD-ByofuZurvqSrZc.html?auth=v2.public.eyJzY29wZSI6eyJSZXBvcnRTY29wZVYxIjp7ImFzc2V0IjoidHBXdktRZUpkMWx4WjVzZ1hGX1YyTVh4ZUZ6RC1CeW9mdVp1cnZxU3JaYy5odG1sIiwicmVwb3J0X2lkIjoiNjE5T0JQeHF1elhXRThiNUw5LW5OSDZ0In19LCJuYmYiOiIyMDI1LTA2LTAyVDIxOjI4OjQ5LjkxMDIxNDM0NFoiffD4EfpAyeld22ULRE3c7bLSwLfZnrndwoLK3xEZNS9NSodLnVBBi4dnOfNIrSFJFLb2JJu1jVudzbAh95w_HQw
/cc @nwnt @henrybear327 @joshjms @marcushodgsonantithesis @fuweid …
> Introduce Result struct to represent ternary result: success, failure unknown

- tests/robustness/model/deterministic.go
/cc @nwnt @henrybear327 @joshjms @marcushodgsonantithesis @fuweid @siyuanfoundation
> Ignore leases from failed requests greatly reducing linearization search space

- tests/e2e/cmux_test.go
Ensures tests to run successfully in Debian 12.
Partial backport of https://github.com/etcd-io/etcd/pull/16516.
/cc @ivanvc @jmhbnz 
> [release-3.4] Backport removing obsolete http 1.0 version for cmux tests

- CHANGELOG/CHANGELOG-3.6.md
Link to https://github.com/etcd-io/etcd/pull/20154
@Elbehery @fuweid @ivanvc @jmhbnz @serathius @tjungblu
> Update 3.6.2 changelog to cover bumping bbolt to 1.4.1

- GOVERNANCE.md
cc @fuweid @ivanvc  @jmhbnz @serathius @siyuanfoundation  @spzala @wenjiaswe @jberkus
> Update the Decision-making process and transparency

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
Part of: https://github.com/etcd-io/etcd/issues/20126
> CHANGELOG(3.4,3.5): Add Go 1.23.10 note

- Makefile
- test.sh
This PR adds `run-govuluncheck` makefile target for release-3.5.
ref: https://github.com/kubernetes/test-infra/issues/32754#issuecomment-2942746295
> [release-3.5] Add makefile target for run-govuluncheck

- etcdctl/ctlv3/command/printer_json.go
A necessary "pre-change" for #19469.
The `jsonPrinter` struct now includes an `io.Writer` field, enabling unit testing of this module.
> etcdctl: refactor json printing to support custom writers

- Documentation/contributor-guide/release.md
Adds the dry run directive into the release instructions. 
/cc @jmhbnz @ivanvc 
> Add dry run instruction for release

- tools/proto-annotations/cmd/etcd_version.go
There is a [new function](https://pkg.go.dev/slices@go1.21.0#Contains) added in the go1.21 standard library, which can make the code more concise and easy to read.
> refactor: use slices.Contains to simplify code

- tests/antithesis/test-template/robustness/traffic/main.go
- tests/robustness/client/client.go
- tests/robustness/client/watch.go
- tests/robustness/main_test.go
- tests/robustness/traffic/traffic.go
> Refactor recording client management

- etcdctl/ctlv3/command/check.go
- pkg/report/perfdash.go
- pkg/report/report.go
- pkg/report/report_test.go
- pkg/report/weighted.go
- tools/benchmark/cmd/lease.go
- tools/benchmark/cmd/mvcc-put.go
- tools/benchmark/cmd/put.go
- tools/benchmark/cmd/range.go
- tools/benchmark/cmd/root.go
- tools/benchmark/cmd/stm.go
- tools/benchmark/cmd/txn_mixed.go
- tools/benchmark/cmd/txn_put.go
- tools/benchmark/cmd/util.go
- tools/benchmark/cmd/watch.go
- tools/benchmark/cmd/watch_get.go
- tools/benchmark/cmd/watch_latency.go
This PR introduces the `--json` flag to the benchmark utility to produce JSON reports that are compatible with the `perfdash` format. 
This will enable systematic performance tracking and visualization of etcd performance metrics over time, with the scope to integrate with CI while helping to identify regressions and analysis of performance trends over time.
Sample usage:
```
> benchmark put --json
...
2025/06/10 08:14:01 INFO: [core] [Channel #1]Channel Connectivity change to READY
10000 / 10000 [---------------------------------------------------------------------------------------------------------------------------] 100.00% 2062 p/s
Successfully created a JSON perf report at _artifacts/etcd_perf_2025-06-10T12:14:06Z.json
Summary:
Total:	5.0494 secs.
Slowest:	0.0036 secs.
Fastest: …
```
> Add support to generate JSON report to the benchmark tool

- .github/ISSUE_TEMPLATE/bug-report.yml
- security/README.md
- security/email-templates.md
- security/security-release-process.md
Revert https://github.com/etcd-io/etcd/pull/17590
Previously we temporally moved to use etcd maintainers mailing list from security@etcd.io in https://github.com/etcd-io/etcd/pull/17590, while we were discussing how to resolve the security@etcd.io migration in https://github.com/kubernetes/k8s.io/pull/6542.
Now the security@etcd.io is working well, so let's continue to use security@etcd.io
cc @fuweid  @ivanvc @jberkus @jmhbnz  @serathius @siyuanfoundation @spzala
> Use security@etcd.io to receive any CVE report

- test.sh
Ref: https://github.com/etcd-io/etcd/pull/20168#issuecomment-2990238028
/cc @ivanvc @serathius 
> [release-3.5] Remove integration_extra from integration tests

- tests/robustness/validate/patch_history_test.go
- tests/robustness/validate/result.go
- tests/robustness/validate/validate.go
This PR adds requests that we don't linearize to visualization.
Ref https://github.com/etcd-io/etcd/issues/19029
We don't linearize all requests, because it's inefficient or impossible. This prevents them being showed in linearization. A new feature in porcupine allows adding manual annotations. The added requests are shown as gray.
As result we have more complete view of everything that happens during a test.
/cc @ahrtr @joshjms @nwnt @siyuanfoundation @fuweid
> Add non-linearizable requests to visualization

- tests/robustness/model/deterministic.go
/cc @joshjms @nwnt @fuweid @siyuanfoundation
> Split model Step function

- tests/robustness/client/watch.go
- tests/robustness/main_test.go
After https://github.com/etcd-io/etcd/pull/20229 restriction in progress notification has started causing flakes in robustness tests 
/cc @ahrtr @siyuanfoundation @fuweid @nwnt @henrybear327
> Disable progress notify validation until we can guarantee response

- tests/robustness/client/watch.go
- tests/robustness/main_test.go
Backport https://github.com/etcd-io/etcd/pull/20240 to prevent flakes in presubmits.
/cc @ahrtr @siyuanfoundation @fuweid @nwnt @henrybear327
> [release-3.6] Disable progress notify validation until we can guarantee response

- Documentation/contributor-guide/triage_prs.md
cc @fuweid @ivanvc @jmhbnz @serathius @siyuanfoundation @spzala
> Add review policy

- CHANGELOG/CHANGELOG-3.6.md
Add 3.6.2 changelog entry from the bbolt bump to 1.4.2.
> CHANGELOG(3.6): Add bbolt 1.4.2 entry

- tests/go.mod
- tests/go.sum
- tests/robustness/coverage/README.md
- tests/robustness/coverage/coverage_test.go
- tests/robustness/coverage/kind-with-tracing.yaml
- tests/robustness/coverage/testdata/.gitignore
It pulls a file from testdata with traces collected by Jaeger and then iterates over them in order to group them into those which use the contract interface, are known (and usually valid) uses outside of it. Later it can further analyze the parameters used over the run of Kubernetes conformance tests.
```
=== RUN   TestInterfaceUse/otlp_etcd-2025-07-03.json
coverage_test.go:55: Traces found: 64228
coverage_test.go:66: API calls by gRPC method: map[etcdserverpb.KV/Compact:50 etcdserverpb.KV/R
ange:36761 etcdserverpb.KV/Txn:25450 etcdserverpb.Lease/LeaseGrant:1554 etcdserverpb.Maintenance/St
atus:412 etcdserverpb.Watch/Watch:1]
=== RUN   TestInterfaceUse/otlp_etcd-2025-07-04.json
coverage_test.go:55: Traces found: 100000
coverage_test.go:66: API calls by gRPC method: …
```
> Add Kubernetes API coverage test consuming traces

- scripts/test_images.sh
Ref: https://github.com/kubernetes/test-infra/issues/32754
Continuation of #20168
Partial backport of #19305
Rename the input "IMAGE" to "TEST_IMAGE" to avoid clashing with the environment variable from the Prow infrastructure.
<details>
<summary>Results in pj-on-kind</summary>
<pre>
% '/home/prow/go/src/github.com/etcd-io/etcd/scripts/test_images.sh'
a92a0d16d13e6ac3add6d08bb8edb7b7b8541bc07ac21804ffb3f134862c638d
Succesfully tested etcd local image v3.5.99-amd64
Correct Architecture v3.5.99-amd64
Correct Architecture v3.5.99-arm64
Correct Architecture v3.5.99-ppc64le
Correct Architecture v3.5.99-s390x
test_etcd
'release_tests' completed at Mon Jul  7 09:39:51 UTC 2025
SUCCESS
+ EXIT_VALUE=0
+ set +o xtrace
Cleaning up after docker in docker. …
> [release-3.5] Fix error in pull-etcd-release-tests when running in Prow

- tests/robustness/coverage/kind-with-tracing.yaml
Introduced in https://github.com/etcd-io/etcd/pull/20181. It caused `make verify-yamllint` fail with the following error:
```
./tests/robustness/coverage/kind-with-tracing.yaml
1:1       warning  missing document start "---"  (document-start)
4:1       error    wrong indentation: expected at least 1  (indentation)
6:3       error    wrong indentation: expected at least 3  (indentation)
```
/cc @serathius
> Fix yamllint errors

- pkg/traceutil/trace.go
- pkg/traceutil/trace_test.go
- server/etcdserver/apply/apply.go
- server/etcdserver/txn/delete.go
- server/etcdserver/txn/put.go
- server/etcdserver/txn/range.go
- server/etcdserver/txn/txn.go
- server/etcdserver/v3_server.go
Part of https://github.com/etcd-io/etcd/issues/12460 split from https://github.com/etcd-io/etcd/pull/20307.
`traceutil.New` is removed in favor of `traceutil.EnsureTrace` (previously used only in `go.etcd.io/etcd/server/v3/etcdserver`) in order to unify the method of creating Spans. This in turn makes it easier to migrate to OpenTelemetry tracing.
> Move EnsureTrace to traceutil

- pkg/go.mod
- pkg/traceutil/trace.go
- server/embed/config_tracing.go
- server/etcdserver/v3_server.go
- server/go.mod
- tests/integration/tracing_test.go
Part of https://github.com/etcd-io/etcd/issues/20182 and https://github.com/etcd-io/etcd/issues/12460
This adds new spans in `Range` and `Txn` methods. This makes it easier to distinguish actual execution time from the overhead of grpc and other pre/post processing.
Attributes added:
1. `Range`:
* `range_begin` (`key` field in proto), `range_end` - used to better understand key transformations from other systems (like Kubernetes)
* `rev` - revision used to distinguish between requests for old or latest data
* `limit` - lists vs gets
* `count_only` (boolean)
2. `Txn`:
* `first_compare_key` - first non-empty key from `compare`s
* `compare_len` - the number of compare operation in the request
* `failure_len`, `success_len` - counts for `failure` and `success` operations in the request
* …
> Add OpenTelemetry Spans to Range and Txn

- CHANGELOG/CHANGELOG-3.5.md
Link to
- https://github.com/etcd-io/etcd/pull/20357
- https://github.com/etcd-io/etcd/issues/20351
> Update 3.5 changelog to cover the v2store check false alarm

- tests/antithesis/server/Dockerfile
- tests/antithesis/server/inject/verify.patch
As a follow up of #20312.  This replaces `verify.Verify` with Antithesis's `assert.Always`.
Note, I had to use `git apply` instead of `patch` because patch does not exist on the image.
cc @serathius @ahrtr
> Inject antithesis at verify.Verify

- CHANGELOG/CHANGELOG-3.4.md
- CHANGELOG/CHANGELOG-3.5.md
- CHANGELOG/CHANGELOG-3.6.md
Source PR: #20328 
Issue: #20224
> CHANGELOG(3.4,3.5,3.6): Add update in docs of --quota-backend-bytes

- server/etcdserver/v3_server.go
Part of https://github.com/etcd-io/etcd/issues/20182 and https://github.com/etcd-io/etcd/issues/12460
Attributes added:
1. `Put`: method not used by Kubernetes outside integration tests
* `key`
2. `DeleteRange`: method not used by Kubernetes outside integration tests
* `range_begin`
* `range_end`
3. `Compact`: method not part of k8s-etcd interface, but added for completeness
* `rev`
4. `Range`:
* `keys_only` - used by Kubernetes 1.34 since https://github.com/kubernetes/kubernetes/pull/132355 (depending on feature gate)
Events added:
1. `Send raft proposal`
2. `Receive raft result`
> Add OpenTelemetry Spans to Put, DeleteRange, Compact

- server/etcdserver/api/membership/cluster.go
- tests/e2e/member_no_proxy_test.go
fix https://github.com/etcd-io/etcd/issues/20340
Backport https://github.com/etcd-io/etcd/pull/20391 to 3.6.
> [release-3.6] Check promotion against v2store when updating v2store

- CHANGELOG/CHANGELOG-3.6.md
link to
- https://github.com/etcd-io/etcd/pull/20387
- https://github.com/etcd-io/etcd/issues/20340
> Update 3.6 changelog to cover the etcdserver bootstrap failure when replaying learner promotion operation

- tests/integration/tracing_test.go
It was broken by https://github.com/etcd-io/etcd/pull/20389
```
logger.go:146: 2025-07-24T10:46:57.742Z	WARN	default	request stats	{"start time": "2025-07-24T10:46:57.741Z", "time spent": "433.165µs", "remote": "127.0.0.1:41996", "response type": "/etcdserverpb.KV/Range", "request count": 0, "request size": 7, "response count": 0, "response size": 28, "request content": "key:\"key\" count_only:true "}
tracing_test.go:204: Span mismatch (-want +got):
(*v1.Span)(Inverse(protocmp.Transform, protocmp.Message{
"@type": s"opentelemetry.proto.trace.v1.Span",
"attributes": []protocmp.Message{
... // 3 identical elements
{"@type": s"opentelemetry.proto.common.v1.KeyValue", "key": string("limit"), "value": protocmp.Message{"@type": s"opentelemetry.proto.common.v1.AnyValue", "int_value": int64(0)}}, …
```
> Add missing keys_only attribute to tracing test

- cache/cache.go
- cache/cache_test.go
validateWatchRange is renamed as validateRequestRange so that it can be reused by other function in future like validateGet
> cache: rename validateWatchRange as validateRequestRange

- etcdctl/ctlv3/command/printer_json.go
- etcdctl/ctlv3/command/printer_json_test.go
Fix #19262.
Example output of `etcdctl member remove 1234567890 --write-out json --hex` command:
```json
{
"header": {
"cluster_id": 14841639068965178418,
"member_id": 10276657743932975437,
"raft_term": 5
},
"members": [
{
"ID": 10276657743932975437,
"name": "default",
"peerURLs": [
"http://localhost:2380"
],
"clientURLs": [
"http://localhost:2379"
]
}
]
}
```
```json
{
"header": {
"cluster_id": "cdf818194e3a8c32",
"member_id": "8e9e05c52164694d",
"raft_term": 5
},
"members": [
{
"ID": "8e9e05c52164694d",
"name": "default",
"peerURLs": [
"http://localhost:2380"
],
"clientURLs": [
"http://localhost:2379"
]
}
]
}
```
> Update `etcdctl member remove` command to support printing clusterID and memberID in hex

- CHANGELOG/CHANGELOG-3.7.md
- pkg/netutil/host_normalize.go
- pkg/netutil/host_normalize_test.go
- pkg/netutil/netutil.go
This is an IPv6 address comparison logic fix for Issue #15127
The issue is that `etcd` fails to bootstrap clusters because IPv6 addresses do not match literally even when they are equivalent (Example: `c262:266f:fa53:0ee6:966e:e3f0:d68f:b046` vs `c262:266f:fa53:ee6:966e:e3f0:d68f:b046` - note the leading zero difference in the fourth group)
1. Created new IPv6 normalization logic that normalizes IPv6 and IPv4 addresses to their canonical string representation
2. Modified [urlsEqual()](https://github.com/etcd-io/etcd/blob/ea69bcafdbbcb57e2c12d5a394b630564db8c7e0/pkg/netutil/netutil.go#L148) function to use the new normalization-based comparison instead of [reflect.DeepEqual](https://github.com/etcd-io/etcd/blob/ea69bcafdbbcb57e2c12d5a394b630564db8c7e0/pkg/netutil/netutil.go#L157)
3. These …
> netutil: Refactor IPv6 address comparison logic

- cache/cache.go
> cache: refactor validateWatch to use a switch for unsupported watch ops

- etcdctl/ctlv3/command/printer_json.go
- etcdctl/ctlv3/command/printer_json_test.go
Fix #19262.
Example output of `etcdctl member promote 21a5a012a514cca2 -w json --hex` command:
```json
{
"header": {
"cluster_id": 14841639068965178418,
"member_id": 10276657743932975437,
"raft_term": 3
},
"members": [
{
"ID": 2424519976348339362,
"name": "test-node",
"peerURLs": [
"http://127.0.0.1:12380"
],
"clientURLs": [
"http://127.0.0.1:12379"
]
},
{
"ID": 10276657743932975437,
"name": "default",
"peerURLs": [
"http://localhost:2380"
],
"clientURLs": [
"http://localhost:2379"
]
}
]
}
```
```json
{
"header": {
"cluster_id": "cdf818194e3a8c32",
"member_id": "8e9e05c52164694d",
"raft_term": 4
},
"members": [
{
"ID": "8e9e05c52164694d",
"name": "default",
"peerURLs": [
"http://localhost:2380"
],
"clientURLs": [
"http://localhost:2379"
]
},
{
"ID": "21a5a012a514cca2",
"name": …
```
> Update `etcdctl member promote` command to support printing clusterID and memberID in hex

- server/etcdmain/help.go
The flag `--experimental-snapshot-catch-up-entries` doesn't exist. Only `--experimental-snapshot-catchup-entries` is correct. But we made a mistake, if users configure the flag via a config file, then both `experimental-snapshot-catch-up-entries` and `experimental-snapshot-catchup-entries` are accepted.
FYI. in main (3.7), only `--snapshot-catchup-entries` is correct (`snapshot-catchup-entries` for config file)
> [release-3.6] Remove the --experimental-snapshot-catch-up-entries from help

- tests/integration/cache_test.go
To address this comment: https://github.com/etcd-io/etcd/pull/20372#discussion_r2226341294 
This PR updates `TestCacheWithPrefixGet` to assert the specific `ErrKeyRangeInvalid` error instead of merely checking that `err != nil`.
> cache: consolidate ErrKeyRangeInvalid assertion in TestCacheWithPrefixGet

- etcdserver/api/membership/cluster.go
- etcdserver/api/v3rpc/watch.go
- etcdserver/raft.go
- etcdserver/server.go
- mvcc/backend/backend.go
- mvcc/backend/batch_tx.go
- mvcc/kvstore.go
- mvcc/kvstore_compaction.go
fixes #17817
This PR backports gofail comments to the release-3.4 branch.
Skipping gofail comments for [`batch_tx.go`](https://github.com/etcd-io/etcd/blob/release-3.5/server/mvcc/backend/batch_tx.go) since this hook is not used/available in `v3.4`.
https://github.com/etcd-io/etcd/blob/e483d1f1b66e76bfaa14128dfa6a98827fbe67d2/server/mvcc/backend/batch_tx.go#L361-L366
> [release-3.4] back port gofail comments

- cache/demux.go
- cache/ringbuffer.go
- cache/ringbuffer_test.go
@serathius @MadhavJivrajani 
Opened this PR to makes ring buffer generic (not just for events but for snapshots in future). This includes:
- renamed `Filter` as `GetFromRevision` and apply binary search instead of full scan
- added a few new functions like `FindAtOrBefore` which might be useful for snapshots
For now I use a `RevisionOf[T]` function to extract revisions from any item type, maybe should later switch to a wrapper that contains the revision directly
> cache: make ring buffer generic for events and snapshots

- server/storage/schema/schema.go
- server/storage/schema/schema_test.go
- tests/e2e/logging_test.go
The field `confState` was added since etcd v3.5. If an etcd cluster was created since v3.4, then it wouldn't have this field. In 3.5+, the field will only be automatically populated during conf change (i.e. add/remove/update member). So when upgrading from 3.4 to 3.5, and from 3.5 to 3.6, the field will never be populated unless users add or remove or update members.
Note if you can't reproduce this issue, it should be because that there is no v2 snapshot, and etcdserver will replay all WAL records (including add member records) on bootstrap.
See also https://github.com/etcd-io/etcd/discussions/20446#discussioncomment-14114666
> Remove checking `confState` during schema migration

- cache/demux.go
- cache/ringbuffer.go
- cache/ringbuffer_test.go
#20477 follow-up to move batching into demux to further simplify ringbuffer interface
> cache: move batching to demux so that ringBuffer stores single item

- tests/integration/snapshot/v3_snapshot_test.go
On big endian platforms, skip the TestCorruptedBackupFileCheck test that uses a little endian format file as test input and causes the test to fail for the wrong reason. See earlier discussion here: https://github.com/etcd-io/etcd/issues/11306
I would like to get a fix for this in because this test fails in the newly added https://prow.k8s.io/job-history/gs/kubernetes-ci-logs/logs/ci-etcd-integration-1-cpu-s390x job which runs on the big endian s390x platform.
Closes issue: https://github.com/etcd-io/etcd/issues/20517
> tests: skip TestCorruptedBackupFileCheck test on big endian platforms

- etcdctl/ctlv3/command/options_command.go
- etcdctl/ctlv3/ctl.go
fix: #20466 
before
```
./bin/etcdctl --help       
A simple command line client for etcd3.
Usage:
etcdctl [command]
Key-value commands
compaction  Compacts the event history in etcd
del         Removes the specified key or range of keys [key, range_end)
get         Gets the key or a range of keys
lease       Lease related commands. Use `etcdctl lease --help` to see subcommands
put         Puts the given key into the store
txn         Txn processes all the requests in one transaction
watch       Watches events stream on keys or prefixes
Cluster maintenance commands
alarm       Alarm related commands. Use `etcdctl alarm --help` to see subcommands
defrag      Defragments the storage of the etcd members with given endpoints
downgrade   Downgrade related commands. Use `etcdctl downgrade …
```
> etcdctl: hide global flags

- clientv3/snapshot/v3_snapshot_test.go
Back port of https://github.com/etcd-io/etcd/pull/20525 to release-3.4 branch.
fixes: https://github.com/etcd-io/etcd/issues/20517
> [release-3.4] back port tests: skip TestCorruptedBackupFileCheck test on big endian platforms

- cache/cache.go
- cache/demux.go
- cache/watcher.go
To address the issue #20488
#20491 follow-up: we want to:
- remove early compaction check from `Cache.Watch` (therefore `demux.PeekOldest` is not needed)
- rely on `demux.resyncLaggingWatchers` to handle compacted watchers
- make `watcher` carry cancel response so that `Cache.Watch` goroutine can forward it
> cache: remove early compaction check from Cache.Watch

- tools/mod/go.mod
- tools/mod/go.sum
This pull request completes this week's etcd dependency updates following our [dependency roster](https://docs.google.com/spreadsheets/d/1jodHIO7Dk2VWTs1IRnfMFaRktS9IH8XRyifOnPdSY8I/edit#gid=1394774387) and [dependency management instructions](https://github.com/etcd-io/etcd/blob/main/Documentation/contributor-guide/dependency_management.md).
- https://github.com/etcd-io/etcd/pull/20509
- https://github.com/etcd-io/etcd/pull/20537
> [2025-08-22] Bump dependency updates identified by dependabot

- tests/robustness/coverage/README.md
- tests/robustness/coverage/apiserver-shared-conf/tracing.yaml
- tests/robustness/coverage/kind-with-tracing.yaml
What changed:
* runs Jeager in docker instead of KiND cluster
* uses a separate docker network to make IP address management easier
* provides new configuration of apiserver and kind cluster
* focuses test execution on sig-apps conformance tests to make them faster
Why it changed:
* until Etcd publishes nightly image (or tracing changes are backported/released) it is easier to run `etcd` instance from command line (replacing etcd image in KiND without using external repository is difficult)
* we want to start collecting traces from apiserver to make it easier to attribute calls to contract interface
/cc @serathius
> Start collecting traces from apiserver in robustness/coverage/README.md

- tests/robustness/coverage/README.md
- tests/robustness/coverage/contract_test.go
- tests/robustness/coverage/coverage_test.go
- tests/robustness/coverage/patches/kubernetes/0001-Add-Open-Telemetry-trace-event-when-passing-through-.patch
- tests/robustness/coverage/patches/kubernetes/0002-Add-kubernetesEtcdContractTracker.patch
- tests/robustness/coverage/patches/kubernetes/0003-Add-1m-timeout-to-Watch-to-ensure-Spans-are-exported.patch
- tests/robustness/coverage/patches/kubernetes/0004-Configure-cmd-tests.patch
This approach requires patched kubernetes in order to:
1. Create spans from `Watch` calls. By default `Watch` runs indefinitely, with the patch it is capped at 1 minute
1. Add events to all traces of calls passing through the `Kubernetes` contract interface
1. Create OpenTelemetry spans for all methods of `Kubernetes` contract interface regardless of the information stored in the context (or not)
1. Use the latest `etcd` in both e2e and command tests
/cc @serathius
> Add contract attribution to trace analysis

- tests/robustness/coverage/coverage_test.go
New cases (Watch on compaction key and Range with keys_only) cover new usage of Etcd API by Kubernetes v1.34. Matchers are tighter to better detect future changes (Watch without `prev_kv`).
Optimistic Put and Delete are split. `lease` information is added to the table.
> Update matchers in trace analysis

- .github/workflows/antithesis-test.yml
This is just metadata for Dependabot. The release v0.9 has the same commit as what we were using. Reference: https://github.com/antithesishq/antithesis-trigger-action/releases/tag/v0.9.
> dependency: lock antithesis-trigger-action to v0.9

- tests/framework/e2e/cluster.go
- tests/robustness/README.md
- tests/robustness/coverage/README.md
- tests/robustness/coverage/coverage_test.go
- tests/robustness/scenarios/scenarios.go
Use `TRACING_SERVER_ADDR` environment variable to collect traces when running robustness tests.
/cc @serathius
> Add an option to collect traces from robustness tests

- server/lease/lessor.go
- tests/e2e/v3_lease_no_proxy_test.go
- tests/robustness/Makefile
The lease might have been revoked during renew process (right after previous check). The legacy implementation still returns success. After this PR, it returns `ErrLeaseNotFound`.
I will add an e2e test to reproduce the issue later.
> Re-check that the lease still exists during the renew process

- tests/robustness/traffic/traffic.go
Adds measurement of watch statistics in robustness tests. Introduces `watchStats` and `CalculateWatchStats` that track:
- Number of watch requests
- Number of events
- Progress notifies
- Immediate closures
- Revision coverage
- Average watch duration
Completes part of #20487 to have watch quality metrics, similar to KV traffic stats.
All tests pass locally (`go test ./robustness/traffic`).
> robustness: add watch stats measurement to traffic tests

- build.sh
- server/lease/lessor.go
- tests/e2e/v3_lease_no_proxy_test.go
Backport https://github.com/etcd-io/etcd/pull/20590 to 3.5
> [release-3.5] Re-check that the lease still exists during the renew process

- tests/robustness/traffic/kubernetes.go
`Get` is a `Range` call that should return only one object.
`GetRev` is a `Get` call on a key prefix (`/registry/pods` in this case) without trailing slash `/`. It shouldn't return any key, only revision.
`GetStale` is added for completeness. While possible, it doesn't happen in the current version of e2e/cmd tests.
> Add Get, GetStale, GetRev to Kubernetes robustness tests

- cache/cache.go
- cache/demux.go
- cache/demux_test.go
> cache: change demux.Broadcast to accept clientv3.WatchResponse

- tests/antithesis/server/Dockerfile
- tests/antithesis/test-template/Dockerfile
Reduce the image size of the client and server used in antithesis tests.  Currently each of them is ~2GB.  With this change, each of them takes up less than 100MB.
```
REPOSITORY                                             TAG                                        IMAGE ID       CREATED         SIZE
etcd-client                                            latest                                     6d4d890aa661   5 minutes ago   93MB
etcd-server                                            latest                                     6921ccd8241a   7 minutes ago   39.7MB
```
@serathius
> Reduce the antithesis docker image footprint

- etcdserver/api/v3rpc/maintenance.go
- etcdserver/server.go
- tests/e2e/etcd_process.go
- tests/e2e/reproduce_20271_test.go
backport https://github.com/etcd-io/etcd/pull/20553 to release-3.4 branch
fix https://github.com/etcd-io/etcd/issues/20271
> [release-3.4] protect backend usage from concurrent applySnapshot and defrag

- tools/benchmark/cmd/watch_latency.go
The new version of Go has been optimized, and variables do not need to be reassigned.
> refactor: omit unnecessary reassignment

- tests/antithesis/test-template/robustness/traffic/main.go
- tests/robustness/client/watch.go
- tests/robustness/main_test.go
- tests/robustness/options/options.go
- tests/robustness/traffic/traffic.go
Evolved the [code](https://github.com/serathius/etcd/blob/52673cee64e7da995f4bc700977a88a21a304066/tests/robustness/client/watch.go) from Marek based on the work we did together on Sep. 12, 2025, and based on https://github.com/etcd-io/etcd/pull/20234 and https://github.com/etcd-io/etcd/issues/20221#issuecomment-3013240962 from Marek, we settled on those 2 configuration options for future robustness test use cases.
Parent issue: https://github.com/etcd-io/etcd/issues/20349
> Implement a feature to periodically open watches in robustness test and make it configurable

- tools/mod/go.mod
- tools/mod/tools.go
This missing dependency was caught by the weekly dependency bump from 2025-09-22 (#20703). Even though golang.org/x/tools/cmd/goimports is installed through `tools/mod`, it was never defined in that module.
The `verify-gen-proto` check fails with:
```bash
Running gofast (gogo) proto generation...
% 'pushd' './server/storage/wal/walpb'
/tmp/twd.Y5hm7E/etcd/server/storage/wal/walpb /tmp/twd.Y5hm7E/etcd
% (cd server/storage/wal/walpb && 'protoc' '--gofast_out=plugins=grpc:.' '-I=.:/home/prow/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/..:/home/prow/go/pkg/mod/github.com/gogo/protobuf@v1.3.2/proto/../protobuf:/tmp/twd.Y5hm7E/etcd/..:/home/prow/go/pkg/mod/go.etcd.io/raft/v3@v3.6.0/raftpb/..:/tmp/twd.Y5hm7E/etcd:/tmp/googleapi.QTbHM' …
```
> Add golang.org/x/tools/cmd/goimports tool dependency

- Documentation/dev-guide/apispec/swagger/rpc.swagger.json
- api/etcdserverpb/rpc.pb.go
- api/etcdserverpb/rpc.proto
fix inconsistent function name in comment
> chore: fix inconsistent function name in comment

- pkg/idutil/id.go
6 byte suffix means event window is 2^48, not 2^56.
> idutil: document event window as 2^48

- Documentation/contributor-guide/dependency_management.md
- Documentation/contributor-guide/modules.md
The documentation calls to use `./scripts/fix.sh`, but this script doesn't trigger all the steps that are in the `fix` Makefile target.
Follow up on #20768.
> Update dependency management guide to use make fix
