etcdserver/server.go, etcdserver/server_test.go, rafthttp/peer.go, rafthttp/peer_test.go, rafthttp/transport.go, rafthttp/transport_test.go
=> etcdserver: collect error from errorc

Documentation/2.0/admin_guide.md
=> docs: add doc for server timeout

README.md
=> Fix link to Documentation/2.0 in README

etcdserver/force_cluster.go, test, wal/encoder.go, wal/util.go, wal/util_test.go, wal/wal.go, wal/wal_bench_test.go, wal/wal_test.go
=> add tests and do clean in wal package

pkg/transport/keepalive_listener_test.go, pkg/transport/listener_test.go, pkg/transport/timeout_listener_test.go, pkg/transport/timeout_transport_test.go
=> add tests in pkg/transport package

migrate/cmd/etcd-dump-logs/main.go
=> make `go test ./...` work

etcdmain/config_test.go, etcdmain/http.go
=> etcdmain: add config tests

pkg/pbutil/pbutil_test.go
=> pkg/pbutil: add marshal-related tests

etcdmain/etcd.go, etcdserver/etcdhttp/peer.go, etcdserver/etcdhttp/peer_test.go, integration/cluster_test.go
=> etcdhttp: add NewPeerHandler test

Documentation/2.0/api.md, Documentation/api.md
=> docs: fix send rate usage in api.md

pkg/cors/cors.go, pkg/cors/cors_test.go
=> pkg/cors: add tests

pkg/crc/crc_test.go
=> pkg/crc: add test

integration/cluster_test.go
=> integration: add TestForceNewCluster

etcdserver/etcdhttp/client_test.go, etcdserver/etcdhttp/http_test.go, etcdserver/etcdhttp/peer_test.go, pkg/testutil/testutil.go, pkg/types/set_test.go, pkg/types/slice_test.go, pkg/types/urls.go, pkg/types/urls_test.go
=> add tests in pkg/types package

rafthttp/http.go, rafthttp/streamer.go
=> rafthttp: write StatusOK before start streaming

Documentation/api.md, etcdctl/README.md, etcdctl/command/get_command.go
=> *: remove consistent-get related stuffs

etcdserver/etcdhttp/client.go
=> etcdhttp: add health endpoint

etcdserver/server_test.go, raft/node.go, raft/raft.go, raft/raft_test.go, raft/status.go
Status returns the current status of raft state machine.
=> raft: add Status interface

etcdserver/etcdhttp/client.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go, rafthttp/entry_reader.go, rafthttp/entry_test.go, rafthttp/entry_writer.go, rafthttp/streamer.go
follower:
```
{
"cmdline": ...
"memstats": ...
"rafthttp.stream.bytes_received": {"924e2e83e93f2560": 385},
"rafthttp.stream.entries_received": {"924e2e83e93f2560": 5},
"rafthttp.stream.last_index_received": {"924e2e83e93f2560": 19214}
}
```
leader:
```
{
"cmdline": ...
"memstats": ...
"rafthttp.stream.bytes_sent": {"6e3bd23ae5f1eae0": 1001, "a8266ecf031671f3": 1001},
"rafthttp.stream.entries_sent": {"6e3bd23ae5f1eae0": 13, "a8266ecf031671f3": 13},
"rafthttp.stream.last_index_sent": {"6e3bd23ae5f1eae0": 19222, "a8266ecf031671f3": 19222}
}
```
=> metrics: add /rafthttp/stream metrics

etcdserver/raft.go, raft/node.go, raft/node_bench_test.go, raft/node_test.go, raft/raft.go, raft/raft_paper_test.go, raft/raft_test.go
This PR replaces #2121 and is based on comments there. 
Closes cockroachdb/etcd#6.
@xiang90 @yichengq
=> raft: Add applied index as an argument to newRaft and RestartNode.

server/peer_server.go
@yichengq @philips 
First step:
Members are periodically checking their internal store for changes to the underlying key (/_etcd/internal-version). The master waits 10sec to wait for all members to append the entry and then exit itself.
changes: internal-version -> next-internal-version
=> server: add version monitoring

pkg/ioutil/reader.go, pkg/ioutil/reader_test.go, rafthttp/http.go, test
This helps keep my OCD under control
=> pkg: ioutils -> ioutil

etcdserver/cluster.go, etcdserver/config.go, pkg/netutil/netutil.go, pkg/netutil/netutil_test.go
- To solve validation error problem using URLs in hostname #2123
cc: @barakmich @kelseyhightower
=> Treat URLs have same IP address as same

etcdserver/etcdhttp/client.go, pkg/metrics/metrics.go, pkg/metrics/metrics_test.go
This helps the embedded tests.
=> pkg/metrics: self-manage global expvar map

Documentation/admin_guide.md
=> docs: improve doc for server timeout

raft/raft.go, raft/raft_test.go
This addresses a problem that comes up in the cockroach tests,
in which the order of messages may lead to deadlocks (due to
the fact that we don't have regular heartbeat timers in most
of our tests).
I believe this fixes the test failures we're tracking in cockroachdb/cockroach#285.
=> raft: Send any waiting appends after receiving MsgAppResp.

etcdserver/etcdhttp/client.go, etcdserver/raft.go, etcdserver/server.go
first step towards removing metrics pkg from etcd.
=> etcdserver: remove the dep on metrics. 

pkg/transport/keepalive_listener.go, pkg/transport/keepalive_listener_test.go
Fix #2184  
TLS.Conn does not expose the inner conn. So we have to make a customized listener to change the conn before hand it over to tls.
=> Fix tls keepalive

etcdctl/command/backup_command.go, etcdserver/server.go, wal/wal.go
for #2182 
from #2188, but compare to 201(stable) branch
=> support disaster recovery from rc1 data dir

etcdmain/config.go, main.go, migrate/functional/README.md, migrate/functional/member.go, migrate/functional/upgrade_test.go, migrate/snapshot.go, migrate/starter/starter.go, migrate/starter/tls_info.go, pkg/flags/flag.go
=> migrate: support start desired version

etcdctl/command/member_commands.go
/cc @xiang90 @robszumski @philips
=> etcdctl: give more helpful suggestions on removal

etcdmain/etcd.go, migrate/functional/README.md, migrate/functional/member.go, migrate/functional/upgrade_test.go, migrate/standby.go, migrate/starter/starter.go
=> migrate: support standby mode upgrade

raft/rafttest/network.go, raft/rafttest/node.go
=> rafttest: separate network interface and network

etcdserver/server.go, store/store.go, store/store_test.go
=> fix the problem of StoreKeysPrefix key in store

raft/rafttest/node.go, raft/rafttest/node_test.go
=> rafttest: support node pause

migrate/starter/starter.go
=> migrate/starter: fix --version output

rafthttp/streamer.go
It is not sent out because it is useless to let remote raft step the
message.
Moreover, MsgApp stream reader can always assume that the length
of entries sent is > 0.
fixes #2270
=> rafthttp: not send 0-entry MsgApp using stream

migrate/etcd4.go
=> migrate: fix setting commit index from snapshot

etcdmain/etcd.go, etcdserver/config.go, etcdserver/config_test.go, etcdserver/server.go, etcdserver/storage.go, wal/util.go, wal/util_test.go
Actually having a hook for migrations is useful. We have one, let's use it.
=> etcdserver: Fix migrations

Documentation/libraries-and-tools.md
i add etcd-console tool to tools list for reference
=> add etcd-console tool to tools list

etcdserver/cluster.go, etcdserver/config.go, etcdserver/server.go
=> etcdserver: validate discovery cluster

Documentation/other_apis.md
Signed-off-by: zhangbaitong <zhangbaitong@163.com>
=> docs:small fix

Documentation/docker_guide.md
=> doc: add etcd docker guide

.travis.yml, client/keys_test.go, discovery/discovery_test.go, etcdctl/command/member_commands.go, etcdserver/etcdhttp/client_test.go, etcdserver/etcdhttp/http_test.go, etcdserver/server.go, etcdserver/server_test.go, integration/cluster_test.go, integration/v2_http_kv_test.go, migrate/etcd4.go, migrate/starter/starter.go, raft/log_test.go, raft/node_test.go, raft/raft_paper_test.go, raft/raft_test.go, store/event_test.go, store/heap_test.go, test, wal/wal_test.go
We've been bitten by this enough times that I wrote a tool so that
it never happens again.
=> *: remove shadowing of variables from etcd and add travis test

pkg/wait/wait_time.go, pkg/wait/wait_time_test.go
WaitTime waits on deadline instead of id.
For https://github.com/coreos/etcd/issues/2102
/cc @barakmich @yichengq
=> pkg/wait: add WaitTime

Documentation/proxy.md
=> Documentation fixes for proxy

migrate/starter/starter.go, wal/util.go
=> migrate/starter: fix v2 data dir checking

raft/raft.go
add comments around unreachable.
=> raft: cleanup unreachable

Documentation/clustering.md
Documentation: fix "Missing infra1="
=> Documentation: fix "Missing infra1="

Documentation/implementation-faq.md
Add some notes on the design discussion around the `--initial` flags. If
anything is wrong let me know.
Just wanted to close the loop on our discussion and document the motivations for the initial flags.
/cc @jedsmith @kelseyhightower @xiang90 @yichengq
=> Documentation: add implementation faq

etcdserver/server.go, raft/raft.go, rafthttp/http_test.go, rafthttp/peer.go, rafthttp/pipeline.go, rafthttp/pipeline_test.go, rafthttp/stream.go, rafthttp/transport.go
=> rafthttp: report unreachable status of the peer

etcdserver/server.go, raft/raft.go, rafthttp/http.go, rafthttp/http_test.go, rafthttp/peer.go, rafthttp/pipeline.go, rafthttp/transport.go
=> rafthttp: report MsgSnap status

rafthttp/http.go, rafthttp/http_test.go, rafthttp/peer.go, rafthttp/peer_test.go, rafthttp/pipeline_test.go, rafthttp/stream.go, rafthttp/stream_test.go, rafthttp/transport.go, rafthttp/transport_bench_test.go, rafthttp/transport_test.go, test
compared with master branch.
from #2388
=> rafthttp: add unit tests and SendMsgApp benchmark

rafthttp/peer.go, rafthttp/peer_test.go
=> rafhttp: refactor peer.go

rafthttp/peer.go
/cc @kelseyhightower @barakmich @yichengq
=> rafthttp: add comment for timeout

rafthttp/peer.go
=> rafthttp: kill connection timeout TODO

rafthttp/stream.go, rafthttp/transport.go
/cc @yichengq @kelseyhightower @barakmich
=> Cleanup rafthttp

rafthttp/metrics.go, rafthttp/pipeline.go, rafthttp/stream.go
record message sending latency.
=> rafthttp: add metrics for sending message

raft/doc.go
Includes more details on the required caller behavior and the safety of
membership changes.
Closes #2397
=> raft: Expand doc.go

raft/doc.go, raft/multinode.go
Add ReportSnapshot requirement to doc.go.
=> Add ReportUnreachable and ReportSnapshot to MultiNode.

tools/functional-tester/etcd-tester/main.go, tools/functional-tester/etcd-tester/stresser.go
=> etcd-tester: initial stresser

wal/decoder.go, wal/encoder.go
Fix https://github.com/coreos/etcd/issues/2423
=> wal: do not race reader and writer

raft/log.go, raft/log_unstable.go, raft/logger.go, raft/node.go, raft/raft.go, raft/raft_paper_test.go, raft/rafttest/node.go, raft/status.go, raft/storage.go
@bdarnell
everything is infof for now. will add debug, warning in the near future.
copied a huge amount code from coreos.com/pkg/log 
/cc @bcwaldon
=> raft: introduce logger interface

rafthttp/peer.go, rafthttp/stream.go, rafthttp/stream_test.go
MsgProp process is blocing when there is no leader, which blocks the peer
loop totally.
=> rafthttp: use dedicated go-routine for MsgProp process

wal/wal.go, wal/wal_test.go
ReleaseLockTo should not release the lock on the WAL
segment that is right before the given index. When
restarting etcd, etcd needs to read from the WAL segment
that has a smaller index than the snapshot index.
The correct behavior is that ReleaseLockTo releases
the locks w is holding so that w only holds one lock
that has an index smaller than the given index.
=> wal: fix ReleaseLockTo

raft/raft.go, raft/raft_test.go
=> raft: fall back to bad path when unreachable

Documentation/configuration.md
=> Documentation: make -bind-addr and -peer-bind-addr docs match the code

tools/functional-tester/etcd-agent/agent.go, tools/functional-tester/etcd-agent/client/client.go, tools/functional-tester/etcd-agent/rpc.go, tools/functional-tester/etcd-agent/rpc_test.go
=> tools/functional-tester/etcd-agent: add status rpc

tools/functional-tester/etcd-agent/rpc.go
=> tools/funcational-tester/etcd-agent: log the error for dubgging

Documentation/branch_management.md, README.md
/cc @kelseyhightower @xiang90 @barakmich
=> docs: add branch management

tools/functional-tester/etcd-tester/cluster.go, tools/functional-tester/etcd-tester/tester.go
=> tools/functional-tester/etcd-tester: report agent status

etcdserver/etcdhttp/client_security.go
=> etcdserver/etcdhttp: write the http error to response writer

etcdmain/etcd.go
=> etcdserver: etcd should fall back to proxy again if proxy data is detected

raft/raft.go, raft/raft_snap_test.go, raft/raft_test.go, raft/status.go
=> raft: introduce progress states

raft/design.md
@yichengq @bdarnell 
I am also going to draw the state machine states in ascii when I am patient... 
Add our very first design about the `Progress`. I plan to talk about how we model raft as a pure state machine, the abstraction of tick and the node/multipNode in the future.
=> raft: add our very first design.md

raft/design.md
=> raft: add progress state machine graph

scripts/build-release
fixes #2523 
/cc @kelseyhightower @barakmich
=> scripts: add .exe extension on windows binaries

raft/multinode.go, raft/node.go, raft/node_bench_test.go, raft/node_test.go, raft/raft.go, raft/raft_flow_control_test.go, raft/raft_paper_test.go, raft/raft_snap_test.go, raft/raft_test.go
The first step is to make raft itself configurable, then i will go ahead to make node configurable. 
@bdarnell what is your opinion? 
/cc @yichengq
=> raft: make raft configurable

etcdserver/config.go, etcdserver/config_test.go, etcdserver/server.go
fixes #2396 
/cc @wsimmonds I have reproduced the panic and fixed it through this PR. Could you double-check it?
=> etcdserver: check -initial-cluster in join case

etcdserver/raft.go, raft/example_test.go, raft/node.go, raft/node_test.go, raft/raft.go, raft/raft_test.go
=> raft: make node configurable

etcdserver/server.go, etcdserver/storage.go, test, version/version.go, version/version_test.go, wal/util.go
fixes #2571 
/cc @barakmich @kelseyhightower @xiang90
=> print out extra files in data dir instead of erroring

raft/multinode.go, raft/multinode_test.go, raft/raft_test.go
=> raft: Use raft.Config in MultiNode.

wal/wal.go, wal/wal_test.go
=> wal: releastTo should work with large release index

etcdserver/config.go, etcdserver/config_test.go
=> etcdserver: loose member validation for joining existing cluster

etcdserver/cluster.go, etcdserver/cluster_test.go, etcdserver/server.go, etcdserver/server_test.go, rafthttp/transport.go
=> etcdserver: not apply stale conf change

etcdserver/etcdhttp/client.go, etcdserver/etcdhttp/client_test.go, version/version.go
This reverts commit a77bf97c147a93e5b78898b427d081ba11b8f118.
Conflicts:
version/version.go
=> Revert "etcdhttp: add internalVersion"

server/server.go
/v2/migration/snapshot returns snapshot via http
/v2/migration/snapshot?disk=true saves a snapshot inside local data-dir
/cc @kelseyhightower
=> server: introduce /v2/migration/snapshot endpoint

tools/functional-tester/etcd-agent/agent.go
=> tools/etcd-agent: stop etcd only if it is running when cleanup

Documentation/rfc/api_security.md
Remove lastModified related stuff.
=> doc/rfc: remove unimplemented stuff

etcdserver/etcdhttp/client_security.go
=> etcdserver/etcdhttp: do not return back the password of a user

Godeps/Godeps.json, Godeps/_workspace/src/golang.org/x/net/context/context.go, Godeps/_workspace/src/golang.org/x/net/context/context_test.go
Fix memory leak in context pkg.
=> *: update context pkg

wal/encoder.go
before
```
BenchmarkWrite100EntryWithoutBatch     10000        112254 ns/op         233 B/op          6 allocs/op
BenchmarkWrite100EntryBatch10     200000         11131 ns/op         193 B/op          4 allocs/op
BenchmarkWrite100EntryBatch100    500000          3557 ns/op         192 B/op          4 allocs/op
BenchmarkWrite100EntryBatch500   1000000          1823 ns/op         192 B/op          4 allocs/op
BenchmarkWrite100EntryBatch1000  1000000          1750 ns/op         192 B/op          4 allocs/op
BenchmarkWrite1000EntryWithoutBatch    10000        114098 ns/op        1121 B/op          6 allocs/op
BenchmarkWrite1000EntryBatch10    100000         19193 ns/op        1108 B/op          4 allocs/op
BenchmarkWrite1000EntryBatch100   200000          8259 ns/op        1108 B/op …
```
=> wal: reduce allocation when encoding int64

integration/cluster_test.go
=> integration: add TestTLSClusterUsingDiscovery and TestDoubleTLSCluster

Documentation/backward_compatibility.md
=> docs: fix broken link for migration tool

client/keys.go, client/keys_test.go
/cc @bcwaldon @kelseyhightower @barakmich 
Prepare for porting to etcdctl.
=> client: add dir/ttl fields into node

etcdctl/command/import_snap_command.go
```
./etcdctl import -snap migrate.snap -hidden _coreos.com
starting to import snapshot migrate.snap with 10 clients
2015/04/07 12:46:07 entering dir: /
2015/04/07 12:46:07 entering dir: /_coreos.com
2015/04/07 12:46:07 copying key: /_coreos.com/foo
finished importing 1 keys
```
=> etcdctl: import hidden keys

wal/wal.go
SaveSnap and Save are called in separate goroutines now. Allow at most
one WAL function being called at one time to protect internal fields and
guarantee execution order.
Or one possible bug is that the new cut file is started with snapshot
entry instead of crc entry.
/cc @barakmich
=> wal: allow at most one WAL function called at one time

etcdctl/command/backup_command.go
fix part one of https://github.com/coreos/etcd/issues/2664
=> etcdctl: backup tool should use the new layout

Documentation/backward_compatibility.md
Add thorough notes on both the data directory migration and the snapshot
migration options.
=> Documentation: add migration notes to backward compatibility

Documentation/backward_compatibility.md
These won't get picked up by our docs sidebar if they aren't an h2 or h3
=> docs: size up all headers by 2

etcdserver/etcdhttp/client.go, etcdserver/etcdhttp/client_test.go, etcdserver/etcdhttp/peer.go, version/version.go
Returns version on peer url too.
=> *: serve json version on both client and peer url

Documentation/security_api.md, etcdserver/etcdhttp/client.go, etcdserver/etcdhttp/client_security.go, etcdserver/etcdhttp/http.go, etcdserver/security/security.go, etcdserver/security/security_requests.go, etcdserver/security/security_test.go, integration/v2_http_kv_test.go
Still working on some of the client improvements, but here's the PR for fixing the list on #2384 
Notably, prefixes are simplified, enabling security is separate from a root user, there's a root role, there's guest access, and obviates some of the "is security enabled" bugs in the decoupling.
=> security: Update security

pkg/fileutil/lock_solaris.go
=> pkg/fileutil: add filelock support for solaris

integration/cluster_test.go
=> integration: add tests around the membership change issues

integration/cluster_test.go
A extreme membership change case is a full cluster rotation. We add a test case for it.
=> integration: add a test case for a full cluster rotation

Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/README.md, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/example/hello_dolly.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/formatters.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/glog_formatter.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/log_hijack.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/logmap.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/pkg_logger.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/syslog_formatter.go, etcdmain/config.go, etcdmain/etcd.go, etcdmain/http.go
The first step in #2398 is to use the new logger I wrote.
Fortunately, it wraps log. So it's trivial to get started -- this is the minimal change (with new flags available for detailed logging in the future) in order to start fixing the log situation.
=> etcdmain: New logger

etcdmain/etcd.go, etcdserver/cluster.go, etcdserver/cluster_util.go, etcdserver/etcdhttp/peer.go, etcdserver/etcdhttp/peer_test.go, etcdserver/server.go, etcdserver/server_test.go, integration/cluster_test.go, rafthttp/peer.go, rafthttp/remote.go, rafthttp/transport.go
=> backport #2701 to release-2.0 branch

tools/functional-tester/etcd-agent/main.go, tools/functional-tester/etcd-tester/main.go
Help users to understand what these flags are for.
=> tools/functional-testing: add help message for flags

proxy/reverse.go
established connections were leaked when client disconnected before proxyreq
completes. This happens all time for wait=true requests.
=> Fix connection leak when client disconnected

build, etcdmain/config.go, version/version.go
added more version information output to aid debugging
Fixes #2560
=> version: added more version information

Documentation/libraries-and-tools.md
etseed is an R client for etcd
=> Documentation: add the R client etseed to libraries-and-tools.md

rafthttp/stream.go
name 'close' is shorter and more straightforward.
for https://github.com/coreos/etcd/pull/2782#discussion_r30384197
=> rafthttp: resetCloser -> close

Documentation/security_api.md, etcdserver/security/security.go, etcdserver/security/security_requests.go, etcdserver/security/security_test.go, integration/v2_http_kv_test.go
May find new instances for #2741
=> security: Lazily create the security directories. Fixes #2755.

Documentation/libraries-and-tools.md
Metafora uses etcd as a task broker, command channel, and state store.
=> docs: mention metafora distributed task library

etcdserver/cluster.go, etcdserver/etcdhttp/http_test.go, etcdserver/member.go, etcdserver/server.go
=> etcdserver: refactore member.go

etcdmain/etcd.go
Indirectly addresses https://github.com/coreos/etcd/issues/2794.
=> etcdmain: explicitly set gomaxprocs and log its value

Documentation/clustering.md
reviewed this with Yicheng Qin who thinks its good
=> docs: add client flags to examples in clustering.md

proxy/reverse.go
=> Reuse a bytes buffer as proxy request body.

wal/util.go, wal/wal.go
=> wal: use leveled logger

snap/snapshotter.go, wal/util.go, wal/wal.go
=> *: rename logger to plog

rafthttp/pipeline.go, rafthttp/pipeline_test.go
This PR makes pipeline.stop stop quickly. It cancels inflight requests,
and stops sending messages in the buffer.
fixes #2888 
I have manually tested the case that is described, and it has been fixed.
@tj-corrigan Give this branch a try if you have time?
=> rafthttp: fix pipeline.stop may block

etcdctl/command/cluster_health.go, etcdctl/command/error.go, etcdctl/command/format.go, etcdctl/command/get_command.go, etcdctl/command/handle.go, etcdctl/command/import_snap_command.go, etcdctl/command/mk_command.go, etcdctl/command/mkdir_command.go, etcdctl/command/rm_command.go, etcdctl/command/rmdir_command.go, etcdctl/command/set_command.go, etcdctl/command/util.go, etcdctl/command/watch_command.go
=> etcdctl: cleanup 

storage/backend/batch_tx.go, storage/index.go, storage/index_test.go, storage/key_index.go, storage/key_index_test.go, storage/kv.go, storage/kvstore.go, storage/kvstore_compaction.go, storage/kvstore_test.go, storage/reversion.go
1. refactor key-index to support reversion (main, sub)
2. initial compaction support
=> Storage initial compaction

client/client.go, client/client_test.go
Fix https://github.com/coreos/etcd/issues/2669
=> client: fix cancel watch

Documentation/admin_guide.md
=> docs: document cpu cores deployment

etcdserver/etcdhttp/client.go, etcdserver/etcdhttp/client_security.go, etcdserver/etcdhttp/http.go, etcdserver/etcdhttp/peer.go
make etcdhttp use leveled logging.
the next step is to add debugging level log for incoming http requests.
=> etcdhttp: use leveled logging

etcdserver/etcdhttp/client.go, etcdserver/etcdhttp/http.go
=> Simple debug HTTP request logging

etcdserver/cluster.go, etcdserver/cluster_util.go, etcdserver/config.go, etcdserver/member.go, etcdserver/metrics.go, etcdserver/raft.go, etcdserver/server.go, etcdserver/server_test.go, etcdserver/storage.go
Leveled logging for etcdserver pkg.
=> etcdserver: use leveled logging

rafthttp/http.go, rafthttp/peer.go, rafthttp/pipeline.go, rafthttp/remote.go, rafthttp/stream.go, rafthttp/transport.go
=> rafthttp: use leveled logger

test
=> test: run with cpu = 1,2,4

proxy/director_test.go
fix test by sorting the string slice before comparison.
=> proxy: fix test

discovery/discovery.go, discovery/srv.go, etcdserver/etcdhttp/httptypes/errors.go, etcdserver/security/security.go, etcdserver/security/security_requests.go, etcdserver/stats/leader.go, etcdserver/stats/stats.go, pkg/flags/flag.go, pkg/flags/urls.go, pkg/netutil/netutil.go, pkg/osutil/interrupt_unix.go, pkg/osutil/osutil.go, pkg/pbutil/pbutil.go, wal/repair.go
Only a few things left. Let us change them together in one pull request.
Fix #2707
=> all pkgs use leveled log

etcdmain/config.go, etcdmain/etcd.go
So the variable name doesn't mess up with standard package name.
=> etcdmain: var log -> plog

Documentation/libraries-and-tools.md
I've been working on this project for a few weeks and I believe it has some features that could assist maintaining etcd registries. Please check it out and I hope you would like to include it in your list of etcd tools.
I will upload a couple of screenshots ASAP...
Kind regards,
Nikos
=> docs: add etcd-viewer into libraries-and-tools.md

raft/doc.go
We recently added a config struct to start raft. Update
our doc accordingly.
Fix #2971 
/cc @cespare
=> raft: fix usage section of doc

Documentation/auth_api.md, client/auth_role.go, client/auth_user.go, etcdctl/command/auth_commands.go, etcdctl/command/role_commands.go, etcdctl/command/user_commands.go, etcdctl/main.go, etcdserver/auth/auth.go, etcdserver/auth/auth_requests.go, etcdserver/auth/auth_test.go, etcdserver/etcdhttp/capability.go, etcdserver/etcdhttp/client.go, etcdserver/etcdhttp/client_auth.go, etcdserver/etcdhttp/http.go
"Security" ought to refer to SSL.
=> *: Rename `security` to `auth`

Documentation/glossary.md, Documentation/metrics.md
=> doc: add doc for metrics feature

Documentation/auth_api.md
This is the first thing user needs to do. So let's make it to the top.
=> doc: move enable section to the top in auth_api.md

Documentation/auth_api.md
1. Last modified is removed
2. explain the error more explicitly
=> auth: minor fix for user section

etcdserver/etcdhttp/client_auth.go
Fix https://github.com/coreos/etcd/issues/3016
=> etcdhttp: fix the response type for auth

etcdserver/auth/auth.go, etcdserver/auth/auth_test.go, etcdserver/etcdhttp/http.go
auth error should not always be HTTP.StatusBadRequest.
Fix #3017
=> etcdserver: use correct http status code for auth error

etcdserver/auth/auth.go
Fix #3019
```
curl http://127.0.0.1:2379/v2/auth/users/fleet -XPUT -d '{"user":"fleet", "grant": ["fleet"]}' 
{"message":"auth: granting duplicate role fleet for user fleet"}
```
=> auth: do not allow to grant duplicate role or revoke ungranted role 

Documentation/auth_api.md
Please take a look.
/cc @barakmich @yichengq
=> doc: update auth_api.md

client/client_test.go
This fixes the bug that the test may hang forever.
fixes #2449 
/cc @bcwaldon
=> client: fix TestSimpleHTTPClientDoCancelContextResponseBodyClosed

rafthttp/transport.go, rafthttp/transport_test.go
Update term when AddPeer, or the term in peer will not be updated until
the term is changed. This fixes the log flood happended when the v2.1
follower applies the snapshot from v2.0 leader:
```
rafthttp: cannot attach out of data stream server [0 / 17]
```
or
```
rafthttp: server streaming to 6e3bd23ae5f1eae0 at term 0 has been
stopped
```
for missed problem in #2793
=> rafthttp: update term when AddPeer

etcdserver/auth/auth.go, etcdserver/etcdhttp/client_auth.go
Giving both roles and grant/revoke is not allowed.
Creating an existing user is not allowed.
Updating a non-existing user is not allowed.
=> etcdhttp: improve user endpoint validation

etcdserver/auth/auth.go
we should not allow to update root role.
=> auth: do not allow update root role

Documentation/auth_api.md
1. update status code
2. add an example for modifying guest role
=> auth: update the auth doc

discovery/discovery.go
Add keepalive and headertimeout for discovery client.
=> discovery: add timeouts for discovery client

etcdserver/metrics.go, snap/metrics.go
Fix two minor issues. See commits.
=> refactor metrics

Documentation/configuration.md
Re-opened #2997 under my fork.
=> Documentation: Refer back between name and initial-cluster options

Documentation/benchmarks/etcd-2-1-0-benchmarks.md
=> docs/benchmarks: doc benchmark tool

storage/index.go, storage/index_test.go, storage/key_index.go, storage/key_index_test.go, storage/kvstore.go, storage/reversion.go
Save created and modified index. Made some necessary changes to the index system.
=> storage: save created index and modified index

Documentation/metrics.md
=> docs: doc metrics used in rafthttp package

storage/index.go, storage/index_test.go, storage/key_index.go, storage/key_index_test.go, storage/kvstore.go, storage/kvstore_test.go
=> storage: save version

Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/example/hello_dolly.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/formatters.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/glog_formatter.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/log_hijack.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/logmap.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/pkg_logger.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/syslog_formatter.go
It fixes windows building problem.
=> Godeps/capnslog: bump to 99f6e6b8f8ea30b0f82769c1411691c44a66d015

etcdserver/etcdserverpb/etcdserver.pb.go, etcdserver/etcdserverpb/etcdserver.proto, raft/raftpb/raft.pb.go, raft/raftpb/raft.proto, snap/snappb/snap.pb.go, snap/snappb/snap.proto, storage/storagepb/kv.pb.go, storage/storagepb/kv.proto, wal/walpb/record.pb.go, wal/walpb/record.proto
no real changes. just add proto2/proto3 syntax and regenerate go code.
=> *: resolve proto warnings

storage/kvstore.go
Add few small fixes for storage.
=> storage: fix small issues

client/members.go, client/members_test.go, etcdctl/command/member_commands.go
=> Member update

integration/v2_http_kv_test.go
=> integration: always check error for function calls

Documentation/upgrade_2_1.md
rolling upgrade doc for 2.1 release.
Fix #3004
=> doc: add rolling upgrade doc for 2.1

etcdmain/etcd.go
Fix https://github.com/coreos/etcd/issues/3108
=> etcdmain: proxy ignores discovery if it is initialized

etcdctl/README.md, etcdctl/command/util.go, etcdctl/main.go
provided a domain, will look up SRV records for etcd endpoints
Fixes #2636
=> etcdctl: added domain discovery flag

Documentation/proxy.md
=> docs: fix wrong proxy command

README.md
=> Update contact section in README.md

Documentation/api.md
follows from #2777 
I added the correct watch command, and changed some sentences to make it more readable.
I also ran the example and correct the commands.
/cc @xiang90 @robszumski @schmichael @ravigadde
=> docs: update watch API doc for clarity

client/keys.go, client/keys_test.go
=> client: add Quorum option in getOption

Documentation/reporting_bugs.md, README.md
For #3161 and already reviewed.
Fix #911.
=> doc: add reporting bug doc

Documentation/rfc/v3api.md, Documentation/rfc/v3api.proto, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto, storage/backend/backend.go, storage/backend/batch_tx.go, storage/kv.go, storage/kvstore.go, storage/kvstore_test.go
Transaction should be tx or txn, but not tnx.
=> *: tnx -> txn

etcdctl/command/cluster_health.go
This method uses raft status exposed at /debug/varz to determine the
health of the cluster. It uses whether commit index increases to
determine the cluster health, and uses whether match index increases to
determine the member health.
This could fix the bug that fails to detect follower is unhealthy
because it doesn't rely on whether message in long-polling connection is sent.
This health check is stricter than the old one, and reflects the
situation that whether followers are healthy in the view of the leader. One
example is that if the follower is receiving the snapshot, it will turns
out to be unhealthy because it doesn't move forward.
This will reflect the healthy view in the raft level, while connectivity checks reflects the healthy view in transport level.
This is a prototype, and I …
=> etcdctl: refactor the way to check cluster health

etcdserver/auth/auth.go, etcdserver/auth/auth_requests.go, etcdserver/auth/auth_test.go, etcdserver/etcdhttp/client.go, etcdserver/etcdhttp/client_auth.go, etcdserver/etcdhttp/client_auth_test.go
=> etcdhttp: Improve test coverage surrounding auth

Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/go-systemd/daemon/sdnotify.go, Godeps/_workspace/src/github.com/coreos/go-systemd/util/util.go, etcdmain/etcd.go
Fix #2724 
/cc @crawford @eyakubovich
=> etcdmain: support sdnotify for readiness

build.bat
Ported your bash [build](https://github.com/offscale/etcd/blob/master/build) to Windows Batch.
=> build: implemented build shell-script for Windows

Documentation/clustering.md
=> doc: unique names must be specified when using public discovery service

etcdctl/command/ls_command.go
=> etcdctl: ls takes / as default key arg

client/client.go, client/client_test.go
KeepSync provides the way for client to keep syncing member list from
etcd cluster. Current implementation syncs member list every sync
interval.
fixes #2255
=> client: add KeepSync function

pkg/fileutil/perallocate_unsupported.go, pkg/fileutil/preallocate.go, pkg/fileutil/preallocate_test.go, wal/wal.go
Fix https://github.com/coreos/etcd/issues/2336
=> pkg/fileutil: support perallocate

client/client.go, client/client_test.go
=> client: return context.Canceled error when user cancels the request

Documentation/admin_guide.md
docs/admin_guide: update migration example on CoreOS …
It points out that the example workflow is on CoreOS, and updates the
command to match the case.
docs/admin_guide: decouple recovery from CoreOS specific path …
This makes the example commands general, while keeping it easy to
understand.
It is updated based on user feedback. /cc @kayrus
=> update commands used in admin_guide.md

etcdserver/raft.go
The behavior accelarates the happen of the first-time leader election,
so the new cluster could elect its leader fast. Technically, it could
help to reduce `electionMs` wait time for the first leader election.
Main usage:
1. Quick start for the local cluster when setting a little longer
election timeout
2. Quick start for the global cluster, which sets election timeout to
its maximum 50s.
for #964
=> etcdserver: tick ElectionTicks before starting when bootstrap new cluster

etcdmain/etcd.go
=> etcdmain: fix path printing

client/client.go, client/client_test.go
This helps client to pin the same endpoint as long as cluster doesn't change.
for #2254
=> client: Sync() pin the endpoint when member list doesn't change

Documentation/rfc/v3api.proto, etcdctl/command/import_snap_command.go, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto, etcdserver/server_test.go, raft/raft_flow_control_test.go, rafthttp/transport.go
Fix https://github.com/coreos/etcd/issues/3232
=> *: fix typos vaild->valid

Documentation/runtime-configuration.md, Documentation/runtime-reconf-design.md
Fix https://github.com/coreos/etcd/issues/3014
=> doc: add runtime reconfiguration design doc

client/client.go, client/client_test.go
Add Timeout field in Config, so users could set timeout for each request.
Before this, one hanged request may block the call for long time. After
this, if the network is good, the user could set short timeout and expect
that API call can attempt next available endpoint quickly.
from #2850  I borrow a lot of code of the original PR.
=> client: set timeout for each request

client/README.md
It describes some basic usage and caveat of etcd/client package.
/cc @bcwaldon
=> client: add README

client/README.md
Address rob's comments about sentences in README.
It is much cleaner now! Thanks @robszumski 
from #3194 
/cc @robszumski @xiang90
=> client: clean up README

raft/log.go, raft/log_test.go, raft/log_unstable.go, raft/log_unstable_test.go, raft/raft.go, raft/raft_test.go
groupID will be provided here and the actual log will be done in cockroach/multiraft/raft.go.
=> set groupID in multinode as log context so it can be logged

client/client.go, etcdctl/command/error.go, etcdctl/command/util.go
Fix https://github.com/coreos/etcd/issues/3264
=> Better error message for etcdctl

hack/kubernetes-deploy/README.md, hack/kubernetes-deploy/etcd.yml, hack/kubernetes-deploy/vulcand.yml
=> add etcd on k8s example

Documentation/clustering.md, Documentation/discovery_protocol.md
This document talks about the technical details of discovery service
protocol. It helps users to learn about how discovery service works and
what behavior to expect.
fixes https://github.com/coreos/etcd/issues/2095
=> docs: add discovery protocol doc

Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/init.go, Godeps/_workspace/src/github.com/coreos/pkg/capnslog/init_windows.go
=> godeps: bump capnslog to 42a8c3b1a6f917bb8346ef738f32712a7ca0ede7

etcdserver/cluster_util.go
Fix https://github.com/coreos/etcd/issues/3288
=> etcdserver: better version detection log output

etcdserver/etcdhttp/client.go, etcdserver/etcdhttp/client_test.go
Fix https://github.com/coreos/etcd/issues/3235
=> etcdhttp:write etcderror for all errors in keyhandler

Documentation/configuration.md, etcdmain/help.go
so people could deprecate old flags and use new flags much easier.
/cc @crawford @robszumski
=> etcdmain: update -ca-file description

client/keys.go
=> client: fixed typo in WatcherOptions docs

Documentation/tuning.md
It gives more details about how to set heartbeat interval and election
timeout correctly based on RTT.
fixes #3312 
/cc @robszumski
=> docs: document how to set heartbeat interval and election timeout

etcdctl/command/cluster_health.go
Make cluster health checking more reliable and simple
=> etcdctl: use health endpoint to greatly simplify health checking

Documentation/benchmarks/etcd-2-2-benchmarks.md, hack/benchmark/README.md, hack/benchmark/bench.sh
It also includes the script to run the benchmark.
for #3290
=> docs/benchmarks: add benchmark result for 2.2

storage/index.go, storage/index_test.go, storage/key_index.go, storage/key_index_test.go, storage/kvstore.go, storage/kvstore_compaction.go, storage/kvstore_test.go, storage/revision.go, storage/revision_test.go
I think this is a typo.  Reversion is a return to a previous state, revision is a mutation.
=> Reversion->Revision

pkg/fileutil/perallocate_unsupported.go, pkg/fileutil/preallocate.go
Fix https://github.com/coreos/etcd/issues/3335
=> pkg/fileutil: treat not support error as nil error in preallocate

etcdserver/auth/auth.go, etcdserver/auth/auth_requests.go, etcdserver/auth/auth_test.go
=> etcdserver/auth: cache auth enable result

etcdserver/cluster.go, etcdserver/config.go, pkg/netutil/netutil.go, pkg/netutil/netutil_test.go
fixes #3350 
It reverts the commit to fix #2815 , so I fix #2815 with another method.
=> fix that etcd fails to start if using both IP and hostname when discovery srv

.travis.yml, client/keys_test.go
go1.5 is available. Let's test it.
=> travis: test for go 1.5 build

etcdctl/command/cluster_health.go
=> etcdctl/cluster_health: set health var when checked healthy

Documentation/rfc/v3api.proto, etcdserver/etcdserverpb/rpc.proto, storage/storagepb/kv.proto
We still need to update the watch and lease related stuff. But it would be after 2.2.
=> update v3 proto and doc

Documentation/benchmarks/etcd-3-0-demo-benchmarks.md, tools/v3benchmark/main.go, tools/v3benchmark/report.go
It includes the initial read benchmark for etcd v3.
This is the first step to give some rough thoughts. I haven't digged
deeper to answer some questions, including why its performance is not
better than HTTP + json, why one put will cause performance downgrade.
for #3290
=> *: add initial read benchmark for etcd v3

Godeps/Godeps.json, Godeps/_workspace/src/github.com/boltdb/bolt/.gitignore, Godeps/_workspace/src/github.com/boltdb/bolt/README.md, Godeps/_workspace/src/github.com/boltdb/bolt/batch.go, Godeps/_workspace/src/github.com/boltdb/bolt/bolt_unix.go, Godeps/_workspace/src/github.com/boltdb/bolt/bolt_windows.go, Godeps/_workspace/src/github.com/boltdb/bolt/bucket_test.go, Godeps/_workspace/src/github.com/boltdb/bolt/cmd/bolt/main.go, Godeps/_workspace/src/github.com/boltdb/bolt/db.go, Godeps/_workspace/src/github.com/boltdb/bolt/db_test.go, Godeps/_workspace/src/github.com/boltdb/bolt/errors.go, Godeps/_workspace/src/github.com/boltdb/bolt/freelist.go, Godeps/_workspace/src/github.com/boltdb/bolt/freelist_test.go, Godeps/_workspace/src/github.com/boltdb/bolt/node.go, Godeps/_workspace/src/github.com/boltdb/bolt/page.go, Godeps/_workspace/src/github.com/boltdb/bolt/page_test.go, Godeps/_workspace/src/github.com/boltdb/bolt/tx.go, Godeps/_workspace/src/github.com/boltdb/bolt/tx_test.go, storage/backend/backend.go, storage/backend/batch_tx.go
Fix #3353
related commit for the fix https://github.com/boltdb/bolt/commit/e929eba364732aa3a7eb76e2c9c38b7d23b8a980
=> Godeps: update bolt dependency

Documentation/configuration.md
=> doc: add evn variable name to configuration.md

storage/index.go, storage/index_test.go, storage/key_index.go, storage/key_index_test.go, storage/kv_test.go, storage/kvstore_compaction_test.go, storage/kvstore_test.go
for #3306 
The coverage reaches 90%
=> add unit tests for storage

Documentation/faq.md
=> add faq documentation

pkg/cors/cors_test.go, raft/rafttest/network_test.go, storage/backend/backend_test.go
Replacing #3365 A bunch of tests were failing, which was making my automatic cross-compiling a pain. This is a series of atomic fixes to clean them up.
=> Test Fixes: Take 2

pkg/flags/flag.go
Fix #3319 
Case 1: unrecognized and used env
```
ETCD_NAME=good ./etcd
2015-08-27 12:10:45.438503 I | flags: recognized and used environment variable ETCD_NAME=good
...
```
Case 2: unrecognized but shadowed by flag
```
ETCD_NAME=bad ./etcd -name=good
2015-08-27 12:09:00.832892 I | flags: recognized environment variable ETCD_NAME, but unused: shadowed by corresponding flag 
...
```
Case 3: unrecognized 
```
ETCD_BAD=bad ./etcd
2015-08-27 12:11:07.695042 W | flags: unrecognized environment variable ETCD_BAD=bad
...
```
=> pkg/flags: print out evn usage information

etcdserver/auth/auth.go, etcdserver/cluster.go, etcdserver/cluster_util.go, integration/cluster_test.go, pkg/fileutil/fileutil_test.go, pkg/fileutil/purge_test.go, pkg/transport/listener_test.go, pkg/transport/timeout_listener_test.go, raft/multinode.go, snap/snapshotter_test.go, test
Use official support instead of home-made one.
/cc @barakmich
=> test: use go vet shadow feature instead of go-nyet

Documentation/benchmarks/etcd-2-2-benchmarks.md
This benchmark is for etcd 2.2 rc after fixing several performance
downgrade bugs.
=> docs/benchmark: update etcd 2.2 bench

Documentation/api.md
linked to section in the file, but now is a separate file
=> fix docs, change tuning link in api.md from section to file

raft/multinode.go, raft/multinode_test.go
@xiang90 @yichengq 
CC @mrtracy
=> raft: Fix a nil-pointer panic in MultiNode.Propose.

storage/key_index.go, storage/metrics.go
Fix https://github.com/coreos/etcd/issues/687
=> more on storage metrics

Documentation/04_to_2_snapshot_migration.md, README.md
=> doc: add 0.4.9 to 2.2 migration guide

raft/multinode_test.go, raft/raft.go
Fixes another panic in MultiNode.Propose.
@xiang90 @yichengq @mrtracy
=> raft: A removed node can no longer be leader.

etcdserver/cluster_util.go
It sets no timeout for public GetClusterFromRemotePeers.
This helps the following cases to work well in high latency scenario:
1. proxy sync members from the cluster
2. newly-joined member sync members from the cluster
After removing request timeout, the request is still controlled by dial
timeout and read connection timeout, which is 5s. This avoids
unreasonably long wait.
fixes #3215
=> etcdserver: add timeout param on getClusterFromRemotePeers

etcdmain/etcd.go
=> etcdmain: proxy does not need to belong to the discovered cluster

Godeps/_workspace/src/github.com/boltdb/bolt/bolt_unix_solaris.go
Changed the commit message as requested
=> Godeps: boltdb dependency missing solaris support

build
@xiang90 I tried to fix the issue#3417, I think this would also work with Go1.5. Would you like to have a look?
=> build: fix build error on ubuntu

storage/backend/backend.go, storage/backend/backend_test.go, storage/backend/batch_tx.go, storage/backend/batch_tx_test.go, test
=> storage/backend: add unit tests for backend and batchTx

Documentation/upgrade_2_2.md
Fix https://github.com/coreos/etcd/issues/3400
=> doc: add upgrade to 2.2 doc

storage/kvstore.go, storage/kvstore_compaction.go, storage/kvstore_test.go
=> storage: add mock tests for store struct

Documentation/rfc/v3api.md, Documentation/rfc/v3api.proto, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto, etcdserver/v3demo_server.go, storage/kv_test.go, storage/kvstore.go, storage/kvstore_test.go, storage/storagepb/kv.pb.go, storage/storagepb/kv.proto
Make the naming consistent in store and its proto API.
=> *: v3api index->revision

etcdctl/command/cluster_health.go
We made a mistake on the health endpoint by returning a string "true".
We have to make the etcdctl works for the next version of etcd which
will correct the mistake on the server side.
It is too late to change the server side right now since we already
released a version of etcdctl that only understands "true".
=> etcdctl: prepare for health endpoint change

test
=> test: now raft has no shadow issue

Documentation/admin_guide.md
=> doc: add monitoring section to admin doc

etcdserver/v3demo_server.go
=> etcdserver: refactor v3demo do

etcdctlv3/command/txn_command.go
=> etcdctlv3: fix txn command

Documentation/upgrade_2_2.md
We have improved our snapshot mechanism. This limitation has been solved.
=> doc: remove one limitation in upgrade doc

ROADMAP.md
=> roadmap: remove 2.2 section

etcdmain/etcd.go
etcdmain: Proxy doesnt specify - listening on http or https
Fixes #3464
=> etcdmain: Proxy doesnt specify - listening on http or https

Documentation/runtime-configuration.md
/cc @robszumski @yichengq 
typo fixed
=> doc: member id typo fixed

ROADMAP.md
=> roadmap.md: update roadmap for 2.3

Documentation/libraries-and-tools.md
libraries-and-tools.md: add etcddir
=> libraries-and-tools.md: add etcddir

etcdctlv3/command/delete_range_command.go, etcdctlv3/command/put_command.go, etcdctlv3/command/range_command.go, etcdctlv3/command/txn_command.go, etcdctlv3/main.go
etcdctlv3 should support endpoint flag to prepare for support v3 api cluster.
=> etcdctlv3: support endpoint flag

README.md
More accessible, better scaling.
=> readme: Use SVG image for build status badge

Documentation/tuning.md
- Use one sentence per line for easier diffing
- Walkthrough the thought process and cleanup the grammar
- Move below the other sections
Original author: @philips
inherited from #3189 
/cc @philips
=> Documentation/tuning: cleanup paragraph on max election

raft/log.go
Give a human being some insight into how we might have gotten to this
state based on feedback from #3504.
=> raft: improve panic error message

etcdserver/api/v3rpc/key.go, etcdserver/etcdserverpb/raft_internal.pb.go, etcdserver/etcdserverpb/raft_internal.proto, etcdserver/server.go, etcdserver/v3demo_server.go
After this pull request, request through v3 api can get committed and applied across the cluster.
We still need to
1. fix the v3 snapshot, it should be able to replicate through the cluster
2. make readonly request remains to be applied locally
=> support clustered v3 api

etcdserver/api/v3rpc/error.go, etcdserver/api/v3rpc/key.go, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto
This is the first step towards using gRPC error.
We will make the error message better and do more validation over time.
/cc @yichengq @ecnahc515
=> etcdserver: use gRPC error instead of error message in header

etcdctlv3/command/compaction.go, etcdctlv3/main.go, etcdserver/api/v3rpc/key.go, etcdserver/etcdserverpb/raft_internal.pb.go, etcdserver/etcdserverpb/raft_internal.proto, etcdserver/v3demo_server.go
Add support for storage compaction
=> *: support v3 compaction

etcdserver/config.go, etcdserver/server.go
and rename it to a formal name
follow https://github.com/coreos/etcd/pull/3526#issuecomment-140277647
=> etcdserver: rename db file into a formal directory

tools/v3benchmark/get.go, tools/v3benchmark/main.go
=> benchmarkv3: refactoring the main logic

Godeps/_workspace/src/github.com/cheggaaa/pb/.travis.yml, Godeps/_workspace/src/github.com/cheggaaa/pb/LICENSE, Godeps/_workspace/src/github.com/cheggaaa/pb/README.md, Godeps/_workspace/src/github.com/cheggaaa/pb/example/copy/copy.go, Godeps/_workspace/src/github.com/cheggaaa/pb/example/pb.go, Godeps/_workspace/src/github.com/cheggaaa/pb/format.go, Godeps/_workspace/src/github.com/cheggaaa/pb/format_test.go, Godeps/_workspace/src/github.com/cheggaaa/pb/pb.go, Godeps/_workspace/src/github.com/cheggaaa/pb/pb_nix.go, Godeps/_workspace/src/github.com/cheggaaa/pb/pb_solaris.go, Godeps/_workspace/src/github.com/cheggaaa/pb/pb_test.go, Godeps/_workspace/src/github.com/cheggaaa/pb/pb_win.go, Godeps/_workspace/src/github.com/cheggaaa/pb/pb_x.go, Godeps/_workspace/src/github.com/cheggaaa/pb/reader.go
Both previous folked version of pb and this version of pb are ignored by default gitignore file.
I have no reason why. They matches the rule `*.com`
=> Godep: add cheggaaa dependency

proxy/proxy.go, proxy/proxy_test.go
This is a readonly feature for now. We will see the requirement from community to decide to make this also writable.
=> proxy: expose proxy configuration

Documentation/auth_api.md, etcdserver/etcdhttp/client_auth.go, etcdserver/etcdhttp/client_auth_test.go
allow recursive query on users and roles to get more detail
Fixes #3278
=> etcdserver: extend auth api

Documentation/libraries-and-tools.md
Submit new pull req. messed up last fork.
=> docs/libraries-and-tools: add etcd-export tool

etcdmain/etcd.go
etcd should exit after printing log for unhandlable error.
=> etcdmain: exit after print out ErrDuplicateID

etcdserver/etcdhttp/client.go, etcdserver/etcdhttp/client_test.go
=> etcdhttp: add Content-Type: application/json header to version handler

etcdserver/server.go
To load the previous data.
for #3549
=> etcdserver: restore v3 storage when restart

pkg/transport/timeout_dialer_test.go
Accessing test.T async will cause data race.
Change to use select to coordinate the access of test.T.
follows #3593
=> pkg/transport: fix a data race in TestReadWriteTimeoutDialer

Documentation/libraries-and-tools.md
Added link for generic REST API in Go using etcd as a backend and validation using JSON Schema
=> docs/libraries-and-tools: add etcd-rest rest api daemon

Documentation/clustering.md, Documentation/configuration.md
Fix https://github.com/coreos/etcd/issues/3025
=> doc: emphasize name should be unique

etcdmain/etcd.go
/cc @eyakubovich @robszumski Please help to review :) Thanks!
=> etcdmain: print out error and suggestion for fixing notify issue

storage/backend/backend.go, storage/backend/batch_tx.go, storage/kvstore.go, storage/kvstore_test.go, storage/metrics.go
Tx.Size() is a high water mark for the db size. It is a good indicator of the max on disk size.
=> storage: add metrics for db total size

Documentation/api.md
=> docs/api.md: fix documentation

Documentation/authentication.md, Documentation/clustering.md, Documentation/configuration.md, Documentation/faq.md, Documentation/implementation-faq.md, Documentation/metrics.md, Documentation/runtime-configuration.md, Documentation/runtime-reconf-design.md, Documentation/tuning.md
I found some typos. Please let me know if you have any feedback.
Thanks,
=> Documentation: fix typos

pkg/transport/timeout_dialer_test.go, pkg/transport/timeout_listener_test.go
Longer timeout our slow CI system.
=> pkg/transport: longer timeout for slow CI

storage/backend/batch_tx.go
Commit a bolt tx will make all keys got inside the tx invalid. It might cause seg fault accessing these invalid keys.
We do access previously got keys inside a batchTx. So we MUST make sure we never commit a bolt tx inside one batchTx.
I can create the seg fault case without this patch. I cannot reproduce it with the patch. (It is hard to write a test though... I need to run my test for quite a while to catch a seg fault)
=> storage/backend: avoid creating new bolt.tx during a batchTx

etcdserver/cluster.go, etcdserver/server.go
quick fix. We need to fix the TODOs soon.
=> etcdserver: skip updating attr if the member does not exist

README.md
=> README: add semaphore CI status badge into README

client/README.md
=> Added example on how to get node's value

README.md
Address confusion on where to find stuff and make it easier to find with keywords for various operating systems.
=> README: fix language for release binaries

storage/watchable_store.go
We need to access the underlying store to use its RangeEvents function.
It is not good to use unnecessary type conversion.
The underlying store is also needed for further store upon
watchableStore.
=> storage: add store field in watchableStore

Documentation/04_to_2_snapshot_migration.md, Documentation/admin_guide.md, Documentation/branch_management.md, Documentation/errorcode.md, Documentation/glossary.md, Documentation/libraries-and-tools.md, Documentation/metrics.md, Documentation/other_apis.md, Documentation/production-ready.md, Documentation/proxy.md, Documentation/reporting_bugs.md, Documentation/rfc/v3api.md, Documentation/runtime-configuration.md, Documentation/runtime-reconf-design.md, Documentation/tuning.md, Documentation/upgrade_2_1.md, Documentation/upgrade_2_2.md
Correct the hierarchy of document headings.
Supersedes and closes #3696 .
=> Documentation: Fix heading hierarchy.

Documentation/configuration.md
to make it consistent with other sections in the doc.
/cc @joshix @jonboulle
=> docs/configuration: fix heading hierarchy

Documentation/libraries-and-tools.md
Add a c++ language binding for API v2.2.0
=> docs/libraries-and-tools: Update libraries-and-tools.md with etcdcpp

Documentation/proxy.md
This fixes some typos in proxy.md.
Thanks,
=> Documentation: fix typo in proxy.md

etcdctlv3/command/watch_command.go, etcdctlv3/main.go
=> etcdctlv3: support watch

Godeps/Godeps.json, Godeps/_workspace/src/github.com/boltdb/bolt/README.md, Godeps/_workspace/src/github.com/boltdb/bolt/bolt_arm64.go, Godeps/_workspace/src/github.com/boltdb/bolt/bolt_linux.go, Godeps/_workspace/src/github.com/boltdb/bolt/bolt_openbsd.go, Godeps/_workspace/src/github.com/boltdb/bolt/bolt_ppc64le.go, Godeps/_workspace/src/github.com/boltdb/bolt/bolt_s390x.go, Godeps/_workspace/src/github.com/boltdb/bolt/bolt_windows.go, Godeps/_workspace/src/github.com/boltdb/bolt/boltsync_unix.go, Godeps/_workspace/src/github.com/boltdb/bolt/bucket.go, Godeps/_workspace/src/github.com/boltdb/bolt/bucket_test.go, Godeps/_workspace/src/github.com/boltdb/bolt/db_test.go, Godeps/_workspace/src/github.com/boltdb/bolt/tx.go
Fix https://github.com/coreos/etcd/issues/3788
=> Godeps: update boltdb

raft/doc.go
For https://github.com/coreos/etcd/issues/3522
=> raft: add more words about raft protocol

raft/doc.go
=> raft: add doc to make restart clear

lease/lessor.go, lease/lessor_test.go
Add minimum KV interface and implmement the deleting mechanism for
revoking lease.
=> lease: delete items when the lease is revoked.

wal/wal.go
Fixes a minor typo in wal.go.
Thanks!
=> wal: minor typo in wal pkg

raft/progress.go
=> raft: minor typo in progress.go

Documentation/runtime-configuration.md
Partially fix https://github.com/coreos/etcd/issues/3476.
=> doc: talk about update client urls in reconf doc

raft/multinode_test.go, raft/node_test.go, raft/progress.go, raft/raft.go, raft/raft_test.go, raft/raftpb/raft.pb.go, raft/raftpb/raft.proto, raft/util.go
If quorum check fails, the leader will step down to follower.
Fix https://github.com/coreos/etcd/issues/3866
=> raft: support quorum check when raft is leader

etcdserver/v3demo_server.go
=> etcdserver: Fix panic for v3 transaction compares on non-existent keys

Documentation/proxy.md
This is for https://github.com/coreos/etcd/issues/3740. Some users find
`advertise-client-urls` and `initial-cluster` flags confusing to set up a
proxy. This clarifies why we need both flags.
=> Documentation: clarify flag usage for proxy

Documentation/proxy.md
Say what goreman is so it doesn't confuse. (line 17)
=> Documentation/proxy: Explain more about Procfile sample.

Documentation/proxy.md
This fixes a minor typo in proxy.md.
/cc @joshix @urzds
Found by https://github.com/coreos/etcd/issues/3740#issuecomment-160931333
Thanks
=> Documentation: minor typo in proxy.md

storage/watchable_store.go
/cc @gyuho @jonboulle @eyakubovich
=> storage: add missing return for unsafeAddWatching

etcdserver/api/v3rpc/watch.go
=> v3rpc: Tiny clean up

storage/watchable_store_test.go
This adds map operation tests for unsafeAddWatching, which
could have been failed without https://github.com/coreos/etcd/pull/3939.
/cc @xiang90 
Thanks!
=> storage: add tests for unsafeAddWatching

pkg/fileutil/purge_test.go
1. Add a few comments to the test.
2. Provide a more robust way to check the purging
result. Tolerate slow io operations.
Fix https://github.com/coreos/etcd/issues/3747
=> pkg/fileutil: make purgeTest more robust

etcdserver/server_test.go
save a few lines of code and make it more readable.
/cc @jonboulle
=> etcdserver: refactor a for loop in recvSnap test

storage/kvstore_test.go
Fix https://github.com/coreos/etcd/issues/3955
Retry a few times to handle slow IO issue.
=> storage: make RestoreContinueUnfinishedCompaction more reliable

raft/raft.go
This was causing some issues in cockroach cockroachdb/cockroach#2950
=> Ensure that Progress is not nil when a MsgSnapStatus comes in

pkg/ioutil/readcloser.go, rafthttp/snapshot_sender.go
=> rafthttp: snapshot sender cleanup

rafthttp/stream_test.go
fix https://github.com/coreos/etcd/issues/3983
=> rafhttp: make TestStreamWriterAttachOutgoingConn more robust

Documentation/production-users.md
=> Add OpenTable to production-users.md

README.md
Link to production_users.md.
/cc @philips
=> README: link to production users

Documentation/production-users.md
Adding use case for Radius Intelligence.
=> Radius Intelligence Use Case

contrib/raftexample/kvstore.go, contrib/raftexample/listener.go, contrib/raftexample/raft.go, contrib/raftexample/raftexample_test.go
Tests and some fixes along the way.
=> Raftexample tests

Godeps/Godeps.json, Godeps/_workspace/src/github.com/cheggaaa/pb/pb_win.go, Godeps/_workspace/src/github.com/olekukonko/ts/.travis.yml, Godeps/_workspace/src/github.com/olekukonko/ts/LICENCE, Godeps/_workspace/src/github.com/olekukonko/ts/README.md, Godeps/_workspace/src/github.com/olekukonko/ts/doc.go, Godeps/_workspace/src/github.com/olekukonko/ts/ts.go, Godeps/_workspace/src/github.com/olekukonko/ts/ts_darwin.go, Godeps/_workspace/src/github.com/olekukonko/ts/ts_linux.go, Godeps/_workspace/src/github.com/olekukonko/ts/ts_other.go, Godeps/_workspace/src/github.com/olekukonko/ts/ts_test.go, Godeps/_workspace/src/github.com/olekukonko/ts/ts_unix.go, Godeps/_workspace/src/github.com/olekukonko/ts/ts_windows.go, Godeps/_workspace/src/github.com/olekukonko/ts/ts_x.go
I reran Godep after this patch https://github.com/tools/godep/pull/352.
=> Godeps: add missing dependencies

raft/doc.go
To help people wanting use this package get started point to the
raftexample package.
=> raft: add raftexample to the docs

etcdserver/server.go
splits out the apply case into smaller functions
=> etcdserver: refactor server.go select loop

contrib/README.md, contrib/systemd/etcd2-backup-coreos/.gitignore, contrib/systemd/etcd2-backup-coreos/30-etcd2-backup-restore.conf, contrib/systemd/etcd2-backup-coreos/README.md, contrib/systemd/etcd2-backup-coreos/build, contrib/systemd/etcd2-backup-coreos/etcd2-backup-install, contrib/systemd/etcd2-backup-coreos/etcd2-backup.service, contrib/systemd/etcd2-backup-coreos/etcd2-backup.timer, contrib/systemd/etcd2-backup-coreos/etcd2-join, contrib/systemd/etcd2-backup-coreos/etcd2-join.service, contrib/systemd/etcd2-backup-coreos/etcd2-restore.go, contrib/systemd/etcd2-backup-coreos/etcd2-restore.service
multi-node backup and restore procedures for etcd2 clusters, presented as systemd jobs.
=> contrib/systemd: etcd2-backup package and docs

scripts/build-aci
The produced aci _should_ be the same.
=> scripts: rewrote build-aci to use acbuild

contrib/raftexample/raftexample_test.go, test
adds contrib/raftexample to test and fixes a race found by --race
=> test: activate tests on contrib/raftexample

etcdserver/server.go, etcdserver/server_test.go
shouldstop would get clobbered when several conf changes are in an apply
=> etcdserver: stop if removed along with multiple conf changes

etcdserver/server.go, etcdserver/snapshot_merge.go, rafthttp/snapshot_sender.go, rafthttp/transport.go, rafthttp/util.go, snap/message.go
Fix #4055 
Now etcd can recover from 5GB snapshot even under high load!
=> *: fix snapshot sending cycle

store/event.go, store/node.go, store/node_test.go
Updates IsCreated logic on event.go. Cleans up node.go
and adds tests to it.
=> store: clean up event.go, node.go and add tests

store/node_test.go
Found at https://travis-ci.org/coreos/etcd/jobs/99087279#L298.
=> store: fix govet shadow on expiration variable

etcdctl/command/util.go
=> etcdctl: return exitcode 2 if can't connect to any peer urls

tools/benchmark/cmd/put.go
This patch makes it possible to use benchmark to generate n keys and
make random updates to only those n keys.
=> tools/benchmark: support puts on sequential keys over a bounded keyspace

etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto, storage/storagepb/kv.pb.go
=> *: fix proto and regenerate all go files

etcdctlv3/command/watch_command.go, etcdserver/api/v3rpc/watch.go, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto, storage/kv_test.go, storage/watchable_store.go, storage/watchable_store_test.go, storage/watcher.go, storage/watcher_test.go
Related to:
- Issue https://github.com/coreos/etcd/issues/3848
- PR https://github.com/coreos/etcd/pull/3817
=> storage: watch events in slice

etcdctlv3/command/watch_command.go, etcdserver/api/v3rpc/watch.go, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto, tools/benchmark/cmd/watch.go
1. Add watch/cancel request
2. Add necessary fields in response to return watch error
3. Add watch_id into watch response
=> *: update watch related proto

storage/metrics.go, storage/watchable_store.go, storage/watchable_store_bench_test.go, storage/watchable_store_test.go, storage/watcher.go, storage/watcher_test.go
watcher is the active struct that watches on a key. It sends the watched event to its chan.
=> storage: rename watching -> watcher

raft/raft.go
Rename i to id since i looks like index which is confusing.
=> raft: Tiny refactor

.header
=> header: change date to 2016

etcdserver/api/v3rpc/watch.go, storage/kv.go, storage/kv_test.go, storage/watchable_store.go, storage/watchable_store_bench_test.go, storage/watchable_store_test.go, storage/watcher.go, storage/watcher_test.go
=> *: remove CancelFunc return for Watch. Use Cancel for watch.

etcdserver/server.go, etcdserver/server_test.go, storage/backend/backend.go, storage/backend/backend_test.go, storage/backend/batch_tx_test.go, storage/consistent_watchable_store.go, storage/consistent_watchable_store_test.go, storage/kv_test.go, storage/kvstore.go, storage/kvstore_bench_test.go, storage/kvstore_compaction_test.go, storage/kvstore_test.go, storage/watchable_store.go, storage/watchable_store_bench_test.go, storage/watchable_store_test.go, storage/watcher_bench_test.go, storage/watcher_test.go, tools/benchmark/cmd/storage.go
KV and lease will share the same backend. Thus we need to make
backend outside KV.
=> *: make backend outside kv

storage/kv_test.go
=> storage: remove test file after test

etcdmain/etcd.go, etcdserver/api/v3rpc/watch.go, etcdserver/etcdserverpb/rpc.proto, storage/watchable_store.go, storage/watcher.go
Related to https://github.com/coreos/etcd/issues/3848.
=> *: fill in WatchResponse.Header

lease/lessor.go, storage/consistent_watchable_store_test.go, storage/kv_test.go, storage/kvstore.go, storage/kvstore_bench_test.go, storage/kvstore_test.go, storage/watchable_store_bench_test.go, storage/watchable_store_test.go, storage/watcher_test.go, tools/benchmark/cmd/storage-put.go
NoLease is a special LeaseID for all leases, it's not just storage only
=> lease: move storage.NoLease to lease package

tools/benchmark/cmd/storage-put.go
=> tools/benchmark/cmd: print error out to stderr

etcdserver/raft.go, lease/lessor.go
=> *: expose Lessor Promote and Demote interface

lease/lessor.go, lease/lessor_test.go
=> lease: remove minExpiry and add helper funcs

etcdserver/server.go, lease/lessor.go
=> *: stop lessor when etcdserver is stopped

etcdctlv3/command/error.go, etcdctlv3/command/range_command.go, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto, etcdserver/v3demo_server.go
=> etcdserver: support sorted range requests in v3 api

raft/progress.go, raft/raft.go
Follow the golint notice, replace '+=1' to '++'
=> follow golint notice replace '+=1' to '++'

Documentation/api.md, Documentation/metrics.md
Addressing https://github.com/coreos/etcd/issues/4035.
/cc @xiang90 @joshix 
Thanks,
=> Documentation: stats/metrics reset on etcd restart

client/keys.go
=> client: keys.go minor typo

storage/watchable_store.go, storage/watcher_test.go
Current syncWatchers method skips the events that have
prefixes that are being watched when the prefix is not
existent as a key. This fixes https://github.com/coreos/etcd/issues/4191
by adding prefix checking to not skip those events.
=> storage: check prefix in unsynced

storage/backend/backend.go, storage/backend/backend_test.go, storage/backend/batch_tx.go
Fix https://github.com/coreos/etcd/issues/4110
Remove wait schedule which is unreliable.
=> backend: make test more reliable

storage/kv_test.go
Fix https://github.com/coreos/etcd/issues/4039
I believe the root cause of panic is that the defer closed backend while the last operation was still running. That happens since the wait timeouted. 
This pull request increase the wait time for slow IO and also only close backend when we know all txn are finished. Then we will not get panic at lease. Leaving some files in tmp dir seems to be just fine.
=> storage: fix panic in test

integration/v3_grpc_test.go
Related https://github.com/coreos/etcd/issues/4216.
Fixes https://semaphoreci.com/coreos/etcd/branches/master/builds/285.
=> integration: test header revision in v3 grpc

etcdmain/etcd.go
Proxy should not do srv lookup when there is an existing cluster file.
Fix #3753 
@raoofm
=> etcdmain: fix proxy srv lookup

integration/v3_grpc_test.go
Tests for races between producer and consumer on watcher
=> integration: submit keys concurrently with watcher streaming

etcdctl/README.md
Added some missing documentation surrounding etcdctl to hopefully save other people some time in the future (esp. for the environment variables)!
ping @robszumski
=> Add docs for configuration flags and env vars

integration/v3_grpc_test.go
For https://github.com/coreos/etcd/issues/4216.
=> integration: add TestV3WatchMultiple

test
=> test: test fmt before running unit tests

integration/v3_grpc_test.go
Related to https://github.com/coreos/etcd/issues/4216.
=> integration: watch test for multi-events with txn

integration/v3_grpc_test.go
Related https://github.com/coreos/etcd/issues/4216.
=> integration: add TestV3WatchMultipleStreams

integration/v3_grpc_test.go
This finishes https://github.com/coreos/etcd/issues/4216 except `PUT` with `unsynced` cases.
=> integration: add more tests for unsynced watch

integration/v3_grpc_test.go
Related https://github.com/coreos/etcd/issues/4216.
=> integration: TestV3WatchMultipleEventsPutUnsynced

integration/v3_grpc_test.go, lease/lessor.go, storage/key_index.go
/cc @xiang90 @heyitsanthony 
Thanks!
=> *: minor typos, kill TODOs

etcdmain/etcd.go, etcdserver/api/v3rpc/lease.go, etcdserver/errors.go, etcdserver/etcdhttp/peer.go, etcdserver/etcdhttp/peer_test.go, etcdserver/server.go, etcdserver/v3demo_server.go, integration/cluster_test.go, integration/v3_grpc_test.go, lease/http.go, lease/lessor.go
=> lease: forward lease keepalive to leader

contrib/recipes/barrier.go, contrib/recipes/client.go, contrib/recipes/key.go, contrib/recipes/mutex.go, contrib/recipes/priority_queue.go, contrib/recipes/queue.go, contrib/recipes/range.go, contrib/recipes/rwmutex.go, contrib/recipes/stm.go, contrib/recipes/watch.go, integration/v3_barrier_test.go, integration/v3_lock_test.go, integration/v3_queue_test.go, integration/v3_stm_test.go
Concurrency recipes using the V3 API (sans leases).
=> contrib: v3 recipes

integration/v3_barrier_test.go
@heyitsanthony https://travis-ci.org/coreos/etcd/jobs/104197786#L269
=> integration: minor govet shadow fix

etcdserver/etcdhttp/peer.go, etcdserver/server.go, etcdserver/v3demo_server.go, lease/leasehttp/http.go, pkg/transport/timeout_transport.go
move lease/http.go to its own pkg
=> leasehttp: move lease/http.go to its own pkg

etcdserver/server.go
Was causing goroutine leaks on my machine.
=> etcdserver: complete stopWithDelay on server shutdown

etcdserver/api/v3rpc/error.go, etcdserver/api/v3rpc/key.go, integration/v3_grpc_test.go
Fix https://github.com/coreos/etcd/issues/4109
=> v3rpc: check max ops in txn

etcdserver/v3demo_server.go, integration/v3_grpc_test.go, storage/kv.go, storage/kvstore.go
Fix https://github.com/coreos/etcd/issues/4265
=> etcdserver: check invalid range in txn

etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto
a direct port of https://github.com/coreos/etcd/blob/master/Documentation/members_api.md
=> etcdserver: initial member api proto

etcdctlv3/command/member_command.go, etcdctlv3/main.go, etcdmain/etcd.go, etcdserver/api/v3rpc/error.go, etcdserver/api/v3rpc/member.go, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto
tested with etcdctlv3 member sub command.
Fix #4263
=> *: finish member api implementation

etcdctlv3/command/compaction_command.go, etcdctlv3/command/delete_range_command.go, etcdctlv3/command/lease_command.go, etcdctlv3/command/member_command.go, etcdctlv3/command/put_command.go, etcdctlv3/command/range_command.go, etcdctlv3/command/txn_command.go, etcdctlv3/command/watch_command.go, tools/benchmark/cmd/util.go
Related to https://github.com/coreos/etcd/issues/4299.
=> *: pass WithInsecure to grpc.Dial for now

raft/doc.go
=> raft/doc: add notice about thread safety of messages

clientv3/kv.go
=> clientv3: add initial kv api for client

contrib/recipes/client.go, contrib/recipes/double_barrier.go, contrib/recipes/election.go, contrib/recipes/key.go, contrib/recipes/lease.go, integration/v3_double_barrier_test.go, integration/v3_election_test.go
rely on leases so these weren't included in the last batch
=> recipes: add election and double barrier recipes

clientv3/compare.go, clientv3/kv.go, clientv3/op.go, clientv3/sort.go
Set up initial client structure so that we can iterate on fast.
=> etcdclientv3: setup initial structure

clientv3/client.go, clientv3/kv.go, etcdserver/api/v3rpc/key.go, etcdserver/api/v3rpc/member.go
=> clientv3: use retryConnection

clientv3/kv.go, clientv3/op.go, clientv3/sort.go
=> clientv3: fill in kv ops

clientv3/watch.go
/cc @heyitsanthony @barakmich @gyuho @mitake
=> clientv3: initial watch API

clientv3/lease.go
/cc @heyitsanthony @gyuho @mitake @barakmich
=> clientv3: lease initial api

clientv3/compare.go, clientv3/kv.go, clientv3/op.go, clientv3/txn.go
/cc @heyitsanthony @gyuho @barakmich @mitake
=> clientv3: initial txn

clientv3/kv.go, clientv3/txn.go
=> clientv3: hook up KV and Txn

clientv3/kv.go, clientv3/txn.go
/cc @gyuho @heyitsanthony @mitake
=> clientv3: threadsafe

etcdserver/server_test.go
was racing when waiting for the node commit
fixes #4333
=> etcdserver/test: use recorderstream in TestApplyRepeat

e2e/etcdctl_test.go
Fixes https://semaphoreci.com/coreos/etcd/branches/pull-request-4344/builds/1
=> e2e: increase watch timeout

clientv3/integration/client_test.go, etcdserver/v3demo_server.go
=> Revert "*: TestKVRange to clientv3/integration, fix rev"

clientv3/client_test.go, clientv3/txn.go, pkg/types/urlsmap.go, pkg/wait/wait_time.go, raft/raft_test.go, wal/wal.go
Reference: http://goreportcard.com/report/coreos/etcd
=> *: fix minor typos, comments

storage/kvstore.go, storage/watchable_store.go
We decided that we will not support modifing the same
key in one txn multiple times. That can simlify the current
code/design a lot.
=> storage: simplify watch store

clientv3/lease.go, etcdctlv3/command/global.go, etcdctlv3/command/lease_command.go, etcdserver/api/v3rpc/lease.go
/cc @heyitsanthony @mitake @gyuho
=> clientv3: initial lease

clientv3/integration/kv_test.go
/cc @xiang90 @heyitsanthony 
Thanks,
=> clientv3/integration: TestKVPut with lease id

clientv3/kv.go
=> clientv3: do not retry on modifications

clientv3/cluster.go, clientv3/integration/cluster_test.go
/cc @heyitsanthony @gyuho @mitake
=> clientv3: implement cluster api

clientv3/client.go, clientv3/lease.go, integration/cluster.go, tools/benchmark/cmd/util.go
splitting this out so I can test individually; might be breaking CI
=> clientv3: support unix endpoints

clientv3/client.go
=> clientv3: add no endpoint error

storage/watchable_store.go, storage/watchable_store_bench_test.go, storage/watchable_store_test.go
=> storage: add watchSet and watchSetByKey type

storage/watchable_store.go, storage/watchable_store_test.go
=> storage: remove unnecessary abstraction

clientv3/integration/cluster_test.go, integration/cluster.go
Do not connect to the member to remove.
=> clientv3/integration: fix member remove

pkg/testutil/leak.go
Strips out the pointer arguments in the header of the stack trace so
that more stack traces match each other.
=> pkg/testutil: more aggressive goroutine stack trace coalescing

storage/watchable_store.go, storage/watchable_store_bench_test.go, storage/watchable_store_test.go
=> storage: make unsync a watcherSetByKey

storage/watchable_store.go, storage/watchable_store_test.go
=> storage: update watch.cur and fix tests

etcdserver/api/v3rpc/key.go, etcdserver/etcdserverpb/etcdserver.pb.go, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto, etcdserver/v3demo_server.go, integration/v3_grpc_test.go
For https://github.com/coreos/etcd/issues/4380.
=> etcdserver: add kv Hash method (for testing purpose)

tools/functional-tester/etcd-agent/agent_test.go, tools/functional-tester/etcd-agent/rpc.go, tools/functional-tester/etcd-agent/rpc_test.go, tools/functional-tester/etcd-tester/cluster.go, tools/functional-tester/etcd-tester/main.go, tools/functional-tester/etcd-tester/stresser.go
For https://github.com/coreos/etcd/issues/4380.
=> *: functional-tester with v3

pkg/wait/wait.go, pkg/wait/wait_test.go
/cc @heyitsanthony Let's try to catch duplicate id earlier...
=> pkg/wait: make id checking stricter

tools/functional-tester/etcd-tester/cluster.go, tools/functional-tester/etcd-tester/stresser.go, tools/functional-tester/etcd-tester/tester.go
For https://github.com/coreos/etcd/issues/4380.
=> functional-tester: fix grpc endpoint, consistent check

clientv3/integration/txn_test.go
also made TestTxnWriteFail better about timing out
fixes #4424
=> clientv3/integration: add timeouts to TestTxnWriteFail

clientv3/integration/kv_test.go
make sure Get will succeed after reconnect cycle
=> clientv3/integration: test Get retry

Documentation/rfc/v3api.md
To help people wanting use this package get started point to the
raftexample package.
=> Documentation: add more context on the v3 API

clientv3/client.go, etcdserver/api/v3rpc/error.go
=> *: add etcdserver namespace for rpc error

tools/functional-tester/etcd-tester/stresser.go, tools/functional-tester/etcd-tester/tester.go
And fix some minor print formats.
/cc @xiang90 
Thanks!
=> etcd-tester: log cancel in stresser

rafthttp/transport.go
Fix https://github.com/coreos/etcd/issues/4427
=> transport: make tr stop safe

Documentation/rfc/v3api.md, etcdserver/api/v3rpc/error.go, etcdserver/api/v3rpc/key.go, etcdserver/errors.go, etcdserver/v3demo_server.go, integration/v3_grpc_test.go
Fix https://github.com/coreos/etcd/issues/1978
=> *: limit request size for v3

Documentation/api.md, client/keys.go, client/keys_test.go, error/error.go, etcdserver/cluster.go, etcdserver/cluster_test.go, etcdserver/etcdhttp/client.go, etcdserver/etcdhttp/client_test.go, etcdserver/etcdserverpb/etcdserver.pb.go, etcdserver/etcdserverpb/etcdserver.proto, etcdserver/server.go, etcdserver/server_test.go, store/stats_test.go, store/store.go, store/store_bench_test.go, store/store_test.go
=> store/httpapi: support refresh ttl without firing watch

tools/functional-tester/etcd-agent/agent.go
=> etcd-agent: mkdir with read/write to all users

tools/functional-tester/etcd-tester/tester.go, tools/functional-tester/etcd-tester/util.go
=> etcd-tester: cleanup

tools/functional-tester/etcd-tester/stresser.go
Currently gRPC connection just gets recreated
for every Stress call. When Stress ends or gets
canceled, gRPC connection must also be closed.
For https://github.com/coreos/etcd/issues/4464.
/cc @xiang90
=> etcd-tester: close gRPC connection when canceling

tools/functional-tester/etcd-tester/stresser.go, tools/functional-tester/etcd-tester/tester.go
For https://github.com/coreos/etcd/issues/4465
=> etcd-tester: close leaky gRPC connections

tools/etcd-dump-logs/main.go
=> tools/etcd-dump-logs: support parsing v3 log

pkg/schedule/schedule.go, pkg/schedule/schedule_test.go, storage/kvstore.go, storage/kvstore_compaction.go, storage/kvstore_compaction_test.go, storage/kvstore_test.go
/cc @heyitsanthony Do you think we can convert the scheduler in applier (etcd/server.go) to use this too?
=> *: add a scheduler and use it to schedule compaction

clientv3/cluster.go
=> clientv3: fix godoc for member apis

lease/lessor.go, lease/lessor_test.go, storage/kvstore.go, storage/kvstore_test.go
=> detach keys from lease

pkg/schedule/schedule.go, pkg/schedule/schedule_test.go, storage/kvstore_test.go
Fix https://github.com/coreos/etcd/issues/4492
=> *: fix schedule.Wait race

etcdctl/README.md
For issues like https://github.com/coreos/etcd/issues/4496.
=> etcdctl: make doc on 'no-sync' clearer

etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto, etcdserver/v3demo_server.go, storage/storagepb/kv.pb.go
=> *: support local range request

clientv3/integration/kv_test.go, clientv3/op.go
=> clientv3: support serializable

integration/v3_lease_test.go
=> integration: test switch lease via put

tools/functional-tester/etcd-tester/cluster.go, tools/functional-tester/etcd-tester/tester.go
=> etcd-tester: use Hash method to get both revision and hash

tools/functional-tester/etcd-tester/main.go, tools/functional-tester/etcd-tester/metrics.go, tools/functional-tester/etcd-tester/tester.go
/cc @gyuho Let's redeploy tester!
=> tools/functional-tester: add metrics

tools/benchmark/cmd/watch.go
Current watch benchmark seems to be broken. This commit revives it.
=> tools/benchmark: revive watch benchmark

tools/benchmark/cmd/range.go
On my local machine, serializable range is 10x faster than range.
=> tools/benchmark: support serializable range benchmark

clientv3/sync/syncer.go, etcdctlv3/command/snapshot_command.go
Also add prefix support for sync. Prepare for the mirrorMaker use case.
=> *: move sync logic to clientv3/sync

clientv3/sync/syncer.go, etcdctlv3/command/make_mirror_command.go, etcdctlv3/main.go
Fix https://github.com/coreos/etcd/issues/1749
This is an initial implementation, do not expect this to be prefect.
=> etcdctlv3: add initial mirrormaker

tools/functional-tester/etcd-agent/agent.go
https://github.com/golang/go/blob/master/src/os/exec_posix.go#L18 shows that
cmd.Process.Kill calls syscall.SIGKILL to the command. But
http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_12_01.html explains
'If you send a SIGKILL to a process, you remove any chance for the process to
do a tidy cleanup and shutdown, which might have unfortunate consequences.'
This sends SIGTERM, SIGINT syscalls to the PID so that the process could
have more time to clean up the resources.
Related to https://github.com/coreos/etcd/issues/4517, https://github.com/coreos/etcd/issues/4517#issuecomment-183999787
=> etcd-agent: tidy cleanup before SIGKILL

etcdserver/snapshot_merge.go, snap/db.go
For https://github.com/coreos/etcd/issues/4527
=> *: record the number of bytes of snapshot sent/received

rafthttp/stream.go, rafthttp/transport.go
start to clean up rafthttp, : )
=> rafthttp: refactoring

rafthttp/stream.go
Improved the overall performance more than 20% under heavy load
with little latency impact.
heavy load
```
Requests/sec: ~23200  vs  Requests/sec: ~31500
Latency distribution:
10% in 0.0883 secs.
25% in 0.1022 secs.
50% in 0.1207 secs.
75% in 0.1460 secs.
90% in 0.1647 secs.
95% in 0.1783 secs.
99% in 0.2223 secs.
vs
Latency distribution:
10% in 0.1119 secs.
25% in 0.1272 secs.
50% in 0.1469 secs.
75% in 0.1626 secs.
90% in 0.1765 secs.
95% in 0.1863 secs.
99% in 0.2276 secs.
```
Similar on light load too.
=> rafthttp: smart batching

etcdserver/api/v3rpc/watch.go, integration/v3_watch_test.go, storage/watchable_store.go
Watcher would miss events since the keys would be created after
sending the watcher request but before etcd registered the watcher.
Fixes #4482
=> fix several watcher races

tools/functional-tester/etcd-agent/rpc.go, tools/functional-tester/etcd-tester/cluster.go, tools/functional-tester/etcd-tester/tester.go
capnslog already prefixes with its package name.
=> functional-tester: remove log prefixes

etcdctlv3/README.md, etcdctlv3/command/global.go, etcdctlv3/command/put_command.go
=> etcdctlv3: make PUT command clean and documented

tools/functional-tester/etcd-agent/agent.go
Partially related to https://github.com/coreos/etcd/issues/4552.
=> etcd-agent: get base when renaming

rafthttp/peer.go
Not sure why there is this additional go routine. So remove it... I am trying to see if there is a performance impact.
/cc @heyitsanthony please give this a careful look. Thanks!
=> rafthttp: remove unncessary go routine

integration/v3_watch_test.go
=> integration: fix go vet -shadow error

etcdserver/auth/auth.go
The removed comment is obsolete because the enabled field is removed
in the commit b2d2c79a2fcb20f6c64eeb95d1e7d1ddbcd453b1.
=> etcdserver, auth: remove obsolete mutex

etcdctlv3/README.md, etcdctlv3/command/get_command.go, etcdctlv3/command/util.go, etcdctlv3/command/watch_command.go
=> etcdctlv3: better watch command

tools/functional-tester/etcd-tester/stresser.go
For https://github.com/coreos/etcd/issues/4477. We confirmed that PUT requests were timing out
and returning when it triggered at the same moment as leader failure. This saves those requests by continuing in the for loop.
/cc @xiang90
=> etcd-tester: continue for deadline exceeded

etcdctlv3/README.md, etcdctlv3/command/make_mirror_command.go, etcdctlv3/doc/mirror_maker.md
=> etcdctlv3: add doc for mirror maker

tools/functional-tester/etcd-tester/cluster.go
=> tools/functional-tester: fix leaky issue by closing conn

.travis.yml
For https://github.com/coreos/etcd/issues/4577.
/cc @xiang90
=> travis: add go1.6

etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto, etcdserver/v3demo_server.go, integration/v3_grpc_test.go
For https://github.com/coreos/etcd/issues/4576.
=> *: return the number of deleted keys

etcdserver/raft_test.go, etcdserver/server_test.go, etcdserver/storage.go
=> etcdserver: fix race in TestTriggerSnap

clientv3/README.md, clientv3/example_kv_test.go
=> clientv3: README, GoDoc examples

etcdctlv3/README.md, etcdctlv3/command/txn_command.go, etcdctlv3/command/util.go, etcdctlv3/command/watch_command.go
=> etcdctlv3: make watch interactive mode better

client/auth_role.go, client/auth_user.go, clientv3/kv.go, clientv3/lease.go, clientv3/sync/syncer.go, etcdserver/cluster.go, etcdserver/member.go, raft/node.go, rafthttp/transport.go, storage/kv.go
=> *: fix godoc bugs in interfaces and slice fields

Documentation/security.md
Fix https://github.com/coreos/etcd/issues/3599
/cc @joshix @heyitsanthony @philips
=> doc/security.md: add notes for proxy security

clientv3/lease.go
=> clientv3: respect first stream error in lease recv loop

client/keys.go
=> client: minor typo fix

Documentation/admin_guide.md, Documentation/api.md, Documentation/auth_api.md, Documentation/authentication.md, Documentation/benchmarks/README.md, Documentation/benchmarks/etcd-2-1-0-alpha-benchmarks.md, Documentation/benchmarks/etcd-2-2-0-rc-benchmarks.md, Documentation/benchmarks/etcd-3-demo-benchmarks.md, Documentation/benchmarks/etcd-3-watch-memory-benchmark.md, Documentation/branch_management.md, Documentation/clustering.md, Documentation/configuration.md, Documentation/discovery_protocol.md, Documentation/faq.md, Documentation/metrics.md, Documentation/production-users.md, Documentation/proxy.md, Documentation/reporting_bugs.md, Documentation/rfc/v3api.md, Documentation/runtime-configuration.md, Documentation/runtime-reconf-design.md, Documentation/security.md, Documentation/tuning.md, Documentation/upgrade_2_1.md, Documentation/upgrade_2_2.md
/cc @joshix @robszumski @gyuho @xiang90
It is much easier to list all links at the bottom of the page. Let's do this way in future.
=> docs: Relink and fix broken links

clientv3/integration/watch_test.go, clientv3/op.go, clientv3/watch.go, etcdserver/api/v3rpc/watch.go, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto, integration/v3_watch_test.go, pkg/adt/interval_tree.go, pkg/adt/interval_tree_test.go, storage/kv_test.go, storage/watchable_store.go, storage/watchable_store_bench_test.go, storage/watchable_store_test.go, storage/watcher.go, storage/watcher_bench_test.go, storage/watcher_group.go, storage/watcher_test.go
protocol change so watch requests are ranges; server rejects non-prefix ranges
=> etcdserver, storage, clientv3: watcher ranges

etcdserver/raft.go, etcdserver/server.go, pkg/contention/contention.go
=> etcdserver: detect raft stravation

raft/raft.go
I lost a day or two to these ambiguities, hopefully this prevents others from the same fate :)
=> Fix raft node config docs

version/version.go
For https://github.com/coreos/etcd/issues/4652.
=> version: bump to apha1

clientv3/concurrency/mutex.go
Lock would get the prior key on retry using WithRev(myRev - 1) instead of
using the latest revision; the Watch() would return immediately and Lock
devolves into polling.
=> clientv3/concurrency: don't poll in mutex lock on early prior key delete

integration/v3_lease_test.go
Fix https://github.com/coreos/etcd/issues/4656.
=> integration: add TestV3PutOnNonExistLease

clientv3/client.go, clientv3/concurrency/election.go, clientv3/concurrency/mutex.go, clientv3/concurrency/session.go, etcdctlv3/command/elect_command.go, etcdctlv3/command/lock_command.go, integration/v3_election_test.go, integration/v3_lock_test.go
=> clientv3: include a context in Client

clientv3/integration/watch_test.go, clientv3/op.go, clientv3/watch.go
For https://github.com/coreos/etcd/issues/4628.
=> clientv3: add WithProgressNotify

tools/benchmark/cmd/watch.go
By specifying 'key-space-size', we can test min/max-key-range
of keys to watch.
For https://github.com/coreos/etcd/issues/3863.
=> benchmark: watch, key-space-size(max possible key)

tools/benchmark/cmd/put.go
For https://github.com/coreos/etcd/issues/4633.
=> benchmark: add auto-compact flags

tools/functional-tester/etcd-tester/cluster.go
For https://github.com/coreos/etcd/issues/4634.
=> functional-tester: less intensive stresser

clientv3/op.go, etcdserver/api/v3rpc/watch.go, integration/v3_watch_test.go
=> *: fix watch full key range

integration/v3_watch_test.go, storage/watchable_store.go
=> storage: use creation revision to compute txn event types

client/auth_role.go, client/auth_user.go, e2e/etcdctl_test.go
=> etcdctl: correctly unmarshal list users and list roles

etcdserver/api/v3rpc/watch.go, integration/v3_watch_test.go, storage/watchable_store.go, storage/watchable_store_test.go
Fix  https://github.com/coreos/etcd/issues/4624
=> *: support watch from future revision

clientv3/client.go, integration/v3_grpc_test.go
=> clientv3: don't deadlock on Close with broken connection

etcdserver/member.go
=> etcdserver: update NewMember comment to reflect how id is computed

tools/benchmark/cmd/watch.go
=> benchmark: change complete notifier first 

clientv3/client.go, etcdctlv3/command/global.go, integration/cluster.go, tools/benchmark/cmd/util.go
=> clientv3: use tls.Config in clientv3.Config

clientv3/integration/cluster_test.go
=> clientv3/integration: do not remove client member in TestMemberRemove

pkg/fileutil/lock.go, pkg/fileutil/lock_plan9.go, pkg/fileutil/lock_solaris.go, pkg/fileutil/lock_unix.go, pkg/fileutil/lock_windows.go
Just removes unnecessary duplicates.
=> pkg/fileutil: clean up interface, comments

storage/backend/backend_test.go
Fix https://github.com/coreos/etcd/issues/4530
Checked the code. I think the code is fine. CI just needs more time to finish IO.
=> backend: fix TestBackendClose by giving more time to wait for io

storage/backend/backend.go
Fixes crashes on 32-bit tests.
=> storage/backend: align fields used for atomic ops

etcdctl/command/set_dir_command.go
=> etcdctl: clarify setdir purpose in help message

etcdserver/api/v3rpc/grpc.go, etcdserver/api/v3rpc/maintenance.go, etcdserver/etcdserverpb/etcdserver.pb.go, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto, etcdserver/server.go
=> etcdserver: add maintain service to support defrag

clientv3/client.go, clientv3/maintenance.go, etcdctlv3/command/defrag_command.go, etcdctlv3/main.go
=> *: add client.defrag and defrag cmd for etcdctl

Godeps/Godeps.json, Godeps/_workspace/src/github.com/boltdb/bolt/README.md, Godeps/_workspace/src/github.com/boltdb/bolt/bolt_unix.go, Godeps/_workspace/src/github.com/boltdb/bolt/bolt_unix_solaris.go, Godeps/_workspace/src/github.com/boltdb/bolt/bolt_windows.go, Godeps/_workspace/src/github.com/boltdb/bolt/db.go, Godeps/_workspace/src/github.com/boltdb/bolt/tx.go
Fix https://github.com/coreos/etcd/issues/4527
=> godeps: update boltdb dependency

Documentation/api_v3.md
/cc @joshix @heyitsanthony @gyuho
=> doc: add v3 data model

etcdserver/server.go
oops... forgot to remove todo...
also use the var instead of the guarded field in server.
=> etcdserver: remove todo

Documentation/api.md
=> doc: fix refresh section in api.md

etcdserver/raft.go
=> etcdserver: leader latency optimization

pkg/fileutil/sync.go, pkg/fileutil/sync_linux.go, wal/wal.go
=> wal: support fadatasync on linux

README.md
Gocard includes most of the go style checking tools that we care about. This is a good indicator for us.
=> Readme: adding gocard

clientv3/integration/mirror_test.go, clientv3/mirror/syncer.go
Fix mirror.Sync. Sync should start from next revision.
=> clientv3: fix mirror and add integration test

wal/wal.go
We save commit index changes as a hint. So when a node restarts it can fast move forward commit index and then apply the entries.
But this is an optimization, and does not require fsync.
from raft paper:
```
Persistent state on all servers:
(Updated on stable storage before responding to RPCs)
- currentTerm 
- votedFor 
- log[]
```
=> wal: do not call fsync when it is not necessary

etcdctlv3/README.md, etcdctlv3/command/txn_command.go
=> etcdctlv3: define non-interactive txn format to match interactive input

etcdctlv3/command/get_command.go
Usage:
```
./bin/etcdctlv3 --endpoints=127.0.0.1:2378  get --with-prefix foo
```
It returns the data with key prefix "foo".
=> etcdctlv3/command: add with-prefix flag for get

tools/benchmark/cmd/put.go, tools/benchmark/cmd/range.go, tools/benchmark/cmd/report.go, tools/benchmark/cmd/timeseries.go, tools/benchmark/cmd/watch.go
Sample
```
Actual Latency distribution:
1457999564	69.503µs	  501
1457999565	20.887µs	  499
```
=> benchmark: printSecondSample with time series

tools/benchmark/cmd/timeseries.go
```
./benchmark put --total=10 --sample
10 / 10 Boooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00 % 1s
Summary:
Total:	1.0763 secs.
Slowest:	0.2407 secs.
Fastest:	0.0517 secs.
Average:	0.1076 secs.
Stddev:	0.0569 secs.
Requests/sec:	9.2907
Response time histogram:
0.052 [1]	|∎∎∎∎∎∎∎∎∎∎∎∎∎
0.071 [3]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
0.089 [0]	|
0.108 [2]	|∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎∎
0.127 [1]	|∎∎∎∎∎∎∎∎∎∎∎∎∎
0.146 [1]	|∎∎∎∎∎∎∎∎∎∎∎∎∎
0.165 [1]	|∎∎∎∎∎∎∎∎∎∎∎∎∎
0.184 [0]	|
0.203 [0]	|
0.222 [0]	|
0.241 [1]	|∎∎∎∎∎∎∎∎∎∎∎∎∎
Latency distribution:
10% in 0.0518 secs.
25% in 0.0675 secs.
50% in 0.1080 secs.
75% in 0.1572 secs.
90% in 0.2407 secs.
Sample in one second (unix latency throughput):
unix_ts,avg_latency,throughput
1458151378,51.660505ms,1 …
```
=> bench/cmd: print csv-format timeseries

raft/doc.go
Fix #4753 
/cc @heyitsanthony @bdarnell @ngaut @es-chow
=> raft: add optimization notes

Documentation/proxy.md
And partially related to https://github.com/coreos/etcd/issues/4595.
=> Documentation: discovery-fallback flag to proxy.md

clientv3/concurrency/session.go, clientv3/example_lease_test.go, clientv3/integration/kv_test.go, clientv3/integration/lease_test.go, clientv3/integration/watch_test.go, clientv3/lease.go, clientv3/op.go, clientv3/watch.go, contrib/recipes/key.go, etcdctlv3/command/lease_command.go, etcdctlv3/command/make_mirror_command.go, etcdctlv3/command/put_command.go, etcdctlv3/command/snapshot_command.go, etcdserver/api/v3rpc/key.go, etcdserver/api/v3rpc/lease.go, etcdserver/api/v3rpc/member.go, etcdserver/api/v3rpc/rpctypes/error.go, integration/v3_grpc_test.go, integration/v3_lease_test.go, test
=> clientv3: break etcdserver dependency

ROADMAP.md
=> Documentation: update ROADMAP with version 2.3

clientv3/kv.go, clientv3/op.go
Fix https://github.com/coreos/etcd/issues/4809.
=> clientv3: set Serializable from Op

Documentation/dev/release.md
=> Documentation: add public key link to release doc

e2e/etcd_test.go, etcdmain/config.go, etcdmain/etcd.go, pkg/transport/listener.go, pkg/transport/listener_test.go
Bare-bones; no cert verification, etc.
=> automatic peer TLS

etcdctlv3/command/ep_health_command.go, etcdctlv3/command/global.go, etcdctlv3/main.go
/cc @mqliang @heyitsanthony @gyuho 
ping pings every endpoint.
It can generate 3 outputs:
1. cannot connect to the member through endpoint
2. connected to the member, but member failed to commit any proposals
3. connected to the member, and member committed a proposal
=> etcdctlv3: implement endpoint-health command

e2e/etcdctlv3_test.go, etcdctlv3/command/get_command.go
=> etcdctlv3: get command with consistency flag

clientv3/compare.go, clientv3/concurrency/election.go, clientv3/concurrency/mutex.go, clientv3/txn_test.go, etcdctlv3/command/txn_command.go
=> clientv3: rename comparison from CreatedRevision to CreateRevision

tools/functional-tester/etcd-tester/cluster.go
=> functional-tester: set gRPC endpoint for stresser

tools/functional-tester/etcd-tester/cluster.go
GRPC and v2 client address share the same host(port)
but GRPC does not work with schema specified. This fixes
it by adding another member for GRPC without schema, as
we had before.
=> functional-tester: add GRPCURLs for cluster config

Documentation/configuration.md, e2e/etcd_test.go, e2e/etcdctlv3_test.go, etcdmain/config.go, etcdmain/etcd.go, etcdmain/help.go, etcdserver/config.go, etcdserver/raft.go, etcdserver/server.go, etcdserver/server_test.go, integration/cluster.go, integration/v3_grpc_test.go, rafthttp/peer.go, rafthttp/transport.go, tools/functional-tester/etcd-tester/cluster.go
WOW... We have v3 by default now.
=> *: enable v3 by default

tools/functional-tester/etcd-tester/main.go
Command line argument for specifying a schedule of test cases per round.
Default is run each test case once each round.
=> tools/functional-tester: --schedule-cases flag

etcdctlv3/command/auth_command.go, etcdctlv3/command/compaction_command.go, etcdctlv3/command/defrag_command.go, etcdctlv3/command/del_command.go, etcdctlv3/command/ep_health_command.go, etcdctlv3/command/get_command.go, etcdctlv3/command/global.go, etcdctlv3/command/lease_command.go, etcdctlv3/command/member_command.go, etcdctlv3/command/put_command.go, etcdctlv3/command/util.go, etcdctlv3/main.go
ref https://github.com/coreos/etcd/issues/4769
@xiang90 
Do not merge, just send for review, only adding support to "etcdctl member". If this approach looks good, will update to support all etcdctlv3 commands.
=> etcdctlv3: add timeout support

etcdmain/etcd.go
Fix https://github.com/coreos/etcd/issues/3850.
/cc @gtank
=> etcdmain: warn on contradictory TLS settings

etcdctlv3/command/ep_health_command.go, etcdctlv3/command/global.go, etcdmain/config.go, pkg/flags/flag.go, pkg/flags/flag_test.go
Fix https://github.com/coreos/etcd/issues/4197
=> etcdctlv3: accept evn for global configuration flags

Documentation/dev/logging.md
=> doc/dev: add logging doc

clientv3/integration/kv_test.go
=> clientv3/integration: get quorum before watching in TestKVCompact

client/doc.go, clientv3/doc.go
Fix #4865 
/cc @schmichael @heyitsanthony
=> client: doc that client is thread-safe

etcdctl/README.md, etcdctl/ctlv2/command/util.go
=> Handle ETCDCTL_USERNAME environment

etcdmain/help.go
=> etcdmain: add missing flag doc

client/client.go, client/client_test.go
Fix https://github.com/coreos/etcd/issues/3209.
=> client: return context error

auth/store.go, clientv3/auth.go, etcdserver/api/v3rpc/auth.go, etcdserver/apply.go, etcdserver/etcdserverpb/etcdserver.pb.go, etcdserver/etcdserverpb/raft_internal.pb.go, etcdserver/etcdserverpb/raft_internal.proto, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto, etcdserver/v3demo_server.go
This PR is based on the comment: https://github.com/coreos/etcd/pull/4845#issuecomment-201652908
/cc @xiang90
=> *: add Auth prefix to auth related requests and responses

auth/store.go, etcdserver/api/v3rpc/auth.go, etcdserver/api/v3rpc/key.go, etcdserver/api/v3rpc/util.go
=> etcdserver: return internal error in a case of not auth specific errors

client/README.md, clientv3/README.md
Related https://github.com/coreos/etcd/issues/4904.
=> *: document client package vendoring guide

etcdserver/apply.go, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto, etcdserver/v3demo_server.go, storage/kv.go, storage/kv_test.go, storage/kvstore.go, storage/watchable_store_test.go, tools/functional-tester/etcd-tester/cluster.go, tools/functional-tester/etcd-tester/tester.go
Faster than waiting 30 seconds between rounds.
=> etcd-tester: check compaction revision

alarm/alarms.go, clientv3/client.go, clientv3/maintenance.go, etcdctl/ctlv3/command/alarm_command.go, etcdctl/ctlv3/command/printer.go, etcdctl/ctlv3/ctl.go, etcdserver/api/v3rpc/maintenance.go, etcdserver/api/v3rpc/quota.go, etcdserver/apply.go, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto, etcdserver/server.go
Adds support for `etcdctl alarm list` and `etcdctl alarm disarm`.
=> etcdctl: alarm command

etcdserver/v3demo_server.go, storage/kvstore.go
=> etcdserver, storage: wait for physical compaction if already compacted

etcdctl/ctlv3/command/auth_command.go, etcdctl/ctlv3/command/user_command.go
This commit lets etcdctl v3 follow the manner of etcdctl v2.
=> etcdctl: print messages for successful auth operations

e2e/etcd_test.go, e2e/etcdctlv3_test.go
Resolves TODO with the new expect package.
=> *: ctl v3 tests with multi expects

auth/store.go, clientv3/auth.go, etcdctl/ctlv3/command/user_command.go, etcdserver/api/v3rpc/auth.go, etcdserver/apply.go, etcdserver/etcdserverpb/raft_internal.pb.go, etcdserver/etcdserverpb/raft_internal.proto, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto, etcdserver/v3demo_server.go
This commit adds a functionality for updating password of existing
users.
=> *: support changing password in v3 auth

etcdserver/v3demo_server.go, storage/kvstore.go
=> etcdserver: force backend commit before acking physical compaction

tools/functional-tester/etcd-tester/cluster.go
When compactKV request is halted before final acknowledgement,
it used to just continue on the next endpoint. But there could be
a case than compactKV is requested twice, and the first one is already
replicated and applied by the time the second request was to be
applied (returning compact revision error). This skips the case
by parsing the error message.
=> etcd-tester: no error for compact double-send

Godeps/Godeps.json, clientv3/client.go, clientv3/config.go, clientv3/config_test.go, vendor/github.com/ghodss/yaml/.gitignore, vendor/github.com/ghodss/yaml/.travis.yml, vendor/github.com/ghodss/yaml/LICENSE, vendor/github.com/ghodss/yaml/README.md, vendor/github.com/ghodss/yaml/fields.go, vendor/github.com/ghodss/yaml/yaml.go, vendor/gopkg.in/yaml.v2/LICENSE, vendor/gopkg.in/yaml.v2/LICENSE.libyaml, vendor/gopkg.in/yaml.v2/README.md, vendor/gopkg.in/yaml.v2/apic.go, vendor/gopkg.in/yaml.v2/decode.go, vendor/gopkg.in/yaml.v2/emitterc.go, vendor/gopkg.in/yaml.v2/encode.go, vendor/gopkg.in/yaml.v2/parserc.go, vendor/gopkg.in/yaml.v2/readerc.go, vendor/gopkg.in/yaml.v2/resolve.go, vendor/gopkg.in/yaml.v2/scannerc.go, vendor/gopkg.in/yaml.v2/sorter.go, vendor/gopkg.in/yaml.v2/writerc.go, vendor/gopkg.in/yaml.v2/yaml.go, vendor/gopkg.in/yaml.v2/yamlh.go, vendor/gopkg.in/yaml.v2/yamlprivateh.go
Fix https://github.com/coreos/etcd/issues/4008.
@mitake I looked through your pr, but I do not really feel good about bringing in viper as a dependency for such a small problem. viper seems to be overkill for it.
=> clientv3: support read conf from file

clientv3/integration/watch_test.go, clientv3/op.go, clientv3/watch.go, e2e/etcd_test.go, etcdserver/server_test.go, integration/v3_grpc_test.go, integration/v3_watch_test.go, pkg/fileutil/fileutil_test.go, storage/key_index.go
With help from https://github.com/dominikh/go-simple.
=> *: clean up if, bool comparison

storage/backend/backend.go
=> backend: reset count in defrg

tools/functional-tester/etcd-tester/cluster.go, tools/functional-tester/etcd-tester/tester.go
Fix https://github.com/coreos/etcd/issues/4665.
=> functional-tester: defrag every 500 round

clientv3/maintenance.go, etcdctl/ctlv3/command/printer.go, etcdctl/ctlv3/command/status_command.go, etcdctl/ctlv3/ctl.go, etcdserver/api/v3rpc/maintenance.go, etcdserver/etcdserverpb/etcdserver.pb.go, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto
@xiang90 
Initial implementaton of `etcdctl member status` command. 
Only expose version information in this initial implementation. Will try to expose more information(such ad  raft status, db size) in a follow-up PR.
BTW, How about move the "IsLeader" status to the output of `etcdctl member status` from `etcdctl member list`?
=> etcdctlv3: initial implementaton of 'etcdctl member status' command

e2e/etcd_test.go, e2e/etcdctlv3_test.go, pkg/expect/expect.go, pkg/expect/expect_test.go
=> e2e, pkg/expect: distinguish between Stop and Close

etcdserver/v3demo_server.go
Support case where txn doesn't have to go through quorum.
=> etcdserver: serializable transactions

e2e/etcdctlv3_test.go
=> e2e: clean up to test tables, endpoint-health test

pkg/expect/expect.go, pkg/expect/expect_test.go
ExpectFunc to make expect more extensible. LineCount to be
able to check 'no output' command.
=> pkg/expect: ExpectFunc, LineCount

clientv3/integration/watch_test.go
=> clientv3/integration: fix watch range test typo

client/auth_user.go, client/keys_test.go, etcdctl/ctlv3/ctl.go, etcdmain/etcd.go, etcdserver/api/v2http/http.go, pkg/netutil/netutil.go, proxy/director.go, raft/raft.go, rafthttp/stream.go, storage/watcher_group.go
With help from https://github.com/dominikh/go-unused.
IsNetTimeoutError seems useful, so moved to pkg/netutil.
=> *: clean up unused vars, functions

e2e/etcd_test.go, etcdserver/api/cluster.go, etcdserver/api/v2http/client.go, etcdserver/api/v2http/client_test.go, etcdserver/api/v2http/http.go, etcdserver/api/v2http/http_test.go, etcdserver/api/v2http/peer_test.go, etcdserver/api/v3rpc/member.go, etcdserver/cluster_util.go, etcdserver/errors.go, etcdserver/membership/cluster.go, etcdserver/membership/cluster_test.go, etcdserver/membership/errors.go, etcdserver/membership/member.go, etcdserver/membership/member_test.go, etcdserver/raft.go, etcdserver/raft_test.go, etcdserver/server.go, etcdserver/server_test.go, etcdserver/util.go, pkg/types/urls.go
continue to clean up etcdserver pkg and prepare for storing membership info in storage pkg.
=> etcdserver: move membership related code to membership pkg

e2e/ctl_v2_test.go, e2e/etcd_test.go, etcdserver/api/v2http/capability.go
debugging https://github.com/coreos/etcd/issues/4998 in CI env.
=> *: log, expect by capability check

clientv3/integration/watch_test.go
Fix https://github.com/coreos/etcd/issues/5001.
=> clientv3/integration: use clientv3.Event type

etcdserver/membership/cluster.go, etcdserver/membership/store.go, etcdserver/server.go, etcdserver/server_test.go
Close https://github.com/coreos/etcd/pull/4116
=> membership: update attr in membership pkg

.travis.yml, clientv3/concurrency/key.go, contrib/systemd/etcd2-backup-coreos/etcd2-restore.go, etcdctl/ctlv2/command/cluster_health.go, etcdctl/ctlv2/command/util.go, etcdctl/ctlv3/command/member_command.go, etcdserver/auth/auth_test.go, etcdserver/membership/cluster.go, etcdserver/stats/queue.go, etcdserver/stats/server.go, pkg/testutil/leak.go, storage/kvstore.go, storage/kvstore_compaction.go, store/event_history.go, store/store.go, test
- https://github.com/dominikh/go-unused
- https://github.com/dominikh/go-simple
=> clean up with gosimple and unused

raft/node.go, raft/node_test.go, raft/raft.go, raft/raft_test.go, raft/raftpb/raft.pb.go, raft/raftpb/raft.proto, raft/rawnode.go, raft/rawnode_test.go, raft/util.go
Try to implement transfer leader as per raft thesis `3.10 Leadership transfer extension`.
=> raft: transfer leader feature

auth/authpb/auth.pb.go, auth/authpb/auth.proto, auth/store.go, clientv3/auth.go, etcdctl/ctlv3/command/role_command.go, etcdserver/api/v3rpc/auth.go, etcdserver/api/v3rpc/rpctypes/error.go, etcdserver/api/v3rpc/util.go, etcdserver/apply.go, etcdserver/etcdserverpb/raft_internal.pb.go, etcdserver/etcdserverpb/raft_internal.proto, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto, etcdserver/v3demo_server.go
=> *: support granting key permission to role in v3 auth

auth/authpb/auth.pb.go, auth/authpb/auth.proto, etcdctl/ctlv3/command/auth_command.go, etcdctl/ctlv3/command/user_command.go
This PR has two commits that just fix trivial problems in v3 auth.
=> trivial updates for v3 auth

client/README.md, clientv3/README.md
If I understand our new vendoring correctly... please review /cc @xiang90 @heyitsanthony
=> *: client vendoring README

e2e/ctl_v3_user_test.go
New test cases have been added to test the "user" sub-commands of
the etcdctlv3 utility.
=> e2e: Test cases for the etcdctlv3 user commands.

raft/log_test.go
sync test case from https://github.com/pingcap/tikv/pull/398
=> raft: add a test case for Test Slice

e2e/ctl_v3_test.go, etcdctl/ctlv3/command/global.go
Support got clobbered about a month ago.
=> etcdctl: respect --write-out

auth/authpb/auth.pb.go, etcdctl/ctlv3/command/printer.go, etcdserver/api/v3rpc/maintenance.go, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto, lease/leasepb/lease.pb.go, raft/raftpb/raft.pb.go, snap/snappb/snap.pb.go, storage/storagepb/kv.pb.go, wal/walpb/record.pb.go
ref https://github.com/coreos/etcd/issues/4797
@xiang90
=> etcdctlv3: expose store size and raft status in 'etcdctl status' command

rafthttp/msgappv2_codec.go
=> rafthttp: fix comment in msgappv2

e2e/ctl_v2_test.go, e2e/ctl_v3_lock_test.go, e2e/ctl_v3_test.go, e2e/etcd_test.go, pkg/expect/expect.go, pkg/expect/expect_test.go
Trying to figure out what is going on with pids and signals on CI.
=> pkg/expect, e2e: support sending Signals to expect process, test etcdctl lock

e2e/ctl_v3_elect_test.go
Thanks! Almost same as your lock command test.
=> e2e: add elect command test

tools/functional-tester/etcd-tester/http.go, tools/functional-tester/etcd-tester/tester.go
to fix the last one at https://goreportcard.com/report/github.com/coreos/etcd#go_vet
=> etcd-tester: fix govet

cmd/Godeps/Godeps.json, cmd/vendor/google.golang.org/grpc/backoff.go, cmd/vendor/google.golang.org/grpc/clientconn.go, cmd/vendor/google.golang.org/grpc/rpc_util.go, cmd/vendor/google.golang.org/grpc/transport/control.go, cmd/vendor/google.golang.org/grpc/transport/http2_client.go, cmd/vendor/google.golang.org/grpc/transport/http2_server.go
/cc @heyitsanthony Mainly for fixing grpc.
=> *:update dependencies

e2e/ctl_v3_test.go, etcdctl/READMEv3.md, etcdctl/ctlv3/command/get_command.go
/cc @xiang90 @heyitsanthony 
Thanks.
=> *: add rev flag to get command

tools/functional-tester/etcd-agent/agent.go, tools/functional-tester/etcd-agent/client/client.go, tools/functional-tester/etcd-agent/rpc.go, tools/functional-tester/etcd-tester/failure.go, tools/functional-tester/etcd-tester/main.go
Fix https://github.com/coreos/etcd/issues/4666.
=> functional-tester: add latency test (simulate slow network)

etcdctl/READMEv3.md
nearly complete. still missing alarm and auth
=> doc: document many etcdctl commands

etcdmain/etcd.go, proxy/httpproxy/director.go, proxy/httpproxy/director_test.go, proxy/httpproxy/doc.go, proxy/httpproxy/metrics.go, proxy/httpproxy/proxy.go, proxy/httpproxy/proxy_test.go, proxy/httpproxy/reverse.go, proxy/httpproxy/reverse_test.go, test
We are going to add a tcp proxy for etcdlet and probably a grpc proxy for etcdout.
=> proxy: move http related thing to httpproxy

auth/store.go
Fixes https://github.com/coreos/etcd/issues/5077
=> auth: remove index out of range in role grant

proxy/tcpproxy/userspace.go, proxy/tcpproxy/userspace_test.go, test
/cc @heyitsanthony @gyuho 
prepare for etcdlet.
=> proxy: initial userspace tcp proxy
