etcd-io/etcd

- clientv3/config.go
- clientv3/config_test.go
> clientv3: make YamlConfig struct private

- test
The data race in net/http has been fixed for a while.
> test: check races on rafthttp

- Documentation/api_v3.md
> doc: add doc for kv message

- tools/functional-tester/etcd-tester/cluster.go
> etcd-tester: return error if first compaction times out

- Documentation/api_v3.md
> doc: add response header doc into api

- tools/benchmark/cmd/watch.go
Fix https://github.com/coreos/etcd/issues/5099.
> benchmark: ensure all watcher receivers to finish

- proxy/httpproxy/proxy.go
Issue https://github.com/coreos/etcd/issues/5033. It was just enable the http2 support to proxy and member, and it was enable in client connecting to the proxy. I thought it maybe support when using v3 api.
> Enable http2 support between proxy and member

- pkg/fileutil/lock_flock.go
- pkg/fileutil/lock_linux.go
- pkg/fileutil/lock_unix.go
> pkg/fileutil: fix linux file locks over NFS

- Documentation/interacting_v3.md
> doc: add write/read example for interact doc

- Documentation/local_cluster.md
> doc: add local_cluster doc

- Documentation/interacting_v3.md
> doc: add lease section to interacting doc

- Documentation/dl_build.md
/cc @heyitsanthony @gyuho @joshix
> doc: build

- test
https://travis-ci.org/coreos/etcd/jobs/124383329 failing silently on gosimple
/cc @gyuho @mitake
> test: display failure output for gosimple

- storage/backend/backend.go
- storage/backend/backend_test.go
- storage/backend/batch_tx.go
> backend: update db.size after defrag

- e2e/ctl_v3_alarm_test.go
- e2e/ctl_v3_test.go
- e2e/etcd_test.go
Same as https://github.com/coreos/etcd/blob/master/integration/v3_grpc_test.go#L525 but in e2e.
Thanks.
> e2e: test alarm

- e2e/ctl_v3_make_mirror_test.go
- e2e/etcd_test.go
For https://github.com/coreos/etcd/issues/4589.
> e2e: make-mirror

- tools/functional-tester/etcd-tester/tester.go
When hashes don't match, there could be some nodes
falling behind and the compact request can then error
with 'future revision compact'.
> etcd-tester: skip compaction after different hash

- Documentation/docs.md
/cc @heyitsanthony @joshix @weiliendang
Fix https://github.com/coreos/etcd/issues/5106
> doc: front page of etcd3 doc

- Documentation/api_reference_v3.md
- scripts/genproto.sh
**It's experimental**. One can run './scripts/genproto.sh -g'
Fix https://github.com/coreos/etcd/issues/5100.
> *: Protocol Buffer docs auto-generate script

- Documentation/api_reference_v3.md
- scripts/genproto.sh
> *: change Protocol Buffer documentation title

- integration/v3_grpc_test.go
> integration: wait for alarm in TestV3StorageQuotaApply

- tools/functional-tester/etcd-tester/tester.go
Otherwise, the previous success overwrites the later failure.
I forgot last time... 
/cc @xiang90
> etcd-tester: reset success var for every case

- etcdctl/ctlv3/command/snapshot_command.go
> etcdctl/ctlv3: close bolt.DB in snapshot status

- tools/functional-tester/etcd-tester/failure.go
For https://github.com/coreos/etcd/issues/5121.
> etcd-tester: wait more for slow network recovery

- Documentation/recovery_v3.md
> doc: v3 disaster recovery doc

- tools/functional-tester/etcd-tester/main.go
- tools/functional-tester/etcd-tester/tester.go
> etcd-tester: flag consistency-check

- clientv3/lease.go
If switchRemoteAndStream fails, the whole lease API fails since
the internal routine exits. We should only fail the whole API when
there is a fatal error. For example, we should fail if we fail to
connection to all the endpoints user provided.
If we connect to an endpoint, but fail to create a stream, we should
retry instead of returning error to fail the entire API.
> clientv3: retry on switchRemoteAndStream

- Documentation/docs.md
- Documentation/op_guide/recovery.md
> doc: link to recovery.md

- etcdctl/ctlv3/command/make_mirror_command.go
- etcdmain/config.go
move quota flag to where member flags are, and fix minor typo
> *: fix flag location, minor typo

- Documentation/docs.md
Make the heading sentences that introduce each list of documents
a little more standard language, remove implied 2nd person, reduce
exclamations.
> Documentation/doc.md: Make headings boring :)

- .github/ISSUE_TEMPLATE.md
- .github/PULL_REQUEST_TEMPLATE.md
Hopefully we do not have to ask people to change their commit message anymore...
> .github: add pull request and issue template

- Documentation/metrics.md
- etcdserver/metrics.go
- mvcc/metrics.go
- rafthttp/metrics.go
- snap/metrics.go
- store/metrics.go
- wal/metrics.go
/cc @heyitsanthony @joshix @fabxc
> *: add debugging metrics

- clientv3/integration/lease_test.go
- clientv3/lease.go
- etcdserver/api/v3rpc/lease.go
> etcdserver: respond with ttl=0 for revoked lease keep alive

- tools/functional-tester/etcd-tester/stresser.go
To prevent stressers from returning from failure injections
> etcd-tester: match more grpc errors

- auth/store.go
- auth/store_test.go
- test
> auth: add basic tests

- clientv3/concurrency/mutex.go
- integration/v3_lock_test.go
With randomized keys, if the connection goes down, but the session remains,
the client would need complicated recovery logic to avoid deadlock.
Instead, bind the session's lease id to the lock entry; if a session tries
to reacquire the lock it will reassume its old place in the wait list.
> clientv3/concurrency: use session lease id for mutex keys

- etcdserver/api/v3rpc/header.go
- etcdserver/api/v3rpc/lease.go
- etcdserver/apply.go
Fix https://github.com/coreos/etcd/issues/5173
> v3rpc: fill lease header

- etcdserver/v3_server.go
- integration/v3_grpc_test.go
Fix #5214.
/cc @heyitsanthony Can you give this a try?
> etcdserver: add timeout for processing v3 request

- integration/cluster.go
- integration/cluster_test.go
- rafthttp/transport.go
> integration: wait for ReadyNotify in Issue3699 test

- clientv3/client.go
- clientv3/client_test.go
- clientv3/cluster.go
- clientv3/integration/auth_test.go
- clientv3/integration/kv_test.go
- clientv3/integration/lease_test.go
- clientv3/integration/role_test.go
- clientv3/integration/txn_test.go
- clientv3/integration/user_test.go
- clientv3/kv.go
- clientv3/lease.go
- clientv3/maintenance.go
- clientv3/txn.go
- clientv3/watch.go
- etcdserver/api/v3rpc/rpctypes/error.go
- integration/cluster.go
For https://github.com/coreos/etcd/issues/5211.
> *: return rpctypes.Err in clientv3

- Documentation/production-users.md
Added production usage for Vonage
> Doc: Update production-users.md

- clientv3/kv.go
- clientv3/txn.go
If the grpc connection is restored between an rpc network failure
and trying to reestablish the connection, the connection retry would
end up resetting good connections if many operations were
in-flight at the time of network failure.
> clientv3: better serialization for kv and txn connection retry

- mvcc/watchable_store.go
- mvcc/watcher_test.go
> mvcc: fix watch deleteRange

- clientv3/auth.go
- clientv3/integration/kv_test.go
- clientv3/integration/lease_test.go
- clientv3/integration/watch_test.go
- etcdserver/api/v3rpc/key.go
- etcdserver/api/v3rpc/lease.go
- etcdserver/api/v3rpc/member.go
- etcdserver/api/v3rpc/quota.go
- etcdserver/api/v3rpc/rpctypes/error.go
- etcdserver/api/v3rpc/rpctypes/error_test.go
- etcdserver/api/v3rpc/util.go
- integration/cluster.go
- integration/member_test.go
- integration/migration_test.go
- integration/v3_grpc_test.go
- integration/v3_lease_test.go
- test
Fix https://github.com/coreos/etcd/issues/5211.
> rpctypes: error interface

- clientv3/README.md
- clientv3/example_kv_test.go
> clientv3: fix README, add error handling example

- README.md
repeated put rather than put followed by get
> simple typo in README docs for getting started

- .travis.yml
- build
- test
See: https://github.com/coreos/etcd/issues/5054
> Add arm64 travis builds

- tools/functional-tester/etcd-runner/main.go
/cc @heyitsanthony @gyuho 
We plan to run this against a no consistency checking failure injection cluster. Interesting!
> etcd-runner: initial commit

- Documentation/op-guide/configuration.md
- e2e/ctl_v3_kv_test.go
- e2e/ctl_v3_test.go
- e2e/etcd_test.go
- etcdmain/config.go
- etcdmain/etcd.go
> *: support auto tls on client side

- build
Fix https://github.com/coreos/etcd/issues/5255.
> build: set GitSHA version in cmd directory

- build
> build: Simplify host detection

- etcdmain/help.go
> etcdmain: add auto-tls flag to help.go

- etcdserver/server.go
Fix https://github.com/coreos/etcd/issues/3328.
> *: more detailed timeout logging

- clientv3/integration/watch_test.go
- clientv3/watch.go
- integration/cluster.go
> clientv3: gracefully handle watcher resume on compacted revision

- tools/functional-tester/etcd-tester/main.go
- tools/functional-tester/etcd-tester/status.go
- tools/functional-tester/etcd-tester/tester.go
Fix https://github.com/coreos/etcd/issues/5254.
> etcd-tester: refactor

- Documentation/metrics.md
- Documentation/v2/metrics.md
- etcdserver/api/v2http/metrics.go
- etcdserver/api/v3rpc/grpc.go
- etcdserver/api/v3rpc/metrics.go
- etcdserver/metrics.go
- snap/metrics.go
- wal/metrics.go
/cc @fabxc @brian-brazil @mwitkow It would be awesome if you can take a look. Thanks!
> *: add metrics for grpc api

- Documentation/docs.md
- Documentation/op-guide/performance.md
/cc @heyitsanthony @joshix @gyuho
> doc: add performance.md

- build.ps1
> build: set git sha on windows builds

- clientv3/client.go
- clientv3/cluster.go
- clientv3/kv.go
- clientv3/lease.go
- clientv3/maintenance.go
- clientv3/remote_client.go
- clientv3/txn.go
- clientv3/watch.go
the etcd-runner lock tester seems to work fine now
> clientv3: fix disconnect breakage

- Documentation/metrics.md
- etcdserver/metrics.go
- etcdserver/raft.go
/cc @heyitsanthony @joshix @fabxc @brian-brazil
> *: add leader changes to metrics

- Documentation/metrics.md
- etcdserver/metrics.go
- etcdserver/raft.go
/cc @heyitsanthony @joshix @fabxc @brian-brazil
> *: add has leader metrics

- etcdserver/v3_server.go
> etcdserver: fix nil dereference in physical Compact on proposal timeout

- wal/decoder.go
- wal/doc.go
- wal/encoder.go
- wal/repair.go
- wal/repair_test.go
> wal: repair torn writes

- etcdmain/config.go
- etcdmain/config_test.go
- etcdmain/etcd.conf.sample.yml
- etcdmain/etcd.go
- etcdmain/help.go
Added a new command line option to etcd server to read in a YAML
based configuration file. Have also added an example configuration
file with comments.
Fixes #4009
> etcd: Configuration file for etcd server.

- Documentation/op-guide/configuration.md
Add a description about the --config-file option into the
configuration.md file.
> Doc: Add the new '--config-file' detail to configuration.md file

- etcdctl/READMEv3.md
- etcdctl/ctlv3/command/ep_command.go
- etcdctl/ctlv3/command/member_command.go
- etcdctl/ctlv3/command/printer.go
- etcdctl/ctlv3/command/snapshot_command.go
- etcdctl/ctlv3/ctl.go
Fix https://github.com/coreos/etcd/issues/5296.
> etcdctl/ctlv3: make 'table' printer configurable

- Documentation/metrics.md
- etcdserver/metrics.go
- etcdserver/raft.go
/cc @fabxc @heyitsanthony @joshix @brian-brazil
> *: add proposalsCommitted metrics

- etcdmain/etcd.go
> etcdmain: notify systemd when etcd is ready to accept requests

- Documentation/metrics.md
- mvcc/backend/batch_tx.go
- mvcc/backend/metrics.go
- wal/wal.go
/cc @joshix @heyitsanthony @gyuho @fabxc
> *: add disk operation metrics for monitoring

- Documentation/v2/README.md
For https://github.com/coreos/etcd/issues/518.
> v2/README: add known bugs

- Documentation/v2/README.md
- README.md
> *: fix minor typos

- rafthttp/transport_test.go
> *: fix TestTransportErrorc

- etcdserver/api/v3rpc/grpc.go
- etcdserver/api/v3rpc/interceptor.go
- etcdserver/api/v3rpc/metrics.go
- etcdserver/api/v3rpc/rpctypes/error.go
- etcdserver/api/v3rpc/rpctypes/md.go
- integration/v3_grpc_test.go
> *: etcd member rejects unary call with leader requirement when it does not have leader

- integration/cluster.go
- integration/v3_grpc_test.go
- integration/v3_lock_test.go
> integration: fix NewClientV3 error messages

- proxy/httpproxy/reverse.go
> httpproxy: fix capnslog log path

- clientv3/client.go
- clientv3/integration/kv_test.go
Was crashing on a nil connection. Reworked the shutdown path a little so
there's only one connection close site.
> clientv3: fix Close after failed Put

- etcdmain/gateway.go
- proxy/tcpproxy/userspace.go
Fix https://github.com/coreos/etcd/issues/5335.
> etcdmain: gateway monitor-interval flag

- raft/raft.go
If there is a leadership transfer request to leader itself, we can always ignore it. We do not need to abort anything. The abort logic is correctly handle at line 713 
/cc @tiancaiamao @es-chow @bdarnell @swingbach
> raft: simplify leadership transfer

- e2e/ctl_v3_kv_test.go
- etcdctl/ctlv3/command/get_command.go
> etcdctl/ctlv3: allow empty key

- clientv3/kv.go
- integration/cluster.go
- proxy/grpcproxy/kv.go
- proxy/grpcproxy/kv_test.go
> proxy: initial grpc kv service proxy

- integration/v3_election_test.go
elections are now per-session so waiting on the same election with the
same client will not block like before
Fixes #5362
> integration: fix TestElectionWait

- Documentation/dev-guide/local_cluster.md
- Documentation/op-guide/maintenance.md
> Documentation: write-out=table for v3 commands

- Documentation/v2/admin_guide.md
Fix https://github.com/coreos/etcd/issues/5358.
/cc @xiang90 @heyitsanthony
> Documentation/v2: fix typo for updating a member 

- cmd/Godeps/Godeps.json
- cmd/vendor/github.com/boltdb/bolt/README.md
- cmd/vendor/github.com/boltdb/bolt/db.go
- cmd/vendor/github.com/boltdb/bolt/errors.go
- cmd/vendor/github.com/boltdb/bolt/page.go
- cmd/vendor/github.com/boltdb/bolt/tx.go
> vendor: update boltdb to v1.2.1

- mvcc/kvstore.go
- mvcc/kvstore_bench_test.go
```
go test -v -run=xxx -benchmem -bench BenchmarkStoreTxnPut
Before
BenchmarkStoreTxnPut-8	  200000	     11221 ns/op	    1476 B/op	      13 allocs/op
After 
BenchmarkStoreTxnPut-8	  200000	     10619 ns/op	    1463 B/op	      12 allocs/op
```
If it's not worth this, just remove the TODO?
> mvcc: use buffer bytes to encode consistent index

- raft/raft_test.go
raft: add more assertions to make the test case more understandable
> raft: add more assertions on dueling candidates test case

- tools/benchmark/cmd/watch.go
Fix https://github.com/coreos/etcd/issues/5099.
> benchmark: fix watch command

- clientv3/watch.go
To avoid slice growth when appending
> clientv3: preallocate watch streams slice

- clientv3/concurrency/stm.go
> clientv3/concurrency: preallocate slice in stm

- etcdctl/READMEv3.md
@heyitsanthony @hongchaodeng @gyuho @joshix
> etcdctl: add migrate command into readme

- clientv3/op.go
Sorry for small shitty patches. Hope to have better ones in the future, but I send it as I find it :P
> clientv3: fix typo

- rafthttp/util.go
> rafthttp: replace append with pre-allocated slice

- integration/cluster.go
When debugging issues like https://github.com/coreos/etcd/issues/5416, currently there's no way to know if the leader election happens from our manual member.Stop call or etcd itself. This adds explicit logs about what the testing suite does.
> integration: add logs for debugging

- Documentation/docs.md
- Documentation/op-guide/v2-migration.md
@heyitsanthony @gyuho @hongchaodeng @joshix @robszumski @jakedt @timothysc
Fix https://github.com/coreos/etcd/issues/4969
> doc: add app migration doc

- e2e/ctl_v3_migrate_test.go
- e2e/etcd_test.go
Fix https://github.com/coreos/etcd/issues/5407.
> e2e: test migrate command

- e2e/etcd_test.go
- proxy/httpproxy/director.go
- proxy/httpproxy/reverse.go
> proxy/httpproxy: fix v2 proxy log header

- Documentation/op-guide/v2-migration.md
> Doc: fix typo in v2-migration.md

- store/store.go
> store: use Rlock when GET

- Documentation/dev-guide/api_reference_v3.md
- etcdserver/etcdserverpb/rpc.pb.go
- etcdserver/etcdserverpb/rpc.proto
Fix https://github.com/coreos/etcd/issues/5401.
> etcdserverpb: document how to prefix, range query

- tools/functional-tester/etcd-tester/cluster.go
- tools/functional-tester/etcd-tester/tester.go
Fix https://github.com/coreos/etcd/issues/5440.
> etcd-tester: fix compact timeout

- etcdctl/READMEv3.md
- etcdctl/ctlv3/command/printer.go
- etcdctl/ctlv3/ctl.go
Fix https://github.com/coreos/etcd/issues/5297.
> etcdctl/ctlv3: protobuf write-out for member list

- clientv3/client.go
> clientv3: handle URL scheme when given in endpoint

- Documentation/op-guide/performance.md
Fix https://github.com/coreos/etcd/issues/5433.
> Documentation: add benchmark to performance.md

- auth/doc.go
- compactor/doc.go
- contrib/raftexample/doc.go
- etcdserver/api/doc.go
- etcdserver/api/v3rpc/rpctypes/doc.go
- lease/doc.go
- lease/leasehttp/doc.go
- pkg/adt/doc.go
- pkg/contention/doc.go
- pkg/mock/mockstorage/doc.go
- pkg/mock/mockstore/doc.go
- pkg/mock/mockwait/doc.go
- pkg/schedule/doc.go
- pkg/tlsutil/doc.go
- proxy/grpcproxy/doc.go
- proxy/tcpproxy/doc.go
- tools/benchmark/cmd/doc.go
- tools/benchmark/doc.go
- tools/etcd-dump-logs/doc.go
- tools/etcd-top/doc.go
- tools/functional-tester/etcd-agent/client/doc.go
- tools/functional-tester/etcd-agent/doc.go
- tools/functional-tester/etcd-runner/doc.go
- tools/functional-tester/etcd-tester/doc.go
> *: add missing godoc package descriptions

- tools/functional-tester/etcd-tester/cluster.go
- tools/functional-tester/etcd-tester/tester.go
To help debug https://github.com/coreos/etcd/issues/5440.
> etcd-tester: log more for compact errors

- raft/README.md
> raft: initial readme

- rafthttp/peer.go
- rafthttp/stream.go
- rafthttp/stream_test.go
> rafthttp: simplify streamReader initilization

- etcdctl/ctlv3/command/migrate_command.go
> etcdctl: improve error message on migration without v2 keys

- etcdserver/membership/cluster.go
- etcdserver/server.go
- rafthttp/peer.go
- rafthttp/peer_status.go
- rafthttp/pipeline.go
- rafthttp/probing_status.go
- rafthttp/stream.go
- rafthttp/transport.go
Add more logging for better debugging purpose.
> *: more logging on critical state change

- clientv3/integration/kv_test.go
- clientv3/remote_client.go
> clientv3: fix deadlock on Get with concurrent Close

- clientv3/integration/watch_test.go
- clientv3/watch.go
Fix https://github.com/coreos/etcd/issues/5495.
> clientv3: watch resp with error when client close

- Documentation/docs.md
- Documentation/op-guide/failures.md
/cc @heyitsanthony @joshix @gyuho @philips @robszumski 
fix #https://github.com/coreos/etcd/issues/3428
> doc: add failures guide

- cmd/Godeps/Godeps.json
- cmd/vendor/google.golang.org/grpc/server.go
Sync with https://github.com/grpc/grpc-go/commit/bab01e8e85235b06e1da34c9c9b677f291d2dadb.
> vendor: update grpc dependency

- clientv3/client.go
- clientv3/config.go
since grpc GA was pushed back, will probably have to wait for the picker stabilize
/cc @xiang90
> clientv3: hide retry dial api

- rafthttp/peer.go
- rafthttp/pipeline.go
- rafthttp/pipeline_test.go
- rafthttp/remote.go
- rafthttp/snapshot_sender.go
- rafthttp/stream.go
- rafthttp/stream_test.go
- rafthttp/transport.go
> rafthttp: simplify initialization funcs

- pkg/transport/listener.go
> transport: require tls12

- Documentation/op-guide/v2-migration.md
Doc: fix link for migrate command in v2-migration
> Doc: fix link for migrate command in v2-migration

- pkg/fileutil/preallocate_unix.go
- wal/wal.go
> pkg/fileutil: fall back to truncate() if fallocate is interrupted

- e2e/ctl_v3_watch_test.go
- etcdctl/README.md
- etcdctl/ctlv3/command/watch_command.go
Fix https://github.com/coreos/etcd/issues/5575.
> etcdctl: support watch with range_end

- auth/store.go
> auth: add getuser

- etcdserver/v3_server.go
@mitake I cleaned this up a little bit by reducing indentation.
> etcdserver: make usernameFromCtx more go style

- wal/wal.go
> wal: warn if sync exceeds a second

- clientv3/integration/kv_test.go
Fix https://github.com/coreos/etcd/issues/5601.
> clientv3/integration: WaitLeader to follower

- auth/store.go
- e2e/ctl_v3_auth_test.go
- etcdserver/api/v3rpc/rpctypes/error.go
- etcdserver/api/v3rpc/util.go
- etcdserver/apply.go
automatically create root user with root role when enabling auth if root user does not exist.
> auth: add root user and root role

- clientv3/integration/lease_test.go
- clientv3/lease.go
> clientv3: close keepalive channel if TTL locally exceeded

- clientv3/client.go
Needs to use a different balancer from the main client connection
because of the way grpc uses the Notify channel.
Fixes #5604 
/cc @mitake
> clientv3: use separate dialopts for auth dial

- raft/README.md
/cc @aaronlehmann @aluzzardi @LK4D4
etcd/raft API is pretty stable right now. But there might be minor changes. We generally will notice our users before any API or feature changes.
> raft: add docker/swarmkit as notable raft users

- auth/store.go
- etcdserver/apply.go
> *: add admin permission checking

- pkg/fileutil/preallocate.go
> fileutil: avoid double preallocation

- tools/functional-tester/etcd-tester/tester.go
This is temporary fix for #5606.
> etcd-tester: do not exit for compaction timeout

- auth/store.go
/cc @mitake 
Right now, the only thing we keep in memory as cache is enabled. So we only need to recover that bit.
> auth: implement recover

- auth/range_perm_cache.go
- auth/store.go
Clean up role related marshal.
/cc @mitake
> auth: add getRole

- auth/store.go
> auth: add put_user

- e2e/ctl_v3_auth_test.go
- e2e/ctl_v3_test.go
- etcdserver/v3_server.go
> e2e: auth key put test

- auth/store.go
@heyitsanthony @mitake 
Future cleanup:
1. add put role
2. use getUser
> auth: cleanup

- auth/store.go
> auth: add del functions for user/role

- auth/store.go
> auth: cleanup store.go

- etcdserver/apply.go
- etcdserver/server.go
> etcdserver: warn heavy apply

- pkg/fileutil/fileutil.go
- pkg/fileutil/lock_plan9.go
- pkg/fileutil/lock_test.go
- pkg/fileutil/purge.go
- pkg/fileutil/purge_test.go
- wal/file_pipeline.go
- wal/repair.go
- wal/wal.go
- wal/wal_test.go
To make it consistent with pkg/fileutil
> wal: PrivateFileMode/DirMode as in pkg/fileutil

- Documentation/v2/admin_guide.md
> Doc: Fault tolerance table

- auth/range_perm_cache.go
- auth/range_perm_cache_test.go
> auth: clean up range_perm_cache.go

- auth/range_perm_cache.go
> auth: cleanup get perm func

- Documentation/dev-guide/api_reference_v3.md
- etcdserver/etcdserverpb/rpc.pb.go
- etcdserver/etcdserverpb/rpc.proto
> v3 docs: ErrCompaction -> ErrCompacted

- wal/wal.go
Some minor clean up, simplification
> wal: simplify boolean return

- auth/range_perm_cache.go
- auth/store.go
> auth: clean permission checking

- wal/wal.go
- wal/wal_bench_test.go
- wal/wal_test.go
- Replace reflect.Equal with bytes.Equal where possible
- Remove some TODOs
- Some minor simplifications
> wal: use bytes.Equal, other minor updates

- auth/range_perm_cache.go
- auth/range_perm_cache_test.go
- auth/store.go
- etcdserver/apply.go
- etcdserver/v3_server.go
> make auth key, rangeEnd typed like mvcc ([]byte)

- auth/range_perm_cache.go
- auth/range_perm_cache_test.go
- auth/store.go
/cc @heyitsanthony @mitake 
To combine the range checking and key checking code path, we need to treat key, range the same in the merge function.
> auth: add key support in merge func

- e2e/ctl_v3_watch_test.go
> e2e: don't Put() after watchTest finishes

- auth/store.go
- etcdserver/apply.go
> *: support deleteRange perm checking

- tools/local-tester/bridge/bridge.go
- tools/local-tester/bridge/dispatch.go
With bonus bridge connection code refactor.
> bridge: packet corruption and reordering

- etcdserver/apply_auth.go
I'll work on e2e test for the checking mechanism soon.
> etcdserver: permission checking of Txn() in authApplierV3

- etcdserver/server.go
When there is an inflight snapshot, we want to pause compaction.
The previous approach is too aggressive by pausing the entire snapshot path. That leads to a huge recovery cost due to lack of recent snapshot. This patch improves the mechanism by only pausing compaction but still allowing snapshot to happen.
> etcdserver: only pause compaction when sending snapshot

- etcdserver/apply_auth.go
Fix https://github.com/coreos/etcd/issues/5569
/cc @mitake @heyitsanthony
> etcdserver: fix panic when getting header of raft request

- Documentation/demo.md
- README.md
- Added more demos, links to our README
- links to dash.etcd.io, play.etcd.io
- added `migrate` command example
> README: more demos, links

- tools/functional-tester/etcd-agent/agent_test.go
> etcd-agent: fix test

- Documentation/op-guide/configuration.md
- Documentation/op-guide/maintenance.md
- etcdmain/config.go
- etcdmain/help.go
> *: make auto-compaction-retention non-experimental

- Documentation/metrics.md
- etcdserver/metrics.go
- etcdserver/server.go
> etcdserver: add applied metrics

- Documentation/metrics.md
- rafthttp/metrics.go
/cc @heyitsanthony @gyuho 
We will add network metrics for clients too.
> *: add peer prefix for network metrics between peers

- Documentation/metrics.md
- etcdserver/metrics.go
- etcdserver/v2_server.go
- etcdserver/v3_server.go
> *: add pending/failed proposal metrics

- contrib/recipes/double_barrier.go
- contrib/recipes/key.go
- lease/lessor.go
- lease/lessor_test.go
- proxy/grpcproxy/kv_test.go
- test
- tools/functional-tester/etcd-agent/client/client.go
- tools/functional-tester/etcd-tester/failure.go
- tools/functional-tester/etcd-tester/stresser.go
Whitelisting tests meant etcd wouldn't test packages by default; now using a blacklist.
/cc @gyuho @xiang90
> test: don't hardcode packages for testing

- Documentation/dev-guide/api_grpc_gateway.md
- Documentation/dev-guide/apispec/swagger/rpc.swagger.json
- Documentation/docs.md
- scripts/genproto.sh
- Addressing https://github.com/coreos/etcd/issues/5686
- generate swagger API definitions in `genproto.sh`
- document how to use `grpc-gateway`
> Documentation: grpc-gateway

- etcdctl/ctlv3/command/role_command.go
> etcdctl: slightly enhance output of role revoke-permission

- etcdserver/api/v3rpc/watch.go
- mvcc/metrics.go
Fix https://github.com/coreos/etcd/issues/5717
/cc @nekto0n Can you give this patch a try?
> *: fix pending events metrics

- tools/benchmark/cmd/watch.go
> benchmark: correctly count number of watchers

- Documentation/metrics.md
- etcdserver/api/v3rpc/codec.go
- etcdserver/api/v3rpc/grpc.go
- etcdserver/api/v3rpc/metrics.go
> *: add client network metrics

- e2e/v2_curl_test.go
- e2e/v3_curl_test.go
> e2e: grpc-gateway cURL tests

- clientv3/integration/watch_test.go
- clientv3/watch.go
/cc @gyuho @xiang90
Caveat: unique deadlines will create unique streams since ctxs are keyed by their String()
> clientv3: watch with arbitrary ctx values

- tools/benchmark/cmd/watch.go
> benchmark: fix watch bench

- e2e/ctl_v3_auth_test.go
- e2e/ctl_v3_role_test.go
This commit adds extends the test for checking runtime permission
grant/revoke.
> e2e: check runtime permission changing

- e2e/ctl_v3_auth_test.go
> e2e: add test cases for updating user and role during operations

- etcdctl/README.md
Fix https://github.com/coreos/etcd/issues/5580.
> etcdctl/ctlv3: document auth,user,role

- etcdctl/ctlv3/command/migrate_command.go
- etcdctl/ctlv3/command/role_command.go
- etcdctl/ctlv3/command/user_command.go
- etcdctl/ctlv3/ctl.go
- Fix typo
- Improve command ordering (elect should be below lock)
- Update migrate command description
> etcdctl/ctlv3: minor clean ups

- build
- etcdserver/raft.go
- test
Added a few initial failpoints where it seems useful to delay/crash in etcdserver.
> build with failpoints

- clientv3/integration/kv_test.go
- clientv3/kv.go
- clientv3/op.go
> clientv3: add withCount support

- etcdserver/apply_auth.go
- etcdserver/v3_server.go
> etcdserver: make serialized txns auth-aware

- test
> test: check commit titles

- Documentation/proxy.md
Ref https://github.com/coreos/etcd/pull/5693 in v3 track (master).
Ref backport to 2.3.7 docs in https://github.com/coreos-inc/coreos-pages/pull/747
> Documentation/proxy: Change proxy port from 8080 to 2379

- Documentation/op-guide/configuration.md
- etcdmain/etcd.go
- etcdmain/help.go
> *: make it clear that proxy only supports v2 api now

- Documentation/op-guide/security.md
> doc: auto-tls example in security guide

- Documentation/branch_management.md
- Documentation/dev-internal/discovery_protocol.md
- Documentation/dev-internal/release.md
- Documentation/dl_build.md
- Documentation/docs.md
- Documentation/op-guide/clustering.md
- Documentation/op-guide/configuration.md
- Documentation/op-guide/runtime-configuration.md
- Documentation/op-guide/runtime-reconf-design.md
- Documentation/op-guide/security.md
- Documentation/production-users.md
- Documentation/reporting_bugs.md
- Documentation/tuning.md
> doc: remove you/your from current docs

- Dockerfile
- Dockerfile-release
- scripts/build-docker
Fix https://quay.io/repository/coreos/etcd-git/build/d75d80b1-7d8d-42bd-af07-645b7da3a118.
> *: separate Dockerfile for quay build trigger

- Documentation/dev-guide/experimental_apis.md
- Documentation/docs.md
@heyitsanthony @gyuho 
Shall we call them experimental than unstable? unstable sounds scary... We want it sounds somewhat scary, but we also encourage people to try them out.
> doc: add unstable

- etcdserver/server.go
```bash
./etcd
...
ctrl+c
...
rm default.etcd/member/snap/db
...
./etcd
...
2016-06-26 20:13:02.596930 C | etcdmain: database file (default.etcd/member/snap/db) of backend is missing
```
> etcdserver: refuse to restart if backend file is missing

- etcdserver/server.go
- mvcc/kvstore.go
> etcdserver: check index of the kv when restarting

- Documentation/dl_build.md
- Documentation/op-guide/recovery.md
- Documentation/op-guide/runtime-configuration.md
> Documentation: clear out some TODOs

- Documentation/docs.md
- Documentation/upgrades/upgrade_3_0.md
Tested and confirmed that it worked.
/cc @xiang90 @heyitsanthony
> Documentation/upgrades: upgrade 3.0 doc

- mvcc/backend/backend.go
- mvcc/backend/backend_test.go
- mvcc/kvstore.go
- mvcc/kvstore_test.go
fix https://github.com/coreos/etcd/issues/5791
> mvcc: do not hash consistent index

- clientv3/example_kv_test.go
- clientv3/integration/kv_test.go
- clientv3/integration/watch_test.go
- clientv3/kv.go
- etcdctl/ctlv3/command/compaction_command.go
> clientv3, ctl3, clientv3/integration: add compact response to compact

- raft/node.go
- raft/node_test.go
- raft/raft.go
- raft/raft_test.go
- raft/raftpb/raft.pb.go
- raft/raftpb/raft.proto
try to implement read-only query based on leader lease.
> raft: implemented read-only query when quorum check is on

- clientv3/watch.go
> clientv3: only use return closeErr when donec is closed

- clientv3/naming/grpc.go
- clientv3/naming/grpc_test.go
> clientv3: add grpc naming resolver

- tools/functional-tester/etcd-tester/stresser.go
Fix https://github.com/coreos/etcd/issues/5804.
> etcd-tester: match ErrTimeout in stresser

- raft/log_unstable.go
For https://github.com/coreos/etcd/pull/5790.
CI is acting weird now...
> raft: simplify truncateAndAppend

- proxy/grpcproxy/kv.go
implement compaction function in proxy.
@xiang90
> proxy: implement compaction function

- auth/store.go
- e2e/ctl_v3_auth_test.go
This PR a little bit cleaning and test enhance for disabling auth in v3 API.
> disabling auth in v3 API

- etcdmain/grpc_proxy.go
- etcdmain/main.go
- proxy/grpcproxy/cache/store.go
- proxy/grpcproxy/kv.go
> *: initial implementation of grpc-proxy

- tools/functional-tester/etcd-tester/cluster.go
- tools/functional-tester/etcd-tester/failure.go
- tools/functional-tester/etcd-tester/failure_agent.go
- tools/functional-tester/etcd-tester/member.go
- tools/functional-tester/etcd-tester/tester.go
Started doing this for #5754, but seems self-contained enough to split out. Planning to squash before merge.
/cc @gyuho @xiang90
> etcd-tester: refactor cluster and failure code

- discovery/discovery.go
- discovery/discovery_test.go
- discovery/srv.go
> discovery: Uniform code style

- Documentation/dev-guide/experimental_apis.md
> Doc: fix typo in dev-guide.md

- auth/range_perm_cache.go
- clientv3/lease.go
- etcdmain/config.go
- etcdmain/config_test.go
- etcdmain/etcd.go
> *: fixed some  warning

- compactor/compactor_test.go
> compactor: make tests deterministic

- etcdserver/api/v3rpc/watch.go
Fix #5856 
/cc @tejohnso @heyitsanthony @gyuho
> v3rpc: do not panic on user error for watch

- raft/README.md
/cc @bdarnell @philips @heyitsanthony @gyuho Please take a look. Thanks!
> raft: add features section to readme file

- Documentation/dl_build.md
- README.md
Address https://github.com/coreos/etcd/issues/5857#issuecomment-230174840
> Documentation: add instruction on vendoring, build

- rafthttp/probing_status.go
> rafthttp: make health check meaning clearer

- Documentation/tuning.md
> Documentation: tuning advice for peer prioritization

- etcdserver/api/v3rpc/rpctypes/error.go
/cc @mitake @heyitsanthony @gyuho
> rpctypes: use permission deny code for permission deny error

- Documentation/docs.md
> doc: better link for embed etcd

- e2e/ctl_v2_test.go
- e2e/etcd_test.go
Repro'd the error in #5824 by sleeping for a few seconds in etcdserver before sending the publish request.
/cc @xiang90 @gyuho
> e2e: wait for every etcd server to publish to cluster

- etcdserver/api/v3rpc/rpctypes/error.go
- etcdserver/api/v3rpc/util.go
- etcdserver/errors.go
- etcdserver/server.go
- etcdserver/v3_server.go
fix https://github.com/coreos/etcd/issues/5628
> *: deny proposals when there is a huge gap between apply/commit

- tools/functional-tester/etcd-tester/main.go
- tools/functional-tester/etcd-tester/stresser.go
- tools/functional-tester/etcd-tester/tester.go
Replace https://github.com/coreos/etcd/pull/5914.
> etcd-tester: pause before compaction, fix races, cleanups

- build
- mvcc/backend/batch_tx.go
those commit failpoints we were talking about the other day /cc @gyuho
> build, backend: add backend commit failpoints

- tools/functional-tester/etcd-tester/cluster.go
- tools/functional-tester/etcd-tester/member.go
- tools/functional-tester/etcd-tester/stresser.go
> etcd-tester: add FailFast(false) to grpc calls

- .travis.yml
- test
/cc @philips @jaredeh @xiang90
I nuked ppc64le and replaced it with 386 to save some resources. People have asked for 386 (e.g., @blp), but I am unaware of anyone actually using ppc64le (@luxas added it, but afaik he's only doing arm dev).
> travis: unit test on 386

- etcdmain/grpc_proxy.go
- proxy/grpcproxy/watch.go
- proxy/grpcproxy/watcher.go
- proxy/grpcproxy/watcher_group.go
- proxy/grpcproxy/watcher_group_test.go
- proxy/grpcproxy/watcher_groups.go
- proxy/grpcproxy/watcher_single.go
@heyitsanthony 
Just put up this pr for reference. The most basic functionality works. It is not as complicated as I thought...
> grpcproxy: initial watch proxy

- embed/etcd.go
> embed: fix nil dereference on error to set up initial cluster

- integration/embed_test.go
> integration: new ports for embed test

- etcdserver/server.go
Fix https://github.com/coreos/etcd/issues/5950
/cc @gyuho
> etcdserver: set applied index correctly

- etcdmain/grpc_proxy.go
- proxy/grpcproxy/cluster.go
> *: add cluster proxy

- etcdmain/grpc_proxy.go
- proxy/grpcproxy/maintenance.go
> grpcproxy: add maintenance proxy

- contrib/raftexample/raft.go
By restricting the channel types in the `raftNode` struct, it's clearer that the node only writes to (and never reads from) the `commitC` and `errorC` channels.
> contrib/raftexample: Restrict commit/error channel types in raftNode

- etcdmain/grpc_proxy.go
- proxy/grpcproxy/auth.go
@heyitsanthony Yeah! The proxy now supports all services!
> grpcproxy: add auth

- etcdserver/api/v3rpc/watch.go
- proxy/grpcproxy/watch.go
- proxy/grpcproxy/watcher.go
> grpcproxy: add filter to watcher

- tools/functional-tester/etcd-tester/stresser.go
For https://github.com/coreos/etcd/issues/5618.
> etcd-tester: stress with range, delete

- compactor/compactor_test.go
Fixes #5847
Advancing the clock before the rg.Wait in the first loop means the compactor could receive the clock tick either before or after the unpause. On the rare occasion of receiving the clock tick before the unpause, the test fails with an early revision.
> compactor: make event ordering well-defined in TestPeriodicPause

- clientv3/integration/lease_test.go
Fixes #5900
Way to repro: set the resend timer in `sendKeepAliveLoop()` to a millisecond and add a second delay after the `stream.Recv()` in `recvKeepAliveLoop()`
> integration: drain keepalives in TestLeaseKeepAliveCloseAfterDisconnectRevoke

- etcdmain/gateway.go
/cc @gyuho @heyitsanthony 
Probably we should move the discoverer out of client to discovery pkg in the near future.
> etcdmian: gateway supports dns srv discovery

- proxy/grpcproxy/watcher.go
- proxy/grpcproxy/watcher_groups.go
- proxy/grpcproxy/watcher_single.go
> grpcproxy: do not send duplicate events to watchers

- embed/etcd.go
err result wasn't taken into consideration
> embed: Fixed serve() err return

- Documentation/op-guide/supported-platform.md
@glevand It is OK to put you on arm64?
@luxas feel free you add yourself after this pr.
@Pensu, @bpradipt and @laboger feel free to add ppc64le
> doc: update platform.md

- compactor/compactor_test.go
Test ordering now similar to TestPeriodicPause
Fixes #6060
> compactor: fix race in TestPeriodic

- etcdserver/server_test.go
cf. https://semaphoreci.com/coreos/etcd/branches/master/builds/671
> etcdserver: don't race when waiting for store in TestSnapshot

- clientv3/integration/watch_test.go
- clientv3/op.go
- clientv3/watch.go
> clientv3: watch filters

- embed/config.go
- embed/etcd.go
- embed/serve.go
@xiang90 
This is for https://github.com/coreos/etcd/issues/6014
> embed: support registering client handlers

- raft/README.md
@heyitsanthony @philips @gyuho
> raft: better doc

- etcdserver/apply_auth.go
- etcdserver/server.go
- etcdserver/v3_server.go
Fixes #6010
/cc @mitake @gyuho @xiang90
> etcdserver: apply serialized requests outside auth apply lock

- Documentation/dev-internal/release.md
For https://github.com/coreos/etcd/issues/6049.
/cc @xiang90 @heyitsanthony
> dev-internal: update release note

- tools/functional-tester/etcd-tester/stresser.go
> etcd-tester: remove unnecessary arg from stresser

- etcdserver/server.go
- lease/lessor.go
- lease/lessor_test.go
/cc @xiang90 
Related to #6025
> etcdserver, lease: tie lease min ttl to election timeout

- clientv3/integration/watch_test.go
- clientv3/op.go
- clientv3/watch.go
> clientv3: add send created notification

- clientv3/watch.go
- proxy/grpcproxy/watch.go
- proxy/grpcproxy/watcher.go
- proxy/grpcproxy/watcher_groups.go
Fix https://github.com/coreos/etcd/issues/6012
> grpcproxy: handle create event

- pkg/transport/transport.go
> pkg/transport: update scheme to unix without copy

- raft/raft_test.go
there are still some places left behind needed to be fixed.
> raft: fix #6096

- tools/functional-tester/etcd-tester/stresser.go
For #6017.
@gyuho Can you get this merged and redeploy the testing cluster? Then we can get more info.
> tools/functional-tester: better logging

- Documentation/dev-guide/interacting_v3.md
Replace https://github.com/coreos/etcd/pull/5964.
Trying to clean up old PRs.
/cc @skyao @xiang90
> Documentation/dev-guide: add bash syntax to doc

- NEWS
For https://github.com/coreos/etcd/issues/6049.
> NEWS: add release notes for >v3.0.0 releases

- raft/raft.go
> raft: fix getting unapplied log entries

- clientv3/example_test.go
For https://github.com/coreos/etcd/issues/6148.
> clientv3: update base example with TLS

- rafthttp/http_test.go
- rafthttp/remote.go
- rafthttp/transport.go
- rafthttp/transport_test.go
From https://github.com/coreos/etcd/pull/6140.
/cc @xiang90 @heyitsanthony 
Thanks.
> rafthttp: add Transport.Cut/MendPeer

- raft/log.go
@xiang90 
For https://github.com/coreos/etcd/issues/6143
> raft: fix overflow

- etcdserver/stats/server.go
removed code duplicacy and improved readability
#6160
> etcdserver: stats/server - refactored

- etcdserver/apply.go
- integration/v3_grpc_test.go
Fix https://github.com/coreos/etcd/issues/6146
> etcdserver: fix wrong rev in header when nothing is actually got executed

- etcdserver/server.go
- integration/cluster.go
- integration/network_partition_test.go
For https://github.com/coreos/etcd/issues/4668.
> *: add network partition tests

- ROADMAP.md
> ROADMAP: update

- pkg/wait/wait_time.go
failing in CI: https://semaphoreci.com/coreos/etcd/branches/master/builds/775
> wait: make WaitTime robust against deadline collisions

- Documentation/docs.md
- Documentation/op-guide/clustering.md
- Documentation/op-guide/gateway.md
> docs: add gateway

- cmd/vendor/github.com/jonboulle/clockwork/clockwork.go
- etcdserver/api/v2http/client_test.go
- glide.lock
- glide.yaml
Address https://github.com/coreos/etcd/issues/4821#issuecomment-240258320.
> vendor: use v0.1.0 clockwork

- integration/cluster_proxy.go
```
=== RUN   TestElectionWait
Read at 0x00c420224f00 by goroutine 590:
runtime.mapaccess2_fast64()
/usr/local/go/src/runtime/hashmap_fast.go:147 +0x0
github.com/coreos/etcd/integration.newClientV3()
/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/integration/cluster_proxy.go:46 +0x146
github.com/coreos/etcd/integration.NewClientV3()
/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/integration/cluster.go:552 +0x23d
github.com/coreos/etcd/integration.makeClients.func1()
/home/gyuho/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/integration/v3_lock_test.go:181 +0x8e
github.com/coreos/etcd/integration.TestElectionWait.func1() …
```
> integration: fix race in setting shared proxies

- NEWS
> NEWS: add v3.0.5

- etcdserver/server.go
> etcdserver: improve logging for leadership transfer

- pkg/wait/wait_time.go
- pkg/wait/wait_time_test.go
> pkg/wait: don't expect time.Now() to be strict increasing in WaitTime tests

- .travis.yml
- build
> build: re-enable building outside gopath

- cmd/vendor/github.com/boltdb/bolt/freelist.go
- cmd/vendor/github.com/boltdb/bolt/node.go
- cmd/vendor/github.com/boltdb/bolt/page.go
- glide.lock
- glide.yaml
> vendor: boltdb/bolt v1.3.0 for Go 1.7

- rafthttp/pipeline_test.go
- rafthttp/stream.go
- rafthttp/stream_test.go
> rafthttp: remove WaitSchedule() from tests

- cmd/vendor/google.golang.org/grpc/call.go
- cmd/vendor/google.golang.org/grpc/clientconn.go
- cmd/vendor/google.golang.org/grpc/stream.go
- glide.lock
- glide.yaml
To fix https://github.com/coreos/etcd/issues/6221.
Any concern about backporting this to v3.0.x?
Thanks.
> vendor: update grpc/grpc-go for clientconn patch

- proxy/grpcproxy/cache/store.go
- proxy/grpcproxy/kv.go
> grpc-proxy: invalidate cache entries when there is a put/delete

- etcdserver/server.go
- etcdserver/v3_server.go
- pkg/wait/wait_time.go
- pkg/wait/wait_time_test.go
> etcdserver: add waitApplyIndex

- rafthttp/stream_test.go
> rafthttp: fix race in TestStreamWriterAttachOutgoingConn

- Documentation/dev-guide/local_cluster.md
It isn't clear where to start with these instructions, fix this.
> local_cluster: make it clear where Procfile is

- e2e/ctl_v3_auth_test.go
This commit adds a new test case for checking the permission mechanism
can work well in txn requests.
> e2e: a test case for txn and permission

- clientv3/op.go
For watch request
Otherwise, people have to search through our code base to find out the interval.
> clientv3: specify watch progress notify interval

- Documentation/libraries-and-tools.md
> documentation: update libraries-and-tools.md

- tools/functional-tester/etcd-tester/tester.go
> etcd-tester: fix compact rev counting

- etcdserver/server.go
kv.commit updates the consistent index in backend. When
executing in parallel with apply, it might grab tx lock
after apply update the consistent index and before apply
starts to execute the opeartion. If the server dies right
after kv.commit, the consistent is updated but the operation
is not executed. If we restart etcd server, etcd will skip
the operation. :(
There are a few other places that we need to take care of,
but let us fix this first.
> etcdserver: kv.commit needs to be serialized with apply

- mvcc/kvstore.go
What can happen before:
a. etcdserver.updateIndex(100) in applyEntryNormal.
b. mvcc.range -> saveIndex(100) [range can happen concurrently with applyAll]
---- (etcd can die right here) ----
c. mvcc.put -> saveIndex(100) foo -> bar
if etcd does not die after b, when we restart etcd we can see foo = bar
if etcd dies after b, when we restart etcd we will not see foo = bar. that is because after the restart, the consistent index is 100. etcd will skip apply mvcc.put at c.
> mvcc: only write txn should update index

- etcdctl/ctlv3/ctl.go
Fix https://github.com/coreos/etcd/issues/6233
/cc @gyuho @heyitsanthony
> etcdctl: list output options

- Documentation/op-guide/supported-platform.md
> Documentation: update links for unaligned 64-bit atomics issue

- clientv3/integration/kv_test.go
> clientv3/integration: fix TestKVPutStoppedServerAndClose

- etcdserver/v3_server.go
> etcdserver: use request timeout defined by ServerConfig for v3 requests

- tools/functional-tester/etcd-tester/tester.go
@gyuho this simple change wont work?
> etcd-tester: do not restart stresser on error

- tools/functional-tester/etcd-tester/tester.go
@xiang90 Can't remember what was wrong with printing? 
Is is other than printing the wrong number of compacting entries (already fixed)?
> etcd-tester: return error for mismatch rev/hash

- Documentation/op-guide/container.md
rel: #6177
cc: @gyuho @robszumski
> Documentation: Add initial etcd3 with rkt docs

- wal/doc.go
Corrected grammar mistake for doc.go
> wal: document grammar correction

- store/event_test.go
Test case added to check err handing for replaced entries.
#6255
> store: added missing test case scenerio for scan of de-queued entries

- Documentation/libraries-and-tools.md
Closing https://github.com/coreos/etcd/pull/6294.
/cc @CsatariGergely @xiang90 @heyitsanthony
> libraries-and-tools.md: add C++ client package

- e2e/etcd_release_upgrade_test.go
/cc @xiang90 
For https://github.com/coreos/etcd/pull/6309#issuecomment-243523255
> e2e: add 'TestReleaseUpgradeWithRestart'

- proxy/grpcproxy/watch.go
- proxy/grpcproxy/watcher_single.go
For https://github.com/coreos/etcd/pull/6188.
> grpcproxy: fix data race

- clientv3/watch.go
- integration/cluster_proxy.go
- proxy/grpcproxy/watch.go
- proxy/grpcproxy/watcher_groups.go
> grpcproxy: shutdown on client context cancel

- proxy/grpcproxy/watcher.go
- proxy/grpcproxy/watcher_group.go
- proxy/grpcproxy/watcher_groups.go
Several more tests can pass now.
> grpcproxy: fix more issues in watch path

- proxy/grpcproxy/watch.go
- proxy/grpcproxy/watcher_single.go
> grpcproxy: stop watchers in watch groups

- rafthttp/msg_codec.go
- rafthttp/msg_codec_test.go
Fix https://github.com/coreos/etcd/issues/5386.
> rafthttp: check decode size before buffer alloc

- Documentation/libraries-and-tools.md
Our team had a miscommunication.. ;(
I will give you back later to organize.
I am so sorry for wasting your time..
> libraries-and-tools.md: remove C++

- raft/raft.go
`rand.NewSource` creates a 4872 byte object. With a small number of raft
groups in a process this isn't a problem. With 10k raft groups we'd use
46MB for these random sources. The only usage is in
`raft.resetRandomizedElectionTimeout` which isn't performance critical.
Fixes #6347.
> raft: use a singleton global rand

- Documentation/dev-guide/interacting_v3.md
>  interacting_v3.md: fix typo

- embed/config.go
- integration/embed_test.go
> embed: reject domain names before binding

- raft/util_test.go
> raft: add tests for IsLocalMsg

- etcdctl/README.md
Corrected command in Readme.md
> etcdctl: Corrected command in Readme.md

- etcdserver/api/v3rpc/rpctypes/error.go
- etcdserver/api/v3rpc/util.go
> v3api, rpctypes: add ErrUnhealthy

- etcdctl/ctlv3/command/txn_command.go
> ctlv3: fix line parsing for Windows

- wal/wal.go
Found this while backporting WAL patches to release-3.0
> wal: simplify dir.Close call

- tools/functional-tester/README.md
update readme file to have the correct goreman command to start the functional tester locally.
> functional-tester: correct goreman command in readme

- Documentation/libraries-and-tools.md
Maybe not the best time to add this to doc, but we need to at last. @xiang90 ptal.
> update language bindings doc to add coreos/jetcd

- clientv3/concurrency/key.go
For https://github.com/coreos/etcd/issues/6366
> clientv3: return error from response when possible

- embed/config.go
- integration/embed_test.go
Revert and defang #6336 domain name listener lockout
> embed: warn on domain name in listener

- raft/rawnode.go
- raft/rawnode_test.go
Hi,
This PR adds read index(PR #5553) for RawNode, and test case.
> raft: add read index for RawNode

- contrib/recipes/rwmutex.go
- integration/v3_lock_test.go
> recipes: fix rwmutex locking

- clientv3/balancer.go
Fix the issue by adding a simple guard variable.
Fix #6395 
> clientv3: balancer panics when call up after close

- e2e/ctl_v3_snapshot_test.go
- e2e/etcd_test.go
Fix https://github.com/coreos/etcd/issues/6391.
> e2e: test snapshot restore

- version/version.go
> version: bump to 3.1.0-alpha.0

- etcdserver/api/capability.go
> api: update capability map

- etcdctl/README.md
Added the two flags:
1. dest-prefix
2. no-dest-prefix
which were added for feature make-mirror: modify/remove prefix in dest cluster
> etcdctlv3: updated readme for make-mirror: modify/remove prefix in dest cluster

- .travis.yml
`v3.1` release will be Go 1.7.x
> travis: test with Go 1.7.1

- Documentation/dev-guide/local_cluster.md
> doc: use 2379 as port of the first member in local cluster

- etcdserver/server.go
When 1000 leases expired at the same time, etcd takes more than 5 seconds to clean them. This means that even after the leases have expired, keys associated with leases are still accessible. I increase the deletion throughput by parallelizing leases deletion process.
change variable name and comment for easier read. Fix a race condition in the parallelized leases revoked logic.
> etcdserver: parallelize expired leases process

- tools/functional-tester/etcd-tester/checks.go
- tools/functional-tester/etcd-tester/main.go
- tools/functional-tester/etcd-tester/tester.go
> etcd-tester: split out consistency checking code from tester

- e2e/ctl_v3_make_mirror_test.go
e2e test case added for make-mirror modify dest prefix
> etcdctlv3: test case: make-mirror modify dest prefix

- e2e/ctl_v3_make_mirror_test.go
Added test case for make-mirror command for no-dest-prefix flag.
> etcdctlv3: test case: make-mirror no dest prefix

- etcdctl/README.md
- etcdctl/ctlv3/command/snapshot_command.go
updated readme.md for missing option
updated snapshot restore command usage
> etcdctlv3: updated snapshot restore options

- contrib/raftexample/README.md
> raftexample: remove snapshot TODO in README

- clientv3/balancer.go
- clientv3/client.go
- clientv3/config.go
Fix https://github.com/coreos/etcd/issues/5920.
> clientv3: add 'Sync' method

- etcdctl/README.md
added missing option for del command
> etcdctlv3: updated del command options

- tools/functional-tester/build
> 	functional-tester: build from repo root, vendor

- e2e/ctl_v3_make_mirror_test.go
Modified the test cases to remove code duplicity and to make it more orgainised,
> e2e: refactored ctlv3_make_mirror_test

- etcdctl/ctlv3/command/make_mirror_command.go
> etcdctl: remove the use of remprefix

- etcdctl/README.md
- etcdctl/ctlv3/command/member_command.go
updated member command options for member add and member update
> etcdctlv3: updated member command options

- etcdctl/README.md
- etcdctl/ctlv3/command/compaction_command.go
updated compaction options as per the doc format
> etcdctlv3: updated compaction options

- e2e/ctl_v3_kv_test.go
- etcdctl/ctlv3/command/del_command.go
TODO: added from-key flag for del command.
> etcdctlv3: del command from-key feature added

- etcdctl/README.md
1. added options for del command from-key
2. added example for from-key with prev-key
> etcdctlv3 : added options and examples for del from-key

- cmd/vendor/github.com/google/btree/btree.go
- glide.lock
- glide.yaml
Backporting some minor improvements in btree iteration + glide updates
/cc @xiang90 @heyitsanthony @fanminshi
> vendor: update 'google/btree'

- etcdctl/README.md
- etcdctl/ctlv3/command/role_command.go
- etcdctl/ctlv3/command/user_command.go
@xiang90 @gyuho @heyitsanthony I have completed the organisation of readme.md from my end. Request you to review the entire doc once and let me know if some changes are required, will try to fix it and make it complete in all aspects.
Thank you!
> etcdctlv3:corrected and organised etcdctl commands

- Documentation/dev-guide/interacting_v3.md
1. added version section
2. added put command lease example.
> etcdctlv3: interactive_v3 version and put command update

- Documentation/dev-guide/interacting_v3.md
1. made get command format uniform
2. Add get flags example for hex, from-key, print-value-only and limit
> etcdctlv3: interactive_v3 get command update

- Documentation/dev-guide/interacting_v3.md
added examples for del flags prev-kv, prefix and from-key
> etcdctlv3: interactive_v3 del command update

- Documentation/dev-guide/interacting_v3.md
added wtach command example for interactive, prev-kv, prefix and hex flags.
Corrected the format.
> etcdctlv3: interactive_v3 watch command update

- Documentation/dev-guide/interacting_v3.md
1. added note for compaction to give info about how to get revision in order to perform compaction operation.
2. Added timetolive operation command and its example.
> etcdctlv3: interactive_v3 compaction and timetolive command update

- raft/log_unstable_test.go
- raft/raft_test.go
Hi there,
This PR adds some test cases to improve the test coverage for raft.
> raft: add test cases to improve test coverage

- etcdctl/README.md
- etcdctl/ctlv3/command/put_command.go
1. updated put command flag and added example for it.
2. updated missing flag in make-mirror
> etcdctlv3: minor updates to put and make-mirror command

- wal/encoder.go
> wal: fix minor wording in comment

- etcdserver/v3_server.go
> etcdserver: use linearizableReadNotify for txn

- pkg/fileutil/fileutil.go
- pkg/flags/flag.go
- pkg/logutil/merge_logger_test.go
- pkg/netutil/netutil.go
- pkg/osutil/osutil.go
- pkg/pbutil/pbutil.go
Fix https://github.com/coreos/etcd/issues/6538
> pkg: use etcd as logging repo

- lease/lessor.go
- lease/lessor_test.go
> lease: remove redundant lookup methods

- lease/lessor.go
Fixes #6558
/cc @fanminshi @gyuho
> lessor: delete keys in deterministic order on revoke

- etcdserver/server_test.go
> etcdserver: use stream recorder for TestPublishRetry

- etcdserver/api/capability.go
- etcdserver/api/v2http/http.go
- etcdserver/api/v2http/httptypes/errors.go
- etcdserver/api/v3rpc/grpc.go
- etcdserver/api/v3rpc/key.go
- etcdserver/auth/auth.go
- etcdserver/membership/member.go
- etcdserver/stats/stats.go
- mvcc/backend/backend.go
- proxy/httpproxy/reverse.go
- proxy/tcpproxy/userspace.go
> *: set repo correctly for logging

- Documentation/dl_build.md
Fix https://github.com/coreos/etcd/issues/6526
> doc: build should work for non-github users

- etcdctl/ctlv3/command/lock_command.go
> etcdctl: remove superfluous session in lock command

- etcdserver/raft.go
- etcdserver/server.go
- lease/lessor.go
- lease/lessor_test.go
> Fix lease expire

- test
I split these two patches out from https://github.com/coreos/etcd/pull/6486.
> test: Run integration pass in series

- etcdserver/api/v3rpc/key.go
> v3rpc: return nil as error explicitly

- NEWS
> NEWS: add 'prev-kv' feature for upcoming v3.0.11

- Documentation/docs.md
- Documentation/op-guide/grpc_proxy.md
> doc: add grpc proxy doc

- tools/functional-tester/etcd-runner/main.go
#6584
@xiang90 i have added the feature for watch runner.
Have a few queries:
1. Whether any of the parameter in runWatcher needs to be created as flag?
2. If required the test can be modified to make putting of keys and reading on the watcher concurrent.
Thank you!
> etcd-runner:added watch runner

- tools/functional-tester/etcd-tester/checks.go
- tools/functional-tester/etcd-tester/cluster.go
- tools/functional-tester/etcd-tester/lease_stresser.go
- tools/functional-tester/etcd-tester/main.go
- tools/functional-tester/etcd-tester/tester.go
Add lease stresser to test lease code under stress and etcd failures
resolve #6380
> functional-tester: add lease stresser

- raft/README.md
> Update README to explain starting a single node cluster and joining it.

- etcdctl/README.md
add missing prompts for interactive txn command.
> etcdctlv3: update txn interactive command output

- raft/README.md
Because Dgraph is a notable user of RAFT.
> raft: Add dgraph to the list of users

- scripts/build-binary
> release: build binary without symbols for debug

- tools/functional-tester/etcd-runner/main.go
> etcd-runner: make run watcher fail safe

- build.ps1
> build: add option to enable binaries stripping for windows

- e2e/ctl_v3_alarm_test.go
Fix https://github.com/coreos/etcd/issues/6677.
I can reproduce the failure pretty easily.
It fails when the available quota is X, and
the compact rev is not recent enough to make
free space.
It can happen because we set the db size periodically
whenever commit happens in mvcc side. Quota layer's
db size might be stale if the commit hasn't happened
recently.
@xiang90
> e2e: compact with latest rev in alarm test

- Documentation/v2/admin_guide.md
I have no idea what NB means but just change it to Note
> Documentation: admin guide remove NB

- .travis.yml
> travis: test with Go 1.7.3

- tools/functional-tester/etcd-tester/lease_stresser.go
only renew a lease if the lease is present.
> functional-tester: modify lease renew logic

- mvcc/key_index_test.go
- mvcc/kvstore_compaction_test.go
- mvcc/kvstore_test.go
- rafthttp/urlpick_test.go
@xiang90 
https://travis-ci.org/coreos/etcd/jobs/169379033
> *: fix gofmt issues with go tip

- tools/functional-tester/etcd-runner/main.go
made watcher runner respect the round functionality
> etcd-runner: watcher runner respect rounds

- clientv3/doc.go
> clientv3: Fix URL to rpc errors

- Documentation/libraries-and-tools.md
> Add etcd client for Nim

- tools/functional-tester/etcd-runner/main.go
> etcd-runner: Added connection timeout flag for client

- tools/functional-tester/etcd-runner/main.go
> etcd-runner: fix typo in round prefix

- tools/functional-tester/etcd-tester/checks.go
- tools/functional-tester/etcd-tester/lease_stresser.go
functional-tester: add retries to hash checking
allows hashes to converge through retrying.
> Lease hash fix

- clientv3/integration/watch_test.go
- clientv3/watch.go
Fix https://github.com/coreos/etcd/issues/6606
Send create response over to outc instead of keeping it on ws.buf
@heyitsanthony
> clientv3: send create event over outc

- tools/functional-tester/etcd-tester/tester.go
The current tester doesn't not clean up if any of the failure injection/recovery fails. if tester fails to recover a dead node, tester hangs in the next round because the tester will keep waiting until cluster becomes healthy which is impossible since a node is down. To fix this issue, we will always clean up if any error happens during each round so that cluster will be healthy for next round.
FIX #6743
> functional-tester: always clean up if tester encouters an error

- clientv3/example_metrics_test.go
> clientv3: added example for client metrics

- contrib/recipes/barrier.go
- contrib/recipes/double_barrier.go
- contrib/recipes/key.go
- contrib/recipes/priority_queue.go
- contrib/recipes/queue.go
- contrib/recipes/rwmutex.go
> contrib/recipes: unexport and clean up keys.go

- tools/functional-tester/etcd-tester/tester.go
simple fix for wrongly printed statement.
> functional-tester: fix log statement

- clientv3/integration/watch_test.go
It's possible the put will not propagate to all members before removing quorum,
causing watches on the key to wait forever.
Fixes #6386
> integration: put key on watch target member for TestWatchWithRequireLeader

- tools/functional-tester/etcd-runner/election.go
- tools/functional-tester/etcd-runner/lease_renewer.go
- tools/functional-tester/etcd-runner/lock_racer.go
- tools/functional-tester/etcd-runner/main.go
- tools/functional-tester/etcd-runner/watcher.go
replace #6735 
I got some time today to clean up runner code. I feel this is cleaner than 6735.
PTAL /cc @heyitsanthony @sinsharat
> etcd-runner: refactor code structure and flag cleanup

- pkg/stringutil/stringutil.go
- tools/functional-tester/etcd-runner/watcher.go
> etcd-runner: move string generation to pkg/stringutil

- tools/functional-tester/etcd-tester/checks.go
- tools/functional-tester/etcd-tester/cluster.go
- tools/functional-tester/etcd-tester/failure.go
- tools/functional-tester/etcd-tester/key_stresser.go
- tools/functional-tester/etcd-tester/lease_stresser.go
- tools/functional-tester/etcd-tester/main.go
- tools/functional-tester/etcd-tester/member.go
- tools/functional-tester/etcd-tester/stresser.go
- tools/functional-tester/etcd-tester/tester.go
- tools/functional-tester/etcd-tester/util.go
- tools/functional-tester/etcd-tester/v2_stresser.go
Spent my flight fighting the entropy around this code.
> etcd-tester: refactor stresser / checker management

- etcdserver/raft.go
- etcdserver/raft_test.go
- etcdserver/server.go
- etcdserver/server_test.go
Clear 'TODO'
/cc @xiang90 @heyitsanthony @fanminshi
> etcdserver: move 'EtcdServer.send' to raft.go

- clientv3/integration/watch_test.go
because clientv3.Close won't trigger it any more
clientv3.Close just closes watch client
instead of closing grpc connection
> clientv3/integration: close active connection to get ErrClientConnClosing

- proxy/grpcproxy/watch_client_adapter.go
> grpcproxy: add SetHeader support to ServerStream

- tools/functional-tester/etcd-tester/checks.go
- tools/functional-tester/etcd-tester/lease_stresser.go
move the logic of waiting lease expired from stresser to checker
> etcd-tester: refactor checking short lived lease logic

- store/event_history.go
Fix https://github.com/coreos/etcd/issues/6328
> store: do not modify key during scanning

- etcdctl/ctlv2/command/cluster_health.go
- etcdctl/ctlv2/command/error.go
- etcdctl/ctlv2/command/exec_watch_command.go
- etcdctl/ctlv2/command/get_command.go
- etcdctl/ctlv2/command/ls_command.go
- etcdctl/ctlv2/command/mk_command.go
- etcdctl/ctlv2/command/mkdir_command.go
- etcdctl/ctlv2/command/rm_command.go
- etcdctl/ctlv2/command/rmdir_command.go
- etcdctl/ctlv2/command/set_command.go
- etcdctl/ctlv2/command/update_command.go
- etcdctl/ctlv2/command/update_dir_command.go
- etcdctl/ctlv2/command/util.go
- etcdctl/ctlv2/command/watch_command.go
Fix https://github.com/coreos/etcd/issues/5970.
> etcdctl/ctlv2: error handling with JSON

- etcdserver/server.go
Fix #6750 
```
2016-11-01 17:54:19.573561 I | embed: listening for peers on http://127.0.0.1:2377
2016-11-01 17:54:19.573617 I | embed: listening for client requests on 127.0.0.1:2378
2016-11-01 17:54:20.575101 W | etcdserver: another etcd process is running with the same data dir and holding the file lock.
2016-11-01 17:54:20.575232 W | etcdserver: waiting for it to exit before starting...
```
> etcdserver: print out warning when waiting for file lock

- clientv3/README.md
> clientv3: updated doc for metric support

- auth/store.go
- auth/store_test.go
- etcdserver/api/v3rpc/rpctypes/error.go
- etcdserver/api/v3rpc/util.go
> auth, etcdserver: forbid adding a user with empty name

- lease/leasehttp/http.go
- lease/leasehttp/http_test.go
@xiang90 @heyitsanthony @fanminshi
> leasehttp: use graceful close, add tests, remove TODO

- etcdctl/README.md
- etcdctl/ctlv3/command/user_command.go
> etcdctl/ctlv3: clarify 'user add' argument (user:password)

- Documentation/metrics.md
- etcdserver/api/v3rpc/interceptor.go
- etcdserver/api/v3rpc/metrics.go
> v3rpc: add 'active' gRPC streamsGauge

- raft/rafttest/network.go
- raft/rafttest/node.go
- raft/rafttest/node_test.go
Fix https://github.com/coreos/etcd/issues/6290
> rafttest: make raft test reliable

- proxy/grpcproxy/kv.go
If the txn comparison block makes claims about a key's current
state, then it may say a key has been updated. Future range/txn
operations may expect this update to eventually be propagated through
the cluster and show up in serialized requests. To avoid spinning
forever on txn/serialized range loops, invalidate the comparison keys.
> grpcproxy: invalidate comparison keys after txn

- raft/raft.go
- raft/raft_test.go
If MsgTimeoutNow arrived after a node was removed, the node could start
and win an election, then panic in becomeLeader (see
cockroachdb/cockroach#8535)
> raft: Check promotable() in MsgTimeoutNow handling

- Documentation/op-guide/clustering.md
- clientv3/integration/metrics_test.go
Closing https://github.com/coreos/etcd/pull/6777 and some minor cleaning from https://goreportcard.com/report/github.com/coreos/etcd#misspell. 
@xiang90 @heyitsanthony
> *: fix minor typos, styles

- tools/functional-tester/etcd-tester/key_stresser.go
- tools/functional-tester/etcd-tester/lease_stresser.go
- tools/functional-tester/etcd-tester/stresser.go
- tools/functional-tester/etcd-tester/tester.go
- tools/functional-tester/etcd-tester/v2_stresser.go
functional tester sometime experiences timeout during compaction phase. I crease the timeout limit.
FIX #6805
> etcd-tester: increase compaction timeout limit

- proxy/grpcproxy/cache/store.go
- proxy/grpcproxy/kv.go
Fixes more hangs in TestSTMConflict.
> grpcproxy: update cache based on txn response

- Documentation/op-guide/grpc_proxy.md
/cc @gyuho @heyitsanthony @fanminshi
> doc: add gRPC proxy start doc

- tools/functional-tester/etcd-runner/watcher.go
> etcd-runner: clean up watcher runner

- NEWS
Did some cleaning, and also for tomorrow
@heyitsanthony @xiang90 @fanminshi
> NEWS: update with v3.0.15

- tools/benchmark/cmd/watch_latency.go
> benchmark: added watch-latency

- proxy/grpcproxy/watch.go
- proxy/grpcproxy/watch_broadcast.go
- proxy/grpcproxy/watcher.go
> grpcproxy: support prevKV watcher

- mvcc/index.go
- mvcc/kvstore.go
- mvcc/kvstore_bench_test.go
- mvcc/kvstore_test.go
#5317 
@xiang90 Currently i have commented the test cases. Will fix all the test cases and also add the benchmark test case for this in this PR. There are too many test cases dependent on this. Will start fixing them one by one.
Thank you!
> mvcc: store.restore taking too long triggering snapshot cycle fix

- pkg/netutil/isolate_linux.go
- pkg/netutil/routes_linux.go
- pkg/netutil/routes_linux_test.go
Fix https://github.com/coreos/etcd/issues/6841.
@heyitsanthony @xiang90 @fanminshi
> pkg/netutil: get default interface for tc commands

- Documentation/dev-guide/api_grpc_gateway.md
- e2e/v2_curl_test.go
- e2e/v3_curl_test.go
- etcdserver/api/v3rpc/watch.go
- integration/v3_watch_test.go
WIP until grpc-gateway side fixes get in
> Documentation: add grpc gateway watch example

- etcdmain/grpc_proxy.go
Broken. WIP.
Just testing to see what happens in grpcproxy tests.
> etcdmain: add '/metrics' HTTP/1 path to grpc-proxy

- raft/node_test.go
Only send signal after applying conf change.
Or deadlock might happen if raft node receives
ready without conf change when the test server
is slow.
> raft: fix TestNodeProposeAddDuplicateNode

- Documentation/op-guide/monitoring.md
> Documentation/op-guide: add notes about 'datasource' in Prometheus

- clientv3/client.go
Fix https://github.com/coreos/etcd/issues/6892.
@xiang90 @fanminshi
> clientv3: return copy of endpoints, not pointer

- client/README.md
> client: update README about health monitoring

- integration/v3_grpc_test.go
Proxy client layer ignores call options so Put is always FailFast.
Tried adding WithCallOptions as a client OpOption to do CallOption passthrough but the change set was larger than what seemed reasonable to support essentially a testing path.
> integration: use Range to wait for reboot in quota tests

- store/store_test.go
> store: check sorted order in TestStoreGetSorted

- tools/functional-tester/etcd-agent/agent.go
- tools/functional-tester/etcd-tester/checks.go
- tools/functional-tester/etcd-tester/lease_stresser.go
- tools/functional-tester/etcd-tester/tester.go
Move few checking logic from lease stresser to lease checker and change connection logic for lease stresser and checker
> etcd-tester: refactor lease checker

- proxy/grpcproxy/metrics.go
- proxy/grpcproxy/watch_broadcast.go
> grpcproxy: add richer metrics for watch

- proxy/grpcproxy/cache/store.go
- proxy/grpcproxy/kv.go
- proxy/grpcproxy/metrics.go
Fix https://github.com/coreos/etcd/issues/6917
> grpcproxy: add cache related metrics

- tools/benchmark/cmd/put.go
/cc @heyitsanthony for gRPC watch benchmark
> banchmark: add rate limit

- Documentation/docs.md
- Documentation/faq.md
/cc @heyitsanthony @joshix 
Create an initial page for faq. We should start to collect them, so that we can simply point people to this page instead of repeating the answers again and again.
> doc: initial faq

- Documentation/faq.md
@xiang90 @heyitsanthony @fanminshi 
Will add more after these.
Thanks
> Documentation: add more FAQ questions

- etcdserver/server.go
- pkg/mock/mockstore/store_recorder.go
- store/store.go
> etcdserver: only send v2 sync if ttl keys exist

- Documentation/dev-guide/interacting_v3.md
> Documentation: update get examples to be clearer about ranges

- embed/etcd.go
- embed/serve.go
- etcdserver/api/v2http/client.go
- etcdserver/config.go
- etcdserver/server.go
Seems like a better place for prof setup since it's not specific to v2.
> etcdserver, embed, v2http: move pprof setup to embed

- Documentation/faq.md
Fix https://github.com/coreos/etcd/issues/6968
/cc @heyitsanthony @gyuho @johnnyluo586
> doc: add faq about apply warning logging

- Documentation/faq.md
Fix https://github.com/coreos/etcd/issues/6955
/cc @gyuho @heyitsanthony
> doc: add faq about missing heartbeat

- auth/store.go
- e2e/ctl_v3_auth_test.go
- etcdserver/api/v3rpc/interceptor.go
- integration/v3_watch_test.go
- proxy/grpcproxy/watch_broadcast.go
- raft/raft_test.go
- raft/rawnode_test.go
- test
- tools/etcd-dump-db/main.go
- tools/functional-tester/etcd-agent/main.go
- tools/functional-tester/etcd-tester/key_stresser.go
- tools/functional-tester/etcd-tester/v2_stresser.go
> *: fix 'gosimple', 'gounused' checks

- etcdctl/ctlv3/command/printer.go
- etcdctl/ctlv3/ctl.go
Writes out fields from responses in the format "FieldName" : FieldValue. If FieldValue is a string, it is formatted with %q.
> etcdctl: "fields" output formats

- build
using `-r` flag when remove a directory.
> build: remove dir use -r flag

- tools/functional-tester/etcd-tester/main.go
Useful for debugging issues like https://github.com/coreos/etcd/pull/6994.
> etcd-tester: add 'enable-pprof' option

- Documentation/docs.md
- Documentation/op-guide/hardware.md
> doc: add hardware section

- auth/range_perm_cache.go
- auth/range_perm_cache_test.go
> auth: improve 'removeSubsetRangePerms' to O(n)

- Documentation/op-guide/clustering.md
> op-guide/clustering: fix typo

- clientv3/client.go
> clientv3: close Lease on client Close

- Documentation/faq.md
> Documentation: FAQ entry for cluster ID mismatches

- etcdctl/ctlv3/command/migrate_command.go
> etcdctl: warn when backend takes too long to open on migrate

- raft/storage.go
> raft: make memory storage set method thread safe

- tools/functional-tester/etcd-tester/checks.go
- tools/functional-tester/etcd-tester/lease_stresser.go
To help debug issues like https://github.com/coreos/etcd/issues/7052
/cc @fanminshi
> etcd-tester: fix typo, add endpoint in logs

- raft/raft_test.go
Hi,
This PR fixes a few test cases for the pre-vote feature.
> raft: fix pre-vote tests

- etcdserver/config.go
- etcdserver/config_test.go
- etcdserver/membership/cluster.go
- pkg/netutil/netutil.go
- pkg/netutil/netutil_test.go
> retry on resolution failure for advertised peer DNS check

- e2e/ctl_v3_endpoint_test.go
- etcdctl/ctlv3/command/ep_command.go
Relaxes the permission expectations for endpoint health by noting:
* permission denial on linearized reads is always through consensus
* endpoint health means consensus with the cluster through the endpoint
So, there's no need to require permission on a health check key in order
to know whether the endpoint is healthy.
Fixes #7075
/cc @mitake
> etcdctl: treat permission denied as healthy endpoint

- e2e/ctl_v2_test.go
- etcdserver/api/v2http/client.go
Removing the periodic SYNC calls broke the health endpoint since the
raft index stops updating. Instead, if there is no activity after 250ms, issue
a QGET to force some raft traffic.
Fixes #6985
> v2http: submit QGET in health endpoint if no progress

- lease/lessor.go
Demote was racing on expiry when LeaseTimeToLive called Remaining. Replace
with intrinsics since the ordering isn't important, but torn writes are
bad.
```
Write at 0x00c42ceda888 by goroutine 446:
github.com/coreos/etcd/lease.(*lessor).Demote()
/home/anthony/go/src/github.com/coreos/etcd/lease/lessor.go:348 +0x12a
github.com/coreos/etcd/etcdserver.(*EtcdServer).run.func3()
/home/anthony/go/src/github.com/coreos/etcd/etcdserver/server.go:630 +0x264
github.com/coreos/etcd/etcdserver.(*raftNode).start.func1()
/home/anthony/go/src/github.com/coreos/etcd/etcdserver/raft.go:165 +0xfdd
Previous read at 0x00c42ceda888 by goroutine 365:
github.com/coreos/etcd/lease.(*Lease).Remaining()
/home/anthony/go/src/github.com/coreos/etcd/lease/lessor.go:554 +0x4a …
```
> lease: use atomics for accessing lease expiry

- e2e/etcd_release_upgrade_test.go
Fix https://github.com/coreos/etcd/issues/7065.
> e2e: poll '/version' in release upgrade tests

- etcdserver/raft.go
- etcdserver/server.go
> etcdserver: consistent naming in raftReadyHandler

- pkg/testutil/leak.go
- test
> coverage: rework coverage for unit and integration tests

- etcdmain/grpc_proxy.go
- integration/cluster_proxy.go
- integration/v3_watch_test.go
- proxy/grpcproxy/watch.go
> integration: wait for watch proxy to finish on client close

- etcdserver/server.go
> etcdserver: resume compactor only if leader

- etcdserver/api/v3rpc/rpctypes/error.go
- etcdserver/api/v3rpc/util.go
Fix https://github.com/coreos/etcd/issues/7072.
I only tested manually. And works.
> etcdserver: expose ErrMemberNotEnoughStarted

- proxy/grpcproxy/watch.go
If client closes but all watch streams are not canceled, the outstanding
watch will wait until it is canceled, causing watch server to potentially
wait forever to close.
Fixes #7102
> grpcproxy: tear down watch when client context is done

- pkg/expect/expect.go
Dump process output to stdout when EXPECT_DEBUG != "".
> expect: EXPECT_DEBUG environment variable

- Documentation/learning/why.md
explain the meaning behind the term etcd.
> why: add origin of the term etcd

- raft/raft_test.go
Hi,
This PR fixes a test case for #7042 
PTAL
> raft: fix test cases for #7042

- raft/node_test.go
- raft/rawnode_test.go
Hi,
This PR adds the test case in #6866 for RawNode.
> raft: add RawNode test case for #6866

- etcdctl/ctlv3/command/auth_command.go
Kind of tedious to add the root role when enabling auth; can just add
it automatically.
/cc @mitake
> etcdctl: create root role on auth enable if it does not yet exist

- Documentation/libraries-and-tools.md
Added load test tool reference for etcd version 3.0 and above.
> tools: Add etcd 3.0 load test tool refernece

- clientv3/balancer_test.go
minor balancer test logic fix.
> clientv3: fix balancer test logic

- clientv3/lease.go
Would cause the keepalive loop to cancel out.
Why was it doing this in the first place? Who knows!
Fixes #7082
> clientv3: don't reset stream on keepaliveonce or revoke failure

- etcdserver/api/capability.go
- rafthttp/stream.go
Fix https://github.com/coreos/etcd/issues/7152
> etcdserver/api, rafthttp: add version v3.2

- etcdctl/README.md
- etcdctl/ctlv3/command/member_command.go
Replace https://github.com/coreos/etcd/pull/7050.
> ctlv3: print cluster info after adding new member

- clientv3/balancer.go
- clientv3/balancer_test.go
> clientv3: balancer uses one connection at a time

- etcdserver/v3_server.go
> etcdserver: use ReqTimeout for linearized read

- clientv3/txn.go
fixes TODO : 
clientv3/txn.go:      // TODO: add a Do for shortcut the txn without any condition
> clientv3/txn.go : removed the TODO: add a Do for shortcut the txn without any condition

- NEWS
Fix wrong date for tomorrow release
> NEWS: fix date for v3.1 release

- Documentation/dl_build.md
It's even easier now.
/cc @ibmendoza
> documentation: update build documentation

- ROADMAP.md
/cc @gyuho @heyitsanthony @fanminshi
> roadmap: update roadmap

- clientv3/concurrency/stm.go
- integration/v3_stm_test.go
- tools/benchmark/cmd/stm.go
Changes include:
* Revamp of NewSTM interface with variadic options.
* Bulk Get()
* Prefetch support
* Snapshot level isolation
Fixes #6923
> STM: prefetch and more

- contrib/recipes/key.go
fixed comment in method newSequentialKV
> contrib/recipes/key.go : fixed comment in method newSequentialKV

- Documentation/libraries-and-tools.md
Added a C library for etcd in the list of available libraries.
Also added Apache Celix as a project which is using etcd.
> Documentation: C library added

- Documentation/libraries-and-tools.md
Project [scrz](https://github.com/scrz/scrz) does not exist anymore.
> Documentation: Deleted non-existing project from libraries-and-tools.md

- clientv3/balancer.go
- clientv3/integration/dial_test.go
> clientv3: fix balancer update address bug

- contrib/README.md
- contrib/systemd/etcd3-multinode/README.md
Fix https://github.com/coreos/etcd/issues/5971
/cc @xiang90
> contrib: add etcd cluster deploy on systemd docs

- auth/store_test.go
This covers tests for User and Role related operations. This tests brings code coverage in store.go from 40.2% to 72.3%.
/cc @mitake
> auth: Adding unit tests

- clientv3/concurrency/session.go
- integration/v3_election_test.go
This change is needed to handle process restarts with elections. When the
leader process is restarted, it should be able to hang on to the leadership
by using the existing lease.
Fixes #7166
> clientv3: start a session with existing lease

- auth/store_test.go
This covers unit-test for AuthStore.IsAdminPermitted in store.go
\cc @mitake @xiang90
> auth: test for AuthStore.IsAdminPermitted

- clientv3/client.go
- clientv3/config.go
- clientv3/example_metrics_test.go
- clientv3/integration/metrics_test.go
Removes strict prometheus dependency.
Fixes #7058
> clientv3: add DialOptions to config

- pkg/report/timeseries.go
- pkg/report/timeseries_test.go
For https://github.com/coreos/dbtester/issues/221.
> pkg/report: add min/max latency per second

- scripts/build-binary
This PR is for building ppc64le binary for release.
> scripts: Add support to build ppc64le binary for release

- clientv3/integration/lease_test.go
> clientv3/integration:  stop member before keepalive in TestLeaseKeepAliveInitTimeout

- Documentation/v2/proxy.md
Fix a command error:
`- px | grep etcd`
`+ ps | grep etcd`
Signed-off-by: CUI Wei <ghostplant@qq.com>
> Fix a command error.

- Documentation/dev-guide/api_reference_v3.md
- clientv3/op.go
- etcdserver/etcdserverpb/rpc.pb.go
- etcdserver/etcdserverpb/rpc.proto
> etcdserverpb, clientv3: clarify WithLimit documentation

- Documentation/op-guide/runtime-configuration.md
> op-guide: fix remove instructions in runtime-configuration and conform to style

- proxy/grpcproxy/leader.go
Leadership timeout can sometimes take too long, such as in test cases.
However, it is possible to infer a leader is available based on RPCs
that must go through consensus. Therefore, have a way to update the
leadership status off the watch path.
/cc @fanminshi
> grpcproxy: support forcing leader as available

- clientv3/lease.go
Sorry. My git push failed. I did not notice that. Fix this again.
/cc @gyuho
> clientv3: fix lease keepalive duration

- e2e/etcd_spawn_cov.go.go
- e2e/etcd_spawn_nocov.go
- e2e/etcd_test.go
- etcdmain/config.go
- main_test.go
- pkg/expect/expect.go
- test
> e2e: add code coverage to e2e

- raft/raft_test.go
Hi,
This PR revises the case case and fixes a typo in #7331
> raft: revise test case and fix typo

- pkg/netutil/routes_linux.go
Was non-deterministic.
/cc @felixoid
> netutil: use ipv4 host by default

- clientv3/integration/watch_test.go
> integration: permit background watch streams in TestWatchCancelOnServer

- proxy/grpcproxy/logger.go
- proxy/grpcproxy/register.go
- proxy/grpcproxy/register_test.go
For #6902.
To get 'Register' part reviewed first.
Will add auto-sync part in later PRs.
> grpcproxy: add 'register' address

- e2e/etcd_spawn_cov.go
Wasn't compiling.
/cc @fanminshi
> e2e: fix -tags cov builds

- Documentation/op-guide/grpc_proxy.md
Trying to clear out doc TODO's.
/cc @fanminshi
> Documentation: add documentation for grpc lease stream coalescing

- integration/cluster.go
- integration/cluster_test.go
The issue is caused by leader loss even after waitLeader() returns
which can happen if the test machine is flaky which triggers a leader loss
or the killed node is the leader since waitLeader() only scans followers in
TestRestartMember() and they can have the same older leader.
In those cases, clusterMustProgress() proceeds with no leader which triggers
the no leader error.
To get around that, use linearizable get in waitLeader() to ensure leader is up
and retries on kapi.create() in clusterMustProgress() to ensure it proceeds with
a leader.
FIX #7258
> integration: integration: ensure leader is up in waitLeader() and clusterMustProgress()

- e2e/etcd_spawn_cov.go
- e2e/etcd_spawn_nocov.go
- e2e/etcd_test.go
- etcdctl/ctlv2/ctl.go
- etcdctl/ctlv2/ctl_cov.go
- etcdctl/ctlv2/ctl_nocov.go
- etcdctl/ctlv3/ctl.go
- etcdctl/ctlv3/ctl_cov.go
- etcdctl/ctlv3/ctl_nocov.go
- etcdctl/main_test.go
- test
> e2e: rework coverage ctl

- Documentation/op-guide/container.md
For https://github.com/coreos/etcd/pull/7399.
/cc @xiang90 @heyitsanthony @fanminshi
> op-guide: add notes on mounting certs directory

- clientv3/example_test.go
> clientv3: bump example requestTimeout for slow CI

- etcdctl/ctlv2/ctl.go
- etcdctl/main.go
> etcdctl: show warning if ETCDCTL_API is not set

- Documentation/tuning.md
Also cleaned up tuning.md newlines to conform with style.
> Documentation: suggest ionice for disk tuning

- etcdctl/ctlv3/command/make_mirror_command.go
> etcdctl: correctly batch revisions in make-mirror

- etcdserver/api/capability.go
- integration/cluster.go
> api: default to V3 capability

- etcdctl/README.md
If the added newline on the last line is a problem, let me know and I'll get rid of it.
> etcdctl: Fix migrate example in README.md

- clientv3/clientv3util/util.go
This is quite useful for transactions.
> clientv3: Add KeyExists and KeyNotExists Cmp helpers

- .github/ISSUE_TEMPLATE.md
- CONTRIBUTING.md
- Documentation/benchmarks/etcd-2-2-0-rc-memory-benchmarks.md
- Documentation/op-guide/container.md
- Documentation/platforms/freebsd.md
- Documentation/production-users.md
- Documentation/upgrades/upgrade_3_0.md
- README.md
- contrib/raftexample/README.md
- contrib/systemd/etcd2-backup-coreos/README.md
- etcdctl/READMEv2.md
- hack/insta-discovery/README.md
- hack/tls-setup/README.md
- raft/README.md
- test
- tools/functional-tester/README.md
Per https://github.com/coreos/docs/blob/master/STYLE.md#eschew-you
> test: eschew you

- Documentation/production-users.md
>  Documentation: add PD to production users

- Documentation/production-users.md
add qingcloud to production user
> Documentation: add qingcloud to production user

- Documentation/production-users.md
> doc: add usecase of qiniu

- Documentation/production-users.md
> doc: add new usecase of qiniu

- Documentation/production-users.md
Added Yandex to the list of production users.
> Documentation: add production user

- Documentation/production-users.md
> Add Tencent Games user case

- Documentation/production-users.md
It would be our pleasure to be listed as a production user
> Add hyper.sh to production users

- Documentation/production-users.md
> Add use case in Meitu Inc.

- Documentation/dev-internal/release.md
For https://github.com/coreos/etcd/issues/7449
> Documentation: sign source zip files

- Documentation/production-users.md
> Documentation: add Grab etcd use case

- e2e/ctl_v3_auth_test.go
- e2e/ctl_v3_member_test.go
- e2e/ctl_v3_test.go
> e2e: don't remove member used to connect to etcd cluster

- Documentation/op-guide/grpc_proxy.md
- clientv3/naming/grpc.go
- etcdmain/grpc_proxy.go
- proxy/grpcproxy/cluster.go
- proxy/grpcproxy/cluster_test.go
- proxy/grpcproxy/register.go
- proxy/grpcproxy/register_test.go
Fix https://github.com/coreos/etcd/issues/6902
> *: register grpc-proxy members

- Documentation/production-users.md
Signed-off-by: allencloud <allen.sun@daocloud.io>
add a production user DaoCloud to Documentation/production-users.md
> add production user daocloud

- Documentation/production-users.md
Cherry-picking https://github.com/coreos/etcd/pull/7427.
Some diffs just cleans up trailing whitespace.
> Documentation: add huawei product user

- clientv3/balancer.go
- clientv3/balancer_test.go
> clientv3: serialize updating notifych in balancer

- Documentation/production-users.md
> doc: add Baidu Waimai

- Documentation/production-users.md
> doc: fix title size

- Documentation/production-users.md
> doc: add branch.io use case into production users

- Documentation/op-guide/gateway.md
Update from single available endpoint to round robin.
> op-guide: update gateway routing policy

- Documentation/learning/api.md
- Documentation/learning/api_guarantees.md
> doc/learning: complete the api guide

- integration/v3_lock_test.go
TestMutexWaitsOnCurrentHolder ensures a series of waiters
obtain lock only after the previous lock requests are gone.
> integration: add TestMutexWaitsOnCurrentHolder test

- etcdserver/api/v3client/doc.go
- etcdserver/api/v3client/v3client.go
> v3client: add example and godoc New

- etcdserver/raft.go
- etcdserver/raft_test.go
- etcdserver/server.go
Fix https://github.com/coreos/etcd/issues/7280
/cc @siddontang
> etcdserver: candidate should wait for applying all configuration changes

- clientv3/balancer.go
- clientv3/integration/dial_test.go
> clientv3/balancer: update eps if pinAddr is not included in updateAddrs

- embed/etcd.go
- embed/serve.go
- integration/embed_test.go
> embed: don't return error when closing on embed etcd

- etcdserver/membership/cluster.go
- pkg/report/timeseries.go
seeing on https://travis-ci.org/coreos/etcd/jobs/213115154
> *: fix gosimple warning for fmt.Sprintf("%s")

- etcdserver/v3_server.go
Needed for 3.0->3.1. Not needed for 3.1->3.2
> etcdserver: remove legacy range/txn

- mvcc/backend/backend.go
> backend: add FillPercent option

- .travis.yml
Fix https://github.com/dominikh/go-tools/issues/76.
See https://github.com/dominikh/go-tools/issues/76#issuecomment-288189194.
> travis: always 'go get -u' in 'before_install'

- Documentation/benchmarks/etcd-2-1-0-alpha-benchmarks.md
> etcd-2-1-0-bench: Fix an absolute bare link to resource outside of Doc dir

- clientv3/client_test.go
hit a leak failure https://semaphoreci.com/coreos/etcd/branches/pull-request-7549/builds/4
> clientv3: wait for Get goroutine in TestDialCancel

- Documentation/production-users.md
> add Salesforce to prod users

- pkg/adt/interval_tree.go
- pkg/adt/interval_tree_test.go
For all intervals [x, y), Visit will visit intervals in ascending order
sorted by x.
Since sorted visit is going to be needed for auth stuff. /cc @mitake
> adt: Visit() interval trees in sorted order

- integration/network_partition_test.go
Fix https://github.com/coreos/etcd/issues/7587.
Retry for possible leader election in majority.
@heyitsanthony I tried using https://golang.org/pkg/testing/#T.Run but it will still mark it as failed. Think this is the simplest way?
> integration: retry TestNetworkPartition5MembersLeaderInMajority

- auth/design.md
This commit imports and refines the design doc of v3 auth:
https://goo.gl/fwBxz6
> auth: import design doc

- proxy/grpcproxy/adapter/chan_stream.go
- proxy/grpcproxy/adapter/lease_client_adapter.go
- proxy/grpcproxy/adapter/watch_client_adapter.go
Preliminary work for adding maintenance API to adapter
> proxy/grpcproxy: add chanStream helper

- compactor/compactor_test.go
> compactor: make TestPeriodic die early

- Documentation/faq.md
> Documentation: add disk latency leader loss question to FAQ

- Documentation/dev-guide/api_reference_v3.md
- Documentation/dev-guide/interacting_v3.md
- Documentation/dev-guide/limit.md
- Documentation/learning/api_guarantees.md
- Documentation/op-guide/gateway.md
- Documentation/v2/api_v3.md
- etcdserver/etcdserverpb/rpc.pb.go
- etcdserver/etcdserverpb/rpc.proto
These should be rather clear cases.
Unfortunately the PR is in multiple commits and I do not follow a commit message structure. Is that okay?
> Fixing small typos in documentation

- compactor/compactor_test.go
compactor: fix TestPeriodic
Perviously, we advance checkCompactionInterval more than we should.
The compaction might happen nondeterministically since there is no
synchronization before we call clock.Advance().
The number of rg.Wait() should be equal to the number of Advance() if
compactor routin and test routin run at the same pace. However, in our current
test, we call Advance() more than rg.Wait().
It works OK when the compactor routine runs "slower" than the test routine, which
is the common case. However, when the speed changes, the compactor ruotine might
block rg.Rev() since there is not enough calls of rg.Wait().
This commit force the compactor and test routin runs at the same pace. And we supply
the exact number of Advance() and wg.Wait() that compactor needs.
> compactor: fix TestPeriodic

- Documentation/integrations.md
I am actively working on this client, if anyone cares to help out.
> Documentation: Adding new Ruby v3 client entry to integrations.md

- pkg/idutil/id.go
Comments for id generator format is out of
date, correct it.
Fixes #7636
Signed-off-by: Peng Gao <peng.gao.dut@gmail.com>
> idgen: correct comments for id generator

- clientv3/client_test.go
Cf. https://travis-ci.org/coreos/etcd/jobs/218209895#L759
> clientv3: fix go1.8 go fmt warning in test

- auth/range_perm_cache.go
- mvcc/watcher_group.go
- pkg/adt/interval_tree.go
- pkg/adt/interval_tree_test.go
> *: support checking that an interval tree's keys cover an entire interval

- embed/etcd.go
- embed/serve.go
- etcdmain/grpc_proxy.go
- pkg/debugutil/doc.go
- pkg/debugutil/pprof.go
Fix https://github.com/coreos/etcd/issues/7514
> *: add pprof flag to grpc proxy
