etcd-io/etcd

Documentation/op-guide/configuration.md
etcdmain/help.go
etcdserver/server.go

Keep more wal entries in memory for fast follower recovery and less snapshots.
10,000 was a too small number that triggers quite a few compactions/snapshots.
ZK proves that 100,000 is a reasonable number for even old less powerful
machines.
Eventually we should provide both count and max memory (for large entries).

etcdserver: increase snapshot to 100,000

---

tools/functional-tester/etcd-tester/cluster.go

Since we want to send snapshot more often in failure injected cluster

etcd-tester: use 10K for '--snapshot-count'

---

pkg/transport/listener.go

This line does not do what it thinks it does. If it did do what it thinks it does, then it would be insecure. As it is, it's pretty damn insecure. Actually it's all pretty insecure.
The intended behaviour would not verify the server name when a private PKI is being used. Actually, that's not true, it would not verify any PKI, private or not, if the root certs are being explicitly provided. This means that the TLS does not protect against MITMs if you have any certificate from the PKI (basically removing the P from PKI and making it a rather clumsy shared secret).
The current behaviour of setting ServerName to an empty string causes the ssl to be verified against the Host passed to the transport (as far as I can tell). This is exactly what #6084 is meant to solve. But this breaks it. …

Obey the usual rules of SSL server name verification when using a private PKI

---

etcdmain/grpc_proxy.go
integration/cluster_proxy.go
proxy/grpcproxy/cache/store.go
proxy/grpcproxy/kv.go
proxy/grpcproxy/kv_test.go

ccache launches some goroutines that need to be explicitly stopped.
Fixes #7158
May still need to patch ccache's Stop in upstream if the goroutines are too slow to exit since it doesn't wait for its goroutines to exit.

grpcproxy, etcdmain, integration: add close channel to kv proxy

---

store/store.go
store/store_test.go

Sets `e.Node.Dir` attribute in `DeleteExpiredKeys`
When a directory node expired, the `prevNode` has a `"dir":true` attribute in the received expire event, but the `node` has no `"dir":true` attribute
Fixes #7033

store: set e.Node.Dir attribute, when node expired

---

Documentation/v2/docker_guide.md

Hi everyone,
when my team set up our first etcd cluster based on docker, we strictly followed the instructions found in docker_guide.md. One thing that was a bit problematic for us is that the run commands for all cluster members are _mostly_ the same, with only minor variations. I felt like it would be useful to highlight these differences in the documentation so that they are visible right away. In order to highlight the parts within a code block, I changed the code block to a ```<pre></pre>``` block.
Regards,
Tobi

Highlight differences between example run commands in docker_guide

---

Documentation/op-guide/container.md

Replace https://github.com/coreos/etcd/pull/7191.
Might as well backport this for tomorrow release.

Documentation: fix typo s/endpoint-health/endpoint health/

---

pkg/flags/flag.go

if the env in which ETCD starts also has the ETCDCTL_API variable set , then etcd gives a warning
```
vimal (make-v2-endpoint-optional-#7100) bin $ ./etcd
2017-01-20 11:53:07.324208 W | pkg/flags: unrecognized environment variable ETCDCTL_API=3
2017-01-20 11:53:07.324319 I | etcdmain: etcd Version: 3.2.0+git
2017-01-20 11:53:07.324344 I | etcdmain: Git SHA: b2d5c91
2017-01-20 11:53:07.324366 I | etcdmain: Go Version: go1.7
2017-01-20 11:53:07.324386 I | etcdmain: Go OS/Arch: linux/amd64
```
after this fix the warning is not there
```
vimal (fix-ETCD-prefix-check *) bin $ ./etcd
2017-01-20 13:08:58.172081 I | etcdmain: etcd Version: 3.2.0+git
2017-01-20 13:08:58.172154 I | etcdmain: Git SHA: 94eec5d
2017-01-20 13:08:58.172170 I | etcdmain: Go Version: go1.7
2017-01-20 13:08:58.172184 I | …
```

pkg/flags: fixed prefix checking of the env variables

---

clientv3/concurrency/stm.go
integration/v3_stm_test.go

This patch is cherry-picked from https://github.com/coreos/etcd/pull/7185.
Fix https://github.com/coreos/etcd/issues/7184.
Would like to get this in v3.1 if possible?

concurrency: fix stm restart on concurrent key deletion

---

e2e/ctl_v3_snapshot_test.go
etcdctl/ctlv3/command/snapshot_command.go

Fix https://github.com/coreos/etcd/issues/7192

etcdctlv3: snapshot restore works with lease key

---

test

the `${pass}_pass` functions in the `${REPO_PATH}/test` script make use of the function arguments in invoking the  `go test`  , but there are no parameters being passed while invoking the function.
modified to pass the script arguments as the function parameters
this way selective tests can be run (if needed in developer testing environment). 
e.g. `PASSES='e2e' ./test -run TestCtlV3 2>&1 | tee e2e_test.log`
can run the V3 etcdctl tests only.

test: passed the test script arguments to the function parameters

---

Documentation/op-guide/configuration.md
embed/config.go
embed/etcd.go
embed/serve.go
etcd.conf.yml.sample
etcdmain/config.go
etcdmain/help.go

- added a config flag `enable-v2` with default value `true`
- if this flag is set to false, v2 handler is not created

embed/etcd.go: make v2 endpoint optional. fixes #7100

---

Documentation/op-guide/grpc_proxy.md

We say it's alpha here https://github.com/coreos/etcd/blob/master/Documentation/dev-guide/experimental_apis.md.
Make it consistent.

op-guide: change grpc-proxy from 'pre' to alpha'

---

README.md

We are deprecating ACI (to be replaced by OCI as soon as the tooling is ready), and use Go 1.7+ now.
/cc @philips

README: remove ACI, update Go version

---

Documentation/upgrades/upgrade_3_0.md

This PR updates the documentation with the two root causes of some issues experienced during upgrade, and includes the log output I was receiving to hopefully help users making the upgrade more quickly find the info I eventually found while troubleshooting.

Documentation: add upgrade gotchas/further info for better visibility on google, etc

---

pkg/cpuutil/doc.go
pkg/cpuutil/endian.go
pkg/netutil/routes.go
pkg/netutil/routes_linux.go

Tests were failing on non-386/amd64 archs since the build flags were trying to enforce little endian ordering. Just detect endianness instead and have the route detection code work everywhere.
/cc @mkumatag

pkg/netutil: use native byte ordering

---

Documentation/docs.md

It is not clear to users immediately what is the gRPC
gateway. Adding a more explanation to make it clear that
etcd3 supports HTTP API through the gateway.
/cc @philips @heyitsanthony @gyuho @fanminshi

doc: mention HTTP JSON in doc link

---

client/client.go
client/client_test.go

Cherry-picked from https://github.com/coreos/etcd/pull/6422.

	client: add GetVersion method

---

cmd/vendor/github.com/olekukonko/tablewriter/table.go
cmd/vendor/github.com/olekukonko/tablewriter/wrap.go
etcdctl/ctlv3/command/printer_table.go
glide.lock
glide.yaml

`tablewriter` default align could be
```
|         123 |
| 1GB         |
```
We should align them at center.
Fix typo in https://github.com/coreos/etcd/blob/master/cmd/vendor/github.com/olekukonko/tablewriter/table.go#L31.

ctlv3: right-align table output, fix typo in vendor

---

embed/config.go
embed/etcd.go
embed/serve.go

Fixes #7200
Hi again,
My original design does not progress well, the main problem is that the code generated by gRPC does not export corresponding ServiceDesc. Please refer https://github.com/grpc/grpc-go/blob/master/examples/helloworld/helloworld/helloworld.pb.go#L123
It seems we have to setup a `func(*grpc.Server)` instead.
/cc @xiang90 @heyitsanthony

embed: support user defined grpc services.

---

.gitignore

This will keep  all intellij IDEA IDE related files out of git.
This helps contributors using IDEA IDE for development.
/cc @mitake
as per https://github.com/coreos/etcd/pull/7229/files/2fe7945a6b3a5f099878c70aabb8c1ce24c5518f

.gitignore: Adding .idea to .gitignore

---

clientv3/client.go
clientv3/client_test.go

clientv3: use DialContext

---

auth/store_test.go

Refactored auth store tests to pull common setup into a method.
as per https://github.com/coreos/etcd/pull/7229/files/1b9a4d891148eca86d28ef051676f1eb5e49fa00
/cc @xiang90 @mitake

auth: refactor auth store test to use common setup

---

test

PPC64 timing out; integration tests already at 15 minutes.

test: bump e2e timeout to 15 minutes

---

embed/config.go
integration/embed_test.go

embed: reject domain names before binding (again)

---

e2e/ctl_v3_auth_test.go

Fix https://github.com/coreos/etcd/issues/7187
If we remove the member we connect to, we might see member is stopped before the response arrives.

e2e: do not remove the member we connect to

---

Documentation/op-guide/supported-platform.md
etcdmain/etcd.go

etcdserver : ppc64le platform support

ppc64le platform support

---

embed/config.go
pkg/netutil/isolate_linux.go
pkg/netutil/routes_linux.go
pkg/netutil/routes_linux_test.go

in v3.1.0 netutil couldn't get default interface for ipv6only hosts
Fixes #7219

netutil: add dualstack to linux_route

---

auth/store.go
e2e/ctl_v3_auth_test.go
e2e/etcd_test.go
etcdserver/api/v3rpc/maintenance.go
etcdserver/server.go
etcdserver/v3_server.go

This PR lets v3 auth mechanism authenticate clients based on CommonName of certificate like v2 auth.
/cc @yudai

 authenticate clients based on certificate CommonName in v3 API

---

auth/store_test.go

This will cover unit-test for AuthDisable in store.go
/cc @mitake @xiang90

auth: unit-test for authStore.AuthDisable()

---

rafthttp/fake_roundtripper_test.go
rafthttp/pipeline.go
rafthttp/snapshot_sender.go
rafthttp/stream.go

rafthttp: use http.Request.WithContext instead of Cancel

---

lease/leasehttp/http.go
pkg/httputil/httputil.go
proxy/httpproxy/reverse.go

*: Use http.Request.WithContext instead of Cancel

---

clientv3/client.go
clientv3/config.go
clientv3/yaml/config.go
clientv3/yaml/config_test.go

Moved to clientv3/yaml
Should this also include username/password fields too? They're missing right now.

clientv3: remove strict yaml dependency

---

clientv3/lease.go

when lease client resets lease keep alive stream, sendKeepAliveLoop() should send out keep alive reqs immediately instead of waiting for 500ms.

clientv3: sends keepalive reqs immediately after lease keep alive stream reset

---

clientv3/lease.go

clientv3: only start lease stream after first keepalive call

---

clientv3/lease.go

Only have Close() cancel out outstanding goroutines. Canceling out
single-shot RPCs will mask connection close on client.Close().
/cc @xiang90

clientv3: remove cancelWhenStop from lease implementation

---

clientv3/integration/cluster_test.go
clientv3/integration/kv_test.go
clientv3/integration/lease_test.go
clientv3/integration/role_test.go
clientv3/integration/txn_test.go
clientv3/integration/user_test.go
clientv3/integration/watch_test.go

clientv3 integration test was using clientv3.NewKV, clientv3.NewWatcher, etc to create specific client.
replace those with direct client calls so that the direct calls can also test grpc proxy.

clientv3: integration test uses direct client calls

---

auth/store.go
auth/store_test.go

Because of my own silly mistake, current NewAuthStore() doesn't
initialize authStore in a correct manner. For example, after recovery
from snapshot, it cannot revive the flag of enabled/disabled. This
commit fixes the problem.
Fix https://github.com/coreos/etcd/issues/7165
/cc @ekle @yudai

auth: correct initialization in NewAuthStore()

---

etcdserver/util.go
integration/v3_election_test.go
mvcc/kvstore.go
raft/node_test.go
tools/functional-tester/etcd-runner/command/global.go

Getting gosimple suggestion while running test script, so this PR is for fixing gosimple S1019 check.
raft/node_test.go:456:40: should use make([]raftpb.Entry, 1) instead (S1019)
raft/node_test.go:457:49: should use make([]raftpb.Entry, 1) instead (S1019)
raft/node_test.go:458:43: should use make([]raftpb.Message, 1) instead (S1019)
Refer https://github.com/dominikh/go-tools/blob/master/cmd/gosimple/README.md#checks for more information.

test: Fix gosimple errors

---

clientv3/integration/lease_test.go
etcdserver/api/v3rpc/lease.go
integration/v3_lease_test.go

lease: LeaseTimeToLive returns TTL=-1 resp on lease not found

---

proxy/grpcproxy/kv.go

TestKVRange from client integration tests was failing.

grpcproxy: support CountOnly

---

proxy/grpcproxy/watcher.go

CompactRevision wasn't sent over watch stream, causing TestKVCompact to hang.

grpcproxy: respect CompactRevision in watcher

---

raft/node.go
raft/node_test.go
raft/rawnode_test.go
wal/wal.go

Add Ready.MustSync which indicates that the hard state and raft log
entries in a Ready message must be synchronously written to persistent
storage.

raft: add Ready.MustSync

---

auth/range_perm_cache.go
auth/range_perm_cache_test.go

No need of separate function to filter duplicates.
Just merge ranges in-place
```
go test -v -run=xxx -bench=BenchmarkMergeOld -benchmem
BenchmarkMergeOld-8   	  100000	     13524 ns/op	    1104 B/op	       8 allocs/op
go test -v -run=xxx -bench=BenchmarkMergeNew -benchmem
BenchmarkMergeNew-8   	  100000	     13432 ns/op	     936 B/op	       3 allocs/op
```
Not much performance boost, but less memory allocation
and simpler

auth: simplify merging range perm

---

.travis.yml

Was spamming security@coreos.com
Alternative is to have it spam team-etcd, but that seems kind of noisy.
/cc @crawford @xiang90

travis: disable email notifications

---

clientv3/integration/watch_test.go
proxy/grpcproxy/kv.go
proxy/grpcproxy/leader.go
proxy/grpcproxy/watch.go

Move leadership detection out of watch code since it will be shared with
lease code. Also stricter: assumes leader does not exist unless watch can
be successfully created.

grpcproxy: split out / tighten up leadership detection

---

clientv3/lease.go

clientv3: fix lease keepalive duration

---

raft/raft.go
raft/raft_test.go

Hi,
This PR tries to fix issue #7331 . It follows the raft thesis 6.4 to reject read only request when a new leader has not committed any log entry at its term.

raft: fix read index request for #7331

---

pkg/transport/listener.go

4a0f922 changed SelfCert to use a helper from pkg/fileutils which
introduced a transitive dependency on coreos/pkg/capnslog. This means
anyone who imports pkg/transport to use TLS with the clientv3 library
has the default stdlib logger hijacked by capnslog.
This PR reverts 4a0f922. There are no tests because 4a0f922 contained no
test and was not attached to a PR.
Fixes #7350

pkg/transport: remove dependency on pkg/fileutils

---

Documentation/op-guide/container.md

One should use host volume when running etcd

op-guide: use host volume in Docker command

---

clientv3/README.md

Fix https://github.com/coreos/etcd/issues/7337.
Replace https://github.com/coreos/etcd/pull/7343.

clientv3: fix typo in README

---

proxy/grpcproxy/chan_stream.go

Since select{} won't prioritize, ctx.Done() can sometimes override
a pending message on recvc. Loop if recvc has messages instead.
Fixes #7340

grpcproxy: only return ctx error in chan stream if recvc is empty

---

clientv3/client.go
clientv3/config.go
clientv3/integration/dial_test.go

Adds a `UseLatestCluster` flag (and user-defined context) to config.
Fixes #6579

clientv3: version checking

---

proxy/tcpproxy/userspace.go

Ends up trying to reactivate only the last endpoint.
/cc @Quentin-M

tcpproxy: don't use range variable in reactivate goroutine

---

clientv3/integration/lease_test.go
clientv3/lease.go

Was causing failures in `TestV3LeaseKeepAlive` for proxy tests.
/cc @xiang90

clientv3: do not set next keepalive time <= now+TTL

---

auth/store.go
auth/store_test.go
integration/v3_grpc_test.go

When there's no changes yet (right after auth
store initialization), we should commit old revision.
Fix https://github.com/coreos/etcd/issues/7359.
Seems like `commitRevision` was introduced long time ago,
and we recently fixed it to have correct revision in `authStore`,
so it starts failing in our hash tests.
Do we have any reason to bump up revision for every `commitRevision` call,
even around store initialization?

auth: keep old revision in 'NewAuthStore'

---

clientv3/example_metrics_test.go

Was getting bind conflicts causing failures on semaphore.
Cf. https://semaphoreci.com/coreos/etcd/branches/master/builds/1580

clientv3: use any port for metrics example

---

raft/node_test.go

TestNodeTick relies on a unreliable func `waitForSchedule` when running
with GOMAXPROCS > 1. This commit changes the test to make sure we stop
the node after it drains the tick chan. The test should be reliable now.
Fix #7374 
/cc @fanminshi @heyitsanthony

raft: make TestNodeTick reliable

---

proxy/grpcproxy/watch.go

grpcproxy: return closing error when stream is canceled from conn close

---

Documentation/op-guide/container.md

Use the one that works in Container Linux
Signed-off-by: Gyu-Ho Lee <gyuhox@gmail.com>
For https://github.com/coreos/etcd/pull/7399.

Documentation/op-guide: use exact certs dir for Container Linux

---

test

fmt pass went from ~20 CPU minutes to ~1 CPU minute.
/cc @gyuho

test: run unused and gosimple over all packages at once

---

tools/functional-tester/etcd-tester/checks.go

Following the change at
https://github.com/coreos/etcd/commit/2ca1823a96105409febb89479d53c6c5e0f83dc2
This fixes the error that we are getting
> [round#6 case#0] functional-tester returning with error (tt.checkConsistency error (lease 5264526043634585873 expiration mismatch (lease expired=false, keys expired=true), lease 8791688976795817481 expiration mismatch (lease expired=false, keys expired=true), lease 1772547482562197041 expiration mismatch (lease expired=false, keys expired=true), lease 7369958869430294037 expiration mismatch (lease expired=false, keys expired=true), lease 8847421022184526416 expiration mismatch (lease expired=false, keys expired=true)))

etcd-tester: check expired lease with -1 TTL

---

embed/config.go
embed/config_test.go
etcdmain/etcd.go

Fix https://github.com/coreos/etcd/issues/7348.
https://github.com/coreos/etcd/pull/7027 broke this.
It overwriting the advertise-client-urls' host with 'localhost'.
Signed-off-by: Gyu-Ho Lee <gyuhox@gmail.com>

*: use machine default host only for default value, 0.0.0.0

---

contrib/raftexample/raftexample_test.go

Travis claimed errors of gosimple like below
(https://travis-ci.org/coreos/etcd/jobs/208098545):
gosimple checking failed:
contrib/raftexample/raftexample_test.go:78:6: should write erri := <-clus.errorC[i] instead of erri, _ := <-clus.errorC[i]
contrib/raftexample/raftexample_test.go:114:10: should write err := <-eC instead of err, _ := <-eC
This commit fixes the errors.

contrib: suppress gosimple errors of raftexample

---

clientv3/client.go
clientv3/client_test.go

Fixes #7419
Before:
```sh
$ ETCDCTL_API=3 etcdctl get whatever
Error:  grpc: timed out when dialing
```
After:
```sh
$ ETCDCTL_API=3 etcdctl get whatever
Error:  dial tcp 127.0.0.1:2379: getsockopt: connection refused
```

clientv3: pass back dial error on dial timeout

---

.travis.yml
auth/store_test.go
etcdctl/ctlv2/command/role_commands.go
etcdctl/ctlv3/command/printer_protobuf.go
etcdserver/raft.go
etcdserver/raft_test.go
etcdserver/server.go
etcdserver/server_test.go
integration/cluster.go
integration/v3_lease_test.go
lease/lessor_test.go
mvcc/kvstore_bench_test.go
pkg/transport/keepalive_listener_test.go
raft/node_test.go
rafthttp/stream.go
store/store_test.go
store/watcher_hub.go
test
wal/repair_test.go
wal/wal_test.go

Fix https://github.com/coreos/etcd/issues/7298.
We will still have some failures until we migrate to Go 1.8.
So this just mask those errors to not fail the whole test suite.
```
skipping error:
contrib/raftexample/raftexample_test.go:105:3: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
skipping error:
e2e/ctl_v3_watch_test.go:72:3: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
e2e/etcd_release_upgrade_test.go:156:3: the goroutine calls T.Fatalf, which must be called in the same goroutine as the test (SA2002)
skipping error:
etcdctl/ctlv3/command/elect_command.go:76:36: os.Kill cannot be trapped (did you mean syscall.SIGTERM?) (SA1016)
etcdctl/ctlv3/command/elect_command.go:110:36: os.Kill …
```

*: add 'staticcheck' to 'test'

---

Documentation/op-guide/configuration.md
auth/jwt.go
auth/simple_token.go
auth/store.go
auth/store_test.go
cmd/vendor/github.com/dgrijalva/jwt-go/LICENSE
cmd/vendor/github.com/dgrijalva/jwt-go/claims.go
cmd/vendor/github.com/dgrijalva/jwt-go/doc.go
cmd/vendor/github.com/dgrijalva/jwt-go/ecdsa.go
cmd/vendor/github.com/dgrijalva/jwt-go/ecdsa_utils.go
cmd/vendor/github.com/dgrijalva/jwt-go/errors.go
cmd/vendor/github.com/dgrijalva/jwt-go/hmac.go
cmd/vendor/github.com/dgrijalva/jwt-go/map_claims.go
cmd/vendor/github.com/dgrijalva/jwt-go/none.go
cmd/vendor/github.com/dgrijalva/jwt-go/parser.go
cmd/vendor/github.com/dgrijalva/jwt-go/rsa.go
cmd/vendor/github.com/dgrijalva/jwt-go/rsa_pss.go
cmd/vendor/github.com/dgrijalva/jwt-go/rsa_utils.go
cmd/vendor/github.com/dgrijalva/jwt-go/signing_method.go
cmd/vendor/github.com/dgrijalva/jwt-go/token.go
embed/config.go
embed/etcd.go
etcdmain/config.go
etcdmain/help.go
etcdserver/config.go
etcdserver/server.go
etcdserver/v3_server.go
glide.lock
glide.yaml
integration/cluster.go

This PR adds jwt token support in v3 auth API.
Remaining major ToDos:
- Currently token type isn't hidden from etcdserver. In the near
future the information should be completely invisible from
etcdserver package.
- Configurable expiration of token. Currently tokens can be valid
until keys are changed.
How to use:
1. generate keys for signing and verfying jwt tokens:
$ openssl genrsa -out app.rsa 1024
$ openssl rsa -in app.rsa -pubout > app.rsa.pub
1.  add command line options to etcd like below:
--v3-auth-token-type jwt \
--v3-auth-jwt-pub-key app.rsa.pub --v3-auth-jwt-priv-key app.rsa \
--v3-auth-jwt-sign-method RS512
2. launch etcd cluster
Below is a performance comparison of serializable read w/ and w/o jwt
token. Every (3) etcd node is executed on a single machine. Signing
method is …

*: support jwt token in v3 auth API

---

Documentation/upgrades/upgrade_3_0.md

Fix https://github.com/coreos/etcd/issues/7429.

Documentation: warn membership change while migration

---

etcdmain/gateway.go

strip the scheme from the endpoints to have a clean hostname for TCP proxy
Fixes #7452

gateway: fix the dns discovery method

---

lease/lessor.go
lease/lessor_test.go

Fix https://github.com/coreos/etcd/issues/7448.
Affected if etcd builds with Go 1.8+.

lease: guard 'Lease.itemSet' from concurrent writes

---

NEWS
auth/jwt.go
integration/v3_lease_test.go
pkg/adt/interval_tree.go
test

Mainly to fix the wrong command name in `test` script (to `staticcheck`).
Might as well fix others.

*: fix minor typos

---

etcdctl/ctlv3/command/snapshot_command.go
etcdserver/apply.go
etcdserver/apply_auth.go
etcdserver/server.go
etcdserver/v3_server.go
lease/lessor.go
lease/lessor_test.go
mvcc/backend/backend.go
mvcc/backend/backend_test.go
mvcc/backend/batch_tx.go
mvcc/backend/read_tx.go
mvcc/backend/tx_buffer.go
mvcc/kv.go
mvcc/kv_test.go
mvcc/kv_view.go
mvcc/kvstore.go
mvcc/kvstore_bench_test.go
mvcc/kvstore_test.go
mvcc/kvstore_txn.go
mvcc/metrics_txn.go
mvcc/watchable_store.go
mvcc/watchable_store_bench_test.go
mvcc/watchable_store_test.go
mvcc/watchable_store_txn.go
tools/benchmark/cmd/mvcc-put.go

Clean-up of the mvcc interfaces to use txn interfaces instead of an id.
Adds support for concurrent read-only mvcc transactions.
Fixes #7083

mvcc: txns and  r/w views

---

test

Lots of repeated compilation. Cache results with go build -i.

test: install packages when building coverage tests

---

etcdmain/etcd.go
etcdmain/gateway.go
etcdmain/grpc_proxy.go
etcdmain/main.go

Just tried this on Container Linux with systemd, confirmed that it works well without sd-notify errors.
```
Mar 09 17:52:19 gyuho-coreos.c.etcd-development.internal systemd[1]: Starting etcd...
Mar 09 17:52:19 gyuho-coreos.c.etcd-development.internal etcd[25737]: ready to proxy client requests to [127.0.0.1:2379]
Mar 09 17:52:19 gyuho-coreos.c.etcd-development.internal systemd[1]: Started etcd.
Mar 09 17:54:06 gyuho-coreos.c.etcd-development.internal systemd[1]: Starting etcd...
Mar 09 17:54:06 gyuho-coreos.c.etcd-development.internal etcd[25832]: listening for grpc-proxy client requests on 127.0.0.1:23791
Mar 09 17:54:06 gyuho-coreos.c.etcd-development.internal systemd[1]: Started etcd.
```
Fix https://github.com/coreos/etcd/issues/7465

etcdmain: SdNotify when gateway, grpc-proxy are ready

---

discovery/srv.go

I am getting 
> 2017-03-10 23:00:19.229962 N | discovery: got bootstrap from DNS for etcd-server at httpmy-etcd-1.example.com:2380

discovery: fix print format

---

auth/store.go

If the context does not include auth information, get authinfo will
return a nil auth info and a nil error. This is then passed to
IsAdminPermitted, which would dereference the nil auth info.
via #7471
/cc @mitake

auth: nil check AuthInfo when checking admin permissions

---

clientv3/main_test.go
pkg/testutil/leak.go

AfterTest() has a delay that waits for runtime goroutines to exit; CheckLeakedGoroutine does not. Since the test runner manages the test cluster for examples, there is no delay between terminating the cluster and checking for leaked goroutines. Instead, apply AfterTest checking before running CheckLeakedGoroutine to let runtime http goroutines finish.

clientv3: use CheckAfterTest after terminating cluster

---

auth/simple_token.go
auth/store_test.go

Just use the mutex instead.
Fixes #7471

auth: get rid of deadlocking channel passing scheme in simpleTokenTTL

---

test

Was only getting coverage for packages with test files. Instead, include
packages that don't have test files as well.

test: add coverage for more packages

---

clientv3/watch.go

If substream is closing but outc is still open while reconnecting, then outc
would only be closed once the watch client would connect or once the watch
client is closed. This was leading to deadlocks in the proxy tests. Instead,
close immediately if the context is canceled.
Fixes #7503

clientv3: close open watch channel if substream is closing on reconnect

---

clientv3/balancer_test.go

Was leaking dialers.
Failure: https://semaphoreci.com/coreos/etcd/branches/pull-request-7496/builds/1

clientv3: synchronize on goroutines in TestBalancerDoNotBlockOnClose

---

etcdctl/ctlv3/command/member_command.go

In cases of multiple endpoints, it's possible member add would get a its
member list from a member that has not yet recognized the membership
update. Instead, confirm that the member list response is from the
member that acked the member add or from a member that has synced
with the cluster following the member add.
Fixes #7498

ctlv3: ensure synced member list before printing env vars on member add

---

etcdserver/api/v3client/doc.go

Was passing embed.Etcd instead of etcdserver.EtcdServer.
/cc @darasion

v3client: fix doc to use e.Server

---

wal/file_pipeline.go
wal/repair.go
wal/wal.go
wal/wal_test.go

Use the path/filepath package instead of the path package. The
path package assumes slash-separated paths, which doesn't work
on Windows. But path/filepath manipulates filename paths in a way
that's compatible across OSes.

wal: use path/filepath instead of path

---

embed/etcd.go
embed/util.go
etcdctl/ctlv2/command/backup_command.go
etcdctl/ctlv3/command/migrate_command.go
etcdctl/ctlv3/command/snapshot_command.go
etcdmain/etcd.go
etcdserver/config.go
etcdserver/server.go
integration/embed_test.go
lease/lessor_test.go
mvcc/backend/backend.go
pkg/fileutil/fileutil.go
pkg/fileutil/purge.go
pkg/fileutil/purge_test.go
pkg/transport/listener.go
snap/db.go
snap/snapshotter.go
snap/snapshotter_test.go
tools/etcd-dump-logs/main.go

Full audit of codebase. Continuation of #7515

*: replace path.Join on files with filepath.Join

---

embed/config.go

`embed.NewConfig()` sets the initial cluster from name but we should clear it in the event that another discovery option has been specified.
Fixes #7516

embed: Delay setting initial cluster

---

e2e/ctl_v3_auth_test.go
e2e/ctl_v3_member_test.go
e2e/ctl_v3_test.go

e2e tests use different invocations of etcdctl, so the endpoint used to get
the member list will not necessarily be the same to make the remove call.
Instead, select an endpoint that is not being remove, and connect with that.
Cf. https://semaphoreci.com/coreos/etcd/branches/master/builds/1676

e2e: force endpoint for member removal

---

etcdctl/ctlv3/ctl.go

ctlv3: have "protobuf" in output help string instead of "proto"

---

README.md
etcdctl/ctlv3/command/snapshot_command.go
pkg/fileutil/fileutil.go
pkg/fileutil/fileutil_test.go
pkg/fileutil/lock_linux.go
pkg/fileutil/preallocate.go
wal/encoder.go
wal/repair.go
wal/repair_test.go
wal/wal.go
wal/wal_test.go

For https://github.com/coreos/etcd/issues/6174.

*: use 'io.Seek*' for go1.7+

---

e2e/ctl_v3_auth_test.go
e2e/ctl_v3_defrag_test.go
e2e/ctl_v3_endpoint_test.go
e2e/ctl_v3_snapshot_test.go
etcdserver/server.go

e2e, etcdserver: fix wrong usages of ordinal

---

etcdmain/etcd.go
integration/cluster.go
integration/cluster_test.go

Fix https://github.com/coreos/etcd/issues/7512.
If a server starts and aborts due to config error,
it is possible to get stuck in ReadyNotify waits.
This adds select case to get notified on stop channel.

*: fix blocking etcd process

---

client/integration/client_test.go

Fix https://github.com/coreos/etcd/issues/7558.
Same as https://github.com/coreos/etcd/issues/6959.

client/integration: use only digits in unix port

---

Documentation/docs.md
Documentation/op-guide/authentication.md

It is almost same to Documentation/v2/authentication.md because a
major part of its user interface is shared with the v2 auth. The newly
added doc includes some refinements for the v3 auth.

Documentation: add a doc of v3 auth

---

integration/member_test.go

In rare cases, the last member may not have the leader by the time the
final cluster progress check tries to open a watch, causing a timeout.
Cf. https://jenkins-etcd-public.prod.coreos.systems/job/etcd-proxy/1046/consoleFull

integration: wait on leader before progress check in TestRestartMember

---

Documentation/op-guide/etcd3_alert.rules
Documentation/op-guide/monitoring.md
Documentation/v2/etcd_alert.rules

Adding the etcd alerting rules we developed. This way they have visibility and we can collaborate on them together with the community. The etcd2 rules are basically a subset of the etcd3 rules as etcd3 introduced a lot of new metrics that we were able to write alerts for.
I remember that we had previously reviewed the alerts together, but feel free to review them again! :slightly_smiling_face: 
@hongchaodeng @xiang90

Documentation: add Prometheus alerting rules

---

etcdctl/ctlv3/command/migrate_command.go
etcdserver/quota.go
etcdserver/server.go
lease/lessor_test.go
mvcc/backend/backend.go
mvcc/backend/backend_bench_test.go
mvcc/backend/backend_test.go
mvcc/backend/boltoption_linux.go
tools/benchmark/cmd/mvcc.go

Mechanism for permitting mmaps > 10GB.

etcdserver, backend: configure mmap size based on quota

---

integration/v3_maintenance_test.go
mvcc/backend/backend.go
mvcc/backend/batch_tx.go

When resetting `bolt.Tx` in `defrag` and `batchTxBuffered.commit` operation, we do not hold `readTx` lock, so the inflight range requests can trigger panic in `mvcc.Range` paths. This fixes by moving mutexes out and hold it while resetting the `readTx`.
The test case is added (fails in current master branch).

*: fix panic during defrag operation

---

tools/functional-tester/etcd-tester/member.go

etcd panic-ed, so defrag response just blocked for "days";
the actual 'v3rpc' path never returned.
We should catch this earlier.
ref. https://github.com/coreos/etcd/issues/7526

tools/etcd-tester: add timeout for 'defrag'

---

clientv3/watch.go

When a grpc watch stream is torn down, it will join on its logical substream
goroutines by waiting for each to close a channel. This doesn't guarantee
the substream is fully exited, though, but only about to exit and can be
waiting to resume even after Watch.Close finishes. Instead, use a
waitgroup.Done at the very end of the substream defer.
Fixes #7573 
reproduced reliably by allocating 10x more watch channels in TestWatchStressResumeClose

clientv3: use waitgroup to wait for substream goroutine teardown

---

auth/store.go
e2e/ctl_v3_auth_test.go
etcdserver/api/v3rpc/rpctypes/error.go
etcdserver/api/v3rpc/util.go

- The 1st commit adds a new flag `--revoke` to `etcdctl role delete`. If the flag is passed, the role will be revoked from all users. The 2nd commit adds an e2e test case for this.
- The 3rd commit forbids deleting the role root and revoking the role from the user root if auth is enabled. The 4th commit adds an e2e test case for this.

auth: changes of managing roles and users

---

Dockerfile-release

The file '/etc/nsswitch.conf' is created in order to
take in account '/etc/hosts' entries while resolving
domain names inside docker container.
Closes #7559

Dockerfile-release: add nsswitch.conf into image

---

raft/raft_test.go
raft/read_only.go

advance() should use rs.req.Entries[0].Data as the context instead of
req.Context for deletion. Since req.Context is never set, there won't be
any context being deleted from pendingReadIndex; results mem leak.
FIXES #7571

raft: use rs.req.Entries[0].Data as the key for deletion in advance() 

---

Documentation/op-guide/authentication.md

As i understand there is no guest role in v3 auth. guest role was introduced in v2 auth to be backward compatible.

op-guide: Remove guest role from v3 auth doc

---

integration/v3_grpc_test.go
proxy/grpcproxy/cache/store.go

Since the current revision is 0, it'll always be less than the compaction
revision. If the proxy sees a compaction, it would always reject the
current revision requests since it's less than the compaction revision.
Instead, check if the revision is historical before trying to reject on
compaction revision.
Fixes #7599

grpcproxy/cache: only check compaction revision for historical revisions

---

pkg/testutil/leak.go

gRPC leaks only show up at the final leak check, making it difficult to
determine which test is causing the leak.

testutil: check for grpc resources in AfterTest

---

etcdctl/ctlv3/command/check.go
etcdctl/ctlv3/ctl.go

This is a very simple performance validation command. The output is PASS or FAIL. There is nothing much to tune by design. If users want to find out more information, they should use benchmark tool instead.
example output:
```
ETCDCTL_API=3 ./etcdctl validate-perf --load=m
60 / 60 Booooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo! 100.00%1m0s
PASS: Throughput is 968 writes/s
PASS: Slowest request took 0.490595s
PASS: Stddev is 0.030787s
PASS
```
I am going to finish up docs if this direction looks good. /cc @heyitsanthony @gyuho

etcdctl: add initial check perf command

---

Documentation/dev-guide/apispec/swagger/rpc.swagger.json
etcdserver/etcdserverpb/rpc.pb.go
scripts/genproto.sh

Fixes #7631
I'm not seeing .pb.go file changes as mentioned in the original issue. The swagger changes are likely related to the fact the genproto.sh script doesn't pin grpc-gateway/protoc-gen-swagger to any particular SHA.

*: use protoc 3.2.0

---

clientv3/integration/lease_test.go
clientv3/lease.go
etcdserver/api/v3rpc/lease.go
integration/v3_lease_test.go

Fixes #7275
Also includes a test/fix for the etcdserver when using WithRequireLeader for lease streams. Without the fix, the lease stream could wait forever on a Recv() if the leader is lost instead of exiting immediately.

clientv3: support WithRequireLeader in lease client

---

auth/range_perm_cache.go
auth/range_perm_cache_test.go
auth/store.go

This commit change the type of cached permission information from the
home made thing to interval tree. It improves computational complexity
of permission checking from O(n) to O(lg n).
/cc @heyitsanthony This is a preparation for https://github.com/coreos/etcd/issues/7468 , could you take a look? We can support the unlimited range by configuring a permission like ["a", "\xff") in a simple manner thanks to interval tree.

auth: store cached permission information in a form of interval tree

---

etcdserver/apply.go
etcdserver/server.go
etcdserver/server_test.go
integration/cluster.go
integration/cluster_test.go

Without being able to cancel the requests, HardStop could take more than five seconds to complete.

etcdserver: ctx-ize server initiated requests

---

clientv3/client.go
clientv3/client_test.go

clientv3: respect dial timeout in auth

---

Documentation/integrations.md

Added to `Documentation/integrations.md` from discussion of https://github.com/coreos/etcd/issues/7542

Documentation: add encryption wrapper to integrations

---

clientv3/auth.go

I don't see anywhere using these fields... Will close if test fails.

clientv3: remove unused fields from 'auth'

---

auth/store.go
auth/store_test.go

Fix https://github.com/coreos/etcd/issues/7660.

auth: use atomic access to 'authStore.revision'

---

test

The coverage data is still useful even if some tests fail. Instead of
terminating the coverage pass on any test failure, collect and pass
the failed tests, generate the coverage report, then report the failed
packages and exit with an error.
See: https://jenkins-etcd-public.prod.coreos.systems/job/etcd-coverage/782/console

test: generate coverage report even if some tests fail

---

Documentation/benchmarks/etcd-2-2-0-rc-benchmarks.md
Documentation/benchmarks/etcd-3-demo-benchmarks.md
Documentation/op-guide/clustering.md
Documentation/op-guide/security.md
Documentation/v2/benchmarks/etcd-2-1-0-alpha-benchmarks.md
Documentation/v2/benchmarks/etcd-2-2-0-benchmarks.md
Documentation/v2/benchmarks/etcd-2-2-0-rc-benchmarks.md
Documentation/v2/benchmarks/etcd-3-demo-benchmarks.md
Documentation/v2/clustering.md
Documentation/v2/security.md

This change is necessary for some downstream documentation that gets built for https://coreos.com/etcd/docs/latest.
Also absolute links are notoriously not a good idea 😉 
CC: @robszumski, @joshix, @crawford

Docs: replace absolute links with relative ones.

---

auth/range_perm_cache.go
auth/range_perm_cache_test.go
e2e/ctl_v3_auth_test.go
e2e/ctl_v3_role_test.go
etcdctl/ctlv3/command/printer_simple.go
etcdctl/ctlv3/command/role_command.go

This commit adds a new option --open-ended to the command etcdctl role
grant-permission. If the option is passed, an open ended permission
will be granted to a role e.g. from start-key to any keys those are
larger than start-key.
```
Example:
$ ETCDCTL_API=3 bin/etcdctl --user root:p role grant r1 readwrite a b
$ ETCDCTL_API=3 bin/etcdctl --user root:p role grant --open-ended r1 readwrite c
$ ETCDCTL_API=3 bin/etcdctl --user root:p role get r1
Role r1
KV Read:
[a, b) (prefix a)
[c, <open ended>
KV Write:
[a, b) (prefix a)
[c, <open ended>
```
Note that a closed parenthesis doesn't follow the above <open ended>
for indicating that the role has an open ended permission ("<open
ended>" is a valid range end).
Fixes https://github.com/coreos/etcd/issues/7468

etcdctl: add a new option --open-ended for unlimited range permission

---

auth/range_perm_cache.go
auth/range_perm_cache_test.go
auth/store.go
pkg/adt/interval_tree.go

It will be useful for avoiding a cost of casting from string to
[]byte. The permission checker is the first user of the type.

auth, adt: introduce a new type ByteAffineComparable

---

pkg/transport/listener.go

etcd passes 'url.URL.Host' to 'SelfCert' which contains
client, peer port. 'net.ParseIP("127.0.0.1:2379")' returns
'nil', and the client on this self-cert will see errors
of '127.0.0.1 because it doesn't contain any IP SANs'
cf. https://github.com/coreos/etcd/issues/7654#issuecomment-291382464

pkg/transport: remove port in Certificate.IPAddresses

---

clientv3/client.go
e2e/etcd_test.go
embed/etcd.go
pkg/transport/unix_listener.go

Now use url.Host + url.Path as unix socket path
Fixes #7644
Related: https://github.com/pingcap/pd/issues/595

*: fix a bug in handling unix socket urls

---

lease/lessor_test.go

Revoke expects the BatchTx lock to be held when holding the TxnDeleter
because it updates the lease bucket. The tests don't hold the lock so
it may race with the backend commit loop.
Fixes #7662

lease: acquire BatchTx lock in fakeDeleter

---

clientv3/yaml/config.go

To be consistent with 'pkg/transport' https://github.com/coreos/etcd/blob/master/pkg/transport/listener.go#L171

clientv3/yaml: use TLS 1.2 in min version

---

etcdctl/ctlv3/command/global.go
etcdctl/ctlv3/ctl.go

By default, grpclog is disabled. It should be configurable
for debugging purposes, as we did in v2.
I need this for debugging issues like https://github.com/coreos/etcd/issues/7654.
e.g. user forgets to specify CA in v3 ctl
current output:
```
ETCDCTL_API=3 /Users/gyuho/go/src/github.com/coreos/etcd/bin/etcdctl \
--endpoints localhost:2379 \
--cert $HOME/certs/my-etcd-1.pem \
--key $HOME/certs/my-etcd-1-key.pem \
put foo bar
Error:  grpc: timed out when dialing
```
with this patch
```
ETCDCTL_API=3 /Users/gyuho/go/src/github.com/coreos/etcd/bin/etcdctl \
--debug \
--endpoints localhost:2379 \
--cert $HOME/certs/my-etcd-1.pem \
--key $HOME/certs/my-etcd-1-key.pem \
put foo bar
grpc: Failed to dial localhost:2379: connection error: desc = "transport: x509: certificate signed by unknown …
```

ctlv3: add '--debug' flag (to enable grpclog)

---

etcdmain/gateway.go
etcdmain/grpc_proxy.go
etcdmain/util.go

etcdmain: support SRV discovery for gRPC proxy

---

test

client/keys.generated.go has poor coverage but it's generated; other
generated files (e.g., pb stuff) are ignored, so this should be ignored too.

test: remove generated files from coverage statistics

---

rafthttp/util.go
rafthttp/util_test.go

Not used in actual code base, only used in tests

rafthttp: move test-only functions to '_test.go'

---

clientv3/concurrency/stm.go
tools/benchmark/cmd/stm.go

Pure Snapshot isolation would permit read conflicts. Change the name
from Snapshot to SerializableSnapshot to reflect that it will also
reject read conflicts.

*: rename Snapshot STM isolation to SerializableSnapshot

---

discovery/srv.go
discovery/srv_test.go
embed/config.go

Can add the argument back when it's actually used something.

discovery: remove dead token argument from SRVGetCluster

---

auth/simple_token.go
integration/v3_auth_test.go

Dual locking doesn't really give a convincing performance improvement and
the lock ordering makes it impossible to safely check if the TTL keeper
is enabled or not.
/cc @raoofm @mitake
Fixes #7722

auth: protect simpleToken with single mutex and check if enabled

---

embed/etcd.go

ref. https://github.com/golang/go/issues/9524#issuecomment-271937649

embed: remove ReadTimeout TODO

---

clientv3/integration/metrics_test.go
pkg/transport/listener.go
pkg/transport/listener_test.go
rafthttp/stream.go

Before we do the gRPC graceful shutdown (will return closed listener errors as well),
removing some duplicate code.

pkg/transport: add 'IsClosedConnError'

---

embed/etcd.go
etcdmain/etcd.go
pkg/transport/keepalive_listener_test.go
pkg/transport/listener.go
pkg/transport/listener_test.go
pkg/transport/listener_tls.go
pkg/transport/timeout_listener.go
rafthttp/util.go

transport: deny incoming peer certs with wrong IP SAN

---

etcdserver/api/v3rpc/maintenance.go

The information that can be obtained with the RPC doesn't need to be
protected.
Fix https://github.com/coreos/etcd/issues/7721
/cc @raoofm @heyitsanthony

etcdserver: let Status() not require authentication

---

etcdserver/raft.go
etcdserver/raft_test.go

When apply-layer sees configuration change entry in
raft.Ready.CommittedEntries, the server should not proceed
until that entry is applied. Otherwise, follower's raft
layer advances, possibly election-timeouts, and becomes
the leader in single-node cluster, before add-node conf
change of other nodes is applied.
Fix https://github.com/coreos/etcd/issues/7595.
@xiang90 @heyitsanthony 
Could you check if this is the correct approach?
I think we can also remove the `isCandidate` check,
if we had that only for config changes?
Thanks.

etcdserver: wait apply on conf change Raft entry

---

clientv3/client.go
clientv3/integration/dial_test.go

clientv3: let client dial endpoints not in the balancer

---

clientv3/namespace/doc.go
clientv3/namespace/watch.go

using "abc" will watch the wrong range when WithPrefix() specified.

clientv3/namespace: fix incorrect watching prefix-end

---

etcdserver/apply.go
integration/v3_auth_test.go

Replace https://github.com/coreos/etcd/pull/7716 (https://github.com/coreos/etcd/pull/7716/commits/5e0f9ebf2927882afd23a1ce85bd5bd3c5e35284).

etcdserver: fill-in Auth API Header in apply layer

---

clientv3/integration/user_test.go

Since we don't have any test cases around 'wrong' id or password

clientv3/integration: add 'TestUserErrorAuth'

---

tools/benchmark/cmd/root.go
tools/benchmark/cmd/util.go

Current benchmark picks destinations of RPCs in a random
manner. However, it will result divergent benchmarking result because
RPCs other than serializable range must be forwarded when a follower
node receives it. This commit adds a new flag --target-leader for
avoid the problem. If the flag is passed, benchmark always picks an
endpoint of a leader node.

benchmark: a new flag --target-leader for targetting a leader endpoint

---

.travis.yml
embed/serve.go
integration/v3_lease_test.go
pkg/transport/listener.go

ref. https://github.com/coreos/etcd/issues/6174

*: clean up for Go 1.8+

---

clientv3/integration/kv_test.go
clientv3/op.go

Users seem to expect the client to do this.

clientv3: translate WithPrefix() into WithFromKey() for empty key

---

pkg/debugutil/pprof.go

Sample output
```
go test -v -run=xxx -benchtime 10s -mutexprofile=mutex.out -bench=BenchmarkWatchableStoreWatchSyncPut
go tool pprof mvcc.test mutex.out
```
```
go tool pprof mvcc.test mutex.out
Entering interactive mode (type "help" for commands)
(pprof) top
9.85s of 9.85s total (  100%)
Dropped 4 nodes (cum <= 0.05s)
Showing top 10 nodes out of 14 (cum >= 5.57s)
flat  flat%   sum%        cum   cum%
9.85s   100%   100%      9.85s   100%  sync.(*Mutex).Unlock
0     0%   100%      5.57s 56.62%  github.com/coreos/etcd/mvcc.(*metricsTxnWrite).End
0     0%   100%      5.57s 56.62%  github.com/coreos/etcd/mvcc.(*storeTxnWrite).End
0     0%   100%      4.27s 43.36%  github.com/coreos/etcd/mvcc.(*watchableStore).syncWatchers
0     0%   100%      4.27s 43.36% …
```

pkg/debugutil: add 'mutex' profiler (Go 1.8+)

---

embed/config.go
embed/config_test.go

Wherever `net.SplitHostPort` is used and we don't care about the parsing error, we can just use the new methods `Hostname` and `Port` that strip out the port or hostname.
https://golang.org/doc/go1.8#net_url

embed: use '*url.URL.Hostname(),Port()' for Go 1.8

---

etcdserver/raft.go
etcdserver/raft_test.go
etcdserver/server.go
etcdserver/server_test.go

raftNode was being initialized in start(), which was causing
hangs when trying to stop the etcd server since the stop channel
would not be initialized in time for the stop call. Instead,
setup non-configurable bits in a constructor.
Fixes #7668

etcdserver: initialize raftNode with constructor

---

pkg/transport/listener_tls.go

The current transport client TLS checking will pass an IP address into
VerifyHostnames if there is DNSNames SAN. However, the go runtime will
not resolve the DNS names to match the client IP. Intead, resolve the
names when checking.
/cc @gyuho

transport: resolve DNSNames when SAN checking

---

auth/store.go
clientv3/client.go
e2e/ctl_v3_auth_test.go
etcdserver/v3_server.go

Fix https://github.com/coreos/etcd/issues/7724
/cc @raoofm @heyitsanthony

*: simply ignore ErrAuthNotEnabled in clientv3 if auth is not enabled

---

embed/serve.go

CMux.Serve blocks, so grpcServerC was never closed.
https://github.com/cockroachdb/cmux/blob/master/cmux.go#L80
Fix https://github.com/coreos/etcdlabs/issues/216.

embed: signal 'grpcServerC' before cmux serve

---

etcdctl/ctlv3/command/printer_fields.go

Output was giving %!d(string=) instead of the expected lease ID
value.

ctlv3: keep lease as integer in fields printer

---

etcdctl/ctlv3/command/lease_command.go
etcdctl/ctlv3/command/printer.go
etcdctl/ctlv3/command/printer_fields.go
etcdctl/ctlv3/command/printer_simple.go

ctlv3: use printer for lease command results

---

cmd/vendor/golang.org/x/text/unicode/norm/composition.go
cmd/vendor/golang.org/x/text/unicode/norm/iter.go
cmd/vendor/golang.org/x/text/unicode/norm/normalize.go
cmd/vendor/golang.org/x/time/rate/rate.go
glide.lock
glide.yaml

Go just updated its import path https://github.com/golang/time/commit/c06e80d9300e4443158a03817b8a8cb37d230320
For https://github.com/coreos/etcd/issues/6174.

vendor: update 'golang.org/x/time/rate' with context

---

cmd/vendor/golang.org/x/net/http2/server.go
cmd/vendor/golang.org/x/net/trace/trace.go
glide.lock
glide.yaml

For https://github.com/coreos/etcd/issues/6174.

vendor: use 'x/net/trace' with std 'context'

---

clientv3/integration/watch_test.go
clientv3/watch.go
integration/bridge.go
integration/cluster.go

Always updating the initReq.rev on watch create will resume from the wrong
revision if initReq is ever nonzero.

clientv3: only update initReq.rev == 0 with watch revision

---

clientv3/concurrency/election.go
integration/v3election_grpc_test.go

Weaken TestV3ElectionObserve so it only checks that it observes a strictly
monotonically ascending leader transition sequence following the first
observed leader. First, the Observe will issue the leader channel before
getting a response for its first get; the election revision is only bound
after returning the channel. So, Observe can't be expected to always
return the leader at the time it was started.  Second, Observe fetches
the current leader based on its create revision, but begins watching on its
ModRevision; this is important so that elections still work in case the
leader issues proclamations following a compaction that exceeds its
creation revision. So, Observe can't be expected to return the entire
proclamation sequence for a single leader.
Fixes #7749

integration: permit dropping intermediate leader values on observe

---

etcdserver/api/v2http/client.go
etcdserver/api/v2http/client_test.go

v2http: remove deprecated /v2/machines path

---

clientv3/watch.go

Turns out the optimization to ignore setting the init rev for
current revision watches breaks some ordering assumptions. Since
Watch only returns a channel once it gets a response, it should
bind the revision at the time of the first create response.
Was causing TestWatchReconnInit to fail.

clientv3: set current revision to create rev regardless of CreateNotify

---

clientv3/concurrency/session.go
clientv3/example_lease_test.go
clientv3/integration/lease_test.go
clientv3/lease.go
etcdctl/ctlv3/command/lease_command.go
integration/cluster_proxy.go
proxy/grpcproxy/lease.go
tools/benchmark/cmd/lease.go
tools/functional-tester/etcd-runner/command/lease_renewer_command.go

clientv3: don't halt lease client if there is a lease error 

---

etcdserver/raft.go
etcdserver/raft_test.go
etcdserver/server.go

Problem is:
`Step1`: `etcdserver/raft.go`'s `Ready` process routine sends config-change entries via `r.applyc <- ap` (https://github.com/coreos/etcd/blob/master/etcdserver/raft.go#L193-L203)
`Step2`: `etcdserver/server.go`'s `*EtcdServer.run` routine receives this via `ap := <-s.r.apply()` (https://github.com/coreos/etcd/blob/master/etcdserver/server.go#L735-L738)
`StepA`: `Step1` proceeds without sync, right after sending `r.applyc <- ap`.
`StepB`: `Step2` proceeds without sync, right after `sched.Schedule(s.applyAll(&ep,&ap))`.
`StepC`: `etcdserver` tries to sync with `s.applyAll(&ep,&ap)` by calling `rh.waitForApply()`.
`rh.waitForApply()` waits for all pending jobs to finish in `pkg/schedule`
side. However, the order of `StepA`,`StepB`,`StepC` is not guaranteed. It
is possible that …

etcdserver: ensure waitForApply sync with applyAll

---

etcdserver/raft.go

@heyitsanthony pointed out sending to `raftDone` blocks on raft shutdown, so just return when the raft is stopped.
Thanks!

etcdserver: do not block on raft stopping

---

tools/functional-tester/build
tools/functional-tester/etcd-tester/checks.go
tools/functional-tester/etcd-tester/etcd_runner_stresser.go
tools/functional-tester/etcd-tester/key_stresser.go
tools/functional-tester/etcd-tester/lease_stresser.go
tools/functional-tester/etcd-tester/main.go
tools/functional-tester/etcd-tester/stresser.go
tools/functional-tester/etcd-tester/tester.go
tools/functional-tester/etcd-tester/v2_stresser.go

etcd tester runs etcd runner as a separate binary.
it signals sigstop to the runner when tester wants to stop stressing.
it signals sigcont to the runner when tester wants to start stressing.
when tester needs to clean up, it signals sigint to runner.
FIXES #7026

etcd-tester: integrate etcd runner into etcd tester

---

etcdserver/api/v3client/v3client.go

Printing the values in ctx.String() will data race if the value
is mutable and doesn't implement String(), which seems to be common.
Instead, just return a fixed string instead of computing it; v3client
watches don't need as much flexibility for creating separate strings,
so separate ctx strings probably aren't necessary at this point.
Fixes #7811

v3client: wrap watch ctxs with blank ctx

---

integration/v3_grpc_test.go

Fix https://github.com/coreos/etcd/issues/7835.

integration: match more TLS errors for wrong certs

---

Documentation/v2/docker_guide.md

Supersedes #7825
Partially addresses #7843

Documentation/v2: pin docker guide to use latest 2.3.x

---

embed/etcd.go
embed/serve_test.go

If 'StartEtcd' returns before starting gRPC server
(e.g. mismatch snapshot, misconfiguration),
receiving from grpcServerC blocks forever. This patch
just closes the channel to not block on grpcServerC,
and proceeds to next stop operations in Close.
This was masking the issues in https://github.com/coreos/etcd/issues/7834

embed: fix blocking Close before gRPC server start

---

raft/README.md

Per @xiang90's comment on https://github.com/coreos/etcd/pull/7515#issuecomment-287126104, this adds Chain Core to the notable users list for the raft package.

raft: add chain core to notable users list

---

integration/v3_lease_test.go

A follower in 3-node cluster could apply 'LeaseRevoke'
later (e.g. fetch TTL with TimeToLive, then revoke applies).
Just retry max 5-times.
Fix https://github.com/coreos/etcd/issues/7817.

integration: ensure revoke completes before TimeToLive

---

etcdserver/server.go
etcdserver/server_test.go

previously, apply() doesn't set consistIndex for EntryConfChange type.
this causes a misalignment between consistIndex and applied index
where EntryConfChange entry results setting applied index but not consistIndex.
suppose that addMember() is called and leader reflects that change.
1. applied index and consistIndex is now misaligned.
2. a new follower node joined.
3. leader sends the snapshot to follower
where the applied index is the snapshot metadata index.
4. follower node saves the snapshot and database(includes consistIndex) from leader.
5. restarting follower loads snapshot and database.
6. follower checks snapshot metadata index(same as applied index) and database consistIndex,
finds them don't match, and then panic.
FIXES #7834

etcdserver: apply() sets consistIndex for any entry type

---

clientv3/concurrency/stm.go

semver paranoia via upgrading zetcd

concurrency: provide old STM functions as deprecated

---

clientv3/concurrency/session.go
clientv3/example_lease_test.go
clientv3/integration/lease_test.go
clientv3/lease.go
etcdctl/ctlv3/command/lease_command.go
integration/cluster_proxy.go
proxy/grpcproxy/lease.go
tools/benchmark/cmd/lease.go
tools/functional-tester/etcd-runner/command/lease_renewer_command.go

This reverts commit fbbc4a4979b256125d2238f6325ad86e7f1b58bd, reversing
changes made to f254e383859a2939d5929346f6595549f424f7c5.
Fixes #7851

Revert "Merge pull request #7732 from heyitsanthony/lease-err-ka"

---

Documentation/upgrades/upgrade_3_2.md

For https://github.com/coreos/etcd/pull/7852.

Documentation/upgrades: revert KeepAlive interface change

---

integration/v3_grpc_test.go

Fix https://github.com/coreos/etcd/issues/7865.
It is also possible to have mismathced key while
renaming directories.

integration: clean up TLS reload tests, fix no-file while renaming

---

clientv3/balancer.go
integration/bridge.go

If the balancer update notification loop starts with a downed
connection and endpoints are switched while the old connection is up,
the balancer can potentially wait forever for an up connection without
refreshing the connections to reflect the current endpoints.
Instead, fetch upc/downc together, only caring about a single transition
either from down->up or up->down for each iteration
Simple way to reproduce failures: add time.Sleep(time.Second) to the
beginning of the update notification loop.
Found while investigating #7823, but not a fix.

clientv3: don't race on upc/downc/switch endpoints in balancer

---

Documentation/dev-internal/logging.md
Documentation/op-guide/configuration.md
Documentation/op-guide/grpc_proxy.md
Documentation/production-users.md
Documentation/reporting_bugs.md
Documentation/v2/README.md
Documentation/v2/api_v3.md
Documentation/v2/backward_compatibility.md
Documentation/v2/configuration.md
Documentation/v2/libraries-and-tools.md
Documentation/v2/reporting_bugs.md
Documentation/v2/rfc/v3api.md
README.md
etcdctl/README.md
etcdctl/READMEv2.md

Replace https://github.com/coreos/etcd/pull/7864.
Fix https://github.com/coreos/etcd/issues/7861.
Only cherry-pick the changes for backporting.
Will integrate with `marker` once it can handle the `[...]` in markdown headers.

*: fix broken links in markdown

---

integration/fixtures-expired/gencerts.sh

To make gencerts.sh script safer.

integration/fixtures-expired: do not force 'rm'

---

clientv3/integration/lease_test.go
integration/cluster_proxy.go

500ms keepalive delay on proxy side causes client to sometimes send
a second keepalive since it waits more than 500ms for the first response.
Fixes #7658
No longer shows up when burning TestLeaseWithRequireLeader.
Also includes a proxy integration fix from the punted lease patch to take care of occasional goroutine leaks from not closing proxy the lease client.

clientv3/integration: drain keepalives before waiting for leader loss

---

.travis.yml
Documentation/op-guide/configuration.md
Documentation/v2/configuration.md
scripts/install-marker.sh
test

Fix https://github.com/coreos/etcd/issues/7123.

*: run 'marker' in CI

---

compactor/compactor.go
compactor/compactor_test.go

compactor: Make periodic compactor runs every hour

---

mvcc/backend/backend.go

backend: print snapshotting duration warning every 30s 

---

raft/raft.go
raft/raft_test.go

I found that enabling the `CheckQuorum` flag led to spurious leader elections when new nodes joined. It looks like in the time between a new node joining the cluster, and that node first communicating with the leader, the quorum check could fail because the new node looks inactive. To solve this, set the `RecentActive` flag when nodes are first added. This gives a grace period for the node to communicate before it causes the quorum check to fail.
This seems like a decent way to solve the problem, but please feel free to suggest other approaches instead.

raft: Set the RecentActive flag for newly added nodes

---

clientv3/watch_test.go

Fix watch_test.go TestEvent
Prior to This fix the isModify case of the table driven test was never checked.

Fix watch_test.go TestEvent

---

mvcc/backend/backend.go
mvcc/backend/metrics.go

backend: add prometheus metric for large snapshot duration.

---

embed/etcd.go
embed/serve.go

Passing canceled context to close existing idle connections only once and to not delay the server shutdown. And make `embed.Etcd.Peers` non-exported (need release note).
c.f. https://github.com/coreos/etcd/issues/6174

embed: gracefully close peer handler

---

bill-of-materials.json
scripts/updatebom.sh

Need this script when we add external dependencies.
c.f. https://github.com/coreos/etcd/pull/7896

scripts: add 'BOM' update script

---

clientv3/client.go
clientv3/lease.go

clientv3: Do no stop keep alive loop by server side errors

---

etcdserver/api/v3rpc/util.go

There is the same case at line 69.

v3rpc: remove duplicated error case for lease.ErrLeaseNotFound

---

etcdserver/raft.go
etcdserver/raft_test.go
etcdserver/server.go
etcdserver/server_test.go
etcdserver/util.go
snap/db.go

In the case that follower recieves a snapshot from leader
and crashes before renaming xxx.snap.db to db but after
snapshot has persisted to .wal and .snap, restarting
follower results loading old db, new .wal, and new .snap.
This will causes a index mismatch between snap metadata index
and consistent index from db.
This pr forces an ordering where saving/renaming db must
happen after snapshot is persisted to wal and snap file.
this guarantees wal and snap files are newer than db.
on server restart, etcd server checks if snap index > db consistent index.
if yes, etcd server attempts to load xxx.snap.db where xxx=snap index
if there is any and panic other wise.
FIXES #7628

etcdserver: renaming db happens after snapshot persists to wal and snap files

---

tools/functional-tester/etcd-runner/command/election_command.go
tools/functional-tester/etcd-runner/command/global.go
tools/functional-tester/etcd-runner/command/lock_racer_command.go

election runner can deadlock in atomic release().
suppose election runner has two clients A and B.
if A is a leader and B is a follower, B obtains lock
for release() and waits for A to close(nextc) which signal
next round is ready. However, A can only close(nextc) if it
obtains lock for release(); hence deadlock.
this pr removes atomicity of validate() and release() in global.go
and gives the responsibility of locking to each runner.
FIXES #7891

etcd-runner: remove mutex on validate() and release() in global.go

---

pkg/srv/srv.go

So that 'terr' can be returned later.

pkg/srv: fix error checks from resolveTCPAddr

---

etcdserver/backend.go
etcdserver/config.go
etcdserver/server.go
etcdserver/server_test.go
etcdserver/storage.go
etcdserver/util.go
pkg/mock/mockstorage/storage_recorder.go
snap/db.go

Computing the snapshot file path is error prone; snapshot recovery was
constructing file paths missing a path separator so the snapshot
would never be loaded. Instead, refactor the backend path handling
to use helper functions where possible.

snap, etcdserver: tighten up snapshot path handling

---

e2e/ctl_v3_elect_test.go
e2e/ctl_v3_lock_test.go
e2e/etcd_test.go
integration/cluster_test.go
integration/logger_test.go
pkg/expect/expect.go

Dump all console output and SIGQUIT data to debug #6464 and #6934.

e2e: more debugging output for lock and elect tests

---

mvcc/backend/backend.go
mvcc/backend/config_default.go
mvcc/backend/config_linux.go
mvcc/backend/config_windows.go

boltdb on windows allocates a file with the full mmap size even if the
db is empty. Force the initial mmap size to 0 so there's no huge initial
db file on windows.
Fixes #7910
Currently untested on windows; will give it a spin/unWIP it in a day or two when I can get to my windows VM.
/cc @danielfaust

backend: force initial mmap size to 0 for windows

---

pkg/osutil/interrupt_unix.go
pkg/osutil/osutil.go
pkg/osutil/osutil_test.go
pkg/osutil/signal.go
pkg/osutil/signal_linux.go

The go runtime won't always reinstall the default signal handler on the
SIGTERM path, so it's possible the signal won't terminate the process.
Instead, permit etcd to exit normally after processing a signal.

osutil: force SIG_DFL before resending terminating signal 

---

pkg/osutil/signal.go

CI didn't catch this :0
With that build tag

pkg/osutil: fix missing 'syscall' import

---

.travis.yml

Can't use the same `test` script for Windows (exited with `go test: -race requires cgo; enable cgo by setting CGO_ENABLED=1`)

travis: test builds in other OSes

---

e2e/ctl_v3_elect_test.go
e2e/ctl_v3_lock_test.go
e2e/etcd_test.go

Gets backtrace by sending SIGQUIT if Close hangs after sending a SIGINT.
Bug showed up in CI again but it's hanging on an expected close so the SIGQUITs won't fire.

e2e: Stop() lock/elect etcdctl process if Close times out

---

tools/functional-tester/etcd-agent/agent.go
tools/functional-tester/etcd-tester/cluster.go
tools/functional-tester/etcd-tester/main.go

Persistent data should be configured in agent side.
There is no need to specify the data-dir in tester side.

functional-tester: use log-dir as data-dir in etcd-agent

---

tools/benchmark/cmd/stm.go

Simple benchmarking for RPC mutexes by further hijacking the STM benchmark.

benchmark: add rpc mutexes to stm benchmark

---

tools/local-tester/bridge/bridge.go

Injects transmit and receive latencies.
For testing lock latencies.

bridge: add tx-delay and rx-delay

---

proxy/tcpproxy/userspace.go

The switch to *net.SRV for endpoints caused the ready string to emit
pointers instead of endpoint strings.
Fixes #7942

tcpproxy: display endpoints, not pointers, in ready to proxy string

---

etcdmain/config_test.go
pkg/transport/listener.go
tools/functional-tester/etcd-tester/main.go

Fixes CI, some other fixes from go report https://goreportcard.com/report/github.com/coreos/etcd#misspell

*: remove unused, fix typos

---

integration/v3_lease_test.go

Fix https://github.com/coreos/etcd/issues/7952.

integration: bump up 'TestV3LeaseRequireLeader' timeout to 5-sec

---

.travis.yml
ROADMAP.md
e2e/etcd_release_upgrade_test.go
test

Once merged, we can create a branch `release-3.2`.

*: bump up test Go runtime, etcd versions before 3.2 release

---

etcdctl/README.md
etcdctl/ctlv3/command/lock_command.go

The lock command is clumsy to use from the command line, needing mkfifo,
wait, etc. Instead, make like consul and support launching a command if
one is given.
(cf. https://github.com/coreos/etcd/issues/2855#issuecomment-294260572)

etcdctl: support exec on lock

---

clientv3/integration/txn_test.go
embed/config.go
embed/etcd.go
etcdmain/config.go
etcdmain/help.go
etcdserver/api/v3rpc/key.go
etcdserver/config.go
integration/cluster.go
integration/v3_grpc_test.go

etcdserver: add --max-txn-ops flag

---

embed/config.go
embed/etcd.go
etcdmain/config.go
etcdmain/help.go
etcdserver/api/v3rpc/grpc.go
etcdserver/config.go
etcdserver/server.go
etcdserver/v3_server.go
integration/cluster.go
integration/v3_grpc_test.go

etcd: make max request bytes configurable

---

e2e/etcd_spawn_cov.go
etcdctl/ctlv2/ctl_cov.go
etcdctl/ctlv3/ctl_cov.go

etcdctl, e2e: use 0xe7cd as argument separator in cov-enabled etcdctl

---

mvcc/kvstore.go
mvcc/kvstore_bench_test.go
mvcc/kvstore_test.go

Loading all keys at once would cause etcd to use twice as much
memory than it would need to serve the keys, causing RSS to spike on
boot. Instead, load the keys into the mvcc by chunk. Uses pipelining
for some concurrency.
Fixes #7822
tmpfs benchmarks:
Before:
```
go test -v -run=BenchmarkStoreRestore -bench=BenchmarkStoreRestore
BenchmarkStoreRestoreRevs1-8     1000000      4446 ns/op     814 B/op      7 allocs/op
BenchmarkStoreRestoreRevs10-8     200000     11053 ns/op    5397 B/op     38 allocs/op
BenchmarkStoreRestoreRevs20-8     100000     17458 ns/op   10518 B/op     69 allocs/op
```
After:
```
go test -bench=BenchmarkStoreRestore -run=BenchmarkStoreRestore
BenchmarkStoreRestoreRevs1-8    	 1000000	      2464 ns/op	     641 B/op	       6 allocs/op
BenchmarkStoreRestoreRevs10-8 …
```

mvcc: chunk reads for restoring

---

mvcc/backend/batch_tx.go
mvcc/backend/read_tx.go

Large fetches hold the lock when they do not need to do so.

backend: don't hold boltdb read txn lock on cursor scanning

---

mvcc/kvstore.go
mvcc/kvstore_bench_test.go

Called on every entry apply and boltdb requests aren't free.
Old:
```sh
$ go test -bench=Consistent -v -count=5 -run=Consistent
BenchmarkConsistentIndex-8       3000000               452 ns/op              96 B/op          3 allocs/op
BenchmarkConsistentIndex-8       3000000               457 ns/op              96 B/op          3 allocs/op
BenchmarkConsistentIndex-8       3000000               452 ns/op              96 B/op          3 allocs/op
BenchmarkConsistentIndex-8       3000000               466 ns/op              96 B/op          3 allocs/op
BenchmarkConsistentIndex-8       3000000               446 ns/op              96 B/op          3 allocs/op
PASS
ok      _/home/anthony/go/src/github.com/coreos/etcd/mvcc       12.831s
```
New:
```sh
$ GOPATH=~/etcd-gopath/ go test …
```

mvcc: cache consistent index

---

Documentation/op-guide/performance.md

It's been a year, time to refresh with 3.2.0 data.

op-guide: update performance.md

---

clientv3/main_test.go

There's a workaround by running -run=Test but this periodically
comes up as an issue, so have `go test` only run Test* to stem
the complaints.
Fixes #8000

clientv3: do not launch cluster on go test without explicit -run

---

etcdserver/server.go

Lots of garbage db files in #7957. Should purge.

etcdserver: purge old snap.db files

---

tools/benchmark/cmd/mvcc-put.go
tools/benchmark/cmd/util.go

This commit adds a new option --batch to `benchmark mvcc put`. A
number specified with this option will be used as a number of written
keys in a single transaction. It will be useful for checking the
effect of the batching.
This commit also changes the interface of the report package for
dealing with the batched operations.

benchmark, pkg: a new option of mvcc --batch for enlarging a single txn

---

raft/status.go

return leaderTransferee when get raft status
get more detail information about raft status

return leaderTransferee at raft status

---

clientv3/client.go
clientv3/integration/dial_test.go
integration/cluster.go

Dialing out without specifying TLS creds but giving https uses some
default behavior that depends on passing an endpoint with https to
Dial(), so it's not enough to completely rely on the balancer to supply
endpoints.
Fixes #8008

clientv3: use Endpoints[0] to initialize grpc creds

---

Documentation/dev-guide/api_grpc_gateway.md
e2e/v3_curl_test.go
etcdserver/api/v3rpc/key.go

Includes fix for crash in #7889

e2e: test txn over grpc json

---

e2e/ctl_v2_test.go

GetUser doesn't go through quorum, so issuing a user get
to any member of a cluster get stale data from a slow member.
Instead, use a single member cluster for the test.
Fixes #7993

e2e: make CtlV2GetRoleUser non-quorum

---

test

Don't throw away all coverage data if some profiles are corrupted.

test: incrementally merge coverage files

---

rafthttp/peer.go
rafthttp/stream.go
rafthttp/stream_test.go
rafthttp/transport.go

Please consider this small improvement: ```rafthttp.streamReader``` dial timeout was hardcoded to 100ms which may be too frequent for some use-cases of ```rafthttp``` library. I would like to have this setting configurable.

rafthttp: configurable stream reader retry timeout

---

Documentation/dev-guide/api_reference_v3.md
scripts/genproto.sh

Was missing the new cancel_reason field. Also includes updated protodoc
sha to fix generating documentation for upcoming txn compare range patchset.
Split into a separate PR from the txn compare range one so it's easier to backport into 3.2.0

Documentation, scripts: update RPC API docs

---

Documentation/dev-guide/apispec/swagger/rpc.swagger.json
scripts/genproto.sh

Changes to the genproto to support splitting out the grpc-gateway broke
swagger generation.

scripts, Documentation: fix swagger generation

---

clientv3/example_metrics_test.go
contrib/raftexample/raft.go
e2e/ctl_v3_elect_test.go
etcdctl/ctlv3/command/check.go
etcdserver/server.go
etcdserver/stats/leader.go
etcdserver/stats/server.go
integration/v3_grpc_test.go
rafthttp/functional_test.go
rafthttp/transport_test.go
test
tools/benchmark/cmd/util.go
tools/functional-tester/etcd-runner/command/election_command.go
tools/functional-tester/etcd-runner/command/global.go
tools/functional-tester/etcd-runner/command/lease_renewer_command.go
tools/functional-tester/etcd-runner/command/lock_racer_command.go
tools/functional-tester/etcd-runner/command/watch_command.go

Was iterating over every file, reloading everything. Instead,
analyze the package directories. On my machine, the time for
vet checking goes from 34s to 3s. Scans more code too.

test: speedup and strengthen go vet checking

---

pkg/osutil/signal.go
pkg/osutil/signal_linux.go
test

Was causing etcd to terminate before finishing writing its coverage profile.

test, osutil: disable setting SIG_DFL on linux if built with cov tag

---

mvcc/kvstore_bench_test.go
mvcc/kvstore_txn.go

Saves an allocation when creating a storeTxnWrite.
Before:
```
BenchmarkStoreTxnPut-4            	  200000	      7728 ns/op	    1515 B/op	      16 allocs/op
BenchmarkWatchableStoreTxnPut-4   	  200000	      7934 ns/op	    1580 B/op	      18 allocs/op
```
After:
```
BenchmarkStoreTxnPut-4            	  200000	      7319 ns/op	    1498 B/op	      15 allocs/op
BenchmarkWatchableStoreTxnPut-4   	  200000	      7558 ns/op	    1565 B/op	      17 allocs/op
```

mvcc: don't use pointer for storeTxnRead in storeTxnWrite

---

test

this should fix travis unit tests

test: fix package splitting when appending REPO_PATH to tests

---

etcdserver/api/v3rpc/util.go

Switch statement had poor coverage, use a map instead

v3rpc: use map for translating errors to grpc errors

---

pkg/fileutil/fileutil_test.go
pkg/fileutil/preallocate.go

fallocate will return EINVAL, causing zeroing to the end of a
0 byte file to fail.
Fixes #8045

fileutil: return immediately if preallocating 0 bytes

---

pkg/fileutil/lock_linux_test.go
pkg/fileutil/preallocate_test.go

syscall.Flock fallback and preallocExtendTrunc
via codecov:
https://codecov.io/gh/coreos/etcd/src/fb086ef13f6ef78d497c2aec6b6070781e2d0543/pkg/fileutil/preallocate.go
https://codecov.io/gh/coreos/etcd/src/fb086ef13f6ef78d497c2aec6b6070781e2d0543/pkg/fileutil/lock_flock.go

fileutil: test some fallback functionality

---

mvcc/metrics_txn.go

Txns were previously only bumping the txn counter; now bumps all operation
counters.
/cc @xiang90

mvcc: count range/put/del operations for txns

---

auth/simple_token.go
auth/store.go
etcdserver/apply.go
etcdserver/apply_auth.go
etcdserver/server.go
integration/v3_auth_test.go

Current leases can be revoked by anyone. This PR limits the users who can revoke leases. If the user isn't granted write permission of keys which are attached the lease, the revoking request will be denied.
/cc @yudai

protecting lease revoking with auth

---

Documentation/op-guide/grafana.json

https://github.com/grpc-ecosystem/go-grpc-prometheus/blob/master/server_reporter.go
`grpc_code` is only for `grpc_server_handled_total`. And no need to match `grpc_code` for handled streams. When the stream gets canceled, `grpc_code` is `Unavailable` (e.g. `grpc_server_handled_total{grpc_code="Unavailable",grpc_method="LeaseKeepAlive",grpc_service="etcdserverpb.Lease",grpc_type="bidi_stream"}`).

Documentation/op-guide: fix 'grpc_code' field in metrics

---

mvcc/watchable_store.go
mvcc/watchable_store_test.go

Current tests don't normally trigger the watch victim path because the
constants are too large; set the constants to small values and hammer
the store to cause watch delivery delays.

mvcc: test watch victim/delay path

---

etcdserver/metrics.go
etcdserver/server.go

Fix https://github.com/coreos/etcd/issues/8050.
e.g.
```
curl -L http://localhost:2379/metrics | grep lease
etcd_debugging_server_lease_expired_total 3
```

etcdserver: add leaseExpired metrics

---

etcdserver/api/v2http/client.go
etcdserver/api/v2http/client_test.go

This reverts commit 2bb33181b6c8fbe8109fc668a19ce4ab46c605ec. python-etcd
seems to depend on /v2/machines and the maintainer vanished. Plus, it is
prefixed with /v2/ so it probably can't be deprecated anyway.
/cc @xiang90

v2http: put back /v2/machines and mark as non-deprecated

---

clientv3/lease.go
clientv3/watch.go

private structs such as keepAlive and watchGrpcStream shouldn't expose a public Close() method.

clientv3: change Close() to close() for keepAlive and watchGrpcStream

---

etcdserver/apply.go
integration/v3_grpc_test.go
mvcc/kv.go

Fixes inconsistencies from writes interfering with read-only txns.

etcdserver: use same ReadView for read-only txns

---

tools/benchmark/cmd/watch.go

Hangs at/above 100 streams due to a hardcoded constant `defaultMaxStreamsClient` in grpc (having multiple grpc connections doesn't seem to make a difference)
Supersedes #7922, #8057

benchmark: refactor watch benchmark

---

rafthttp/http.go
rafthttp/msg_codec.go

v2 snapshots were hitting the 512MB message decode limit, causing
sending snapshots to new members to fail for being too big.

rafthttp: permit very large v2 snapshots

---

Documentation/upgrades/upgrade_3_0.md
Documentation/upgrades/upgrade_3_1.md
Documentation/upgrades/upgrade_3_2.md

Let's link the previous guides, rather than hardcoded release tags, some might be outdated.

Documentation/upgrades: link to previous guides

---

e2e/ctl_v2_test.go
etcdctl/ctlv2/command/cluster_health.go

ctlv2: report unhealthy in cluster-health if any node is unavailable

---

etcdserver/config.go
etcdserver/config_test.go

The old error was not clear about what URLs needed to be added, sometimes
truncating the list. To make it clearer, print out the missing entries
for --initial-cluster and print the full list of initial advertise peers.
Fixes #8079 and #7927
Old output:
```
etcdmain: --initial-cluster must include etcd01=http://172.28.0.4:2380 given --initial-advertise-peer-urls=http://172.28.0.4:2380
```
New output:
```
etcdmain: --initial-cluster has etcd01=http://172.28.0.2:2380 but missing from --initial-advertise-peer-urls=http://172.28.0.4:2380
```

etcdserver: better warning when initial-cluster doesn't match advertise urls

---

contrib/raftexample/raft.go

Save the snapshot index to the WAL before saving the snapshot to the
filesystem. This ensures that wal.Open is only ever called with a 
snapshot that was previously saved to the WAL.
Fixes #8082.

contrib/raftexample: save snapshot to WAL first

---

scripts/build-aci

The appc discovery spec states that the architecture specifier in the ACI
image file name will be an ACI architecture value.  Our build scripts were
using GOARCH in the image name, which is incorrect for arm64/aarch64.
See: https://github.com/appc/spec/blob/master/spec/discovery.md

build-aci: Fix ACI image name

---

lease/lessor.go

Fix https://github.com/coreos/etcd/issues/8097.

lease: rate limit revoke runLoop

---

clientv3/watch.go

The "too slow" comment is rather vague. If the server closes
the watch for being too slow (it doesn't seem to any more), the
watch client should gracefully resume instead of forcing the
user to handle it.
Also removed the 'opts' comment since it wasn't being maintained.
via https://groups.google.com/forum/#!topic/etcd-dev/RdwV1UPUKyg

clientv3: clarify Watch close conditions

---

Documentation/op-guide/grafana.json

This fixes failed RPC rate query, where we do not need
subtraction because we already query by the status code.
Also adds grpc_method to make it more specific. Most of the
time, the failure recovers within 10-second, which is our
Prometheus scrap interval, so 'rate' query might not cover
that time window, showing as 0s, but still shows up in the graph.
Before
After
Also fixes RPC rate query.

Documentation/op-guide: fix failed RPC rate, leader election metrics

---

clientv3/concurrency/mutex.go

The uncontended path for a mutex would fetch the minimum
revision key on the prefix after creating its entry in
the wait list. This fetch can be rolled into the txn for
creating the wait key, eliminating a round-trip for immediately
acquiring the lock.

concurrency: fetch current lock holder when creating waitlist key

---

glide.lock
glide.yaml

Also ignores appengine import from the grpc-gateway examples which
were causing glide errors on x/crypto when fetching imports.

vendor: update glide.yaml to use probing 0.0.1

---

integration/v3_lease_test.go
lease/lessor.go
lease/lessor_test.go

Address https://github.com/coreos/etcd/issues/8096.

lease: randomize expiry on initial refresh call

---

Documentation/dev-guide/apispec/swagger/rpc.swagger.json
auth/store.go
e2e/v2_curl_test.go
e2e/v3_curl_test.go
scripts/genproto.sh

The allows native use of grpc-gateway authorization header, providing direct access to metadata context while using intuitive naming.
Fixes #6643

auth: support "authorization" token for grpc-gateway

---

embed/etcd.go
etcdserver/backend.go
etcdserver/raft.go
etcdserver/server.go
etcdserver/server_test.go
integration/cluster.go

ServerConfig is owned by etdcserver and unshared, so don't pass or store by
pointer. Also removes duplicated field 'snapCount'.

etcdserver, embed, integration: don't use pointer for ServerConfig

---

etcdserver/server_test.go

via https://travis-ci.org/coreos/etcd/jobs/243406529, fixes
```
--- FAIL: TestSyncTimeout (0.02s)
server_test.go:837: action = [], want [{Propose blocked []}]
```

etcdserver: use RecorderStream for TestSyncTimeout to avoid missing action

---

integration/metrics_test.go
mvcc/kvstore.go

mvcc: set db size metric on restore

---

mvcc/index.go
mvcc/kvstore.go
mvcc/kvstore_test.go

Clobbering the mvcc kvindex with new keyIndexes for each restore
chunk would cause index corruption by dropping historical information.

mvcc: restore into tree index with one key index

---

proxy/grpcproxy/lease.go

Hello,
```
Problem Observed
----------------
When there is no etcd process behind the proxy,
clients repeat resending lease grant requests without delay.
This behavior can cause abnormal resource consumption on CPU/RAM and
network.
Problem Detail
--------------
`LeaseGrant()` uses a bare protobuf client to forward requests.
However, it doesn't use `grpc.FailFast(false)`, which means the method returns
an `Unavailable` error immediately when no etcd process is available.
In clientv3, `Unavailable` errors are not considered the "Halt" error,
and library retries the request without delay.
Both clients and the proxy consume much CPU cycles to process retry requests.
Resolution
----------
Add `grpc.FailFast(false))` to `LeaseGrant()` of the `leaseProxy`.
This makes the proxy not to return …
```

grpcproxy: Disable fast fail on lease grant call to cluster

---

test

This fixes bash syntax on '[[ -n ${VAR} ]]', which is
always true. Replacing with '[[ ${VAR} ]]'.
I also see CI is failing to download release binaries
but exit code doesn't trigger CI job failure.
We need 'FAIL' string.
It' failing here https://semaphoreci.com/coreos/etcd/branches/pull-request-8133/builds/2
```
Downloading etcd--linux-amd64.tar.gz
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  U   ploadTotal         Spent    Left  Speed
0     0    0     0    0     0    0        0 --:--:-----::- -- --:--:   0
--0     0        0 0       0    0    0      0 --:--:-- --:--:-- --:--:-0
-   cu: rl(22) T rheueeqsted URL ruretned erro 4r:04 Not Found
FAIL with 22
```

test: 'FAIL' on release binary download failure

---

test
tools/functional-tester/etcd-tester/main.go
tools/functional-tester/etcd-tester/tester.go

Fix https://github.com/coreos/etcd/issues/8126.
Changed Semaphore command
> RELEASE_TEST=y INTEGRATION=y PASSES="build unit release integration_e2e functional" ./test 2>&1 | tee test.log
Result: https://semaphoreci.com/coreos/etcd/branches/pull-request-8128/builds/12

*: run basic functional-tester cases to test script

---

Documentation/op-guide/monitoring.md

Rather than 'etcd_debugging_' ones that might change
in the future.

Documentation: use 'etcd_disk_' metrics in monitoring

---

etcdctl/README.md
etcdctl/ctlv3/command/ep_command.go

Query the cluster for endpoints when given --cluster for the endpoint commands.
Fixes #8117

etcdctl: use cluster endpoints when passed --cluster

---

integration/metrics_test.go
mvcc/kvstore.go
mvcc/kvstore_txn.go
mvcc/metrics.go

mvcc: use GaugeFunc metric to load db size when requested

---

etcdctl/ctlv3/command/compaction_command.go

Found via https://github.com/coreos/etcd/pull/8153/commits/9a7a9f4de6e4a60245a6ee0e098a1568ce810bd4#r123566851.

etcdctl/ctlv3: remove unnecessary 'return'

---

integration/v3_lease_test.go
lease/lessor.go
lease/lessor_test.go

lessor: extend leases on promote if expires will be rate limited

---

e2e/ctl_v3_kv_test.go

Semaphore is failing with context exceeded errors and dial timeouts, only
returning an "Error: ..." from expect on etcdctl. So, only test for
"Error:" instead of grpc internal errors.

e2e: accept more kinds of errors in CRL test

---

cmd/vendor/google.golang.org/grpc/rpc_util.go
cmd/vendor/google.golang.org/grpc/transport/http2_client.go
glide.lock
glide.yaml

Fix https://github.com/coreos/etcd/issues/8141.

vendor: upgrade grpc-go to 1.4.2

---

compactor/compactor.go
compactor/compactor_test.go
compactor/periodic.go
compactor/periodic_test.go
compactor/revision.go
compactor/revision_test.go
embed/config.go
embed/etcd.go
etcdmain/config.go
etcdmain/help.go
etcdserver/config.go
etcdserver/server.go

Hello,
For #8098, adding a new compactor named `Revisional`, which runs compaction every 5 minutes.
To switch the compactor from the default `Periodic`, I added a new option `--auto-compaction-mode` as well.
Some Notes:
* Should `Periodic` run compaction every 5 minutes as well for consistency? (currently it runs hourly)
* The new option might be little confusing. Instead of numbers, we might want to use human readable labels such as `periodic` and `revisional`.

Compactor: Add Revisional compactor

---

clientv3/concurrency/stm.go

Update the comment of NewSTM function
Signed-off-by: Hui Kang <kangh@us.ibm.com>

Default stm isolation level is serializable snapshot isolation

---

compactor/compactor_test.go
compactor/revision_test.go

For #8182
```
Use atomic functions to manipulate `rev` of `fakeRevGetter`
so that the tester goroutine can update the
value without race with the compactor's goroutine.
```

compactor: Fix data race in revision compactor test

---

lease/lessor_test.go

Fix https://github.com/coreos/etcd/issues/8193.

lease: fix racey access to 'leaseRevokeRate'

---

auth/store.go
e2e/ctl_v3_auth_test.go
etcdserver/apply_auth.go

This PR adds a new option `--all-readable` to `etcdctl get`. If the option is passed, etcdctl tries to get all read granted keys from a user specified with `--user`.
For doing it, the first commit changes the semantics of `UserGet()` and `RoleGet()` semantics. Now they can be called by non admin users if the information belongs to the user itself.
Fix https://github.com/coreos/etcd/issues/8157
@hzektser @japhar81 could you check that this is what you want?
/cc @heyitsanthony I'll add e2e test cases for the changes until earlier next week.

allow users to know their roles and permissions

---

clientv3/concurrency/stm.go

concurrency: fix typo in Serializable godoc

concurrency: fix typo in Serializable godoc

---

embed/etcd.go
embed/serve.go

net.Listener says its address is [::] when given 0.0.0.0, breaking
hosts that have ipv6 disabled.
Fixes #8151
Fixes #7961

embed: connect json gateway with user-provided listen address

---

Documentation/dev-guide/experimental_apis.md

No experimental APIs at the moment.
Fixes #8212
/cc @xiang90

dev-guide: update experimental APIs

---

pkg/transport/listener_tls.go

The IP SAN check would always do a DNS SAN check if DNS is given
and the connection's IP is verified. Instead, don't check DNS
entries if there's a matching iP.
Fixes #8206

transport: accept connection if matched IP SAN but no DNS match

---

Documentation/learning/why.md

Since we implemented docs versioning, the default url is
https://cockroachlabs.com/docs/stable instead of
https://cockroachlabs.com/docs. We have a redirect in place
from /docs to /docs/stable, so existing links aren't broken,
but it's a better user experience to bypass the redirect.

Documentation/learning/why: Update link to CockroachDB

---

mvcc/kvstore.go
mvcc/kvstore_test.go
mvcc/kvstore_txn.go

Use 'nil' since it's only reading a single key. Also preallocates
the result slice based on limit / number of revisions fetched.
Fixes #8208 
Slight throughput improvement on serialized benchmarks for large ranges (tested with 1k small keys), but larger stddev. Observed worse performance without the preallocation, possibly due to GC effects.

mvcc: don't allocate end revision while computing range

---

clientv3/client.go
clientv3/config.go

this makes the grpc client connection use a keep-alive.
Linked to [this issue on Kubernetes](https://github.com/kubernetes/kubernetes/issues/46964)

clientv3: add keep-alive to connection

---

embed/etcd.go
error/error.go
etcdserver/api/etcdhttp/base.go
etcdserver/api/etcdhttp/peer.go
etcdserver/api/etcdhttp/peer_test.go
etcdserver/api/etcdhttp/version_test.go
etcdserver/api/v2http/client.go
etcdserver/api/v2http/client_test.go
etcdserver/api/v2http/http.go
integration/cluster.go

Lets --enable-v2=false configurations provide /metrics, /health, etc.
Fixes #8167

*: move v2http handlers without /v2 prefix to etcdhttp

---

tools/local-tester/Procfile
tools/local-tester/bridge.sh
tools/local-tester/bridge/bridge.go

Setting only latency options is a pain since every fault must
be disabled on the command line. Instead, by default start
as a standard bridge without any fault injection.

bridge: make pass-through the default

---

Documentation/dev-guide/api_grpc_gateway.md

Lack of a range_end example has caused some confusion.

dev-guide: document using range_end for prefixes with json

---

etcdserver/api/v3rpc/grpc.go

Issue Observed
----------------
From etcd v3.2.0, custom clients can create up to 100 streams for watch and keepalive. This limitation can cause unexpected behavior to custom clinets/proxies that need to establish many streams.
Issue Detail
------------
etcd v3.2.0 updated the go-grpc library and it had a (breaking) change in it, which caps the default max streams per client to 100 (https://github.com/grpc/grpc-go/pull/1071). 
The official client and proxies do not establish many streams for now. However, this limitation can have impact for third party libraries that need to establish more streams for some reason.
Proposal
---------
In this commit, we simply set the number of streams to the max number. We may have configuration property for this as well.
```
From go-grpc v1.2.0, the …
```

v3rpc: Let clients establish unlimited streams

---

Documentation/docs.md
Documentation/faq.md
Documentation/op-guide/authentication.md
Documentation/op-guide/failures.md
Documentation/op-guide/recovery.md
Documentation/op-guide/security.md
Documentation/op-guide/supported-platform.md
Documentation/op-guide/versioning.md
Documentation/platforms/aws.md
Documentation/platforms/container-linux-systemd.md

Reorganizes sections in README.md, slightly changes some titles, puts
sections at a consistent depth.

Documentation, op-guide: reorganize etcd operation section

---

pkg/testutil/leak.go

Calling a WaitGroup.Done() in a defer will sometimes trigger the leak
detector since the WaitGroup.Wait() will unblock before the defer
block completes. If the leak detector runs before the Done() is
rescheduled, it will spuriously report the finishing Done() as a leak.
This happens enough in CI to be irritating; whitelist it and ignore.
Cf. https://semaphoreci.com/coreos/etcd/branches/master/builds/2144

testutil: whitelist WaitGroup.Done

---

test

Fix https://github.com/coreos/etcd/issues/8211.
tester started before agent starts listening. This patch syncs
with agent listener starts.

test: sync with etcd-agent start in functional_pass

---

e2e/ctl_v3_auth_test.go
etcdctl/ctlv3/command/error.go

Fprintln will insert a space between arguments, so printing "Error: "
would lead to two spaces between the "Error:" and the error string.

etcdctl: remove extra space in error message

---

embed/config.go
embed/etcd.go
etcdmain/config.go
etcdmain/etcd.go
etcdmain/grpc_proxy.go
etcdmain/help.go

Fix https://github.com/coreos/etcd/issues/8060.
https://github.com/prometheus/prometheus/wiki/Default-port-allocations
```
9378 - etcd gRPC Proxy Exporter
9379 - etcd Exporter
```

*: support additional '/metrics' endpoints

---

embed/etcd.go
integration/embed_test.go

Both grpc.Server.Stop and grpc.Server.GracefulStop close the listeners
first, to stop accepting the new connections. GracefulStop blocks until
all clients close their open transports(connections). Unary RPCs
only take a few seconds to finish. Stream RPCs, like watch, might never
close the connections from client side, thus making gRPC server wait
forever.
This patch still calls GracefulStop, but waits up to 10s before manually
closing the open transports.
Address https://github.com/coreos/etcd/issues/8224.
@heyitsanthony  https://github.com/coreos/etcd/issues/8224#issuecomment-315133886
> Is there some way the server can stop the client listener and cut the connections instead of waiting for all clients to disconnect on their own?
This stops all client listeners first (no more new RPCs), …

embed: wait up to request-timeout for pending RPCs when closing

---

Documentation/integrations.md

Closing https://github.com/coreos/etcd/pull/8234.
Closing https://github.com/coreos/etcd/pull/8273.

Documentation/integrations: add 'networking-vpp', raft lib users

---

contrib/raftexample/kvstore.go

contrib/raftexample: use bytes.Buffer.String (no 'string()')

---

e2e/ctl_v3_alarm_test.go
etcdserver/api/etcdhttp/base.go
etcdserver/server.go

Fix https://github.com/coreos/etcd/issues/8207.

/health reports unhealthy when alarm is raised

---

pkg/testutil/leak.go

Leak detector is catching goroutines trying to close files which appear
runtime related:
1 instances of:
syscall.Syscall(...)
/usr/local/golang/1.8.3/go/src/syscall/asm_linux_386.s:20 +0x5
syscall.Close(...)
/usr/local/golang/1.8.3/go/src/syscall/zsyscall_linux_386.go:296 +0x3d
os.(*file).close(...)
/usr/local/golang/1.8.3/go/src/os/file_unix.go:140 +0x62
It's unlikely a user goroutine will leak on file close; whitelist it.

testutil: whitelist os.(*file).close

---

mvcc/kvstore_compaction.go
mvcc/metrics.go

When digging into etcd/boltdb "storage space exceeded" issues, this metric may help answer questions about if/when compactions occured and how much data was freed.

mvcc: Add metric for count of db key revisions compacted.

---

e2e/ctl_v3_txn_test.go
etcdctl/ctlv3/command/txn_command.go

etcdctl:  print "del" instead of "delete" in txn interactive mode

---

proxy/grpcproxy/kv.go

Requests of linearizable range don't touch the cache of grpcproxy. So
incrementing the miss count wouldn't be meaningful.

proxy: don't inc a cache miss count in a case of linearizable range

---

raft/raft.go
raft/raft_test.go

Fixes #8243.
`TestNodeWithSmallerTermCanCompleteElection` tests the scenario where a
node that has been partitioned away (and fallen behind) rejoins the
cluster at about the same time the leader node gets partitioned away.
Previously the cluster would come to a standstill when run with PreVote
enabled.
When responding to `Msg{Pre,}Vote` messages we now include the term from
the message, not the local term. To see why consider the case where a
single node was previously partitioned away and it's local term is now
of date. If we include the local term (recall that for pre-votes we
don't update the local term), the (pre-)campaigning node on the other
end will proceed to ignore the message (it ignores all out of date
messages).
The term in the original message and current local term are the …

raft: introduce/fix TestNodeWithSmallerTermCanCompleteElection

---

clientv3/kv.go
clientv3/ordering/kv.go
clientv3/ordering/kv_test.go
clientv3/ordering/util.go
clientv3/ordering/util_test.go

[#7623](https://github.com/coreos/etcd/issues/7623)
Still a WIP. :skull: Do not merge :skull:

Added initial kv order caching functionality

---

Documentation/docs.md
Documentation/upgrades/upgrading-etcd.md

docs: adding an index for upgrade pages.

---

etcdserver/server.go
etcdserver/v3_server.go

Duplicated error checking code moved into raftRequest/raftRequestOnce.

etcdserver: consolidate error checking for v3_server functions

---

clientv3/integration/watch_test.go
clientv3/watch.go
etcdserver/api/v3rpc/watch.go
proxy/grpcproxy/watcher.go

The change to the RPC needs client changes to avoid closing the channel without sending the compact revision; older clients will only see the close. Possible alternatives are either fake it entirely in the client, send two compact revision responses (one without the cancel, followed by one with), or change the documentation.
Fixes #8231

v3rpc: set Canceled=true on compacted watch

---

e2e/cluster_proxy_test.go
e2e/cluster_test.go
e2e/etcd_process.go
e2e/metrics_test.go
e2e/v2_curl_test.go
embed/etcd.go
etcdmain/etcd.go
etcdmain/grpc_proxy.go
etcdserver/api/etcdhttp/base.go
etcdserver/api/etcdhttp/metrics.go

Fix https://github.com/coreos/etcd/issues/8226.

*: serve '/metrics' in insecure port

---

mvcc/backend/backend_test.go
mvcc/backend/read_tx.go

TestV3HashKV returns hash mismatch because UnsafeForEach traverses mvcc 
at a different order depends on if there are uncommitted items or not.
Before uncommitted items are committed, UnsafeForEach traverses those first before items in boltdb.
After uncommitted items have been committed, UnsafeForEach traverses boltdb first then the recently committed items.
Hence, hash on same items with different order results hash mismatch.

integeration: fix TestV3HashKV hash mismatch

---

Documentation/dev-guide/experimental_apis.md
clientv3/ordering/doc.go
clientv3/ordering/kv.go
etcdmain/grpc_proxy.go

add experimental serializable ordering feature to grpcproxy

---

etcdctl/ctlv3/command/ep_command.go

Close https://github.com/coreos/etcd/pull/8316 and https://github.com/coreos/etcd/pull/8307.
Fix https://github.com/coreos/etcd/issues/8295.

ctlv3: exit non-zero on unhealty ep command

---

mvcc/index.go
mvcc/index_test.go
mvcc/key_index.go
mvcc/key_index_test.go
mvcc/kvstore.go
mvcc/kvstore_test.go

mvcc: fix TestHashKVWhenCompacting hash mismatch

---

clientv3/client.go
clientv3/integration/dial_test.go
clientv3/integration/kv_test.go
clientv3/ordering/kv_test.go
clientv3/ordering/util_test.go
clientv3/retry.go

Was able to get errors out of put in 1.4 but the upgrade to 1.5 grpc seems to have changed error handling; haven't investigated fully. Removed the retry and added a test for at-most-once semantics during disconnects.
/cc @HardySimpson

clientv3: put at most once

---

clientv3/integration/lease_test.go

Fix https://github.com/coreos/etcd/issues/8329.
Different behavior from https://github.com/grpc/grpc-go/pull/1369,
in grpc-go transportMonitor.

clientv3/integration: match context canceled on client close

---

Documentation/v2/README.md

The PR replaces https://github.com/coreos/etcd/pull/8319

docs: revising to match sidebar structure.

---

clientv3/integration/watch_test.go
clientv3/watch.go

Watches were bucketed on string(ctx) for historical reasons;
metadata.FromOutgoingContext should be enough to key watches now.
Fixes #8338

clientv3: use FromOutgoingContext to bucket watches

---

test

OSX dirname doesn't support multiple arguments; use a for loop instead.
Fixes #8359

test: fix PASSES=fmt for OSX

---

raft/raft.go
raft/raft_test.go

raft: reset votes when becomePreCandidate.  because the [poll method](../blob/master/raft/raft.go#L690) wouldn't update grant state when key exists.
here is a case:  
1.  cluster with three node [A, B, C],  all term are 2, with leader A and all logs are replicated.
2.  node A down.   B and C start election at the same time (split votes), both become pre-candidate.
3.  C grant B's pre-vote,  and B grant C's pre-vote.  So, both B and C become candidate, with term 3.
4.  C reject B's vote, and B reject C's vote.  So, B and C are still candidate.   B record votes like (B, true) (C, false),   C record votes like (B, false)  (C, true)
5.  B election-timeout first, start pre-vote.  C grant B's pre-vote.
6.  when B check poll state，it's still (B, true) (C, false).     So, election will continue, …

raft: reset votes when becomePreCandidate

---

e2e/ctl_v3_elect_test.go
e2e/ctl_v3_lock_test.go

No need to read from fd after signalling process to stop and closing
issues an automatic SIGHUP.

e2e: remove SIGQUIT debugging for elect and lock

---

integration/v3_grpc_test.go
proxy/grpcproxy/kv.go

grpcproxy: forward PrevKv flag in Put

---

Documentation/dev-internal/release.md
Documentation/op-guide/container.md

`docker pull`ing quay in Container Linux is still very slow.
We have alternative registry from v3.2.5.
Closing https://github.com/coreos/etcd/pull/8357.

Documentation/op-guide: add gcr.io image as alternative

---

Documentation/op-guide/v2-migration.md
clientv3/integration/maintenance_test.go
clientv3/maintenance.go
e2e/ctl_v3_endpoint_test.go
etcdctl/README.md
etcdctl/ctlv3/command/ep_command.go
etcdctl/ctlv3/command/printer.go
etcdctl/ctlv3/command/printer_fields.go
etcdctl/ctlv3/command/printer_json.go
etcdctl/ctlv3/command/printer_simple.go
etcdctl/ctlv3/command/printer_table.go

Fix https://github.com/coreos/etcd/issues/8348.
Address https://github.com/coreos/etcd/issues/8305.

*: add 'endpoint hashkv' command

---

clientv3/integration/leasing_test.go
clientv3/leasing/kv.go

Gets should retry on transient failure, but the txn inserts a write, skipping
the retry logic in the client. Instead, check the error if the txn should be
retried.
Fixes #8372

leasing: retry on errors from acquire txn

---

Documentation/op-guide/maintenance.md
etcdctl/README.md
etcdctl/ctlv3/command/defrag_command.go

We've run into a number of cases where it would be helpful to be able to defrag when etcd is not running. @heyitsanthony Is this an appropriate place to add such a command, or would it be better if I put it elsewhere? Maybe bbolt's CLI?

etcdctlv3: Add option to defrag a data directory directly

---

etcdctl/README.md
etcdctl/ctlv3/command/lock_command.go

1, add session ttl for lock cmd
2, set default session ttl to 10 seconds
@xiang90 @heyitsanthony 
please buddy check and  suggest if it is a better way to set the ttl as a gloabal flag ?

etcdctl: add ttl flag for lock command

---

embed/config.go

Address https://github.com/coreos/etcd/issues/8379.
> ./bin/etcd --listen-client-urls=http://127.0.0.1:2379 --advertise-client-urls=http://$SPELEDOK:2379
> 2017-08-09 13:34:52.220844 E | etcdmain: error verifying flags, unexpected empty host (http://:2379). See 'etcd --help'.

embed: warns about empty hosts in advertise urls

---

pkg/flags/flag.go

Address https://github.com/coreos/etcd/issues/8380.
```
export ETCD_NAME=aaaaa
./bin/etcd --name bbb
2017-08-09 14:18:11.061895 W | etcdmain: recognized environment variable ETCD_NAME, but unused: shadowed by corresponding flag
export ETCDCTL_ENDPOINTS=aaaaa.com
ETCDCTL_API=3 ./bin/etcdctl endpoint health --endpoints=bbb.com
2017-08-09 14:18:11.061895 W | pkg/flags: recognized environment variable ETCDCTL_ENDPOINTS, but unused: shadowed by corresponding flag
```

pkg/flags: warns on shadowed environment variable flags

---

Documentation/op-guide/container.md

Previously the command included `--net=host` so etcd could bind directly to the host IP address. Without that parameter and therefore using a separate network namespace I get an error trying to bind to the host's IP, which makes sense because it's not available from inside the container.
This PR fixes this by binding to all IP addresses within the container - i.e. 0.0.0.0. The advertise URL still requires the host IP addr as previously.

docs: use 0.0.0.0 to listen on container-local addrs

---

Documentation/platforms/container-linux-systemd.md

Fix field names in Container Linux Config for etcd 3.x service. Some of the field names were in CLI format.

Fix field names in Container Linux Config for etcd 3.x service

---

Documentation/dev-guide/interacting_v3.md

Close https://github.com/coreos/etcd/pull/8389.

dev-guide: note v2 keys to v3 API incompatibility

---

e2e/etcd_config_test.go
embed/etcd.go

I tried to test this with unix sockets but there's an unrelated bootstrap bug. After fixing that, the failure doesn't seem to appear for unix sockets (why, I don't know), so the e2e test uses tcp.
Fixes #8383

embed: associate peer serve() listener with corresponding peer

---

auth/store.go

This was missed in last gRPC bump-up.
c.f. https://github.com/grpc/grpc-go/commit/596a6acc87c73c3bc398a60ef0089976491ca060

auth: replace NewContext with NewOutgoingContext

---

e2e/etcd_config_test.go
pkg/netutil/netutil.go

etcd would fail to bootstrap:
```
../bin/etcd-1358: 2017-08-17 11:48:48.526669 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
../bin/etcd-1358: 2017-08-17 11:48:48.526804 I | embed: listening for peers on unix://etcd.unix:1
../bin/etcd-1358: 2017-08-17 11:48:48.527042 I | embed: listening for client requests on localhost:2379
../bin/etcd-1358: 2017-08-17 11:48:49.061660 W | pkg/netutil: failed resolving host etcd.unix:1 (lookup etcd.unix on 75.75.75.75:53: no such host); retrying in 1s
../bin/etcd-1358: 2017-08-17 11:48:50.093301 W | pkg/netutil: failed resolving host etcd.unix:1 (lookup etcd.unix on 75.75.75.75:53: no such host); retrying in 1s
../bin/etcd-1358: 2017-08-17 11:48:51.122967 W | pkg/netutil: failed resolving host etcd.unix:1 (lookup …
```

netutil: don't resolve unix socket URLs when comparing URLs

---

mvcc/watchable_store.go
mvcc/watchable_store_test.go

Fixes: #8411
Replace https://github.com/coreos/etcd/pull/8412.
Cherry-pick for today's release.

mvcc: sending events after restore

---

mvcc/index.go
mvcc/kvstore_test.go
mvcc/kvstore_txn.go

Save another alloc on the one key path.
master:
```
$ go test -bench=OneKey -run=OneKey -count=4 
BenchmarkStoreRangeOneKey-8      1000000              1883 ns/op             610 B/op         14 allocs/op
BenchmarkStoreRangeOneKey-8      1000000              1807 ns/op             609 B/op         14 allocs/op
BenchmarkStoreRangeOneKey-8      1000000              1861 ns/op             610 B/op         14 allocs/op
BenchmarkStoreRangeOneKey-8      1000000              1850 ns/op             610 B/op         14 allocs/op
```
branch:
```
$ go test -bench=OneKey -run=OneKey -count=4
BenchmarkStoreRangeOneKey-8      1000000              1808 ns/op             578 B/op         13 allocs/op
BenchmarkStoreRangeOneKey-8      1000000              1766 ns/op             578 B/op         13 …
```

mvcc: Revisions() method for index to avoid key allocation

---

clientv3/concurrency/example_stm_test.go
clientv3/concurrency/stm.go
integration/v3_stm_test.go

Was checking the rset key mod rev, which does not work.

concurrency: retry snapshot serializable stm if writes since first header rev

---

etcdserver/api/v3rpc/grpc.go

grpc 1.3 uses MaxMsgSize() to limit received message size. However, grpc 1.4 introduces a 4mb default limit on send message size. In etcd, server shouldn't be limiting size of message that it can be sent. Hence, set maximum size of send message using MaxSendMsgSize().

v3rpc: use MaxRecvMsgSize and MaxSendMsgSize to limit msg size

---

integration/v3_auth_test.go
pkg/testutil/assert.go

Fixes #8406 
Should be backported along with 478ba2c

integration: check concurrent auth ops don't cause old rev errors

---

pkg/wait/wait.go

Change list's lock from Mutex to RWMutex, which allows concurrent
access for list.IsRegistered function.

pkg/wait: change list's lock to RWMutex

---

etcdctl/ctlv3/ctl_cov.go

The stricter warnings on pkg/flags generates extra output that
break coverage tests. Unset the ETCDCTL_ARGS environment variable
so the warnings aren't printed.

etcdctl: unset ETCDCTL_ARGS on cov builds

---

pkg/srv/srv.go
pkg/srv/srv_test.go

The https scheme for a peer advertise URL was ignored when resolving through
SRV records.

srv: if a host matches a peer, only use if url schemes match

---

raft/README.md

Persist entries before hardstate. If the system crashes after hardstate is persisted to the wal but before the entries are persisted, raft is not able to recover on restart.
I had a look at the etcd/server code and there also entries are persisted before hardstate.

Persist entries before hardstate.

---

mvcc/index.go
mvcc/kvstore_bench_test.go

~6% improvement
Before:
```
$ go test -bench=RangeKey100 -run=RangeKey100 -v  -count=4
BenchmarkStoreRangeKey100-8        10000            118881 ns/op           46240 B/op        723 allocs/op
BenchmarkStoreRangeKey100-8        10000            117498 ns/op           46241 B/op        724 allocs/op
BenchmarkStoreRangeKey100-8        10000            119148 ns/op           46241 B/op        724 allocs/op
BenchmarkStoreRangeKey100-8        10000            116682 ns/op           46241 B/op        724 allocs/op
```
After:
```
BenchmarkStoreRangeKey100-8        10000            111767 ns/op           40113 B/op        716 allocs/op
BenchmarkStoreRangeKey100-8        10000            110846 ns/op           40112 B/op        715 allocs/op
BenchmarkStoreRangeKey100-8        10000 …
```

mvcc: don't allocate keys when computing Revisions

---

integration/cluster.go
integration/cluster_test.go

Could reproduce via
```sh
while [ 1 ]; do date; nice go test -v -run=Decrease -cpu=1,2,4 -count=5 >out.txt 2>&1 || break; done
```
Fixes #8225

integration: check all members agree on leader in waitLeader

---

etcdctl/ctlv3/command/global.go
etcdctl/ctlv3/ctl.go

etcdctl: add discovery-srv global flag for v3

---

e2e/ctl_v2_test.go
e2e/ctl_v3_test.go
e2e/etcd_process.go
e2e/etcd_spawn_cov.go
e2e/etcd_spawn_nocov.go
e2e/main_test.go
etcdctl/ctlv2/command/backup_command.go

Copy v3 db if given --with-v3. Strip out v3 entries from WAL by default.

ctlv2: backup --with-v3

---

raft/raft_test.go

TestRecvMsgPreVote was intended to be introduced in https://github.com/coreos/etcd/pull/6624 but was uncapitalized (search for testRecvMsgPreVote instead) and then subsequently removed due to it being unused.

raft: (re-)introduce TestRecvMsgPreVote

---

Documentation/upgrades/upgrade_3_3.md
clientv3/client.go
clientv3/client_test.go
clientv3/integration/dial_test.go
integration/v3_grpc_test.go

Address https://github.com/coreos/etcd/issues/8504.

clientv3: deprecate grpc.ErrClientConnTimeout errors

---

build
scripts/build-aci
scripts/build-binary
scripts/build-docker
scripts/genproto.sh
scripts/install-marker.sh
scripts/release.sh
scripts/updatebom.sh
scripts/updatedep.sh
test

* regexp warnings
* use ./*glob* so names don't become options
* use $(..) instead of legacy `..`
* read with -r to avoid mangling backslashes
* double quote to prevent globbing and word splitting

*: fix shellcheck warnings

---

Dockerfile-test

While Semaphore CI does not support Go 1.9 yet, we can do:
```
docker build --tag etcd-test --file ./Dockerfile-test .
docker run \
--volume=`pwd`:/go/src/github.com/coreos/etcd \
etcd-test \
/bin/sh -c "RELEASE_TEST=y INTEGRATION=y PASSES='build unit release integration_e2e functional' ./test 2>&1 | tee test.log"
```

Dockerfile-test: add test image with Go 1.9

---

lease/lessor.go

lease: use time.Until in 'Remaining'

---

test

test: use 'grep -E' for non-standard 'egrep'

---

tools/benchmark/cmd/lease.go
tools/benchmark/cmd/put.go
tools/benchmark/cmd/range.go
tools/benchmark/cmd/stm.go
tools/benchmark/cmd/txn_put.go
tools/benchmark/cmd/util.go
tools/benchmark/cmd/watch_get.go
tools/benchmark/cmd/watch_latency.go

tools/benchmark: replace 'golang.org/x/net/context' with 'context'

---

client/client.go
client/client_test.go

client: fail over to next endpoint on oneshot failure

---

cmd/vendor/github.com/coreos/go-systemd/util/util_cgo.go
glide.lock
glide.yaml

`cockroachdb/cmux` wasn't removed from `glide.yaml`.
And upgrade to https://github.com/coreos/go-systemd/releases/tag/v15.

vendor: upgrade go-systemd to v15, remove cockroachdb/cmux

---

clientv3/example_test.go
clientv3/logger.go
etcdctl/ctlv3/command/global.go
etcdserver/api/v3rpc/grpc.go
tools/benchmark/cmd/util.go
tools/functional-tester/etcd-tester/stresser.go

`grpclog.Logger` has been deprecated.

*: upgrade grpclog to LoggerV2

---

clientv3/compare.go

The logical input to Compare would be a LeaseID (type int64) but the
check panics if we give a LeaseID directly. Allow both so that we don't
unnecessarily annoy and confuse the programmer using the API in the most
logical way.

clientv3: Allow naked LeaseID or int64 for LeaseValue Compare's

---

rafthttp/http.go
rafthttp/util.go

add remote in pipeline and snapshot handler when corresponding peer or remote do not exist
Fixes: #8506

rafthttp: add remote in pipeline and snapshot handler

---

lease/lessor_test.go

Test whether lease's ttl is set to minLeaseTTL when passing a ttl smaller than minLeaseTTL to Grant function.

lease: test minLeaseTTL limit

---

e2e/ctl_v3_auth_test.go
etcdctl/ctlv3/command/role_command.go

Current `etcdctl role grant-permission` doesn't handle an empty key
("") correctly. Because the range permissions are treated as
BytesAffineInterval internally, just specifying the empty key as a
beginning of range introduces an invalid permission which doesn't work
and betray users' intuition. This commit Fix the way of handling empty
key as a prefix or from key in permission granting.
Fix #8494 
/cc @zyf0330 @heyitsanthony

etcdctl: handle empty key permission correctly

---

e2e/ctl_v3_kv_test.go
proxy/grpcproxy/kv.go

grpcproxy: respect KeysOnly flag

---

raft/raft.go
raft/raft_test.go

raft: currently when raft recv message with higher term, it set leader to that node.  If raft recv a MsgAppResp with higher term, it could not know whether remote node is leader or not. it's confusing.
So for message with higher term, only reset raft.lead when it's leader RPC request. Those messages are MsgApp, MsgHeartbeat, MsgSnap.

raft: check whether it's leader PRC request when recv message with higher term 

---

test

broken when fixing shellcheck errors

test: fix flags in coverage test

---

raft/raft.go
raft/raft_test.go

Fix #8450 
The previous behavior is to return 0(invalid) index if CheckQuroum is not enabled but ReadOnlyOption is lease based.
This commit makes the checking explicitly during the initialization phase.

raft: ensure CheckQuorum is enabled when readonlyoption is lease based

---

clientv3/balancer.go
clientv3/balancer_test.go
clientv3/client.go
clientv3/health_balancer.go
clientv3/integration/kv_test.go
clientv3/retry.go

Works with the watch keepalive test from the grpc ping timeout patch.
Supersedes #8327
Fixes #8326

clientv3: Health balancer

---

raft/README.md

Before this change:
After this change:

raft: fix bullet point indentation in README

---

Documentation/op-guide/container.md

Fix https://github.com/coreos/etcd/issues/8549.

Documentation/op-guide: add docker:// to 'rkt run gcr.io'

---

etcd.conf.yml.sample

Previous config was incorrect for peer client cert auth
Enable peer client cert authentication.
client-cert-auth: false
corrected to 
peer-client-cert-auth

etcd.conf.yml.example: peer-client-cert-auth flag

---

client/client.go

client uses math.rand.Perm, and now Perm works like Shuffle
in go math package (https://github.com/golang/go/commit/caae0917bff12751019cb4240e99874fa692e770#diff-d4a72c5ba8515eae95a093e0aec62635).
Fixes client test breakage in Go tip.
```
--- FAIL: TestHTTPClusterClientSyncUnpinEndpoint (0.00s)
client_test.go:988: #0: pinned endpoint = {http  <nil> 127.0.0.1:4001   false  }, want http://127.0.0.1:2379
client_test.go:988: #2: pinned endpoint = {http  <nil> 127.0.0.1:4001   false  }, want http://127.0.0.1:4002
--- FAIL: TestHTTPClusterClientSyncUnpinEndpoint (0.00s)
client_test.go:988: #0: pinned endpoint = {http  <nil> 127.0.0.1:4001   false  }, want http://127.0.0.1:2379
client_test.go:988: #2: pinned endpoint = {http  <nil> 127.0.0.1:4001   false  }, want http://127.0.0.1:4002
--- FAIL: …
```

client: fix TestHTTPClusterClientSyncUnpinEndpoint

---

e2e/ctl_v3_auth_test.go
etcdmain/grpc_proxy.go
proxy/grpcproxy/maintenance.go
proxy/grpcproxy/util.go
proxy/grpcproxy/watch.go
proxy/grpcproxy/watch_broadcast.go

This commit lets grpcproxy support authed RPCs. Auth tokens supplied
by clients are now forwarded to etcdserver by grpcproxy.
Fix https://github.com/coreos/etcd/issues/8247
/cc @zhuqunzhou @heyitsanthony 
This PR is still WIP because I'm considering how to protect proxy based watch. It isn't simple like other RPCs because of its streaming and broadcast nature.
@zhuqunzhou could you try it for your purpose? Authed KV requests with proxy should work now.

clientv3, etcdmain, proxy: support authed RPCs with grpcproxy

---

etcdserver/config.go

fix https://github.com/coreos/etcd/issues/8532

etcdserver: make dial timeout longer

---

Documentation/op-guide/monitoring.md

The dashboard was removed during Tectonic migration in AWS, while the Grafana still runs in GCP.
Screenshot should be good enough for now.
We can add it back when Grafana is fully migrated to Tectonic cluster,
which won't happen in the near future.

Documentation/op-guide: remove grafana demo link

---

clientv3/balancer.go
clientv3/health_balancer.go
etcdctl/ctlv3/command/global.go

For https://github.com/coreos/etcd/issues/8591.
Sets logger level 2 as debugging level in clientv3.
```
ETCDCTL_API=3 ./bin/etcdctl put foo bar --debug
ETCDCTL_CACERT=
ETCDCTL_CERT=
ETCDCTL_COMMAND_TIMEOUT=5s
ETCDCTL_DEBUG=true
ETCDCTL_DIAL_TIMEOUT=2s
ETCDCTL_DISCOVERY_SRV=
ETCDCTL_ENDPOINTS=[127.0.0.1:2379]
ETCDCTL_HEX=false
ETCDCTL_INSECURE_DISCOVERY=true
ETCDCTL_INSECURE_SKIP_TLS_VERIFY=false
ETCDCTL_INSECURE_TRANSPORT=true
ETCDCTL_KEY=
ETCDCTL_USER=
ETCDCTL_WRITE_OUT=simple
OK
```

etcdctl,clientv3: add debugging logs

---

Documentation/op-guide/authentication.md
e2e/ctl_v3_auth_test.go
etcdserver/v3_server.go

/cc @raoofm 
I'd like to hear comments about we should add an option for controlling the priority or not.
Fix https://github.com/coreos/etcd/issues/8584

RFC: etcdserver: swap priority of cert CN and username + password

---

clientv3/integration/kv_test.go
clientv3/integration/lease_test.go
clientv3/retry.go

With slow CPU, gRPC can lag behind with RPCs being sent before
calling 'Up', returning 'no address available' on the first try.
Fix https://github.com/coreos/etcd/issues/8581 and many other test failures since https://github.com/coreos/etcd/pull/8545.
Full explanation coming...

clientv3: wait for ConnectNotify before sending RPCs

---

embed/config.go
embed/etcd.go
embed/serve.go
etcdmain/config.go
etcdmain/help.go
etcdserver/api/v3rpc/grpc.go

From https://github.com/coreos/etcd/pull/8477.

*: configure server keepalive

---

.words
clientv3/integration/watch_keepalive_test.go
integration/bridge.go
integration/cluster.go

Address https://github.com/coreos/etcd/issues/8022.
Test https://github.com/coreos/etcd/pull/8545.

*: add watch with client keepalive test

---

compactor/compactor.go
compactor/periodic.go
compactor/periodic_test.go
embed/config.go
embed/etcd.go
etcdmain/config.go
etcdmain/help.go
etcdserver/config.go

*: support auto-compaction with finer granularity

---

integration/cluster.go

Found out gRPC master branch breaks our keepalive...
Also need debugging lines for stabilizing client balancer.

integration: enable client debug logging on CLIENT_DEBUG

---

Documentation/op-guide/monitoring.md

Add back dashboard link removed from https://github.com/coreos/etcd/commit/607d0762eb670c444ef873e7debcb69b167a76c8#diff-0f3cf03299e1ba976aa2c96fa242e51c.
The one with kubemark.

Documentation/op-guide: add Grafana dashboard link

---

clientv3/ordering/kv_test.go

Fix https://github.com/coreos/etcd/issues/8641.
`ordering` package is working as expected, we just didn't check the errors in tests.

clientv3/ordering: add missing 'errOrderViolation' error check

---

clientv3/yaml/config.go
clientv3/yaml/config_test.go
pkg/transport/listener.go

To be consistent with etcdmain? We're deprecating `ca-file` in favor of `trusted-ca-file`.

clientv3/yaml: add 'TrustedCAfile' field to replace 'CAfile'

---

cmd/vendor/golang.org/x/crypto/bcrypt/bcrypt.go
cmd/vendor/golang.org/x/crypto/blowfish/cipher.go
cmd/vendor/golang.org/x/crypto/blowfish/const.go
glide.lock
glide.yaml

To include https://github.com/golang/crypto/commit/6c586e17d90a7d08bbbc4069984180dce3b04117.

vendor: update 'golang.org/x/crypto'

---

.travis.yml

1.9.x doesn't work with travis Go 'gimme'.
https://travis-ci.org/coreos/etcd/jobs/283789582#L616-L629

travis: specify Go minor versions

---

mvcc/index.go

To make it consistent with other code paths.

mvcc: move 'keyi' define before holding locks

---

embed/config.go

Fix #8445 
@gyuho can you manually test it? or do we have a plan to add a test case for this?

embed: fix HTTPs + DNS SRV discovery

---

Makefile

In preparation of running all tests inside container.
Currently, we run Jenkins in shared environment.
This is not good. Need manual Go runtime updates,
cannot run two different branches, port conflicts,
out of disk on /tmp, etc.

Makefile: suffix test log files

---

etcdserver/api/etcdhttp/doc.go

etcdserver/api/etcdhttp: document package in doc.go

---

e2e/docker-dns-srv/Dockerfile
e2e/docker-dns/Dockerfile

This was noticed when attempting to replicate #8608 using the very convenient `make docker-dns-srv-test-build` command added in #8628.
On some system configurations bind9 failed to start in the container with 'permission denied' errors when accessing the config files added by the `Dockerfile`.  In my case the system configuration was Ubuntu trusty 14.04 and docker 1.12.6.
I'm not entirely clear on why this succeeds on other system configurations, but since `/etc/init.d/bind9` runs the daemon as the 'bind' user, setting the config file permissions appropriately seems like the way to go.

Dockerfile: Improve file permissions for docker build images using bind9

---

README.md

Separate `grpc-proxy` part out of https://github.com/coreos/etcd/pull/8656.

README: update 'goreman' guide with 'grpc-proxy'

---

etcdctl/ctlv3/command/ep_command.go
etcdctl/ctlv3/command/global.go
etcdctl/ctlv3/command/make_mirror_command.go
etcdctl/ctlv3/ctl.go

etcdctl: add keep alive time/timeout in etcdctl
client can switch from fault node to normal when keep alive is timeout
Fixes #7941

etcdctl/v3: add keep alive time/timeout

---

Dockerfile-test

Dockerfile-test: add 'ineffassign' to image

---

etcdctl/ctlv3/command/watch_command.go

Address https://github.com/coreos/etcd/issues/7941#issuecomment-334905241.

etcdctl/ctlv3: enable 'require-leader' for 'watch' command

---

.words
clientv3/balancer.go
clientv3/health_balancer.go
clientv3/integration/network_partition_test.go
clientv3/retry.go

Only health-check when timeout elapses since last failure.
Otherwise network-partitioned member with active health-check
server would not be gray-listed, making health-balancer stuck
with isolated endpoint. Also clarifies some log messages.
Mark partitioned member as unhealthy in retry code paths.
Previous behavior is when server returns errors, retry
wrapper does not do anything, while passively expecting
balancer to gray-list the isolated endpoint. This is
problematic when multiple endpoints are passed, and
network partition happens.
This patch adds `endpointError` method to `balancer` interface
to actively(possibly even before health-check API gets called)
handle RPC errors and gray-list endpoints for the time being,
thus speeding up the endpoint switch.
This is safe in a …

clientv3/balancer: handle network partition in health check

---

clientv3/health_balancer.go

Otherwise, 'mayPin' incorrectly decides if an address
should be pinned or not. Balancer is clearly broken because of this.
This should help address https://github.com/coreos/etcd/issues/8624.
With this patch, the failure doesn't happen in my VM anymore.
Will keep an eye on it, if it still fails.

clientv3: reset unhealthy on updateAddrs

---

clientv3/integration/network_partition_test.go

Separated from https://github.com/coreos/etcd/pull/8675.

clientv3: fix typo in 'testNetworkPartitionBalancer'

---

etcdctl/ctlv3/command/check.go
etcdctl/ctlv3/command/global.go
etcdctl/ctlv3/command/make_mirror_command.go

When creating multiple clients, 'mustClientFromCmd' overwrites
inherited flags with environment variables, so later clients
were printing warnings on duplicate key updates.
Fix https://github.com/coreos/etcd/issues/8664.
Nothing was breaking. This just removes the warnings.

etcdctl/ctlv3: inherit/update flags only once in 'check' command

---

auth/simple_token.go
auth/simple_token_test.go

`TokenProvider`s can be `enabled` and `disabled`. The `tokenSimple` implementation is disabled when the `simpleTokenKeeper` field is set to`nil`. 
`func (t *tokenSimple) assignSimpleTokenToUser(...)`, however, is missing a `t.simpleTokenKeeper != nil` check like those found in `(t *tokenSimple) invalidateUser(...)` and `(t *tokenSimple) info(...)`, and if it is called when tokenSimple is disabled, a nil pointer derference panic will occur. This appears to be the cause of https://github.com/coreos/etcd/issues/8608:
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x90197c]
goroutine 133 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/auth.(*simpleTokenTTLKeeper).addSimpleToken(0x0, …
```

auth: Fix simpleToken to respect disabled state for assign

---

clientv3/ready_wait.go
clientv3/retry.go

Separate out from https://github.com/coreos/etcd/pull/8710.
c.f. https://github.com/coreos/etcd/issues/8691.

clientv3: separate readyWait for ConnectNotify

---

clientv3/lease.go
clientv3/retry.go

Separate out from https://github.com/coreos/etcd/pull/8710.
c.f. https://github.com/coreos/etcd/issues/8691.

clientv3: remove redundant retries in Lease, set FailFast=true

---

clientv3/auth.go
clientv3/cluster.go
clientv3/kv.go
clientv3/maintenance.go
clientv3/retry.go
clientv3/txn.go
clientv3/watch.go

Separate out from https://github.com/coreos/etcd/pull/8710.
c.f. https://github.com/coreos/etcd/issues/8691.

clientv3: clean up retry wrapper, remove all FailFast=false

---

etcdserver/api/v3rpc/rpctypes/error.go

Changes ErrGRPCNotLeader error code to FailedPrecondition,
to disable retry with unavailable.

v3rpc/rpctypes: use codes.FailedPrecondition for ErrGRPCNotLeader

---

etcdctl/ctlv3/command/snapshot_command.go

Without calling `Close()`, the backend keeps the `db` file open.

etcdctl: close snapshot backend to close open file on member/snap/db

---

clientv3/ordering/logger_test.go

The server side logging is verbose when failures are injected. Also it does not make sense to enable server logging when we test clients. For debugging purpose, logging should be enabled on demand.

clientv3: disable server logging for client testing

---

.gitignore
Dockerfile-test
Makefile
test

Instead just specify `TEST_OPTS` env
> TEST_OPTS="RELEASE_TEST=y INTEGRATION=y PASSES='build unit release integration_e2e functional'" make docker-test
Removed all redundant targets (e.g. `docker-test-all`, `docker-test-proxy`, `docker-test-386`, etc.)

Makefile: clean up all redundant targets

---

.travis.yml
.words
Dockerfile-test
clientv3/integration/network_partition_test.go
clientv3/integration/watch_keepalive_test.go

Debian base image from golang-stretch was breaking
shellcheck tests.
`shellcheck` test is now fixed
```bash
docker run \
--rm \
--volume=`pwd`:/go/src/github.com/coreos/etcd \
gcr.io/etcd-development/etcd-test:go1.9.1 \
/bin/bash -c "PASSES='fmt' ./test"
```
(I pushed the docker image to our registry)
We need to use docker as well in Travis, to fix the CI failures.

*: fix test docker images, switch travis to docker

---

clientv3/balancer.go

When no address is pined, and balancer ignores the addr Up due to
its current unhealthy state, balancer will be unresponsive forever.
This PR fixes it by doing a full reset when there is no pined addr,
thus re-trigger the Up call.

clientv3: fix balancer unresponsiveness 

---

Documentation/op-guide/container.md

The documentation examples for running a single etcd node fail due to a number of issues, one being DATA_DIR is not set but is used in the example.
The `Run the latest version of etcd` example does not work out of the box.

Documentation/op-guide: Fix missing docker volume commands and specify the initial DATA_DIR

---

clientv3/integration/dial_test.go
clientv3/integration/kv_test.go
clientv3/integration/metrics_test.go
clientv3/integration/network_partition_test.go
clientv3/ordering/util_test.go
integration/cluster.go

Add 'SkipClients' field to skip creating clients if not used.

clientv3/integration: do not create v3 clients when not used

---

clientv3/integration/network_partition_test.go

To be consistent with `TestBalancerUnderShutdown*`
https://github.com/coreos/etcd/pull/8758

clientv3/integration: rename partition tests

---

clientv3/integration/dial_test.go
clientv3/integration/kv_test.go
clientv3/integration/network_partition_test.go
clientv3/ordering/util_test.go
integration/cluster.go
integration/network_partition_test.go

'member' type is not exported.
In network partition tests, we want do
```
InjectPartition(t, clus.Members[lead], clus.Members[lead+1])
```

integration: use variadic parameters for *Partition

---

clientv3/integration/server_shutdown_test.go

Current Watch integration tests haven't covered the balancer
switch behavior under server failures.

clientv3/integration: add TestBalancerUnderServerShutdownWatch

---

clientv3/integration/black_hole_test.go

clientv3/integration: add put blackhole test

---

clientv3/integration/black_hole_test.go
clientv3/integration/network_partition_test.go
clientv3/integration/server_shutdown_test.go
clientv3/integration/util.go

RPC should be sent to trigger 'readyWait' on new pin address.
Otherwise, endpoints other than ep[0] may be pinned.

clientv3/integration: add waitPinReady

---

clientv3/integration/server_shutdown_test.go

clientv3/integration: add TestBalancerUnderServerShutdownMutable*

---

integration/v3_lease_test.go
pkg/testutil/testutil.go

Fixes #8740
Previously the test would wait for ~1s after the renewed lease should expire, check if it had expired, and hard fail the test if it had not. This can easily flake if the operations that must occur in the etcd cluster during the wait take longer than expected and push out the renewal of the lease. I've replace the check with a polling check that waits for the renewed lease to be released, waiting up to 10 seconds.
Also, the sleeps between events in the test have no reference frames so can accumulate skew from the operations that occur between them. To firm up the timing, I've added a couple time references before/after important events and updated the sleeps to wait relative to those time references. I've also tightened up the timing of the test a bit to reduce the expected …

test: Deflake TestV3LeasePrmote integration test

---

clientv3/integration/network_partition_test.go

@xiang90 Should we also test when leader becomes isolated as well?
This only tests:
1. follower gets isolated
2. `WithRequireLeader` detects leader lose
3. Close watch stream with error
[EDIT] add test case with leader

clientv3/integration: add TestBalancerUnderNetworkPartitionWatch

---

clientv3/integration/server_shutdown_test.go

clientv3/integration: add TestBalancerUnderServerShutdownImmutable

---

e2e/ctl_v3_lease_test.go
etcdctl/ctlv3/command/lease_command.go

etcdctl/v3: add lease keep-alive --once flag

---

clientv3/integration/network_partition_test.go

Those tests are about balancer endpoint switch, not about keepalive pings.

clientv3/integration: remove client keepalive in network partition tests

---

clientv3/integration/black_hole_test.go
clientv3/integration/network_partition_test.go
clientv3/integration/server_shutdown_test.go
clientv3/integration/util.go

https://github.com/coreos/etcd/pull/8779#discussion_r147487474

clientv3/integration: rename to 'mustWaitPinReady'

---

auth/store.go
auth/store_test.go

authpb.User.Roles is sorted so we don't need a linear search for
checking the user has a root role or not.

auth: use binary search for checking root permission

---

clientv3/integration/network_partition_test.go

1. one with retry
2. one without retry (range request with longer timeouts)

clientv3/integration: finish isolated node test cases

---

clientv3/integration/black_hole_test.go

clientv3/integration: add blackhole tests on mutable operations

---

clientv3/integration/black_hole_test.go

Fix https://github.com/coreos/etcd/issues/8711

clientv3/integration: add blackhole tests for range RPCs

---

.words
clientv3/integration/kv_test.go

Since 3-second is the minimum time to keep an endpoint in unhealthy,
it is possible that endpoint switch happens right after context timeout.
Fix https://github.com/coreos/etcd/issues/8757.

clientv3/integration: increase balancer switch timeout for TestKVGetResetLoneEndpoint

---

clientv3/integration/server_shutdown_test.go

Fix
```
=== RUN   TestBalancerUnderServerShutdownWatch
WARNING: 2017/10/31 20:06:47 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial unix localhost:21207094780: connect: no such file or directory"; Reconnecting to {localhost:21207094780 <nil>}
WARNING: 2017/10/31 20:06:47 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial unix localhost:21207094780: connect: no such file or directory"; Reconnecting to {localhost:21207094780 <nil>}
INFO: 2017/10/31 20:06:47 get error from resetTransport context canceled, transportMonitor returning
WARNING: 2017/10/31 20:06:47 grpc: addrConn.transportMonitor exits due to: context canceled
WARNING: …
```

clientv3/integration: match more errors in put retries

---

.semaphore.sh
.travis.yml

Separate from https://github.com/coreos/etcd/pull/8764.
Images are already uploaded.

semaphore,travis: use Go 1.9.2

---

.semaphore.sh
.travis.yml
client/integration/client_test.go

Pending approval of https://github.com/coreos/etcd/pull/8805. This adds semaphore to 3.1 branch, like https://github.com/coreos/etcd/commit/2f74456443f97d34ee5a23591fdd4a4ab9405aea did for the 3.2 branch.
This also upgrades the 3.1 branch from go 1.8.3 to 1.8.5, primarly because we already have `gcr.io/etcd-development/etcd-test:go1.8.5` in the registry and don't see any point adding `1.8.3` when we can more easily upgrade go by a couple patch versions.

semaphore.sh, go: add semaphore to release-3.1 branch, upgrade release-3.1 to go 1.8.5

---

embed/config.go
etcd.conf.yml.sample
etcdmain/config.go
etcdmain/etcd.go

Remove grpc logs when `--debug=false`:
```
WARNING: 2017/11/02 11:35:51 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp: operation was canceled"; Reconnecting to {localhost:2379 <nil>}
WARNING: 2017/11/02 11:35:51 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial tcp: operation was canceled"; Reconnecting to {localhost:2379 <nil>}
INFO: 2017/11/02 11:35:51 get error from resetTransport grpc: the connection is closing, transportMonitor returning
```

*: move logging to embed, disable grpc server log by default

---

embed/config.go
etcdmain/config.go

Otherwise, embedded etcd will panic in SetupLogging

embed: NewConfig sets LogOutput to "default"

---

lease/leasehttp/http.go

Fix go vet warnings in Go tip
https://travis-ci.org/coreos/etcd/jobs/296632539

lease/leasehttp: use keyed fields in composite literals

---

.semaphore.sh
hack/scripts-dev/Makefile
test

Need these changes for upcoming gRPC upgrade, since new gRPC client logs have `TRANSIENT_FAILURE`. `egrep` commands are already used by Jenkins CIs.
Cherry-picked from https://github.com/coreos/etcd/pull/8771, since it's been taking awhile to figure out gRPC balancer issues.

*: fail tests with egrep "(--- FAIL:|leak)"

---

clientv3/balancer.go
clientv3/naming/grpc.go
clientv3/watch.go
etcdserver/api/v3rpc/util.go

It's been deprecated as of grpc/grpc-go v1.6.x.

api/v3rpc: deprecate grpc.Errorf

---

etcdserver/api/v3rpc/util.go
etcdserver/api/v3rpc/util_test.go

Fix error handling on `*status.statusError` errors from server side (e.g. linearizableReadNotify).
ref https://github.com/coreos/etcd/pull/8821.
Fix https://github.com/coreos/etcd/issues/8809.

api/v3rpc: do not convert server context error to grpc/*status.statusError

---

clientv3/integration/logger_test.go
clientv3/ordering/logger_test.go
integration/logger_test.go

Silence logs like
> WARNING: 2017/11/07 15:03:56 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial unix localhost:87057270247096176020: connect: no such file or directory"; Reconnecting to {localhost:87057270247096176020 <nil>}

*: disable grpc client log in tests by default

---

.semaphore.sh

Fix https://github.com/coreos/etcd/issues/8832.

semaphore: manually pin last release version for release tests

---

e2e/ctl_v3_snapshot_test.go
etcdctl/ctlv3/command/snapshot_command.go

etcdctl: snapshot status open bbolt with ReadOnly as true
this can avoid writing the freelist to the db file

etcdctl: fix snapshot status accidentally modified the db file

---

Documentation/branch_management.md
Documentation/dev-internal/release.md
hack/patch/README.md
hack/patch/cherrypick.sh

As part of a larger effort to align the supported etcd versions with versions of etcd kubernetes supports, we propose extending the officially supported etcd versions from **one** previous minor release version to **two**.
**Background / Rationale:**
Current state:
Aspirational State:
(Note that kubernetes will always lag by at least 1 minor etcd release version due to the quarterly release cadence of both projects)
**How can we make progress toward the aspirational state?** For kubernetes supported versions, move **trailing edge** forward with a deprecation policy of older etcd versions that is enforced by kube-apiserver, and move the **leading edge** forward with an adoption policy and schedule regular etcd upgrades supported with automated test and upgrade tooling. Establish better …

release, documentation, tools: Expand patch management support to the previous two minor versions

---

clientv3/integration/kv_test.go

Already tested in other server shutdown tests.

clientv3/integration: remove TestKVGetOneEndpointDown

---

clientv3/integration/logger_test.go
clientv3/logger.go
clientv3/ordering/logger_test.go
etcdctl/ctlv3/command/global.go
integration/logger_test.go
store/store_v2v3_test.go

Fix https://github.com/coreos/etcd/issues/8856.

*: grpclog.SetLoggerV2 on clientv3.SetLogger, disable gRPC client logs

---

Documentation/op-guide/etcd3_alert.rules.yml
Documentation/op-guide/monitoring.md
Documentation/v2/etcd_alert.rules.yml

This adds the existing Prometheus alerting rules in the new Prometheus 2.0 rule syntax.
@xiang90 @gyuho

Documentation/op-guide: Add rules for Prometheus 2.0

---

Documentation/upgrades/upgrade_3_2.md

Need this for gRPC v1.7 upgrade in release-3.2 branch.

Documentation/upgrades: add client upgrade check list for 3.2.10

---

Documentation/integrations.md

aioetcd3 is a Python binding for etcdv3 API for asyncio.
[https://github.com/gaopeiliang/aioetcd3](https://github.com/gaopeiliang/aioetcd3)

Documentation/integrations.md: Add aioetcd3 to Python language bindings

---

Documentation/op-guide/etcd3_alert.rules
Documentation/op-guide/etcd3_alert.rules.yml
Documentation/op-guide/monitoring.md

This adapts the provided example alerting rules for Prometheus to use the new gRPC metrics coming from [grpc-go-prometheus](https://github.com/grpc-ecosystem/go-grpc-prometheus) and fixes the incorrect link introduced in https://github.com/coreos/etcd/pull/8848#discussion_r150603693.
@xiang90 @gyuho

Adapt rules to use new gRPC metrics

---

etcdmain/grpc_proxy.go
etcdserver/api/v3rpc/grpc.go

This initializes the gRPC metrics to their respective zero-values. This is useful for discovering metrics, as well as being able to differentiate whether metrics are missing due to the target missing or currently just no request having generated the metrics yet.
@xiang90 @gyuho

*: initialize gRPC server metrics with zero values

---

embed/config.go

This reverts commit f79d5aaca475f6d36985856f2fba5b2ed3df7249.
Backporting https://github.com/coreos/etcd/pull/8884 to release-3.2.

release-3.2: Revert "embed: fix HTTPs + DNS SRV discovery"

---

embed/etcd.go
etcdserver/corrupt.go

Split from https://github.com/coreos/etcd/pull/8554.
Preliminary work for https://github.com/coreos/etcd/issues/8313.
This doesn't change any server behavior.

etcdserver,embed: clean up/reorganize client/peer/corrupt handlers

---

etcdmain/config_test.go

This will fix following error for gotip:
```
Starting 'fmt' pass at Fri Nov 17 20:40:20 UTC 2017
Checking gofmt...
gofmt checking failed:
etcdmain/config_test.go
diff -u etcdmain/config_test.go.orig etcdmain/config_test.go
--- etcdmain/config_test.go.orig	2017-11-17 20:40:20.691852875 +0000
+++ etcdmain/config_test.go	2017-11-17 20:40:20.691852875 +0000
@@ -149,7 +149,7 @@
Durl           string `json:"discovery"`
}{
{
-		// Use default name and generate a default initial-cluster
+			// Use default name and generate a default initial-cluster
},
{
Name: "non-default",
```
Fixes: https://github.com/coreos/etcd/issues/8900

Fix go fmt for gotip

---

auth/simple_token.go
auth/simple_token_test.go
auth/store.go
auth/store_test.go
etcdserver/apply.go

The keys of context shouldn't be string. They should be a struct of
their own type.
Fix https://github.com/coreos/etcd/issues/8826
/cc @gyuho

auth, etcdserver: follow the correct usage of context

---

Documentation/op-guide/configuration.md
Documentation/v2/configuration.md
etcd.conf.yml.sample
etcdmain/config.go
etcdmain/help.go

when i try to configure an etcd cluster with https,the word "key file" mislead me.what we need provide should be a CA cert file,not the CA private key.so the word "cert" will be better than the word "key".

Documentation: change "key file" to "cert file"

---

e2e/cluster_test.go
e2e/ctl_v3_test.go
e2e/etcd_corrupt_test.go
embed/config.go
embed/etcd.go
etcdmain/config.go
etcdmain/help.go
etcdserver/config.go
etcdserver/corrupt.go

Fix https://github.com/coreos/etcd/issues/8313.

*: check data corruption on boot

---

e2e/ctl_v3_test.go
tools/functional-tester/etcd-tester/member.go

Fix https://github.com/coreos/etcd/issues/8909.

*: enable initial corrupt check in tests

---

clientv3/doc.go
clientv3/integration/black_hole_test.go
clientv3/integration/network_partition_test.go
clientv3/integration/server_shutdown_test.go

gRPC passing contexts around remote machines by copying
the deadline timestamps. And it is possible that the copied
remote context times out while the client-side context hasn't
timed out due to clock drift.
Similar failure in `TestBalancerUnderNetworkPartitionLinearizableGetWithShortTimeout`
```
expected expected error, got rpc error: code = codes.DeadlineExceeded desc = context deadline exceeded
```

clientv3/integration: handle server-side context timeouts from clock-drift

---

clientv3/integration/network_partition_test.go
clientv3/integration/server_shutdown_test.go

Tests with cluster_proxy tags were failing, since isServerCtxTimeout
was defined with "+build !cluster_proxy".

clientv3/integration: move isServerCtxTimeout to server_shutdown_test.go

---

scripts/build-docker

`gcr.io/etcd-development/etcd` is now the default.
But, we will keep supporting quay.io as well--I will update the release process Google docs as well.

scripts/build-docker: build both gcr.io and quay.io images

---

Documentation/branch_management.md
Documentation/dev-internal/release.md

Add a release manager listing similar to the [kubernetes one](https://github.com/kubernetes/community/wiki), but simplified.
The only other page with release management docs is `Documentation/branch_management.md`. Should I add a link to this section from that page?

Documentation: Add release manager table

---

test

Make fmt tests selectable (e.g. `PASSES="markdown_you" ./test`).
UPDATE: removed parallel runs, since we need exit code.

test: clean up fmt tests

---

clientv3/doc.go

Fix https://github.com/coreos/etcd/issues/8709.

clientv3: update error handling godoc

---

etcdserver/api/v3rpc/lease.go
etcdserver/api/v3rpc/watch.go

Helpful for debugging https://github.com/coreos/etcd/issues/8904.
c.f. https://github.com/grpc/grpc-go/pull/1687

api/v3rpc: log grpc stream send/recv errors in server-side

---

clientv3/integration/kv_test.go
clientv3/integration/server_shutdown_test.go

Test all possible cases of server shutdown with inflight range requests.
Removed redundant tests in kv_test.go.
c.f. https://github.com/coreos/etcd/issues/8711

clientv3/integration: add more tests on balancer switch, inflight range

---

Documentation/op-guide/security.md

Fix https://github.com/coreos/etcd/issues/8798.

Documentation/op-guide: document TLS changes in 3.2

---

e2e/etcd_config_test.go

Now error is `embed: rejected connection from "127.0.0.1:58527" (error "remote error: tls: bad certificate", ServerName "")`.
Change from https://github.com/coreos/etcd/pull/8952.

e2e: fix remote error string in TestEtcdPeerCNAuth

---

.semaphore.sh
hack/scripts-dev/Makefile

Specify more leaky goroutine errors (e.g. `Too many goroutines`).
Separating out https://github.com/coreos/etcd/pull/8954.
/cc @fanminshi

semaphore, test: grep "test timed out" first, specify leaky goroutine string 

---

e2e/metrics_test.go
etcdserver/metrics.go

Fixes #8948 
```
curl -s http://localhost:2379/metrics  | grep etcd_server_version
etcd_server_version{server_version="3.2.0+git"} 1
```
When the metric aggregated from multiple etcd nodes, can be used to monitor the # of nodes running each etcd version.

metrics: Add server_version metric

---

etcdserver/api/v3rpc/lease.go
etcdserver/api/v3rpc/watch.go

Cherry pick of #8939 on release-3.2.
#8939: api/v3rpc: log grpc stream send/recv errors in server-side

Automated cherry pick of #8939

---

clientv3/doc.go

See https://github.com/coreos/etcd/blob/master/Documentation/upgrades/upgrade_3_2.md#client-upgrade-checklists-3210.
It was documented based on old etcd versions. Making godoc sync with latest release.

clientv3/doc: update dial-timeout error handling with new gRPC

---

auth/store.go
lease/lessor_test.go

I just rebuilt our base test-image with latest `gosimple`, and found this via https://travis-ci.org/coreos/etcd/jobs/311545346#L843-L844.

*: fix gosimple warnings on sort.StringSlice

---

cmd/vendor/google.golang.org/grpc/rpc_util.go
cmd/vendor/google.golang.org/grpc/transport/handler_server.go
glide.lock
glide.yaml

To include upstream fix https://github.com/grpc/grpc-go/pull/1687.
Already backported to `release-3.2`, planning `v3.2.11` sometime this week.
Should fix https://github.com/coreos/etcd/issues/8904.

vendor: upgrade grpc/grpc-go to v1.7.4

---

clientv3/doc.go

Looks off in https://godoc.org/github.com/coreos/etcd/clientv3.

clientv3: fix indentation in doc.go

---

Documentation/upgrades/upgrade_3_2.md

Address https://github.com/coreos/etcd/issues/6336#issuecomment-246486183 about https://github.com/coreos/etcd/pull/7236.
Had a customer whose v3.2 upgrade failed from this issue. v3.2 upgrade doc should have highlighted those changes.

Document/upgrades: add server upgrade checklists on listen URLs

---

embed/etcd.go
embed/serve.go
integration/embed_test.go

Replace https://github.com/coreos/etcd/pull/8986.
Fix https://github.com/coreos/etcd/issues/8916.

embed: fix *grpc.Server panic on GracefulStop with TLS-enabled server

---

Documentation/upgrades/upgrade_3_2.md
Documentation/upgrades/upgrade_3_3.md

There's already a section called "Server upgrade checklists" below.
Instead, highlight the listen URLs change as a breaking change in
server. Also update 3.2 and 3.3 gRPC requirements as v1.7.4.

Documentation/upgrades: highlight 3.2 breaking change, require gRPC v1.7.4

---

embed/serve.go

I forgot to handle this in https://github.com/coreos/etcd/pull/8987.
If serve errors before *grpc.Server is sent to serversC,
it should be closed manually.
@xiang90

embed: stop *grpc.Server on *serveCtx serve error

---

compactor/revision.go

Hello,
This is just a quick fix for an error message formatting. The Periodic compactor does not have the same issue. 
---
Reorder the parameters so that Noticef can output the error properly.

compactor: fix error message of Revision compactor

---

Documentation/learning/api.md

Just some minor fixes in api.md.

Documentation/learning/api.md: fix typos

---

README.md

The current Running etcd section only shows how to run etcd for installation
with master branch. If user has installed a pre-built release following the
instructions on the release page, the ./bin/etcd won't work to bring up the
etcd. The Getting etcd section covers both, pre-built and master branch,
with recommendation of pre-built usage so the Running etcd section is updated
accordingly.
fix #9003

Update Running etcd section for pre-built install of etcd

---

clientv3/health_balancer.go
clientv3/logger.go
clientv3/logger_test.go
clientv3/retry.go

Add `Lvl` method with `grpclog.LoggerV2` wrapper.
Shouldn't break anything that imports `clientv3.Logger`.

clientv3: simplify balancer level logging

---

pkg/fileutil/preallocate_darwin.go

ftruncate changes st_blocks, and following fallocate
syscalls would return EINVAL when allocated block size
is already greater than requested block size
(e.g. st_blocks==8, requested blocks are 2).
ref. https://github.com/apple/darwin-xnu/blob/master/bsd/kern/kern_descrip.c#L1241
Cross checked the behavior in C++:
```cpp
#include <fstream>
#include <iostream>
#include <fcntl.h>
#include <sys/stat.h>
#include <unistd.h>
using namespace std;
void fallocate(int fd, off_t len) {
// preallocate contiguous chunks on disk
fstore_t store={F_ALLOCATECONTIG,F_PEOFPOSMODE,0,len};
int ret=fcntl(fd,F_PREALLOCATE,&store);
if(ret<0) {
// non-contiguous allocation
store.fst_flags=F_ALLOCATEALL;
if(fcntl(fd,F_PREALLOCATE,&store)<0) perror("fcntl error");
}
}
void print_stats(int fd) {
struct stat stat; …
```

pkg/fileutil: fix preallocate under OS X kernel

---

auth/store.go
auth/store_test.go
etcdserver/server.go
integration/v3_auth_test.go

When auth is enabled, lease revoke loop was broken because we were embedding the token in the wrong way (affects etcd v3.2.10+ with gRPC v1.7.x).
Address https://github.com/coreos/etcd/issues/9006.

*: fix server-side lease expire when auth is enabled

---

e2e/ctl_v3_auth_test.go
e2e/ctl_v3_lease_test.go

Added tests to improve Lease coverage in e2e testing.
*  authLeaseTestKeepAlive
* authLeaseTestTimeToLiveExpired
* leaseTestTimeToLiveExpired
ref #9010

e2e: improve Lease coverage

---

clientv3/lease.go

Document the output of TTL when a Lease is expired. fixes (https://github.com/coreos/etcd/issues/9033)

clientv3/lease.go: TTL, document expired Lease.

---

mvcc/key_index.go

mvcc: clean-up godoc in key_index.go

---

cmd/vendor/google.golang.org/grpc/rpc_util.go
glide.lock
glide.yaml

No need backport. Just to explicitly pin the latest v1.7.x release.
/cc @jpbetz

vendor: pin "grpc/grpc-go" v1.7.5

---

Documentation/upgrades/upgrade_3_3.md
clientv3/integration/maintenance_test.go
clientv3/maintenance.go

To be consistent with other APIs.
Related discussion https://github.com/coreos/etcd/pull/9024#discussion_r157322731.

clientv3: translate Snapshot API gRPC status error

---

.words
clientv3/lease.go

Address https://github.com/coreos/etcd/issues/8993.

clientv3: document context to "KeepAlive" API

---

test

Recently we've added many more tests.
Until we parallelize tests, just increase the timeout.
https://semaphoreci.com/coreos/etcd/branches/master/builds/2696
ref. https://github.com/coreos/etcd/issues/8862

test: bump up clientv3/integration test time out

---

integration/v3_grpc_test.go

Address https://github.com/coreos/etcd/issues/9043.
Won't fix it, but we need test coverage on response back
from server as well.
Will fix the issue in the following PR.
/cc @jpbetz @xiang90

integration: test large request response back from server

---

e2e/ctl_v3_lease_test.go
etcdctl/README.md
etcdctl/ctlv3/command/printer_simple.go

Fix https://github.com/coreos/etcd/issues/9028.
@hexfusion Could you review? Had to finish this early, to ship this in today's rc release.

etcdctl/ctlv3: clarify "lease timetolive" output on expired lease 

---

e2e/ctl_v3_auth_test.go
e2e/ctl_v3_make_mirror_test.go
e2e/ctl_v3_watch_test.go
etcdctl/README.md
etcdctl/ctlv3/command/watch_command.go
etcdctl/ctlv3/command/watch_command_test.go

Fix https://github.com/coreos/etcd/issues/8814.

etcdctl: support exec watch in v3

---

CHANGELOG.md

/cc @xiang90 @jpbetz @fanminshi 
Will add
> **In the meantime, please try out [v3.3.0-rc.0](https://github.com/coreos/etcd/releases/tag/v3.3.0-rc.0).**
When the release candidate is out, sometime this or next month.

CHANGELOG: add v3.3 pre-release

---

Documentation/op-guide/etcd3_alert.rules
Documentation/op-guide/etcd3_alert.rules.yml

/cc @brancz 
The example alerts make reference to `etcd_network_member_round_trip_time_seconds_bucket`, but the codebase only contains `etcd_network_peer_round_trip_time_seconds_bucket` (in rafthttp/metrics.go).  Is this a mistake?

Documentation/op-guide: fix typo, s/member_round_trip_time/peer_round_trip_time/

---

.words
Documentation/upgrades/upgrade_3_2.md
Documentation/upgrades/upgrade_3_3.md
clientv3/auth.go
clientv3/client.go
clientv3/cluster.go
clientv3/config.go
clientv3/grpc_options.go
clientv3/integration/dial_test.go
clientv3/integration/kv_test.go
clientv3/kv.go
clientv3/lease.go
clientv3/maintenance.go
clientv3/ordering/kv_test.go
clientv3/txn.go
clientv3/watch.go
etcdserver/api/v3client/v3client.go
integration/cluster.go
integration/cluster_proxy.go
integration/v3_grpc_test.go

Fix https://github.com/coreos/etcd/issues/9043.
- https://github.com/kubernetes/kubernetes/issues/51099
- https://github.com/kubernetes/kubernetes/pull/57160#issuecomment-352906474
/cc @jpbetz @xiang90

*: configurable gRPC message size limits

---

Documentation/dev-guide/api_reference_v3.md
Documentation/dev-guide/apispec/swagger/rpc.swagger.json
etcdserver/etcdserverpb/rpc.pb.go
etcdserver/etcdserverpb/rpc.proto

Update documentation of expected expired lease output using scripts/genproto.sh.

Documentation/dev-guide: update TimeToLive documentation.

---

clientv3/retry.go

c.f. https://github.com/coreos/etcd/issues/8691.

clientv3/retry: clean up retryRPCFunc

---

.words
clientv3/maintenance.go

Address https://github.com/coreos/etcd/issues/8993.

clientv3: document context to "Snapshot" API

---

tools/etcd-dump-db/backend.go
tools/etcd-dump-db/main.go
tools/etcd-dump-logs/main.go

Helpful when debugging issues like https://github.com/coreos/etcd/pull/9031. And take data directory as an argument rather than flag (less typing).
Also add TODO for https://github.com/coreos/etcd/issues/7620.
```
etcd-dump-db iterate-bucket ./agent-1/etcd.data/ lease --decode
lease ID=5f3b606ba41b115a, TTL=120s
lease ID=5f3b606ba41b1158, TTL=120s
lease ID=5f3b606ba41b1156, TTL=120s
lease ID=5f3b606ba41b1154, TTL=120s
lease ID=5f3b606ba41b1152, TTL=120s
etcd-dump-db iterate-bucket ./agent-1/etcd.data/ key --decode
rev={main:6984 sub:0}, value=[key "foo000000000003ccd8" | val "aaa" | created 6984 | mod 6984 | ver 1]
rev={main:6983 sub:0}, value=[key "foo00000000000004f3" | val "aaa" | created 6983 | mod 6983 | ver 1]
rev={main:6982 sub:0}, value=[key "foo000000000002eaee" | val "aaa" | …
```

tools/etcd-dump-*: add TODOs, --decode flag

---

.words
clientv3/watch.go

Address https://github.com/coreos/etcd/issues/8993.

clientv3: document context to "Watch" API 

---

CHANGELOG.md
Documentation/upgrades/upgrade_3_2.md
Documentation/upgrades/upgrade_3_3.md

In v3.2.10 and v3.2.11, client response limit is still 4 MiB (default value in gRPC).

*: highlight client response size limit (4 MiB) in previous versions

---

CHANGELOG.md
embed/config.go
etcdmain/grpc_proxy.go

Fix https://github.com/coreos/etcd/issues/8983.

*: discard only info when --debug=false, add "--debug" grpc-proxy start

---

Documentation/op-guide/container.md

Update the coreos.com/etcd:v3.1.2 references with the quay registry for etcd
release image example. Using the stable 3.2 as an example instead of 3.1.2. 
Fixes #8984

Doc: update etcd container image registry references

---

clientv3/leasing/kv.go

Fix
```
=== RUN   TestLeasingSessionExpireCancel
Read at 0x00c42022e780 by goroutine 48:
github.com/coreos/etcd/clientv3/leasing.(*leasingKV).waitSession()
/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/leasing/kv.go:449 +0x5a
github.com/coreos/etcd/clientv3/leasing.(*leasingKV).put()
/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/leasing/kv.go:232 +0x6d
github.com/coreos/etcd/clientv3/leasing.(*leasingKV).Do()
/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/leasing/kv.go:103 +0x53f
github.com/coreos/etcd/clientv3/integration.TestLeasingSessionExpireCancel.func5()
/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/integration/leasing_test.go:1944 …
```

clientv3/leasing: fix racey waitSession

---

Documentation/dev-guide/grpc_naming.md

there is a error in invoke service by balance like grpc_naming.md
sometimes occurs:  
```
rpc error: code = Unavailable desc = there is no address available
```
#8701

grpc_naming.md: improve docs invoke grpc naming by balance

---

Documentation/op-guide/configuration.md

Add a reference of the config file, sample file link and precedence detail  to the
configuration doc.
Fixes #9063 

Doc: update etcd configuration detail with config file

---

etcdmain/config.go

Adding information that when config file is used other command line flags
and env variables will be ignored. This changes are a follow up of a
disucssion under PR https://github.com/coreos/etcd/pull/9066

Log: add information statement

---

etcdctl/README.md

As README declares in the beginning, flags can have dash and it should be
replaced with underscore while using. Also flags or commands are emphasized
in general. The range-end is not a flag or valid doc word and should not be
used as such.
Fixes #9075 

README: range-end is not a flag and should not be used

---

embed/etcd.go
etcdserver/api/v3rpc/grpc.go
etcdserver/api/v3rpc/lease.go
etcdserver/api/v3rpc/watch.go
etcdserver/config.go
tools/functional-tester/etcd-tester/stresser.go

Make logs from https://github.com/coreos/etcd/pull/8939 to debug level.
etcd server logs were getting too verbose when there are lots of streams canceled.
Also silence gRPC info level server logs (balancer logs).
ref. https://github.com/kubernetes/kubernetes/pull/57480

etcdserver: log stream error with debug level, silence gRPC server info level logs

---

clientv3/integration/kv_test.go

Fix
```
$ go test -tags cluster_proxy -v -run TestKVLargeRequests
=== RUN   TestKVLargeRequests
--- FAIL: TestKVLargeRequests (2.00s)
kv_test.go:943: #3: expected rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (10485770 vs. 10485760), got rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (10485785 vs. 10485760)
kv_test.go:943: #5: expected rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (10485775 vs. 10485760), got rpc error: code = ResourceExhausted desc = grpc: trying to send message larger than max (10485790 vs. 10485760)
FAIL
```
https://jenkins-etcd.prod.coreos.systems/job/etcd-proxy/3774/console
We shouldn't do exact match on message size, which might change …

clientv3/integration: fix TestKVLargeRequests with -tags cluster_proxy

---

etcdctl/README.md

Create a doc for etcdctl check commands with perf subcommand.
Fixes #9072

Doc: Create doc for etcdctl check perf command

---

raft/raft.go
raft/raft_test.go

"Learner" was spelled incorrectly in a few places.

raft: s/leaner/learner/g

---

Documentation/op-guide/maintenance.md

The current command as such produces no output on mac term or bash shell.
Using regex wildcard works fine on mac and linux.
Fixes #9092 

DocCommand: use regex wildcard

---

embed/etcd.go
etcdmain/etcd.go

Following up on https://github.com/coreos/etcd/pull/7030.
The `extensive` metrics were only [enabled](https://github.com/coreos/etcd/blob/2fb972847346d838b7395d9b5305ad45c124ff1b/etcdmain/etcd.go#L183) for the binary form of etcd, and not when using the embed server. This PR alleviate exactly this.

embed: enable extensive metrics if specified

---

etcdserver/api/v3rpc/lease.go
etcdserver/api/v3rpc/util.go
etcdserver/api/v3rpc/watch.go

The context error with cancel code is typically for user cancellation which
should be at debug level. For other error codes we should display a warning.
Fixes #9085

etcdserver/api/v3rpc: debug user cancellation and log warning for rest

---

mvcc/backend/backend.go

```
Since CreateBucketIfNotExists() can return nil when it gets an error,
accessing FilePercent must be done after a nil check, not to cause
a panic.
```
We observed  a panic during a defrag like below with etcd v3.2.10 under heavy load (larger IO wait). It seems it's due to a nil check failure. As the code is till there in the master, I'm sending a patch to fix the issue. Probably backporting to v3.2.x is required.
```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x8c76a7]
goroutine 905788 [running]:
github.com/coreos/etcd/cmd/vendor/github.com/coreos/etcd/mvcc/backend.defragdb(0xc4401b81e0, 0xc44617a000, 0x2710, 0x0, 0x0)
__/home/gyuho/etcd/release/etcd/gopath/src/github.com/coreos/etcd/cmd/vendor/gi …
```

mvcc: check null before set FillPercent not to panic

---

raft/node.go
raft/node_test.go
raft/raft.go
raft/raft_test.go
raft/rawnode.go

Scanning the uncommitted portion of the raft log to determine whether
there are any pending config changes can be expensive. In
cockroachdb/cockroach#18601, we've seen that a new leader can spend so
much time scanning its log post-election that it fails to send
its first heartbeats in time to prevent a second election from
starting immediately.
Instead of tracking whether a pending config change exists with a
boolean, this commit tracks the latest log index at which a pending
config change *could* exist. This is a less expensive solution to
the problem, and the impact of false positives should be minimal since
a newly-elected leader should be able to quickly commit the tail of
its log.

raft: Avoid scanning raft log in becomeLeader

---

etcdctl/README.md
etcdctl/ctlv3/command/snapshot_command.go

Address https://github.com/coreos/etcd/issues/9109#issuecomment-356235178.
@lyddragon

ctlv3: add "snapshot restore --wal-dir"

---

cmd/vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/convert.go
cmd/vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go
cmd/vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_json.go
cmd/vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_jsonpb.go
cmd/vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_proto.go
cmd/vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler.go
glide.lock
glide.yaml
scripts/genproto.sh

Doesn't change any generated output (no need backport).
https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v1.3.1

*: pin latest grpc-gateway release v1.3.1

---

clientv3/client.go
clientv3/integration/server_shutdown_test.go
clientv3/leasing/kv.go
clientv3/retry.go
etcdserver/api/v3rpc/rpctypes/error_test.go
tools/functional-tester/etcd-runner/command/lease_renewer_command.go

status.FromError can return nil, false. We are handling the return values
most places in code but some places we aren't. Fixing it herewith.
Fixes #9117

StatusFromError: handle return value of the function

---

test
tools/functional-tester/etcd-tester/key_stresser.go
tools/functional-tester/etcd-tester/main.go
tools/functional-tester/etcd-tester/stresser.go

functional-tester never failed for the last several months.
This adds Txn stresser.
Address https://github.com/coreos/etcd/issues/8293.

etcd-tester: add txn stresser

---

raft/node.go
raft/node_test.go
raft/raft.go
raft/raft_test.go
raft/rawnode.go

raft: raft learners should be returned after applyConfChange

---

tools/functional-tester/etcd-tester/key_stresser.go

Found when debugging https://github.com/coreos/etcd/issues/9130.

etcd-tester: fix "writeTxn" key selection

---

raft/node_test.go
raft/raft.go
raft/raft_paper_test.go
raft/raft_test.go
raft/rawnode_test.go

While the leader is transferring or some other states which the raft node may drop the proposal, we should fail fast to notify the proposal cancelled.
This should fix issue #8975 and #8977

raft: let raft step return error when proposal is dropped to allow fail-fast

---

tools/functional-tester/etcd-tester/key_stresser.go

Large key writes (stressEntries[1].weight) should not take this
much weight. It was triggering "database size exceeded" errors.
Fix https://github.com/coreos/etcd/issues/9130.

etcd-tester: update stresser weights with txn stresser

---

Documentation/op-guide/security.md

Make it more accurate (just as pkg/transport/listener_tls.go does).

Documentation/op-guide: clarify security.md on TLS auth

---

Documentation/upgrades/upgrade_3_3.md
Documentation/v2/admin_guide.md
Documentation/v2/other_apis.md
e2e/ctl_v3_alarm_test.go
e2e/metrics_test.go
etcdserver/api/etcdhttp/metrics.go
proxy/grpcproxy/health.go

Fixes #9144
Fixes breaking change in /health API response prior to 3.3.0 release
Needs picking to release-3.3
Example impact of compatibility break is at https://github.com/kubernetes/kubernetes/issues/58240

api/etcdhttp: change /health type back to string for backwards compatibility

---

e2e/ctl_v3_watch_test.go
etcdctl/README.md
etcdctl/ctlv3/command/global.go
etcdctl/ctlv3/command/watch_command.go
etcdctl/ctlv3/command/watch_command_test.go

Parsing logic became more complicated, but added test cases should cover all edge cases.
Can you give this a try @debovema @vikin91 @wwyiwzhang @pldmgg ?
```bash
ETCDCTL_API=3 ETCDCTL_WATCH_KEY=foo ./bin/etcdctl watch
ETCDCTL_API=3 ETCDCTL_WATCH_KEY=foo ./bin/etcdctl watch --rev 5
ETCDCTL_API=3 ETCDCTL_WATCH_KEY=foo ./bin/etcdctl watch -i
```
ref. https://github.com/coreos/etcd/pull/8919#issuecomment-356980785
https://github.com/coreos/etcd/issues/8814

ctlv3: support ETCDCTL_WATCH_KEY, ETCDCTL_WATCH_RANGE_END

---

raft/README.md

Code snippet in Raft README refers to non-existent field `State`. Fixed the reference by setting it to `HardState`.

docs: fix invalid reference in Raft README

---

Documentation/upgrades/upgrade_3_3.md
e2e/ctl_v3_alarm_test.go
etcdserver/api/etcdhttp/metrics.go
proxy/grpcproxy/health.go

To not break any backward compatibilities, just keep `/health` endpoint as same.

*: remove "errors" field in /health endpoint 

---

clientv3/README.md

Separated from https://github.com/coreos/etcd/pull/9129.

clientv3: document client-side request size limit

---

.words
etcdserver/api/v3rpc/util.go

Fix https://github.com/coreos/etcd/issues/9166.

etcdserver/api/v3rpc: debug-log client disconnect on TLS, http/2 stream CANCEL

---

.words
clientv3/cluster.go
clientv3/integration/cluster_test.go

Prevent https://github.com/coreos/etcd/issues/9173 in client-side.

clientv3: prevent wrong URLs to cluster APIs

---

e2e/ctl_v3_member_test.go

Part of ongoing e2e coverage improvements.
ref: https://github.com/coreos/etcd/issues/9149

e2e: improve Member TLS test coverage.

---

pkg/logger/discard.go
pkg/logger/doc.go
pkg/logger/logger.go
pkg/logger/package_logger.go

Later to be used with "snapshot" and "clientv3" packages.
Separated from https://github.com/coreos/etcd/pull/9118.

pkg/logger: initial commit

---

e2e/ctl_v3_snapshot_test.go
etcdctl/ctlv3/command/printer.go
etcdctl/ctlv3/command/printer_fields.go
etcdctl/ctlv3/command/printer_json.go
etcdctl/ctlv3/command/printer_simple.go
etcdctl/ctlv3/command/printer_table.go
etcdctl/ctlv3/command/snapshot_command.go
snapshot/doc.go
snapshot/util.go
snapshot/v3_snapshot.go

Fix https://github.com/coreos/etcd/issues/8632.
Address https://github.com/coreos/etcd/issues/9109 with tests in `snapshot` package.

*: add snapshot package

---

pkg/testutil/var.go
snapshot/member_test.go
snapshot/v3_snapshot_test.go

For https://github.com/coreos/etcd/issues/9151.

snapshot: add "snapshot" restore/save/member-add tests

---

raft/raft.go

This includes one theoretical logic change: A node that knows the
leader of the current term will no longer grant votes, even if it has
not yet voted in this term. It also adds a `m.Type == MsgPreVote`
guard on the `m.Term > r.Term` check, which was previously thought to
be incorrect (see #8517) but was actually just unclear.
Closes #8517
Closes #8571

raft: Clarify conditions for granting votes and prevotes.

---

Documentation/op-guide/security.md

Fix links after splitting out CHANGE files.

Documentation/op-guide: fix CHANGELOG links in security.md

---

Documentation/op-guide/etcd3_alert.rules
Documentation/op-guide/etcd3_alert.rules.yml

The alerting rules you supply are really good, apart from the fact that if all requests are failing the alert states that 1% is failing.
This should fix that issue

Documentation/op-guide: integer value of 1 is 100% not 1% for failing reqs

---

Documentation/op-guide/clustering.md
Documentation/op-guide/configuration.md
Documentation/v2/clustering.md
Documentation/v2/configuration.md
embed/config.go
etcdmain/config.go
pkg/srv/srv.go
pkg/srv/srv_test.go

This PR adds the ability to configure the subdomain used for DNS cluster discovery. Previously, the domain was hardcoded to `_etcd-server._tcp.FOO` and `_etcd-server-ssl._tcp.FOO`. This did not work with our DNS setup, so I've made this patch to allow configuring the subdomain portion of the SRV queries.
We've been running this in production for a few months.

pkg/srv, embed, etcdmain: Support multiple clusters in the same DNS domain

---

etcdserver/config.go
etcdserver/membership/cluster.go
pkg/netutil/netutil.go
pkg/netutil/netutil_test.go

- Better warning on [mismatched `--initial-cluster`](https://github.com/coreos/etcd/pull/8083) flag.
- etcd compares `--initial-advertise-peer-urls` against corresponding `--initial-cluster` URLs with forward-lookup.
- If resolved IP addresses of `--initial-advertise-peer-urls` and `--initial-cluster` do not match (e.g. due to DNS error), etcd will exit with errors.
- v3.2 error: `"--initial-cluster must include s1=https://s1.test:2380 given --initial-advertise-peer-urls=https://s1.test:2380"`.
- v3.3 error: `"--initial-advertise-peer-urls has https://s1.test:2380 but missing from --initial-cluster="` (DNS returns zero results).
- v3.3 error should be: `failed to resolve https://s1.test:2380 to match --initial-cluster=s1=https://s1.test:2380 (failed to resolve "https://s1.test:2380" …

*: add detailed error message on URLs equal check

---

Documentation/integrations.md
Documentation/v2/libraries-and-tools.md
README.md

fleet is deprecated and no longer maintained.

Documentation: drop fleet from integration lists

---

Documentation/op-guide/hardware.md

Wrong instance type, n1-standard-1 has only 1 vCPU and 3,75 GB memory.

 Documentation/op-guide: Typo instance type GCE

---

etcdserver/backend.go

Found this confusing while doing some benchmarks on freelist rebuilds.

etcdserver: clarify warnings on backend open taking >10 seconds

---

embed/config.go

solves https://github.com/coreos/etcd/issues/8379
Not sure if this is what wanted.  :sweat_smile:

embed: return error when advertise-client-urls are with empty hosts

---

raft/raft.go
raft/raft_test.go

Fixes https://github.com/coreos/etcd/issues/8501

raft: fix deadlock during PreVote migration process

---

CHANGELOG-3.3.md
CHANGELOG-3.4.md
embed/config.go

[Go internal packages](https://docs.google.com/document/d/1e8kOo3r51b2BWtTs_1uADIA5djfXhPT36s6eHVRIvaU/edit) cannot be imported by external projects. So, define compactor mode variable in embed packages. It broke https://travis-ci.org/coreos/etcdlabs/jobs/334931774#L467.

embed: define "embed.CompactorMode*"

---

CHANGELOG-3.3.md
etcdmain/grpc_proxy.go

Hi
Pull request which solves #9055 for grpc-proxy.

grpcproxy: configure --max-send-bytes and --max-recv-bytes for grpc proxy

---

etcdmain/help.go

Small update to help for `discovery-srv-name` feature.
ref: https://github.com/coreos/etcd/pull/8690

etcdmain: add discovery-srv-name

---

Documentation/op-guide/maintenance.md

Clarify on https://github.com/coreos/etcd/issues/9222.
/cc @yudai

Documentation/op-guide: highlight defragment operation

---

CHANGELOG-3.4.md
etcdserver/api/v2http/client.go
etcdserver/api/v2http/client_auth.go
etcdserver/api/v2http/client_auth_test.go
etcdserver/api/v2http/http.go
etcdserver/v2auth/auth.go
etcdserver/v2auth/auth_requests.go
etcdserver/v2auth/auth_test.go

Confusing with v3 auth package, and this is internal to etcdserver, anyway.

etcdserver: move "etcdserver/auth" to "etcdserver/v2auth"

---

etcdserver/api/v3rpc/watch.go

v3rpc: add jitter to progress notification

---

raft/raft.go

No need to call "lastIndex" again.
"append" call already returns "lastIndex".

raft: reuse "last index" in "appendEntry"

---

build

Package `version` has been moved to `internal/version`.

build: fix "internal/version" LD flags

---

internal/mvcc/watchable_store.go
internal/mvcc/watchable_store_test.go

For #9086
In case syncWatchersLoop() starts before Restore() is called,
watchers already added by that moment are moved to s.synced by the loop.
However, there is a broken logic that moves watchers from s.synced
to s.uncyned without setting keyWatchers of the watcherGroup.
Eventually syncWatchers() fails to pickup those watchers from s.unsynced
and no events are sent to the watchers, because newWatcherBatch() called
in the function uses wg.watcherSetByKey() internally that requires
a proper keyWatchers value.
This might be a cause of missing update issues that happen on node failures.

mvcc: restore unsynced watchers

---

etcdserver/apply.go
etcdserver/apply_v2.go
etcdserver/server.go
etcdserver/util.go
etcdserver/v2_server.go
etcdserver/v3_server.go

fix https://github.com/coreos/etcd/issues/9111
range and txn readonly range need special care in its own funcs since these two kinds of request wont go through raft to be applied.
example output
```
2018-02-06 12:14:01.589768 W | etcdserver: read-only range request "key:\"\\000\" range_end:\"\\000\" " took too long [3.389041388s] to execute
```
to trigger the warning, try to put 1M keys into etcd and do a large range over the entire 1M keys.
/cc @hexfusion please take a look. thanks!

etcdserver: improve request took too long warning

---

build.ps1

I'm building etcd on Windows but encounters error about can't find package  "github.com/coreos/etcd/cmd/etcd", I think should remove cmd directory.

build.ps1: remove .\cmd

---

mvcc/watchable_store.go
mvcc/watchable_store_test.go

Cherry pick of #9281 on release-3.2.
#9281: mvcc: restore unsynced watchers

Automated cherry pick of #9281

---

Documentation/dev-guide/api_reference_v3.md

genproto populated a change from https://github.com/coreos/etcd/commit/6b775cd786d897f6cc8d0e552456558399135459 breaking it out here in seperate commit.
@yudai

*: regenerate proto

---

internal/mvcc/backend/backend.go
internal/mvcc/backend/batch_tx.go

/cc @yudai 
After your PR, we now update metrics in defrag func. So no need to call commit to update metrics.

mvcc: remove unnecessary metrics update code

---

tools/etcd-test-proxy/main.go

Fix govet warnings with Go tip
```
tools/etcd-test-proxy/main.go:47: Fprintln arg list ends with redundant
newline
```
https://travis-ci.org/coreos/etcd/jobs/339098329#L746

*: fix govet warnings

---

internal/mvcc/backend/backend.go
internal/mvcc/backend/batch_tx.go

I found that etcd is unable to process large (take more than 100ms) read requests concurrently even under light or no write workload. We already put some effort to solve the current read problem by adding a writeback buffer in front of the database transaction. So I want to fix this problem.
The root cause of the problem is that although we use Read Lock to allow current read go-routines, but we have another long running go-routine that tries to flush data back to disk every 100ms which requires Write Lock.
Obviously, the write lock has a higher priority that read lock, and will always kick in to block any later read locks. So with this behavior, we basically put a barrier for every 100ms to block all reads until the write lock is acquired by the long running go-routine and then released. …

mvcc: allow large concurrent reads under light  write workload

---

.semaphore.sh
.travis.yml
hack/scripts-dev/Makefile

@jpbetz Can we also update https://github.com/coreos/etcd/blob/release-3.2/.semaphore.sh#L13? I already uploaded test container image with Go 1.8.7 and 1.9.4.

*: use latest Go in tests

---

Documentation/op-guide/maintenance.md
integration/metrics_test.go

Due to boltdb behavior, dbSizeInUse can be unequal to dbSize even when
dbSize is growing in some conditions. The possible gap between the sizes
is up to a couple of pages.
Closes #9302

*: allow dbSizeInUse not to equal to dbSize when growing

---

etcdctl/README.md

some examples use endpoint with port `:2379` but the others with `:12379`

etcdctl: fix typo in README

---

scripts/genproto.sh

Do not skip "protodoc" by default.
@hexfusion @yudai

scripts/genproto: run "protodoc" by default

---

etcdctl/ctlv3/command/check.go

```
$ ETCDCTL_API=3 ./bin/etcdctl endpoint status -w table                                                                                 
+----------------+------------------+-----------+---------+-----------+-----------+------------+--------------------+--------+                                         
|    ENDPOINT    |        ID        |  VERSION  | DB SIZE | IS LEADER | RAFT TERM | RAFT INDEX | RAFT APPLIED INDEX | ERRORS |                                         
+----------------+------------------+-----------+---------+-----------+-----------+------------+--------------------+--------+                                         
| 127.0.0.1:2379 | 8e9e05c52164694d | 3.3.0+git |   20 kB |      true |         2 |          4 |                  4 |        | …
```

ctlv3/command: auto compact and defrag after "check perf"

---

proxy/httpproxy/reverse.go

This change fixes https://github.com/coreos/etcd/issues/9335. I've:
- run the repro scenario described in that issue and confirmed that filehandles aren't leaked
- added a temporary log to confirm that `io.Copy` does now exit (so we don't leak a goroutine)
- checked that it is safe to call `cancel()` repeatedly (https://golang.org/pkg/context/#CancelFunc - "After the first call, subsequent calls to a CancelFunc do nothing.")

httpproxy: cancel requests when client closes a connection

---

etcdctl/ctlv3/command/check.go
etcdctl/ctlv3/command/util.go

Create a new command similar to check perf that can check the memory
consumption for putting different workloads. Return user with a message
that whether there are enough memory for a given workload with pass
or fail.
Fixed #9121

etcdctl/check: create new check command for memory usage

---

.semaphore.sh
.travis.yml
CHANGELOG-3.4.md
README.md
hack/scripts-dev/Makefile
tools/functional-tester/scripts/docker-local-agent.sh
tools/functional-tester/scripts/docker-local-tester.sh

Pushed Go 1.10 test image to https://console.cloud.google.com/gcr/images/etcd-development/GLOBAL/etcd-test.

*: upgrade to Go 1.10

---

embed/config.go
embed/config_test.go
embed/etcd.go

Fix https://github.com/coreos/etcd/issues/9337.

embed: fix revision-based compaction with default value

---

etcdctl/ctlv2/command/backup_command.go
tools/functional-tester/etcd-runner/command/global.go

```
govet -all -shadow checking failed:
etcdctl/ctlv2/command/backup_command.go:192: declaration of "src" shadows declaration at etcdctl/ctlv2/command/backup_command.go:189
etcdctl/ctlv2/command/backup_command.go:192: declaration of "src" shadows declaration at etcdctl/ctlv2/command/backup_command.go:189
etcdctl/ctlv2/command/backup_command.go:192: declaration of "src" shadows declaration at etcdctl/ctlv2/command/backup_command.go:189
tools/functional-tester/etcd-runner/command/global.go:109: declaration of "endpoints" shadows declaration at tools/functional-tester/etcd-runner/command/global.go:33
tools/functional-tester/etcd-runner/command/global.go:109: declaration of "endpoints" shadows declaration at tools/functional-tester/etcd-runner/command/global.go:33
```

*: fix govet -shadow warnings

---

raft/raft.go
raft/raft_paper_test.go
raft/raft_test.go

`raft.Step` already ensures that when `m.Term > r.Term`, candidate reverts back to follower with its term being reset with `m.Term`, thus it's always true that `m.Term == r.Term` in `stepCandidate`. This just makes `r.becomeFollower` calls consistent. Also add tests around this behavior.
Also document why `stepCandidate` should reuse candidate's own term, not `m.Term`. This is because pre-vote is requested with future term.

raft: clarify candidate message handling, test candidate to follower transition with message from leader

---

etcdctl/ctlv3/command/check.go
etcdctl/ctlv3/command/util.go

Running check datascale can create large history of keyspaces and
internal fragmentation. Allow user to run auto compact and defrag
when run check datascale.

etcdctl/check: enable auto compact and defrag for check datascale

---

Documentation/op-guide/grpc_proxy.md

I noticed that the docs mention the grpc proxy will listen on port 8080,
but the above example is explicitly telling it to listen on 2379.
Removing confusion.

documentation: updated grpc documentation

---

pkg/testutil/var.go
snapshot/member_test.go

Membership reconfiguration may not be applied
when the new member joins. Also pass all endpoints
to check restore data in case of leader election or
network faults.
Fix https://github.com/coreos/etcd/issues/9219 and https://semaphoreci.com/coreos/etcd/branches/master/builds/2878.
> --- FAIL: TestSnapshotV3RestoreMultiMemberAdd (14.75s)
member_test.go:78: error validating peerURLs {ClusterID:2dcab7bbeafb497c Members:[&{ID:42fbaab60780e599 RaftAttributes:{PeerURLs:[unix://localhost:18469]} Attributes:{Name:0 ClientURLs:[unix://localhost:42777]}} &{ID:fd5b89a5f93ca727 RaftAttributes:{PeerURLs:[unix://localhost:29664]} Attributes:{Name:1 ClientURLs:[unix://localhost:35826]}} &{ID:336967b030dec3fa RaftAttributes:{PeerURLs:[unix://localhost:10625]} Attributes:{Name:2 …

snapshot: fix "TestSnapshotV3RestoreMultiMemberAdd"

---

etcdserver/raft.go

We enable "raft.Config.CheckQuorum" by default in other
Raft initial starts. So should start with "ForceNewCluster".
If new members are added to standalone node with `CheckQuorum == false` and the standalone node is the leader, this may reduce cluster availabilities, since the leader won't check quorum activities.
For current etcd, it won't help a lot, but once we enable Pre-Vote, this will be useful. For instance, `pb.MsgAppResp` from isolated candidate may be dropped or not even be triggered with Pre-Vote, and then `pb.Msg[Pre]Vote` arrives with higher term. And if the check quorum is false, the vote request would force current leader to step down even if the leader lease is still valid. If check quorum is true, the vote request will be ignored when its leader lease is still valid, thus …

etcdserver: enable "CheckQuorum" when starting with "ForceNewCluster"

---

Documentation/op-guide/recovery.md

Highlight the discussions from https://github.com/coreos/etcd/pull/9177.

Documentation/op-guide: discourage "--force-new-cluster" in recovery

---

lease/lessor.go

lease: Change lease Mutex to RWMutex
When the lease gets huge, etcd costs too much time on lease map ranging, leading to updating requests timeout. Change the Mutex to RWMutex may be helpful.
related: https://github.com/coreos/etcd/issues/9159

lease: Change lease Mutex to RWMutex

---

rafthttp/transport.go

"ActiveSince" is read-only, and should be able to call
concurrently, as long as there is no routine holding
write lock (send, send snapshot).
e.g. "ActiveSince" is used around etcd server
"processInternalRaftRequestOnce", should be non-blocking

rafthttp: make "ActiveSince" non-blocking on write lock

---

auth/nop.go
auth/store.go

This commit adds a new auth token provider named nop. The nop provider
refuses every Authenticate() request so CN based authentication can
only be allowed. If the tokenOpts parameter of auth.NewTokenProvider()
is empty, the provider will be used.
Fix https://github.com/coreos/etcd/issues/9349
/cc @stts @gyuho

auth: a new auth token provider nop

---

embed/serve.go

@hexfusion We forgot to rename it.

embed: rename "v3alphaMutator" to "v3Mutator"

---

Documentation/op-guide/configuration.md
auth/jwt.go
e2e/cluster_test.go
e2e/ctl_v3_auth_test.go

This commit adds a new option of --auth-token, ttl, for configuring
TTL of jwt tokens. It can be specified like this:
```
--auth-token jwt,pub-key=<pub key path>,priv-key=<priv key path>,sign-method=<sign method>,ttl=5m
```
In the above case, TTL will be 5 minutes.
/cc @fanminshi

auth: a new option for configuring TTL of jwt tokens

---

CHANGELOG-3.2.md
CHANGELOG-3.3.md
CHANGELOG-3.4.md
hack/scripts-dev/docker-dns/insecure/run.sh

Separate commits from https://github.com/coreos/etcd/pull/9379 to make backport easier.

CHANELOG/hack: add Election HTTP API fix

---

e2e/util.go
e2e/v3_curl_test.go
etcdserver/api/v3election/election.go

Server should never panic from wrong-formatted client requests. Without this patch, `/v3/election/proclaim` request with `leader` field missing can panic etcd servers.
@jpbetz This needs 3.2 backport as well.

*: fix server panic on invalid Election Proclaim/Resign HTTP requests

---

pkg/flags/flag.go
pkg/flags/flag_test.go

Fix https://github.com/coreos/etcd/issues/8380.
```
export ETCD_NAME=aaaaa
./bin/etcd --name bbb
2018-03-02 10:27:49.770161 C | pkg/flags: conflicting environment variable "ETCD_NAME" is shadowed by corresponding command-line flag (either unset environment variable or disable flag)
export ETCDCTL_ENDPOINTS=aaaaa.com
ETCDCTL_API=3 ./bin/etcdctl endpoint health --endpoints=bbb.com
2018-03-02 10:28:09.438985 C | pkg/flags: conflicting environment variable "ETCDCTL_ENDPOINTS" is shadowed by corresponding command-line flag (either unset environment variable or disable flag)
```

pkg/flags: fatal on conflicting environment variable

---

etcdctl/README.md

Create documentation for check datascale.
Fixes #9327

etcdctl/doc: create doc for check datascale

---

Documentation/op-guide/maintenance.md
etcdctl/README.md
etcdctl/ctlv3/command/defrag_command.go

Had a customer hit database size limit issue, but the doc was not clear about `--endpoints` flag in `defrag` command.

*: add "--cluster" flag to defrag, highlight defrag endpoints

---

embed/config.go
embed/etcd.go
etcdmain/config.go
etcdmain/help.go
etcdserver/config.go
etcdserver/raft.go
etcdserver/server.go
raft/raft.go
raft/raft_test.go

Address https://github.com/coreos/etcd/issues/9333 and https://github.com/coreos/etcd/issues/8499.
/cc @wojtek-t @jpbetz 
In simplest form, Raft leader steps down to follower when it receives a message with higher term. For instance, a flaky(or rejoining) member drops in and out, and starts campaign. This member will end up with a higher term, and ignore all incoming messages with lower term. In this case, a new leader eventually need to get elected, thus disruptive to cluster availability. Same happens with isolated member or slow incoming network. In etcd, isolated member with higher term would send `pb.MsgAppResp`, in response to `pb.MsgHeartbeat` from leader, and [`pb.MsgAppResp` to leader forces leader to step down, and cluster becomes …

*: configure Raft Pre-Vote to reduce disruptive rejoining servers

---

mvcc/watchable_store.go
mvcc/watchable_store_test.go

Cherry pick of #9297 on release-3.1.
When discussing the rollback of etcd server from 3.2 to 3.1 for kubernetes 1.10 (https://github.com/kubernetes/kubernetes/pull/60891), one of the concerns with etcd 3.1 was that it was missing this fix. The good news is that etcd 3.1 already contains all other critical fixes for kubernetes except this one.
We're aware that etcd 3.1 is no longer supported, but are hoping to get this fix in as it's considered critical and will be considerable help to the kubernetes community.
#9297: mvcc: restore unsynced watchers

Automated cherry pick of #9297

---

proxy/httpproxy/reverse.go

Cherry pick of #9336 on release-3.2.
#9336: httpproxy: cancel requests when client closes a connection

Automated cherry pick of #9336

---

etcdserver/raft.go

Cherry pick of #9347 on release-3.2.
#9347: etcdserver: enable "CheckQuorum" when starting with

Automated cherry pick of #9347

---

CHANGELOG-3.1.md

Update changelog for 3.1.12 backports. Also make a couple minor corrections to the 3.1.11 changelog.

CHANGELOG: etcd 3.1.12 backports

---

CHANGELOG-3.2.md
CHANGELOG-3.3.md
CHANGELOG-3.4.md
clientv3/integration/lease_test.go
clientv3/options.go
etcdserver/api/v3rpc/rpctypes/error.go
etcdserver/api/v3rpc/util.go
lease/lessor.go
lease/lessor_test.go

math.MaxInt64 / time.Second is 9,223,372,036. 9,000,000,000 is easier to
remember/document.
Closes #9374.

*: enforce max lease TTL with 9,000,000,000 seconds

---

etcdserver/raft.go
etcdserver/server.go
etcdserver/util_test.go
rafthttp/transport.go

Address https://github.com/coreos/etcd/issues/9333 with simpler logic.
Single-node restart with no snapshot does not need special handling, because itself will be elected as leader, by the time peer connection report wait times out.
<br>
Fresh start 1-node cluster
> 15:45:34.940350 I | etcdserver: 8e9e05c52164694d as single-node; fast-forwarding 9 ticks (election ticks 10)
> 15:45:34.940911 I | etcdserver/membership: added member 8e9e05c52164694d [http://localhost:2380] to cluster cdf818194e3a8c32
> 15:45:35.233465 I | raft: 8e9e05c52164694d is starting a new election at term 1
> 15:45:35.233525 I | raft: 8e9e05c52164694d became candidate at term 2  
> 15:45:35.233559 I | raft: 8e9e05c52164694d received MsgVoteResp from 8e9e05c52164694d at term 2
> 15:45:35.233596 I | raft: …

etcdserver: adjust election timeout on restart

---

CHANGELOG-3.1.md
CHANGELOG-3.2.md
CHANGELOG-3.3.md

And add notes in preparation of 3.1.13 and 3.2.18

CHANGELOG: set dates for 3.1.12 & 3.2.17 release

---

test

Enable user to run specified test case with different TIMEOUT expectation when needed.

scripts: add TESTCASE flag to run single unit test

---

Documentation/op-guide/grafana.json

Prometheus that scrapes etcd might also scrape other things, so we should specifically ask for etcd metrics, especially when dealing with generic metrics like `process_resident_memory_bytes`.

Documentation/op-guide: add job="etcd" label matcher to Grafana dashboard

---

Documentation/dev-guide/api_reference_v3.md
Documentation/dev-guide/apispec/swagger/rpc.swagger.json
etcdserver/api/v3rpc/header.go
etcdserver/api/v3rpc/maintenance.go
etcdserver/api/v3rpc/watch.go
etcdserver/etcdserverpb/rpc.pb.go
etcdserver/etcdserverpb/rpc.proto
etcdserver/raft.go
etcdserver/raft_test.go
etcdserver/server.go
etcdserver/v2_server.go

Some refactoring. And endpoint status command was returning applied index for "raft index" field (https://github.com/coreos/etcd/pull/9176); now returns correct committed index.

*: clean up etcdserver raft handler, fix "endpoint status" Raft index field

---

mvcc/backend/backend.go

From https://github.com/coreos/etcd/commit/3ebee21407da8913f183a9e1354513ba8759521e.
```bash
$ go test -v -run TestV3MaintenanceDefragmentInflightRange -race
=== RUN   TestV3MaintenanceDefragmentInflightRange
Write at 0x00c42026aba0 by goroutine 121:
runtime.mapdelete_faststr()
/usr/local/go/src/runtime/hashmap_fast.go:883 +0x0
./mvcc/backend.(*txBuffer).reset()
./mvcc/backend/tx_buffer.go:31 +0x17f
./mvcc/backend.(*readTx).reset()
./mvcc/backend/read_tx.go:117 +0x42
./mvcc/backend.(*backend).defrag()
./mvcc/backend/backend.go:348 +0x95f
./mvcc/backend.(*backend).Defrag()
./mvcc/backend/backend.go:293 +0x38
./etcdserver/api/v3rpc.(*maintenanceServer).Defragment()
./etcdserver/api/v3rpc/maintenance.go:72 +0xb1 …
```

mvcc/backend: defrag to block concurrent read requests while resetting tx

---

Documentation/tuning.md

Tunning: Network
The higher priority port is 2379 instead of 2739

Documentation: 2379 port mistake

---

e2e/v3_curl_test.go

small cleanup while reviewing curl tests.

e2e: remove duplicate error check

---

clientv3/balancer/doc.go
clientv3/balancer/grpc1.7-health.go
clientv3/balancer/grpc1.7-health_test.go
clientv3/client.go
clientv3/retry.go

Preparing balancer rewrite with new gRPC.

clientv3: move health balancer to "balancer"

---

auth/store.go
auth/store_test.go
clientv3/auth.go
clientv3/client.go
e2e/v3_curl_test.go
etcdserver/api/v3rpc/rpctypes/metadatafields.go
proxy/grpcproxy/util.go

Current etcd code uses the string literal ("token") as a field name of
grpc metadata for passing token. It is difficult to maintain so this
commit introduces a new constant for the purpose.
/cc @hexfusion

*: don't use a string literal directly in grpc metadata

---

CHANGELOG-3.1.md
CHANGELOG-3.2.md
CHANGELOG-3.3.md
Documentation/op-guide/maintenance.md

Related to https://github.com/coreos/etcd/pull/9443.
This summarizes how our auto-compaction logic has been changed.
/cc @fanminshi @yudai

*: document auto-compaction logic

---

CHANGELOG-3.4.md
Documentation/upgrades/upgrade_3_4.md
clientv3/yaml/config.go
e2e/cluster_proxy_test.go
e2e/cluster_test.go
embed/config.go
embed/config_test.go
etcdctl/ctlv2/command/util.go
etcdctl/ctlv3/command/global.go
etcdctl/ctlv3/ctl.go
etcdmain/config.go
etcdmain/grpc_proxy.go
etcdmain/help.go
pkg/transport/listener.go
pkg/transport/listener_test.go
tools/benchmark/cmd/root.go

`ca-file` flags were deprecated in v2.1 (3 years ago).
Should be safe to deprecate.
Checked Kubernetes upstream not using these flags either.
Fix https://github.com/coreos/etcd/issues/9432.

*: document deprecated ca-file flags (since v2.1)

---

compactor/compactor.go
compactor/periodic.go
compactor/periodic_test.go
compactor/revision.go
compactor/revision_test.go

Separate clean up changes from https://github.com/coreos/etcd/pull/9474.

compactor: clean up

---

e2e/util.go
e2e/v3_curl_lease_test.go
e2e/v3_curl_test.go

With a focus on Lease this is my initial stab at refactoring e2e grpc gateway tests. Next phase will be breaking out existing curl tests into separate files and providing full TLS coverage in prep for stable v3/.
ref: https://github.com/coreos/etcd/issues/9189, https://github.com/coreos/etcd/pull/9450

e2e: add gRPC gateway Lease tests

---

compactor/periodic.go
compactor/periodic_test.go

Simplified version of https://github.com/coreos/etcd/pull/9482.
Similar to how v3.2 works while handling compaction period <1-hour.
Address https://github.com/coreos/etcd/pull/9443.

compactor: adjust interval for period <1-hour

---

Documentation/upgrades/upgrade_3_0.md
Documentation/upgrades/upgrade_3_1.md
Documentation/upgrades/upgrade_3_2.md
Documentation/upgrades/upgrade_3_3.md
Documentation/upgrades/upgrade_3_4.md

Fix https://github.com/coreos/etcd/issues/9480.

Documentation: highlight v3 post migration

---

rafthttp/peer.go
rafthttp/remote.go

Cherry pick of #9437 on release-3.2.
#9437: rafthttp: add missing "peer_sent_failures_total" metrics call

Automated cherry pick of #9437
