clientv3/watch.go
=> clientv3: register waitCancelSubstreams closingc goroutine with waitgroup

etcdctl/ctlv3/command/elect_command.go, etcdctl/ctlv3/command/lock_command.go, main_test.go, pkg/netutil/netutil_test.go, test
=> test: fix fmt pass, shorten warnings, clear SA1016

Documentation/platforms/aws.md
Add guide for deployed etcd on AWS discussing resource planning and cluster design
=> Adds AWS platform guide

README.md, etcdctl/ctlv3/help.go, tools/functional-tester/etcd-runner/help.go
Same as https://github.com/rkt/rkt/pull/3634.
=> *: coreos/rkt -> rkt/rkt

tools/benchmark/cmd/txn_put.go
Submits multiple put ops in a single txn.
=> benchmark: add txn-put benchmark

test, tools/benchmark/cmd/lease.go, tools/benchmark/cmd/put.go
ref. https://golang.org/cmd/gofmt/#hdr-The_simplify_command
=> tools/benchmark: fix misc gofmt warnings

Documentation/docs.md
=> Documentation: reshuffle op-guide to include platforms and upgrading

Documentation/v2/libraries-and-tools.md
Adding a separate v2 and a v3 API binding for C++.
Signed-off-by: csatari <gergely.csatari@nokia.com>
=> Adding C++ bindings

pkg/report/report_test.go
Currently no coverage according to codecov
=> report: add test for Report interface

auth/simple_token.go
run goroutine was resetting a field for no reason and without holding a lock.
This patch cleans up the run goroutine management to make the start/stop path
less racey in general.
/cc @mitake 
Failure from proxy-ci:
```
Read at 0x00c4285902e0 by goroutine 211:
github.com/coreos/etcd/auth.(*simpleTokenTTLKeeper).resetSimpleToken()
/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/auth/simple_token.go:62 +0x3f
github.com/coreos/etcd/auth.(*tokenSimple).info()
/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/auth/simple_token.go:175 +0x24c
github.com/coreos/etcd/auth.(*authStore).authInfoFromToken()
/home/jenkins/workspace/etcd-proxy/gopath/src/github.com/coreos/etcd/auth/store.go:663 +0xa7 …
```
=> auth: fix race on stopping simple token keeper

etcdctl/ctlv3/command/printer_fields.go
=> etcdctl: show responses of auth RPCs if --write-output=fields is passed

Documentation/op-guide/v2-migration.md
=> op-guide: add command for checking if there's any v3 data

raft/log_unstable.go
Accumulation of old entries in the underlying array backing the
entries slice has been found to cause massive memory growth in
CockroachDB for workloads that do large (1MB) writes
(https://github.com/cockroachdb/cockroach/issues/14776)
This doesn't appear to have much consistent effect on the raft
benchmarks, although it's worth noting that they vary quite a bit
between runs so it's kind of tough to draw strong conclusions from them.
Let me know if there are any different benchmarks you'd like me to run!
```
benchmark              old ns/op     new ns/op     delta
BenchmarkOneNode-8     3283          3125          -4.81%
benchmark              old allocs     new allocs     delta
BenchmarkOneNode-8     6              6              +0.00%
benchmark              old bytes     new bytes …
```
=> raft: Avoid holding unneeded memory in unstable log's entries array

NEWS
=> NEWS: update v3.1.6

clientv3/integration/lease_test.go
Server Stop+Restart sometimes takes more than 500ms, so with a
one second window the lease client may not get a chance to issue
a keepalive and get a lease extension before the lease client
timer elapses. Instead, sleep for a shorter period of time (while
still guaranteeing a keepalive resend during quorum loss) and
skip the test if server restart takes longer than the lease TTL.
Fixes #7346
=> clientv3/integration: sleep less in TestLeaseRenewLostQuorum

embed/serve.go, etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go, etcdserver/api/v3lock/v3lockpb/gw/v3lock.pb.gw.go, etcdserver/etcdserverpb/gw/rpc.pb.gw.go, scripts/genproto.sh, test
=> *: put gateway stubs in packages separate from pb stubs

integration/cluster.go, mvcc/key_index.go, pkg/schedule/schedule.go, store/node.go
Cf. https://travis-ci.org/coreos/etcd/jobs/224498875
=> *: clear redundant return statement warnings (S1027)

tools/functional-tester/etcd-runner/command/election_command.go, tools/functional-tester/etcd-runner/command/global.go, tools/functional-tester/etcd-runner/command/help.go, tools/functional-tester/etcd-runner/command/lease_renewer_command.go, tools/functional-tester/etcd-runner/command/lock_racer_command.go, tools/functional-tester/etcd-runner/command/root.go, tools/functional-tester/etcd-runner/command/watch_command.go, tools/functional-tester/etcd-runner/main.go
This is a preliminary pr for integrating etcd runner with etcd tester.
=> etcd-runner: fix runner and minor refactoring.

.travis.yml, bill-of-materials.json, cmd/vendor/github.com/bgentry/speakeasy/LICENSE, cmd/vendor/github.com/bgentry/speakeasy/speakeasy.go, cmd/vendor/github.com/bgentry/speakeasy/speakeasy_unix.go, cmd/vendor/github.com/bgentry/speakeasy/speakeasy_windows.go, glide.lock, glide.yaml, test
Fixes #7780 
WIP since the generated license-bill-of-materials doesn't look quite right
=> CI BOM checking

clientv3/concurrency/election.go, integration/v3_election_test.go
Watching from the leader's ModRevision could cause live-locking on
observe retry loops when the ModRevision is less than the compacted
revision. Instead, start watching the leader from at least the store
revision of the linearized read used to detect the current leader.
Fixes #7815
=> concurrency: use current revisions for election

pkg/wait/wait.go
Closing https://github.com/coreos/etcd/pull/5010.
Trying to clean up old pending PRs before rc release.
=> pkg/wait: add comment and make List private

scripts/build-aci
=> scripts: annotate with acbuild with supports-systemd-notify

Documentation/op-guide/container.md
=> Documentation: add documentation for single node docker etcd

README.md
Just be consistent with the messaging and use of etcd
=> README: use the same tagline from github

tools/functional-tester/etcd-agent/agent.go, tools/functional-tester/etcd-agent/main.go
Otherwise, etcd-agent in container has no access to
host volume.
=> etcd-agent: store failure_archive in log dir

etcdctl/ctlv3/command/printer.go, tools/functional-tester/etcd-agent/agent.go
=> *: remove unnecessary fmt.Sprint

etcdserver/snapshot_merge.go
for https://github.com/coreos/etcd/issues/7944
=> etcdserver: more logging on snapshot close path

pkg/report/report.go, pkg/report/report_test.go, pkg/report/weighted.go
Reports with weighted results.
Something like `report.Options` to get the `NewReport(WithWhatever(), WithWhatever2())` pattern instead of all these special constructors would be good, but that'll break outside deps (e.g., dbtester) and can be rolled into another PR.
/cc @mitake @gyuho
=> report: add NewWeightedReport

clientv3/clientv3util/util.go, clientv3/naming/doc.go, clientv3/yaml/config.go, contrib/recipes/doc.go, etcdserver/membership/doc.go, pkg/srv/srv.go, pkg/stringutil/stringutil.go, proxy/grpcproxy/cache/store.go, tools/functional-tester/etcd-runner/command/root.go
Words for the blank boxes in https://godoc.org/github.com/coreos/etcd
=> *: fill out missing package godocs

tools/functional-tester/etcd-tester/failpoint.go, tools/functional-tester/etcd-tester/main.go
=> etcd-tester: add '-failpoints' to configure gofail

Documentation/dev-guide/api_concurrency_reference_v3.md, Documentation/dev-guide/api_reference_v3.md, scripts/genproto.sh
=> Documentation, scripts: regenerate protobuf docs with updated protodoc

Documentation/learning/api.md
=> documentation: fixed typo

etcdctl/README.md, etcdctl/ctlv3/command/role_command.go
Add `--prefix` to `role revoke-permission`, consolidate permission range handling, update README with example
Fixes #7951
=> etcdctl: improve role --prefix flag

Documentation/docs.md, Documentation/platforms/container-linux-systemd.md
Fix https://github.com/coreos/docs/issues/1062.
=> Documentation: add systemd, Container Linux guide

etcdserver/server.go
Scheduled compaction will panic if KV is not stopped before
closing the backend.
via inspecting code paths related to #7957
=> etcdserver: close mvcc.KV on init error path

Documentation/production-users.md
=> doc: modify vonage usecase, adding kubernetes and vault

Documentation/faq.md
This is becoming "frequently asked".
Also moves miscategorized cluster id mismatch entry from "performance"
to "operation".
=> Documentation: add FAQ entry for "database space exceeded" errors

Documentation/upgrades/upgrade_3_2.md
Fix https://github.com/coreos/etcd/issues/7998.
=> Documentation: add 'yaml.NewConfig' change in 3.2

Documentation/op-guide/gateway.md
=> op-guide: document configuration flags for gateway

Documentation/op-guide/security.md, Documentation/v2/security.md
Address some of the confusion from #8020
=> op-guide: document CN certs in security.md

Documentation/integrations.md
I've been working on building out this client for some time. I feel it's now feature-complete enough to be listed here 😃
=> doc: add mixer/etcd3 as a Node.js client integration

Documentation/op-guide/grafana.json
Demo http://dash.etcd.io/dashboard/db/test-etcd.
=> Documentation/op-guide: fix typo in grafana.json

client/example_keys_test.go, client/main_test.go
Supersedes PRs #3985 and #3999
=> client: add golang examples for KeysAPI

.travis.yml, build, scripts/build-aci, scripts/build-docker, scripts/genproto.sh, scripts/release.sh, scripts/updatedep.sh, test
Left a few suppressions since there's about 180 errors remaining and shell code tends to be somewhat delicate. Can clear them all in this shot if it makes sense.
=> test: shellcheck

client/example_keys_test.go
=> client: sort nodes in example

e2e/ctl_v3_auth_test.go
Wasn't being covered
/cc @mitake
=> e2e: add role get and role list e2e tests

auth/jwt.go, auth/jwt_test.go
wasn't being covered by CI
/cc @mitake
=> auth: JWT tests

NEWS
Will update the date when we actually release it. (Will merge right before the release).
Please let me know if I am missing anything.
=> NEWS: add v3.2.0

integration/cluster_proxy.go, proxy/grpcproxy/adapter/auth_client_adapter.go
not yet covered: https://codecov.io/gh/coreos/etcd/src/master/proxy/grpcproxy/auth.go
=> integration: test auth layer in grpc proxy tests

bill-of-materials.json, bill-of-materials.override.json
Fix https://github.com/coreos/etcd/issues/8086.
=> bill-of-materials: regenerate with multi licenses

Documentation/op-guide/etcd3_alert.rules, Documentation/v2/etcd_alert.rules
Hi~
When I used the default alert rule files to do the alert job, I found some small bugs. Here is the fix and tested on my environment.
=> Documentation: alert.rules. fix labels bug

Documentation/faq.md
Been seeing this somewhat frequently.
=> Documentation: update FAQ with entry about changing peer advertising

Documentation/dl_build.md
1. Removed a redundant step
2. minimal editing
=> etcd/Documentation/dl_build.md: removed an extra step for testing etcd 

CODE_OF_CONDUCT.md
github community insights complains there isn't one
=> *: add code of conduct

Documentation/dev-internal/release.md
Thanks to https://github.com/coreos/etcd/issues/8085#issuecomment-308232300.
=> Documentation/release: sign *.aci files

clientv3/integration/watch_test.go
=> clientv3/integration: wait for leader before trying to count watches

integration/v3_auth_test.go
This commit add a new test case which ensures that non authorized RPCs
failed with ErrUserEmpty. The case can happen in a schedule like
below:
1. create a cluster
2. create clients
3. enable authentication of the cluster
4. the clients issue RPCs
Fix https://github.com/coreos/etcd/issues/7770
=> integration: add a test case for non authorized RPCs

raft/node_test.go, raft/raft.go
this allows users to disable followers from forwarding proposals to the
leader.
=> raft: add DisableProposalForwarding option

NEWS
Highlights some important bug fixes + user facing
changes in debugging metrics.
=> NEWS: add v3.2.1

Documentation/faq.md
Signed-off-by: Hui Kang <kangh@us.ibm.com>
=> Documentation/faq: fix typo in flag names

NEWS
=> NEWS: clarify the corruption problem

Documentation/dev-guide/local_cluster.md
Tested the content, added clarification to the concepts, and organized the doc
=> dev-guide: clarify concepts in local_cluster doc

version/version.go
Master branch should be `3.2.0+git`
=> version: bump up to 3.2.0+git

Documentation/learning/api.md
Replace https://github.com/coreos/etcd/pull/8089.
=> Documentation: refer to LeaseKeepAliveRequest for lease refresh

clientv3/integration/lease_test.go
Linearized read to ensure the keys have committed.
Cf. https://semaphoreci.com/coreos/etcd/branches/pull-request-8259/builds/2
=> integration: sync lapi server after puts in TestLeaseTimeToLive

CONTRIBUTING.md
#coreos is too noisy and #etcd is already in the readme
=> Documentation: point contributing irc channel to #etcd

Documentation/integrations.md
As suggested by @philips on Twitter
=> Add lclarkmichalek/etcdhcp to integrations list

etcdmain/etcd.go
Fixes failures from TestCtlV3PutClientAutoTLS in proxy coverage tests.
=> etcdmain: create self-signed certs when listening on https for httpproxy

Documentation/learning/why.md
=> docs: slight rearranging of top two sections.

integration/v3_grpc_test.go
Fix https://github.com/coreos/etcd/issues/8235.
=> integration: increase dial timeout in testTLSReload

clientv3/concurrency/example_election_test.go, clientv3/concurrency/example_mutex_test.go, clientv3/concurrency/example_stm_test.go, clientv3/concurrency/main_test.go
A few people have asked about this.
=> concurrency: add election example

Documentation/op-guide/grpc_proxy.md
Also made the etcdctl calls consistent across the file.
=> op-guide: TLS termination with grpc-proxy

mvcc/kv_test.go, mvcc/kvstore.go
=> mvcc: reset keys gauge on restore

cmd/vendor/github.com/coreos/bbolt/db.go, cmd/vendor/github.com/coreos/bbolt/freelist.go, cmd/vendor/github.com/coreos/bbolt/tx.go, cmd/vendor/github.com/russross/blackfriday/html.go, cmd/vendor/github.com/russross/blackfriday/smartypants.go, glide.lock, glide.yaml, integration/metrics_test.go
Once merged, I will redeploy functional tester cluster.
=> vendor: coreos/bbolt v1.3.1-coreos.0, add others in glide.yaml

embed/config.go, etcd.conf.yml.sample
Fix https://github.com/coreos/etcd/issues/8402.
=> embed: add 'enable-pprof' tag for config file

Documentation/production-users.md
Close https://github.com/coreos/etcd/pull/8375.
=> Documentation: Update to include Huawei (renamed Canal)

etcdctl/README.md
=> etcdctl: document getting all keys with etcdctl3

clientv3/integration/leasing_test.go, clientv3/leasing/kv.go, etcdmain/grpc_proxy.go
Semaphore was seeing goroutine leaks
=> leasing, integration, etcdmain: closer function for leasing kv

Documentation/op-guide/monitoring.md
=> op-guide: add /debug details

cmd/vendor/github.com/spf13/pflag/bool.go, cmd/vendor/github.com/spf13/pflag/bool_slice.go, cmd/vendor/github.com/spf13/pflag/count.go, cmd/vendor/github.com/spf13/pflag/flag.go, cmd/vendor/github.com/spf13/pflag/float32.go, cmd/vendor/github.com/spf13/pflag/float64.go, cmd/vendor/github.com/spf13/pflag/golangflag.go, cmd/vendor/github.com/spf13/pflag/int.go, cmd/vendor/github.com/spf13/pflag/int32.go, cmd/vendor/github.com/spf13/pflag/int64.go, cmd/vendor/github.com/spf13/pflag/int8.go, cmd/vendor/github.com/spf13/pflag/ip.go, cmd/vendor/github.com/spf13/pflag/ip_slice.go, cmd/vendor/github.com/spf13/pflag/ipnet.go, cmd/vendor/github.com/spf13/pflag/string.go, cmd/vendor/github.com/spf13/pflag/string_array.go, cmd/vendor/github.com/spf13/pflag/string_slice.go, cmd/vendor/github.com/spf13/pflag/uint.go, cmd/vendor/github.com/spf13/pflag/uint16.go, cmd/vendor/github.com/spf13/pflag/uint32.go, cmd/vendor/github.com/spf13/pflag/uint64.go, cmd/vendor/github.com/spf13/pflag/uint8.go, cmd/vendor/github.com/spf13/pflag/uint_slice.go, glide.lock, glide.yaml
cut first release about a month ago
=> vendor: spf13/pflags v1.0.0

mvcc/backend/backend.go, mvcc/backend/batch_tx.go, mvcc/backend/read_tx.go, mvcc/kvstore_bench_test.go
mvcc has benchmarks for Put but not Range.
=> mvcc: benchmark Range() on a single key

clientv3/integration/leasing_test.go, clientv3/leasing/kv.go
TTL'd keys may expire on cluster without lease holder's consent.
=> leasing: don't acquire lease on ttl'd keys

clientv3/README.md
=> clientv3: fix godoc badge link

etcdmain/config.go, pkg/flags/strings.go, pkg/flags/strings_test.go
when init flagSet, set default value should be moved to StringFlags init
func, which is more friendly
personal proposal
=> flag: improve StringFlags by support set default value when init

mvcc/watchable_store.go, mvcc/watchable_store_test.go, mvcc/watcher.go
=> mvcc: only remove watch cancel after cancel completes

pkg/pbutil/pbutil_test.go
=> Fix go vet errors

pkg/netutil/netutil_test.go
add tests for http/https mismatch and unix scheme
=> netutil: test schemes for URLStringsEqual

Documentation/learning/data_model.md
=> Documentation: modifying a key does not create a new gen in data model

lease/doc.go, lease/lessor.go
typo: implemetation  -> implementation
=> lease: fix typo and modify findExpiredLeases function

wal/decoder.go, wal/wal.go, wal/wal_test.go
Distinguish temp wal file from available wal file.
=> wal: tiny refactor

clientv3/client.go, clientv3/leasing/kv.go, clientv3/retry.go, etcdserver/api/v3rpc/rpctypes/error.go, etcdserver/api/v3rpc/rpctypes/error_test.go, integration/v3_grpc_inflight_test.go, integration/v3_grpc_test.go, integration/v3_lease_test.go, proxy/grpcproxy/cluster.go, proxy/grpcproxy/leader.go, tools/functional-tester/etcd-runner/command/lease_renewer_command.go, tools/functional-tester/etcd-tester/key_stresser.go
grpc.Code, grpc.ErrorDesc, grpc.Errorf have been deprecated.
=> *: deprecate grpc.Code, grpc.ErrorDesc

clientv3/concurrency/election.go, clientv3/namespace/kv.go, mvcc/index.go, pkg/report/timeseries.go, test
=> test: check for inconsistent receiver names

Documentation/platforms/aws.md
=> docs: remove link-breaking space

tools/functional-tester/etcd-agent/agent_test.go
Data directory is added automatially in commit 2e3d27e but test was
not updated.
=> functional-tester: don't specify data dir on tester side

clientv3/integration/leasing_test.go
Test cache invalidating in [txnLeasing.commitToCache](https://github.com/coreos/etcd/blob/master/clientv3/leasing/txn.go#L164) function.
=> clientv3/integration: test leasing txn invalidates deleted cache

Documentation/op-guide/configuration.md
=> Documentation/op-guide: fix typo in configuration.md

.travis.yml, client/keys.generated.go, client/main_test.go, clientv3/client.go, clientv3/integration/watch_test.go, clientv3/main_test.go, clientv3/naming/grpc_test.go, clientv3/ordering/kv_test.go, clientv3/ordering/util_test.go, compactor/revision_test.go, e2e/ctl_v3_role_test.go, e2e/etcd_spawn_cov.go, etcdctl/ctlv3/help.go, etcdserver/api/v2http/client.go, etcdserver/api/v2v3/store.go, proxy/tcpproxy/userspace.go, raft/progress.go, store/store_bench_test.go, store/store_ttl_test.go, test, tools/functional-tester/etcd-runner/command/help.go
Go report card already runs this. We should automate it in our fmt tests.
=> test: add 'ineffassign'

Makefile, e2e/docker-dns-srv/Dockerfile
To dockerize all test runs in Jenkins.
=> Makefile: add 'test-proxy', 'test-coverage'

CHANGELOG.md
=> CHANGELOG: add v3.2.9, minor updates

clientv3/balancer.go, clientv3/retry.go
Helpful for debugging client balancer.
=> clientv3: add debugging lines to 'retry' paths

clientv3/ordering/kv.go
Several goroutines may call setPrevRev concurrently with different revisions, all higher than prevRev. Previously all of these goroutines could set prevRev, so prevRev may be replaced by older one.
If response's revision equals to prevRev in kvOrdering.Get, there's no need to call setPrevRev.
=> clientv3/ordering: compare and update prevRev atomically

Makefile
`make docker-test-all` for tests in Semaphore CI. And fix `make test` command.
=> Makefile: fix 'test', add 'test-all' commands with docker

clientv3/integration/txn_test.go
see https://github.com/coreos/etcd/issues/8735
=> clientv3/integration: skip retry test on txn read

clientv3/integration/network_partition_test.go
For put, etcd can return timeout errors from network partitions.
=> clientv3/integration: match ErrTimeout in testNetworkPartitionBalancer

clientv3/integration/watch_keepalive_test.go
Previously, the ping interval is 4 seconds. And we only give the test 1s more before timing out, which is too short for slow machine.
Now I change the ping interval to 3 seconds, and remove a unnecessary sleep.
=> clientv3/integration: shorten keepalive timeout

clientv3/integration/watch_keepalive_test.go
The blackholed endpoint cannot be re-pined. Then it will make the waiting time longer than expected. Let us wait for it can be re-pined before blackhole ep1 to test re-pin.
=> clientv3/integration: fix keepalive by waiting for unhealthy

Documentation/integrations.md
=> Documentation: add OpenStack to integrations.md

clientv3/integration/server_shutdown_test.go
Address https://github.com/coreos/etcd/pull/8762#discussion_r147019068.
=> clientv3/integration: Get with context timeout

clientv3/integration/network_partition_test.go
=> clientv3/integration: fix a todo in testNetworkPartitionBalancer

tools/benchmark/cmd/root.go, tools/benchmark/cmd/util.go
Solves https://github.com/coreos/etcd/issues/8706
=> benchmark ask for password is not supplied

integration/cluster.go, integration/network_partition_test.go
Addressing https://github.com/coreos/etcd/issues/8781.
=> integration: expose ElectionTimeout method

cmd/vendor/github.com/coreos/bbolt/bolt_windows.go, glide.lock, glide.yaml
And pin some other dependencies.
=> vendor: upgrade coreos/bbolt to v1.3.1-coreos.3

store/stats.go
In Go tip https://travis-ci.org/coreos/etcd/jobs/296471879.
=> store/stats.go: fix gofmt warnings

Documentation/op-guide/grafana.json
Small fix on the unit in Client Traffic In, should be Bps, not short, see Client Traffic Out.Tested ok
=> Documentation/op-guide: fix unit in grafana

auth/store.go
=> auth: clean up mutex lock/unlocks

.semaphore.sh, hack/scripts-dev/Makefile
Fail CI tests like this https://semaphoreci.com/coreos/etcd/branches/pull-request-8834/builds/3.
=> test: fail when test times out

etcdmain/config.go, etcdmain/config_test.go, etcdmain/etcd.go
Fix https://github.com/coreos/etcd/issues/8800.
=> etcdmain: do not embed structs (fix go vet warnings)

hack/patch/README.md
Fix https://travis-ci.org/coreos/etcd/jobs/300256759#L825.
=> hack/patch: remove "you" in markdown doc

CHANGELOG.md, Documentation/upgrades/upgrade_3_1.md
ref. https://github.com/coreos/etcd/issues/8802
=> *: highlight gRPC metrics change in v3.1

clientv3/integration/kv_test.go, clientv3/integration/network_partition_test.go
Current, kv network partition tests do not specifically test
isolated leader case.
This PR moves TestKVSwitchUnavailable to network_partition_test.go
and make it always isolate leader.
=> clientv3/integration: test linearizable get with leader election, network partition

Dockerfile-test, client/keys.go, clientv3/client.go, contrib/raftexample/raft.go, embed/etcd.go, etcdctl/ctlv3/command/printer.go, etcdserver/raft.go, etcdserver/storage.go, integration/bridge.go, integration/embed_test.go, pkg/fileutil/lock_windows.go, pkg/netutil/routes_linux.go, pkg/report/report.go, pkg/testutil/leak.go, pkg/transport/keepalive_listener.go, pkg/types/set.go, store/node.go, test, tools/etcd-dump-db/backend.go, tools/etcd-dump-logs/main.go, wal/decoder.go, wal/encoder.go, wal/file_pipeline.go
Fix https://github.com/coreos/etcd/issues/8852.
=> *: fix naked returns, integrate with CI

cmd/vendor/google.golang.org/grpc/balancer_conn_wrappers.go, cmd/vendor/google.golang.org/grpc/clientconn.go, cmd/vendor/google.golang.org/grpc/credentials/credentials.go, cmd/vendor/google.golang.org/grpc/rpc_util.go, cmd/vendor/google.golang.org/grpc/server.go, cmd/vendor/google.golang.org/grpc/transport/http2_server.go, glide.lock, glide.yaml
Fix https://github.com/coreos/etcd/issues/8855.
=> vendor: upgrade grpc/grpc-go to v1.7.3

cmd/vendor/github.com/dustin/go-humanize/bigbytes.go, cmd/vendor/github.com/dustin/go-humanize/bytes.go, cmd/vendor/github.com/dustin/go-humanize/comma.go, cmd/vendor/github.com/dustin/go-humanize/commaf.go, cmd/vendor/github.com/dustin/go-humanize/humanize.go, cmd/vendor/github.com/dustin/go-humanize/number.go, cmd/vendor/github.com/dustin/go-humanize/si.go, cmd/vendor/github.com/dustin/go-humanize/times.go, glide.lock, glide.yaml
`grpc-gateway` just tagged a new version (same as `v1.3`).
=> vendor: upgrade grpc-gateway to v1.3.0, dustin/go-humanize

Documentation/upgrades/upgrade_3_3.md
Only document user-facing changes.
=> Documentation/upgrades: add 3.3 changes

pkg/flags/flag.go, pkg/flags/flag_test.go
Fix https://github.com/coreos/etcd/issues/8863.
=> pkg/flags: fix "SetFlagsFromEnv" error masking

CHANGELOG.md
In preparation for 3.1.11 patch release
=> CHANGELOG: add v3.1.11, bug fixes

embed/config.go, etcdmain/config_test.go
Address https://github.com/coreos/etcd/pull/8920#issuecomment-347347461.
=> embed: error on zero heartbeat-interval, election-timeout

embed/config.go
=> embed: provide more details on TLS handshake failure

CHANGELOG.md
=> CHANGELOG: add v3.2.11

Dockerfile-test, test
Fix https://github.com/coreos/etcd/issues/8924.
=> *: fix coverage test failures

embed/config.go
=> embed/config: remove v3.2 TODO

Documentation/integrations.md
Adding intergration reference to existing Perl modules [Net::Etcd](https://metacpan.org/release/Net-Etcd) and [Etcd](https://metacpan.org/release/Etcd).
=> Documentation/integrations: add Perl clients.

compactor/compactor.go
Cherry pick of #8999 on release-3.2.
#8999: compactor: fix error message of Revision compactor
=> Automated cherry pick of #8999

clientv3/client.go
=> Clientv3: Fix govet error for gotip

Documentation/integrations.md
Update Perl libraries to use global style...
=> Documentation/integrations: minor style fix.

etcdserver/api/capability.go, rafthttp/stream.go
/cc @xiang90 @jpbetz @fanminshi 
Will be the last PR to merge before cutting `release-3.3` branch.
=> *: server-side version bump up to 3.3

CHANGELOG.md
Plan is release tomorrow morning.
=> CHANGELOG: add v3.2.13, v3.3.0-rc.1

pkg/expect/expect.go
bufio.NewReader.ReadString blocks even
when the process received syscall.SIGKILL.
Remove ptyMu mutex and make ReadString return
when *os.File is closed.
File read polling in Go still seems leaky.
```
Too many goroutines running after all test(s).
2 instances of:
internal/poll.runtime_pollWait(...)
/usr/local/go/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(...)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:85 +0x9b
internal/poll.(*pollDesc).waitRead(...)
/usr/local/go/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(...)
/usr/local/go/src/internal/poll/fd_unix.go:135 +0x1dc
os.(*File).read(...)
/usr/local/go/src/os/file_unix.go:230 +0x4e
os.(*File).Read(...)
/usr/local/go/src/os/file.go:106 +0x6a
bufio.(*Scanner).Scan(...) …
```
=> pkg/expect: fix deadlock in macOS

clientv3/integration/black_hole_test.go, clientv3/integration/dial_test.go, clientv3/integration/kv_test.go, clientv3/integration/lease_test.go, clientv3/integration/network_partition_test.go, clientv3/integration/server_shutdown_test.go, clientv3/integration/watch_test.go, integration/cluster.go
I have begun stepping through the tests and defining constants. Before I get too far along I would like to get some general input on my naming and thoughts on extending constants via cluster. I appreciate you taking a look.
/cc @xiang90 @gyuho 
ref: https://github.com/coreos/etcd/issues/8781
=> integration: add constant requestWaitTimeout.

clientv3/integration/black_hole_test.go, clientv3/integration/dial_test.go
=> clientv3/integration: fix typos

etcdmain/etcd.go
Fix https://github.com/coreos/etcd/issues/9077.
ref. https://github.com/coreos/etcd/pull/9089#discussion_r159707772
=> etcdmain: unset ETCD_UNSUPPORTED_ARCH after arch check

raft/log_unstable.go
Cherry-pick https://github.com/coreos/etcd/pull/9102.
=> raft: fix wrong comments in "mustCheckOutOfBounds"

clientv3/watch.go
Fix https://github.com/coreos/etcd/issues/9103.
=> clientv3: document possible memory pile-up in Watch

ROADMAP.md
@xiang90 @jpbetz @hexfusion @spzala
=> ROADMAP: update 3.4 roadmap

Documentation/faq.md
For https://github.com/coreos/etcd/issues/9165.
/cc @saranbalaji90
We can add more details when @saranbalaji90 finds more about this later.
=> Documentation: add TCP RST flag on stream close

Documentation/op-guide/configuration.md
Fix https://github.com/coreos/etcd/issues/9164.
=> Documentation/op-guide: Clarify TLS "--peer" flags

Documentation/learning/why.md
=> Fix a typo

Documentation/op-guide/security.md
For https://github.com/coreos/etcd/issues/9181.
=> Documentation/op-guide: explain `--peer-cert-allowed-cn` in security.md

pkg/logger/discard.go, pkg/logger/package_logger.go
Rather than asserting inside functions.
=> pkg/logger: type-assert in global-scope

clientv3/namespace/doc.go
clientv3/namespace: fixed an error in the doc.go
=> clientv3/namespace: fixed an error in the doc.go

MAINTAINERS
Hitoshi has been involved in all components of etcd.
Thanks for your consistent and great work!
Also fix my name spelling.
=> MAINTAINERS: @mitake as "pkg:*" maintainer

MAINTAINERS, MAINTAINERS_RULES.md
/cc @heyitsanthony @xiang90 @fanminshi @jpbetz @hexfusion @spzala
=> MAINTAINERS: add "MAINTAINERS_RULES" and second email

snapshot/v3_snapshot.go
Fix https://github.com/coreos/etcd/issues/9248.
=> snapshot: clarify "Restore" method with conflicting data directory

Documentation/dev-internal/release.md
Now we are in 3.4 release cycle :)
@xiang90 @jpbetz
Thanks!
=> Documentation/dev-internal: update release managers with 3.3 release

CHANGELOG-3.3.md, Documentation/dev-guide/limit.md, Documentation/faq.md
Also mention that in v3.3 change log.
cc:/ @gyuho
=> *: Remove 8GiB quota limitation from documents

integration/metrics_test.go
Fix https://travis-ci.org/coreos/etcd/jobs/336753617#L750.
=> integration: fix govet error in Go tip

e2e/ctl_v3_user_test.go
This commit improves e2e coverage for user.
re: https://github.com/coreos/etcd/issues/9149
=> e2e: improve user coverage

CHANGELOG-3.2.md, CHANGELOG-3.3.md, CHANGELOG-3.4.md
Changes made in January and February, and add upcoming 3.2 and 3.3 patch release changelogs.
=> CHANGELOG: updates from January/February 2018

e2e/ctl_v3_auth_test.go, e2e/ctl_v3_lease_test.go
ref: https://github.com/coreos/etcd/issues/9149
=> e2e: improve Watch test coverage

CHANGELOG-3.4.md
added details to CHANGELOG for https://github.com/coreos/etcd/pull/9298
=> CHANGELOG: updates from #9298

build, test
=> test, build: Fix gopath creation

client/client_test.go, clientv3/clientv3util/example_key_test.go, etcdctl/ctlv3/command/check.go, raft/raft_test.go, tools/functional-tester/etcd-tester/main.go, tools/functional-tester/etcd-tester/stresser.go, tools/functional-tester/etcd-tester/tester.go
=> *: fix minor lint warnings

Documentation/learning/why.md
Just minor updates in doc. /cc @philips
=> Documentation: make "Consul" section more objective

build
```bash
./build: 68: ./build: Syntax error: "(" unexpected (expecting "}")
```
=> build: fix compile pass

build
=> build: Fix setting gopath

build, hack/scripts-dev/Makefile, hack/scripts-dev/docker-dns/insecure/Procfile, hack/scripts-dev/docker-dns/insecure/run.sh, test
Preliminary test work for https://github.com/coreos/etcd/issues/9353.
Also move GOPATH setup to build script. /cc @mkumatag
=> *: fix Makefile, move GOPATH setup to build script

CHANGELOG-3.1.md, CHANGELOG-3.2.md, CHANGELOG-3.3.md, CHANGELOG-3.4.md
=> CHANGELOG: add changes for next patch release

CHANGELOG-3.2.md, CHANGELOG-3.3.md, CHANGELOG-3.4.md
Add https://github.com/coreos/etcd/pull/9382 and https://github.com/coreos/etcd/pull/8302.
=> CHANGELOG: clean up, add auth/flag changes

etcdctl/README.md
Create doc for newly created auto-compact and defrag options in
check perf command.
=> etcdctl/doc: document check perf auto-compact and defrag options

clientv3/logger.go, etcdctl/ctlv3/command/snapshot_command.go, pkg/logutil/discard_logger.go, pkg/logutil/doc.go, pkg/logutil/logger.go, pkg/logutil/logger_test.go, pkg/logutil/merge_logger.go, pkg/logutil/merge_logger_test.go, pkg/logutil/package_logger.go, pkg/logutil/package_logger_test.go, snapshot/v3_snapshot.go, snapshot/v3_snapshot_test.go
Just merge "pkg/logger" with "pkg/logutil".
=> *: replace "pkg/logger" with "pkg/logutil"

e2e/v3_curl_test.go, etcdserver/api/v3election/election.go
Cherry pick of #9379 on release-3.2.
#9379: api/v3election: error on missing "leader" field
=> Automated cherry pick of #9379

Documentation/learning/api_guarantees.md
Signed-off-by: Hui Kang <kangh@us.ibm.com>
=> Documentation: make the API guarantee example explicit 

Documentation/op-guide/runtime-reconf-design.md
Fix typos and add articles to improve the experience of people reading the docs.
=> runtime-reconf-design.md: improve documentation

Dockerfile-release.ppc64le
=> Change baseimage for ppc64le dockerfile

CHANGELOG-3.2.md, Documentation/upgrades/upgrade_3_2.md
Fix https://github.com/coreos/etcd/issues/9425.
Please check out our upgrade guides and changelogs.
We will start documenting all possible breaking changes in those docs.
/cc @shyamjvs @jpbetz
=> *: document v3.2 default snapshot-count value change

CHANGELOG-3.4.md, CHANGELOG-4.0.md
Fix https://github.com/coreos/etcd/issues/9413.
=> *: document deprecate policy in CHANGELOG-4.0

clientv3/client.go
=> clientv3: optimize func NewFromURL

Documentation/dev-guide/api_reference_v3.md, Documentation/dev-guide/apispec/swagger/rpc.swagger.json, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto
Explain where the computation happens (e.g. "Hash" for all buckets
and "HashKV" for "key" bucket).
=> etcdserverpb: document "Hash" and "HashKV" more clearly

tools/functional-tester/tester/cluster_tester.go, tools/functional-tester/tester/stress.go, tools/functional-tester/tester/stress_composite.go, tools/functional-tester/tester/stress_key.go, tools/functional-tester/tester/stress_lease.go, tools/functional-tester/tester/stress_runner.go
If there's no failure injected, there should be no error from key stresser.
=> functional-tester: expect no client error in liveness mode

Gopkg.lock, vendor/github.com/google/btree/btree.go
Cherry-pick https://github.com/coreos/etcd/pull/9573 to rebase from master.
=> vendor: upgrade "google/btree"

.travis.yml, test
Maximize our Travis 5-worker usage.
Address https://github.com/coreos/etcd/issues/8862.
=> *: parallelize integration tests with CPU parameters

etcdmain/help.go
closes https://github.com/coreos/etcd/issues/9617
=> etcdmain: document peer-cert-allowed-cn flag

hack/kubernetes-deploy/etcd.yml
=> kubernetes-deploy: set etcd pod restartPolicy=Always

CHANGELOG-3.0.md, CHANGELOG-3.1.md, CHANGELOG-3.2.md, CHANGELOG-3.3.md, CHANGELOG-3.4.md, CHANGELOG-3.5.md, CHANGELOG-4.0.md, Documentation/upgrades/upgrade_3_2.md, Documentation/upgrades/upgrade_3_3.md, Documentation/upgrades/upgrade_3_4.md, Documentation/upgrades/upgrade_3_5.md, embed/config.go, pkg/logutil/zap_journald.go
=> *: improve documentation around logger change

CHANGELOG-3.4.md
Update CHANGELOG-3.4 for #9628
=> CHANGELOG: update from #9628

README.md
Use vectorized image instead of rasterized image for a sharper look.
cc/ @robszumski @gyuho
=> readme: use svg format for logo

auth/simple_token.go, auth/store.go, etcdctl/ctlv3/command/printer_simple.go, etcdctl/ctlv3/command/user_command.go, lease/leasehttp/http_test.go
=> *: remove "strings.Compare == 0"

auth/store.go, etcdctl/ctlv3/command/check.go, etcdserver/api/v2http/metrics.go, etcdserver/api/v2v3/store.go, etcdserver/corrupt.go, etcdserver/server.go, functional/runner/global.go, lease/lessor.go, mvcc/backend/backend.go, mvcc/kvstore_txn.go, pkg/flags/unique_strings.go, pkg/report/timeseries.go, rafthttp/msgappv2_codec.go, rafthttp/peer.go, rafthttp/remote.go, test, tests/Dockerfile, wal/repair.go
https://github.com/mdempsky/unconvert
=> test: integrate github.com/mdempsky/unconvert

etcdserver/server.go
Help debug issues like https://github.com/coreos/etcd/issues/9670.
=> etcdserver: clarify server membership change logging

etcdserver/backend.go, raftsnap/db.go
Address https://github.com/coreos/etcd/issues/9463.
=> *: clarify missing snapshot file error message/warning

pkg/fileutil/lock_linux.go, wal/wal.go
To help debug https://github.com/coreos/etcd/issues/9670.
=> wal,fileutil: add more logs, clarify error messages

etcdserver/server.go
etcdserver: purge old snap.db files
Lots of garbage db files in #7957. Should purge.
=> Cherry-picking PR 7967 to release-3.1

etcdserver/raft.go
ref https://github.com/coreos/etcd/issues/9438.
=> etcdserver: set default Raft logger with zap.Logger

Documentation/op-guide/authentication.md
=> Documentation: Add etcd version support notes for Using TLS common name in RBAC and notes about inter-peer CN filtering

CHANGELOG-3.1.md, CHANGELOG-3.2.md
=> CHANGELOG: Updates dates for 3.1.16 and 3.2.21 releases

Documentation/integrations.md
Add c# client supporting v3+ and grpc.
=> Documentation: Add v3 grpc C# client to libraries

etcdserver/apply.go, etcdserver/apply_v2.go, etcdserver/etcdserverpb/raft_internal_stringer.go, etcdserver/server.go, etcdserver/util.go, etcdserver/v2_server.go, etcdserver/v3_server.go
=> etcdserver: Automated cherry pick of detailed "took too long" warnings to release-3.1

tests/semaphore.test.bash
ref. https://github.com/coreos/etcd/issues/8862
=> tests: run proxy tests in Semaphore

tests/e2e/v3_cipher_suite_test.go, tests/e2e/v3_curl_test.go, tests/semaphore.test.bash
Trying to use another spare worker in Semaphore CI.
ref. https://github.com/coreos/etcd/issues/8862 and https://github.com/coreos/etcd/issues/9153.
=> tests: run coverage tests in Semaphore

etcdserver/metrics.go
Cherry pick of #8960 on release-3.2.
#8960: metrics: Add server_version metric
=> Automated cherry pick of #8960

CHANGELOG-3.2.md
Update CHANGELOG-3.4 for #9845
=> CHANGELOG: update from #9845

CHANGELOG-3.1.md
Update CHANGELOG-3.1 for #9848
=> CHANGELOG-3.1: update from #9848

raft/logger.go
Fix https://github.com/coreos/etcd/issues/9850.
=> raft: fix logger variadic parameter

etcdserver/quota.go
```
./bin/etcd --logger zap --log-outputs stderr
```
Before
```
{"level":"info","ts":1529090871.035875,"caller":"etcdserver/quota.go:84","msg":"enabled backend quota with default value","quota-name":"v3-applier","quota-size-bytes":2147483648,"quota-size":"2.1 GB"}
{"level":"info","ts":1529090871.037118,"caller":"etcdserver/quota.go:84","msg":"enabled backend quota with default value","quota-name":"kv","quota-size-bytes":2147483648,"quota-size":"2.1 GB"}
{"level":"info","ts":1529090871.0371432,"caller":"etcdserver/quota.go:84","msg":"enabled backend quota with default value","quota-name":"lease","quota-size-bytes":2147483648,"quota-size":"2.1 GB"}
{"level":"info","ts":1529090871.732761,"caller":"etcdserver/quota.go:84","msg":"enabled backend quota with default …
```
=> etcdserver: log quota only once

tools/etcd-dump-logs/README.md
etcd-dump-logs: minor change in README.md
Change "etcd-dump-logs inspects etcd db files." to "etcd-dump-logs dumps the log from data directory."
=> etcd-dump-logs: minor change in README.md

tools/etcd-dump-logs/README.md
etcd-dump-logs: minor editting in README.md
=> etcd-dump-logs: minor editting in README.md

docs/client-architecture.rst, docs/faq.rst, docs/index.rst
Copied from https://github.com/coreos/etcd/blob/master/Documentation/faq.md.
=> docs: add "FAQs"

Documentation/integrations.md
=> Documentation/integrations: add PHP v3 client

tools/benchmark/README.md
benchmark: Create benchmark.md with installation information
When trying to get the benchmark running I had difficulty figuring out how to run it. This should help anyone in a similar circumstance.
=> benchmark: Create README.md

functional/scripts/genproto.sh, scripts/genproto.sh
https://github.com/google/protobuf/releases/tag/v3.6.0
=> *: require protoc 3.6.0

Documentation/etcd-mixin/README.md
=> Documentation/etcd-mixin: fix typo in README.md

CHANGELOG-3.2.md
CHANGELOG-3.2: update from #9942
=> CHANGELOG-3.2: update from #9942

etcdserver/metrics.go, etcdserver/server.go
=> etcdserver: support zap.Logger in FD monitoring routine

docs/README.md, docs/index.rst, docs/operate.rst, docs/set-up.rst
=> docs: add initial operate guide structure

Documentation/v2/admin_guide.md
this doc is inconsistent between --force-new-cluster and
-force-new-cluster. Use the latter as it is the preferred option in
etcd.
=> Documentation: v2: add -- for force new cluster

Documentation/integrations.md
=> Document: add lucas to integrations.md

raft/raft_paper_test.go
=> raft: fix typo in test

Documentation/production-users.md
=> Documentation: add Transwarp to production user

clientv3/doc.go
Fix code example in clientv3/doc
=> clientv3/doc: Fix code example

client/README.md, clientv3/README.md
- update client docs to `go.etcd.io`
=> client,clientv3: update client docs to "go.etcd.io"

docs/faq.rst
As a native English speaker this is my best guess at what was meant in the original document.
=> Use IPA notation for pronunciation of etcd

contrib/recipes/watch.go
=> contrib/recipes/watch.go : cancel() the watch after desired watch event

contrib/systemd/etcd.service, functional.yaml, functional/Dockerfile, scripts/build-binary, scripts/build-docker, scripts/release, test
=> *: path changes for moving to github/etcd-io/etcd

integration/cluster.go
This PR will change all integration test helpers from:
```go
func HelperFoo(t *testing.T)
```
to
```go
func HelperFoo(t testing.TB)
```
`testing.TB` Is the interface which defines all functions that `testing.T` & `testing.B` have in common.
Using `testing.TB` will enable the usage of all integration test helpers to be used in tests(use `testing.T`) & benchmarks(use `besting.B`).
`testing.TB`:
```go
// TB is the interface common to T and B.
type TB interface {
Error(args ...interface{})
Errorf(format string, args ...interface{})
Fail()
FailNow()
Failed() bool
Fatal(args ...interface{})
Fatalf(format string, args ...interface{})
Log(args ...interface{})
Logf(format string, args ...interface{})
Name() string
Skip(args ...interface{})
SkipNow()
Skipf(format string, args ...interface{}) …
```
=> Use testing.TB for integration test helpers to enable usage in benchmarks

Documentation/integrations.md
A number of projects using etcd were missing. Add.
=> Documentation: add new projects

Documentation/op-guide/monitoring.md
Close https://github.com/etcd-io/etcd/issues/10073.
/cc @philips
=> Documentation/op-guide: remove "dash.etcd.io"

Documentation/metrics.md
Typo fix: particlarly -> particularly
=> Documentation/metrics.md: Fix a typo

Documentation/dev-guide/experimental_apis.md, Documentation/dev-guide/grpc_naming.md, Documentation/dev-internal/release.md, Documentation/dl_build.md, Documentation/docs.md, Documentation/integrations.md, Documentation/learning/why.md
=> Documentation/*: change github url, import path from coreos to etcd-io

clientv3/concurrency/election.go
=> clientv3/concurrency: Document Election API context parameter

etcdserver/server.go
Removed duplicated imports of package 'context' in server.go
=> etcdserver: remove duplicated imports

Documentation/integrations.md
=> add erlang client for etcd API v3

etcdctl/ctlv3/command/snapshot_command.go
Cherry pick of #10109 to release-3.3.
Add snapshot file integrity verification when querying snapshot status. If the snapshot file is corrupted, querying exits with error.
/cc @gyuho @xiang90 @jpbetz
=> etcdctl: cherry pick of #10109 to release-3.3

CHANGELOG-3.3.md
CHANGELOG-3.3: update from #10109.
=> CHANGELOG-3.3: update from #10109

CHANGELOG-3.2.md
CHANGELOG-3.2: update from #10109.
=> CHANGELOG-3.2: update from #10109

CHANGELOG-3.1.md
CHANGELOG-3.1: update from #10109.
=> CHANGELOG-3.1: update from #10109

.travis.yml, Makefile
Just pushed the test image with Go 1.11.1.
=> *: use Go 1.11.1 for testing

CHANGELOG-3.1.md, CHANGELOG-3.2.md, CHANGELOG-3.3.md, CHANGELOG-3.4.md
Update CHANGELOG 3.1, 3.2, 3.3 and 3.4 from #10153.
/cc @gyuho
=> CHANGELOG: update from #10153

Documentation/dev-internal/release.md
=> Update patch release list to reflect that 3.1 is maintained

Documentation/op-guide/configuration.md
Noticed this was missing when answering https://github.com/etcd-io/etcd/issues/10143
=> Document unix and unixs URL schemes

clientv3/lease.go
Per https://github.com/etcd-io/etcd/issues/10170, attempt to clarify the KeepAlive function documentation based on my understanding of the current implementation.
=> clientv3: Clarify lessor KeepAlive docs

raft/raft_test.go
/assign @xiang90 @jpbetz @wenjiaswe @jingyih
=> raft: fix godoc in tests

pkg/ioutil/pagewriter_test.go
the error info is:
got -4 bytes pending, expected less than 128 bytes
=> pkg/ioutil: n is equal or greater than cw.writeBytes

clientv3/balancer/grpc1.7-health_test.go, clientv3/doc.go, clientv3/lease.go, clientv3/watch.go, embed/config.go, embed/etcd.go, etcdctl/ctlv2/command/member_commands.go, etcdctl/ctlv3/command/global.go, etcdserver/api/membership/cluster.go, etcdserver/config.go, functional/tester/case_network_delay.go, functional/tester/cluster.go, integration/cluster_test.go, integration/v3_election_test.go, integration/v3_grpc_inflight_test.go, integration/v3_lease_test.go, pkg/proxy/server.go, raft/raft_test.go, tools/etcd-dump-db/backend.go
Fix github links replaced in #10044
=> Fix github links

clientv3/client.go
Just fixing a minor mistake that I stumbled upon
=> Fix spelling in comment

proxy/tcpproxy/userspace_test.go
Add a test to cover different priority cases.
=> tcpproxy: add a test.

Documentation/op-guide/configuration.md
add ENV variable: ETCD_CIPHER_SUITES description
Fixes #10277
=> Documentation: add ENV variable ETCD_CIPHER_SUITES description

CHANGELOG-3.4.md
=> CHANGELOG-3.4: update from #10301

.travis.yml, Makefile, auth/store_test.go, embed/serve.go, test
Ref https://github.com/etcd-io/etcd/issues/10328
/cc @hexfusion @jpbetz @xiang90
=> *: update Go versions

proxy/grpcproxy/cache/store.go
Cherry-pick https://github.com/etcd-io/etcd/commit/d88f686a91a57e46db742e2340c18212a1f38ab4
=> [Cherry-pick 3.2] grpcproxy: fix memory leak

client/keys.generated.go
Fixes #10325 
/cc @yeyongyong  @maps
=> client: update generated ugorji codec, manual remove "yynn2=0"

embed/config_test.go
The test case in TestAutoCompactionModeParse are  simple, 
so add some test cases and increase coverage.
https://github.com/etcd-io/etcd/blob/400b568fd63e8b84758b9c64ca36c85cd6cf7320/embed/config_test.go#L169-L177
=> embed: add test cases in TestAutoCompactionModeParse.

build, test
shellcheck 0.6.0 updates for SC2236
ref: https://github.com/koalaman/shellcheck/wiki/SC2236
=> *: Use -n instead of ! -z. [SC2236]

etcdctl/ctlv3/command/auth_command.go, etcdctl/ctlv3/command/check.go, etcdctl/ctlv3/command/compaction_command.go, etcdctl/ctlv3/command/del_command.go, etcdctl/ctlv3/command/elect_command.go, etcdctl/ctlv3/command/get_command.go, etcdctl/ctlv3/command/lease_command.go, etcdctl/ctlv3/command/lock_command.go, etcdctl/ctlv3/command/make_mirror_command.go, etcdctl/ctlv3/command/put_command.go, etcdctl/ctlv3/command/role_command.go, etcdctl/ctlv3/command/txn_command.go, etcdctl/ctlv3/command/user_command.go, etcdserver/api/v2http/client.go, etcdserver/api/v2http/client_test.go, tests/e2e/ctl_v3_user_test.go
Incremental staticcheck cleanup
ref: https://staticcheck.io/docs/checks#ST1005
=> *: error strings should not end with punctuation or a newline (ST1005)

etcdserver/raft_test.go, etcdserver/server_test.go
=> etcdserver: add a test to verify number of MsgAppResp sent is correct.

auth/store.go
=> [Cherry-pick 3.3] auth: fix cherry-pick

CHANGELOG-3.2.md, CHANGELOG-3.3.md
=> CHANGELOG: bump version and release date

embed/config_logging.go, etcdmain/config.go
Some small fixes in the area of config and logging - avoid abrupt panic or exit given invalid CLI options, tiny typo fix, and remove duplicated code
=> Config logging fixes

OWNERS
=> OWNERS: add hexfusion as approver and remove joelegasse

test
Fixes: https://github.com/etcd-io/etcd/issues/10455
=> Add shadow tool

auth/simple_token.go
1. "randum" to "random" in line 17.
2. "alredy" to "already" in line 137.
=> Fix plog.Panicf error message

docs/requirements.txt
Address https://github.com/etcd-io/etcd/network/alert/docs/requirements.txt/pyyaml/open
/cc @xiang90 @jpbetz @hexfusion
=>  docs: update PyYAML to 4.2b1

embed/etcd.go
Modify the comments to be more precise.
=> embed: Modify the comments to be more precise.

clientv3/integration/cluster_test.go
TestMemberAddWithExistingURLs ensures adding a new member with URLs already being used in the cluster will not succeed.
=> clientv3/integration: Add TestMemberAddWithExistingURLs

clientv3/naming/doc.go
doc: fix document example error
=> doc: fix document example error

raft/node.go
more precise that rename res to err
=> raft: more precise that rename res to err.

etcdserver/raft.go
@xiang90 @jpbetz @hexfusion @jingyih
=> etcdserver: improve heartbeat send failures logging

raft/README.md, raft/doc.go, raft/raft_paper_test.go
=> raft: update raft paper link (previous link deprecated)

Documentation/etcd-mixin/mixin.libsonnet, Documentation/op-guide/grafana.json
A small change to add automatic refresh in grafana dashboard. This should provide better user experience when viewing etcd dashboard.
/cc: @brancz
=> Doc/etcd-mixin: provide better user experience for monitoring etcd

etcdserver/server.go
=> etcdserver: fix typo in log message

README.md
=> readme: add etcd Emeritus section

MAINTAINERS, README.md
@heyitsanthony 
Thanks for your awesome work on etcd!
=> *: Move Anthony to Emeritus Maintainers

go.mod, scripts/updatedep.sh
Address https://github.com/etcd-io/etcd/pull/10773.
=> module: require 1.12, remove "v3" import paths

etcdctl/ctlv3/command/ep_command.go, etcdctl/ctlv3/command/printer.go, etcdctl/ctlv3/command/printer_fields.go, etcdctl/ctlv3/command/printer_json.go, etcdctl/ctlv3/command/printer_simple.go, etcdctl/ctlv3/command/printer_table.go
=> ctlv3: cherry pick of #9540 to release 3.1

etcdctl/ctlv3/command/ep_command.go, etcdctl/ctlv3/command/printer.go, etcdctl/ctlv3/command/printer_fields.go, etcdctl/ctlv3/command/printer_json.go, etcdctl/ctlv3/command/printer_simple.go, etcdctl/ctlv3/command/printer_table.go
=> ctlv3: cherry pick of #9540 to release 3.2

CHANGELOG-3.1.md, CHANGELOG-3.2.md, CHANGELOG-3.3.md
Update CHANGELOG from #10782, #10783, #10784.
cc @gyuho @xiang90
=> CHANGELOG: update from cherry picks of #9540

CHANGELOG-3.4.md
=> CHANGELOG: add learner metrics

Documentation/dev-guide/interacting_v3.md
=> DOC: Fix referencing the wrong version number.

raft/raft.go
=> raft: update log info and annotation

rafthttp/transport.go
(cherry picked from commit b1812a410fbca6fb77bf95b496408c7b75d0a370)
=> Raft HTTP: fix pause/resume race condition

.travis.yml, Makefile
=> *: test with Go 1.12.7

raft/node.go, raft/node_bench_test.go, raft/node_test.go
To help debug https://github.com/etcd-io/etcd/issues/9939.
@tbg @xiang90 @jingyih @manishrjain
=> raft: improve logging around tick miss

README.md
=> README: require Go 1.12+

.github/SECURITY.md, security/README.md, security/email-templates.md, security/security-release-process.md
Create security disclosure and release process, and team to handle issues.
Related # 
https://github.com/etcd-io/maintainers/issues/1
https://github.com/etcd-io/maintainers/issues/9
=> Security: Create etcd security process

functional/README.md
=> functional test: Update functional README.md

functional/README.md
Cherry pick of #10985 on release-3.4.
#10985: functional test: Update functional README.md
=> Automated cherry pick of #10985

README.md
Now that we have security disclosure and release process in place,
update the related reference.
=> README: update security reference

functional/README.md
=> functional: Update functional test README.md

tools/etcd-dump-logs/main.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> etcd-dump-logs: correct logging message word

raft/raft.go
=> raft: fix typo

tools/benchmark/cmd/put.go
=> cleanup: correct summary message in put.go

scripts/release
Seems like there are lots of `yq` CLIs. Use https://github.com/mikefarah/yq.
=> scripts/release: update "yq" command

clientv3/client.go
If overwritten, the previous context should be canceled first.
Replace https://github.com/etcd-io/etcd/pull/10813.
=> clientv3: use Endpoints(), fix context creation

CHANGELOG-3.4.md
=> CHANGELOG-3.4: update from 10523

CHANGELOG-3.4.md, Documentation/upgrades/upgrade_3_4.md
=> *: highlight "--enable-v2=false"

functional/tester/stresser_lease.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> cleanup: fix typos in doc/comment

lease/lessor.go
Signed-off-by: Guangming Wang <guangming.wang@daocloud.io>
=> lease: cleanup typo words in lessor.go

CHANGELOG-3.3.md
Update CHANGELOG-3.3 from #11056.
=> CHANGELOG-3.3: update from #11056

clientv3/integration/kv_test.go
Cherry pick of #11069 on release-3.4.
#11069: integration: fix TestKVPutError
=> Automated cherry pick of #11069 on release-3.4

raft/log_unstable.go
write compact if statements, rather than making code lengthy,
functionality is not changed.
Thank you.
=> raft : write compact if statements

CHANGELOG-3.4.md
=> CHANGELOG-3.4: add sha256sum

scripts/release
Cherry pick of #11087 on release-3.4.
#11087: scripts/release: add sha256sum summary of release assets
=> Automated cherry pick of #11087 on release 3.4

Documentation/faq.md
=> Documentation:fix clerical error

scripts/release
I run https://github.com/koalaman/shellcheck/ over scripts/* and fixed
the findings it returned.
=> scripts/release: Apply shellcheck findings

embed/serve.go
Fix https://github.com/etcd-io/etcd/issues/11107.
/cc @jingyih
=> embed: fix secure server logging message

mvcc/kvstore.go, mvcc/metrics.go
Cherry pick of #11126 on release-3.4.
#11126: mvcc: add store revision metrics
=> Automated cherry pick of #11126 on release-3.4

mvcc/kvstore.go, mvcc/metrics.go
Cherry pick of #11126 on release-3.3.
#11126: mvcc: add store revision metrics
=> Automated cherry pick of #11126 on release-3.3

mvcc/kvstore.go, mvcc/metrics.go
Cherry pick of #11126 on release-3.2.
#11126: mvcc: add store revision metrics
=> Automated cherry pick of #11126 on release-3.2

CHANGELOG-3.4.md, CHANGELOG-3.5.md
=> CHANGELOG: update 3.4.1 and 3.5

clientv3/example_kv_test.go
=> clientv3: remove the redundant CancelFunc invocation

CONTRIBUTING.md
=> *: add slack contact

README.md
Added link and removed wrongly copied text
=> README: fix formatting on hangouts link

etcdctl/ctlv3/command/member_command.go
Cherry pick of #11194 on release-3.3.
#11194: etcdctl: fix member add command
=> Automated cherry pick of #11194 on release-3.3

.words, clientv3/balancer/resolver/endpoint/endpoint.go, clientv3/client.go, clientv3/credentials/credentials.go
Cherry pick of #11184 on release-3.4.
#11184: clientv3: Set authority used in cert checks to host of
=> Automated cherry pick of #11184

CHANGELOG-3.2.md, CHANGELOG-3.3.md
=> changelog: for the skip client san verification option.

clientv3/snapshot/v3_snapshot.go, etcdserver/apply.go, etcdserver/apply_auth.go, etcdserver/corrupt.go, etcdserver/server.go, etcdserver/util.go, etcdserver/v3_server.go, integration/v3_alarm_test.go, mvcc/kv.go, mvcc/kv_test.go, mvcc/kv_view.go, mvcc/kvstore.go, mvcc/kvstore_bench_test.go, mvcc/kvstore_compaction_test.go, mvcc/kvstore_test.go, mvcc/kvstore_txn.go, mvcc/watchable_store.go, mvcc/watchable_store_bench_test.go, mvcc/watchable_store_test.go, mvcc/watchable_store_txn.go, pkg/traceutil/trace.go, pkg/traceutil/trace_test.go, tools/benchmark/cmd/mvcc-put.go
Cherry pick of #11179 on release-3.4.
#11179: pkg: create package traceutil for tracing. mvcc: add
=> Automated cherry pick of #11179

go.mod, go.sum
Related to https://github.com/sirupsen/logrus/issues/1035
=> go.mod: Bump Logrus and x/crypto

scripts/release
Cherry pick of #11234 on release-3.4.
#11234: scripts: fix read failure prompt in release; use https for
=> Automated cherry pick of #11234

scripts/release
=> scripts: use https for git clone.

scripts/build-binary
=> scripts: avoid release builds on darwin machine.

etcdserver/api/membership/cluster.go
=> etcdserver: unset old cluster version in metrics

CHANGELOG-3.4.md, CHANGELOG-3.5.md
Update changelog from #11254. Suggestions on wording are welcomed:)
=> CHANGELOG: update from PR 11254

Documentation/op-guide/configuration.md, embed/config.go, embed/etcd.go, etcdmain/config.go, etcdmain/help.go
fixes issue #https://github.com/etcd-io/etcd/issues/11258
I think a changelog is necessary to tell user how to operate maybe in CHANGELOG-3.5 and CHANGELOG-3.4? @jingyih @gyuho  WDYT
=> *: promote the boltdb-freelistType from experimental to official

CHANGELOG-3.2.md
Add changelog for etcd_cluster_version metrics from ##11271
=> Update CHANGELOG-3.2 for #11271

CHANGELOG-3.3.md
Add log for etcd_cluster_version metrics addition in #11261
=> Update CHANGELOG-3.3 for 11261

Documentation/learning/why.md, README.md
Update the adopters file path.
=> doc: update file ref path

scripts/release
Cherry pick of #11247 on release-3.3.
#11247: Add version, tag and branch checks to release script
=> Automated cherry pick of #11247

tests/e2e/ctl_v3_test.go
=> e2e: add cluster version test

etcdserver/api/rafthttp/stream_test.go
For https://github.com/etcd-io/etcd/pull/11274#discussion_r336303134
=> rafthttp: add test stream support for current version.

scripts/release
=> scripts/release: list GPG key only when tagging is needed

etcdserver/server.go, pkg/fileutil/purge.go, pkg/fileutil/purge_test.go
Cherry pick of #11308 on release-3.2.
#11308: etcdserver: wait purge file loop during shutdown
=> Automated cherry pick of #11308 on release-3.2

etcdserver/server.go, pkg/fileutil/purge.go, pkg/fileutil/purge_test.go
Cherry pick of #11308 on release-3.3.
#11308: etcdserver: wait purge file loop during shutdown
=> Automated cherry pick of #11308 on release-3.3

etcdserver/server.go, pkg/fileutil/purge.go, pkg/fileutil/purge_test.go
Cherry pick of #11308 on release-3.4.
#11308: etcdserver: wait purge file loop during shutdown
=> Automated cherry pick of #11308 on release-3.4

CHANGELOG-3.2.md
=> CHANGELOG: bump release 3.2.28

CHANGELOG-3.2.md, CHANGELOG-3.3.md, CHANGELOG-3.4.md
Update changelog from PR #11308.
=> CHANGELOG: update for #11308

raft/README.md
docs: Update the raft usage by adding Hyperledger project
=> docs: Update the raft usage by adding Hyperledger project

mvcc/metrics.go, mvcc/metrics_txn.go
Cherry pick of #11374 on release-3.3.
#11374: mvcc: add "etcd_mvcc_put_size_in_bytes" to monitor the
=> Automated cherry pick of #11374 on release 3.3

mvcc/metrics.go, mvcc/metrics_txn.go
Cherry pick of #11374 on release-3.4.
#11374: mvcc: add "etcd_mvcc_put_size_in_bytes" to monitor the
=> Automated cherry pick of #11374 on release 3.4

CHANGELOG-3.3.md, CHANGELOG-3.4.md, CHANGELOG-3.5.md
=> CHANGELOG: update from PR #11374

CHANGELOG-3.4.md
=> CHANGELOG: update from PR 11403

auth/store.go
=> auth: fix user.Options nil pointer

auth/store.go
=> Automated cherry pick of #11413 to release-3.4

mvcc/kvstore.go
=> go style error check

integration/cluster.go
kubernetes unit tests may occasionally get the following error, after some analysis and testing we find that it is related to etcd exit mechanism.
tests like: 
staging/src/k8s.io/client-go/rest/request_test.go
1803:func TestWatch(t *testing.T) {
staging/src/k8s.io/cli-runtime/pkg/resource/builder_test.go
1500:func TestWatch(t *testing.T) {
========================================================
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x15afb1a]
goroutine 908 [running]:
k8s.io/kubernetes/vendor/github.com/coreos/bbolt.(*Tx).Bucket(...)
/home/t4/chorus/f9f659c/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/github.com/coreos/bbolt/tx.go:101 …
=> integration: gracefully shut down gRPC server

auth/store.go, tests/e2e/v3_curl_test.go
cherrypick of #11418 to release3.4
=> Automated cherry pick of #11418 to release 3.4

Documentation/metrics/v3.4.0, Documentation/metrics/v3.4.1, Documentation/metrics/v3.4.2, Documentation/metrics/v3.4.3
Signed-off-by: Gabi Davar <gabi.davar@arm.com>
=> Documentation: added v3.4 metrics docs

raft/raft.go, raft/raft_test.go
Signed-off-by: qupeng <qupeng@pingcap.com>
Close https://github.com/etcd-io/etcd/issues/11326.
I'm not sure where to add test case for this, in raft_test.go or testdata?
=> raft: abort leader transferring if the target is demoted

pkg/adt/interval_tree.go
=> pkg/adt: rbcolor string fix

CHANGELOG-3.2.md, CHANGELOG-3.3.md, CHANGELOG-3.4.md, CHANGELOG-3.5.md, CHANGELOG-4.0.md
=> CHANGELOG: update recommended versions

CHANGELOG-3.5.md
=> Changelog-3.5: update changelog for grpc upgrade

mvcc/backend/backend.go
Incomplete fix #11502 when warning logging.
=> mvcc: incomplete fix in #11502

clientv3/integration/kv_test.go, clientv3/integration/lease_test.go
=> clientv3/integration: fix tests

clientv3/integration/leasing_test.go
=> clientv3/integration: fix typo in "TestLeasingRevGet"

Documentation/dl_build.md
changelog and readme are already updated.
=> doc: update required go version for master

auth/jwt.go
Cherry pick of #11586 on release-3.4.
#11586: auth: correct logging level
=> Automated cherry pick of #11586 on release 3.4

embed/config.go, embed/etcd.go, embed/serve.go
Remove dependency of `capnslog` in `embed` pkg. Also remove nil checks for logger as they are no longer necessary.
=> embed: remove capnslog

wal/file_pipeline.go, wal/repair.go, wal/util.go, wal/wal.go
Remove dependency of `capnslog` in wal pkg.
=> wal: remove capnslog

auth/jwt.go, auth/range_perm_cache.go, auth/simple_token.go, auth/store.go
Remove dependency of `capnslog` in auth pkg.
=> auth: remove capnslog

mvcc/backend/backend.go, mvcc/backend/batch_tx.go, mvcc/index.go, mvcc/key_index.go, mvcc/kvstore.go, mvcc/kvstore_compaction.go, mvcc/kvstore_txn.go, mvcc/watchable_store.go
Remove dependency of `capnslog` in mvcc pkg.
=> mvcc: remove capnslog

Documentation/rfc/v3api.md
This PR is going to fix #11591 .
=> doc: remove out-date introduction video link.

etcdmain/config.go, etcdmain/etcd.go, etcdmain/main.go, etcdmain/util.go
Remove dependency of `capnslog` in `etcdmain` pkg.
=> etcdmain: remove capnslog

raft/raft.go
Signed-off-by: qupeng <qupeng@pingcap.com>
Cleanup code about read index, extracted from #11505 .
=> raft: cleanup read index code

etcdctl/ctlv3/command/member_command.go
Cherry pick of #11638 on release-3.3.
#11638: etcdctl: fix member add command
=> Automated cherry pick of #11638 on release-3.3

etcdctl/ctlv3/command/member_command.go
Cherry pick of #11638 on release-3.4.
#11638: etcdctl: fix member add command
=> Automated cherry pick of #11638 on release-3.4

proxy/grpcproxy/metrics.go
Cherry pick of #11694 on release-3.4.
#11694: proxy/grpcproxy: add return on error for metrics handler
=> cherry pick of #11694 on release-3.4

proxy/grpcproxy/metrics.go
Cherry pick of #11694 on release-3.3.
#11694: proxy/grpcproxy: add return on error for metrics handler
=> cherry pick of #11694 on release-3.3

CHANGELOG-3.4.md
This fix is actually in 3.4.4, not 3.4.2.
cc @spzala
=> CHANGELOG-3.4: correction

CHANGELOG-3.3.md, CHANGELOG-3.4.md, CHANGELOG-3.5.md
=> CHANGELOG: bump to include #11694

etcdserver/api/etcdhttp/metrics.go
Small refactoring of
`go.etcd.io/etcd/etcdserver/api/etcdhttp/metrics.go.checkHealth`
function just to avoid annoying repeatings of `if h.Health == "true" {`
=> etcdserver/api/etcdhttp: checkHealth refactoring

etcdmain/main.go
To help find out bugs in "go-systemd"
=> etcdmain: log "SdNotify" error/success

etcdmain/gateway.go
=> etcdmain: fix typo

CHANGELOG-3.5.md
Update CHANGELOG-3.5 to include change of #11743
=> CHANGELOG: update from #11743

clientv3/concurrency/mutex.go
=> clientv3/concurrency: do not swallow error

.github/stale.yml
Adding the numbers of days in the info.
=> github: add stale issue close time

CHANGELOG-3.3.md, CHANGELOG-3.4.md, CHANGELOG-3.5.md
=> CHANGELOG: update for #11699,#11670,#11652,#11735,#11659

Documentation/op-guide/authentication.md
=> Documentation: note on password strength

wal/wal.go
closeAll() in wal.go should try to close all readers.
One of the closer error is returned.
The callers of closeAll() currently don't check the error return.
=> closeAll should attempt to close all ReadCloser's

wal/wal.go
In Create(), if fileutil.Fsync() encounters error, we should close the pdir
=> wal: close the directory when Fsync() encounters error

Documentation/etcd-mixin/mixin.libsonnet, Documentation/op-guide/etcd3_alert.rules.yml, Documentation/op-guide/grafana.json
Continuation of #9885 with comments addressed.
@xiang90 @gyuho @hexfusion
=> Use UID instead of ID in Grafana dashboard

.github/ISSUE_TEMPLATE.md
to make redirection possible. Changed undercore to dash.
=> .github/ISSUE_TEMPLATE: fix of a broken link

clientv3/snapshot/v3_snapshot.go
In v3Manager#Status, we should check error return from Write() calls.
=> Check the error return from Write in v3Manager#Status

etcdserver/api/rafthttp/http.go
Add a snapshot size limit const.
=> rafthttp: add snapshot limit const

CHANGELOG-3.3.md, CHANGELOG-3.4.md
update 3.4/3.3 changelog for 11817
=> CHANGELOG: update 3.4/3.3 changelog for 11817

mvcc/kvstore.go
Cherry pick of #11817  on release-3.4.
#11817 : mvcc: fix deadlock bug
=> Automated cherry pick of #11817 on release-3.4 

mvcc/backend/read_tx.go
In readTx#UnsafeRange, we potentially lock and unlock txMu twice:
* around calling rt.tx.Bucket()
* around calling bucket.Cursor()
this PR merges the consecutive lock/unlock pairs into one lock/unlock pair.
=> mvcc: Obtain tx Lock once in readTx#UnsafeRange

CHANGELOG-3.5.md
https://github.com/etcd-io/etcd/pull/11850
=> Update CHANGELOG for 11850

Dockerfile-release
fixes https://github.com/etcd-io/etcd/issues/11901
=> fix(Dockerfile-release): from image was missing image name

etcdserver/api/v2store/store.go
This PR adds error return check for store#internalCreate().
=> etcdserver: check error return for store#internalCreate

CHANGELOG-3.2.md, Documentation/upgrades/upgrade_3_3.md
=> CHANGELOG: update 3.2 changelog and 3.3 upgrade document for #11691

etcdserver/api/v2store/stats.go
Fixes #11981 
/cc @gyuho @jingyih @xiang90 @spzala
=> etcdserver/api/v2store: fix race in TestIssue2746WithThree

auth/store.go, auth/store_test.go, clientv3/integration/user_test.go
=> auth: return correct ErrUserEmpty without username 

etcdserver/etcdserverpb/raft_internal_stringer.go
=> Change protobuf field type from int to int64

Documentation/faq.md, Documentation/op-guide/hardware.md
=> Documentation: fix broken links

Documentation/op-guide/security.md
=> Documentation: note on data encryption

CHANGELOG-3.4.md, CHANGELOG-3.5.md, etcdmain/help.go
Also update helper message to include the new flag.
=> CHANGELOG: update for #11946

Documentation/op-guide/security.md
Cherry pick of #11830 on release-3.4.
#11830: Documentation: note on the policy of insecure by default
=> Automated cherry pick of #11830

Documentation/op-guide/authentication.md
Cherry pick of #11796 on release-3.4.
#11796: Documentation: note on password strength
=> Automated cherry pick of #11796

etcdmain/gateway.go
Cherry pick of #11845 on release-3.4.
#11845: etcdmain: best effort detection of self pointing in tcp proxy
=> Automated cherry pick of #11845

embed/config_test.go, embed/etcd.go
Cherry pick of #11787 on release-3.4.
#11787: embed: fix compaction runtime err
=> Automated cherry pick of #11787

CHANGELOG-3.5.md, Documentation/op-guide/configuration.md
CHANGELOG: update for https://github.com/etcd-io/etcd/pull/11980 , https://github.com/etcd-io/etcd/pull/11986 , https://github.com/etcd-io/etcd/pull/11987 .
=> CHANGELOG: update for PR #11980 ,  #11986 ,  # 11987 ,

etcdmain/etcd.go, pkg/fileutil/fileutil.go, pkg/fileutil/fileutil_test.go, pkg/transport/listener.go
Cherry pick of #11798 on release-3.4.
#11798: pkg: check file stats
=> Automated cherry pick of #11798

etcdmain/gateway.go
Cherry pick of #12066 on release-3.4.
#12066: etcdmain: fix shadow error
=> Automated cherry pick of #12066

Documentation/op-guide/gateway.md, etcdmain/gateway.go
Cherry pick of #12060 on release-3.3.
#12060: doc: add TLS related warnings
=> Automated cherry pick of #12060

etcdserver/metrics.go
Cherry pick of #11986 on release-3.4.
#11986: etcdserver:FDUsage set ticker to 10 minute from 5 seconds.
=> Automated cherry pick of #11986

pkg/fileutil/dir_unix.go, pkg/fileutil/dir_windows.go, pkg/fileutil/fileutil.go
Cherry pick of #11945 on release-3.3.
#11945: pkg: Fix dir permission check on Windows
=> Automated cherry pick of #11945

CHANGELOG-3.3.md, CHANGELOG-3.4.md
update for #12069  ,and other cherry pick PRs.
=> CHANGELOG-3.3-3.4: update for #12069

auth/simple_token.go, auth/simple_token_test.go, auth/store.go, auth/store_test.go, embed/config.go, embed/etcd.go, etcdmain/config.go, etcdmain/help.go, etcdserver/config.go, etcdserver/server.go
Cherry pick of #11980 on release-3.3.
#11980: auth: Customize simpleTokenTTL settings.
=> Automated cherry pick of #11980

etcdmain/etcd.go
Cherry pick of #12100 on release-3.4.
#12100: etcdmain: fix shadow error
=> Automated cherry pick of #12100

Documentation/op-guide/security.md
Cherry pick of #12012 on release-3.3.
#12012: Documentation: note on data encryption
=> Automated cherry pick of #12012

CHANGELOG-3.3.md, CHANGELOG-3.4.md
=> CHANGELOG: add breaking changes doc for v3.4.10/v3.3.23

clientv3/auth.go, embed/auth_test.go, etcdserver/api/v3client/v3client.go
This PR closes https://github.com/etcd-io/etcd/issues/12139.
=> v3client: implement clientv3.Auth interface

etcdserver/api/v3rpc/maintenance.go
Fix for: https://github.com/etcd-io/etcd/issues/12126
**Cause:**
`srv.Send` does not wait until the message is received by the client.
Therefore the buffer can not be safely reused between Send operations
**Fix:**
Allocate the buffer inside the loop of each Send operation.
**First seen:** before `v3.3`
**How tested:**
In a private branch added verbose logs with CRC checksum for each Blob on the server and the client and had a solid repro,
that shows the client receives identical Blobs matching the last one.
=> 12126: snapshot: corrupted in Embedded server

clientv3/watch.go
It seems excessive to log "about to send" and "failed to send" watch cancel requests at info level. Changing their logging level to debug instead.
xref: https://github.com/kubernetes/kubernetes/issues/93450
cc @jackkleeman @gyuho @liggitt
=> clientv3: remove excessive watch cancel logging

CHANGELOG-3.3.md
Update changelog 3.3 for #12215 
cc @jingyih @gyuho
=> CHANGELOG: update from 12215

Documentation/op-guide/security.md, pkg/fileutil/fileutil.go
Cherry pick of #12242 on release-3.3.
#12242: pkg: file stat warning
=> Automated cherry pick of #12242

CHANGELOG-3.4.md, CHANGELOG-3.5.md
CHANGELOG: update from #12288 and #12299
=> CHANGELOG: update from #12288 and #12299

mvcc/kvstore_test.go
=> mvcc: fix typo

lease/lease_queue.go, lease/lease_queue_test.go, lease/lessor.go
fix https://github.com/etcd-io/etcd/issues/12291
=> lease: fix lease expiry bases on wall clock

CHANGELOG-3.5.md
Follow up to PR: https://github.com/etcd-io/etcd/pull/12279
=> CHANGELOG: Update changelog about modules instead of ./vendor

raft/log.go
raft/log: remove redundant code logic
=> raft/log: remove redundant code logic

Documentation/etcd-mixin/test.yaml
Signed-off-by: Guus van Weelden <guus.vanweelden@moia.io>
=> the example alert file had a wrong indentation

clientv3/namespace/kv.go, clientv3/op.go, integration/v3_kv_test.go
namespace: check IsWithFromKey if keyLen equal 0.
fixes: #12282
=> namespace: check IsWithFromKey if keyLen equal 0.

clientv3/retry_interceptor.go
Cherry pick of #12264 on release-3.4.
#12264: clientv3: get AuthToken automatically when clientConn is
=> Automated cherry pick of #12264

server/etcdserver/api/membership/cluster.go
during cluster version update in etcd cluster, the log should info from
XX to XX.
=> etcdserver: updated cluster version

Documentation/metrics/v3.3.11, Documentation/metrics/v3.3.12, Documentation/metrics/v3.3.13, Documentation/metrics/v3.3.14, Documentation/metrics/v3.3.15, Documentation/metrics/v3.3.16, Documentation/metrics/v3.3.17, Documentation/metrics/v3.3.18, Documentation/metrics/v3.3.19, Documentation/metrics/v3.3.20, Documentation/metrics/v3.3.21, Documentation/metrics/v3.3.22, Documentation/metrics/v3.3.23, Documentation/metrics/v3.3.24, Documentation/metrics/v3.4.10, Documentation/metrics/v3.4.11, Documentation/metrics/v3.4.12, Documentation/metrics/v3.4.13, Documentation/metrics/v3.4.4, Documentation/metrics/v3.4.5, Documentation/metrics/v3.4.6, Documentation/metrics/v3.4.7, Documentation/metrics/v3.4.8, Documentation/metrics/v3.4.9
=> Documentation: add generated metrics docs

server/etcdserver/apply.go, server/etcdserver/apply_v2.go, server/etcdserver/metrics.go
Add metric tracking apply method duration:
* etcd_server_apply_duration_seconds
It can be used to understand which operations are slow, in addition to the warning log message.
=> Add etcd_server_apply_duration_seconds

Documentation/etcd-mixin/mixin.libsonnet
Resolving typo which has direct user exposure.
=> Documentation/etcd-mixin: fix typo

client/v3/README.md
=> docs: update client v3's README

client/v3/yaml/config_test.go, pkg/fileutil/fileutil_test.go
=> Cleanup tmpfiles

pkg/transport/listener.go, pkg/transport/listener_test.go
in pkg/transport, we should catch NewCert error.
=> transport: catch new cert error

etcdctl/READMEv2.md, server/etcdserver/api/membership/cluster.go, server/etcdserver/api/v2error/error.go
=> chore: update the documentation link in the comment

wal/wal.go, wal/wal_test.go
Manual cherry-pick of  #11807 (cherry picked as #12087 in 3.3)
=> wal: fix panic when decoder not set

client/v2/client.go
client: replace dial with dialContext
=> client: replace dial with dialContext 

contrib/README.md
del systemd/etcd2-back-coreos in docs
=> contrib: del systemd/etcd2-backup-coreos in docs

etcdserver/api/etcdhttp/metrics.go
ref. #12677
ref. https://github.com/etcd-io/etcd/commit/0b9cfa86772fa1ca9f4fc0a402ac6c73ffb599a0
=> [Backport-3.4] etcdserver/api/etcdhttp: log successful etcd server side health check in debug level

contrib/raftexample/raft.go
If there is a previous snapshot and a node crash after writing to WAL but before writing to snapshot file, the restarted node restores from previous snapshot and replays WAL from the index of new snapshot. This causes data inconsistency.
=> raftexample: Save snapshot file before writing to wal

raft/raft.go, raft/raft_test.go
=> raft: check `VotersOutgoing` for snapshot

contrib/raftexample/kvstore.go, contrib/raftexample/raft.go, contrib/raftexample/raftexample_test.go
I added these lines in [this PR](https://github.com/etcd-io/etcd/pull/11889) to wait for triggering snapshot until all committed entries are applied.
https://github.com/etcd-io/etcd/blob/b67ed4e4aa560734e2c041584e0e31fa488c038a/contrib/raftexample/raft.go#L354-L361
But this causes loading snapshot in kvstore and breaks data.
The kvstore have to know the end of Ready batch and notify all entries were applied to the raft node.
=> raftexample: Explicitly notify all committed entries are applied

contrib/raftexample/raft.go, contrib/raftexample/raftexample_test.go
The returned channel from publishEntries is always nil. I fixed this and added a unit test for this.
=> raftexample: Return an appropriate applyDoneC

etcd.conf.yml.sample
Replace the deprecated debug flag.
=> Update debugging flag in the sample config file

pkg/systemd/journal.go
=> systemd: Fix typo in DialJournal documentation

.github/ISSUE_TEMPLATE.md
Fix the report bug link in issue template.
=> Docs: fix the report bug link in issue template

.github/ISSUE_TEMPLATE.md
=> Github: Shorten the reporting-bugs link.

.github/ISSUE_TEMPLATE.md, CHANGELOG-3.0.md, CHANGELOG-3.1.md, CHANGELOG-3.2.md, CHANGELOG-3.3.md, CHANGELOG-3.4.md, CHANGELOG-3.5.md, CHANGELOG-4.0.md, CONTRIBUTING.md, Documentation/README.md, README.md, security/README.md
fixes: https://github.com/etcd-io/etcd/issues/12700
=> Updating links in .md files after removing Documentation.

client/v2/client.go, client/v3/client.go, client/v3/client_test.go, client/v3/ctx_test.go, client/v3/internal/endpoint/endpoint.go, client/v3/ordering/kv_test.go, client/v3/retry_interceptor.go, client/v3/txn_test.go, etcdctl/ctlv2/command/exec_watch_command.go, etcdctl/ctlv3/command/ep_command.go, etcdctl/ctlv3/command/printer_json.go, etcdctl/ctlv3/command/watch_command.go, pkg/fileutil/fileutil.go, pkg/transport/transport.go, raft/confchange/confchange.go, raft/quorum/datadriven_test.go, raft/quorum/quick_test.go, raft/rafttest/interaction_env_handler_log_level.go, raft/rafttest/interaction_env_handler_process_ready.go, raft/rafttest/node.go, raft/rawnode_test.go, raft/status.go, raft/tracker/tracker.go
Fixes to part of `staticcheck` complains as step to potentially incorporate static checker into regular testing procedure.
=> *: partial staticcheck fix

README.md
A.d. https://github.com/etcd-io/etcd/issues/12680
Thanks @wpedrak for pointing that out !
=> README: Update required go version.

.github/ISSUE_TEMPLATE/distributors-application.md, security/README.md, security/security-release-process.md
=> security: add private distributor list, and its application template

pkg/pbutil/pbutil_test.go
Cherry pick of #8469 on release-3.2.
#8469: pkg/pbutil: Fix go vet errors
=> Manual cherry pick of #8469

CHANGELOG-3.2.md
=> CHANGELOG: release 3.2

CHANGELOG-3.5.md, etcdctl/ctlv3/command/lock_command.go, tests/e2e/ctl_v3_lock_test.go
=> etcdctl: lock return exit code of exec-command

client/v3/naming/doc.go
=> client: fix doc typo

README.md
=> doc: fix branch management link

mvcc/kvstore_txn.go
backport PR #12894 to release-3.4
=> [Backport-3.4] etcdserver/mvcc: update trace.Step condition

etcdctl/ctlv3/command/check.go
If ctc+c is pressed during the run of etcdctl check perf, this deletes all the previously created keys that perf check created.
I also cleaned the context a bit for this to be possible, so that we can cancel all the contexts before deleting, otherwise during deletion the new keys would keep being created.
=> etcdctl/ctlv3: Cleanup keys on signal interrupt.

server/mvcc/backend/backend.go
Currently `Mlock` flag of bboltDB is dropped during defrag (or rather is not applied to new DB). This PR changes it. 
Related PRs:
- #12832 - analogous PR for `freelistType` and `initialMmapSize`
- #12904 - introduction of `Mlock` flag
=> server: reapply `Mlock` flag after defrag

server/etcdserver/api/membership/cluster.go
https://github.com/etcd-io/etcd/issues/12913
Part 5 of preparing to deprecate StoreV2
=> No-storeV2: Read membership information from the backend (Part5)

client/v3/naming/doc.go
The service parameter is not used in the doc demo.
=> fix doc demo bug

README.md
Ref https://github.com/etcd-io/etcd/issues/12921
=> readme: Switch Travis CI test results badge to GitHub actions

client/v3/watch.go
check resuming len to avoid panic
=> check resuming len to avoid panic

etcdctl/README.md
=> doc: fix output flag format

client/v3/client.go, client/v3/client_test.go, server/etcdserver/api/v3client/v3client.go
Ref https://github.com/etcd-io/etcd/issues/12326
Follow up from https://github.com/etcd-io/etcd/pull/12948
=> client: Add logger argument to NewCtxClient

CHANGELOG-3.5.md
=> Fix typo in CHANGELOG

scripts/build-docker, scripts/release
manual cherry-pick of #12997 into release-3.5
=> Manual cherry pick of #12997

server/etcdmain/config.go
Signed-off-by: Gábor Lipták gliptak@gmail.com
=> Correct typo

server/mvcc/kvstore_compaction.go
=> limit tx lock scope in store.scheduleCompaction

tools/rw-heatmaps/plot_data.py, tools/rw-heatmaps/rw-benchmark.sh
modified script to include test parameters inside the output csv file so that we can get more information out of the test.
=> tool: save test parameters in mixed read/write benchmark script.

tools/rw-heatmaps/plot_data.py
Found a small bug in the performance testing script.
=> tools: fix small rw-heatmaps python plot script argument parsing bug

server/etcdserver/apply.go, tests/e2e/v3_curl_test.go
Backport https://github.com/etcd-io/etcd/pull/13084.
=> [backport 3.5] etcdserver: don't activate alarm w/missing AlarmType

CHANGELOG-3.5.md
CHANGELOG: etcdserver: don't attempt to grant nil permission to a role
=> CHANGELOG: etcdserver: don't attempt to grant nil permission to a role

tools/rw-heatmaps/plot_data.py
bug fixing and updated format.
=> tools: rw-heatmaps output format bug fix

etcdutl/etcdutl/printer.go, etcdutl/snapshot/v3_snapshot.go, server/etcdserver/api/membership/confstate.go, server/etcdserver/api/v3rpc/maintenance.go, server/etcdserver/server.go, server/etcdserver/version/doc.go, server/etcdserver/version/version.go, server/etcdserver/version/version_test.go, server/mvcc/buckets/bucket.go, tests/e2e/ctl_v3_snapshot_test.go, tests/integration/clientv3/maintenance_test.go, tests/integration/clientv3/snapshot/v3_snapshot_test.go
Implements second and third part of the proposal in https://github.com/etcd-io/etcd/issues/13070
=> [Version in Snapshot] Preserve etcd version in backend allowing etcdutl to read it from snapshot

server/etcdserver/api/etcdhttp/metrics.go
=> fix health endpoint not usable when authentication is enabled

server/auth/store.go, server/etcdserver/api/membership/cluster.go, server/etcdserver/api/membership/store.go, server/mvcc/buckets/bucket.go, server/mvcc/kvstore.go, server/mvcc/kvstore_compaction.go, server/mvcc/kvstore_compaction_test.go, server/mvcc/kvstore_test.go
=> etcdserver: Move all named keys to buckets module

client/pkg/transport/listener_opts.go, client/pkg/transport/sockopt.go, client/pkg/transport/sockopt_unix.go, client/pkg/transport/sockopt_windows.go, client/v3/naming/endpoints/endpoints.go, client/v3/naming/endpoints/endpoints_impl.go, client/v3/naming/endpoints/internal/update.go, client/v3/naming/resolver/resolver.go, pkg/grpc_testing/stub_server.go, server/etcdserver/adapters.go, server/etcdserver/version/monitor.go, test.sh, tools/mod/go.mod, tools/mod/go.sum, tools/mod/tools.go
=> *: Add missing file licenses and Fix the static analysis to prevent skipping them

CHANGELOG-3.5.md
=> CHANGELOG-3.5: fix broken link

README.md
=> README: explain "MAINTAINERS"

server/auth/range_perm_cache.go, server/auth/store.go, server/mvcc/buckets/auth_roles.go, server/mvcc/buckets/auth_users.go
=> etcdserver: Move all get/put/delete on AuthUsers and AuthRoles to buckets module

server/auth/store.go, server/mvcc/buckets/auth.go, server/mvcc/buckets/auth_test.go
=> etcdserver: Move read/update methods on Auth bucket to one place

etcdutl/etcdutl/backup_command.go, etcdutl/snapshot/v3_snapshot.go, server/etcdserver/api/membership/cluster.go, server/etcdserver/api/membership/membership_test.go, server/etcdserver/api/membership/store.go, server/etcdserver/api/membership/storev2.go, server/etcdserver/server.go, server/etcdserver/server_test.go, server/mvcc/buckets/confstate.go, server/mvcc/buckets/confstate_test.go, server/mvcc/buckets/membership.go
=> etcdserver: Membership uses MembershipStorage interface instead of directly accessing Backend

server/mvcc/kvstore.go, server/mvcc/kvstore_compaction.go, server/mvcc/kvstore_compaction_test.go, server/mvcc/kvstore_test.go, server/mvcc/store.go, server/mvcc/store_test.go
=> etcdserver: Extract functions for setting and reading compaction information in backend

etcdutl/etcdutl/backup_command.go, etcdutl/snapshot/v3_snapshot.go, server/etcdserver/api/v3rpc/maintenance.go, server/etcdserver/backend.go, server/etcdserver/cindex/cindex.go, server/etcdserver/cindex/cindex_test.go, server/etcdserver/server.go, server/etcdserver/server_test.go, server/etcdserver/version/version.go, server/etcdserver/version/version_test.go, server/mvcc/buckets/cindex.go, server/mvcc/buckets/confstate_test.go, server/mvcc/buckets/version.go, server/mvcc/buckets/version_test.go, server/mvcc/kvstore_bench_test.go, server/verify/verify.go
=> etcdserver: Move Read/Update methods on Meta bucket to one place

README.md
Link the maintainers role and responsibilities.
=> README: link maintainers role details

contrib/raftexample/httpapi.go
=> Use method const in package http instead of literal

CHANGELOG-3.5.md
Add missing PR number in the changelog entry.
=> CHANGELOG: add missing PR number

CHANGELOG-3.4.md, raft/raft.go
=> MINOR: Fix typos(hearbeat -> heartbeat)

etcdutl/etcdutl/migrate_command.go
=> migrate_command: Fix typo in migrate

server/storage/wal/doc.go, server/storage/wal/repair.go
=> doc, log: fix typo in wal doc, log

server/etcdserver/server.go, tests/integration/clientv3/snapshot/v3_snapshot_test.go, tests/integration/snapshot/v3_snapshot_test.go, tests/integration/utl_wal_version_test.go
=> Fix a few typos

tools/rw-heatmaps/rw-benchmark.sh
=> rw benchmark add val-size

server/storage/mvcc/watchable_store.go
=> mvcc: simplify watchable_store addVictim code

Dockerfile-release.amd64, Dockerfile-release.arm64, Dockerfile-release.ppc64le, Dockerfile-release.s390x
=> [release-3.5] Dockerfile: bump debian bullseye-20210927

CHANGELOG-3.4.md
This PR updates CL to align with now released 3.4.17
=> CHANGELOG: 3.4.17

CHANGELOG-3.3.md
=> CHANGELOG: 3.3.26

scripts/genproto.sh
=> Fix genproto path error:./server/wal/walpb

server/etcdserver/api/etcdhttp/metrics.go, server/etcdserver/api/etcdhttp/metrics_test.go
cherry-pick to 3.5 from #13467
=> cherry-pick to 3.5 from #13467 exclude the same alarm type activated by multiple peers

CHANGELOG-3.6.md
=> CHANGELOG: add experimental-max-learners

etcdctl/ctlv3/command/defrag_command.go
=> etcdctl/ctlv3/command: add use time for defrag command

tools/rw-heatmaps/rw-benchmark.sh
Signed-off-by: Liang Zheng <zhengliang0901@gmail.com>
issue: #13496
=> fix etcd benchmark binary not found

server/mvcc/watchable_store.go
=> Backport watchablestore runlock bug fix to release-3.5

server/lease/leasehttp/http.go, server/storage/mvcc/index.go, server/storage/mvcc/kvstore.go, tools/etcd-dump-db/backend.go
Signed-off-by: Liang Zheng <zhengliang0901@gmail.com>
1. print remaining TTL
2. nitpick
=> update dump db tool

README.md
=> README: Cleanup community meetings video recordings

CHANGELOG-3.5.md
Update CHANGELOG-3.5 to cover the fix (see PR [pull/13501](https://github.com/etcd-io/etcd/pull/13501) ) for issue [issues/13494](https://github.com/etcd-io/etcd/issues/13494) . 
cc @ptabor @serathius  @spzala
=> update CHANGELOG-3.5.md to cover the fix for issue 13494

raft/node.go
=> raft: avoid jump tag to make code more understandable

server/storage/mvcc/kvstore_txn.go
=> Code clean: make rangeKeys close to storeTxnRead.

README.md
fix： https://github.com/etcd-io/etcd/issues/13620
=> README: fix go version that development required

.github/workflows/codeql-analysis.yml
Ref https://github.com/etcd-io/etcd/issues/13588
=> Add required permissions for CodeQL

.github/workflows/codeql-analysis.yml
Reverting changes made under #13631 per the latest discussion in the issue #13588 to
test if we can remove the write permission.
=> Revert CodeQL permission

README.md
=> Remove badge for disabled test suite

embed/config_logging.go
Fixes https://github.com/etcd-io/etcd/issues/13618 https://github.com/etcd-io/etcd/issues/12530
Cherry-pick https://github.com/etcd-io/etcd/pull/12406 to 3.4 branch
=> embed: only log stream error with debug level

CHANGELOG/CHANGELOG-3.1.md, CHANGELOG/CHANGELOG-3.2.md, CHANGELOG/CHANGELOG-3.3.md, CHANGELOG/CHANGELOG-3.4.md, CHANGELOG/CHANGELOG-3.5.md, scripts/release
=> release: Post v3.5.2 release updates and fixes

server/auth/simple_token.go
Fixes https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44478&q=etcd&can=1
=> server/auth: fix oss-fuzz issue 44478

server/storage/mvcc/index.go
Fixes: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=44449&q=etcd&can=1
=> server/storage/mvcc: fix oss-fuzz issue 44449

server/storage/backend/backend.go, server/storage/backend/backend_test.go
Problem: Defrag was implemented before custom bolt options were added.
Currently defrag doesn't restore backend options.
For example BackendFreelistType will be unset after defrag.
Solution: save bolt db options and use them in defrag.
fixes https://github.com/etcd-io/etcd/issues/13678
=> server/storage/backend: restore original bolt db options after defrag

server/etcdserver/server.go
Fixes https://oss-fuzz.com/testcase-detail/5146766184415232
=> server/etcdserver: fix oss-fuzz issue 42181

server/etcdserver/api/rafthttp/transport.go
base https://github.com/etcd-io/etcd/pull/13479, merge commit.
=> fix panic when restart after removeMember

MAINTAINERS
Per discussion with existing maintainers, I nominate @ahrtr for the reviewer role.
@ahrtr thank you for your outstanding contributions to the project.
/cc @ptabor @gyuho @hexfusion @jpbetz @xiang90 @mitake @jingyih @wenjiaswe
=> Add ahrthr@ to reviewers

etcdutl/etcdutl/migrate_command.go, server/embed/config_logging.go, server/storage/schema/membership.go, server/storage/schema/migration.go, server/storage/schema/schema.go, tests/functional/tester/cluster.go
Found some log format typos during code review. 
@spzala @serathius @ptabor
=> Fix some log format typos

etcdctl/README.md, etcdctl/ctlv3/command/defrag_command.go, tests/e2e/ctl_v3_defrag_test.go
Part of https://github.com/etcd-io/etcd/issues/13798
delete offline defrag in etcdctl  when release 3.6
cc @ptabor @spzala @serathius  @ahrtr
=> delete offline defrag in etcdctl

tests/e2e/ctl_v3_defrag_test.go, tests/e2e/ctl_v3_snapshot_test.go, tests/e2e/ctl_v3_test.go
Parts of https://github.com/etcd-io/etcd/issues/13798
Fixes comment: https://github.com/etcd-io/etcd/pull/13809#discussion_r827977075
=> test: set etcdutl to default

tools/etcd-dump-db/backend.go
Both `consistent_index` and `term` are uint64 values, so it makes more sense to display them as uint64. When the `--decode` flag is provided, then both of them are displayed as uint64 values, otherwise keep the existing behavior. 
See example output below,
```
$ ./etcd-dump-db iterate-bucket ~/tmp/etcd/default.etcd/member/snap/db meta --decode
key="term", value=3
key="consistent_index", value=6
key="confState", value="{\"voters\":[10276657743932975437],\"auto_leave\":false}"
```
=> enhance etcd-dump-db to display keys in meta more friendly

Makefile
Apologies, made a mistake here when implementing. 
This should try to pull than trying to push the image. I'll backport it to rel-3.5 and rel-3.4 as well.
=> Makefile: Fix wrong target

Makefile
Backport of https://github.com/etcd-io/etcd/pull/13857
=> [Release-3.5] Makefile: Fix wrong target

raft/raft.go
=> fix comment in raft.go

Makefile
@ptabor apologies, that it seems like i opened that [PR](https://github.com/etcd-io/etcd/pull/13857) too early, here's another small fix (otherwise it will build it anyway).
=> Makefile: Additional logic fix

client/pkg/logutil/zap.go, client/v3/client.go, client/v3/logger.go, client/v3/snapshot/v3_snapshot.go, etcdctl/ctlv3/command/ep_command.go, etcdctl/ctlv3/command/global.go, etcdctl/ctlv3/command/snapshot_command.go, etcdutl/etcdutl/common.go, etcdutl/snapshot/v3_snapshot.go, pkg/expect/expect.go, pkg/netutil/netutil.go, pkg/proxy/server.go, server/etcdmain/config.go, server/etcdmain/etcd.go, server/etcdmain/gateway.go, server/etcdmain/grpc_proxy.go, server/etcdmain/main.go, tests/e2e/cluster_test.go, tests/e2e/etcd_process.go, tests/e2e/util.go, tests/e2e/zap_logging_test.go, tests/functional/cmd/etcd-agent/main.go, tests/functional/cmd/etcd-proxy/main.go, tests/functional/cmd/etcd-tester/main.go, tests/functional/tester/cluster_test.go
Backport https://github.com/etcd-io/etcd/pull/13864 to release v3.5
cc @ptabor @ahrtr
=> [release-3.5] Fix inconsistent log format

etcdutl/etcdutl/backup_command.go, etcdutl/etcdutl/defrag_command.go, etcdutl/etcdutl/migrate_command.go, etcdutl/snapshot/v3_snapshot.go, server/etcdserver/cindex/cindex_test.go, server/lease/lessor_test.go, server/storage/backend.go, server/storage/backend/backend.go, server/storage/backend/backend_test.go, server/storage/backend/hooks_test.go, server/storage/backend/testing/betesting.go, server/storage/mvcc/store_test.go, server/storage/schema/auth_roles_test.go, server/storage/schema/auth_test.go, server/storage/schema/auth_users_test.go, server/storage/schema/lease_test.go, server/storage/schema/schema_test.go, server/storage/schema/version_test.go, server/verify/verify.go, tests/e2e/utl_migrate_test.go, tests/integration/clientv3/maintenance_test.go, tests/integration/v3_alarm_test.go, tools/benchmark/cmd/mvcc.go, tools/etcd-dump-db/backend.go
=> tests: Pass logger to backend

server/storage/mvcc/kvstore.go
It's just read-only operation, so replace batchTx with ReadTx
=> Use readTx in (*store).restore

etcdctl/go.mod, etcdctl/go.sum, etcdutl/go.mod, etcdutl/go.sum, go.mod, go.sum, server/go.mod, server/go.sum, tests/go.mod, tests/go.sum
=> *: update golang.org/x/crypto

CHANGELOG/CHANGELOG-3.5.md
@serathius 
adding changelog item for #13862
=> CHANGELOG-3.5: Add #13862

CHANGELOG/CHANGELOG-3.5.md, CHANGELOG/CHANGELOG-3.6.md
cc @serathius @spzala @ptabor @liggitt
=> Update changelog for 3.5.4 and 3.6

CHANGELOG/CHANGELOG-3.5.md
=> Update the release date of 3.5.4

tests/common/lease_test.go
Problem: TestLeaseGrantAndList is flaky because lists won't match at the end.
Test uses revision to verify that all members got leases. But checking for revision isn't enough.
Solution: use size of the list to stop polling.
=> tests/common/lease: don't use revision to wait for leases

tests/integration/clientv3/watch_test.go
This PR fix data race in `testWatchOverlapContextCancel()`
See #14003
=> Fix data race in testWatchOverlapContextCancel #14003

CHANGELOG/CHANGELOG-3.4.md
Update the CHANGELOG file for https://github.com/etcd-io/etcd/pull/13999
cc @ahrtr
=> Update CHANGELOG for PR 13999

client/pkg/fileutil/purge_test.go, client/pkg/transport/listener_test.go, client/v3/config_test.go, pkg/go.mod, pkg/go.sum, pkg/traceutil/trace_test.go, server/etcdserver/zap_raft_test.go, tools/etcd-dump-metrics/main.go
=> tests: Use zaptest.NewLogger in places we missed

.github/workflows/coverage.yaml
Ref https://github.com/etcd-io/etcd/issues/14012
cc @ptabor @spzala @ahrtr
=> coverage: Run coverage only on push

CHANGELOG/CHANGELOG-3.4.md
Prepare for the 3.4.19.
cc @serathius @ptabor @spzala @mitake @cfz @hexfusion
=> Update 3.4 change log for 3.4.19

client/pkg/verify/verify.go
Provide a generic assert function so that it can be reused by others, such as [pull/13947](https://github.com/etcd-io/etcd/pull/13947) and [pull/14022](https://github.com/etcd-io/etcd/pull/14022)
=> Provide a generic assert function

tests/common/kv_test.go, tests/common/lease_test.go, tests/common/main_test.go, tests/common/role_test.go, tests/common/txn_test.go, tests/common/user_test.go
=> tests: Extract cluster test cases

tests/common/alarm_test.go, tests/common/compact_test.go, tests/common/defrag_test.go, tests/common/endpoint_test.go, tests/common/kv_test.go, tests/common/lease_test.go, tests/common/role_test.go, tests/common/txn_test.go, tests/common/user_test.go, tests/framework/e2e.go, tests/framework/integration.go, tests/framework/interface.go, tests/framework/testutils/execute.go, tests/framework/unit.go
=> tests: Make common framework context aware

Documentation/postmortems/v3.5-data-inconsistency.md
I think we gave enough time to collect feedback on postmortem. It was also presented on recent community meeting.
=> Documentation: Publish v3.5 data inconsistency postmortem

scripts/release.sh
cc @ahrtr @ptabor 
This PR removes additional clone when building artifacts.
When releasing v3.5.4 this clone was main cause of issues and
confusion about what release script is doing.
release.sh script already clones repo in /tmp/ directory, so clonning
before build is not needed. As precautions for bug in script leaving
/tmp/ clone in bad state  I moved "Verify the latest commit has the
version tag" and added "Verify the clean working tree" to be always run
before build.
=> scripts: Avoid additional repo clone

scripts/release.sh
=> scripts: Detect staged files before building release

server/etcdserver/api/snap/snapshotter.go
=> Fix a typo: print the correct error info

contrib/raftexample/Procfile
=> use go install instead of go get

.gitignore, tools/benchmark/.gitignore
=> Add etcd tool binaries into .gitignore
