etcdserver/raft.go, etcdserver/server.go, etcdserver/util_test.go, rafthttp/transport.go
Cherry pick of #9415 on release-3.2.
#9415: rafthttp: add "ActivePeers" to "Transport"
=> Automated cherry pick of #9415

raft/rafttest/node_bench_test.go, raft/rafttest/node_test.go
Tests in `rafttest` would fail because they referred to field `Id` instead of `ID`.
This PR fixes that.
Closes #9504.
=> raft: fix failing tests in rafttest

Documentation/op-guide/configuration.md
Explanation of configuration flag '--auto-compaction-mode' is rendered as table in coreos.com
(https://coreos.com/etcd/docs/latest/op-guide/configuration.html)
=> Explanation of configuration flag '--auto-compaction-mode' is rendered as table in coreos.com

CHANGELOG-3.4.md, embed/config.go, etcdctl/ctlv3/command/global.go, etcdmain/etcd.go, etcdmain/grpc_proxy.go, pkg/transport/listener.go, pkg/transport/listener_test.go, pkg/transport/proxy.go
We weren't logging anything, and logs were being silenced in Go runtime.
Fix https://github.com/coreos/etcd/issues/9400.
Address https://github.com/coreos/etcd/issues/9438.
=> pkg/transport: log cert file not found in server-side

CHANGELOG-3.4.md, lease/lease_queue.go, lease/lessor.go, lease/lessor_bench_test.go
This adds a heap acting as a priority queue to keep track of lease
exiprations. Previously the whole lease map had to be iterated through
each time.
The queue allows us to check only those leases which might be expired.
When the expiration changes, we add an additional entry. If we check an
entry that isn't expired, it means that the lease got extended.
If we find a entry in the heap that doesn't have a corresponding entry in
the map, we know that the lease has already been expired or revoked.
This is our first stab at writing real Go, and we're happy to make any changes if you all think this is a good way of doing things.
/cc @jcalvert
=> lease: Add a heap to optimize lease expiration checks

etcdctl/ctlv3/command/snapshot_command.go, snapshot/v3_snapshot.go, snapshot/v3_snapshot_test.go
In the process of removing capnslog
Address https://github.com/coreos/etcd/issues/9438
=> snapshot: use structured logger

CHANGELOG-3.4.md, etcdctl/ctlv3/command/ep_command.go, etcdctl/ctlv3/command/printer.go, etcdctl/ctlv3/command/printer_fields.go, etcdctl/ctlv3/command/printer_json.go, etcdctl/ctlv3/command/printer_simple.go, etcdctl/ctlv3/command/printer_table.go
```bash
$ ETCDCTL_API=3 ./bin/etcdctl endpoint --cluster health --write-out simple                                                    
http://127.0.0.1:2379 is healthy: successfully committed proposal: took = 474.51µs                                                                            
http://127.0.0.1:32379 is healthy: successfully committed proposal: took = 719.75µs                                                                           
http://127.0.0.1:22379 is healthy: successfully committed proposal: took = 459.323µs                                                                          
$ ETCDCTL_API=3 ./bin/etcdctl endpoint --cluster health --write-out table                                                     
+------------------------+--------+-----------+-------+ …
```
=> ctlv3: support "write-out" for "endpoint health" command

CHANGELOG-3.4.md, etcdserver/v3_server.go
after https://github.com/coreos/etcd/pull/9137 merged, may need to handle the proposal error in etcdserver.
This will be used to fix issue: https://github.com/coreos/etcd/issues/8975
=> etcdserver: handle proposal error when processing internal raft request

clientv3/integration/server_shutdown_test.go, clientv3/integration/util.go
Balancer tests have been flaky since last balancer rewrite.
Should be from slow balancer failover. Once we re-rewrite balancer
with roundrobin, there should be no more flaky tests as below:
```
TestBalancerUnderServerStopInflightLinearizableGetOnRestart (27.62s)
server_shutdown_test.go:343: context deadline exceeded
TestBalancerUnderServerShutdownDelete (3.22s)
util.go:32: context deadline exceeded
```
/cc @jpbetz
=> clientv3/integration: log test failures from slow balancer as TODO

etcdserver/v2_server.go
Handle "raft.ErrProposalDropped" as in v3 applier.
=> etcdserver: handle raft Propose error in v2 applier

.travis.yml, Makefile, bill-of-materials.json, bill-of-materials.override.json, etcdserver/v2_server.go, test, tests/semaphore.test.bash
Address https://github.com/coreos/etcd/issues/8862.
Currently, semaphore runs almost >50min. We have 5 workers in travis (vs. 2 workers in semaphore), so move `functional` and `integraion` tests to Travis, and only run `e2e` tests in semaphore. This should reduce test runtime from 50-min to 35-min.
Later, split more over to Jenkins.
=> *: parallelize tests, remove redundant tests, Phase 1

pkg/proxy/server.go, pkg/proxy/server_test.go
Extend proxy for more advanced corrupt and packet drop testing.
For https://github.com/coreos/etcd/issues/5614 and https://github.com/coreos/etcd/issues/9563.
=> pkg/proxy: make/simplify interface more extensible

embed/etcd.go, embed/serve.go
This is pending https://github.com/grpc/grpc-go/pull/1883
ref: https://github.com/coreos/etcd/issues/9340
=> embed: explicitly define unix proto

etcdserver/metrics.go, etcdserver/raft.go
Before this change, we had now way to find a leader using /metrics endpoint. This commit adds a metric to do that.
=> etcdserver: add is_leader prometheus metric that is 1 on the leader.

CHANGELOG-3.3.md, CHANGELOG-3.4.md, Documentation/upgrades/upgrade_3_3.md, etcd.conf.yml.sample
Uber actually uses YAML config file, and this was an undocumented breaking change.
@fanminshi @joelegasse
=> *: highlight breaking change in compaction retention

Documentation/op-guide/maintenance.md, Documentation/upgrades/upgrade_3_2.md
Fix https://github.com/coreos/etcd/issues/8018.
Address https://github.com/coreos/etcd/issues/7607.
https://github.com/coreos/etcd/issues/7607 needs more monitoring doc.
@mitake @yudai
=> *: improve compaction documentation

etcdserver/metrics.go, etcdserver/raft.go
Cherry pick of #9587 on release-3.1.
#9587: etcdserver: add is_leader prometheus metric that is 1 on the
=> Automated cherry pick of #9587

CHANGELOG-3.1.md, CHANGELOG-3.2.md
Per https://github.com/coreos/etcd/issues/9592, add notes for upcoming 3.1 and 3.2 releases
=> CHANGELOG: Add 3.1.14 and 3.2.19 release notes

Documentation/op-guide/configuration.md
Address https://github.com/coreos/etcd/pull/9591#issuecomment-383019257.
/cc @mborsz @joelegasse
=> Documentation/op-guide: add missing flags, clarify "--initial*" flags

scripts/release
We found a couple obvious bugs when attempting to use the release script for the first time.  This fixes those:
- Docker tags should be of the form "v<etcd-semver>".
- The git tag validation check was always failing causing the script to terminate early.
- The build script was assumed to be `./scripts/release.sh` but the previous PR move that script to `./scripts/build-release.sh`.  For now this script will check for both and use whichever exists so we can release 3.1..3.3 from this script.
- When entering docker registry passwords, don't exit the script if the login fails, instead keep retrying.
We should be able to safely re-run the script if it fails for any reason.  To make this possible:
- Instead of creating a new tempdir for each run, reuse the same temp dir using the naming scheme …
=> scripts: Fix a few etcd release script bugs and make it reenterant.

etcdctl/ctlv3/command/global.go
Fixes https://github.com/coreos/etcd/issues/9619
Before
```
$ ETCDCTL_API=3 etcdctl --cert tls/etcd-client.crt --key tls/etcd-client.key get keys --endpoints=https://etcd-1.local:12379 get keys                                                                                                                            
Error: context deadline exceeded
```
After
```
$ ETCDCTL_API=3 etcdctl --cert tls/etcd-client.crt --key tls/etcd-client.key get keys --endpoints=https://etcd-1.local:12379 get keys                                                                                                                          
WARNING: 2018/04/24 15:34:04 Failed to dial etcd-1.local:12379: connection error: desc = "transport: authentication handshake failed: x509: certificate signed by unknown …
```
=> etcdctl/ctlv3/command: enable gRPC WARNING logs by default

etcdctl/ctlv3/command/global.go
Despite holding important information, these are too noisy.
See https://github.com/coreos/etcd/pull/9623
=> etcdctl/ctlv3/command: don't print gRPC WARNING logs by default

pkg/idutil/id.go, pkg/idutil/id_test.go
Use atomic.AddUint64(_fetch-and-add primitive_) instead of mutex lock to inc count field.
Bench result:
```
benchmark           old ns/op     new ns/op     delta
BenchmarkNext-4     163           26.3          -83.87%
```
=> pkg/idutil: use count field as atomic variable

etcdserver/api/v2v3/store.go, etcdserver/v2store/store_test.go
When a new file is created under an non existent directly,
the v2 API automatically create the parent directly.
This commit aligns the behaviour of v2v3 emulation to comply with the v2
API.
Fixes #9609
=> etcdserver: Fix v2v3api set to create parent directly if not exists

etcdserver/config.go, etcdserver/membership/cluster.go, etcdserver/membership/cluster_test.go, etcdserver/server.go, pkg/netutil/doc.go, pkg/netutil/netutil.go, pkg/netutil/netutil_test.go
=> pkg/netutil: use structured logging for TCP resolve

auth/jwt.go, auth/jwt_test.go, auth/range_perm_cache.go, auth/range_perm_cache_test.go, auth/simple_token.go, auth/simple_token_test.go, auth/store.go, auth/store_test.go, etcdserver/server.go, test
=> auth: support structured logging

CHANGELOG-3.3.md, Documentation/op-guide/configuration.md, Documentation/op-guide/monitoring.md, etcdmain/config.go, etcdmain/help.go
The `--listen-metrics-urls` also responds to the `/health` endpoint, but
that was not made clear in the documentation. These updates should help
explain how else that flag can be used.
Fixes #9653
=> docs: Update documentation around --listen-metrics-urls

contrib/raftexample/raft.go
`progress.appliedIndex[%d] 1` should be `progress.appliedIndex[%d]+1`.
=> contrib/raftexample: fix typo

contrib/raftexample/kvstore.go
`err == raftsnap.ErrNoSnapshot` being false implies that
`err != raftsnap.ErrNoSnapshot` is true.
=> contrib/raftexample: remove useless check

.travis.yml, CHANGELOG-3.4.md, Makefile, test, tests/semaphore.test.bash
Already pushed test images to gcr. Will update 3.3 branch as well.
https://golang.org/doc/devel/release.html#go1.10
=> *: use Go 1.10.2 and Go 1.9.6

CHANGELOG-3.4.md, clientv3/integration/logger_test.go, clientv3/ordering/logger_test.go, etcdserver/api/v3rpc/watch.go, etcdserver/v2store/store_v2v3_test.go, integration/cluster.go, integration/logger_test.go
To enable:
```bash
CLUSTER_DEBUG=1 go test -v -run TestRestartRemoved
```
=> integration: use "zap" in tests

CHANGELOG-3.5.md, Documentation/upgrades/upgrade_3_5.md, etcd.conf.yml.sample
v3.4 still keeps capnslog and everything else.
v3.5 starts deprecating capnslog and capnslog specific config `--log-package-levels` flag.
=> *: highlight "--log-package-levels" deprecation in v3.5

Documentation/op-guide/clustering.md
ref: https://github.com/coreos/etcd/issues/6336, https://github.com/coreos/etcd/issues/9575
=> Documentation: binding listeners must be IP.

contrib/recipes/grpc_gateway/user_add.sh
Show automated authentication workflow example in bash using TLS and curl.
ref: https://github.com/coreos/etcd/issues/9691
=> contrib: add gRPC gateway script for user/add with full chain TLS.

etcdserver/server.go
etcdserver: purge old snap.db files
Lots of garbage db files in #7957. Should purge.
=> Cherry-picking PR 7967 to release-3.2

Documentation/op-guide/configuration.md, auth/store.go, auth/store_test.go, clientv3/main_test.go, embed/config.go, embed/etcd.go, etcdmain/config.go, etcdmain/help.go, etcdserver/config.go, etcdserver/server.go, integration/cluster.go
This change implements the feature request in #9615. It replaces https://github.com/coreos/etcd/pull/9633
=> *: make bcrypt-cost configurable

etcdserver/backend.go, etcdserver/server.go, mvcc/backend/backend.go, mvcc/backend/batch_tx.go, mvcc/index.go, mvcc/index_test.go, mvcc/key_index.go, mvcc/key_index_test.go, mvcc/kvstore.go, mvcc/kvstore_test.go, mvcc/kvstore_txn.go, mvcc/util.go, mvcc/watchable_store.go, rafthttp/http.go, rafthttp/snapshot_sender.go, raftsnap/db.go
=> *: add more structured logger

etcdmain/etcd.go, etcdmain/grpc_proxy.go, tests/e2e/cluster_proxy_test.go
https://jenkins-etcd.prod.coreos.systems/job/etcd-coverage/4144/console
Coverage tests should be fixed with this.
=> tests/e2e: fix v2 proxy tests

scripts/release
Fix a couple issues in the release script, the most significant:
- set umask to `022` at start of script to guarantee release artifacts always have the same permission bits regardless of build machine
- fix gcloud login retry loop
- fix checking of github remote tags
- fix docker pushes to not attempt to push arm64 and ppc64le for etcd 3.1, since support for those architectures began in 3.2
Fixes https://github.com/coreos/etcd/issues/9701
=> scripts: Fix remote tag check, gcloud login and umask in release script

mvcc/kvstore_txn.go
We replace/insert into in-memory B-tree, which means
we only keep a single node per key thus do not support
delete by revision on B-tree. So, (*keyIndex).tombstone
has always been marked with latest revision.
tombstone with key's modified revision panics:
```
panic: store.keyindex: put with unexpected smaller revision [{2 0} / {2 0}]
```
=> mvcc: use latest revision to tombstone

etcdctl/ctlv3/command/check.go
Create a progress bar. The bar will show progress for a given workload.
Fixes #9328
=> etcdctl/check: create progress bar for datascale

README.md
Closes https://github.com/coreos/etcd/issues/9721
We can update this to a non-Red Hat controlled list if there's interest later. For now we need something.
cc @gyuho
=> README.md: add security disclosure link

CHANGELOG-3.4.md, CHANGELOG-3.5.md, Documentation/upgrades/upgrade_3_4.md, Documentation/upgrades/upgrade_3_5.md, Documentation/v2/admin_guide.md, etcdserver/api/etcdhttp/base.go
It's capnslog specific endpoint. Should be deprecated.
=> doc: deprecate '/config/local/log' in v3.5

pkg/logutil/zap_journald.go
Found that it was detecting as journald when run with container
```
FAILED TO WRITE TO JOURNALD journal error: could not connect to journald socket {"level":"info","ts":1526495490.4501956,"caller":"rafthttp/peer.go:340","msg":"stopped remote peer","remote-peer-id":"5a8f1f42fc365b65"}
{"level":"info","ts":1526495490.4501956,"caller":"rafthttp/peer.go:340","msg":"stopped remote peer","remote-peer-id":"5a8f1f42fc365b65"}
```
Which means capnslog will also keep error for every single log write.
After this PR, will disable PPID = 1 checks on journald logging.
Should only be configured manually.
=> pkg/logutil: do not print error message on journaldWriter

CHANGELOG-3.4.md, pkg/fileutil/fileutil.go, pkg/fileutil/fileutil_test.go, pkg/fileutil/read_dir.go, pkg/fileutil/read_dir_test.go, wal/util.go
Fix https://github.com/coreos/etcd/issues/7287.
In other words, WAL directory with a single `lost+found` file will be considered not initialized.
=> wal: allow non-WAL files in wal directory

clientv3/integration/watch_fragment_test.go
Client receive limit is not yet supported in gRPC proxy. Fixes test failures.
=> clientv3/integration: do not run fragmentation tests with gRPC Proxy

CHANGELOG-3.4.md, Documentation/upgrades/upgrade_3_4.md, contrib/raftexample/raft.go, embed/config.go, embed/etcd.go, etcdmain/config.go, etcdmain/config_test.go, etcdserver/config.go, etcdserver/raft.go, etcdserver/server.go, etcdserver/server_test.go, functional/rpcpb/etcd_config.go, functional/rpcpb/etcd_config_test.go, integration/cluster.go, integration/cluster_test.go, integration/member_test.go, integration/v3_watch_test.go, tests/e2e/cluster_test.go, tests/e2e/ctl_v2_test.go, tests/e2e/etcd_corrupt_test.go, tests/e2e/etcd_release_upgrade_test.go
To cover the real-world use case that fails 100% without @yudai's watch fix https://github.com/coreos/etcd/pull/9281.
```diff
diff --git a/mvcc/watchable_store.go b/mvcc/watchable_store.go
index edbb7f9d0..bdffbf749 100644
--- a/mvcc/watchable_store.go
+++ b/mvcc/watchable_store.go
@@ -193,7 +193,7 @@ func (s *watchableStore) Restore(b backend.Backend) error {
}
for wa := range s.synced.watchers {
-               s.unsynced.watchers.add(wa)
+               s.unsynced.add(wa)
}
s.synced = newWatcherGroup()
return nil
```
To make it testable, added `SnapshotCountCatchUpEntries` field, but make it configurable only via tests.
=> *: test watch restore in network-partitioned node, clean up fields, logging

auth/jwt_test.go, auth/store.go, auth/store_test.go, tests/e2e/ctl_v3_auth_test.go
ref: https://github.com/coreos/etcd/issues/9695
=> auth: fix panic using WithRoot and improve JWT coverage

CHANGELOG-3.4.md, Gopkg.lock, etcdserver/api/v3election/v3electionpb/gw/v3election.pb.gw.go, etcdserver/api/v3lock/v3lockpb/gw/v3lock.pb.gw.go, etcdserver/etcdserverpb/gw/rpc.pb.gw.go, scripts/genproto.sh
This PR bumps up gRPC gateway dependency to [v1.4.0](https://github.com/grpc-ecosystem/grpc-gateway/releases/tag/v1.4.0)
ref: https://github.com/coreos/etcd/issues/9753
=> vendor: use latest "grpc-ecosystem/grpc-gateway"

etcdserver/api/v3rpc/lease.go, etcdserver/api/v3rpc/metrics.go, etcdserver/api/v3rpc/watch.go
ref. https://github.com/coreos/etcd/issues/9438
=> etcdserver/api/v3rpc: add "etcd_network_server_stream_failures_total"

etcdserver/metrics.go, etcdserver/raft.go, etcdserver/util.go, mvcc/backend/backend.go, mvcc/backend/batch_tx.go, mvcc/backend/metrics.go, mvcc/kvstore.go, mvcc/metrics.go
https://github.com/coreos/etcd/issues/9438 and https://github.com/coreos/etcd/issues/8910
=> etcdserver,mvcc: add more storage layer metrics

etcdserver/api/rafthttp/metrics.go, etcdserver/api/rafthttp/peer.go, etcdserver/api/rafthttp/peer_status.go, etcdserver/api/rafthttp/pipeline_test.go, etcdserver/api/rafthttp/probing_status.go, etcdserver/api/rafthttp/remote.go, etcdserver/api/rafthttp/snapshot_test.go, etcdserver/api/rafthttp/stream_test.go, etcdserver/api/snap/metrics.go, etcdserver/api/snap/snapshotter.go, etcdserver/api/v2http/metrics.go, mvcc/backend/backend.go, mvcc/backend/batch_tx.go, mvcc/backend/metrics.go, mvcc/kvstore.go, mvcc/kvstore_compaction.go, mvcc/metrics.go, proxy/httpproxy/metrics.go, wal/metrics.go, wal/wal.go
And clean up second computation (just call `time.Duration.Seconds()`).
=> *: document all histogram metrics, add etcd_snap_fsync_duration_seconds

integration/cluster.go, integration/v3_auth_test.go
https://github.com/coreos/etcd/pull/9698 wasn't really testing
the panic code path when leases are expiry.
ref. https://github.com/coreos/etcd/issues/9695
=> integration: test lease revoke routine with JWT token

lease/lessor.go, lease/metrics.go
This patch adds four metrics (leases granted, leases revoked, leases renewed, and the average TTL of leases) to the `leases` package for easier debugging and visibility into outstanding leases. 
There's not currently a way to monitor the number of leases that are granted or revoked within etcd.  It's currently possible to see the number of leases expired via `server_lease_expired_total`, but not the number initially granted nor those being renewed.
This makes it tough to determine the current number of leases held, and determine why leases are not being cleaned up. This patch makes the behavior described in, for example, https://github.com/coreos/etcd/issues/9395 easier to debug and understand as it makes it clear that leases are never being revoked, rather than renewed forever.
Please …
=> leases: Add metrics to etcd leases

raft/raft.go
At the beginning, I found `raft.resetRandomizedElectionTimeout` is called in single goroutine of `raft.node.run`. So I thought there's no need to use mutex lock to protect `rand.Rand` variable.
After searching commit history and finding related issue #6347, I noticed that static varitable `globalRand` could be accessed by multi raft groups.
This commit adds comment of the reason why `globalRand(lockedRand)` needs synchronization, which may save time of the newcomers.
=> raft: describe the purpose of lockedRand

etcdctl/ctlv3/command/global.go
=> etcdctl/ctlv3 : fixes 9583. trim spaces in ETCDCTL_ENDPOINTS env variable

Documentation/etcd-mixin/README.md, Documentation/etcd-mixin/mixin.libsonnet
This PR contains a set of Prometheus alerts for etcd, based on a new format for distributing reusable, customisable alerts called "monitoring mixins".  
The mixin is based on the existing alerts in the repo; this format more flexible that as it allows users to customer the selectors used in the alerts.  Coupled with the new package manager, users can contribute to and easily stay up to date with alert definitions.  I suggest we remove the existing alerts and include instructions to generate them from the mixin.  WDYT?
See https://docs.google.com/document/d/1A9xvzwqnFVSOZ5fD3blKODXfsat5fg6ZhnKu9LK3lB4/edit# for more details on the format.
/cc @brancz
=> Documentation: add Prometheus monitoring-mixin

Documentation/op-guide/authentication.md, etcdctl/ctlv3/command/global.go, etcdctl/ctlv3/command/user_command.go, etcdctl/ctlv3/ctl.go
Fix https://github.com/coreos/etcd/issues/9691
/cc @cristifalcas you can create a user whose name includes `:` now
=> etcdctl: add --password flag to the subcommand user add

Documentation/op-guide/etcd3_alert.rules, Documentation/op-guide/etcd3_alert.rules.yml
We're running etcd v3.2.7 and I can't see those metrics with the `etcd_http` prefix.
I guess, they have been removed in v3?
I double checked on `:2379/metrics` and they don't show up.
=> Documentation/op-guide: remove etcd_http_.* rules from examples

clientv3/integration/maintenance_test.go
Errors from gRPC should be typed *status.statusError
```
=== RUN   TestMaintenanceSnapshotErrorInflight
WARNING: 2018/05/29 11:43:21 grpc: addrConn.resetTransport failed to create client transport: connection error: desc = "transport: Error while dialing dial unix localhost:55815860381826373260: connect: no such file or directory"; Reconnecting to {localhost:55815860381826373260 0  <nil>}
--- FAIL: TestMaintenanceSnapshotErrorInflight (2.42s)
maintenance_test.go:192: expected context deadline exceeded, got rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
Fix https://jenkins-etcd-public.prod.coreos.systems/job/etcd-proxy/4840/console.
=> clientv3/integration: fix "TestMaintenanceSnapshotErrorInflight"

Documentation/op-guide/monitoring.md
Fixed a few minor typos and added a note about min etcd version for flag usage.
=> Documentation: add min version for --listen-metric-urls flag.

integration/v3_watch_restore_test.go, mvcc/watchable_store.go, mvcc/watchable_store_test.go, mvcc/watcher_group.go
It can happen without gRPC proxy as well.
Fix panic when gRPC proxy leader watcher is restored:
```
go test -v -tags cluster_proxy -cpu 4 -race -run TestV3WatchRestoreSnapshotUnsync
=== RUN   TestV3WatchRestoreSnapshotUnsync
panic: watcher minimum revision 9223372036854775805 should not exceed current revision 16
goroutine 156 [running]:
github.com/coreos/etcd/mvcc.(*watcherGroup).chooseAll(0xc4202b8720, 0x10, 0xffffffffffffffff, 0x1)
/home/gyuho/go/src/github.com/coreos/etcd/mvcc/watcher_group.go:242 +0x3b5
github.com/coreos/etcd/mvcc.(*watcherGroup).choose(0xc4202b8720, 0x200, 0x10, 0xffffffffffffffff, 0xc420253378, 0xc420253378)
/home/gyuho/go/src/github.com/coreos/etcd/mvcc/watcher_group.go:225 +0x289
github.com/coreos/etcd/mvcc.(*watchableStore).syncWatchers(0xc4202b86e0, 0x0) …
```
=> mvcc: fix panic by allowing future revision watcher from restore operation

scripts/release
Just a couple small fixes to the release script.
=> scripts/release: Fix docker push for 3.1 releases, remove inaccurate warning at the end of release script

etcdctl/README.md
In `etcdctl txn`, the`create` target also expects operand or error is printed.
```
$ etcdctl txn -i
compares:
create("mykey") "1"
Error:  malformed comparison: create("mykey") "1"; got create("mykey") "1" ""
```
=> Documentation: Fix etcdctl tx eBNF

etcdctl/ctlv3/ctl_cov.go, etcdctl/ctlv3/ctl_nocov.go, etcdctl/main.go, tests/e2e/ctl_v2_test.go
To make coverage stats happy https://codecov.io/gh/coreos/etcd/commit/25bc65794f6802cb24b40c3a46de9ab3fa5f9e6b.
=> etcdctl/ctlv3: remove ETCDCTL_API warning, fix e2e coverage tests

mvcc/watchable_store_bench_test.go
```
$ go test -v -run XXX -bench BenchmarkWatchableStoreWatchPutUnsync
BenchmarkWatchableStoreWatchPutUnsync-4   	  200000	      7398 ns/op	     282 B/op	       2 allocs/op
$ go test -v -run XXX -bench BenchmarkWatchableStoreWatchPutSync
BenchmarkWatchableStoreWatchPutSync-4   	 1000000	      2691 ns/op	     251 B/op	       2 allocs/op
```
=> mvcc: separate synced/unsynced benchmarks

etcdctl/ctlv3/command/check.go
We should have limit of 3M not 30 as it's said in the doc comment.
=> Check: correct the memory limit

etcdctl/ctlv3/command/global.go, etcdctl/ctlv3/command/move_leader_command.go, tests/e2e/ctl_v3_move_leader_test.go
Fix https://github.com/coreos/etcd/issues/9805.
=> ctlv3: support TLS endpoints for move-leader command

etcdserver/backend.go, etcdserver/server.go
On 3.1.11, we encountered:
```
2018-06-01 00:15:41.134882 C | etcdmain: database file (/tmp/default.etcd/member/snap/db index 263183180) does not match with snapshot (index 265092933).
```
This has proved tricky to reproduce exactly, but we were able to simulate it by setting --max-wals=1 stopping a member, waiting for the wal logs to be replaced, forcing compaction and then replacing the db file with one of the out-of-date snap.db files.
We believe it is caused by recovery from a snap.db file when etcd crashes after persisting the snapshot file to disk but before updating the backend db. `recoverBackendSnapshot` was introduced in https://github.com/coreos/etcd/pull/7917 to fix this in etcd 3.2+, so this PR backports that recovery code to 3.1.
./test SUCCESS
PASSES=integration ./test …
=> etcdserver: Backport snapshot recovery from #7917 to 3.1 branch

lease/lessor.go
Because the leases were sorted inside UnsafeLeases() the lessor mutex
ended up being locked while the whole map was sorted. This pulls the
soring outside of the lock, per feedback on
https://github.com/coreos/etcd/pull/9699
=> leases: Move lease sorting outside of lock

scripts/release
The following line expects etcd to be built can check version.
=> scripts: Fix release script to always build etcd binary before checking version

Documentation/op-guide/grafana.json, Documentation/op-guide/maintenance.md, Documentation/upgrades/upgrade_3_4.md, Documentation/upgrades/upgrade_3_5.md, integration/metrics_test.go, mvcc/kvstore.go, mvcc/metrics.go
`etcd_debugging_mvcc_db_total_size_in_bytes` will still be kept for backward compatibilities.
`etcd_debugging_mvcc_db_total_size_in_use_in_bytes` was never released, so just renaming it to `etcd_mvcc_db_total_size_in_use_in_bytes`.
ref. https://github.com/coreos/etcd/issues/9438
=> *: promote db size metric to "'etcd" namespace

etcdserver/metrics.go, etcdserver/quota.go, integration/metrics_test.go
Currently, there's no way to programmatically fetch the current quota size and use it for alert. One manually needs to look at the server configuration flag, or look at the server logs.
Add `etcd_server_quota_backend_bytes` metrics. It will be useful for writing alert rules combining with `etcd_mvcc_db_total_size_in_bytes` and `etcd_mvcc_db_total_size_in_use_in_bytes`, before the alarm is raised.
/cc @saranbalaji90 @xiang90 @jpbetz
=> *: add "etcd_server_quota_backend_bytes" metric

etcdserver/etcdserverpb/raft_internal_stringer.go
This removes the logging of values for "request took too long warnings" that was introduced in etcd 3.2.  We shouldn't log values. Value fields are likely contain sensitive data, make the logs difficult to scan, and have the potential to "flood" the logs exhausting disk space and/or starving the system disk IO.
This replaces all occurrences of value fields with a value_size field. Fortunately there are only two occurrences: (1) put requests and (2) txns that do a value compare.
txn:
```
BEFORE:
2018-06-07 16:54:52.146394 W | etcdserver: request "header:<ID:7587830746628055043 > txn:<compare:<target:VALUE key:\"a\" value:\"1\" > success:<request_put:<key:\"b\" value:\"foo\" > > failure:<request_put:<key:\"c\" value:\"goo\\\"\" > > > " took too long (106.821µs) to execute …
```
=> etcdserver: Replace value contents with value_size in request took too long warning

integration/v3_tls_test.go
Found via testing new gRPC balancer.
=> integration: block dial for timeout errors

etcdserver/apply.go, etcdserver/apply_v2.go, etcdserver/util.go, etcdserver/v3_server.go
Large range reads can result in "took too long" warnings. This adds range response counts as well as total proto response message size (in bytes) to the warnings to help debug situations where knowing the volume of data returned can help diagnose an issue.
put:
```
BEFORE:
2018-06-08 10:11:40.140673 W | etcdserver: read-only range request "key:\"/a\" range_end:\"/b\" " took too long (97.966µs) to execute
AFTER:
2018-06-08 10:11:40.140673 W | etcdserver: read-only range request "key:\"/a\" range_end:\"/b\" " with result "range_response_count:3 size:96" took too long (97.966µs) to execute
```
txn:
```
BEFORE:
etcdserver: read-only range request "compare:<target:VALUE key:\"a\" value:\"1\" > success:<request_range:<key:\"/a\" range_end:\"/b\" > > failure:<request_range:<key:\"/a\" …
```
=> etcdserver: Add response byte size and range response count to took too long warning

functional/tester/case.go
Fix negative commit entry diff:
> {"level":"info","ts":1528740474.775448,"caller":"tester/case.go:299","msg":"trigger snapshot PROGRESS","retries":53,"committed-entries":-238470,"etcd-snapshot-count":10000,"start-revision":238470,"last-revision":0,"took":77.302668629,"error":"context deadline exceeded"}
=> functional/tester: fix trigger snapshot retry

CHANGELOG-3.4.md, mvcc/backend/batch_tx.go, mvcc/backend/metrics.go
@gyuho @jpbetz 
We observed high latency in the commit call. Adding more metrics can help to understand which part of bbolt commit is the root cause.
=> backend: more metrics for bboltdb transaction

etcdserver/etcdserverpb/raft_internal_stringer.go, etcdserver/util.go
#9822 fixed log entries starting with "etcdserver: request", but not those starting with. "etcdserver: read-only range request":
```
etcdserver: read-only range request "compare:<target:VALUE key:\"a\" value:\"1\" > success:<request_range:<key:\"/a\" range_end:\"/b\" > > failure:<request_range:<key:\"/a\" range_end:\"/b\" > > " with result "responses:<range_response_count:0> size:12" took too long (48.373µs) to execute
```
This fixes the logger to handle the "read-only range" warnings correctly:
```
etcdserver: read-only range request "compare:<target:VALUE key:\"a\" value_size:1 > success:<request_range:<key:\"/a\" range_end:\"/b\" > > failure:<request_range:<key:\"/a\" range_end:\"/b\" > >" with result "responses:<range_response_count:0> size:12" took too long (37.32µs) to execute
```
=> etcdserver: Fix txn request 'took too long' warnings to use loggable request stringer

etcdserver/apply.go, etcdserver/apply_v2.go, etcdserver/etcdserverpb/raft_internal_stringer.go, etcdserver/server.go, etcdserver/util.go, etcdserver/v2_server.go, etcdserver/v3_server.go
Cherry pick request "took too long" warning improvements to release-3.2.
To improve debuggability of etcd.  This is important since etcd 3.1+ no longer appended quorum writes to WAL log, and this will the only record expensive requests.
#9288: etcdserver: improve request took too long warning
#9661: etcdserver: not print password in the warning message of expensive request
#9822: etcdserver: Replace value contents with value_size in request took too long warning
#9826: etcdserver: Add response byte size and range response count to took too long warning
#9835: etcdserver: Fix txn request 'took too long' warnings to use loggable request stringer
=> Automated cherry pick of detailed "took too long" warnings to release-3.2

.travis.yml
We only get 5 concurrent workers in Travis.
Save time by fetching test image only once
for all build tests.
Keep working for https://github.com/coreos/etcd/issues/8862.
=> travis: combine all build tests

etcdserver/metrics.go
Cherry pick of #8960 on release-3.1.
#8960: metrics: Add server_version metric
=> Automated cherry pick of #8960

clientv3/client.go, clientv3/watch.go
this is a targeted fix to the predominant CPU consumer when an etcd server becomes unavailable to a client with established watches. this picks cleanly back to 3.3.x and 3.2.x
This took our apiserver from 700% cpu when etcd was temporarily down to 10% cpu
xref #9578 #9740
=> Backoff on reestablishing watches when Unavailable errors are encountered

raft/logger.go
etcd/raft is failing in building with below error message
```
"# github.com/coreos/etcd/raft
raft/logger.go:117: missing ... in args forwarded to print-like function"
```
New parameter check got added the golang to check the function parameter
https://github.com/golang/go/commit/c00603607511701ecc9f56fd82ac528ecf6b8fc6#diff-8fa5b0d6191706747ef5773f895781c9
=> raft: fix logger Panic variadic parameter

etcdserver/api/v3rpc/grpc.go, integration/embed_test.go
Fix
```
=== RUN   TestEmbedEtcd
Write at 0x000001df86d0 by goroutine 711:
github.com/coreos/etcd/embed.(*Config).setupLogging.func1()
/go/src/github.com/coreos/etcd/vendor/google.golang.org/grpc/grpclog/loggerv2.go:68 +0x16c
sync.(*Once).Do()
/usr/local/go/src/sync/once.go:44 +0xe1
github.com/coreos/etcd/embed.(*Config).setupLogging()
```
in gRPC proxy tests.
=> etcdserver/api/v3rpc: remove duplicate gRPC logger set

.travis.yml, tests/semaphore.test.bash
Run e2e and unit tests in Semaphore.
Run rest in Travis.
gRPC proxy tests are failing for no reason, only in Semaphore.
Testing it in Travis, to see if it fixes.
=> tests: switch between Travis and Semaphore

tests/e2e/v3_cipher_suite_test.go
```
../../bin/etcd-30074: 2018-06-19 11:49:12.052662 I | etcdmain: v2 proxy started listening on client requests on "https://localhost:20002"
../../bin/etcd-30083: Error: unknown flag: --cipher-suites
../../bin/etcd-30083: Usage:
../../bin/etcd-30083:   etcd grpc-proxy start [flags]
```
Keep fixing gRPC proxy tests...
=> tests/e2e: do not run cipher suite tests for gRPC proxy

clientv3/watch.go
/cc @jpbetz 
ref. https://github.com/kubernetes/kubernetes/issues/59848 and https://github.com/coreos/etcd/issues/8673 and https://github.com/grpc/grpc-go/issues/2166.
=> clientv3: clarify "WithRequireLeader" for network partition

etcdctl/doc/mirror_maker.md
Fix #9867
mirror_maker doc mentioned "Data under the destination cluster’s mirroring prefix should be treated as read only."
To avoid confusion, read only is being removed and a clear statement mentions that the updated values at destination wont be replicated from destination to origin.
=> docs: mirror_maker, rm readOnly, add uni-directional

Documentation/op-guide/clustering.md
Using SRV discovery with TLS, the SRV record must be in the DNS SAN or clustering will fail.
This is a new requirement and may cause mysterious failures when upgrading from 3.1 to 3.2.  I was only able to fix this in our configuration after reading through #8445; and now I understand the problem it's clear the docs have a hole here.
=> clustering.md:  SRV records in DNS SAN for TLS

raft/raft.go
I meant to do this in #9073, but sent the PR before it was finished.
The last log index is known directly; there is no need to fetch any
entries here.
=> raft: Really avoid scanning raft log in becomeLeader

etcdmain/grpc_proxy.go
This PR proposes backporting support for different certs for the etcd-gRPC proxy. The feature has been already introduced in #8277, but not backported to v3.2.
This PR cherry-picks [`1365f87d4046469bcc94ad03048a52b8b4367bb0`](https://github.com/coreos/etcd/pull/8277/commits/1365f87d4046469bcc94ad03048a52b8b4367bb0), as well as [`e5531a4d54e89338e35994ee1c7e69c87c18d0e8`](https://github.com/coreos/etcd/commit/e5531a4d54e89338e35994ee1c7e69c87c18d0e8), as it introduced some changes in the gRPC-proxy code.
The [`efbee9d8c788e434cae8da03b03ad55f5a6f67c5`](https://github.com/coreos/etcd/pull/8277/commits/efbee9d8c788e434cae8da03b03ad55f5a6f67c5) and [`c5447c2ec91bc349117327de9f7f019cf6cdf1b5`](https://github.com/coreos/etcd/pull/8277/commits/c5447c2ec91bc349117327de9f7f019cf6cdf1b5) commits …
=> etcdmain: backport support for different certs for etcd-gRPC proxy

CHANGELOG-3.2.md
This PR updates the CHANGELOG for version 3.2 to include changes from #9894.
The Changelog seems out-of-loop, as 3.2.23 has already been released. I added a new 3.2.24 entry, however I didn't know release date and Go version.
Let me know should I add or improve something.
/cc @gyuho
=> Update CHANGELOG-3.2 to include changes from #9894

etcdserver/metrics.go, etcdserver/v3_server.go
Current read index warnings are just dumping raw bytes of request ID that nobody understands.
This PR prints out corresponding request IDs to show how much follower falls behind. Also, add `etcd_server_slow_read_indexes_total` metrics to monitor how many read requests are out-of-sync or timed out.
Before
> ignored out-of-date read index response (want [0 1 2 3 5], got [0 1 2 3 6])
After
> ignored out-of-date read index response; local node read indexes queueing up and waiting to be in sync with leader (request ID want 101, got 100)
/cc @SaranBalaji90
=> etcdserver: clarify read index warnings, add metrics

Documentation/op-guide/etcd3_alert.rules
The HTTP metrics have been deprecated and removed. In other places all
the HTTP related alerts have already been removed, this is just a clean
up of the remaining places these were left.
This is a follow up to #9706. Thanks @jolson490 for pointing out that these
alerts were still present here.
@gyuho @metalmatze
=> Documentation/op-guide: Remove HTTP alerts

clientv3/balancer/balancer_test.go, etcdserver/apply_auth.go, etcdserver/server_test.go, mvcc/kvstore_txn.go, mvcc/watcher_test.go, raft/log_test.go, raft/raft_test.go, tests/Dockerfile, tests/e2e/ctl_v3_alarm_test.go, tests/e2e/v3_cipher_suite_test.go
Fedora is too big (550 MB). Reverting back to Ubuntu image (only 350 MB).
=> *: revert back to ubuntu test image, fix "unconvert" linter warnings

embed/etcd.go, etcdmain/etcd.go, etcdserver/config.go, etcdserver/quota.go, etcdserver/server.go
Previous server configuration logs were spread-out, thus hard to read. Move all info logs to `embed.StartEtcd`. This will make test debug easier once we move all integration tests  to use embed package. And just use `memberInitialized` in `embed` package.
Before
> {"level":"info","ts":1531157203.0864909,"caller":"etcdmain/etcd.go:85","msg":"starting etcd","etcd-version":"3.3.0+git","git-sha":"e23853a9e","go-version":"go1.10.3","go-os":"linux","go-arch":"amd64","max-cpu-set":4,"max-cpu-available":4}
> {"level":"info","ts":1531157203.098978,"caller":"etcdserver/config.go:304","msg":"server configuration","name":"default","data-dir":"default.etcd","member-dir":"default.etcd/member","dedicated-wal-dir":"","force-new-cluster":false,"heartbeat-interval":"100ms","election-timeout":"1s","initial-e …
=> *: combine all configuration print logs to embed.StartEtcd

Documentation/upgrades/upgrading-etcd.md
Fix https://github.com/coreos/etcd/issues/9909.
Will backport and request for coreos.com doc sync.
v3.4 has not been released but we are starting tracking changes in https://github.com/coreos/etcd/blob/master/Documentation/upgrades/upgrade_3_4.md.
@philips
=> Documentation/upgrades: update upgrade doc indexes

functional/tester/stresser_key.go, integration/v3_grpc_inflight_test.go
gRPC has moved the transport package to an internal-only directory. This
eliminates direct use of the transport package in the stress test in
favor of the error code from gRPC that represents a connection problem.
https://godoc.org/google.golang.org/grpc/internal/transport is the new
location for the package, which says it's not intended to be imported
directly. Instead, the maintainers suggested to use the code Unavailable
to detect a connection problem.
This change slightly reorganizes the stresser test error handling.
=> Eliminate direct use of the gRPC transport package

etcdserver/metrics.go, etcdserver/raft.go, etcdserver/util.go, mvcc/backend/backend.go, mvcc/backend/batch_tx.go, mvcc/backend/metrics.go, mvcc/kvstore.go, mvcc/metrics.go
Cherry pick of #9761 on release-3.3.
#9761: etcdserver: add "etcd_server_heartbeat_failures_total"
=> Automated cherry pick of #9761

CHANGELOG-3.3.md
Update CHANGELOG-3.3 for #9940
=> CHANGELOG-3.3: update from #9940

clientv3/integration/lease_test.go, clientv3/lease.go
client should update next keepalive send time
even when lease keepalive response queue becomes full.
Otherwise, client sends keepalive request every 500ms
regardless of TTL when the send is only expected to happen
with the interval of TTL / 3 at minimum.
Fix https://github.com/coreos/etcd/issues/9911.
/cc @cfc4n
=> clientv3: fix keepalive send interval when response queue is full

client/client_test.go, client/integration/client_test.go, clientv3/balancer/resolver/endpoint/endpoint.go, clientv3/integration/metrics_test.go, clientv3/lease.go, clientv3/options.go, clientv3/retry_interceptor.go, contrib/raftexample/raft.go, etcdctl/ctlv3/command/printer_simple.go, etcdserver/api/v2auth/auth.go, etcdserver/api/v2auth/auth_test.go, etcdserver/api/v2store/store.go, integration/cluster.go, mvcc/backend/config_default.go, mvcc/key_index.go, pkg/adt/interval_tree.go, pkg/cpuutil/endian.go, proxy/grpcproxy/util.go, test, tests/Dockerfile, tests/e2e/ctl_v3_lease_test.go, tests/revive.toml, wal/repair_test.go, wal/wal_test.go
https://github.com/mgechev/revive is pretty fast adding only 5 seconds to total test runtime.
Masked some of the warnings as TODOs.
=> *: integrate https://github.com/mgechev/revive with fmt tests

etcdserver/metrics.go
Currently, one has to look at server logs manually,
to see what Go version was used to build etcd server.
```
etcd_server_go_version{server_go_version="go1.10.3"} 1
```
@wenjiaswe
=> etcdserver: add "etcd_server_go_version" metric

CHANGELOG-3.2.md
CHANGELOG-3.2: update from #7892
=> CHANGELOG-3.2: update from #7892

Makefile, docs/faq.rst, docs/index.rst, docs/metrics-latest, docs/metrics-v3.1, docs/metrics-v3.2, docs/metrics-v3.3, docs/operate.rst, tools/etcd-dump-metrics/README, tools/etcd-dump-metrics/main.go
Currently, need manual cluster set-up to find all available metrics, thus cannot be documented. Automatically document all available metrics, with embedded etcd for master branch or specified endpoints. This will make tracking metrics changes much easier.
Following PR should initialize `grpc_server_msg_sent_total` for all available RPCs (https://github.com/coreos/etcd/pull/8878). Right now, v3.1 and v3.2 only show the ones that have been requested.
```
etcd-dump-metrics > docs/metrics-latest
goreman start
etcd-dump-metrics -addr http://localhost:2379/metrics > docs/metrics-v3.3
goreman start
etcd-dump-metrics -addr http://localhost:2379/metrics > docs/metrics-v3.2
goreman start
etcd-dump-metrics -addr http://localhost:2379/metrics > docs/metrics-v3.1
```
<br>
Sample rendering (will be …
=> docs: automate metrics list documentation

.words, clientv3/balancer/resolver/endpoint/endpoint.go, clientv3/client.go, clientv3/integration/dial_test.go, clientv3/integration/maintenance_test.go, clientv3/maintenance.go, tests/e2e/ctl_v3_move_leader_test.go
This fixes `clientv3.Dial` function to directly dial a single endpoint. 
Conveniently, it seems this can be fixed by removing special casing logic from clientv3. Previously clientv3 had code in `dialSetupOpts` that would attempt to circumvent the endpoint the balancer had selected when performing a `net.Dial`, but we had accidentally disabled this code path in the grpc new load balancer upgrade (with a condition that always returned false), and attempts to fix it to properly handle all use cases error prone, attempts to fix it could easily be applied it too broadly such that the balancer became unintentionally disabled when it should not. Instead of using that approach, this PR simply dials with a non-load balanced grpc target for all connections established via `clientv3.Dial`.
Fixes …
=> clientv3: Fix maintenance APIs to directly dial grpc endpoints directly

etcdctl/README.md
Document that etcdctl do not support providing value after using \r.
Fixed #9937
=> etcdctl: value should not be provided after \r

MAINTAINERS
Joe has been helping fix lots of bugs and involved
in critical feature design/implementation,
plus leading patch release process for over a year.
Thanks for your excellent work.
@jpbetz @philips
=> MAINTAINERS: add Joe Betz

etcdserver/api/v2discovery/discovery.go
Found using https://go-critic.github.io/overview#boolExprSimplify-ref
=> etcdserver/api/v2discovery: simplify !(x == y) to x != y

contrib/recipes/barrier.go, contrib/recipes/key.go
If we have a named const, it's more readable to use that.
Found using https://go-critic.github.io/overview#namedConst-ref
=> contrib/recipes: use clientv3.NoLease instead of 0

etcdctl/ctlv2/command/util.go
Since syscall.Errno implements net.Error and all cases
are matched sequentially, it's a mistake to put syscall.Errno
case after net.Error since it will never be executed.
This change swaps syscall.Errno case with net.Error
to give that clause chance to execute.
Found using https://go-critic.github.io/overview#caseOrder-ref
=> etcdctl/ctlv2/command: fix type switch case order

raft/raft.go, raft/raft_test.go
We allow multiple in-flight append messages, but prior to this change
the only way we'd ever send them is if there is a steady stream of new
proposals. Catching up a follower that is far behind would be
unnecessarily slow (this is exacerbated by a quirk of CockroachDB's
use of raft which limits our ability to catch up via snapshot in some
cases).
See cockroachdb/cockroach#27983
=> raft: Make flow control more aggressive

clientv3/snapshot/v3_snapshot.go, clientv3/snapshot/v3_snapshot_test.go
=> clientv3: make saved snapshot readable by user only

raft/log.go, raft/node.go, raft/node_test.go, raft/raft.go, raft/raft_test.go
The MaxSizePerMsg setting is now used to limit the size of
Ready.CommittedEntries. This prevents out-of-memory errors if the raft
log has become very large and commits all at once.
I just used the same size limit as we have for MsgApp, although I'd be willing to make it a separate setting if you think it would be useful to configure them separately.
=> raft: Introduce CommittedEntries pagination

Gopkg.lock, bill-of-materials.json, etcdserver/api/v3rpc/grpc.go, etcdserver/api/v3rpc/interceptor.go, etcdserver/etcdserverpb/raft_internal_stringer.go, etcdserver/server.go, vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go, vendor/github.com/grpc-ecosystem/go-grpc-middleware/doc.go, vendor/github.com/grpc-ecosystem/go-grpc-middleware/wrappers.go
This is to improve debuggability of etcd v3. Added a grpc interceptor to log information on incoming requests to etcdserver. 
The log output includes:
- request starting time, 
- request handling latency, 
- remote client info, 
- request key count, 
- request byte size, 
- response key count, 
- response byte size, 
- request content (with value field redacted).
Example log output:
```
./etcdctl put foo bar
{"level":"debug","ts":1533772428.8998141,"caller":"v3rpc/interceptor.go:168","msg":"request stats","start time":1533772428.89934,"time spent":0.000403816,"remote":"127.0.0.1:46300","response type":"/etcdserverpb.KV/Put","request count":1,"request size":10,"response count":0,"response size":28,"request content":"key:\"foo\" value_size:3 "}
```
Logging is enable by --debug flag.
Fixes …
=> etcdserver: add grpc interceptor to log info on incoming request to etcdserver

etcdserver/metrics.go, etcdserver/server.go
```
etcd_server_id{server_id="8e9e05c52164694d"} 1
```
Useful for automating membership change operations,
no need to run "endpoint status" or "member list"
command to get member IDs.
Also, useful for "etcd_network" metrics with "To/From" labels.
Will update http://etcd.readthedocs.io/en/latest and operation docs in following PRs.
ref. https://github.com/coreos/etcd/issues/9438
=> etcdserver: add "etcd_server_id" metric

bill-of-materials.json, etcdserver/api/v3rpc/grpc.go, etcdserver/api/v3rpc/interceptor.go, etcdserver/etcdserverpb/raft_internal_stringer.go, etcdserver/server.go, vendor/github.com/grpc-ecosystem/go-grpc-middleware/chain.go, vendor/github.com/grpc-ecosystem/go-grpc-middleware/doc.go, vendor/github.com/grpc-ecosystem/go-grpc-middleware/wrappers.go
Cherry pick of #9990 on release-3.3.
#9990: etcdserver: add grpc interceptor to log info on incoming
=> Automated cherry pick of #9990

etcdserver/api/rafthttp/http.go, etcdserver/api/rafthttp/metrics.go, etcdserver/api/rafthttp/snapshot_sender.go, etcdserver/api/snap/db.go, etcdserver/api/snap/metrics.go
v3 snapshots are large and critical operations, often affecting the cluster availabilities. Currently, we do not have any metrics around v3 snapshots. Only way to debug is looking at server logs after something bad happens.
<br>
```
etcd_snap_db_fsync_duration_seconds_count
etcd_snap_db_save_total_duration_seconds_bucket
```
to monitor v3 snapshot save operations on local node.
<br>
```
etcd_network_snapshot_send
etcd_network_snapshot_send_failures
etcd_network_snapshot_send_total_duration_seconds
etcd_network_snapshot_receive
etcd_network_snapshot_receive_failures
etcd_network_snapshot_receive_total_duration_seconds
```
to monitor v3 snapshot operations between remote peers.
Distribution would be:
```
0.1 second or more
...
25.6 seconds or more
51.2 seconds or more
```
<br>
This records …
=> *: add v3 snapshot metrics (fsync, network)

etcdserver/api/v3rpc/interceptor.go
Check log level before generating and writing log info.  If debug level is not enabled, skip logUnaryRequestStats() to avoid potential performance degradation.
/cc @jpbetz @gyuho
=> etcdserver/api/v3rpc/interceptor: add log level checking

etcdserver/api/v3rpc/interceptor.go, etcdserver/etcdserverpb/raft_internal_stringer.go
Cherry pick of #9990 to release-3.2.
This is to improve debuggability of etcd release-3.2. Added a grpc interceptor to log information on incoming requests to etcdserver.
During backporting, the following two dependencies are removed from the original PR:
1. removed dependency on zap logger. Use capnslog for logging.
2. removed dependency on grpc_middleware. Interceptors are chained manually instead.
This backporting also includes #10021. If debug level is disabled, skip logUnaryRequestStats() to avoid potential performance degradation.
=> etcdserver: cherry pick of #9990 to release-3.2

etcdserver/api/v3rpc/grpc.go, integration/embed_test.go
Cherry pick of #9861 'etcdserver/api/v3rpc: remove duplicate gRPC logger set'  to release-3.3.
This PR resolves a race condition, backporting will add general stability and resolve failures while testing with `race`.
=> etcdserver: cherry-pick #9861 to release-3.3

etcdctl/ctlv3/command/get_command.go
The current error is incorrect. Providing a similar one to the del
command.
=> etcdctl: fix get command error when no arg provided

etcdserver/api/v3rpc/interceptor.go, etcdserver/etcdserverpb/raft_internal_stringer.go
Cherry pick of #9990 to release-3.1.
This is to improve debuggability of etcd release-3.1. Added a grpc interceptor to log information on incoming requests to etcdserver.
During backporting, the following two dependencies are removed from the original PR:
1. removed dependency on zap logger. Use capnslog for logging.
2. removed dependency on grpc_middleware. Interceptors are chained manually instead.
This backporting also includes #10021. If debug level is disabled, skip logUnaryRequestStats() to avoid potential performance degradation. 
/cc @gyuho @jpbetz
=> etcdserver: cherry pick of #9990 to release 3.1

clientv3/doc.go
0c5bcd5d8094ef64e8377753d48c038327a266d6 updated error handling for `ErrEmptyKey` but missed the godoc.
=> clientv3/doc: Update error handling godoc

etcdctl/README.md
Several RPC references in readme with memberlist only hyperlinked,
and since it's linked with line numbers it's not pointing to a
desired ref now. Remove the link to make it consistent and correct.
=> etcdctl: fix small inconsistency with RPC ref

etcdserver/api/v3rpc/grpc.go
Previously, only display the one that has been requested at least once.
Now it shows all metrics, as we do in v3.3 and v3.4+.
```
grpc_server_started_total{grpc_method="Alarm",grpc_service="etcdserverpb.Maintenance",grpc_type="unary"} 0
grpc_server_started_total{grpc_method="AuthDisable",grpc_service="etcdserverpb.Auth",grpc_type="unary"} 0
grpc_server_started_total{grpc_method="AuthEnable",grpc_service="etcdserverpb.Auth",grpc_type="unary"} 0
grpc_server_started_total{grpc_method="Authenticate",grpc_service="etcdserverpb.Auth",grpc_type="unary"} 0
grpc_server_started_total{grpc_method="Compact",grpc_service="etcdserverpb.KV",grpc_type="unary"} 0
grpc_server_started_total{grpc_method="Defragment",grpc_service="etcdserverpb.Maintenance",grpc_type="unary"} 0 …
```
=> etcdserver/api/v3rpc: display all registered gRPC metrics at start (v3.2)

etcdserver/api/v3rpc/grpc.go
Previously, only display the one that has been requested at least once.
Now it shows all metrics, as we do in v3.3 and v3.4+.
```
grpc_server_started_total{grpc_method="Alarm",grpc_service="etcdserverpb.Maintenance",grpc_type="unary"} 0
grpc_server_started_total{grpc_method="AuthDisable",grpc_service="etcdserverpb.Auth",grpc_type="unary"} 0
grpc_server_started_total{grpc_method="AuthEnable",grpc_service="etcdserverpb.Auth",grpc_type="unary"} 0
grpc_server_started_total{grpc_method="Authenticate",grpc_service="etcdserverpb.Auth",grpc_type="unary"} 0
grpc_server_started_total{grpc_method="Compact",grpc_service="etcdserverpb.KV",grpc_type="unary"} 0
grpc_server_started_total{grpc_method="Defragment",grpc_service="etcdserverpb.Maintenance",grpc_type="unary"} 0 …
```
=> etcdserver/api/v3rpc: display all registered gRPC metrics at start (v3.1)

etcdserver/v3_server.go
"read index" doesn't tell much about the root cause.
Most likely, the local follower node is having slow
network, thus timing out waiting to receive read
index response from leader.
=> etcdserver: clarify read index wait timeout warnings

etcdserver/api/rafthttp/peer_status.go
"became inactive" is not a clear warning, when what's actually happening is failure to send HTTP requests.
=> etcdserver/api/rafthttp: clarify "became inactive" warning

.travis.yml, Makefile, clientv3/integration/lease_test.go, clientv3/lease.go, etcdserver/api/v2http/client.go, etcdserver/config_test.go, functional/agent/server.go, integration/cluster.go, pkg/testutil/leak.go, proxy/httpproxy/reverse_test.go
Also switching to go module in following PRs.
=> *: use Go 1.11 for tests

rafthttp/http.go, rafthttp/metrics.go, rafthttp/snapshot_sender.go, snap/db.go, snap/metrics.go
Cherry pick of #9997 on release-3.1.
#9997: etcdserver/api/snap: add v3 snapshot fsync metrics
=> Automated cherry pick of #9997

tools/etcd-dump-db/README.md
Small doc cleanup `iterate-bucket` expects [bucket name] vs --bucket=name.
ref: https://github.com/etcd-io/etcd/issues/9931
=> tools/etcd-dump-db: fix iterate-bucket example.

clientv3/watch.go, proxy/grpcproxy/watch.go
V3 watches currently block indefinitely on error when using the grpc proxy.
This PR Fixes #10008
1. Start etcd cluster
2. Add a role and enable auth
3. Start a grpc proxy to the etcd cluster
4. Run `etcdctl watch foo --endpoint=<grpc-endpoint>`
The watch will hang indefinitely with no errors returned. The error, in this case, is `user name is empty`
* ***Return reason to client when server cancels watch***
This change allows Watch users to retrieve the cancel reason when a
watch is canceled by the server. Additionally WatchResponses with
closeErr set now have Canceled set true which is in line with the
documentation for the Canceled field.
* ***return errors to client during watch create***    
Now returns errors from checkPermissionForWatch() via the CancelReason
field. This allows …
=> Improve watch error reporting when using grpc proxy

Documentation/op-guide/configuration.md
This commit annotates the `--logger` flag to let users know that it is not available in versions 3.3.x or later.
=> Documentation: Annotate --logger flag

Documentation/v2/metrics.md
Typo fix: particlarly -> particularly
=> Documentation/v2/metrics.md: Fix a typo

raft/node.go, raft/rawnode_test.go
The previous logic was erroneously setting Ready.MustSync to true when
the hard state had not changed because we were comparing an empty hard
state to the previous hard state. In combination with another misfeature
in CockroachDB (unnecessary writing of empty batches), this was causing
a steady stream of synchronous writes to disk.
=> raft: fix Ready.MustSync logic

contrib/raftexample/kvstore.go
contrib/raftexample: use Rlock instead of Lock in getSnapshot function.
https://github.com/etcd-io/etcd/blob/ab544f2dde1eab69cc555a609dc259291e532544/contrib/raftexample/kvstore.go#L97-L101
`json.Marshal` is an readonly operation.
Fixes #10090
=> bugfix: use Rlock instead of Lock in raftexample.

clientv3/snapshot/v3_snapshot.go
Add snapshot file integrity verification in snapshot status.  If the file is corrupted, user should be notified.
fix: #10108 
```
etcdctl snapshot status corrupt_db/backup.db
Error: Database corrupted! 14 errors found.
page 961: already freed
page 962: already freed
page 1347: already freed
page 1442: already freed
page 1760: already freed
page 2023: already freed
page 2033: already freed
page 969: unreachable unfreed
page 970: unreachable unfreed
page 1355: unreachable unfreed
page 1450: unreachable unfreed
page 1768: unreachable unfreed
page 2031: unreachable unfreed
page 2041: unreachable unfreed
```
=> clientv3: add db integrity check in snapshot status

Documentation/dev-guide/api_grpc_gateway.md
=> Documentation/dev-guide: add gRPC-gateway example of txn target VERSION syntax.

clientv3/integration/kv_test.go, clientv3/integration/lease_test.go, clientv3/integration/leasing_test.go, clientv3/integration/network_partition_test.go, etcdserver/api/v3rpc/rpctypes/error.go, etcdserver/api/v3rpc/util.go, etcdserver/errors.go, etcdserver/metrics.go, etcdserver/server.go, etcdserver/v3_server.go, integration/v3_lease_test.go
The read request will block the following read request until the context timeout if meet network partition, and this PR will drop the read request if the leader is changed. ref:  https://github.com/etcd-io/etcd/pull/9567 https://github.com/etcd-io/etcd/issues/9566
=> server: drop read request if the leader is changed

etcdctl/ctlv3/command/member_command.go
This PR refers to issue #10120
Maintain existing error message for not-enough-args
Add "too many args" if too many args
Add more helpful error message if v2 syntax was used
New output:
```
sauer@host:~/dev/etcd$ ./bin/etcdctl --endpoints http://localhost:5001 member add
Error: member name not provided.
sauer@host:~/dev/etcd$ ./bin/etcdctl --endpoints http://localhost:5001 member add node2 node2
Error: too many arguments
sauer@host:~/dev/etcd$ ./bin/etcdctl --endpoints http://localhost:5001 member add node2 http://localhost:6002
Error: too many arguments, did you mean "--peer-urls http://localhost:6002"
sauer@host:~/dev/etcd$ ./bin/etcdctl --endpoints http://localhost:5001 member add http://localhost:6002 node2
Error: too many arguments, did you mean "--peer-urls http://localhost:6002"
``` …
=> etcdctl: More helpful error handling in member add

etcdctl/ctlv3/command/snapshot_command.go
Cherry pick of #10109 to release-3.2.
Add snapshot file integrity verification when querying snapshot status. If the snapshot file is corrupted, querying exits with error.
/cc @gyuho @xiang90 @jpbetz
=> etcdctl: cherry pick of #10109 to release-3.2

etcdctl/ctlv3/command/snapshot_command.go
Cherry pick of #10109 to release-3.1.
Add snapshot file integrity verification when querying snapshot status. If the snapshot file is corrupted, querying exits with error.
/cc @gyuho @xiang90 @jpbetz
=> etcdctl: cherry pick of #10109 to release-3.1

CHANGELOG-3.4.md
Update CHANGELOG-3.4 from #10109.
=> CHANGELOG-3.4: update from #10109

CHANGELOG-3.3.md
CHANGELOG-3.3: update from #9990. 
This is already added to CHANGELOG-3.1, 3.2 and 3.4, but missing in CHANGELOG-3.3.
/cc @gyuho
=> CHANGELOG-3.3: update from #9990

auth/range_perm_cache_test.go, auth/store_test.go
auth: adds tests for uncovered auth funcs
Coverage 68.5% -> 76.5%
Issue #9734
=> 9734 improve auth coverage

raft/node.go, raft/node_test.go, raft/rawnode.go, raft/rawnode_test.go, raft/util.go
In #9982, a mechanism to limit the size of `CommittedEntries` was
introduced. The way this mechanism works was that it would load
applicable entries (passing the max size hint) and would emit a
`HardState` whose commit index was truncated to match the limitation
applied to the entries. Unfortunately, this was subtly incorrect
when the user-provided `Entries` implementation didn't exactly
match what Raft uses internally. Depending on whether a `Node` or
a `RawNode` was used, this would either lead to regressing the
HardState's commit index or outright forgetting to apply entries,
respectively.
Asking implementers to precisely match the Raft size limitation
semantics was considered but looks like a bad idea as it puts
correctness squarely in the hands of downstream users. Instead, this
PR …
=> raft: fix correctness bug in CommittedEntries pagination

tools/benchmark/cmd/util.go
allow client to setup TLS with cluster members, without the client having to offer TLS authentication itself
fixes #10142
=> benchmark: util.go

tools/etcd-dump-metrics/install_windows.go
When building tools on Win,it shows `.\main.go:68:12: assignment mismatch: 2 variables but 1 values`.The reason is the return variables not match the calling from `main.go` and i try to fix it.
=> tools: fix building failures on Win

CHANGELOG-3.4.md, clientv3/client.go, clientv3/config.go
We should allow etcd client use all of the available keepalive
client parameters as documented in this link,
https://godoc.org/google.golang.org/grpc/keepalive#ClientParameters
Currently in the etcd, by default PermitWithoutStream is set to
false, and user has no way to override it.
On the server side, we explicitely setting EnforcementPolicy
PermitWithoutStream to false and don't provide option to override it
to user but on the client side we should allow this option as
provided by the grpc.
=> clientv3: let etcd client use all available keepalive ClientParams

clientv3/config.go
=> clientv3: fix goword checking in config.go

.words
whitelist keyword 'unfreed' for goword. It is from the bbolt error message, used by error message in clientv3/snapshot.
=> words: whitelist unfreed

clientv3/concurrency/mutex.go
Convenient invariant:
- if werr == nil then lock is supposed to be locked at the moment.
While we could not be confident in stronger invariant ('is exactly locked'),
it were inconvenient that previous code could return `werr == nil` when
it released Lock.
It could happen when ctx is canceled/timeouted exactly after waitDeletes
successfully returned werr == nil and before `<-ctx.Done()` checked.
While such situation is very rare, it is still possible.
fixes #10111
=> clientv3/concurrency.Mutex.Lock() - preserve invariant

clientv3/concurrency/mutex.go
Cherry pick of #10153 on release-3.3.
#10153: clientv3: concurrency.Mutex.Lock() - preserve invariant
=> clientv3: automated cherry pick of #10153 to release-3.3

clientv3/concurrency/mutex.go
Cherry pick of #10153 on release-3.2.
#10153: clientv3: concurrency.Mutex.Lock() - preserve invariant
=> clientv3: automated cherry pick of #10153 to release-3.2

clientv3/concurrency/mutex.go
Cherry pick of #10153 on release-3.1.
#10153: clientv3: concurrency.Mutex.Lock() - preserve invariant
=> clientv3: automated cherry pick of #10153 to release 3.1

etcdserver/api/etcdhttp/metrics.go, integration/metrics_test.go
With https://github.com/etcd-io/etcd/pull/10155, I am trying to improve server side metrics.
People use `/health` endpoint heavily to monitor etcd server status.
Helpful to have server-side metrics to tell how many health check have been made, and how many of which were marked "failed".
=> etcdserver: add "etcd_server_health_success/failures"

etcdserver/api/rafthttp/metrics.go, etcdserver/api/rafthttp/probing_status.go, etcdserver/api/rafthttp/transport.go, etcdserver/api/rafthttp/transport_test.go
This PR adds another probing routine to monitor the connection
for Raft message transports. Previously, we only monitored
snapshot transports.
In our production cluster, we found one TCP connection had >8-sec
latencies to a remote peer, but "etcd_network_peer_round_trip_time_seconds"
metrics shows <1-sec latency distribution, which means etcd server
was not sampling enough while such latency spikes happen
outside of snapshot pipeline connection.
Reworked on https://github.com/etcd-io/etcd/pull/10022.
=> rafthttp: probe all raft transports

etcdserver/cluster_util.go
Only leader can decide cluster version.
Clarify the logging that this local node is the leader.
=> etcdserver: clear message in cluster version decision

integration/metrics_test.go
integration: fix bug in TestMetricsHealth
TestMetricsHealth check the value of etcd_server_health_success, which returns "The total number of successful health checks", if it's not "1" then the test fails. However, the test runs [three times with 1, 2, 4 CPUs by default](https://github.com/etcd-io/etcd/blob/d5c93a7b0b5c434bf87d8de4d55d5a3b4ed4ed64/test#L117), so on the second run, value of etcd_server_health_success is 2 and on the third run, value of etcd_server_health_success is 3, which causes TestMetricsHealth test fail on the second and third time.
In the fix, I make it to check the value of  etcd_server_health_failure instead of etcd_server_health_succuess. 
Fixes #10172 
@gyuho
=> integration: fix bug in TestMetricsHealth

contrib/raftexample/raft.go
The error message is different to the condition it checks for.
This PR modifies the error message accordingly.
Closes #9717.
=> raftexample: Fix publish snapshot error message

Documentation/dev-guide/api_grpc_gateway.md
Documentation: Add the -N option to curl for the watch example to disable buffering
I initially thought that the watch example wasn't working, but occasionally I'd receive a block of multiple responses.  When I used the -N option to curl to disable buffering, the watch results come back immediately.
=> Add the -N option to curl for the watch example to disable buffering

contrib/raftexample/raft.go, raft/README.md, raft/doc.go, raft/node.go, raft/node_test.go, raft/raft.go, raft/raft_test.go, raft/rafttest/node.go, raft/rawnode.go, raft/rawnode_test.go
The suggested pattern for Raft proposals is that they be retried
periodically until they succeed. This turns out to be an issue
when a leader cannot commit entries because the leader will continue
to append re-proposed entries to its log without committing anything.
This can result in the uncommitted tail of a leader's log growing
without bound until it is able to commit entries.
This change add a safeguard to protect against this case where a
leader's log can grow without bound during loss of quorum scenarios.
It does so by introducing a new, optional `MaxUncommittedEntries`
configuration. This config limits the max number of uncommitted
entries that may be appended to a leader's log. Once this limit
is exceeded, proposals will begin to return ErrProposalDropped
errors.
See …
=> raft: provide protection against unbounded Raft log growth

Documentation/etcd-mixin/README.md, Documentation/etcd-mixin/mixin.libsonnet, Documentation/etcd-mixin/test.yaml
Currently the EtcdInsufficientMembers alert fires, when more than (X/2)-1
instances are unavailable. This fixes it to fire at the correct limit of (X-1)/2
unavailable instances and $value now contains the number of available instances
instead of unavailable ones.
=> etcd-mixin: Fix EtcdInsufficientMembers alerting

mvcc/backend/backend_test.go
mvcc/backend: use the backend create by snapshot instead of origin one in tests
fixes #10177
=> bugfix: use the backend create by snapshot instead of origin one in tests

mvcc/backend/backend.go
https://github.com/etcd-io/etcd/blob/7a759c18d294698f537f8be91927354818a71e51/mvcc/backend/backend.go#L402-L412
1. function `(*backend). unsafeBegin` has defined, which function is equal to code in line 402-409.
2. readTx is created by `(*backend). unsafeBegin`
changed like below:
```golang
b.batchTx.tx = b.unsafeBegin(true)
b.readTx.reset()
b.readTx.tx = b.unsafeBegin(false)
```
It's just code format optimization **not bugs**.
=> mvcc/backend: code format optimization

raft/node_test.go, raft/raft.go, raft/raft_paper_test.go, raft/raft_test.go, raft/rawnode_test.go, raft/util.go
The previous code was using the proto-generated `Size()` method to
track the size of an incoming proposal at the leader. This includes
the Index and Term, which were mutated after the call to `Size()`
when appending to the log. Additionally, it was not taking into
account that an ignored configuration change would ignore the
original proposal and append an empty entry instead.
As a result, a fully committed Raft group could end up with a non-
zero tracked uncommitted Raft log counter that would eventually hit
the ceiling and drop all future proposals indiscriminately. It would
also immediately imply that proposals exceeding the threshold alone
would get refused (as the "first uncommitted proposal" gets special
treatment and is always allowed in).
Track only the size of the payload …
=> raft: fix bug in unbounded log growth prevention mechanism

OWNERS, raft/OWNERS
We need OWNERs file to integrate with github bot. Currently, due to github outage, all webhooks are disabled. Once github recovers, will experiment actual Prow jobs using GCP etcd-development project.
https://github.com/etcd-io/etcd/issues/10192
/cc @jpbetz @wenjiaswe @jingyih
=> OWNERS: experiment

build, test
Shellcheck [v0.5.0](https://github.com/koalaman/shellcheck/releases/tag/v0.5.0) was released in May. This PR squelches a few errors related to SC2230 which are now reported with the latest shellcheck version.
```
'shellcheck' started at Fri Oct 26 07:26:01 EDT 2018
shellcheck checking failed:
build:18:5: note: which is non-standard. Use builtin 'command -v' instead. [SC2230]
test:237:7: note: which is non-standard. Use builtin 'command -v' instead. [SC2230]
[...]
```
ref: [SC2230](https://github.com/koalaman/shellcheck/wiki/SC2230)
=> *: resolve shellcheck errors.

Documentation/op-guide/gateway.md
doc: Add the missing `start` subcommand.
=> Documentation/op-guide: fix error command to start gateway

pkg/flags/flag_test.go
Fix https://github.com/etcd-io/etcd/issues/10208.
/cc @sudeeshjohn
=> pkg/flags: fix "TestSetFlagsFromEnvParsingError"

raft/node.go
Update godocs for node interface, explaining the behavior of ReportSnapshot and Propose.
This PR is triggered in response to #10225.
=> raft: Explain ReportSnapshot and Propose behavior

raft/log.go, raft/node_test.go, raft/raft.go
Prior to this change, MaxSizePerMsg was used both to cap the total byte size of
entries in messages as well as the total byte size of entries passed through
CommittedEntries in the Ready struct. This change adds a new Config parameter
MaxCommittedSizePerReady which defaults to MaxSizePerMsg and contols the second
of above descibed settings.
This enables resolution of https://github.com/cockroachdb/cockroach/issues/31511
=> raft: separate MaxCommittedSizePerReady config from MaxSizePerMsg

raft/storage_test.go
There is no test coverage：
https://github.com/etcd-io/etcd/blob/ee9dcbca0d89dc563c9e6bc725fab0c6f21d689b/raft/storage.go#L250-L253
add case:
```
{
[]pb.Entry{{Index: 1, Term: 1}, {Index: 2, Term: 2}},
nil,
[]pb.Entry{{Index: 3, Term: 3}, {Index: 4, Term: 4}, {Index: 5, Term: 5}},
},
```
=> raft:  add a test case in TestStorageAppend

etcdserver/api/membership/cluster.go, etcdserver/api/membership/metrics.go, etcdserver/server.go, tests/e2e/etcd_release_upgrade_test.go, tests/e2e/metrics_test.go
This will be useful for https://github.com/etcd-io/etcd/issues/7308 (rollback support).
We can monitor local `etcd_cluster_version` metrics from each node, to decide whether the downgrade/upgrade target version has been agreed.
/cc @wenjiaswe @jpbetz
=> etcdserver/*: add "etcd_cluster_version" metric

tools/etcd-dump-db/backend.go, tools/etcd-dump-db/main.go
By default, wait up to 10 seconds to obtain flocks.
Fix https://github.com/etcd-io/etcd/issues/10089.
=> tools/etcd-dump-db: add "--timeout" flag

MAINTAINERS
etcd maintainers and community,
I would like to offer my service as a maintainer of the etcd project. I consider the role a great honor and will work very hard to not only grow the community but also to ensure the health of the project. Over the past 2 years, I have been a top 7 contributor and have recently shifted my career to etcd fulltime. Thank you for your consideration.
/cc @heyitsanthony @philips @fanminshi @gyuho @mitake @jpbetz @xiang90 
ref: https://github.com/etcd-io/etcd/graphs/contributors?from=2016-11-20&to=2018-11-14&type=c
=> MAINTAINERS: add Sam Batschelet

raft/raft.go, raft/raft_test.go
The leader perpetually kept itself in ProgressStateProbe even though of
course it has perfect knowledge of its log. This wasn't usually an issue
because it also doesn't care about its own Progress, but it's better to
keep this data correctly maintained, especially since this is part of
raft.Status and thus becomes visible to applications using the Raft
library.
(Concretely, in CockroachDB we use the Progress to inform log
truncations).
=> raft: ensure leader is in ProgressStateReplicate

raft/util.go
A zero RejectHint on MsgAppResp is still used, and so should be
reflected in the message description.
=> raft: print RejectHint of zero on MsgAppResp

Documentation/op-guide/configuration.md, embed/config.go, embed/etcd.go, etcdmain/config.go, etcdmain/help.go, etcdserver/backend.go, etcdserver/config.go
The default backend batch interval is 100ms, which is too long for a fast local ssd. It means that a SSD will be almost idle for 100ms for another fdatasync to happen. 
Making backend related configuration to be configurable through flags.
=> *: add flags to setup backend related config

Documentation/op-guide/configuration.md
```
**Available from v3.4**
+ Specify 'zap' for structured logging or 'capnslog'.
+ default: capnslog
+ env variable: ETCD_LOGGER
+ Specify 'stdout' or 'stderr' to skip journald logging even when running under systemd, or list of comma separated output targets.
+ default: default
+ env variable: ETCD_LOG_OUTPUT
```
Error writing in environment variable `ETCD_LOG_OUTPUT`, which should be `ETCD_LOG_OUTPUTS`.
=> Documentation/op-guide: fix typo.

raft/rawnode.go, raft/rawnode_test.go, raft/status.go
Calls to Status can be frequent and currently incur three heap
allocations, but often the caller has no intention to hold on to the
returned status.
Add StatusWithoutProgress and WithProgress to allow avoiding heap
allocations altogether. StatusWithoutProgress does what's on the
tin and additionally returns a value (instead of a pointer) to
avoid the associated heap allocation. By not returning a Progress
map, it avoids all other allocations that Status incurs.
To still introspect the Progress map, add WithProgress, which
uses a simple visitor pattern.
Add benchmarks to verify that this is indeed allocation free.
```
BenchmarkStatusProgress/members=1/Status-8                  5000000    353 ns/op        784 B/op    3 allocs/op
BenchmarkStatusProgress/members=1/Status-example-8 …
```
=> raft: add (*RawNode).WithProgress

raft/raft.go, raft/raft_snap_test.go
When a follower requires a snapshot and the snapshot is sent at the
committed (and last) index in an otherwise idle Raft group, the follower
would previously remain in ProgressStateProbe even though it had been
caught up completely.
In a busy Raft group this wouldn't be an issue since the next round of
MsgApp would update the state, but in an idle group there's nothing
that rectifies the status (since there's nothing to append or update).
The reason this matters is that the state is exposed through
`RaftStatus()`. Concretely, in CockroachDB, we use the Raft status to
make sharding decisions (since it's dangerous to make rapid changes
to a fragile Raft group), and had to work around [this problem].
[this problem]: https://github.com/cockroachdb/cockroach/blob/91b11dae416f3d9b55fadd2a4b096e9 …
=> raft: enter ProgressStateReplica immediately after snapshot

etcdmain/etcd.go
remove duplicate GetLogger, it always call GetLogger and assign to lg.
=> refactor(*): remove duplicate GetLogger

proxy/grpcproxy/cache/store.go
use set instead of slice as interval value
fixes #10326
=> grpcproxy: fix memory leak

.travis.yml, proxy/grpcproxy/cache/store.go
Cherry-pick https://github.com/etcd-io/etcd/commit/d88f686a91a57e46db742e2340c18212a1f38ab4.
=> [Cherry pick 3.3] grpcproxy: fix memory leak

raft/raft.go, raft/raft_test.go
raft: set leader id to none when becomePreCandidate.
When a follower election timeout, it should mark leader to none (so that old leader is not in lease).  Current implementation of Pre-Vote ignore this, which may cause [wrong judgement ](../blob/master/raft/raft.go#L710).
=>  raft: introduce/fix TestPreVoteWithCheckQuorum

.gitignore
Ignore build result and runtime files of raftexample
=> gitignore: ignore build result and runtime files of raftexample

clientv3/client.go, clientv3/retry_interceptor.go, clientv3/utils.go
We should not introduce dependency just for the 3 lines of code.
/cc @jpbetz @hexfusion
=> clientv3: remove "JitterUp" imports

pkg/testutil/recorder.go
There are no empty lines between some functions, which is strange.
https://github.com/etcd-io/etcd/blob/daec0718136dab067da4f3d2872e76d2893bcd48/pkg/testutil/recorder.go#L42-L70
=> pkg/testutil: add blankline between two functions

etcdserver/api/v2v3/server.go, etcdserver/apply_v2.go
add missing lg assignment.
There are two modifications：
first:
https://github.com/etcd-io/etcd/blob/fde617d2dc73c418ace7e4aab535b5dd1503f6f3/etcdserver/apply_v2.go#L40-L42
`applierV2store` has `lg` field
https://github.com/etcd-io/etcd/blob/fde617d2dc73c418ace7e4aab535b5dd1503f6f3/etcdserver/apply_v2.go#L44-L48
second:
https://github.com/etcd-io/etcd/blob/fde617d2dc73c418ace7e4aab535b5dd1503f6f3/etcdserver/api/v2v3/server.go#L46-L48
`v2v3Server` has `lg` field
https://github.com/etcd-io/etcd/blob/fde617d2dc73c418ace7e4aab535b5dd1503f6f3/etcdserver/api/v2v3/server.go#L39-L44
=> etcdserver: add missing lg assignment.

etcdserver/api/v2store/metrics.go
use camel case instead of snake case.
=> api/v2store:  use camel case instead of snake case.

etcdserver/api/v2store/event_history.go, etcdserver/api/v2store/node.go, etcdserver/api/v2store/watcher_hub.go, etcdserver/api/v2v3/store.go
Extra parentheses are not necessary.
=> etcdserver: remove redundant parentheses.

Documentation/op-guide/configuration.md
Update the docs with supported env vars.
Setting ETCD_BCRYPT_COST causes etcd to throw
```
pkg/flags: unrecognized environment variable ETCD_BCRYPT_COST=someval
```
The ohter env vars are valid to set.
=> fix etcd-io#10381 - update docs

CHANGELOG-3.3.md, Documentation/dev-guide/api_grpc_gateway.md, Documentation/op-guide/authentication.md, Documentation/op-guide/configuration.md, auth/store.go, tests/e2e/v3_curl_test.go
When client-cert-auth is enabled gRPC-gateway proxy request to etcd server will use the CN in client server cert if populated. We should not use this for authentication. In general gRPC-gateway does not support CN authentication and we also should document as such.
The check provided in this PR is based on headers send from gRPC-Gateway
https://github.com/grpc-ecosystem/grpc-gateway/blob/8976e602c518589cb6d40aca52a7dd8aef83706a/runtime/context.go#L183#
/cc @gyuho @mitake
=> *: disable CommonName auth for gRPC-gateway

Documentation/dl_build.md
The documentation recommends using `etcdctl` to verify that etcd has
been built correctly, but the `go get` command provided does not install
it. This changes it so that it does, and also clarifies terminology
('using `go get`', referring to the command used to install it, rather
than 'using `$GOPATH`').
=> docs: install etcdctl with `go get` as well

etcdserver/api/v2auth/auth_requests.go
remove defer in loop.
There are defer call in loop, 
https://github.com/etcd-io/etcd/blob/f0aeb705ceb1daca072af0a54be6b43c87bbc23e/etcdserver/api/v2auth/auth_requests.go#L33-L36
`defer cancel`  does not execute until the function returns, which is not appropriate, because `s.server.Do` is not an async call. It should call them at the end of each loop iteration.
=> api/v2auth: remove defer in loop.

etcdserver/api/rafthttp/fake_roundtripper_test.go
https://github.com/etcd-io/etcd/blob/f0aeb705ceb1daca072af0a54be6b43c87bbc23e/etcdserver/api/rafthttp/fake_roundtripper_test.go#L31-L32
`req.Cancel` should be removed. There are two reasons:
**first**:
[http - GoDoc](https://godoc.org/net/http#Request)
```
type Request struct {
...
// Cancel is an optional channel whose closure indicates that the client
// request should be regarded as canceled. Not all implementations of
// RoundTripper may support Cancel.
//
// For server requests, this field is not applicable.
//
// Deprecated: Use the Context and WithContext methods
// instead. If a Request's Cancel field and context are both
// set, it is undefined whether Cancel is respected.
Cancel <-chan struct{}
...
```
As mentioned above, `req.Cancel` is deprecated. 
**second**: …
=> api/rafthttp: remove deprecated req.Cancel.

etcdserver/v3_server.go
If authentication is enabled, then changing permissions of a role while there are active readers/writers authenticated with the role can cause Etcd nodes consume 100% of CPU.
Consider the following function:
```Golang
// doSerialize handles the auth logic, with permissions checked by "chk", for a serialized request "get". Returns a non-nil error on authentication failure.
func (s *EtcdServer) doSerialize(ctx context.Context, chk func(*auth.AuthInfo) error, get func()) error {
for {
ai, err := s.AuthInfoFromCtx(ctx)
if err != nil {
return err
}
if ai == nil {
// chk expects non-nil AuthInfo; use empty credentials
ai = &auth.AuthInfo{}
}
if err = chk(ai); err != nil {
if err == auth.ErrAuthOldRevision {
continue
}
return err
}
// fetch response for serialized request
get()
//  empty …
```
=> Remove infinite loop in doSerialize

tests/e2e/etcd_process.go
missing return error when call `os.Remove`
https://github.com/etcd-io/etcd/blob/1e42503bea073b559fca682219242a801cf4d587/tests/e2e/etcd_process.go#L107-L121
=> tests/e2e: add missing return error.

auth/store.go
cherry-pick bf9d0d8291dc71ecbfb2690612954e1a298154b2
=> [Cherry-pick 3.2] auth: disable CommonName auth for gRPC-gateway

CHANGELOG-3.3.md
=> CHANGELOG: revert discovery-srv-name feature from 3.3.11

etcdctl/ctlv3/command/watch_command.go
Don't panic if command is given in interactive mode, give a nice error
message instead.
Before:
```sh
$ ./bin/etcdctl watch -i
<hit return>
panic: runtime error: index out of range
goroutine 1 [running]:
etcdctl/ctlv3/command.watchInteractiveFunc(...)
etcd/etcdctl/ctlv3/command/watch_command.go:104 ...
```
After:
```sh
$ ./bin/etcdctl watch -i
<hit return>
Invalid command:  (watch and progress supported)
foo
Invalid command foo (only support watch)
```
=> etcdctl: fix interactive mode panic

embed/config.go, embed/config_logging.go
Signed-off-by: nolouch <nolouch@gmail.com>
In order to improve the ELK system, we want to use a custom zap encoder or more features in `zapcore`.  So we need a custom builder to build the zap logger in the embed config. This PR added
a `ZapLoggerBuilder` to build a custom zap logger. I think some users may have the same needs, so I hope we can merge this.
=> embed: add zap logger builder

CONTRIBUTING.md
The commit message style that etcd repo uses is something that is not fully documented. The PR clarifies what is expected from contributors.
/cc @gyuho @xiang90 @jpbetz
=> CONTRIBUTING: clarify commit message style

Documentation/etcd-mixin/mixin.libsonnet, Documentation/op-guide/etcd3_alert.rules.yml
(and remove non-etcd specific FdExhaustionClose)
Altered version taken from https://github.com/coreos/prometheus-operator/blob/master/helm/exporter-kube-etcd/templates/etcd3.rules.yaml.
=> Sync prometheus alerting rules with prometheus-operator version

Documentation/dev-guide/apispec/swagger/rpc.swagger.json, Documentation/dev-guide/apispec/swagger/v3election.swagger.json, Documentation/dev-guide/apispec/swagger/v3lock.swagger.json, scripts/genproto.sh
Since the update to go mod genproto.sh fails to run. This PR bumps protoc to latest (v3.6.1) and fixes genproto.sh.
Fixes: https://github.com/etcd-io/etcd/issues/10336
/cc @gyuho 
ref: https://github.com/protocolbuffers/protobuf/releases
=> *: bump protoc to 3.6.1 and fix genproto.sh

clientv3/client.go, clientv3/integration/user_test.go
=> clientv3/integration: Don't retry other endpoints when err == rpctypes.ErrAuthNotEnable 

etcdctl/ctlv2/command/util.go, etcdctl/ctlv3/command/global.go
Signed-off-by: Iskander Sharipov <quasilyte@gmail.com>
=> etcdctl: fix strings.HasPrefix args order

etcdctl/ctlv2/command/util.go
Cherry pick of #10443 on release-3.2.
#10443: etcdctl: fix strings.HasPrefix args order
=> Automated cherry pick of #10443 to release 3.2

etcdctl/ctlv2/command/util.go
Cherry pick of #10443 on release-3.1.
#10443: etcdctl: fix strings.HasPrefix args order
=> Automated cherry pick of #10443 to release 3.1

Documentation/etcd-mixin/mixin.libsonnet
Currently message states that has seen large leader
changes within the last 1 hour, although we check
for last 15min and wait for 15min for this alert to keep firing.
This fix changes the message to be 30minutes.
=> etcd-mixin: Improve etcdHighNumberOfLeaderChanges,etcdHighNumberOfFailedProposals messages

CHANGELOG-3.1.md, CHANGELOG-3.2.md, CHANGELOG-3.4.md, etcdctl/ctlv2/command/util.go, etcdctl/ctlv3/command/global.go
See #10443 which was backported to 3.1 and 3.2 today.
=> Add #10443 fix to changelogs

pkg/transport/transport_test.go
Fixes: https://github.com/etcd-io/etcd/issues/10267
=> pkg/transport: Limit InvalidCipherSuites to TLS12

clientv3/integration/kv_test.go, clientv3/op.go
The WithFromKey func should not return error similar to etcdctl usage
of it when an empty key is provided.
Fixed #9833
=> clientv3: fix WithFromKey

Documentation/op-guide/configuration.md
Changed **--strict-reconfig-check** to **default: true** in file
https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md#--strict-reconfig-check
Fixes Issue #10462 
=> Fixed --strict-reconfig-check#10462

Documentation/op-guide/configuration.md, embed/config.go, embed/etcd.go, etcdmain/config.go, etcdmain/help.go, etcdserver/backend.go, etcdserver/config.go, mvcc/backend/backend.go
Use the new bboltdb feature(map freelist type) as a experimental feature in etcd to boost the performance when the data stored in etcd is huge(like 50GB).
=> *: add flag to let etcd use the new boltdb freelistType feature

clientv3/retry_interceptor.go, tests/e2e/ctl_v3_auth_test.go, tests/e2e/ctl_v3_kv_test.go
Log only when it errors + some clarification.
FYI. I am debugging around https://github.com/etcd-io/etcd/issues/9949.
And resolve https://github.com/kubernetes/kubernetes/issues/72102.
=> clientv3: clarify retry interceptor logging

clientv3/integration/network_partition_test.go
The problem of build fails will be randomly encountered at the time of submission. Found associated with TestDropReadUnderNetworkPartition. After analysis, the case was found to have problems.
https://github.com/etcd-io/etcd/blob/f0aeb705ceb1daca072af0a54be6b43c87bbc23e/clientv3/integration/network_partition_test.go#L270
When the network partitioning occurs (the leader is isolated), the other two followers may select a new leader (in this case, the original testcase will succeed), or the new leader may not be selected (in this case, the original testcase will failed).
The following may occur when `rs = <-s.r.readStateC` blocked (the new leader not selected):
https://github.com/etcd-io/etcd/blob/f0aeb705ceb1daca072af0a54be6b43c87bbc23e/etcdserver/v3_server.go#L702-L710
Testcase failures …
=> clientv3/integration: add timeout case.

tools/benchmark/README.md
=> benchmark: fix install docs

contrib/raftexample/README.md, contrib/raftexample/kvstore.go
When trying out raftexample, there's no instruction on how to build the source. So i added few steps to make it clearer to the user.
Also using `defer` to unlock mutex in couple of places in `kvstore.go`.
=> raftexample: added build instruction  and minor refactoring

clientv3/balancer/balancer.go, clientv3/client.go, clientv3/config.go, clientv3/retry_interceptor.go, embed/config_logging.go, etcdmain/grpc_proxy.go, etcdserver/raft.go, integration/cluster.go, pkg/logutil/zap.go, pkg/logutil/zap_grpc_test.go, pkg/logutil/zap_journal_test.go, pkg/logutil/zap_raft_test.go
Clean up and use `ISO8601TimeEncoder` format:
```
{"level":"info","ts":"2019-02-21T10:56:32.823-0800","caller":"etcdserver/backend.go:79","msg":"opened backend db","path":"default.etcd/member/snap/db","took":"1.777717ms"}
{"level":"info","ts":"2019-02-21T10:56:32.918-0800","caller":"etcdserver/raft.go:450","msg":"starting local member","local-member-id":"8e9e05c52164694d","cluster-id":"cdf818194e3a8c32"}
{"level":"info","ts":"2019-02-21T10:56:32.918-0800","caller":"raft/raft.go:712","msg":"8e9e05c52164694d became follower at term 0"}
{"level":"info","ts":"2019-02-21T10:56:32.918-0800","caller":"raft/raft.go:389","msg":"newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]"}
```
=> *: define default zap log configuration 

Documentation/dev-guide/api_grpc_gateway.md, Documentation/learning/why.md, clientv3/README.md
Currently, when we access the URL http://www.grpc.io, it is redirected to https://www.grpc.io automatically.
So this commit aims to replace **HTTP** to **HTTPs** for security.
=> doc: Replacing 'HTTP' by 'HTTPS' for securing links

client/keys_bench_test.go, etcdserver/api/rafthttp/http.go
"unmarshaling" to "unmarshalling" in line 64 and 134.
=> Fix some misspells

etcdctl/README.md
Add documentation to clarify that when writing TXN commands, multi-line values should be written using "\n" and not a literal newline (as in other commands).
Fixes #10169
=> etcdctl: Update README to clarify newline syntax in TXN

mvcc/backend/backend.go, mvcc/backend/batch_tx.go, mvcc/backend/read_tx.go, mvcc/kvstore.go, mvcc/kvstore_test.go, mvcc/kvstore_txn.go, mvcc/watchable_store.go
For better code readability, renaming Lock() to RLock() in ReadTx interface. 
This is my first attempt to address #10505. Personally I do not think we should wrap RLock() in a function named Lock(). But renaming the function does come with challenges. It is cause by the fact that ReadTx interface in embedded in BatchTx interface, and RLock() does not have a proper semantic under BatchTx interface.
Please let me know if this PR actually helps improve readability, or it adds more confusion.
FYI, I also added some comments to explain how the locks affect backend concurrency on reads and writes.
=> mvcc/backend: rename Lock() to RLock() in ReadTx interface

lease/lessor.go, lease/lessor_test.go
Signed-off-by: nolouch <nolouch@gmail.com>
There is a deadlock issue which block the write. when we renew a lease that have remaining TTL cause by the long TTL setting, it write `lease checkpointing` entry to raft and wait it apply, but apply this entry also need acquire the same lock which already acquired by `renew`, and then meet the deadlock until timeout.
=> lease: fix deadlock with Renew lease when the checkpointor is set

mvcc/index.go
Make a copy-on-write clone of the index tree when start traversing. So that lock can be released right after the clone to improve backend concurrency.
Suggested by @xiang90.
=> mvcc: release lock early when traversing index

clientv3/integration/watch_test.go, clientv3/watch.go
Closing of watch by client will cancel the watch grpc stream and
can produce a context canceled error. However, since client
simply wanted to close the watcher the error can create confusion
that something went wrong instead of a successful close. Ensure
that Close do not return ctx canceled error.
Fixed #10340
=> clientV3watch: do not return ctx canceled when Close watch

clientv3/op.go, clientv3/utils.go
The use of WithPrefix() and WithFromKey() together is not supported. The
client doesn't respect this behavior currently.
Fixes #10431
=> clientV3: fix behavior of WithPrefix and WithFromKey functions

etcdmain/main.go
For now `IsRunningSystemd()` checks if system **booted** with systemd, not running it (and doing it in dumb way just by checking `/run/systemd/system` exists and it's directory). There are cases when system isn't booted with systemd, but etcd still **need** to notify it:
* Restricted service (like `TemporaryFileSystem=/run + BindReadOnlyPaths=/run/systemd/notify`)
* [Portable services](https://systemd.io/PORTABLE_SERVICES.html) (same approach)
Internally `daemon.SdNotify()` doing all work for us - detecting *notify socket* (not *booted systemd*), handling errors /etc. The only case that etcd should handle - `err != nil` to notify users about broken notify socket.
After that change I got working portable service for etcd without any harm to any existing installations/setups/etc
=> etcdmain: fix sd_notify for restricted environments

etcdserver/api/rafthttp/pipeline.go
The close method may not be called.
https://github.com/etcd-io/etcd/blob/6da17cda18307eff6e946c824fb7b64ecaf34fbe/etcdserver/api/rafthttp/pipeline.go#L158-L163
=> etcdserver/api/rafthttp: fix the location of close http body.

contrib/raftexample/httpapi.go, lease/leasehttp/http.go
close it after read`http.Request.Body` .
one of them is:
https://github.com/etcd-io/etcd/blob/6da17cda18307eff6e946c824fb7b64ecaf34fbe/contrib/raftexample/httpapi.go#L32-L34
=>  close http request body after read it.

wal/wal.go, wal/wal_test.go
Signed-off-by: Shreyas Rao <shreyas.sriganesh.rao@sap.com>
To allow verification of the WAL contents with minimal memory footprint. Added a `Verify` function to the `wal` package that performs a corruption check on the WAL contents and reports any errors. This serves to be a streamlined version of the `ReadAll` method on the `WAL` struct, as it allows for a quick validation of the WAL contents before starting etcd from an existing data directory without the overhead of returning the entire WAL data in-memory to the caller. Also refactored the `openAtIndex` function to allow the `Verify` function to reuse code for creating decoder.
Fixes #10497
=> wal: add Verify function to perform corruption check on wal contents

clientv3/balancer/grpc1.7-health.go, clientv3/balancer/grpc1.7-health_test.go
"ErrNoAddrAvilable" to "ErrNoAddrAvailable".
=> Fix some variable spelling errors

clientv3/client.go
`getHost ` has two same definitions:
https://github.com/etcd-io/etcd/blob/939b4f8599f617541e1f1121167df22ecabddf89/clientv3/balancer/grpc1.7-health.go#L612-L618
https://github.com/etcd-io/etcd/blob/e1ca3b4434945e57e8e3a451cdbde74a903cc8e1/clientv3/client.go#L671-L677
the second unused which can be removed.
=> clientv3: clean up unused code.

integration/v3_alarm_test.go
use cancel instead of close.
1. close is builtin function name
2. cancel is more general
=> integration: use cancel instead of close.

bill-of-materials.json
Just realized the 'bom' test has been failing for a while in master branch. Re-generated `bill-of-materials.json` using `scripts/updatebom.sh`.
=> bill-of-materials: update to fix 'bom' test failure

contrib/raftexample/raft.go
=> contrib/raftexample: fix naked return.

Documentation/op-guide/configuration.md
The documentation for `--force-new-cluster` flag appears to tell users that it is necessary for restoring from backup. While this is true for v2 it is not part of the documented and preferred method for restoring a cluster [1] for v3 and is properly labeled as unsafe [2].
[1] https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/recovery.md#restoring-a-cluster
[2] https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/configuration.md#unsafe-flags
=> Documentation: update force-new-cluster flag usage for v3

raft/raft.go
=> raft/doc: clarify the case of out of date term

etcdmain/etcd.go
two log handers use different error info.
fixed it. use `err` instead of `lerr` which has no conflict with `err` before `select`.
=> etcdmain: use same error.

contrib/raftexample/raftexample_test.go
add a testcase for `httpKVAPI` which is an import component in raftexample.
In addition, it is helpful to solve problem like #10361.
=> contrib/raftexample: add test for httpKVAPI.

etcdserver/raft.go
When using the embed package to embed etcd, sometimes the storage prefix
being used might be full. In this case, this code path triggers, causing
an: `etcdserver: create wal error: no space left on device` error, which
causes a fatal. A fatal differs from a panic in that it also calls
os.Exit(1). In this situation, the calling program that embeds the etcd
server will be abruptly killed, which prevents it from cleaning up
safely, and giving a proper error message. Depending on what the calling
program is, this can cause corruption and data loss.
This patch switches the fatal to a panic. Ideally this would be a
regular error which would get propagated upwards to the StartEtcd
command, but in the meantime at least this can be caught with recover().
This fixes the most common fatal that I've …
=> etcdserver: Use panic instead of fatal on no space left error

raft/raft.go, raft/raft_test.go
Leader should check message sender upon receiving MsgReadIndex message, even when raft quorum is 1. The message could be sent from learner node. In this case, leader should respond to the sender.
Fixes #10589.
cc @xiang90 @gyuho @WIZARD-CXY @jpbetz
=> raft: leader respond to learner read index message

clientv3/balancer/picker/picker_policy.go, clientv3/integration/leasing_test.go
1. "priotize" to "prioritize" in line 34.
2. "expeted" to "expected".
=> clientv3/integration/leasing_test.go: Fix t.Fatalf error message

CHANGELOG-3.4.md, Documentation/op-guide/grpc_proxy.md, etcdmain/grpc_proxy.go, etcdserver/api/etcdhttp/metrics.go, proxy/grpcproxy/metrics.go
Currently, `grpc-proxy` exposes only metrics for proxy itself and does not allow the client to consume endpoint `/metrics`. The `/health` endpoint forwards a request against endpoint and so should` /metrics`. This PR resolves an issue where metrics returned by `/metrics` were the metrics of the proxy itself instead of the etcd member server.
Fixes: https://github.com/etcd-io/etcd/issues/10611
=> *: Change gRPC proxy to expose endpoint /metrics

wal/wal.go
Signed-off-by: Shreyas Rao <shreyas.sriganesh.rao@sap.com>
Fixed: logger is now included within the WAL struct that is returned by `openAtIndex`, thus ensuring that the logger passed to `Open` and `OpenForRead` is duly returned back, within the WAL.
=> wal: include logger in WAL returned by openAtIndex

clientv3/balancer/balancer.go
https://github.com/etcd-io/etcd/blob/e1ca3b4434945e57e8e3a451cdbde74a903cc8e1/clientv3/balancer/balancer.go#L53-L60
reasons:
1. `baseBalancer.name` should be more of a `cfg` name because the policy name is not the lb name
2.  there has been modified if  `b.cfg.Name` is not empty string.
https://github.com/etcd-io/etcd/blob/e1ca3b4434945e57e8e3a451cdbde74a903cc8e1/clientv3/balancer/balancer.go#L70-L72
Modify:
Direct use of ` b.cfg.Name `.
=> clientv3/balancer: change balancer name to builder name.

.travis.yml
Currently, Travis testing in release-3.3 is broken this PR resolves that. The test container has a different working directory to accommodate the new org. To eliminate this issue and keep it simple for generating new test containers the path is explicitly set for the etcd src.
https://github.com/etcd-io/etcd/blob/c7c689452735a955d32126e3af8f3b18cbd9cf83/tests/Dockerfile#L43
=> travis: fix tests by using proper code path - release-3.3

Documentation/op-guide/grpc_proxy.md, etcdmain/grpc_proxy.go, etcdserver/api/etcdhttp/metrics.go, proxy/grpcproxy/metrics.go
Cherry pick of #10618 to release-3.3.
#10618: *: Change gRPC proxy to expose endpoint /metrics
=> cherry pick of #10618 to release 3.3

raft/progress.go
Update the raft progress `String()` method to include `RecentActive` and `IsLearner` fields.
=> raft: add learner field to progress stringer

mvcc/kvstore_compaction.go
Cherry pick of #10646 on release-3.3.
#10646: mvcc: fix db_compaction_total_duration_milliseconds
=> Automated cherry pick of #10646

CHANGELOG-3.1.md, CHANGELOG-3.2.md, CHANGELOG-3.3.md
This is just the changelog update for the PR # 10646 backports:
3.3 - #10656
3.2 - #10657
3.1 - #10658
=> CHANGELOG: update changelogs for backport of PR #10646

mvcc/kvstore_compaction.go
defer dbCompactionTotalMs.Observe(float64(time.Since(totalStart) / time.Millisecond))
Here, it will calculate `float64(time.Since(totalStart) / time.Millisecond)` when call defer directly and push into function stack, so the duration is quite small, less than 1 millisecond, so this value is always zero.
```
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="100"} 3564
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="200"} 3564
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="400"} 3564
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="800"} 3564
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{le="1600"} 3564
etcd_debugging_mvcc_db_compaction_total_duration_milliseconds_bucket{l …
```
=> fix issue that metric db_compaction_total_duration_milliseconds is always 0

CHANGELOG-3.4.md
Update CHANGELOG-3.4 from PR #10646.
=> CHANGELOG: update CHANGELOG-3.4 from #10646

etcdserver/api/rafthttp/probing_status.go
The log value is inconsistent with the field.
=> api/rafthttp: fix the probing status log print

raft/raft.go
`raftpb.Entry.String` takes a pointer receiver, so calling it
on a loop variable was causing the variable to escape. Removing
the `.String()` call was enough to avoid the allocation, but
this also avoids a memory copy and prevents similar bugs.
This was responsible for 11.63% of total allocations in an
experiment with https://github.com/nvanbenschoten/raft-toy.
=> raft: avoid allocation of Raft entry due to logging

raft/raft.go
By boxing a heap-allocated slice header instead of the slice
header on the stack, we can avoid an allocation when passing
through the sort.Interface interface.
This was responsible for 26.61% of total allocations in an
experiment with https://github.com/nvanbenschoten/raft-toy.
=> raft: Avoid allocation when boxing slice in maybeCommit

raft/log.go
Appending to an empty slice twice could (and often did) result in
multiple allocations. This was wasteful. We can avoid this by performing
a single allocation with the correct size and copying into it.
=> raft: Avoid multiple allocs when merging stable and unstable log

clientv3/client.go
from #10580
1. Concurrent access is possible in `func (c *Client) Endpoints() (eps []string)` , so mutex required.
2. remove naked return.
=> clientv3: modify lock type.

clientv3/naming/grpc.go
=> clientv3/naming: ignore empty update.

mvcc/index.go
Use write lock when cloning index tree.
Fixes #10697.
cc @xiang90
=> mvcc: protect tree clone with write lock

client/client_test.go, client/keys_test.go
Fixes: https://github.com/etcd-io/etcd/issues/10539
=> Fix tests for latest golang

wal/wal.go, wal/wal_test.go
delete <data-dir>/member/wal if any operation after the rename in
wal.Create fails to avoid reading an inconsistent WAL on restart.
Fixes #10688
=>   raft: cleanup wal directory if creation fails

CHANGELOG-3.1.md, CHANGELOG-3.2.md, CHANGELOG-3.3.md
Recommendations for the production were bumped up recently. The related
ML email ref is old one so we should not provide the link.
Fixes #10669
=> CHANGELOG: remove mailing list reference

Documentation/triage/PRs.md, Documentation/triage/issues.md
I would like to propose a formal guide for issue triage and PR management. This should help us keep open issues and PRs under a desirable number. For example, keep issues under 100. These guidelines should specially help manage and close issues and PRs that are inactive in a timely manner.
Sometimes back I had proposed triage guidelines to the Kubernetes community and created one working with the community. Here is a link for reference http://bit.ly/2W0PM4j In the community smaller projects and SIGs are also encouraged to create formal triage doc to keep issues and PRs numbers in check.
=> Doc: create issue and PR management guidelines

.words, clientv3/cluster.go, clientv3/integration/cluster_test.go, clientv3/integration/kv_test.go, etcdctl/ctlv3/command/ep_command.go, etcdctl/ctlv3/command/member_command.go, etcdctl/ctlv3/command/printer.go, etcdctl/ctlv3/command/printer_fields.go, etcdctl/ctlv3/command/printer_simple.go, etcdserver/api/membership/cluster.go, etcdserver/api/membership/cluster_test.go, etcdserver/api/membership/errors.go, etcdserver/api/v2http/client_test.go, etcdserver/api/v2http/http_test.go, etcdserver/api/v2v3/server.go, etcdserver/api/v3rpc/interceptor.go, etcdserver/api/v3rpc/maintenance.go, etcdserver/api/v3rpc/member.go, etcdserver/api/v3rpc/rpctypes/error.go, etcdserver/api/v3rpc/util.go, etcdserver/errors.go, etcdserver/server.go, etcdserver/server_test.go, integration/cluster.go, integration/v3_leadership_test.go
Part 2 of #10645. Continuation of #10725.
This PR incldues the following 16 commits from #10645. The last 6 commits are just formatting and bug fixes for the earlier 10 commits.
```
(ordered by: latest commits on top)
f058b7fbfe9bb3a1ea82f262514110aa91b0c8d5 clientv3/integration: deflake TestKVForLearner
1a080384e20ca55f48c4effe448c87392600ba3e clientv3/integration: fix cluster tests
11e41685030846ba495a4263d8db352d0e9fc7d0 clientv3/integration: update MemberAdd call
5d1f6c73c1dcdd889a28138b0ba6e79f814a704a integration: remove unnecessary type conversion
4f9eb2f7c8b7175ce7eb690c72461e654bd0a0ff etcdserver: remove unnecessary bool comparison
ab030455051cc034704cc4fc9206786b12ee88f6 words: whitelist words to fix goword test.
b0be8067e40c068eb2180b192d792aec21a1e3a2 clientv3, etcdctl: …
```
=> *: support raft learner in etcd - part 2

MAINTAINERS
I no longer have the time to maintain etcd as my career takes me to a different direction; Hence, I think it is appropriate to remove myself from the maintainer responsibility.
Working on etcd project was one of the most challenging and rewarding experiences I ever had. Thanks @xiang90 @gyuho @heyitsanthony @philips
=> MAINTAINERS: remove fanmin shi

raft/node.go, raft/progress.go, raft/raft.go, raft/raft_flow_control_test.go, raft/raft_paper_test.go, raft/raft_snap_test.go, raft/raft_test.go, raft/rawnode.go, raft/read_only.go, raft/status.go
The Progress maps contain both the active configuration and information
about the replication status. By pulling it into its own component, this
becomes easier to unit test and also clarifies the code, which will see
changes as #7625 is addressed.
I broke this up into multiple commits to avoid staring at too much code
movement at once, but the bulk of the changes are still mechanical.
=> raft: extract progress tracking into own component 

CHANGELOG-3.1.md, CHANGELOG-3.2.md, CHANGELOG-3.3.md, CHANGELOG-3.4.md, CHANGELOG-3.5.md, README.md, clientv3/README.md, docs/README.md
Remove all readthedocs references for https://etcd.io to ensure the SEO
goes to the right place.
=> *: move to etcd.io for docs

README.md
`markdown_you` CI test fails due to the appearance of word 'you' in documents.
Ref: https://travis-ci.com/etcd-io/etcd/jobs/202993572#L560
cc @philips
=> Doc: remove word you

Documentation/op-guide/configuration.md, etcdmain/config.go, etcdmain/help.go
Be more explicit in document and in command line help message that if a config file is provided, other command line flags and environment variables will be ignored.
The motivation is to avoid user confusion such as #10751.
Please let me know if you think this is too much verbosity.
=> *: more clarification on when server config file is provided

Documentation/op-guide/runtime-configuration.md, clientv3/integration/cluster_test.go, clientv3/integration/kv_test.go, etcdserver/api/etcdhttp/peer.go, etcdserver/api/etcdhttp/peer_test.go, etcdserver/api/membership/cluster.go, etcdserver/api/membership/cluster_test.go, etcdserver/api/membership/errors.go, etcdserver/api/v3rpc/interceptor.go, etcdserver/api/v3rpc/rpctypes/error.go, etcdserver/api/v3rpc/util.go, etcdserver/cluster_util.go, etcdserver/errors.go, etcdserver/server.go, etcdserver/server_test.go, etcdserver/v3_server.go, integration/cluster.go
Last part of #10645. Continuation of #10727.
This PR incldues the last 12 commits in #10645. Some of the commits are modified during rebasing to #10727.
```
(ordered by: latest commits on top)
b433162c0b9ea4d13e9a0dd49b1f51e20896cbcc integration: update TestMemberPromote test
ae08d06eb991b66d1de77912da0fe4c8ff03a35b etcdserver: update raftStatus
3f937cc459db33b9fd385d14a98b6747e11e93df etcdserver: check http StatusCode before unmarshal
ec1928e7b44fb14b53bd878eb37283ef1a144dec etcdserver: use etcdserver ErrLearnerNotReady
a8f87b83be4fe9f826104c8ac62361c30d779de3 etcdserver: forward member promote to leader
dc79587cd1b05007516544db0bb576b70436aca3 etcdserver: add mayPromote check
c6298843d77162ebb62a256fc2bcde4bcd190153 Doc: add learner in runtime-configuration.md …
```
=> *: support raft learner in etcd - part 3

clientv3/retry_interceptor.go
clientv3: return getToken error when retryAuth
return `get token error` instead of the `lastErr`, since `lastErr` is always "invalid auth token"
Fixes #10754
=> fix #10754

CHANGELOG-3.4.md
Update CHANGELOG-3.4 from #10725.
cc @xiang90 @gyuho @jpbetz @WIZARD-CXY
=> CHANGELOG: update changelog-3.4 with learner

etcdctl/README.md
Add clarification in etcdctl doc. If using released versions earlier than 3.4, `ETCDCTL_API=3` is needed in order to use v3 API.
This is causing user confusion. Examples: #10740, #10768.
=> doc: clarify etcdctl default API version

mvcc/index.go
Revert #10526 and its followup #10699. To fix data race in the following tests:
- TestLeasingDeleteRangeContendTxn
- TestBarrierSingleNode
- TestBarrierMultiNode
`&keyIndex{}` is not deep copied in `tree.Clone()`.
https://github.com/etcd-io/etcd/blob/e1ca3b4434945e57e8e3a451cdbde74a903cc8e1/mvcc/index.go#L94-L96
=> mvcc: revert change made by #10526 and #10699

etcdserver/server.go, lease/lease_queue.go, lease/lease_queue_test.go, lease/lessor.go
Fix https://github.com/etcd-io/etcd/issues/10686:
This is an easy way to try to fix the issue, and I'm not sure if this is a good method. I need some suggestions about it and then add the test.
=> lease/lessor: recheck if exprired lease is revoked

README.md
We may not want to suggest to contact CoreOS now. We could remove this
section but consiering the nature of the subject, discussion with the project
maintainers probably a good idea if someone doesn't find it comfortable
to report an issue right away.
=> README: update handling of security vulnerabilities

clientv3/integration/cluster_test.go
Add 2 failure cases for member promote. "Learner not ready" failure case is already covered in `TestMemberPromote`[1]. This PR completes all 3 cases mentioned in the doc [2].
cc @xiang90 @WIZARD-CXY @gyuho 
Reference:
[1] https://github.com/etcd-io/etcd/blob/2f7121b420960bc6906d64ec853cbd0159c92dff/clientv3/integration/cluster_test.go#L253-L255
[2] [Doc: Error cases when promoting a learner member](https://github.com/etcd-io/etcd/blob/master/Documentation/op-guide/runtime-configuration.md#error-cases-when-promoting-a-learner-member)
=> clientv3/integration: add member promote failure test cases

CHANGELOG-3.3.md
Added the sigs.k8s.io/yaml dependency update in the changelog for release-3.3 : 
The original request came from @gyuho : 
_Originally posted by @gyuho in https://github.com/etcd-io/etcd/pull/10718#issuecomment-497101964_
=> CHANGELOG-3.3: add sigs.k8s.io yaml dependency

etcdctl/ctlv3/command/ep_command.go, etcdctl/ctlv3/command/printer.go, etcdctl/ctlv3/command/printer_fields.go, etcdctl/ctlv3/command/printer_json.go, etcdctl/ctlv3/command/printer_simple.go, etcdctl/ctlv3/command/printer_table.go
=> ctlv3: cherry pick of #9540 to release 3.3

etcdctl/ctlv3/command/printer_simple.go
Add back the newline character in output of EndpointHealth, so that the output message is consistent with the output message before #9540.
cc @gyuho
=> ctlv3: add newline in EndpointHealth output

etcdctl/ctlv3/command/printer_simple.go
Cherry pick of #10788 on release-3.3.
#10788: ctlv3: add missing newline in EndpointHealth
=> Automated cherry pick of #10788 on release-3.3

etcdctl/ctlv3/command/printer_simple.go
Cherry pick of #10788 on release-3.2.
#10788: ctlv3: add missing newline in EndpointHealth
=> Automated cherry pick of #10788 on release-3.2

etcdctl/ctlv3/command/printer_simple.go
Cherry pick of #10788 on release-3.1.
#10788: ctlv3: add missing newline in EndpointHealth
=> Automated cherry pick of #10788 on release-3.1

CHANGELOG-3.4.md, embed/config.go, embed/etcd.go, etcdmain/config.go, etcdmain/help.go, etcdserver/config.go, etcdserver/server.go, integration/cluster.go, integration/v3_lease_test.go
Discussed with @jpbetz. In etcd 3.4, let's put lease checkpoint feature #9924 behind an experimental flag. The primary concern is that the feature introduced a new raft entry type `LeaseCheckpointRequest`. This will make the design of HA cluster downgrade difficult, as servers of old version panics on unknown raft type (during apply).
With this PR, lease checkpoint feature is enabled only if "--experimental-enable-lease-checkpoint" is set.
cc @jpbetz @xiang90 @gyuho
=> *: enable lease checkpoint via experimental flag

tests/e2e/v3_curl_test.go
=> tests/e2e: initialize UserAddOptions{} field in testV3CurlAuth()

README.md
Provide a ref to the issue and PR management doc from the README,
similar to other references we have provided in the README.
related: https://github.com/etcd-io/etcd/pull/10668
=> README: provide ref for issue and PR managenet doc

MAINTAINERS
@jingyih has become increasingly involved in etcd over the last year, the most notable being his recent contributions to the implementation of the Learner feature in 3.4. Equally important is his daily activity reviewing PRs and issues, his bug fixes and backports to ensure etcd is stable and operable, and his contributions to performance enhancements efforts like the fully concurrent reads.
=> Add @jingyih to MAINTAINERS

raft/rawnode_test.go
This will keep them from diverging to much. In fact we should remove
some of the obvious differences that have crept in over time so that
what remains is structural. This isn't done in this commit since
it amounts to a change in the public API; we should lump this in
when we break the public API the next time.
=> raft: make relationship between node and RawNode explicit

lease/lessor.go, lease/lessor_bench_test.go
Lease's benchmark were added when we optimize lease expiration check in  [#9418](https://github.com/etcd-io/etcd/pull/9418).
However, some problems exist.
- For `benchmarkLessorFindExpired`, lease's ttl  is always more than 100 second.
When call `findExpiredLeases`, we always only compare leaseHeap's first element ttl with current time and return immediately.
- Lessor is not primary, so `Renew` do nothing and `Grant` ignore ttl.
- We always call `Grant` with increasing ttl. `leaseHeap` degenerates into sorted array.
- Wrong use size. 
Such as BenchmarkLessorGrant1 and BenchmarkLessorGrant10000. Assume b.N  is 500000. For BenchmarkLessorGrant1, we call `Grant` 500001 times and observer last 500000 call. For BenchmarkLessorGrant10000, we call `Grant` 510000 times and observer last 500000 …
=> lease: refactor lease's benchmark.

etcdmain/config.go
=> etcdmain: fix ignoring of ETCD_CONFIG_FILE env variable

docs/metrics/latest, etcdserver/metrics.go, etcdserver/server.go
@jingyih @xiang90 Add learner metrics.
I suppose we will get this `etcd_debugging_learner_promote_failures` and `etcd_debugging_learner_promote_success` from leader.
=> etcdserver: add learner metrics

mvcc/backend/backend_test.go
Should have updated these as part of the renaming effort in https://github.com/etcd-io/etcd/pull/10506.
cc @xiang90
=> mvcc/backend: use RLock in test

integration/metrics_test.go, mvcc/backend/backend.go, mvcc/backend/backend_test.go, mvcc/backend/batch_tx.go, mvcc/backend/read_tx.go, mvcc/backend/tx_buffer.go, mvcc/kvstore.go, mvcc/kvstore_test.go, mvcc/kvstore_txn.go, mvcc/metrics.go
This PR solves "large read blocking write" issue (https://github.com/etcd-io/etcd/issues/10525) in mvcc/backend, as an alternative approach to #9384. The idea is to make ALL reads concurrent, therefore avoiding the need to predict and postpone the large reads. 
For 'full story', please refer to the [etcd: Fully Concurrent Reads Design Proposal](https://docs.google.com/document/d/1V9UuL8BnpZF2xFpHhvE1lO2hWvtdiLml3Ukr-m4jcdI/edit#heading=h.wuzq924gzsh).
In presence of long (expensive) reads, this PR increases the throughput of other requests (short reads on writes) by about 70%, reduces P99 and P999 latency by about 90%. In other benchmark cases where there are no long reads, performance w/ and w/o this PR is comparable. (see later section for detailed results)
Any ongoing kvstore read …
=> mvcc: fully concurrent read

etcdserver/api/rafthttp/transport.go
=> Raft HTTP: fix pause/resume race condition

raft/raft.go, raft/raft_test.go
We were already taking some precautions against learners campaigning,
but there was no safeguard against an explicit call to `Campaign()`.
The newly added test also verifies that leadership transfers to
learners are ignored.
=> raft: prevent learners from becoming leader

raft/quorum/datadriven_test.go
This slipped in during a rename and I didn't see it in CI because of
CI flakiness and a general intransparency about which failures are
important.
This unbreaks CI.
=> quorum: fix vet failure

test
Every other test build times out due to the 20 minute test timeout. I
doesn't seem like tests are actually hanging, it's more that 20 minutes
just isn't enough to run the tests any more.
=> test: s/20m/30m/g

clientv3/watch.go
Description: `w.mu` is locked at line 385 and unlocked at line 396. Among 5 return statements in this function, `w.mu` is unlocked before 4 return statements, but not unlocked before 1 return statement at line 387.
Fix: Add `w.mu.Unlock()` before that return at line 387.
Fixs [https://github.com/etcd-io/etcd/issues/10863](url)
=> clientv3: Fixed a missing block bug

docs/server-learner.rst, raft/README.md, raft/doc.go
The current link does not work and not valid anymore per stanford support.
Replace all current refs with a link that is used by the
https://raft.github.io/
Fixes # https://github.com/etcd-io/etcd/issues/10831
=> raftdoc: fix raft thesis link

Documentation/op-guide/authentication.md
This is a document error. With running `etcdctl role --help`, we can find that it should be delete, not remove.
Fixes #10849
=> Documentation: change `etcdctl role remove` to `etcdctl role delete`

raft/node.go, raft/quorum/joint.go, raft/quorum/majority.go, raft/quorum/quorum.go, raft/raft.go, raft/raft_snap_test.go, raft/raft_test.go, raft/rawnode.go, raft/tracker/tracker.go
Put all the logic related to applying a configuration change in one
place in preparation for adding joint consensus.
This inspired various TODOs.
I had to rewrite TestSnapshotSucceedViaAppResp since it was relying
on a snapshot applied to the leader, which is now prevented.
=> raft: centralize configuration change application

etcdserver/server.go
In etcdserver/server.go, s.be is always protected by s.bemu, except one read operation to it at line 1294 that is not in critical section.
Before this commit:
```Go
// line 1112 to 1294:
func (s *EtcdServer) applySnapshot(ep *etcdProgress, apply *apply) {
...//some irrelevant code
s.bemu.Lock()
oldbe := s.be
go func() {
...//some code to close oldbe
}()
s.be = newbe
s.bemu.Unlock()
...//some code to handle error
s.cluster.SetBackend(s.be)
...//some irrelevant code
}
```
This commit changes `s.cluster.SetBackend(s.be)` into `s.cluster.SetBackend(newbe)`, so all read operations to s.be are in critical section.
Fix #10871
=> etcdserver: modify a read operation to avoid potential race

raft/tracker/progress.go, raft/tracker/progress_test.go
Make it less verbose by omitting the values for the steady state.
Also rearrange the order so that information that is typically more
relevant is printed first.
=> raft: optimize string representation of Progress

raft/raft.go, raft/raft_test.go
At the time of writing, we don't allow configuration changes to change
voters to learners directly, but note that a snapshot may compress
multiple changes to the configuration into one: the voter could have
been removed, then readded as a learner and the snapshot reflects both
changes. In that case, a voter receives a snapshot telling it that it is
now a learner. In fact, the node has to accept that snapshot, or it is
permanently cut off from the Raft log.
I think this just wasn't realized in the original work, but this is just
my guess since there generally is very little rationale on the various
decisions made. I also generally haven't been able to figure out whether
the decision to prevent voters from becoming learners without first
having been removed was motivated by some particular …
=> raft: allow voter to become learner through snapshot

.travis.yml
This run *should* certainly pass, but it's consistently the one that
fails with a regularity that essentially blocks the CI pipeline.
Someone needs to take a look at #10700, but in the meantime, the show
must go on.
=> test: allow failures in linux-amd64-integration-4-cpu

raft/rafttest/node.go
In order to cover message can well be received when a node is paused, this commit sends message async using goroutine and random sleep. This change makes recvms is possible to cache message during node.pause is triggered.
=> raft/rafttest: simulate async send in node test

raft/confchange/confchange.go, raft/confchange/datadriven_test.go, raft/confchange/quick_test.go, raft/confchange/testdata/joint_idempotency.txt, raft/confchange/testdata/joint_learners_next.txt, raft/confchange/testdata/joint_safety.txt, raft/confchange/testdata/simple_idempotency.txt, raft/confchange/testdata/simple_promote_demote.txt, raft/confchange/testdata/simple_safety.txt, raft/confchange/testdata/update.txt, raft/confchange/testdata/zero.txt, raft/raft.go, raft/raft_test.go, raft/tracker/progress.go, raft/tracker/tracker.go
This commit introduces machinery to safely apply joint consensus
configuration changes to Raft.
The main contribution is the new package, `confchange`, which offers
the primitives `Simple`, `EnterJoint`, and `LeaveJoint`.
The first two take a list of configuration changes. `Simple` only
declares success if these configuration changes (applied atomically)
change the set of voters by at most one (i.e. it's fine to add or
remove any number of learners, but change only one voter). `EnterJoint`
makes the configuration joint and then applies the changes to it, in
preparation of the caller returning later and transitioning out of the
joint config into the final desired configuration via `LeaveJoint()`.
This commit streamlines the conversion between voters and learners, which
is now generally …
=> raft: internally support joint consensus

integration/v3_watch_test.go
add WaitGroup to prevent calling t.Fatalf after TestV3WatchCurrentPutOverlap function return. It could cause a panic
Fixes etcd-io#10886
=> integration: add WaitGroup to TestV3WatchCurrentPutOverlap

scripts/genproto.sh, scripts/updatedep.sh
I had been dealing with these intermittent failures for a while and
finally figured out why. The real solution is making genproto.sh less
ugly but that won't happen for a while.
=> scripts: fail explicitly in updatedep.sh when gopath.proto exists

raft/rawnode.go, raft/rawnode_test.go, raft/status.go, raft/tracker/inflights.go
Recent refactoring to the String() method of `Progress` hit an NPE
because we return nil Inflights as part of the Raft status. Just
fix this at the source and properly populate the Raft status instead
of teaching String() to ignore nil. A real Progress always has a
non-nil Inflights.
=> raft: return non-nil Inflights in raft status

etcdserver/raft.go, etcdserver/raft_test.go
It created a sequence of conf changes that could intermittently cause an
empty set of voters, which Raft asserts against as of #10889.
This fixes TestCtlV2BackupSnapshot and TestCtlV2BackupV3Snapshot, see:
https://github.com/etcd-io/etcd/issues/10700#issuecomment-512358126
=> etcdserver: fix createConfChangeEnts

raft/raft.go, raft/raft_test.go
Cherry pick of #8334 into release-3.3
#8334: raft: set lead to none when becomePreCandidate
=> raft: cherry pick of #8334 to release-3.3

Dockerfile-release, Dockerfile-release.arm64, Dockerfile-release.ppc64le
To improve security and maintenance effort for etcd releases, it would 
be ideal to rebase etcd base image from Alpine to Distroless. However, 
note that distroless images by default do not contain a shell, etcd still has
shell scripts in https://github.com/etcd-io/etcd/tree/master/hack, I will
first rebase to Debian in v3.4.
This work is still in progress, open now to unveil any unexpected errors 
from testing.
Fixes #10804 
/cc @yuwenma
=> Dockerfile: Rebase etcd image to debian

raft/node.go, raft/rawnode.go, raft/rawnode_test.go
I changed `(*RawNode).Ready`'s behavior in #10892 in a problematic way.
Previously, `Ready()` would create and immediately "accept" a Ready
(i.e. commit the app to actually handling it). In #10892, Ready() became
a pure read-only operation and the "accepting" was moved to
`Advance(rd)`.  As a result it was illegal to use the RawNode in certain
ways while the Ready was being handled. Failure to do so would result in
dropped messages (and perhaps worse). For example, with the following
operations
1. `rd := rawNode.Ready()`
2. `rawNode.Step(someMsg)`
3. `rawNode.Advance(rd)`
`someMsg` would be dropped, because `Advance()` would clear out the
outgoing messages thinking that they had all been handled by the client.
I mistakenly assumed that this restriction had existed prior, but this
is …
=> raft: require app to consume result from Ready()

CHANGELOG-3.4.md, Documentation/dev-guide/api_reference_v3.md, Documentation/dev-guide/apispec/swagger/rpc.swagger.json, auth/store.go, auth/store_test.go, clientv3/integration/role_test.go, etcdserver/api/v3rpc/rpctypes/error.go, etcdserver/api/v3rpc/util.go, etcdserver/etcdserverpb/rpc.pb.go, etcdserver/etcdserverpb/rpc.proto
Like user, we should not allow creating empty role.
Related #10905
=> etcdserver: do not allow creating empty role

embed/config_logging.go
This fixes an index out-of-bounds panic caused when using the embed
package and the zap logger. When a TLS handshake error is logged, the
slice for cert ip addresses is allocated with capacity but no length, so
subsequent index access causes the panic, and doesn't surface the TLS
handshake error to the user.
Fixes #10932
=> embed: fix oob panic in zap logger

etcdserver/api/v2v3/main_test.go, etcdserver/api/v2v3/store_test.go
Add a bunch of tests on fundamental operation of Create/Set/Delete.
Context: I want to use this package to run the discovery service against
the v3 storage backend. The limited functionality already implemented
should be sufficient to do this.
https://github.com/coreos/discovery.etcd.io/issues/52
=> etcdserver: api/v2v3: add initial tests

raft/raft.go
The condition is overly strict, which has popped up in CockroachDB
recently.
=> raft: leave TODO about leaving StateSnapshot

Documentation/op-guide/configuration.md, embed/config.go, etcdserver/server.go, tests/e2e/cluster_test.go, tests/e2e/ctl_v2_test.go, tests/e2e/v2_curl_test.go
Still need changelog.
/cc @xiang90 @jpbetz @philips
=> *: disable v2 API by default

Documentation/op-guide/configuration.md, embed/config.go, embed/config_logging.go, etcdmain/config.go, etcdmain/help.go, etcdserver/raft.go, pkg/logutil/log_level.go, pkg/logutil/zap.go, pkg/logutil/zap_raft.go, raft/logger.go
Address https://github.com/etcd-io/etcd/pull/10946.
/cc @jingyih @benitogf
```
etcd --logger zap --log-level warn
```
```
{"level":"warn","ts":"2019-07-28T21:50:24.137-0500","caller":"etcdmain/etcd.go:119","msg":"'data-dir' was empty; using default","data-dir":"default.etcd"}
{"level":"warn","ts":"2019-07-28T21:50:24.242-0500","caller":"auth/store.go:1317","msg":"simple token is not cryptographically signed"}
{"level":"warn","ts":"2019-07-28T21:50:24.269-0500","caller":"etcdserver/metrics.go:186","msg":"failed to get file descriptor usage","error":"cannot get FDUsage on darwin"}
^C{"level":"warn","ts":"2019-07-28T21:50:32.216-0500","caller":"grpclog/grpclog.go:60","msg":"transport: http2Server.HandleStreams failed to read frame: read tcp 127.0.0.1:2379->127.0.0.1:52750: use of closed …
```
=> *: make log level configurable

Documentation/etcd-mixin/mixin.libsonnet, Documentation/etcd-mixin/test.yaml
An etcd member being down is an important failure state - while normal admin operations may cause transient outages during rotation, when any member is down the cluster is operating in a degraded fashion. Add an alert that records when any members are down so that administrators know whether the next failure is fatal.
The rule is more complicated than `up{...} == 0` because not all failure modes for etcd may have an `up{...}` entry for each member. For instance, a Kubernetes service in front of an etcd cluster
might only have 2 endpoints recorded in `up` because the third pod is evicted by the kubelet - the cluster is degraded but `count(up{...})` would not return the full quorum size. Instead, use network peer send failures as a failure detector and attempt to return the max of down …
=> Documentation/etcd-mixin: Add an alert for down etcd members

CHANGELOG-3.4.md, Documentation/op-guide/configuration.md, etcdmain/config.go, pkg/transport/listener.go, pkg/transport/listener_test.go
On initialising the peer-to-peer communication, ETCD checks the CN/SAN for the client side. This is not feasible, if the client IP address (of the HTTPS connection) is not stable or unknown at the time of creation of the certificate.
For example, if the peers of a distributed ETCD cluster with TLS enabled run in multiple clouds (or behind NAT with some kind of DHCP),
the IP addresses of the peers are not stable. Another example for such an environment is a Kubernetes cluster using Calico CNI. Here incoming requests from outside the cluster get the client address of the accepting K8s node.
Therefore a new command line option `--peer-skip-client-verify` is introduced to disable the client address check optionally. Basically it should be enough to rely on the knowledge of a valid …
=> etcdserver: config flag to skip verification of peer client address

CHANGELOG-3.4.md, mvcc/metrics.go, mvcc/metrics_txn.go, tests/e2e/metrics_test.go
This PR promotes the following experimental metrics to stable.
- etcd_debugging_mvcc_put_total -> etcd_mvcc_put_total
- etcd_debugging_mvcc_delete_total  -> etcd_mvcc_delete_total
Fixes #10950
/cc @p0lyn0mial
=> metrics: promote etcd_debugging_mvcc put_total and delete_total

MAINTAINERS
Add @spzala according to https://github.com/etcd-io/etcd/blob/master/MAINTAINERS_RULES.md.
Thanks for all the great work and contribution!
/cc @xiang90 @jpbetz @hexfusion @jingyih
=> MAINTAINERS: add @spzala

mvcc/kvstore.go, mvcc/metrics.go, mvcc/metrics_txn.go
also add missing register calls from https://github.com/etcd-io/etcd/issues/10950
=> mvcc: add "etcd_mvcc_range_total", "etcd_mvcc_txn_total"

pkg/adt/interval_tree.go, pkg/adt/interval_tree_test.go
=> pkg/adt: interval tree based on rbtree

CHANGELOG-3.4.md, Documentation/upgrades/upgrade_3_4.md, clientv3/client.go, clientv3/doc.go, clientv3/integration/kv_test.go, clientv3/integration/lease_test.go, functional/tester/stresser_key.go, proxy/grpcproxy/adapter/chan_stream.go, proxy/grpcproxy/lease.go, proxy/grpcproxy/watch.go
Fix https://github.com/etcd-io/etcd/issues/9304.
=> Deprecate "grpc.ErrClientConnClosing"

functional/Dockerfile, functional/scripts/docker-local-agent.sh, functional/scripts/docker-local-tester.sh
Cherry pick of #10987 on release-3.4.
#10987: functional:update go.etcd.io/etcd link and go image registry
=> Automated cherry pick of #10987

etcdserver/api/v3rpc/watch.go
don't read return value in child goroutine which causes data race.
=> v3rpc: fix a typo `err`

go.mod, go.sum, vendor/google.golang.org/grpc/balancer.go, vendor/google.golang.org/grpc/balancer/base/balancer.go, vendor/google.golang.org/grpc/balancer_conn_wrappers.go, vendor/google.golang.org/grpc/clientconn.go, vendor/google.golang.org/grpc/dialoptions.go, vendor/google.golang.org/grpc/internal/envconfig/envconfig.go, vendor/google.golang.org/grpc/internal/transport/http2_client.go, vendor/google.golang.org/grpc/internal/transport/http2_server.go, vendor/google.golang.org/grpc/pickfirst.go, vendor/google.golang.org/grpc/server.go, vendor/google.golang.org/grpc/status/status.go, vendor/google.golang.org/grpc/stream.go, vendor/google.golang.org/grpc/version.go
> For now, can you use the released version? It doesn't have the change (9771422) that caused the problem
https://github.com/grpc/grpc-go/pull/2952#issuecomment-518436359
Address https://github.com/etcd-io/etcd/issues/10979
=> vendor: update gRPC to latest

clientv3/integration/metrics_test.go
don't share `err` between goroutines
=> integration: fix a data race about `err`

pkg/types/set.go
(tsafeSet).Sub and (tsafeSet).Equals can cause double lock bug.
If one goroutine is invoking ts.Add(), and another goroutine is invoking ts.Equals(ts), then these two goroutines may be both blocking.
Fixs #10925 
***How to trigger this bug***
Please use the following test file to trigger this bug:
```Go
package types
import (
"sync"
"testing"
)
func TestThreadsafeEqualsSet(t *testing.T) {
var wg sync.WaitGroup
s1 := NewThreadsafeSet()
wg.Add(2)
go func(){
for i := 1; i <= 1000; i++ { // On my computer, 1000 is enough to trigger this bug
s1.Equals(s1)
}
wg.Done()
}()
go func(){
for i := 1; i <= 1000; i++ { // On my computer, 1000 is enough to trigger this bug
s1.Add("abc")
}
wg.Done()
}()
wg.Wait()
}
```
***How I fixed this bug***
In (tsafeSet).Equals, if `ts` and `other` …
=> Avoid potential double lock of tsafeSet

raft/raft.go, raft/raft_test.go
It turns out that that learners must be allowed to cast votes.
This seems counter- intuitive but is necessary in the situation in which
a learner has been promoted (i.e. is now a voter) but has not learned
about this yet.
For example, consider a group in which id=1 is a learner and id=2 and
id=3 are voters. A configuration change promoting 1 can be committed on
the quorum `{2,3}` without the config change being appended to the
learner's log. If the leader (say 2) fails, there are de facto two
voters remaining. Only 3 can win an election (due to its log containing
all committed entries), but to do so it will need 1 to vote. But 1
considers itself a learner and will continue to do so until 3 has
stepped up as leader, replicates the conf change to 1, and 1 applies it.
Ultimately, by …
=> raft: let learners vote

functional.yaml, functional/agent/utils.go, functional/rpcpb/member.go, functional/tester/cluster_run.go
`SIGQUIT_AND_REMOVE_ONE_FOLLOWER_UNTIL_TRIGGER_SNAPSHOT` has been flaky.
Lower snapshot count for slow computes (e.g. CI), and be more generous about error counts during `NO_FAIL_WITH_STRESS`.
Address https://github.com/etcd-io/etcd/issues/10979.
=> functiona: fix flaky tests

CHANGELOG-3.3.md, Documentation/op-guide/runtime-configuration.md
See the issue created here:
https://github.com/etcd-io/etcd/issues/10989#issuecomment-518726038
doc: fix broken links referring to etcd.redhatdocs.io
Adding links to internal Documentation within github.com.
Update runtime-configuration.md
Update runtime-configuration.md
Update CHANGELOG-3.3.md
Remove extra space
Keep the formatting similar to original
=> doc: Fix broken links referring to readthedocs.io

functional/agent/server.go
add 1-size buffer for `errc`  to avoid deadlock of child goroutine 
add a local variable to a void data race in `err`
when `case <-stream.Context().Done():` is taken
=> agent: fix data race and deadlock

etcdserver/api/rafthttp/http.go, etcdserver/api/rafthttp/metrics.go, etcdserver/api/rafthttp/snapshot_sender.go, etcdserver/metrics.go, etcdserver/server.go, integration/v3_watch_restore_test.go
Currently, there's no way to find out if current follower is receiving a leader snapshot. If snapshot receive is inflight, the operator may wait until it's done, rather than marking the follower as unhealthy. This is useful for a large cluster, where snapshot sends takes several minutes (e.g. 4 GB).
/cc @xiang90 @jpbetz @jingyih
=> *: add inflight snapshot metrics

raft/quorum/majority.go, raft/tracker/tracker.go, raft/util.go
This is helpful for upcoming testing work which allows datadriven testing
of the interaction of multiple nodes. This testing requires determinism to
work correctly.
=> raft/tracker: visit Progress in stable order

raft/rawnode.go
`newRaft()` does check for validity of `Config` object.
=> raft : remove unnecessary, if check

raft/confchange/confchange.go, raft/confchange/restore.go, raft/confchange/restore_test.go, raft/raft.go, raft/raftpb/confstate.go, raft/raftpb/confstate_test.go, raft/tracker/tracker.go, raft/util.go
While writing interaction tests for joint configuration changes, I realized
that this wasn't working yet - restoring had no notion of the joint
configuration and was simply dropping it on the floor.
This commit introduces a helper `confchange.Restore` which takes a
`ConfState` and initializes a `Tracker` from it.
This is then used both in `(*raft).restore` as well as in `newRaft`.
=> raft: fix restoring joint configurations

integration/metrics_test.go
From the definition, we have a trailing `s` here.
https://github.com/etcd-io/etcd/blob/9c5426830b1b8728af14e069acfdc2a64dea768c/etcdserver/api/etcdhttp/metrics.go#L76
Currently, we only match the prefix of metric name. So we don't find this problem.
https://github.com/etcd-io/etcd/blob/800e7235ebcd99087f084d6afc8521cc35a03c14/integration/cluster.go#L1149-L1153
It seems split at ` ` or `{` to get full metric name will be better.(or just using Prometheus `TextParser`). If it looks good, I can pull request.
=> test: fix metric name typo

go.mod, go.sum, raft/interaction_test.go, raft/raft.go, raft/raft_snap_test.go, raft/raftpb/confchange.go, raft/rafttest/interaction_env.go, raft/rafttest/interaction_env_handler.go, raft/rafttest/interaction_env_handler_add_nodes.go, raft/rafttest/interaction_env_handler_campaign.go, raft/rafttest/interaction_env_handler_compact.go, raft/rafttest/interaction_env_handler_deliver_msgs.go, raft/rafttest/interaction_env_handler_log_level.go, raft/rafttest/interaction_env_handler_process_ready.go, raft/rafttest/interaction_env_handler_propose_conf_change.go, raft/rafttest/interaction_env_handler_raft_log.go, raft/rafttest/interaction_env_handler_stabilize.go, raft/rafttest/interaction_env_handler_status.go, raft/rafttest/interaction_env_handler_tick_heartbeat.go, raft/rafttest/interaction_env_logger.go, raft/rafttest/network.go, raft/storage.go, raft/testdata/campaign.txt, raft/testdata/confchange_v1.txt, raft/testdata/snapshot_succeed_via_app_resp.txt, raft/tracker/progress.go, raft/util.go, vendor/github.com/cockroachdb/datadriven/datadriven.go
It has often been tedious to test the interactions between multi-member
Raft groups, especially when many steps were required to reach a certain
scenario. Often, this boilerplate was as boring as it is hard to write and
hard to maintain, making it attractive to resort to shortcuts whenever
possible, which in turn tended to undercut how meaningful and maintainable
the tests ended up being - that is, if the tests were even written, which
sometimes they weren't.
This change introduces a datadriven framework specifically for testing
deterministically the interaction between multiple members of a raft group
with the goal of reducing the friction for writing these tests to near
zero.
In the near term, this will be used to add thorough testing for joint
consensus (which is already available …
=> raft/rafttest: introduce datadriven testing

CHANGELOG-3.4.md
This metric was added as part of #10523.
cc @gyuho
=> CHANGELOG-3.4: add etcd_mvcc_db_open_read_transactions

proxy/grpcproxy/watch.go
Among 6 read/write operations to wps.watchers, 5 of them are protected by wps.mu.Lock(), except the one [at line 259 in file etcd/proxy/grpcproxy/watch.go](https://github.com/etcd-io/etcd/blob/master/proxy/grpcproxy/watch.go#L259)
***What I did***
Add wps.mu.Lock() to protect wps.watchers and wps.nextWatcherID, and then wps.mu.Unlock()
***Why I did this***
It is quite clear that wps.watchers should be protected, since all other 5 usages of it is protected by wps.mu.Lock().  If wps.watchers doesn't need a mutex [at line 259 in function wps.recvLoop()](https://github.com/etcd-io/etcd/blob/master/proxy/grpcproxy/watch.go#L259), then it also doesn't need a mutex [at line 289 and 294 in function wps.delete()](https://github.com/etcd-io/etcd/blob/master/proxy/grpcproxy/watch.go …
=> proxy: Add critical section to protect wps.watchers and wps.nextWatcherID

MAINTAINERS
Tobias has contributed quite a lot to the raft repo. I would like to propose to let him become on of the raft pkg maintainer.
@tbg what do you think?
/cc @bdarnell @gyuho @philips @jpbetz
=> MAINTAINERS: add Tobias Grieger as a maintainer to raft

CHANGELOG-3.4.md, Documentation/op-guide/configuration.md, clientv3/integration/maintenance_test.go, clientv3/snapshot/v3_snapshot.go, embed/config.go, embed/etcd.go, etcdmain/config.go, etcdmain/help.go, etcdserver/backend.go, etcdserver/config.go, etcdserver/server.go, etcdserver/server_test.go, integration/v3_alarm_test.go, mvcc/kv_test.go, mvcc/kvstore.go, mvcc/kvstore_bench_test.go, mvcc/kvstore_compaction.go, mvcc/kvstore_compaction_test.go, mvcc/kvstore_test.go, mvcc/watchable_store.go, mvcc/watchable_store_bench_test.go, mvcc/watchable_store_test.go, mvcc/watcher_bench_test.go, mvcc/watcher_test.go, tools/benchmark/cmd/mvcc.go
Reduce compaction intervals to 1k and duration between compactions to 10ms.
Also forces immediate commit of the write buffer after each compaction (thanks @jingyih for this).
I'll also make this configurable via a flag.
Supersedes #11021
=> mvcc: Optimize compaction for short commit pauses

Documentation/integrations.md
New tool: ETCD Manager
ETCD Manager is a multi-platform ETCD v3 client. Currently, builds are available form Mac, Wiindows and Linux, but iOS / Android builds will also be added in the future.
It aims to be a modern, efficient and easy to use GUI with full coverage of ETCD APIs / functionality. The first public (beta) release is already available.
=> Documentation: added ETCD Manager tool

etcdmain/help.go
Add `experimental-peer-skip-client-san-verification` flag description to help message. 
Follow up of #10524
=> etcdmain: update help message

functional/agent/handler.go
Fix typo in functional test agent log to avoid debugging confusion.
=> functional test: fix typo in agent log

clientv3/integration/kv_test.go
Fixes #11067.
Give backend quota enough overhead in TestKVPutError. See discussion in #6486.
cc @xiang90 @spzala
=> integration: fix TestKVPutError

clientv3/client.go, clientv3/client_test.go
Added nil checks in Close() for Watcher and Lease fields
Added test case
=> clientv3: add nil checks in Client.Close()

Documentation/demo.md
Updated Snapshot section of demo.md to reflect that snapsot can be requested only from one etcd node at a time.
Fixes : #10855
=> Documentation: snapshot can be requested from one etcd node only

scripts/release
This PR adds a new file SHA256SUM to the release assets for etcd. The file contains a list of sha2456sum for each release asset. By providing a list of sha256sums we can then validate these in various ways including tools like rget[1] with the added advantage of not requiring an isolated signing key.
[1] https://github.com/merklecounty/rget 
Fixes https://github.com/etcd-io/etcd/issues/11086
=> scripts/release: add sha256sum summary of release assets

CHANGELOG-3.4.md, scripts/release
These files are commonly called SHA256SUMS and with this change rget
works for v3.4.0 as well.
I manually fixed the v3.4.0 release.
=> scripts/release: rename SHA256SUM to SHA256SUMS

etcdserver/metrics.go
fix percent sign(%) print in log twice issue.
=> etcdserver: remove dup percentage sign in log

wal/wal.go
wal.Verify() : The opened WAL files are not closed in error cases. Fixed by adding a
defer.
=> wal : wal.Verify defer close the opened WAL files

mvcc/kvstore.go, mvcc/metrics.go
Add experimental metrics `etcd_debugging_mvcc_current_revision` and `etcd_debugging_mvcc_compact_revision`.
=> mvcc: add store revision metrics

integration/v3_tls_test.go
In go1.13, the TLS13 is enablled by default, and as per go1.13 release notes :
TLS 1.3 cipher suites are not configurable. All supported cipher suites are safe,
and if PreferServerCipherSuites is set in Config the preference order is based
on the available hardware.
Fixing the test case for go1.13 by limiting the TLS version to TLS12
=> integration : fix TestTLSClientCipherSuitesMismatch in go1.13

mvcc/kvstore.go
Among 14 read/write operations to s.currentRev, 10 of them are protected by `s.revMu.RLock()` or `s.mu.Lock()`, 3 of them are synchronized by using channel `revc`, but there is one read operation not protect by any Mutex, RWMutex or channel, which is in function `store.Hash()` at line 174 of file etcd/mvcc/kvstore.go:
https://github.com/etcd-io/etcd/blob/9a2af7378a937a3434dd126e225108c97bef0cdf/mvcc/kvstore.go#L167-L175
***What I did***
Add `s.revMu.RLock()` and `defer s.revMu.RUnlock()` to protect s.currentRev
***Why I did this***
In the comment of s.revMu, it is said that s.revMu protects currentRev:
```Go
// revMuLock protects currentRev and compactMainRev.
// Locked at end of write txn and released after write txn unlock lock.
// Locked before locking read txn and …
```
=> Add critical section to protect s.currentRev

.travis.yml, CHANGELOG-3.3.md, CHANGELOG-3.4.md, CHANGELOG-3.5.md, Makefile, functional/scripts/docker-local-agent.sh, functional/scripts/docker-local-tester.sh, go.mod, integration/v3_tls_test.go, pkg/transport/listener.go, scripts/updatedep.sh, test, tests/semaphore.test.bash
Test images have been uploaded already.
=> *: update test Go version / release version

tools/etcd-dump-logs/expectedoutput/decoder_correctoutputformat.output, tools/etcd-dump-logs/expectedoutput/decoder_wrongoutputformat.output, tools/etcd-dump-logs/expectedoutput/listAll.output, tools/etcd-dump-logs/expectedoutput/listConfigChange.output, tools/etcd-dump-logs/expectedoutput/listConfigChangeIRRCompaction.output, tools/etcd-dump-logs/expectedoutput/listIRRCompaction.output, tools/etcd-dump-logs/expectedoutput/listIRRDeleteRange.output, tools/etcd-dump-logs/expectedoutput/listIRRLeaseGrant.output, tools/etcd-dump-logs/expectedoutput/listIRRLeaseRevoke.output, tools/etcd-dump-logs/expectedoutput/listIRRPut.output, tools/etcd-dump-logs/expectedoutput/listIRRRange.output, tools/etcd-dump-logs/expectedoutput/listIRRTxn.output, tools/etcd-dump-logs/expectedoutput/listInternalRaftRequest.output, tools/etcd-dump-logs/expectedoutput/listNormal.output, tools/etcd-dump-logs/expectedoutput/listRequest.output, tools/etcd-dump-logs/main.go
The tool takes default values but it was not visible which default
values were taken. Added default values in proper place, and added a
newline at the end of output.
Fixed failing test case because of this change.
=> tools/etcd-dump-logs: Fixed default values for -entry-type flag

CHANGELOG-3.2.md, CHANGELOG-3.3.md
Updating CHANGELOG according to #11133, #11134 and #11135.
Looks like CHANGELOG-3.4 was already updated. So only updating CHANGELOG-3.3 and CHANGELOG-3.2.
=> CHANGELOG: update to add new metrics

etcdctl/README.md
=> ETCDCTL_README: clarify the usage of ETCDCTL_* variables

go.mod, go.sum, vendor/google.golang.org/grpc/internal/transport/http2_server.go, vendor/google.golang.org/grpc/internal/transport/http_util.go, vendor/google.golang.org/grpc/version.go
https://github.com/grpc/grpc-go/releases/tag/v1.23.1
=> vendor: upgrade to gRPC v1.23.1

embed/config.go, embed/config_logging.go
This exposes the ZapLoggerBuilder in the embed.Config to allow for
custom loggers to be defined and used by embedded etcd.
Fixes #11144
=> embed: expose ZapLoggerBuilder

embed/config.go, embed/config_logging.go
Cherry pick of #11147 on release-3.4.
#11147: embed: expose ZapLoggerBuilder
=> Automated cherry pick of #11147

etcdserver/api/membership/cluster.go
In case of URLs that are synonyms, the current lexicographic sorting
and compare of the URLs fails with frustrating errors. Make sure to do
a full comparison between every set of PeerURLs before failing.
Fixes #11013
=> etcdserver: Fix PeerURL validation

hack/patch/README.md
`remotes` is not a valid git command. Also, set the environmental variable
correctly.
=> hack: fix cherrypick instruction

.travis.yml
bill-of-materials was fixed for module aware 'go list' as part of https://github.com/coreos/license-bill-of-materials/pull/17
So can re enable bom tests
fixes #11132
=> travis: re-enable bom tests

clientv3/integration/cluster_test.go
The break statement should break the outer for loop, or it will run forever.
=> integration:  fix bug in for loop, make it break properly

e2e/ctl_v3_snapshot_test.go, etcdctl/ctlv3/command/snapshot_command.go
This can break production rollback/downgrade process:
For example,
1. start etcd v3.3.10
2. write some data
3. use etcdctl v3.3.10 to save snapshot
4. somehow, upgrading Kubernetes fails, thus rolling back to previous version etcd v3.2.24
5. run etcdctl v3.2.24 snapshot status against the snapshot file saved from v3.3.10 server
6. run etcdctl v3.2.24 snapshot restore fails with `"expected sha256 [12..."`
/cc @wenjiaswe @jingyih
=> etcdctl/ctlv3: do not modify db file on "restore"

clientv3/concurrency/example_mutex_test.go
Since NewMutex will append a slash to pfx, there is no need to append a
slash beforehand.
=> clientv3/concurrency: remove the unneeded slash

Documentation/op-guide/configuration.md, etcdmain/config.go, etcdmain/help.go
It appears that `--metrics="extensive"` flag is only enabling grpc related histogram metrics on server side. Other histogram metrics are always enabled despite this flag.
ref: https://github.com/etcd-io/etcd/blob/c55410ccea53bf613f10f6376ef870d3c81e2eec/embed/etcd.go#L758-L760
Related #11177.
=> doc: clarify metrics flag

etcdctl/ctlv3/command/member_command.go
=> etcdctl: fix member add command

.words, clientv3/balancer/resolver/endpoint/endpoint.go, clientv3/client.go, clientv3/credentials/credentials.go
Fixes https://github.com/etcd-io/etcd/issues/11180
This is a workaround for the gPRC load balancer, which currently uses the "service name" (which the etcd client was setting to the 1st endpoint's hostname or IP) as authority for all credential checks for all the endpoints it load balances against, which does not work well for configurations where etcd servers use a Subject Alternative Names in their certs set to their hostname or IP. We previously added a workaround to fix this problem for IPs (https://github.com/etcd-io/etcd/commit/db61ee106ca9363ba3f188ecf27d1a8843da33ab) but not hostnames.
The workaround keeps track of the endpoints the load balancer dials and overwrites the authority in `ClientHandshake` before the cert checks are performed so that the authority is always the host of …
=> clientv3: Set authority used in cert checks to host of endpoint

etcdctl/ctlv3/command/member_command.go
Cherry pick of #11194 on release-3.4.
#11194: etcdctl: fix member add command
=> Automated cherry pick of #11194 on release-3.4

raft/confchange/confchange.go
confchange: Removed duplicate check in confchange.Simple.
Fixes #11189
=> Removed duplicate check in confchange.Simple

clientv3/snapshot/v3_snapshot.go, etcdserver/apply.go, etcdserver/apply_auth.go, etcdserver/corrupt.go, etcdserver/server.go, etcdserver/util.go, etcdserver/v3_server.go, integration/v3_alarm_test.go, mvcc/kv.go, mvcc/kv_test.go, mvcc/kv_view.go, mvcc/kvstore.go, mvcc/kvstore_bench_test.go, mvcc/kvstore_compaction_test.go, mvcc/kvstore_test.go, mvcc/kvstore_txn.go, mvcc/watchable_store.go, mvcc/watchable_store_bench_test.go, mvcc/watchable_store_test.go, mvcc/watchable_store_txn.go, pkg/traceutil/trace.go, pkg/traceutil/trace_test.go, tools/benchmark/cmd/mvcc-put.go
Fix issue #11166.
This pr creates a standalone trace pkg for record the lifecycle of the request in etcd server. We only enable tracing for range request in this pr. Please refer to issue #11166 for the motivation of it.
Here is the example output of range request with no threshold:
> {"level":"info","ts":"2019-09-25T11:10:35.671-0700","caller":"traceutil/trace.go:116","msg":"trace[1475838163] range","detail":"{range_begin:foo; range_end:fooo; response_count:100000; response_revision:191496;}","duration":"131.11503ms","start":"2019-09-25T11:10:35.540-0700","end":"2019-09-25T11:10:35.671-0700","steps":["trace[1475838163] step 'agreement among raft nodes before linearized reading'  (duration: 56.363µs)","trace[1475838163] step 'authentication'  (duration: 7.283µs)","trace[1475838163] step …
=> Add tracing to range request in etcd server.

Documentation/integrations.md
New tool: ETCD-backup-restore
Etcd-backup-restore is collection of components to backup and restore the etcd. It features
- The periodic full and incremental backups
- Automated restore
- Validation of etcd data directory
- Multi cloud provider support
=> Documenration: Add gardener/etcd-backup-restore to the tools list.

CHANGELOG-3.3.md
See https://github.com/etcd-io/etcd/issues/11241 for details on 3.3.16.
=> CHANGELOG: Note that 3.3.16 is a bad release and add 3.3.17 release notes

scripts/build-binary
=> scripts: avoid release builds on darwin machine.

etcdmain/config.go
Version flag is meant for displaying version and it's a boolean.
It's for an internal use, and we may not want users to set
it in the environment.
Fixes #11210
=> pkg: handle version env variable

scripts/release
Improve checks in release script to prevent mistakes like the one I made in the etcd 3.3.16 release (https://github.com/etcd-io/etcd/issues/11241)
- Before pushing the git version tag for a release version, check that the tag is on HEAD and that the tag is on the release branch. Do this check regardless of if the version tag is already pushed.
- After pushing docker images pull them and run `etcd --version` and check that it reports the correct version.
- After uploading release binaries, download them and run `etcd --version` and check that it reports the correct version
Fixes #11241
=> Add version, tag and branch checks to release script

Documentation/dev-guide/interacting_v3.md, etcdctl/README.md
The current lease time is short and as such can lead to a timeout
error as explained in the related issue which can be confusing.
Fixes #9726
=> doc: add lease time

etcdserver/api/membership/cluster.go, tests/e2e/metrics_test.go
@gyuho We discussed about stripping patch version in cluster version metrics.
```
etcd_cluster_version{cluster_version="3.5"} 1
```
=> etcdserver: strip patch version in cluster version metrics

etcdserver/api/membership/cluster.go, tests/e2e/metrics_test.go
Cherry pick of #11233 #11254 on release-3.4.
#11233: etcdserver: unset old cluster version in metrics
#11254: etcdserver: strip patch version in cluster version
=> Automated cherry pick of #11233 #11254 on release 3.4

etcdserver/server.go
This PR completes #11254. 
For example, if node starts / restarts with existing data dir (which stores cluster version), it goes through this code path. Found in #11261.
=> etcdserver: strip patch version in metrics

etcdserver/server.go
Cherry pick of #11265 on release-3.4.
#11265: etcdserver: strip patch version in metrics
=> Automated cherry pick of #11265 on release 3.4

mvcc/backend/tx_buffer.go
IIRC, `bucketBuffer.merge()`'s logic is to merge the data from `bbsrc` into `bb`, therefore a comment fix.
=> backend: fix comment for bucketBuffer.merge()

etcdserver/membership/cluster.go, etcdserver/membership/metrics.go, etcdserver/server.go, tests/e2e/etcd_release_upgrade_test.go, tests/e2e/metrics_test.go
Cherry pick of #10257 on release-3.3.
#10257: etcdserver/*: add "etcd_cluster_version" metric
=> cherry pick "etcd_cluster_version" metric" (#10257, #11233, #11254, #11265) to release-3.3

e2e/etcd_release_upgrade_test.go, etcdserver/membership/cluster.go, etcdserver/membership/metrics.go, etcdserver/server.go, tests/e2e/metrics_test.go
Cherry pick of #10257, #11233, #11254, #11265 on release-3.2.
XREF: #11261
=> cherry pick "etcd_cluster_version" metric" (#10257, #11233, #11254, #11265) to release-3.2

e2e/etcd_release_upgrade_test.go, e2e/metrics_test.go
Cherry pick PR #11271 instroduced new e2e test failure since "metricsURLScheme" is added when adding "*: support additional '/metrics' endpoints (https://github.com/etcd-io/etcd/pull/8242", which is not in 3.2. Now e2e tests all pass.
cc @jingyih @gyuho
=> e2e test: remove metricsURLScheme from e2e tests

etcdserver/api/rafthttp/stream.go
Fix #11264 
Basically, the bug is due to the failure of `checkStreamSupport`. We need to add stream support to 3.4 and 3.5.
https://github.com/etcd-io/etcd/blob/51b1677d9944e0b28b6b04fab2a64b7a39fe9254/etcdserver/api/rafthttp/stream.go#L635
=> rafthttp: add 3.4.0,3.5.0 stream type

proxy/grpcproxy/watch.go
In watchProxyStream.recvLoop of etcd/proxy/grpcproxy/watch.go, `wps.mu.Lock()` is at line 244 and `wps.mu.Unlock()` is at line 263. However, there is a `continue` at line 257. If this `continue` is executed, the loop will be executed again with `wps.mu` locked, which may cause double lock bug.
***How it is fixed***
Add a `wps.mu.Unlock()` before the `continue` at line 257, so no matter what the control flow is, the status of `wps.mu` will be the same.
=> grpcproxy: Add an Unlock before continue to prevent double lock

pkg/fileutil/lock_windows.go, pkg/srv/srv_test.go
Format errors, according to https://github.com/golang/go/wiki/CodeReviewComments#error-strings
=> fileutil, src: format errors

etcdserver/v3_server.go, integration/v3_auth_test.go
Remove auth validation loop in v3_server.raftRequest(). Re-validation when error ErrAuthOldRevision occurs should be handled on client side.
This is a follow up to #10218.  The client side implementation is tracked in #10408.
=> etcdserver: remove infinite loop for auth in raftRequest

etcdserver/server.go, pkg/fileutil/purge.go, pkg/fileutil/purge_test.go
To prevent purgeFile loop from accidentally acquiring file lock and remove them during server shutdown.
Keyword: "open wal error: wal: file not found"
***Issue***
Normally, server's raft node holds file lock on all the needed wal files. The file lock is only released when a new snapshot is created and the old wal files are no longer needed [1]. During server shutdown, there is a chance that the raft node stops before the purge file loop exists. On stop, raft node closes all the wal files and therefore releases the file lock. So there is a chance that the purge file loop might acquire the file lock [2] and remove some wal files that are still needed by the server. When this happens, server cannot restart due to error:
`C | etcdserver: open wal error: wal: file not found`.
Ref:
[1] …
=> etcdserver: wait purge file loop to finish during shutdown

clientv3/retry_interceptor.go
Fix https://github.com/etcd-io/etcd/issues/11310.
`serverStreamingRetryingStream` is doing all retries.
Logging should be moved there.
/cc @jpbetz @jingyih
=> clientv3: fix retry/streamer error message

lease/lessor_bench_test.go
The pair of `le.mu.Lock()` and `le.mu.Unlock()` is called each time when a loop is executed. However, there is a branch between them, leading to a `break`, and there is no `le.mu.Unlock()` before this `break`.
***Buggy code***
https://github.com/etcd-io/etcd/blob/84e2788c2e41937a851ceb9f365b8e3933b59083/lease/lessor_bench_test.go#L200-L206
=> lease:Add Unlock before break in loop

mvcc/kvstore.go, mvcc/watchable_store.go
There are 2 places in mvcc where a Mutex is not Unlocked before panic. These 2 problems are similar so I use one patch to fix them both.
***Place 1***
```Go
func (s *watchableStore) cancelWatcher(wa *watcher) {
for {
s.mu.Lock()
if s.unsynced.delete(wa) {
slowWatcherGauge.Dec()
break
} else if ...
if !wa.victim {
panic("watcher not victim but not in watch groups")
}
...
s.mu.Unlock()
time.Sleep(time.Millisecond)
}
...
s.mu.Unlock()
}
```
***Place 2***
```Go
func (s *store) restore() error {
...
tx.Lock()
...
for key, lid := range keyToLease {
if s.le == nil {
panic("no lessor to attach lease")
}
...
}
tx.Unlock()
...
}
```
=> mvcc: Add Unlock before panic to prevent double lock

etcdserver/corrupt.go
etcdserver: fix a bug which append object to a new allocated sized slice
https://github.com/etcd-io/etcd/blob/bbe1e78e6242a57d54c4b96d8c49ea1e094c3cbb/etcdserver/corrupt.go#L316
```go
mbs := s.cluster.Members()
pss := make([]peerHashKVResp, len(mbs))
for _, m := range mbs {
if m.ID == s.ID() {
continue
}
pss = append(pss, peerHashKVResp{id: m.ID, eps: m.PeerURLs})
}
```
pss is a new slice with size len(mbs) and append to this slice make the [0:len(mbs)-1] elements are empty and useless. pss := make([]peerHashKVResp, len(mbs)) should be pss := make([]peerHashKVResp, 0, len(mbs))
Fixes #11320
=> etcdserver: fix a bug which append object to a new allocated sized slice

mvcc/kvstore.go
mvcc/kvstore: Optimize compaction
when the number of key-value index is greater than one million, compact take too long and blocks other requests.
Move the “kvindex.Compact” to “fifoSched.Schedule” func
slove conflict for  https://github.com/etcd-io/etcd/pull/11150
=> mvcc/kvstore: Optimize compaction, slove conflict for #11150

etcdserver/v3_server.go, integration/v3_auth_test.go
Cherry pick of #10468 on release-3.4.
#10468: etcdserver: remove auth validation loop
=> Automated cherry pick of #10468 on release-3.4

etcdctl/ctlv3/command/printer_simple.go
Printing to stderr when there is no actual error is not intuitive and makes tool integration more difficult as with bash scripting.
=> etcdctl: Print healthy results to stdout, not stderr

CHANGELOG-3.4.md
Add v3.4.3 and fix v3.4.2 release date.
Fixes #11353
=> CHANGELOG: Add v3.4.3

Documentation/integrations.md
We now have a domain name, so the link has been updated to point to that.
=> Documentation: changed ETCD manager URL

mvcc/metrics.go, mvcc/metrics_txn.go
related #11365 
@logicalhan @jingyih Please have a look.
=> mvcc: add "etcd_mvcc_put_size_in_bytes" metrics

tests/e2e/etcd_release_upgrade_test.go, tests/semaphore.test.bash
Fix e2e test `TestReleaseUpgrade`.
The test will skip only when the cluster version is <3.0. 
> === RUN   TestReleaseUpgrade
--- SKIP: TestReleaseUpgrade (9.81s)
etcd_release_upgrade_test.go:59: #0: v3 is not ready yet (read /dev/ptmx: input/output error (expected "\"etcdcluster\":\"3.5", got ["{\"etcdserver\":\"3.4.0\",\"etcdcluster\":\"3.4.0\"}"]))
etcd_release_upgrade_test.go:59: #1: v3 is not ready yet (read /dev/ptmx: input/output error (expected "\"etcdcluster\":\"3.5", got ["{\"etcdserver\":\"3.4.0\",\"etcdcluster\":\"3.4.0\"}"]))
etcd_release_upgrade_test.go:59: #2: v3 is not ready yet (read /dev/ptmx: input/output error (expected "\"etcdcluster\":\"3.5", got ["{\"etcdserver\":\"3.4.0\",\"etcdcluster\":\"3.4.0\"}"]))
etcd_release_upgrade_test.go:59: #3: v3 is not ready yet (read …
=> e2e: only expect cluster's major version is > 3 in release upgrade test

tests/e2e/cluster_test.go, tests/e2e/ctl_v3_test.go
In #11282, we added a test for cluster version check. However, the cluster in test environment will start servers at the same time so that this test will not cover cluster version compatibility check. 
In this pr, the added test will start servers one by one and then verify the cluster version.
@wenjiaswe @jingyih Please have a look.
=> e2e: add cluster version test with rolling start servers

etcdmain/config.go
Repeated settings have been set in `embed ` package
https://github.com/etcd-io/etcd/blob/f62ea1ceca63bc061e33a1a823e79f5e160a2516/embed/config.go#L497-L504
https://github.com/etcd-io/etcd/blob/f62ea1ceca63bc061e33a1a823e79f5e160a2516/etcdmain/config.go#L380-L386
=> etcdmain: remove duplicate codes.

mvcc/kvstore_compaction.go
=> mvcc/kvstore:fixcompactbug

mvcc/kvstore_compaction.go
Cherry pick of #11400 on release-3.4.
#11400: mvcc/kvstore:fixcompactbug
=> Automated cherry pick of #11400 on release 3.4

.travis.yml, scripts/build-binary
scripts/build-binary: Added TARGET_ARCHS for supporting s390x binary build for release
.travis.yml: Added s390x build in all-build target.
=> scripts/build-binary: Added s390x support for binary release

clientv3/concurrency/mutex.go, clientv3/concurrency/mutex_test.go
check the existence of the lock key before returning the lock api call.
/cc @mitake @aphyr @gyuho
=> concurrency: make lock more reliable

etcdctl/ctlv3/command/make_mirror_command.go
Hi,
the request solves the issue in the title.
two new arguments have been introduced for the make-mirror subcommand:
--dest-user and --dest-password.
both work similar to the --user and --password global arguments.
--dest-user can either be  "$USERNAM:$PASSWORD
or "$PASWORD".
if --dest-password is not provided, the cli will ask for "Destination Password"
the extension is working as expected, i tested it locally.
=> Issue 11383: make mirror accept auth credentials

integration/v3_barrier_test.go, integration/v3_leadership_test.go, integration/v3_lock_test.go, integration/v3_watch_test.go, integration/v3election_grpc_test.go
There are 6 test functions sharing a similar problem: some goroutines in these functions will be leaked in certain cases (like timeout). 
Although `t.Fatal()` is often called in these certain cases, it won't stop the leaking, because ["Calling FailNow does not stop those other goroutines." ](https://golang.org/pkg/testing/#T.FailNow)
This patch stops these leaks no matter what happens in test. 
If the channel operations are not in loop, the fix is to add 1 buffer to the channel. So send won't be blocked and receive will still wait for send.
If the channel operations are in loop, the fix is to create a new channel `stopc`, and put the "possibly-blocking" operation in a `select` together with `case <-stopc:`. Before test return or `t.Fatal()`, …
=> integration: prevent goroutines leaks in test

auth/store.go, tests/e2e/v3_curl_test.go
fix #11414
There is one more concern about the usage of `NoPassword`. If the user is created like `etcdctl user add user:`, should it be inferred as no password? 
@jingyih PHAL
=> auth: fix NoPassWord check when add user

CHANGELOG-3.5.md
=> CHANGELOG-3.5: update for #11427

mvcc/kvstore.go
In kvstore.go, this PR adds log when the following operations fail:
* compactLockfree(scheduledCompact)
* tombstone(lg, rev.main, rev.sub)
Also removed ErrClosed which is not used anywhere.
=> Log warning when compaction encounters error

Documentation/etcd-mixin/mixin.libsonnet, Documentation/etcd-mixin/test.yaml
The `etcdHighNumberOfLeaderChanges` alert had a copy and paste error when it was converted from docs to mixin in PR 10244 - we moved from "increase over 15m > 3" to "rate over 15m > 3" which is not the same (rate is measured per second, so it should have been
"rate over 15m > (3 / 60 / 15)").  As part of fixing that, we need to capture when prometheus starts or when new etcd clusters are captured with a high leader change - i.e. if you start a new
etcd cluster and at the moment prometheus first scrapes you are already at 5 leader changes, we should fire on that transition.
This alert is also now more responsive, so if you get a quick burst of 3 leader changes we'll alert within 5m rather than 15m.
=> Documentation/etcd-mixin: Fix etcdHighNumberOfLeaderChanges

clientv3/watch.go
The check for nil in watcher#RequestProgress is not useful: err has not been assigned.
This PR removes the nil check.
=> clientv3: remove ineffective nil check

clientv3/watch.go
In watchGrpcStream#run, we should log the (non-nil) error when sending request.
=> clientv3: log warning in case of error sending request

tools/benchmark/cmd/txn_put.go
Running `benchmark txn-put --txn-ops 2` will end up with key duplicated error and it will keeps running until finishing all requests.
```
{"level":"warn","ts":"2020-01-06T15:38:55.524-0800","caller":"clientv3/retry_interceptor.go:61","msg":"retrying of unary invoker 
failed","target":"endpoint://client-5c2d0b12-54c5-4421-8da7-ea326407b787/127.0.0.1:2379","attempt":0,"error":"rpc error: code 
= InvalidArgument desc = etcdserver: duplicate key given in txn request"}
```
The root cause is that the key is not unique if flag `--txn-ops` is bigger than `--key-space-size.` 
https://github.com/etcd-io/etcd/blob/e6980b1f9fc008837abb9177e87e893e48d565c1/tools/benchmark/cmd/txn_put.go#L95
This PR added exit at the beginning if it happens.
=> tools/benchmark: exit when txn-ops is larger than key-space-size

clientv3/client.go
In Client#getToken(), the auth variable is declared outside the loop.
This would affect the closing, resulting in resource leak :
```
defer auth.close()
```
This PR moves the variable declaration inside the loop.
Please see the following for demonstration: the two increments on field c were on the same instance. Note the close() is not called at the end of each iteration.
https://play.golang.org/p/kNoi618goai
=> clientv3: Declare auth variable inside the loop

CHANGELOG-3.5.md, etcdctl/ctlv3/command/watch_command.go
Add `--progress-notify` to `etcdctl watch` command. Example output:
```
$ etcdctl watch foo --progress-notify
progress notify: 1272
progress notify: 1789
progress notify: 2001
progress notify: 2001
...
```
=> etcdctl: support progress notify option

mvcc/backend/backend.go
In defragdb(), if there is error and control returns from the func, tmptx is left behind.
This PR rolls back the tmptx in case of err.
=> mvcc: rollback tmptx in case of error

mvcc/backend/backend.go
In the for loop of defragdb(), we call Bucket.ForEach() but don't check the error return.
This PR adds check for the error return and surfaces it.
=> mvcc: check the error return in defragdb

mvcc/index_test.go
This PR fixes error log typo from `nil` to `ErrRevisionNotFound`.
=> mvcc: fix error log typo

clientv3/integration/leasing_test.go
=> clientv3/integration: fix a typo in "TestLeasingTxnRangeCmp"

CHANGELOG-3.3.md, CHANGELOG-3.4.md, CHANGELOG-3.5.md
=> CHANGELOG: add missing changelogs

mvcc/backend/backend.go
PR #11524 was composed ahead of #11525 and it introduced new error variable.
In light of #11525, we should use the same error variable so that the deferred func can properly rollback tmptx.
=> mvcc: use correct error variable in defragdb

proxy/tcpproxy/userspace.go
This PR fixes dup unweighted remote by assigning `nil` to `unweighted` first when the remote srv priority is smaller than the `bestPr`. This is because the `fallthrough` directive will make the adding of remote to weighted or unweighted logic done in the next `case`.
=> proxy/tcpproxy: fix dup unweighted remotes

etcdserver/v3_server.go, integration/v3_auth_test.go
Cherry pick of #10218 #10468 on release-3.3.
#10218: etcdserver: Remove infinite loop in doSerialize
#10468: etcdserver: remove auth validation loop
Fixes #11377
=> Automated cherry pick of #10218 #10468 on release 3.3

vendor/google.golang.org/grpc/attributes/attributes.go, vendor/google.golang.org/grpc/backoff/backoff.go, vendor/google.golang.org/grpc/credentials/go12.go, vendor/google.golang.org/grpc/credentials/tls.go, vendor/google.golang.org/grpc/internal/buffer/unbounded.go, vendor/google.golang.org/grpc/internal/resolver/dns/dns_resolver.go, vendor/google.golang.org/grpc/internal/resolver/dns/go113.go, vendor/google.golang.org/grpc/internal/resolver/passthrough/passthrough.go
Added missing files when I updated grpc version in pr #11522. It should fix recent `go get` issues. 
cc @spzala
=> vendor: add missing grpc files

raft/README.md
```Config``` struct has no package name in README.md
```diff
- c := &Config{
+ c := &raft.Config{
ID:              0x01,
ElectionTick:    10,
HeartbeatTick:   1,
Storage:         storage,
MaxSizePerMsg:   4096,
MaxInflightMsgs: 256,
}
```
=> raft: Fixed missing package name in README.md

clientv3/integration/kv_test.go, clientv3/integration/txn_test.go, etcdserver/server_test.go, mvcc/kvstore_test.go, mvcc/watcher_test.go
There are 6 test functions with a similar problem - some goroutines in these functions will be leaked in certain cases (e.g., timeout).
`testing.T.Fatal()` is often called in these certain cases to stop the test case when failed, but [it does not stop the goroutines](https://golang.org/pkg/testing/#T.FailNow), which result in goroutine leaks.
This patch stops these leaks no matter what happens in test.
The fixes set the length of the channel buffers as 1 so that goroutines will not be blocked when done.
(This patch is similar to #11318)
=> in multiple packages: fixed goroutine leak bugs in tests

client/client_test.go, clientv3/client_test.go, clientv3/txn_test.go, lease/lessor_test.go, pkg/proxy/server_test.go
There are 10 test functions with a similar problem - some goroutines in these functions will be leaked in certain cases (e.g., timeout).
`testing.T.Fatal()` is often called in these certain cases to stop the test case when failed, but [it does not stop the goroutines](https://golang.org/pkg/testing/#T.FailNow), which result in goroutine leaks.
This patch stops these leaks no matter what happens in test.
The fixes set the length of the channel buffers as 1 so that goroutines will not be blocked when done.
(This patch is similar to #11318 and #11569 )
=> in multiple packages: fixed goroutine leak bugs in tests (cont.d)

Documentation/integrations.md
This PR makes the "Libraries and tools" doc more navigable by adding section headers (which show up in the doc's table of contents).
=> Add section headers to integrations.md doc

clientv3/balancer/resolver/endpoint/endpoint.go, clientv3/client.go, clientv3/credentials/credentials.go
fix https://github.com/etcd-io/etcd/issues/11519
verified by tests under tests/docker-dns, tests/dorker-dns-srv, tests/docker-static-ip
@jpbetz @gyuho
=> clientv3: simplify grpc dialer usage.

auth/jwt.go
Fixes #11579.
Need to backport to 3.4.
cc @gyuho @mitake @ae6rt
=> auth: use correct logging level

CHANGELOG-3.5.md
=> CHANGELOG-3.5: add for #11574

clientv3/snapshot/member_test.go, clientv3/snapshot/v3_snapshot_test.go, embed/config.go, embed/config_logging.go, embed/config_test.go, embed/etcd.go, etcdmain/config.go, etcdmain/help.go, etcdserver/config.go, integration/embed_test.go, tools/etcd-dump-metrics/etcd.go
Set zap as default logger. Remove capnslog logger option. Remove deprecated logging flags.
=> *: set zap as default logger, remove capnslog

etcdserver/api/v2v3/store_test.go
This picks up a dropped test error variable in `etcdserver/api/v2v3`.
=> etcdserver/api/v2v3: fix dropped test error

Dockerfile-release.s390x, etcdmain/etcd.go, scripts/build-release.sh, scripts/release
Dockerfile-release.s390x: Added dockerfile for s390x
etcdmain/etcd.go: Added GOARCH for s390x for supported archs
scripts/build-release.sh: Added TARGET_ARCH for s390x
scripts/release: Added TARGET_ARCH for s390x
=> scripts: Added s390x support for docker image release

Makefile
Integration tests always generate data dirs but not clean them up if they are failed. Modify the `clean` target in Makefile to address it.
=> Makefile: cleanup all data dirs.

etcdserver/api/v3rpc/maintenance.go
When no Alarms are found, the response has no header. The header should always
be populated. Some components, like fields printer used by etcdctl, break when
the header is not populated.
Fixes #11581
Signed-off-by: Daniel Lipovetsky <dlipovetsky@d2iq.com>
=> etcdserver: populate ResponseHeader in Alarm method

CONTRIBUTING.md
Fix link to the reporting bugs document
=> contributing: invalid link to "reporting-bugs"

auth/simple_token.go
The strconv.Atoi is equivalent to ParseInt. The index is later used as
uint so we should use strconv.ParseUint.
=> auth: parse to uint instead of int

etcdserver/api/v2discovery/discovery.go, etcdserver/api/v2discovery/discovery_test.go
When an etcd instance attempts to perform service discovery, if a
cluster size with negative value  is provided, the etcd instance
will panic without recovery.
=> Discovery: do not allow passing negative cluster size

embed/config.go
`uint` variables should not be compared to a negative number.
=> embed: don't compare uint to any negative number

etcdserver/apply.go
This is a follow up change of https://github.com/etcd-io/etcd/pull/11536
The newly added `AuthStatus()` RPC doesn't have side effect against the state machine so we should mark it as no side effect request for avoiding replay overhead.
cc @tarcinil
=> etcdserver: mark AuthStatus as no side effect request

etcdserver/apply.go, etcdserver/apply_v2.go, etcdserver/backend.go, etcdserver/cluster_util.go, etcdserver/corrupt.go, etcdserver/metrics.go, etcdserver/quota.go, etcdserver/raft.go, etcdserver/server.go, etcdserver/snapshot_merge.go, etcdserver/storage.go, etcdserver/util.go, etcdserver/v3_server.go
Follow up of #11606 . Remove dependency of `capnslog` under `etcdserver` everywhere except `etcdserver/api`.
=> etcdserver: remove capnslog

etcdctl/ctlv2/command/exec_watch_command.go
index variable is being passed as uint64 so we shouldn't use Int.
Also the if loop is redundant so remove it.
=> etcdctl: use appropriate type conversion

CHANGELOG-3.5.md, etcdctl/ctlv3/command/ep_command.go, etcdctl/ctlv3/command/global.go, etcdmain/config.go, pkg/fileutil/fileutil.go, pkg/fileutil/purge.go, pkg/flags/flag.go, pkg/flags/flag_test.go, pkg/flags/ignored.go, pkg/flags/strings.go, pkg/flags/unique_strings.go, pkg/flags/unique_urls.go, pkg/flags/urls.go, pkg/osutil/interrupt_unix.go, pkg/osutil/osutil.go, pkg/pbutil/pbutil.go
Remove dependency of `capnslog` in `pkg` package.
=> pkg: remove capnslog

CHANGELOG-3.5.md, etcdserver/api/snap/snapshotter.go, mvcc/backend/backend.go
If etcd is terminated during the defrag operation, the `db.tmp` file that it creates can be orphaned. If this happens, the next defragmentation operation that occurs will open the orphaned `db.tmp` instead of creating an empty `db.tmp` file, and starting with a fresh slate, as it should.
Once the defragmentation operation opens `db.tmp` , it traverses all key-values in the main `db` file and writes them to `db.tmp`. Any key-values already in the `db.tmp` file that are not overwritten by this copy remain in it, corrupting the boltdb keyspace. When the defragmentation operation completes successfully, `db.tmp` replaces `db` via file move and the main db file is now corrupt.
Impact:
- the etcd keyspace can be corrupted, see https://github.com/etcd-io/etcd/pull/11613#issuecomment-585458473
- …
=> mvcc/backend: Fix corruption bug in defrag

mvcc/backend/backend.go, snap/snapshotter.go
Cherry pick of #11613 on release-3.3.
#11613: mvcc/backend: Delete orphaned db.tmp files before defrag
=> Automated cherry pick of #11613 to release-3.3

mvcc/backend/backend.go, snap/snapshotter.go
Cherry pick of #11613 on release-3.2.
#11613: mvcc/backend: Delete orphaned db.tmp files before defrag
=> Automated cherry pick of #11613 to release-3.2

etcdserver/api/snap/snapshotter.go, mvcc/backend/backend.go
Cherry pick of #11613 on release-3.4.
#11613: mvcc/backend: Delete orphaned db.tmp files before defrag
=> Automated cherry pick of #11613 to release-3.4

CHANGELOG-3.2.md, CHANGELOG-3.3.md, CHANGELOG-3.4.md
For these backports:
- https://github.com/etcd-io/etcd/pull/11622
- https://github.com/etcd-io/etcd/pull/11623
- https://github.com/etcd-io/etcd/pull/11624
=> changelog: Add #11613 backport to 3.2, 3.3 and 3.4 changelogs

clientv3/integration/lease_test.go, clientv3/integration/leasing_test.go, integration/v3_election_test.go, integration/v3_grpc_test.go
There are four test functions having the same mistake: using `t.Fatal()`or `t.Fatalf()` in a spawned goroutine. This is a misusage because ["FailNow (called by Fatal and Fatalf) must be called from the goroutine running the test or benchmark function, not from other goroutines created during the test."](https://golang.org/pkg/testing/#B.FailNow)
Use a local channel to pass the error or error string. I make channels with buffer or use a select with default, so the concurrency behavior of these test functions won't change after this patch.
=> integration/clientv3: fix 4 API misusage in test functions

etcdserver/api/snap/snapshotter.go
This is follow on to #11613
The removal of db.tmp should not be contingent upon the presence of logger.
=> mvcc/backend: remove db.tmp without checking logger presence

mvcc/backend/backend.go
Check if boltOpenOptions is nil before use it. I believe currently defrag will panic on platforms other than linux.
cc @jpbetz @gyuho @wenjiaswe
=> mvcc/backend: check for nil boltOpenOptions

mvcc/backend/backend.go
Cherry pick of #11630 on release-3.4.
#11630: mvcc/backend: check for nil boltOpenOptions
=> Automated cherry pick of #11630 to release-3.4

mvcc/backend/backend.go
Cherry pick of #11630 on release-3.3.
#11630: mvcc/backend: check for nil boltOpenOptions
=> Automated cherry pick of #11630 to release-3.3

etcdserver/api/etcdhttp/peer.go, etcdserver/api/etcdhttp/peer_test.go, etcdserver/corrupt.go
Currently, corruption check does not work when mTLS is enabled between peers. (See #10934)
With this PR, corruption check uses the existing peer-to-peer http communication framework to get peer hashKV.
Manually tested it works. Example server log:
```
09:18:14 etcd1 | {"level":"info","ts":"2020-02-13T09:18:14.234-0800","caller":"etcdserver/corrupt.go:130","msg":"enabled corruption checking","local-member-id":"d05e7521f6de6bab","interval":"10s"}
09:18:14 etcd3 | {"level":"info","ts":"2020-02-13T09:18:14.245-0800","caller":"etcdserver/corrupt.go:130","msg":"enabled corruption checking","local-member-id":"3fb0bb8f51408909","interval":"10s"}
09:18:14 etcd2 | {"level":"info","ts":"2020-02-13T09:18:14.257-0800","caller":"etcdserver/corrupt.go:130","msg":"enabled corruption …
```
=> etcdserver: make corruption check work under peer mTLS

etcdserver/api/etcdhttp/peer.go, etcdserver/api/etcdhttp/peer_test.go, etcdserver/corrupt.go
=> Automated cherry pick of #11621 to release-3.4

pkg/transport/listener_test.go, pkg/transport/timeout_dialer_test.go, pkg/transport/timeout_listener_test.go
This is a very simple patch. There are 3 test functions with similar problems: some spawned goroutines will be leaked in certain cases (like timeout). 
Although `t.Fatal()` is often called in these certain cases, it won't stop the leaking, because ["Calling FailNow does not stop those other goroutines." ](https://golang.org/pkg/testing/#T.FailNow) This patch stops these leaks no matter what happens in test. 
This patch is similar to #11318
For most blocking channels, adding 1 buffer to them is enough. This can make send operations unblockable. Semantics are not influenced, because there is no instruction after send.
For the last instruction `stop <- struct{}{}` at line 85 of timeout_dialer_test.go, I moved it into a deferred function, so it will …
=> transport: simple fix in test functions to prevent goroutine leak

etcdserver/api/membership/cluster.go, etcdserver/api/membership/cluster_test.go
When promoting a learner member we should not count already a voting
member, but take only into account the number of existing voting
members and their current status (started, unstarted) when taking the
decision whether a learner member can be promoted.
Before this change, it was impossible to grow from a quorum N to a N+1
through promoting a learning member.
Fixes: #11633
---
Note: it would be good to add tests to https://github.com/etcd-io/etcd/blob/b64b36ae9f74fa26784a1589b668d8358578439d/etcdserver/server.go#L1490-L1520 and https://github.com/etcd-io/etcd/blob/b64b36ae9f74fa26784a1589b668d8358578439d/etcdserver/server.go#L1522-L1543 as well, so we test other promotion traits. As far as I could see there are no tests at all regarding learning member promotion (or I couldn't find …
=> Fix quorum calculation when promoting a learner member

etcdserver/api/membership/cluster.go, etcdserver/api/membership/cluster_test.go
Cherry pick of #11640 on release-3.4.
#11640: etcdserver: fix quorum calculation when promoting a learner
=> Automated cherry pick of #11640 on release-3.4

etcdctl/ctlv3/command/member_command.go
I just realized we could simply use the members information in member add response, which is guaranteed to be up to date.
We tried to fix `etcdctl member add` in #11194. But it does not solve the problem if the client balancer is provided with 2 endpoints and balancer is doing round robin.
Fixes #11554
=> etcdctl: fix member add (again...)

auth/metrics.go, auth/store.go, auth/store_test.go, etcdserver/backend.go, etcdserver/server.go, etcdserver/server_test.go, mvcc/kv_test.go, mvcc/watchable_store.go, mvcc/watchable_store_bench_test.go, mvcc/watchable_store_test.go, mvcc/watcher_bench_test.go, mvcc/watcher_test.go, tools/etcd-dump-db/backend.go
=> auth/store: save consistentIndex to fix a data corruption bug

CHANGELOG-3.4.md, CHANGELOG-3.5.md
#11621 was backported and released in 3.4.4. Adding the corresponding log entry to CHANGELOG. Also moving an previous log in CHANGELOG-3.4 to the right spot.
=> CHANGELOG: update from #11621

clientv3/balancer/picker/err.go, clientv3/balancer/picker/roundrobin_balanced.go, clientv3/balancer/resolver/endpoint/endpoint.go
clientv3: Fix grpc-go (v1.27.0) incompatible modification of balancer/resolver API.
Modify the API changed by balancer / resolver to ensure consistency with grpc-go (v1.27.0), otherwise clientv3 will not be able to be pulled by go mod, which will affect the direct use of users.
References:
1. [balancer/resolver: remove temporary backward-compatibility type aliases](https://github.com/grpc/grpc-go/pull/3309)
2. [Notice: Upcoming Experimental Balancer/Resolver API Changes](https://github.com/grpc/grpc-go/issues/3180)
Fixes https://github.com/etcd-io/etcd/issues/11563
=> clientv3: Fix grpc-go(v1.27.0) incompatible changes to balancer/resolver.

proxy/grpcproxy/metrics.go
The gRPC proxy metrics handler will panic on error, return instead.
=> proxy/grpcproxy: add return on error for metrics handler

auth/store.go, etcdserver/apply.go, etcdserver/util.go
There are three minor changes：
1. add warning log for troubleshooting when auth revision is inconsistent(current,no log is printed when node failed to apply command because of inconsistent auth revision).
for example.
`
17:04:56 etcd1 | {"level":"warn","ts":"2020-03-03T17:04:56.173+0800","caller":"auth/store.go:856","msg":"request auth revision is less than current node auth revision","auth store revision":23,"request auth revision":19,"request key":"hello","error":"auth: revision in header is old"}
`
2. no need to save consistentIndex in NewAuthStore(no command is executed) and  it will cause the error log to be printed when starting an empty etcd cluster.
3. print warning log when failed to apply request.
=> *: optimize auth/etcdserver logs to facilitate troubleshooting data inconsistency

.words, clientv3/client.go, clientv3/ctx.go, clientv3/ctx_test.go, clientv3/integration/kv_test.go, clientv3/integration/watch_test.go, clientv3/retry_interceptor.go, etcdserver/api/v3rpc/interceptor.go, etcdserver/api/v3rpc/metrics.go, etcdserver/api/v3rpc/rpctypes/md.go, integration/cluster.go
- `WithRequireLeader` was overwriting existing metadata key-values
- Add `client-api-version` metadata (useful for implementing client-version based server code)
e.g. Example metadata output in server side:
> map[:authority:[localhost:64304770101484282250] client-api-version:[3.5] content-type:[application/grpc] user-agent:[grpc-go/1.26.0]]
=> clientv3: fix "hasleader" metadata key, embed client version

embed/etcd.go, etcdmain/grpc_proxy.go, etcdserver/api/etcdhttp/base.go, etcdserver/api/etcdhttp/metrics.go, etcdserver/api/v2http/client.go, proxy/grpcproxy/health.go
To make it easier to root-cause when /health check fails.
For example, we are using load balancer to health check
each etcd instance, and when one etcd node gets terminated,
it's hard to tell whether etcd "server" was really failing
or client (or load balancer") failed to reach the etcd cluster
which is also failure in load balancer health check.
> {"level":"info","ts":"2020-03-18T10:56:05.206-0700","caller":"etcdhttp/metrics.go:65","msg":"/health OK","http-error-code":200}
=> *: log server-side /health checks

.words, clientv3/ctx.go
```
=== RUN   TestWatchOverlapContextCancel
Write at 0x00c42110dd40 by goroutine 99:
runtime.mapassign()
/usr/local/go/src/runtime/hashmap.go:485 +0x0
github.com/coreos/etcd/clientv3.metadataSet()
/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/ctx.go:61 +0x8c
github.com/coreos/etcd/clientv3.withVersion()
/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/ctx.go:47 +0x137
github.com/coreos/etcd/clientv3.newStreamClientInterceptor.func1()
/go/src/github.com/coreos/etcd/gopath/src/github.com/coreos/etcd/clientv3/client.go:309 +0x81
google.golang.org/grpc.NewClientStream()
/go/src/github.com/coreos/etcd/gopath/src/google.golang.org/grpc/stream.go:101 +0x10e …
```
=> clientv3: fix racy writes to context key

mvcc/watchable_store.go
Method `kvsToEvents` can take a long time if a large number of events need to be synchronized. However, this method does not access any shared resources, so it no need to hold the tx lock when executing. So we can move it outside to reduce lock holding time.
=> mvcc: no need to hold tx lock when converting kvs to watch events

etcdserver/api/v2store/store.go, etcdserver/server.go, functional/tester/stresser_lease.go, mvcc/kvstore_test.go
To fix the following files of goroutines typos 
etcdserver/api/v2store/store.go
etcdserver/server.go
functional/tester/stresser_lease.go
mvcc/kvstore_test.go
=> *: fix goroutines typos

auth/store.go, auth/store_test.go
we learn lessons from issue #11689, if a feature that may update auth-revision or revision is not compatible with older versions, it is possible to cause data inconsistency. so we have to ensure RoleGrantPermission is compatible with older versions, just revert it to old versions. 
@mitake @jingyih
=> auth: ensure RoleGrantPermission is compatible with older versions

lease/lessor.go
=> lease: fix memory leak in LeaseGrant

mvcc/kvstore.go, test
Cherry pick of #11330 on release-3.4.
#11330: mvcc/kvstore:when the number key-value is greater than one
Modified .`/test` to automatically detect branch when finding merge base. (Thanks to @jpbetz)
=> Cherry pick of #11330 on release-3.4

auth/store.go
Optimize lock scope for CheckPassword, to improve authentication performance in concurrent scenarios 
when enable auth and using authentication based password.
`etcd version: 3.4.3`
When enable auth and using authentication based password, we found that etcd's read and write performance dropped sharply, and even a large number of timeouts occurred. After our investigation, we found that time is spent on Authenticate.
Furtherly, we found that the CompareHashAndPassword function will take tens of milliseconds. This function will block the lock of CheckPassword,  which can cause certain requests to block for tens of seconds when there is thousounds of concurrent connection.
(We have add some debug log in etcd. As shown below, the time unit is millisecond)
Moving CompareHashAndPassword out of …
=> auth: dramatically improve checkPassword performance

CHANGELOG-3.5.md, pkg/ioutil/pagewriter.go, wal/encoder.go, wal/metrics.go, wal/repair.go, wal/wal.go
While we track latencies around WAL fsync, actual number of written data aren't being tracked. This will be useful when we look into the write throughput of etcd.
=> wal: add "etcd_wal_writes_bytes_total"

raft/rafttest/interaction_env_handler_raft_log.go, raft/rafttest/interaction_env_logger.go, raft/rafttest/network.go
This removes four unused functions from `raft/rafttest`.
=> raft/rafttest: Prune Unused Functions

clientv3/snapshot/v3_snapshot.go, pkg/fileutil/fileutil.go, pkg/fileutil/fileutil_test.go
=> pkg, clientv3: etcdctl can snaprestore when data-dir exits but empty

etcdserver/apply.go, etcdserver/apply_auth.go, etcdserver/corrupt.go, etcdserver/v3_server.go, pkg/traceutil/trace.go, pkg/traceutil/trace_test.go
Here is an example output of a txn request. 
Request:
```
cmp := clientv3.Compare(clientv3.Value("foo"), "=", "bar");
op1 := clientv3.OpGet("foo", clientv3.WithRange("fooo"))
op2 := clientv3.OpPut("txn", "put")
op3 := clientv3.OpPut("put","txn")
op4 := clientv3.OpTxn([]clientv3.Cmp{cmp}, []clientv3.Op{op1}, []clientv3.Op{})
txn := cli.Txn(ctx).If(cmp).Then(op1, op2, op3, op4)
```
Output:
```
{"level":"info","ts":"2020-01-02T15:27:52.215-0800","caller":"traceutil/trace.go:166","msg":"trace[1023984242] transaction",
"detail":"{read_only:false; response_revision:7; number_of_response:4; }","duration":"440.713µs","start":"2020-01-02T15:27:52.215-0800","end":"2020-01-02T15:27:52.215-0800",
"steps":["trace[1023984242] 'process raft request'  (duration: 195.497µs)",
"trace[1023984242] 'compare' …
```
=> etcdserver: add trace for txn request

etcdctl/ctlv3/command/get_command.go
Sometimes we only want to know how many objects under a specified prefix, instead of extracting the whole keys or values.
=> etcdctl: support query count only of specified prefix

etcdserver/api/v3rpc/watch.go
This pr fixes #11708
The issue is easy to fix, but hard to reproduce. It happens only when:
1. Client successfully established a watch stream
2. Client issues another watch request which results in a `permission denied` response
3. After that, every watch request that reuses the same stream will hang forever
@jingyih @gyuho @xiang90
=> etcdserver: watch stream got closed if one watch request is not permitted

etcdserver/api/v3rpc/watch.go
Cherry pick of #11754 on release-3.4.
#11754: etcdserver: watch stream got closed once one request is not
=> Automated cherry pick of #11754 on release-3.4

.github/stale.yml
There are open issues and pull requests that are years old on the etcd
repo and hundreds of issues that remain open.
Unfortunately it is just far outside the ability of the maintainer team
to take care of all of these issues manually.
So, follow the lead of Kubernetes and introduce a bot that closes PRs
and issues if they are stale.
See more information here: https://github.com/probot/stale#probot-stale
=> github: stale.yml initial commit

raft/node_test.go, raft/raft.go
Signed-off-by: Fullstop000 <fullstop1005@gmail.com>
In current raft implementation, `from` in a message will be overwritten to `r.id` when `r.send(msg)`  is called which might cause some issues. 
For example, assuming establishing a raft cluster with three nodes ABC where C is the Leader. A client sends a `MsgReadIndex` to node A and A redirects the msg to B (`m.From = A`). However, B is a stale leader in the view of A so that B also redirects the msg to C with `m.From = B`. In this case, when `ReadIndex` finishes in C, only B has a chance to receive a `MsgReadIndexResp` because of `m.From` in the `MsgReadIndex`. And the client might be waiting for the read response from A forever since A never receives a `MsgReadIndexResp`.
=> raft: only redirect a msg when `from` is not None

auth/metrics.go, auth/store.go, auth/store_test.go, etcdserver/apply.go, etcdserver/backend.go, etcdserver/server.go, etcdserver/server_test.go, etcdserver/util.go, integration/v3_watch_test.go, mvcc/kv_test.go, mvcc/watchable_store.go, mvcc/watchable_store_bench_test.go, mvcc/watchable_store_test.go, mvcc/watcher_bench_test.go, mvcc/watcher_test.go
Cherry pick of #11652 #11670 #11710 on release-3.3.
#11652: *: fix auth revision corruption bug
#11670: optimize auth/etcdserver logs to facilitate troubleshooting data inconsistency
#11710: auth: ensure RoleGrantPermission is compatible with older
=> Automated cherry pick of #11652 #11670 #11710

CHANGELOG-3.5.md, mvcc/index.go, mvcc/kvstore_test.go, mvcc/kvstore_txn.go, tests/e2e/ctl_v3_kv_test.go
if there are too much keys(> 1 millions),count-only range is very slow(slice expansion) and cost too much memory. it is not necessary to return revpairs,so we can do a small optimization to reduce overhead.
=> mvcc: reduce count-only range overhead

embed/config_test.go, embed/etcd.go
Handle negative value input which currently gives a runtime error.
=> embed: fix compaction runtime err

CHANGELOG-3.5.md, etcdserver/backend.go, etcdserver/server.go
if there are too much keys(> 1 millions),etcd is slow to start. After my investigation, 90% of the time is spent on mvcc restore(rebuild index tree), 9% is spent on open backend db, and because the index tree has a global lock(idx.Insert), there is no room for optimization. however,restore index is called twice, it is unreasonable.we can benefit from  pr #11699  and cut time in half.
=> etcdserver: significantly reduces start-up time

etcdserver/api/membership/cluster.go, etcdserver/api/membership/store.go
Issue #11716
As a field of cluster, downgrade info is stored in backend.
This PR added the getter and setter of it.
@gyuho @jingyih
=> [Etcd Downgrade] Store downgrade info to backend

CHANGELOG-3.5.md
=> CHANGELOG: update from #11711

CHANGELOG-3.4.md
The gRPC-go bump to 1.24 outlined in changelog for 3.4.2 never actually happened, removing.
ref
https://github.com/etcd-io/etcd/blob/f1eca4e1fa5de962ff8079af836bb390e88d1f4c/vendor/google.golang.org/grpc/version.go#L22
=> CHANGELOG-3.4: revert invalid gRPC-go dependency bump

etcdmain/etcd.go, pkg/fileutil/fileutil.go, pkg/fileutil/fileutil_test.go, pkg/transport/listener.go
=> pkg: check file stats

CHANGELOG-3.5.md
Signed-off-by: Nirman Narang <narang@us.ibm.com>
Adding update from PRs #11548 and #11358 to CHANGELOG-3.5.md.
=> CHANGELOG-3.5: update from #11548 and #11358

CHANGELOG-3.5.md, wal/decoder.go, wal/wal.go, wal/wal_test.go
=> wal: check out of range slice in "ReadAll", entry limits in "decodeRecord"

MAINTAINERS
Brandon is no longer at Red Hat. Use a different email.
=> MAINTAINERS: update @philips email

wal/wal.go, wal/wal_test.go
The Create function doc says a WAL is ready to read right after but it results in a panic. A returned WAL from call to Open is ready to read which is correctly mentioned in the Open func.
=> wal: fix panic when decoder not set

wal/wal.go
In Create(), when w.renameWAL() returns non-nil error, we should check whether w is nil before accessing w.dir
This PR adds the nil check.
=> Use known dir-path in log message

clientv3/client_test.go
When a go loop launches goroutines, it is a common mistake to assume
that the routines can reference the loop value from their specific loop
iteration. Actually, all goroutines share the same reference to the loop
veriable, and they typically all see the last value. To correct this, the loop variable must be captured as a parameter to the anonymous func.
=> clientv3: fix DialTimeout race condition

mvcc/kv_test.go
When a go loop launches goroutines, it is a common mistake to assume
that the routines can reference the loop value from their specific loop
iteration. Actually, all goroutines share the same reference to the loop
veriable, and they typically all see the last value. To correct this, the loop variable must be captured as a parameter to the anonymous func.
=> mvcc: fix race in TestKVTxnBlockWriteOperations

etcdctl/ctlv3/ctl.go, etcdmain/grpc_proxy.go
The options are disabled default. This PR just add warnings to their descriptions.
cc @xiang90 @spzala @gyuho @philips
=> etcdctl, etcdmain: warn about --insecure-skip-tls-verify options

security/security-release-process.md
emails here can be an unnecessary maintainance. The provided
GitHub IDs have the latest emails and also the process has
security@etcd.io mentioned in this doc as a contact email.
=> doc: remove Product Security Committee individual emails

clientv3/snapshot/v3_snapshot.go
In v3Manager#saveDB, db file should always be closed upon return from the method.
Currently if db.Seek() call fails (around line 353), db is not closed.
=> clientv3: v3Manager#saveDB should always close db file

Documentation/op-guide/security.md
=> Documentation: note on the policy of insecure by default

glide.lock, glide.yaml, vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/convert.go, vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go, vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_json.go, vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_jsonpb.go, vendor/github.com/grpc-ecosystem/grpc-gateway/runtime/marshaler.go, vendor/go.uber.org/atomic/atomic.go, vendor/go.uber.org/multierr/error.go
Update `grpc-gateway` to v1.3.1 to fix a bug where watch request through a websocket hangs forever.
=> etcdserver: fix the missing delimiter on a transfer-encoding:chunked http response

etcdserver/v3_server.go
@xiang90 This is a PR for not recording password in a WAL entry as a plain text. Because of the stateful nature of simple token, making the entire authentication process as a serializable process is difficult. So I think this would be the simplest way. How do you think?
=> etcdserver: don't let InternalAuthenticateRequest have password

clientv3/watch.go, integration/v3_watch_test.go
Currently, watch cancel requests are only sent to the server after a
message comes through on a watch where the client has cancelled. This
means that cancelled watches that don't receive any new messages are
never cancelled; they persist for the lifetime of the client stream.
This has negative connotations for locking applications where a watch
may observe a key which might never change again after cancellation,
leading to many accumulating watches on the server.
By cancelling proactively, in most cases we simply move the cancel
request to happen earlier, and additionally we solve the case where the
cancel request would never be sent.
Fixes #9416
Heavy inspiration drawn from the solutions proposed there.
=> clientv3: cancel watches proactively on client context cancellation

CHANGELOG-3.5.md, mvcc/kvstore.go
gorountine A(restore snapshot):
```
Apr 26 18:18:57 node-testbash[412644]: go.etcd.io/etcd/pkg/schedule.(*fifo).run(0xc260f6c240)
Apr 26 18:18:57 node-testbash[412644]: /tmp/etcd-release-3.4.7/etcd/release/etcd/etcdserver/server.go:1048 +0x3c
Apr 26 18:18:57 node-testbash[412644]: go.etcd.io/etcd/etcdserver.(*EtcdServer).run.func8(0x1278e20, 0xc29824e040)
Apr 26 18:18:57 node-testbash[412644]: /tmp/etcd-release-3.4.7/etcd/release/etcd/etcdserver/server.go:1102 +0x5d
Apr 26 18:18:57 node-testbash[412644]: go.etcd.io/etcd/etcdserver.(*EtcdServer).applyAll(0xc0002a6580, 0xc00033efa0, 0xc0c0805700)
Apr 26 18:18:57 node-testbash[412644]: /tmp/etcd-release-3.4.7/etcd/release/etcd/etcdserver/server.go:1207 +0xc2c
Apr 26 18:18:57 node-testbash[412644]: …
```
=> mvcc: fix a deadlock bug in mvcc

mvcc/kvstore.go
Cherry pick of #11817 on release-3.3.
#11817: mvcc: fix deadlock bug
=> Automated cherry pick of #11817 on release-3.3

raft/node.go
In  node#run(), the nested loop is used to find matching id:
```
for _, sl := range [][]uint64{cs.Voters, cs.VotersOutgoing} {
for _, id := range sl {
```
When id is found, we can come out of the loop.
=> raft: break out of nested loop when raft id is found

etcdserver/server.go
No need to compute the request size limit everytime in runtime
=> etcdserver: compute max request bytes humanized string once

clientv3/watch.go, integration/v3_watch_test.go, mvcc/watchable_store.go
The watch count metrics are not robust to duplicate cancellations. These
cause the count to be decremented twice, leading eventually to negative
counts. We are seeing this in production. The duplicate cancellations
themselves are not themselves a big problem (except performance), but
they are caused by the new proactive cancellation logic (#11850) which
cancels proactively even immediately before initiating a Close, thus
nearly guaranteeing a Close-cancel race, as discussed in
watchable_store.go. We can avoid this in most cases by not sending a
cancellation when we are going to Close.
The client change is simply for the benefit of those using the 3.5 client against an old cluster - we could remove it if desired. The metrics fix on the server side is sufficient, and that's the real bug …
=> mvcc: avoid negative watcher count metrics

Dockerfile-release, Dockerfile-release.arm64, Dockerfile-release.ppc64le, Dockerfile-release.s390x
Updates the base image for all arch releases to the new location (us.gcr.io/k8s-artifacts-prod/build-image) as well as to the latest version (v2.1.0). This should fix a number of vulnerabilities that are in the 1.0.0 base image release.
=> chore(Dockerfile-release): Update base image to use new debian-base:v2.1.0

raft/raft.go
In raft#restore, when raft id is found, we should break out of the nested loop.
=> raft: break out of nested loop when id is found

.words, clientv3/maintenance.go, clientv3/snapshot/v3_snapshot.go, etcdserver/api/v3rpc/maintenance.go
We've seen some cases where hash was missing from snapshots (still investigating).
This makes sure `clientv3/snapshot` downloads checksum from the server.
=> *: make sure snapshot save downloads SHA256 checksum

etcdserver/api/snap/snapshotter.go
In Snapshotter#ReleaseSnapDBs, when there is error parsing index or removing file, we should continue with the next snap db file.
=> etcdserver: continue releasing snap db in case of error

etcdserver/api/snap/snapshotter.go
In Snapshotter#snapNames(), cleanupSnapdir(names) may clean up orphaned defragmentation file(s).
Such files should be excluded from checkSuffix() call.
=> etcdserver: snapNames() should exclude orphaned defragmentation file

CHANGELOG-3.5.md, wal/wal.go, wal/wal_test.go
=> wal: fix crc mismatch crash bug

clientv3/watch.go
Currently watcher.mu is declared as RWMutex.
However, read lock is never taken.
This PR changes its type to Mutex.
=> clientv3: use Mutex for watcher lock

auth/store.go
Cherry pick of #11735 on release-3.4.
#11735: auth: optimize lock scope for CheckPassword
=> Automated cherry pick of #11735 on release-3.4

clientv3/watch.go
Currently watcher#Watch() is recursive.
This PR replaces the recursion with a for loop.
Prior to the PR,
```
close(closeCh)
```
is placed at the end of Watch().
For recursion involving Watch(), the above code is not executed, except for the most deeply nested Watch(). Meaning closeCh is not closed.
This bug is fixed with this PR
=> clientv3: non-recursive Watch()

auth/store.go, etcdserver/v3_server.go
=> etcdserver: fix LeaseRevoke may fail to apply when authentication is enabled and upgrading cluster from etcd-3.2 to etcd-3.3

etcdserver/server.go
In **"etcdserver/server.go"**，function **“applyEntryNormal”** calls **“applyV2Request“** ，and **“applyV2Request”** calls **“Put”** when etcd application  starts.
There is log output in this function  (**"Put"**), or log will be added later, but **"a.lg" is nil** when function is executed causes panic.
Test :
You can add  **' fmt.Println(a.lg, "-----------applierV2store Put 67--------") '**  to the 
'func (a *applierV2store) Put(r *RequestV2) Response'
=> etcdserver: Missing the cfg.Logger causes panic

etcdserver/api/v2v3/watcher.go
In v2v3Store#mkV2Events, act and key fields are accessed without nil check.
This PR adds proper nil check before accessing the fields.
=> Check events against nil

clientv3/client.go
In newClient, if there is no endpoint, we should cancel the client before returning error.
Also fixed typo in error message.
=> clientv3: cancel the client if there is no endpoint

embed/config.go, embed/etcd.go, etcdmain/config.go, etcdserver/backend.go, etcdserver/config.go, etcdserver/raft.go, etcdserver/storage.go, mvcc/backend/backend.go, wal/wal.go
This makes it possible to run an etcd node for testing and development
without placing lots of load on the file system.
Fixes #11930
=> etcdserver, et al: add --unsafe-no-fsync flag

CHANGELOG-3.5.md, clientv3/snapshot/v3_snapshot.go, etcdserver/server.go, lease/leasehttp/http_test.go, lease/lessor.go, lease/lessor_bench_test.go, lease/lessor_test.go
Consider the following scenario:
```
etcdctl lease grant 10
lease 3269723c5a733e05 granted with TTL(10s)
etcdctl lease grant 15
lease 3269723c5a733e07 granted with TTL(15s)
restart etcd
```
we can see some error log:
```
20:27:54 etcd1 | {"level":"warn","ts":"2020-05-22T20:27:54.599+0800","caller":"etcdserver/util.go:120","msg":"failed to apply request","took":"35.702µs","request":"header:<ID:3632560177992121862 > lease_grant:<ttl:10-second id:3269723c5a733e05>","response":"size:0","error":"lease already exists"}
20:27:54 etcd1 | {"level":"warn","ts":"2020-05-22T20:27:54.599+0800","caller":"etcdserver/util.go:120","msg":"failed to apply request","took":"5.126µs","request":"header:<ID:3632560177992121864 > lease_grant:<ttl:15-second id:3269723c5a733e07>","response":"size:0","error":"lease …
```
=> lease: ensure grant/revoke won't be applied repeatedly after restarting etcd

raft/node.go
This PR drops the read of raft.lead in node#Tick() so that the following data race is avoided:
```
Write at 0x00c0008af9b0 by goroutine 426:
go.etcd.io/etcd/v3/raft.(*raft).reset()
/go/src/go.etcd.io/etcd/raft/raft.go:610 +0x85
go.etcd.io/etcd/v3/raft.(*raft).becomeCandidate()
/go/src/go.etcd.io/etcd/raft/raft.go:710 +0xdb
go.etcd.io/etcd/v3/raft.(*raft).campaign()
/go/src/go.etcd.io/etcd/raft/raft.go:785 +0xfa
go.etcd.io/etcd/v3/raft.(*raft).Step()
/go/src/go.etcd.io/etcd/raft/raft.go:928 +0x1615
go.etcd.io/etcd/v3/raft.(*raft).tickElection()
/go/src/go.etcd.io/etcd/raft/raft.go:665 +0x22e
go.etcd.io/etcd/v3/raft.(*raft).tickElection-fm()
/go/src/go.etcd.io/etcd/raft/raft.go:660 +0x41
go.etcd.io/etcd/v3/raft.(*RawNode).Tick()
/go/src/go.etcd.io/etcd/raft/rawnode.go:59 …
```
=> raft: avoid data race by not reading raft.lead

etcdmain/gateway.go
Best effort approach to detect if the tcp gateway points to itself. Or the gateway might direct traffic to itself and cause an endless traffic loop.
=> etcdmain: best effort detection of self pointing in tcp proxy

etcdserver/api/v2store/store.go, etcdserver/api/v2store/store_ttl_test.go
For store#CompareAndSwap and store#Update, the return value from Write() was ignored.
This PR adds check of the error return.
=> etcdserver: check the error return from Write()

etcdserver/api/v2store/store.go
Currently store#Clone() takes write lock.
This is not needed since cloning only involves reading the current store.
=> etcdserver: take read lock when cloning store

pkg/fileutil/dir_unix.go, pkg/fileutil/dir_windows.go, pkg/fileutil/fileutil.go
Permissions on Windows is different from *nix. This PR separates them.
@spzala
=> pkg: Fix dir permission check on Windows

embed/config.go, embed/etcd.go, etcdmain/config.go, etcdserver/backend.go, etcdserver/config.go, etcdserver/raft.go, etcdserver/storage.go, mvcc/backend/backend.go, wal/wal.go
Cherry pick of #11946 on release-3.4.
#11946: etcdserver, et al: add --unsafe-no-fsync flag
While the policy is usually to NOT backport features to stable branches, I think we should consider making an exception for this given that (a) it is intended to be used in test and (b) it has a lot of promise to speed up tests significantly. If this makes a noticeable dent in k8s test times, and I think it might, it could really help the project.
cc @gyuho @jingyih @dims
=> Automated cherry pick of #11946

CHANGELOG-3.5.md, mvcc/index.go, mvcc/kv_test.go, mvcc/kvstore_test.go, mvcc/kvstore_txn.go
if there are too many keys(key,rangeEnd), even if we set RangeOptions.limit to 1,range request is very expensive and it will result in oom. this pr will push down RangeOptions.limit argv into index tree to reduce memory overhead. @gyuho
=>  mvcc: push down RangeOptions.limit argv into index tree to reduce memory overhead

etcdmain/etcd.go
Create a new logger if one not found.
If an incorrect flag is provided on command line, e.g. #etcd help, it throws a nil pointer.
=> logging: create logger to prevent nil pointer

embed/serve.go
embed: Replaced a number with Go http constant
To realize typical advantage of using a constant
=> Use http constant instead of a number

CHANGELOG-3.5.md, pkg/fileutil/fileutil.go
when I try to upgrade etcd cluster from v3.4 to v3.5, I failed to start etcd etcd process.  I have to find solution from code, pr #11798 introduces this issue.  it is better if we can print detail desired file permission in error log and add breaking change doc for it. thanks. @spzala 
```
Jun 10 13:50:45 VM-test-ubuntu bash[11974]: {"level":"fatal","ts":"2020-06-10T13:50:45.510+0800","caller":"etcdmain/etcd.go:197","msg":"discovery failed","error":"cannot access data directory: directory \"/data/etcd.data\" exist without desired file permission. \"drwxr-xr-x\"","
```
=> pkg/fileutil: optimize file stats error

etcdserver/metrics.go
=> etcdserver:set FDUsage ticker to 10 minute from 5 seconds.

CHANGELOG-3.5.md, etcdserver/api/etcdhttp/metrics.go, tests/e2e/ctl_v3_alarm_test.go, tests/e2e/metrics_test.go
Fix issue #11599 . @gyuho 
```
{"health":"false","reason":"NOSPACE"}
```
=> etcdserver/api/etcdhttp: add reason field for /health response

etcdctl/ctlv3/ctl.go, etcdmain/grpc_proxy.go
Cherry pick of #11841 on release-3.4.
#11841: etcdctl, etcdmain: warn about --insecure-skip-tls-verify
=> Automated cherry pick of #11841

etcdserver/v3_server.go
Cherry pick of #11818 on release-3.4.
#11818: etcdserver: don't let InternalAuthenticateRequest have
=> Automated cherry pick of #11818

etcdserver/api/v2discovery/discovery.go, etcdserver/api/v2discovery/discovery_test.go
Cherry pick of #11608 on release-3.4.
#11608: Discovery: do not allow passing negative cluster size
=> Automated cherry pick of #11608

auth/store.go
Cherry pick of #11795 on release-3.4.
#11795: auth: a new error code for the case of password auth against
=> Automated cherry pick of #11795

wal/wal.go, wal/wal_test.go
Cherry pick of #11807 on release-3.4.
#11807: wal: fix panic when decoder not set
=> Automated cherry pick of #11807

etcdserver/api/v3rpc/watch.go
Cherry pick of #11754 on release-3.3.
#11754: etcdserver: watch stream got closed once one request is not
=> Automated cherry pick of #11754 on release-3.3

auth/simple_token.go, auth/simple_token_test.go, auth/store.go, auth/store_test.go, embed/config.go, embed/etcd.go, etcdmain/config.go, etcdmain/help.go, etcdserver/config.go, etcdserver/server.go
auth: Customize simpleTokenTTL settings.
simple Token TTL default value is auth.simpleTokenTTL = 5 * time.Minute.
Sometimes, this value is not sufficient for use, I hope it can be given to the user to customize the setting.
Fixes #11978
=> auth: Customize the settings of simpleTokenTTL.

CHANGELOG-3.5.md, etcdmain/grpc_proxy.go, proxy/grpcproxy/watch.go, proxy/grpcproxy/watch_broadcast.go, proxy/grpcproxy/watch_broadcasts.go, proxy/grpcproxy/watcher.go
etcd version 3.4.9,recently we met a grpc proxy hang bug when broadcast failed to cancel a watcher. 
watchProxyStream will hold watchRanges global mutex lock all the time if client failed to cancel etcd watchers and it will cause the watch proxy to not work.
it is very difficult to troubleshooting when grpc proxy does not work,so I also add a zap logger for watch proxy.
```
1327935-goroutine 701608 [chan receive, 11 minutes]:
1327936-go.etcd.io/etcd/proxy/grpcproxy.(*watchBroadcast).stop(0xc069bdd200)
1327937-	/tmp/etcd-release-3.4.9/etcd/release/etcd/proxy/grpcproxy/watch_broadcast.go:151 +0x60
1327938-go.etcd.io/etcd/proxy/grpcproxy.(*watchBroadcasts).delete(0xc089d2f9b0, 0xc0d1534300, 0x0)
1327939-	/tmp/etcd-release-3.4.9/etcd/release/etcd/proxy/grpcproxy/watch_broadcasts.go:114 +0x164 …
```
=> proxy/grpcproxy: fix grpc proxy hang when broadcast failed to cancel a watcher

Documentation/op-guide/gateway.md, etcdmain/gateway.go
=> doc: add TLS related warnings

etcdserver/api/capability.go, etcdserver/api/membership/cluster.go, etcdserver/api/membership/cluster_test.go, etcdserver/api/membership/downgrade.go, etcdserver/api/membership/downgrade_test.go, etcdserver/cluster_util.go, etcdserver/cluster_util_test.go, etcdserver/server.go, etcdserver/v3_server.go
4th step of #11716.
The PR adjusted downgrade version latch to server. Previously, cluster will not allow lower version member to join in. With downgrade, the cluster can open such latch if downgrade is enabled.
Based on the discussion [here](https://github.com/etcd-io/etcd/issues/11385), the cluster only allows member with downgrade target version to join in during downgrading.
=> [Etcd downgrade] Apply downgrade policy to server

auth/store.go, auth/store_test.go, clientv3/integration/user_test.go
Cherry pick of #12005 on release-3.3.
#12005: auth: return incorrect result 'ErrUserNotFound' when client
=> Automated cherry pick of #12005

etcdmain/gateway.go
release-3.4 is failed to pass fmt/govet test. 
```
etcdmain/gateway.go:139:11: declaration of "err" shadows declaration at line 96
The command "case "${TARGET}" in
```
https://travis-ci.com/github/etcd-io/etcd/jobs/352631586
=> etcdmain: fix shadow error

clientv3/watch.go, integration/v3_watch_test.go
Cherry pick of #11850 on release-3.4.
#11850: clientv3: cancel watches proactively on client context
=> Automated cherry pick of #11850

wal/decoder.go, wal/wal.go, wal/wal_test.go
Cherry pick of #11793 on release-3.4.
#11793: wal: check out of range slice in "ReadAll", "decoder"
=> Automated cherry pick of #11793

mvcc/backend/backend.go, mvcc/backend/read_tx.go
backend: Create base type for readTx and concurrentReadTx
Eliminate duplicate function(s) between these 2 types and instead use function written as part of base type
=> Create base type for readTx and concurrentReadTx

mvcc/watchable_store.go
Cherry pick of #11987 on release-3.3.
#11987: mvcc: chanLen 1024 is to biger,and it used more memory. 128
=> Automated cherry pick of #11987

CHANGELOG-3.5.md, etcdserver/api/v3rpc/interceptor.go
recently, In the process of troubleshooting the etcd request timeout, I encountered the following problems:
1. Slow query (large response packet) Although the warn log will be printed when apply takes more than 100ms, but lack of remote peer info, it is not convenient to quickly locate the source of the call.
2. Like the [Authenticate interface](https://github.com/etcd-io/etcd/blob/master/etcdserver/v3_server.go#L428) does not go through the apply process, there is no available log for its latency(no warn apply log,no trace log). issue #11826  has the same feedback.
Adjusting the log level to debug can solve the above problems, but the production environment needs to be changed
and performance will drop sharply.
This pr will print expensive request information in grpc interceptor to solve …
=> v3rpc: Log expensive request in UnaryInterceptor

etcdmain/grpc_proxy.go
Cherry pick of #12092 on release-3.4.
#12092: etcdmain: let grpc proxy warn about insecure-skip-tls-verify
=> Automated cherry pick of #12092

etcdmain/grpc_proxy.go, etcdserver/api/etcdhttp/metrics.go, proxy/grpcproxy/metrics.go
grpcproxy does not register self metrics handler, there is no way to get eventsCoalescing/cacheKeys,etc metrics.
this pr registers metrics handler on '/proxy/metrics'.
=> *: register metrics handler for grpcproxy self

pkg/fileutil/fileutil.go
Cherry pick of #11997 on release-3.3.
#11997: pkg/fileutil: print desired file permission in error log
=> Automated cherry pick of #11997

etcdmain/etcd.go, pkg/transport/listener.go
os.MkdirAll creates directory before umask so make sure that a desired
permission is set after creating a directory with MkdirAll.
Added some additional logging as well.
=> pkg: consider umask when use MkdirAll

etcdmain/etcd.go, pkg/transport/listener.go
Cherry pick of #12018 on release-3.3.
#12018: pkg: consider umask when use MkdirAll
=> Automated cherry pick of #12018

Documentation/etcd-mixin/mixin.libsonnet, Documentation/etcd-mixin/test.yaml, Documentation/op-guide/etcd3_alert.rules, Documentation/op-guide/etcd3_alert.rules.yml
A cluster with three members could see three leader changes during a healthy rolling reboot, and we don't want to alert on that.  Growing to 4 reduces false-alarms for clusters with three or fewer members, and that's probably most clusters.  It will also slightly increase the risk of false-negatives, but if the cluster is struggling with high latency, it seems likely that it would quickly pass the new threshold too.
The hard-coded threshold means that we are still likely to get false-positives during rolling reboots of clusters with four or more members.  Ideally we'd scale this with the cluster size, or something, but I'm not sure how to do that.  Three members is the minimum size for high availability, so reducing false positives for that case seems worth addressing even if we leave …
=> Documentation/etcd-mixin: Raise etcdHighNumberOfLeaderChanges threshold to 4

CHANGELOG-3.5.md, etcdmain/grpc_proxy.go, etcdserver/api/etcdhttp/metrics.go, proxy/grpcproxy/health.go
When grpcproxy hangs or is overloaded, the watch client will not receive any change event  and cannot detect the proxy failure. We need a health check to remove the abnormal proxy in time.
=> *: add health handler for grpcproxy self

clientv3/client.go, clientv3/client_test.go, etcdserver/api/v3client/v3client.go
Fix for: https://github.com/etcd-io/etcd/issues/12125
`NewCtxClient` is used with Embedded server. This constructor does not create Logger, which is used by other packages, which causes a panic in `func New(s *etcdserver.EtcdServer) *clientv3.Client`
The fix introduces a default no-op logger and allows to copy the logger from the Embed Server, if specified.
=> 12125: panic: zap.Logger is nil in Embed client

Documentation/etcd-mixin/mixin.libsonnet
Before this change, during a reboot in which etcd recovers quickly (e.g. 1 min),
the etcdMembersDown alert tends to fire even when etcd is fully healthy because
the averaging function can take more than 3 minutes to average back down below
the 0.01 threshold.
This change tries to reduce the possibility of a false negative by considering a
shorter (1 min) failure rate window which tends to average down below the
threshold far more quickly (within 1 min). The `for` clause of the alert should
ensure that the alert still fires if the poor conditions are sustained for an
unreasonable overall time (3 min).
=> Documentation: Tweak etcdMembersDown to reduce false negatives

etcdserver/etcdserverpb/raft_internal_stringer.go
Cherry-picked the fix for panic in several k/k e2e tests
Fixed CI job failure
See more details in https://github.com/kubernetes/kubernetes/issues/91937
=> etcdserver: change protobuf field type from int to int64 (#12000)

CHANGELOG-3.4.md, CHANGELOG-3.5.md
Update changelog for #12000 and #12106.
=> CHANGELOG: update from 12000

raft/tracker/progress.go
In raft/tracker/progress.go:
Line 151
```go
if pr.Next < n+1 {
pr.Next = n + 1
}
```
And line 192
```go
if pr.Next = min(rejected, last+1); pr.Next < 1 {
pr.Next = 1
}
```
Obviously we can use the  `max`  function instead of  `if`  condition making the code more elegant.
Thanks for your review!
=> raft: simplify the code in progress.go

raft/quorum/datadriven_test.go
Interchanging the majorities, so it seems to be `JointConfig([2]MajorityConfig{cj, c})` instead.
=> raft: small bug fix in datadriven_test

raft/raft.go, raft/rawnode_test.go
=> raft: correct pendingConfIndex check for AutoLeave

etcdserver/etcdserverpb/raft_internal_stringer_test.go
- Tested conditions that cause "invalid Go type int" panic
Ref: https://github.com/etcd-io/etcd/pull/12106#issuecomment-654152542
=> Add test case for "invalid Go type int" panic

wal/record_test.go
Fix format error "avoid using reflect.DeepEqual with errors", replace reflect.DeepEqual with errors.Is
=> wal: Fix format error avoid using reflect.DeepEqual with errors

raft/raft.go, raft/raft_test.go
=> raft: check pending conf change before campaign

Documentation/etcd-mixin/mixin.libsonnet
With aggregations using `by`, all additional target labels that a user
might have configured, are aggregated away. However, those target
labels are useful for e.g. alert routing. With this commit, nothing
should change for vanilla job/instance target labels, but whoever has
more target labels can now still make use of them.
=> Documentation/etcd-mixin: Reformulate alerting rules to use `without` rather than `by`

raft/log.go, raft/raft.go, raft/raft_test.go, raft/rawnode.go
If a node starts campaign without applying the snapshot data, loading entries can fail. This can happen when testing transfer leader after snapshot.
This commit is extracted from #12134. Should also fix the issue reported in [comment](https://github.com/etcd-io/etcd/pull/12134#discussion_r459394987).
@xiang90 PTAL
=> raft: fix panic when campaign with snapshot

Documentation/learning/lock/client/client.go
In Documentation/learning/lock/client/client.go,
`func main` forgets `locker.Unlock()` before return.
The fix is to add `defer locker.Unlock()`.
=> Documentation/learning/lock/client: add defer Unlock

etcdserver/api/rafthttp/http.go
**change: etcdserver/api/rafthttp/http.go**
```
conn := &outgoingConn{
t:       t,
Writer:  w,
Flusher: w.(http.Flusher),
Closer:  c,
localID: h.tr.ID,
// peerID: h.id,
peerID:  from,
}
```
the peerID should be changed to **'from'** that comes from the client.
**Why:**
when streamHandler is created at **etcdserver/api/rafthttp/transport.go**
```
// etcdserver/api/rafthttp/transport.go
func (t *Transport) Handler() http.Handler {
...
streamHandler := newStreamHandler(t, t, t.Raft, t.ID, t.ClusterID)
...
}
// etcdserver/api/rafthttp/http.go
func newStreamHandler(t *Transport, pg peerGetter, r Raft, id, cid types.ID) http.Handler {
h := &streamHandler{
...
tr:         t,
...
id:         id,
...
}
...
}
```
**h.id** is same as the **h.tr.id**.
**Log from etcdserver/api/rafthttp/stream.go:** …
=> rafthttp: fix streamHandle outgoingConn peerID

Documentation/etcd-mixin/mixin.libsonnet, Documentation/etcd-mixin/test.yaml
Before this change, the default window for the etcdMembersDown network failure
rate function was recently changed to 1 minute. While this helps detect a etcd
recovery more quickly, it depends on scrape intervals of <= 15s to collect
sufficient data points for the rate function. In practice, an interval of >= 30s
is more typical, which causes the rate function to be less accurate.
This patch increases the window to 2m, which is a compromise between the
original value of 3m and the 1m change introuced with 2aa5684, and should
accomodate more typical scrape intervals.
To offset the window change and to further improve the chance that the alert
will only fire when etcd is truly dead, this patch changes the `for` clause from
3m to 10m. The rationale is as follows:
1. There can be significant …
=> Documentation: Further improve etcdMembersDown alert

CHANGELOG-3.5.md, security/README.md
Update the changelog for recently added audit report. Also mention the
report in the security readme.
=> CHANGELOG: update with added audit report

clientv3/client.go, clientv3/integration/user_test.go
The test is vary flaky on Travis.
Seems that since (https://github.com/etcd-io/etcd/issues/7724) the
client is expected to simply ignore whether server is in AuthDisabled
mode even if the user supplies credentials.
The tests used to:
* use very large cluster (10 nodes)
* set very low timeout (1 sec)
Such setup led to frequent deadlineExceed errors or following failures:
=== RUN   TestGetTokenWithoutAuth
{"level":"warn","ts":"2020-08-04T16:50:48.686+0200","caller":"clientv3/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"endpoint://client-35573307-1ee5-441b-acc7-d073f0bd7de5/localhost:69820396562031027440","attempt":0,"error":"rpc error: code = Unavailable desc = etcdserver: leader changed"}
user_test.go:151: other errors:etcdserver: leader changed
--- FAIL: …
=> clientv3/integration: Reduce flakines of TestGetTokenWithoutAuth

functional/tester/cluster_test.go
The test seems to be failing in the master branch since: https://github.com/etcd-io/etcd/commit/f1c7fd3d53b028c96bab7b35920bd2927db84f20
Failure before fix with the new formatting that allows to spot the differences:
```
--- FAIL: Test_read (0.00s)
cluster_test.go:269: exp != cfg:
expected &{lg:<nil> agentConns:[] agentClients:[] agentStreams:[] agentRequests:[] testerHTTPServer:<nil> Members:[EtcdExec:"./bin/etcd" AgentAddr:"127.0.0.1:19027" FailpointHTTPAddr:"http://127.0.0.1:7381" BaseDir:"/tmp/etcd-functional-1" EtcdPeerProxy:true EtcdClientEndpoint:"127.0.0.1:1379" Etcd:<Name:"s1" DataDir:"/tmp/etcd-functional-1/etcd.data" WALDir:"/tmp/etcd-functional-1/etcd.data/member/wal" HeartbeatIntervalMs:100 ElectionTimeoutMs:1000 ListenClientURLs:"https://127.0.0.1:1379" …
```
=> functional/tester: Update cluster_test.go to reflect functional.yaml

clientv3/example_test.go, clientv3/main_test.go, integration/embed/embed_test.go, pkg/testutil/leak.go
The source of problem was the fact that multiple tests were creating
their clusters (and some of them were setting global grpclog).
If the test was running after some other test that created HttpServer
(so accessed grpclog), this was reported as race.
Tested with:
go test ./clientv3/. -v "--run=(Example).*" --count=2
go test ./clientv3/. -v "--run=(Test).*" --count=2
go test ./integration/embed/. -v "--run=(Test).*" --count=2
=> integration: Fix flakes due to .setupLogging race.

CHANGELOG-3.5.md, embed/etcd.go, etcdserver/api/etcdhttp/base.go, etcdserver/api/etcdhttp/metrics.go, etcdserver/api/v2http/client.go
etcd v2 is closed by default since 3.4, but the health check currently uses v2 QGet, the timeout is only 1 second, it is easier to time out when the load increases slightly.
this pr checks health by using v3 range request and its corresponding timeout. if the user enables v2, it will compatible with old logic.
=> *: check health by using v3 range request and its corresponding timeout

etcdserver/apply.go
Fix Issue #12175. 
For the compact RPC Method, returning nil and ErrCompacted are both successful .
=> etcdserver: ignore ErrCompacted error

etcdserver/api/v2store/store_test.go, wal/wal_test.go
Fixes following problems during "./etcd# go test ./..." build:
> go.etcd.io/etcd/v3/etcdserver/api/v2store_test
etcdserver/api/v2store/store_test.go:847:24: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
> go.etcd.io/etcd/v3/wal
wal/wal_test.go:242:68: conversion from int to string yields a string of one rune, not a string of digits (did you mean fmt.Sprint(x)?)
=> etcdserver, wal: Fix tests unintended CASTing of int->String.

CHANGELOG-3.5.md, etcdserver/metrics.go, pkg/runtime/fds_linux.go
No need to count when we just want the count.
And expose it via metrics that can be used for setting up the monitoring and alarms:
*(Prometheus exposes similar ones, while os_fd_... are the ones perceived by etcd)*
```
...
os_fd_limit 120000
os_fd_used 14
process_cpu_seconds_total 0.31
process_max_fds 120000
process_open_fds 17
...
```
=> *: optimize runtime.FDUsage + add OS level FD metrics

etcdserver/etcdserverpb/raft_internal_stringer.go
Cherry pick of #12106 on release-3.3.
#12106: etcdserver: change protobuf field type from int to int64
fix #12156 
@jingyih @xiang90  @ptabor @YoyinZyc
=> Automated cherry pick of #12106
